strict namespace Logger
{
	void LogActivator(str message)
	{
		LogTo(message, PlayerNumber());
	}
	
	void LogExcept(str message, int id)
	{
		for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
		{
			// Skip the given id.
			if (i == id)
				continue;
			
			// Skip missing player.
			if (!PlayerInGame(i) && !PlayerIsSpectator(i))
				continue;
			
			LogTo(message, i);
		}
	}
	
	void LogBold(str message)
	{
		// Serverside, log to server console.
		if (BCSUtils::IsServerOnly())
			Log(s:message);

		// Offline and direct logging is enabled.
		// We can log directly offline.
		if (ZH2Lib::GetOfflineDirectLogging() && !IsNetworkGame())
		{
			Log(s:message);
			return;
		}
		
		if(!NamedSendNetworkString("LoggerLib_LogOnClientInt", message))
			PrintError("Failed to invoke LoggerLib_LogOnClientInt. Message: '" + message + "'.");
	}
	
	void LogTo(str message, int clientId)
	{
		// Log directly to the server if we target it.
		if (clientId == -1)
		{
			Log(s:message);
			return;
		}

		if (!PlayerInGame(clientId))
			return;
		
		// Don't send to bots.
		if (PlayerIsBot(clientId))
			return;
		
		// LogTo must point to the client if called clientside. Otherwise ignore it.
		if (BCSUtils::IsClient() && clientId != ConsolePlayerNumber())
			return;
		
		// Already clientside, so we do not need to do networking.
		// Calling a script because we do want to ensure the log is send when the console player is the activator.
		if (BCSUtils::IsClient())
		{
			if (!ACS_NamedExecuteAlways("LoggerLib_LogOnClientString", 0, message))
				PrintError("Failed to invoke LoggerLib_LogOnClientString. Message: '" + message + "'.");
			return;
		}
		
		if(!NamedSendNetworkString("LoggerLib_LogOnClientInt", message, clientId))
			PrintError("Failed to invoke LoggerLib_LogOnClientInt on client id " + str(clientId) + ". Message: '" + message + "'.");
	}
}