#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    #define MAPBLOCKCOLUMNS 3
    #define MAPBLOCKHORIZONTALSPACING 200
    #define MAPBLOCKVERTICALSPACING 100
    #define MAPBLOCKWIDTH 150.0
    #define MAPBLOCKHEIGHT 90.0

    #define MAPNAME_WRAPLENGTH 18

    internal void DrawMapList(fixed x, fixed y)
    {
        int id = HUD_SUMMARYMAPLIST;

        fixed GetMapX(int offset)
        {
            int col = offset % MAPBLOCKCOLUMNS;
            return x + fixed(col * MAPBLOCKHORIZONTALSPACING);
        }
        fixed GetMapY(int offset)
        {
            int row = offset / MAPBLOCKCOLUMNS;
            return y - fixed(row * MAPBLOCKVERTICALSPACING);
        }

        // Hardcoded columns.
        // The `Next map` option is disabled when we have no maps in rotation.
        // The `Random map` option is disabled when we have no votable maps.
        bool nextMapPickEnabled = GetMapRotationSize() > 0;
        bool randomMapPickEnabled = ZH2Game::GameContext.VotableMapCount > 0;
        int offset = 0;
        id = DrawMapBlock(id, true, GetMapX(offset), GetMapY(offset), offset++, "Replay map", "", "VIBACK", "VIRESTRT");
        id = DrawMapBlock(id, nextMapPickEnabled, GetMapX(offset), GetMapY(offset), offset++, "Next map", "", "VIBACK", "VINEXT");
        id = DrawMapBlock(id, randomMapPickEnabled, GetMapX(offset), GetMapY(offset), offset++, "Random map", "", "VIBACK", "VIRANDOM");

        // Draw remaining maps.
        for (int i = 0; i < ZH2Game::GameContext.VotableMapCount; ++i)
        {
            int mapIndex = ZH2Game::GameContext.VotableMaps[i];
            str header = GetMapRotationInfo(mapIndex, MAPROTATION_LUMPNAME);

            str label = GetMapRotationInfo(mapIndex, MAPROTATION_NAME);
            str graphic = "VIBACK";

            // Map was not found in the list of parsed maps, proceed to display a basic graphic with the lump name.
            int parsePosition = Map::GetParsedMapPosition(mapIndex);
            if (parsePosition == -1)
            {
                id = DrawMapBlock(id, true, GetMapX(offset), GetMapY(offset), offset++, header, label, graphic);
                continue;
            }

            str replacementLabel = Map::GetMapLabel(parsePosition);
            if (replacementLabel != (raw)0)
                label = replacementLabel;

            str replacementGraphic = Map::GetMapGraphic(parsePosition);
            if (replacementGraphic != (raw)0)
                graphic = replacementGraphic;

            bool isNew = Map::GetMapIsNew(parsePosition);
            bool isLegacyMap = Map::GetMapIsLegacyMap(parsePosition);
            id = DrawMapBlock(id, true, GetMapX(offset), GetMapY(offset), offset++, header, label, graphic, (raw)0, isNew, isLegacyMap);
        }
    }

    internal int DrawMapBlock(int id, bool enabled, fixed x, fixed y, int offset, str header, str label, str graphic, str iconGraphic = (raw)0, bool isNew = false, bool isLegacyMap = false)
    {
        bool isVotedTimer = RoundTimer::GetActiveTimerKnownType() == RoundTimer::TIMERVOTED;

        // Do not draw if the offset doesn't match the picked map.
        if (isVotedTimer && Map::GetFinalVotedMapIndex() != offset)
            return id;

        fixed cursorX = BCSUTILS::Floor(BCSUTILS::CursorX());
        fixed cursorY = BCSUTILS::Floor(BCSUTILS::CursorY());

        fixed graphicX1 = x - MAPBLOCKWIDTH * 0.5;
        fixed graphicX2 = x + MAPBLOCKWIDTH * 0.5;
        fixed graphicY1 = y;
        fixed graphicY2 = y - MAPBLOCKHEIGHT;

        // Check hover state unless the map block is not enabled (automatically also prevents clicking on it).
        bool isOver = enabled
            && cursorX > graphicX1 && cursorX < graphicX2
            && cursorY < graphicY1 && cursorY > graphicY2;

        DebugDrawXY(graphicX1, graphicY1, CR_GOLD);
        DebugDrawXY(graphicX2, graphicY1, CR_GOLD);
        DebugDrawXY(graphicX1, graphicY2, CR_GOLD);
        DebugDrawXY(graphicX2, graphicY2, CR_GOLD);

        bool clientPicked = Map::GetVotedMapIndex() == offset;
        int pickCount = Map::GetMapVoteCount(offset);

        // Base alpha for everything
        fixed baseAlpha = isOver || isVotedTimer ? 1.0 : 0.6;

        // The graphic is slighly more transparent for graphics.
        fixed graphicAlpha = isOver || isVotedTimer ? 0.7 : 0.3;

        // Reduce the alpha of everything if not enabled.
        if (!enabled)
        {
            baseAlpha = 0.5;
            graphicAlpha = 0.2;
        }

        // Alpha for pulsating graphics
        fixed speed = 0.2;
        fixed pulsatingAlpha = baseAlpha * (0.5 + 0.5 * Sin((2.0 * BCSUtils::PI) * speed * (fixed(Utils::GetSynchronizedTimer()) / 35.0)));
        fixed scale = ZH2Game::GetHudSummaryScale();

        BCSUtils::HudSetAlpha(baseAlpha);
        BCSUtils::HudSetTextColor(CR_WHITE);

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetAlpha(graphicAlpha);
        BCSUtils::HudSetScale(0.3 * scale);
        BCSUtils::HudDrawImage(--id, graphic);
        DebugDraw();

        str borderGraphic = clientPicked ? "VIPICKED" : "VINPICKD";
        BCSUtils::HudDrawImage(--id, borderGraphic);
        DebugDraw();

        if (iconGraphic != (raw)0)
        {
            BCSUtils::HudSetPoint(x, y - 30.0);
            BCSUtils::HudSetAlpha(graphicAlpha);
            BCSUtils::HudDrawImage(--id, iconGraphic);
            DebugDraw();
        }

        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetAlpha(baseAlpha);

        if (header != "" && isOver || clientPicked || isVotedTimer)
        {
            BCSUtils::HudSetPoint(x, y - 20.0);
            BCSUtils::HudSetFont("BigFont");
            BCSUtils::HudDrawText(--id, header);
            DebugDraw();
        }

        if (label != "")
        {
            // We want to make sure the map name does not exceed the boundaries of the box.
            str wrappedLabel = Utils::WrapString(label, MAPNAME_WRAPLENGTH);

            // We should reset the alignment for this so the label does not offset weirdly.
            BCSUTILS::HudSetAlignment(BCSUTILS::HUD_ALIGN_CENTER, BCSUTILS::HUD_ALIGN_CENTER);
            
            BCSUtils::HudSetPoint(x, y - 10.0);
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudDrawText(--id, wrappedLabel);
            DebugDraw();

            BCSUTILS::HudSetAlignment(BCSUTILS::HUD_ALIGN_CENTER, BCSUTILS::HUD_ALIGN_BOTTOM);
        }

        // Properties are strings that draw below eachother based on availability.
        // We don't draw them if the block is not enabled.
        if (enabled)
        {
            fixed propertiesY = y - 70.0;
            BCSUtils::HudSetPoint(x, propertiesY);
            BCSUtils::HudSetTextColor(clientPicked ? CR_GREEN : CR_WHITE);
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudDrawText(--id, str(pickCount) + "/" + str(BCSUtils::ClientCount() - BCSUtils::BotCount()));
            DebugDraw();

            propertiesY += 10.0;

            if (isLegacyMap)
            {
                BCSUtils::HudSetAlpha(pulsatingAlpha);
                BCSUtils::HudSetPoint(x, propertiesY);
                BCSUtils::HudSetTextColor(CR_GOLD);
                BCSUtils::HudSetFont("SmallFont");
                BCSUtils::HudDrawText(--id, "legacy map!");
                BCSUtils::HudSetAlpha(baseAlpha);
                DebugDraw();
                
                propertiesY += 10.0;
            }

            if (isNew)
            {
                BCSUtils::HudSetAlpha(pulsatingAlpha);
                BCSUtils::HudSetPoint(x, propertiesY);
                BCSUtils::HudSetTextColor(CR_ORANGE);
                BCSUtils::HudSetFont("SmallFont");
                BCSUtils::HudDrawText(--id, "new!");
                BCSUtils::HudSetAlpha(baseAlpha);
                DebugDraw();
            }
        }

        // Block is unavailable, inform the user.
        if (!enabled)
        {
            BCSUtils::HudSetTextColor(CR_RED);
            BCSUtils::HudSetPoint(x, y - 10.0);
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudDrawText(--id, "Can't pick");
            DebugDraw();
        }

        // Show a countdown on the selected map if we are on cooldown and a map was not yet picked.
        int tics = Map::GetPickCooldownTics();
        if (isOver && tics > 0 && !isVotedTimer)
        {
            str countdownLabel = Utils::FormatTics(tics, true);
            BCSUtils::HudSetPoint(x, y - 40.0);
            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudDrawText(--id, countdownLabel);
            DebugDraw();
        }

        // Clicked, we don't bother checking if it worked.
        if (isOver && BCSUTILS::KeyPressed(BT_ATTACK))
            Map::VotePickMapClientside(offset);

        return id;
    }
}