#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Full list of CVars defined in the code.
// Used by both the internal code and as externed data, as a shared file.
// This also provides an easy way to define CVar values only once instead of defining both its core function + extern function.

strict namespace CVar
{
    // ZE12M
    CVAR_SV_INT_CLAMPED(Ze12MFlow, 0, 3)
    CVAR_CL_BOOL(Ze12MDebug)

    // ZE13M
    CVAR_SV_INT_CLAMPED(Ze13MFlow, 0, 3)
    CVAR_CL_BOOL(Ze13MDebug)

    // ZM06M
    CVAR_SV_INT_CLAMPED(Zm06MEvent, 0, 4)

    // ZM31M
    CVAR_SV_INT_CLAMPED(Zm31MEvent, 0, 3)
    CVAR_SV_INT_CLAMPED(Zm31MEventTics, 350, 21000)
    CVAR_CL_BOOL(Zm31MDebug)
}
