#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Power
{
    // Holds the final factors to apply to the player.
    internal fixed _buildFactors[MAX_POWER_TYPES];

    // Holds a debug message to display when recalculating powers.
    internal str _logFactors[MAX_POWER_TYPES];

    internal void Tic()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();
        int id = PlayerNumber();

        // Check if the activator's powers have expired.
        bool hasExpired = false;

        str logMessage;
        BuildMsg(logMessage = StrParam())
        {
            Append(s:"Power(s) expired of " + BCSUtils::PlayerName(id) + ": ");

            for (int i = 0; i < ZH2Game::PersistingGameContext.PowerCollection.Size; ++i)
            {
                if (!GetPlayerHasPower(id, i))
                    continue;

                // If the player has the power but no tics, we need to take away the power.
                if (GetPlayerPowerTicsLeft(id, i) > 0)
                    continue;

                BCSUtils::SetActorInventory(Identity::GetTid(id), GetItemName(i), 0);

                if (hasExpired)
                    Append(s:", ");

                hasExpired = true;
                Append(s:"\cd" + GetPowerName(i) + "\cj");
            }

            Append(s:".");
        }

        // Something expired
        if (hasExpired)
        {
            Logger::LogDebug(LOGSOURCE , logMessage);
            RecalculatePowers();

            // Send an event unless the round ended.
            // No need to send it in that case.
            if (Round::GetActiveKnownRoundState() < Round::STATEENDING)
                Event::SendPowerExpired(id);
        }
    }

    internal void RecalculatePowers() { RecalculatePlayerPowers(PlayerNumber()); }
    internal void RecalculatePlayerPowers(int id)
    {
        // Set initial factor values.
        for (int i = 0; i < MAX_POWER_TYPES; ++i)
            _buildFactors[i] = 1.0;

        // Special factor values.
        fixed defaultSpeedValue = Player::GetPlayerIsZombie(id) ? 1.2 : 1.0;
        fixed defaultJumpValue = 8.0;
        _buildFactors[POWERTYPE_SPEED] = defaultSpeedValue;
        _buildFactors[POWERTYPE_JUMP] = defaultJumpValue;

        // Set initial log factor values
        for (int i = 0; i < MAX_POWER_TYPES; ++i)
            _logFactors[i] = "Setting power factor \cd" + GetPowerFactorName(i) + "\cj of player \cd" + BCSUtils::PlayerName(id) + "\cj: \cd" + str(_buildFactors[i]) + "\cj";

        for (int i = 0; i < ZH2Game::PersistingGameContext.PowerCollection.Size; ++i)
        {
            if (!GetPlayerHasPower(id, i))
                continue;

            for(int j = 0; j < MAX_POWER_TYPES; ++j)
            {
                // We only care about if the default is defined.
                // From there we get whatever value. Overridden or default.
                if (!GetPowerFactorDefined(i, j))
                    continue;

                fixed factor = GetPowerFactorValue(i, j);
                _buildFactors[j] *= factor;
                _logFactors[j] += " * " + str(factor) + "\cj";
            }
        }

        int tid = Identity::GetTid(id);

        // Set the values and possible log the result.
        for(int i = 0; i < MAX_POWER_TYPES; ++i)
        {
            if (PowerFactorHasActorProperty(i))
                SetActorProperty(tid, PowerFactorToActorProperty(i), _buildFactors[i]);

            // Check the new value. If it's the default don't log it.
            fixed defaultValue;
            switch(i)
            {
                case POWERTYPE_SPEED: defaultValue = defaultSpeedValue; break;
                case POWERTYPE_JUMP: defaultValue = defaultJumpValue; break;
                default: defaultValue = 1.0;
            }

            // Store the calculated value on the player.
            SetPlayerCalculatedPowerFactor(id, i, _buildFactors[i]);

            if (_buildFactors[i] == defaultValue)
                continue;

            _logFactors[i] += ". Total: \cd" + str(_buildFactors[i]) + "\cj.";
            Logger::LogDebug(LOGSOURCE, _logFactors[i]);
        }
    }

    internal void ResetPowers()
    {
        ResetPlayerPowers(PlayerNumber());
    }

    internal void ResetPlayerPowers(int id)
    {
        // Track if we took a power from this player. If not, we do not want to recalculate.
        bool hasPower = false;

        // First take all powers from this player.
        for (int i = 0; i < GetPowerSize(); ++i)
        {
            if (!GetPlayerHasPower(id, i))
                continue;

            TakePlayerPower(id, i, false);
            hasPower = true;
        }

        // Secondly recalculate the new properties so they reset properly, but only if they had a power.
        if (hasPower)
            RecalculatePlayerPowers(id);
    }
}
