#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Power
{
    #define MAX_POWERS 20

    struct PowerCollectionContextT
    {
        // Set to `true` if we defined the collection.
        bool Defined;

        PowerContextT Collection[MAX_POWERS];
        int Size;
    };

    struct PowerContextT
    {
        str Name;
        str HudGraphic;
        int MaxTics;
        fixed SpeedModifier;
        fixed JumpModifier;
        fixed DamageFactor;
        fixed DamageMultiplier;
    };

    enum KnownPowerTypeT : int
    {
        POWERFIREBURNING,
        POWERACIDBURNING,
        POWERSPRINTING,
        POWERPANICKING,
        POWERCAFFEINE,

        POWERZOMBIEPROTECT,
        POWERHUMANIMMUNITY,

        POWERREWARDHUMANSPEED,
        POWERREWARDHUMANWEAPONUPGRADE,
        POWERREWARDZOMBIESPEED,
        POWERREWARDZOMBIEJUMP,
        POWERREWARDZOMBIEVULNERABILITY,
    };
}