#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define SCRIPT_PARSE_PERSISTING_FOOTSTEP_DEFS "zh2_internal_parse_footstep_defs_client"

#define SCRIPT_PARSE_PERSISTING_LOGGER_DEFS_CLIENTSIDE "zh2_internal_parse_logger_defs_client"
#define SCRIPT_PARSE_PERSISTING_LOGGER_DEFS_SERVERSIDE "zh2_internal_parse_logger_defs_server"

strict namespace LibIO
{
    extern void ParseFootstepDefsClientside();
    extern void ParseLoggerDefClientside();
    extern void ParseLoggerDefServerside();
}