#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    internal void AfkPreventionTicServer()
    {
        if (!PlayerInGame(PlayerNumber()) || PlayerIsBot(PlayerNumber()))
            return;

        Round::KnownRoundStateT roundState = Round::GetActiveKnownRoundState();
        if (roundState != Round::STATECOUNTDOWN && roundState != Round::STATEPLAYING)
            return;

        if (!GetHasMovedThisMap())
        {
            if (Utils::GetIsMoving())
            {
                SetHasMovedThisMap(true);
                return;
            }

            // On 0 we don't want AFK prevention at map start. Otherwise it would be instant.
            int seconds = ZH2Game::GetAfkMoveAtRoundStartBeforeSeconds();
            if (seconds == 0)
                return;

            int playTics = GetPlayTics();
            if (seconds * 35 > playTics)
                return;

            // Kick and send to buffer so the Game side can log a message.
            KickFromGame(PlayerNumber(), "inactivity");
            Game::SetWasAfkKicked(true);
        }
    }

    // Clientside we also check input so we can tell the client if he will be kicked.
    internal void AfkPreventionTicClient()
    {
        // Online-only
        if (!IsNetworkGame())
            return;

        if (!PlayerInGame(PlayerNumber()) || PlayerIsBot(PlayerNumber()))
            return;

        if (!GetHasMovedThisMap() && Utils::GetIsMoving())
            SetHasMovedThisMap(true);
    }

    internal bool GetHasMovedThisMap()
    {
        return GetPlayerHasMovedThisMap(PlayerNumber());
    }

    internal bool GetPlayerHasMovedThisMap(int id)
    {
        return ZH2Game::GameContext.Players[id].AfkPreventionContext.HasMovedThisMap;
    }

    internal void SetHasMovedThisMap(bool set)
    {
        SetPlayerHasMovedThisMap(PlayerNumber(), set);
    }

    internal void SetPlayerHasMovedThisMap(int id, bool set)
    {
        ZH2Game::GameContext.Players[id].AfkPreventionContext.HasMovedThisMap = set;
    }

    internal int GetTicsUntilKick()
    {
        return GetPlayerTicsUntilKick(PlayerNumber());
    }

    internal int GetPlayerTicsUntilKick(int id)
    {
        int seconds = ZH2Game::GetAfkMoveAtRoundStartBeforeSeconds();
        if (seconds == 0)
            return 0;

        int playTics = GetPlayerPlayTics(id);
        return BCSUtils::Max(0, (seconds * 35) - playTics);
    }
}
