#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    internal void InitializeHealth()
    {
        EventBus::AddCallbackByScriptName(EVENTPLAYERSPECIECHANGED, "zh2_internal_event_specie_changed_health");
    }

    script "zh2_internal_event_specie_changed_health" (raw packetStr)
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerSpecieChanged(packet);
        int id = Event::GetReceiveData(0);
        SetPlayerHealth(id, BCSUtils::GetActorHealth(Identity::GetTid(id)));
    }

    internal int GetHealth()
    {
        return GetPlayerHealth(PlayerNumber());
    }

    internal int GetPlayerHealth(int id)
    {
        return ZH2Game::GameContext.Players[id].HealthContext.Health;
    }

    internal void SetHealth(int health)
    {
        SetPlayerHealth(PlayerNumber(), health);
    }

    internal void SetPlayerHealth(int id, int health)
    {
        ZH2Game::GameContext.Players[id].HealthContext.Health = health;
    }
}
