#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    // The current heartbeat used.
    // The local ticker sets this because this checks what heartbeat should be played.
    // 0 = None, or the normal one.
    // 1 = Dangerous health.
    // 2 = Critical health.
    internal int _heartbeatType = 0;

    internal int _lastHeartbeatLocalTimestamp = 0;
    internal int _nextHeartbeatLocalTimestamp = 0;

    internal int _nextHeartbeatLastTimestamp = 0;

    internal void HeartbeatTicClient()
    {
        // Ignore if the game ended.
        if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
            return;

        if (!Player::GetIsHuman())
            return;

        if (!ZH2Game::GetEnableHurtHeartbeat())
            return;

        _heartbeatType = DetermineHeartbeatType();
        if (Timer() < _nextHeartbeatLocalTimestamp)
            return;

        int tid = ActivatorTid();
        switch(_heartbeatType)
        {
            case 1:
                _nextHeartbeatLocalTimestamp = Timer() + 18;
                _lastHeartbeatLocalTimestamp = Timer();
                ThingSound(tid, "human/HEARTBEATHURT1", 150);
                break;

            case 2:
                _nextHeartbeatLocalTimestamp = Timer() + 14;
                _lastHeartbeatLocalTimestamp = Timer();
                ThingSound(tid, "human/HEARTBEATHURT2", 150);
                break;

            default:
                break;
        }
    }

    internal void LastHeartbeatTicClient()
    {
        if (Timer() < _nextHeartbeatLastTimestamp)
            return;

        // Map is not configured to play a heartbeat.
        if (!GetPlayFinalHeartbeat())
            return;

        if (!ZH2Game::GetEnableFinalHeartbeat())
            return;

        if (Game::HumanCount() != 1)
            return;

        // The final heartbeat can only happen when the game is playing.
        if (Round::GetActiveKnownRoundState() != Round::STATEPLAYING)
            return;

        for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
        {
            if (!PlayerInGame(i))
                continue;

            if (!Player::GetPlayerIsHuman(i))
                continue;

            LastHeartbeatTicPlayerClient(i);
        }
    }

    // Called from the client's loop for each ingame player index.
    internal void LastHeartbeatTicPlayerClient(int id)
    {
        // The final heartbeat is not triggered locally when the console player is the final human and we are playing a hurt heartbeat.
        if (id == ConsolePlayerNumber() && ZH2Game::GetEnableHurtHeartbeat() && _heartbeatType != 0)
            return;

        int tid = Identity::GetTid(id);

        // Console player has a different heartbeat and timestamp.
        if (id == ConsolePlayerNumber())
        {
            ThingSound(tid, "human/HEARTBEATLOCAL", 150);
            _nextHeartbeatLastTimestamp = Timer() + 35;

            // Also set variables for the hurt heartbeat when local, or it will overlap instantly with this heartbeat.
            _nextHeartbeatLocalTimestamp = Timer() + 35;
            _lastHeartbeatLocalTimestamp = Timer();
        }
        else
        {
            ThingSound(tid, "human/HEARTBEATFAR", 150);
            _nextHeartbeatLastTimestamp = Timer() + 35 + 18;
        }
    }

    internal int DetermineHeartbeatType()
    {
        int health = BCSUtils::Max(0, PlayerHealth());

        if (health <= HEALTH_HUMANCRITICAL)
            return 2;
        else if (health <= HEALTH_HUMANDANGEROUS)
            return 1;
        return 0;
    }

    internal int GetHeartbeatType()
    {
        return _heartbeatType;
    }

    internal int GetElapsedLocalHeartbeatTics()
    {
        if (_lastHeartbeatLocalTimestamp == 0)
            return 0;

        return Timer() - _lastHeartbeatLocalTimestamp;
    }

    internal bool GetPlayFinalHeartbeat()
    {
        return ZH2Game::GameContext.MapDetails.PlayFinalHumanHeartbeat;
    }

    internal void SetPlayFinalHeartbeat(bool set)
    {
        ZH2Game::GameContext.MapDetails.PlayFinalHumanHeartbeat = set;
    }
}
