#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    internal void SetInitialZombie(bool set) { SetPlayerInitialZombie(PlayerNumber(), set); }
    internal void SetPlayerInitialZombie(int id, bool set)
    {
        if (!Identity::IsValidID(id))
        {
            Logger::LogError(LOGSOURCE, "Unable to set player as initial zombie. Id " + str(id) + " is not valid.");
            return;
        }

        if (GetPlayerInitialZombie(id) == set) return;
        ZH2Game::GameContext.Players[id].IsInitialZombie = set;
        Logger::LogDebug(LOGSOURCE, (set ? "Added" : "Removed") + " (\cd" + str(id) + "\cj) \cd" + BCSUTILS::PlayerName(id) + "\cj as an initial zombie.");
    }

    internal bool GetInitialZombie() { return GetPlayerInitialZombie(PlayerNumber()); }
    internal bool GetPlayerInitialZombie(int id)
    {
        if (!Identity::IsValidID(id))
        {
            Logger::LogError(LOGSOURCE, "Unable to get player as initial zombie. Id " + str(id) + " is not valid.");
            return false;
        }

        return ZH2Game::GameContext.Players[id].IsInitialZombie;
    }

    internal void SetInitialZombiePreviously(bool set) { SetPlayerInitialZombiePreviously(PlayerNumber(), set); }
    internal void SetPlayerInitialZombiePreviously(int id, bool set)
    {
        VALIDATE_ID_VALID_FUNCTION(id);

        if (GetPlayerInitialZombiePreviously(id) == set)
            return;

        ZH2Game::PersistingGameContext.Players[id].PreviouslyInitialZombie = set;
        Logger::LogDebug(LOGSOURCE, (set ? "Added" : "Removed") + " (\cd" + str(id) + "\cj) \cd" + BCSUTILS::PlayerName(id) + "\cj as a previously initial zombie.");
    }

    internal bool GetInitialZombiePreviously() { return GetPlayerInitialZombiePreviously(PlayerNumber()); }
    internal bool GetPlayerInitialZombiePreviously(int id)
    {
        VALIDATE_ID_VALID_FUNCTION_RETURN(id, false);
        return ZH2Game::PersistingGameContext.Players[id].PreviouslyInitialZombie;
    }

    // Internal because I don't want to expose this when it has `bool` previous.
    // Use the two methods below instead.
    internal int InitialsCountInternal(bool previous, bool includeDead = false)
    {
        int count;
        for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
        {
            // Count optionally allows for including dead players.
            if (!includeDead
                && (!PlayerInGame(i) || !BCSUtils::ActorIsAlive(Identity::GetTID(i))))
            {
                continue;
            }

            bool check = previous
                ? GetPlayerInitialZombiePreviously(i)
                : GetPlayerInitialZombie(i);
            if (!check) continue;

            count++;
        }

        return count;
    }

    internal int InitialZombieCount(bool includeDead = false)
    {
        return InitialsCountInternal(false, includeDead);
    }

    internal int PreviouslyInitialZombieCount(bool includeDead = false)
    {
        return InitialsCountInternal(true, includeDead);
    }
}