#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    internal void MorphPlayerToHuman(int id) { MorphPlayerToClass(id, CLASS_HUMAN); }
    internal void MorphPlayerToZombie(int id) { MorphPlayerToClass(id, CLASS_ZOMBIE); }

    internal void MorphToHuman() { MorphPlayerToHuman(PlayerNumber()); }
    internal void MorphToZombie() { MorphPlayerToZombie(PlayerNumber()); }

    internal void MorphPlayerToClass(int id, str class)
    {
        ACS_NamedExecuteWithResult("zh2_internal_morphplayer", id, class);
    }

    // As we transfer the translation of the player we must set an activator.
    // Therefore this is handled in a separate script.
    script "zh2_internal_morphplayer"(raw idRaw, raw classRaw)
    {
        int id = (int)idRaw;
        str class = (str)classRaw;
        int tid = Identity::GetTid(id);
        if (tid == -1) terminate;

        if (!BCSUtils::ActorIsAlive(tid))
        {
            Logger::LogWarning(LOGSOURCE, "Unable to morph player " + BCSUtils::PlayerName(id) + ": player is not alive.");
            terminate;
        }

        if (CheckActorClass(tid, class))
        {
            Logger::LogWarning(LOGSOURCE, "Unable to morph player " + BCSUtils::PlayerName(id) + ": player is already target class (" + class + ").");
            terminate;
        }

        // If we morph away from the invisible player class, we want to take NothingWeapon.
        if (CheckActorClass(tid, CLASS_INVISIBLE))
            TakeActorInventory(tid, WEAPON_NOTHINGWEAPON_NAME, 1);

        // Morphing doesn't work when a player is invisible.
        if (GetActorProperty(tid, APROP_Invulnerable))
        {
            Logger::LogError(LOGSOURCE, "Failed to set player " + BCSUtils::PlayerName(id) + " into target class (" + class + "). Player is invulnerable.");
            terminate;
        }

        // Mapspot will hold the player's translation so we can migrate it to the new class.
        int translationHolderTid = UniqueTid();
        if (!SpawnForced("mapspot", 0.0, 0.0, 0.0, translationHolderTid))
        {
            Logger::LogError(LOGSOURCE, "Failed to spawn translation mapspot.");
            terminate;
        }

        // Set activator to the morphing player in order to receive the translation.
        if (!SetActivatorToPlayer(id))
        {
            Logger::LogError(LOGSOURCE, "Failed to set player as activator.");
            terminate;
        }

        Thing_SetTranslation(translationHolderTid, -1);

        // Player is not of class InvisiblePlayer, which means they must first be unmorphed (InvisiblePlayer is the base unmorphed variant).
        if (!CheckActorClass(tid, CLASS_INVISIBLE) && !bool(UnMorphActor(tid, (int)true)))
        {
            Logger::LogError(LOGSOURCE, "Failed to unmorph (" + str(tid) + ")" + BCSUtils::PlayerName(id) + " (actor class = " + GetActorClass(tid) + ").");
            terminate;
        }

        // Note mapspot prevents flashes during morphing.
        if (!CheckActorClass(tid, class) && !MorphActor(tid, class, "", 0x7fffffff, MRF_NEWTIDBEHAVIOUR | MRF_LOSEACTUALWEAPON, "mapspot", "mapspot"))
        {
            Logger::LogError(LOGSOURCE, "Failed to morph (" + str(tid) + ")" + BCSUtils::PlayerName(id) + " into target class (" + class + ", actor class = " + GetActorClass(tid) + ").");
            terminate;
        }

        // If we morphed into the invisible player class, we want to give NothingWeapon.
        if (CheckActorClass(tid, CLASS_INVISIBLE))
            GiveActorInventory(tid, WEAPON_NOTHINGWEAPON_NAME, 1);

        // Set activator to the spawned mapspot holding the translation and transfer the translation back.
        if (!SetActivator(translationHolderTid))
        {
            Logger::LogError(LOGSOURCE, "Failed to set translation holder as activator.");
            terminate;
        }

        Thing_SetTranslation(tid, -1);
        Thing_Remove(translationHolderTid);

        Logger::LogDebug(LOGSOURCE, "Player (" + str(tid) + ")" + BCSUtils::PlayerName(id) + " was morphed to class \cd" + GetActorClass(tid) + "\cj.");
    }
}
