#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define MAX_DAMAGE_SOURCES 2
#define MAX_SOFTWARE_TEXTURES 16

// This maximum is for sync purposes.
#define MAX_INITIAL_ZOMBIE_PICK_WEIGHT 254

strict namespace Player
{
    enum PlayerSpecieT : int
    {
        SPECIENONE,
        SPECIEHUMAN,
        SPECIEZOMBIE
    };

    internal enum PlayerTeamT : int
    {
        TEAM_HUMAN,
        TEAM_ZOMBIE,
    };

    internal enum PlayerStateT : int
    {
        STATENONE,
        STATEGONE,
        STATEPLAYING,
        STATEDEAD,
    };

    internal enum PlayerPanicStateT : int
    {
        PANICSTATENONE,
        PANICSTATEPANICKING,
        PANICSTATECALMINGDOWN,
    };

    internal enum ZombieSkinTypeT : int
    {
        ZOMBIESKIN_OLD,
        ZOMBIESKIN_REGULAR,
        ZOMBIESKIN_INITIAL,
    };

    internal enum DamageSourceTypeT : int
    {
        SOURCE_FIRE,
        SOURCE_ACID,
    };

    struct DamageSourceT
    {
        bool Active;
        str SourceActor;
        int OwnerId;
    };

    struct SoftwareTextureT
    {
        str Name;
        int Flags;
    };

    struct SoftwareTextureContextT
    {
        int Size;
        SoftwareTextureT Textures[MAX_SOFTWARE_TEXTURES];
    };

    internal struct HealthContextT
    {
        int Health;
    };

    internal struct StatsContextT
    {
        int HumanKills;
        int ZombieKills;
        int Infects;

        int DamageToPlayers[BCSUtils::MAX_PLAYERS];
    };

    internal struct PlayerAfkPreventionRoundStartContextT
    {
        bool HasMovedThisMap;
    };

    internal struct PlayerLifecycleContextT
    {
        int JoinTic;
    };

    extern bool GetIsZombie();
    extern bool GetPlayerIsZombie(int id);
    extern bool GetIsHuman();
    extern bool GetPlayerIsHuman(int id);
}