#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define MAX_DAMAGE_SOURCES 2

strict namespace Player
{
    #define ITEM_ACTORISUNSOLID "ZH2ActorIsUnsolid"

    enum PlayerSpecieT : int
    {
        SPECIENONE,
        SPECIEHUMAN,
        SPECIEZOMBIE
    };

    internal enum PlayerTeamT : int
    {
        TEAM_HUMAN,
        TEAM_ZOMBIE,
    };

    internal enum PlayerStateT : int
    {
        STATENONE,
        STATEGONE,
        STATEPLAYING,
        STATEDEAD,
    };

    internal enum PlayerPanicStateT : int
    {
        PANICSTATENONE,
        PANICSTATEPANICKING,
        PANICSTATECALMINGDOWN,
    };

    internal enum ZombieSkinTypeT : int
    {
        ZOMBIESKIN_OLD,
        ZOMBIESKIN_REGULAR,
        ZOMBIESKIN_INITIAL,
    };

    internal enum DamageSourceTypeT : int
    {
        SOURCE_FIRE,
        SOURCE_ACID,
    };

    internal enum PlayerSolidStateT : int
    {
        STATE_DEFAULT, // Default setting of being solid, or unsolid if `sv_unblockplayers` / `sv_unblockallies` is enabled.
        STATE_UNSOLID, // Player is explicitly unsolid.
        STATE_GOBACKSOLID, // Player is ready to turn back solid if able.
    };

    struct DamageSourceT
    {
        bool Active;
        str SourceActor;
        int OwnerId;
    };

    extern bool GetIsZombie();
    extern bool GetPlayerIsZombie(int id);
    extern bool GetIsHuman();
    extern bool GetPlayerIsHuman(int id);
}