#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define MAX_DAMAGE_SOURCES 2

#define THRUACTORS_CHECKSPOT_TID 4000
#define THRUACTORS_CHECKSPOT_NAME "ZH2ThruActorsSpotChecker"

strict namespace Player
{
    enum PlayerSpecieT : int
    {
        SPECIENONE,
        SPECIEHUMAN,
        SPECIEZOMBIE
    };

    internal enum PlayerTeamT : int
    {
        TEAM_HUMAN,
        TEAM_ZOMBIE,
    };

    internal enum PlayerStateT : int
    {
        STATENONE,
        STATEGONE,
        STATEPLAYING,
        STATEDEAD,
    };

    internal enum PlayerPanicStateT : int
    {
        PANICSTATENONE,
        PANICSTATEPANICKING,
        PANICSTATECALMINGDOWN,
    };

    internal enum ZombieSkinTypeT : int
    {
        ZOMBIESKIN_OLD,
        ZOMBIESKIN_REGULAR,
        ZOMBIESKIN_INITIAL,
    };

    internal enum DamageSourceTypeT : int
    {
        SOURCE_FIRE,
        SOURCE_ACID,
    };

    internal enum PlayerThruActorsStateT : int
    {
        STATE_DEFAULT, // Default setting. Might still allow walking through players/allies if `sv_unblockplayers` / `sv_unblockallies` is enabled.
        STATE_THRUACTORS, // Player is explicitly allowed to walk through actors.
        STATE_GOBACKDEFAULT, // Player is ready to turn back to the default state if able.
    };

    struct DamageSourceT
    {
        bool Active;
        str SourceActor;
        int OwnerId;
    };

    struct DamageFeedbackInfoT
    {
        // Indicates the tics when the last hit/kill happened.
        int HitFeedbackTic;
        int KillFeedbackTic;

        // Accumulating counter for damage and kills that get reset after enough time passes without an update.
        int DamageCount;
        int KillCount;
    };

    extern bool GetIsZombie();
    extern bool GetPlayerIsZombie(int id);
    extern bool GetIsHuman();
    extern bool GetPlayerIsHuman(int id);
}