#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Player"

#include "specie.acs"
#include "morph.acs"
#include "team.acs"
#include "skin.acs"
#include "inventory.acs"
#include "lock.acs"
#include "name.acs"
#include "power.acs"
#include "state.acs"
#include "stats.acs"
#include "source.acs"
#include "kevlar.acs"
#include "sprint.acs"
#include "panic.acs"
#include "taunt.acs"
#include "softwaremode.acs"
#include "translucentallies.acs"
#include "initialzombie.acs"
#include "heartbeat.acs"

strict namespace Player
{
    void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for player.");
        SetPlayFinalHeartbeat(true);

        EventBus::AddCallbackByScriptName(EVENTPOWEREXPIRED, "zh2_internal_event_player_power_expired");
    }

    void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for player.");
        SetPlayFinalHeartbeat(false);

        EventBus::AddCallbackByScriptName(EVENTPOWEREXPIRED, "zh2_internal_event_player_power_expired");
    }
}

#undef LOGSOURCE