#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{

    internal bool GetOnFire()
    {
        return GetPlayerOnFire(PlayerNumber());
    }

    internal bool GetPlayerOnFire(int id)
    {
        return Power::GetPlayerHasPower(id, Power::POWERFIREBURNING);
    }

    internal bool GetOnAcid()
    {
        return GetPlayerOnAcid(PlayerNumber());
    }

    internal bool GetPlayerOnAcid(int id)
    {
        return Power::GetPlayerHasPower(id, Power::POWERACIDBURNING);
    }
}
