#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    // Replaces common textures only shown in software mode, unless the user is rendering using OpenGL.
    internal void EnsureSoftwareModeTexturesRemoved()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (!BCSUtils::IsOpenGL())
            return;

        if (!ZH2Game::GetRemoveSoftwareTextures())
            return;

        ReplaceTextures("3DOUTLIN", "", NOT_BOTTOM | NOT_TOP | NOT_FLOOR | NOT_CEILING);
        ReplaceTextures("3DOUTLI2", "", NOT_BOTTOM | NOT_TOP | NOT_FLOOR | NOT_CEILING);
    }
}
