#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    // Replaces common textures only shown in software mode.
    internal void EnsureSoftwareModeTexturesRemoved()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (!BCSUtils::IsOpenGL())
            return;

        if (!ZH2Game::GetRemoveSoftwareTextures())
            return;

        // Replace using lump reading.
        // We don't replace `3DOUTLIN` and `3DOUTLI2` because maps actually do use these textures.
        //ReplaceTextures("3DOUTLIN", "", NOT_BOTTOM | NOT_TOP | NOT_FLOOR | NOT_CEILING);
        //ReplaceTextures("3DOUTLI2", "", NOT_BOTTOM | NOT_TOP | NOT_FLOOR | NOT_CEILING);

        for (int i = 0; i < ZH2Game::GameContext.SoftwareTextureContext.Size; ++i)
        {
            str name = ZH2Game::GameContext.SoftwareTextureContext.Textures[i].Name;
            int flags = ZH2Game::GameContext.SoftwareTextureContext.Textures[i].Flags;
            ReplaceTextures(name, "", flags);
        }
    }
}