#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Settings
{
    // Hard cap on the number of requested client settings we allow to be defined.
    #define SETTINGS_CLIENTMAX 50

    // Defines how often we notify the player.
    #define SETTINGS_INFORMEVERYMAPCOUNT 5

    struct RequestedClientSettingT
    {
        str Type;
        str Name;
        int Value;
        str Label;
    };
}