#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace GameLoop
{
    script "zh2_internal_playerloop"(int id)
    {
        Logger::LogDebug(LOGSOURCE, "Player loop started for id \cd" + str(id) + "\cj.");
        while(BCSUtils::PlayerIsConnected(id))
        {
            if (!SetActivatorToPlayer(id))
            {
                Delay(const: 1);
                continue;
            }

            Decorate::TicServer();
            Power::Tic();
            Player::SprintTic();
            Player::PanicTic();
            Player::ZombieTauntTic();
            Player::NameTic();

            if (PlayerSpace::PlayerSpaceTic())
                Sync::SyncPlayers();

            Game::TicActivatorZombieTeleport();

            // Call hook for this tic.
            _playerTicHookData.Id = id;
            Hook::Call(Hook::HOOK_SERVERPLAYERTIC, _playerTicHookData);

            Delay(const: 1);
        }
        Logger::LogDebug(LOGSOURCE, "Player loop ended for id \cd" + str(id) + "\cj.");
    }

    script "zh2_internal_playerloop_client" clientside
    {
        Logger::LogDebug(LOGSOURCE, "Clientside player loop started for id \cd" + str(ConsolePlayerNumber()) + "\cj.");

        while(true)
        {
            // Note, must be in the loop, or it will fail online.
            if (!BCSUtils::SetActivatorToConsolePlayer())
            {
                Delay(const: 1);
                continue;
            }

            Logger::FlushBuffer();
            Game::TicTipsClient();
            Hud::Tic();
            Item::Tic();
            Decorate::TicClient();
            Weather::TicClient();
            RoundTimer::TicClient();
            Game::FullServerTicClient();
            Player::LockTic();
            Player::HeartbeatTicClient();
            Player::LastHeartbeatTicClient();
            Player::TranslucentAlliesTicClient();
            DamageFeedback::DamageFeedbackTicClient();
            Game::ClientDeathCamTic();
            Game::TeamIndicatorTicClient();
            Footstep::FootstepTicClient();
            Damage::FlushClient();

            // Call hook for this tic.
            Hook::Call(Hook::HOOK_CLIENTTIC, null);

            Delay(const: 1);
        }
        Logger::LogDebug(LOGSOURCE, "Clientside player loop ended for id \cd" + str(ConsolePlayerNumber()) + "\cj.");
    }
}