#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace GameLoop
{
    script "zh2_internal_serverloop"
    {
        Logger::LogDebug(LOGSOURCE, "Server loop started.");
        while(true)
        {
            // After a short delay on the play timer, we start tracking the game state and see if it should end.
            if (Round::GetActiveKnownRoundState() == Round::STATEPLAYING && Game::GetPlayTime() > 35)
            {
                // Game should end, one side won or we tied.
                if (Game::UpdateWinningSpecie())
                    Game::EndGame();
            }

            // Online we want to also flush the server log buffer.
            if (IsNetworkGame())
                Logger::FlushBuffer();

            RoundTimer::TicServer();
            Resist::TicServer();
            Game::FullServerTicServer();
            Game::ModifiersTic();

            if (Timer() % 5 == 0)
                AfkPrevention::AfkPreventionBroadcastServer();

            Feature::TicServer();

            // Call hook for this tic.
            Hook::Call(Hook::HOOK_SERVERTIC, null);

            Sync::LibFlushPendingSyncs();
            Sync::FlushPendingSyncs();

            Delay(const: 1);
        }
    }
}