#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawHud()
    {
        switch (GetHudSkin(ConsolePlayerNumber()))
        {
            case ZH2Game::HUDSKIN_DEFAULT: DrawHudDefault(); break;
        }

        DrawSharedHud();
    }

    // Draws the parts of the hud that are not specific to any skin.
    internal void DrawSharedHud()
    {
        bool drawHud = ZH2Game::GetDrawHud();

        if (Round::GetActiveKnownRoundState() == Round::STATEPLAYING)
            DrawFullServerHud();

        if (drawHud && ZH2Game::GetDrawVersionHud())
            DrawVersion();

        if (drawHud && ZH2Game::GetDrawRoundHud())
            DrawRoundHud();

        // All of this is strictly during the playing game.
        if (Round::GetActiveKnownRoundState() < Round::STATEENDING)
        {
            if (drawHud && ZH2Game::GetDrawResistsHud())
                DrawResistsHud();

            if (drawHud && ZH2Game::GetDrawDebugHud())
                DrawDebugHud();

            // NOTE: We do NOT allow drawing of the admin hud during the voting, because it is also clickable.
            if (ZH2Game::GameContext.HasAdminHudOpen)
                DrawAdminHud();

            // Same as the admin hud
            if (ZH2Game::GameContext.HasClientSettingsHudOpen)
                DrawClientSettingsHud();

            if (_clientCameraOnBody && Player::GetOnFire())
                DrawClientSeparateHudFire(FIRETYPENORMAL);

            if (_clientCameraOnBody && Player::GetOnFire() && Timer() % 10 == 0)
                DrawFireBlur();

            if (_clientCameraOnBody && Player::GetOnAcid() && Timer() % 10 == 0)
                DrawAcidBlur();

            if (Game::ClientDeathCameraEnabled() && Game::GetViewingDeathCamera())
                DrawDeathCamHud();

            if (_clientCameraOnBody && drawHud)
                DrawWeaponsHud();

            if (_clientCameraOnBody && drawHud && BCSUtils::ActorIsAlive(ActivatorTid()))
            {
                if (ZH2Game::GetDrawPlayerPowersHud())
                    DrawPlayerPowersHud();

                DrawIdentity();
                DrawInventory();
                DrawBlurHud();
            }

            if (drawHud && ZH2Game::GetDrawGameHud())
                DrawZombieTeleportTime();

            DrawObituaryHud();
            DrawDamageFeedback();
        }

        // Game must be ending and we must have a winning specie in order to draw the ending hud.
        if (Round::GetActiveKnownRoundState() == Round::STATEENDING)
            DrawEndingHud();

        // Game must be ending and we must have a winning specie in order to draw the ending hud.
        if (Round::GetActiveKnownRoundState() == Round::STATEVOTING)
            DrawSummaryHud();

        if (GetCursorEnabled())
            DrawCursor();
    }
}
