#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Hud"

#include "cursor.acs"
#include "drawhud/drawhud.acs"

strict namespace Hud
{
    internal AdminMenuT _currentAdminMenu;

    internal int _debugHudId;
    internal int _drawnHudId;

    // For shaking of the HUD.
    internal fixed _firingSeedAngle = 0.0;
    internal fixed _xShakeOffset = 0.0;
    internal fixed _yShakeOffset = 0.0;

    // The main positioning and scale used when drawing elements.
    internal fixed _hudX,
                   _hudY;

    internal void Tic()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        _debugHudId = HUDID_DEBUG_COORDINATES;
        _drawnHudId = HUDID_BASE;

        UpdateHudShakeOffset();

        DrawHud();
    }

    internal void PrepareHud(fixed x, fixed y, bool addShake)
    {
        _hudX = x;
        _hudY = y;

        if (addShake)
        {
            _hudX += _xShakeOffset;
            _hudY += _yShakeOffset;
        }
    }

    internal fixed GetHudX()
    {
        return _hudX;
    }

    internal fixed GetHudY()
    {
        return _hudY;
    }

    // Helper method to set the hud point based on possible scaling.
    internal void HudSetPointInternal(fixed addX = 0.0, fixed addY = 0.0)
    {
        BCSUtils::HudSetPoint(_hudX + addX, _hudY + addY);
    }

    internal void DebugDraw(fixed x = 0.0, fixed y = 0.0, int color = CR_WHITE)
    {
        if (!ZH2Game::GetDrawDebugCoordinatesHud()) return;

        BCSUtils::HudPushState();
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetTextColor(color);
        
        if (x != 0.0 && y != 0.0)
            BCSUtils::HudSetPoint(x, y);

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudDrawText(_debugHudId--, "*");
        BCSUtils::HudPopState();
    }

    internal bool DrawClickableTextConditional(bool clickable, int id, fixed x, fixed y, fixed width, fixed height, str text)
    {
        if (!clickable)
        {
            BCSUtils::HudSetTextColor(CR_DARKGRAY);
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawText(id, text);
            return false;
        }

        return DrawClickableText(id, x, y, width, height, text);
    }

    internal bool DrawClickableText(int id, fixed x, fixed y, fixed width, fixed height, str text)
    {
        fixed mouseScale = ZH2Game::GetCursorScale();
        fixed cursorX = BCSUTILS::Floor(BCSUTILS::CursorX()),
              cursorY = BCSUTILS::Floor(BCSUTILS::CursorY());

        // Determine if this text is currently being selected.
        bool isOver =
               cursorX > x && cursorX < x + width
            && cursorY > y && cursorY < y + height;

        BCSUtils::HudSetTextColor(isOver ? CR_RED : CR_WHITE);
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(id, text);
        
        // Draw the bounds of the screen.
        DebugDraw(x, y, CR_GRAY);
        DebugDraw(x + width, y, CR_GRAY);
        DebugDraw(x, y + height, CR_GRAY);
        DebugDraw(x + width, y + height, CR_GRAY);

        return isOver && BCSUTILS::KeyPressed(BT_ATTACK);
    }

    internal void UpdateHudShakeOffset()
    {
        _xShakeOffset = 0.0;
        _yShakeOffset = 0.0;

        if (!Decorate::IsFiringWeapon())
            return;

        if (!ZH2Game::GetEnableHudShaking())
            return;

        int duration = ZH2Game::GetHudShakeDuration();
        int elapsed = Decorate::GetFiringTime();
        if (elapsed >= duration)
            return;

        // Initialize shake on first tic
        if (elapsed == 1)
            _firingSeedAngle = Math::FRandom(0.0, 2.0 * BCSUtils::PI);

        fixed maxIntensity = HUDSHAKE_INTENSITYBASE * ZH2Game::GetHudShakeIntensityMultiplier();
        fixed frequency = HUDSHAKE_FREQUENCYBASE * ZH2Game::GetHudShakeFrequencyMultiplier();

        fixed progress = fixed(elapsed) / fixed(duration);
        fixed intensity = maxIntensity * (1.0 - progress);

        fixed angle = fixed(elapsed) * fixed(frequency) * 0.01;
        fixed offset = Sin(angle) * intensity;

        _xShakeOffset = Cos(_firingSeedAngle) * offset;
        _yShakeOffset = Sin(_firingSeedAngle) * offset;
    }

    internal void OpenAdminMenu(AdminMenuT menu)
    {
        _currentAdminMenu = menu;
    }

    internal void ResetHud()
    {
        OpenAdminMenu(ADMINMENU_START);
        _menuPlayerTargetId = -1;
        menuPlayerTarget = MENUTARGET_NONE;
        _filteredSpecie = Player::SPECIENONE;
    }
}

#undef LOGSOURCE 