#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Hud"

#include "extern.acs"
#include "draw.acs"

#include "skins/default/default.acs"
#include "skins/legacy/legacy.acs"
#include "skins/shared/shared.acs"

#include "round/round.acs"

#include "clientsettings/clientsettings.acs"
#include "deathcam/deathcam.acs"
#include "identity/identity.acs"
#include "inventory/inventory.acs"
#include "blur/blur.acs"
#include "resist/resist.acs"
#include "fullserver/fullserver.acs"
#include "power/power.acs"
#include "ztele/ztele.acs"

#include "ending/ending.acs"
#include "voting/voting.acs"
#include "damagefeedback/damagefeedback.acs"
#include "obituary/obituary.acs"
#include "separate/separate.acs"
#include "decorate/decorate.acs"
#include "admin/admin.acs"

#include "cursor/cursor.acs"
#include "diagnostics/version.acs"
#include "diagnostics/debug.acs"

strict namespace Hud
{
    internal AdminMenuT _currentAdminMenu;

    // Used for killing unsafe players. Indicates the slot to keep safe (or -1 for any slot)
    internal int _killUnsafePlayersSafeSlot = -1;

    internal int _debugHudId;
    internal int _drawnHudId;

    // For shaking of the HUD.
    internal fixed _firingSeedAngle = 0.0;
    internal fixed _xShakeOffset = 0.0;
    internal fixed _yShakeOffset = 0.0;

    // The main positioning and scale used when drawing elements.
    internal fixed _hudX,
                   _hudY;

    // Indicates if the client's camera is on its own body.
    // This means we're not spectating anybody, nor are we on some camera.
    internal bool _clientCameraOnBody;

    // Send through the hook.
    HudHookDataT? _hudHookData;

    internal void Tic()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        _debugHudId = HUDID_DEBUG_COORDINATES;
        _drawnHudId = HUDID_BASE;

        _clientCameraOnBody = CheckPlayerCamera(ConsolePlayerNumber()) == ActivatorTid();

        // Ensure we have the hook data allocated.
        if (_hudHookData == null)
            _hudHookData = bcs::malloc(lengthof(_hudHookData));

        UpdateHudShakeOffset();

        DrawHud();
    }

    internal void PrepareHud(fixed x, fixed y, bool addShake)
    {
        _hudX = x;
        _hudY = y;

        if (addShake)
        {
            _hudX += _xShakeOffset;
            _hudY += _yShakeOffset;
        }
    }

    // Determines the HUD skin to use for the player's HUD.
    // The server's setting has the highest priority.
    // Then the client's setting is used.
    // If neither care, use what is best for the map.
    internal ZH2Game::HudSkinT GetHudSkin(int playerId)
    {
        switch (ZH2Game::GetSvForceHudSkin())
        {
            case ZH2Game::HUDSKINBEHAVIOUR_FORCEDEFAULTSKIN: return ZH2Game::HUDSKIN_DEFAULT;
            case ZH2Game::HUDSKINBEHAVIOUR_FORCELEGACYSKIN: return ZH2Game::HUDSKIN_LEGACY;
            default:
            {
                switch (ZH2Game::GetClHudSkin(playerId))
                {
                    case ZH2Game::HUDSKINPREFERENCE_DEFAULT: return ZH2Game::HUDSKIN_DEFAULT;
                    case ZH2Game::HUDSKINPREFERENCE_LEGACY: return ZH2Game::HUDSKIN_LEGACY;
                    default: return GetBestFitHudSkin();
                }
            }
        }
    }

    // The hud skin the game considers the best one to use.
    internal ZH2Game::HudSkinT GetBestFitHudSkin()
    {
        if (Map::GetCurrentMapIsLegacyMap())
            return ZH2Game::HUDSKIN_LEGACY;

        return ZH2Game::HUDSKIN_DEFAULT;
    }

    internal fixed GetHudX()
    {
        return _hudX;
    }

    internal fixed GetHudY()
    {
        return _hudY;
    }

    // Helper method to set the hud point based on possible scaling.
    internal void HudSetPointInternal(fixed addX = 0.0, fixed addY = 0.0)
    {
        BCSUtils::HudSetPoint(_hudX + addX, _hudY + addY);
    }

    internal void DebugDraw(fixed x = 0.0, fixed y = 0.0, int color = CR_WHITE)
    {
        if (!ZH2Game::GetDrawDebugCoordinatesHud()) return;

        BCSUtils::HudPushState();
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetTextColor(color);

        if (x != 0.0 && y != 0.0)
            BCSUtils::HudSetPoint(x, y);

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudDrawText(_debugHudId--, "*");
        BCSUtils::HudPopState();
    }

    internal bool DrawClickableTextConditional(bool clickable, int id, fixed addX, fixed addY, fixed width, fixed height, str text)
    {
        if (!clickable)
        {
            BCSUtils::HudSetTextColor(CR_DARKGRAY);

            HudSetPointInternal(addX, addY);
            BCSUtils::HudDrawText(id, text);

            return false;
        }

        return DrawClickableText(id, addX, addY, width, height, text);
    }

    internal bool DrawClickableText(int id, fixed addX, fixed addY, fixed width, fixed height, str text)
    {
        fixed mouseScale = ZH2Game::GetCursorScale();
        fixed cursorX = BCSUTILS::Floor(BCSUTILS::CursorX()),
              cursorY = BCSUTILS::Floor(BCSUTILS::CursorY());

        fixed x = GetHudX() + addX,
              y = GetHudY() + addY;

        // Determine if this text is currently being selected.
        bool isOver =
               cursorX > x && cursorX < x + width
            && cursorY > y && cursorY < y + height;

        BCSUtils::HudSetTextColor(isOver ? CR_RED : CR_WHITE);

        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(id, text);

        // Draw the bounds of the screen.
        DebugDraw(x, y, CR_GRAY);
        DebugDraw(x + width, y, CR_GRAY);
        DebugDraw(x, y + height, CR_GRAY);
        DebugDraw(x + width, y + height, CR_GRAY);

        return isOver && BCSUTILS::KeyPressed(BT_ATTACK);
    }

    internal void UpdateHudShakeOffset()
    {
        _xShakeOffset = 0.0;
        _yShakeOffset = 0.0;

        if (!Decorate::IsFiringWeapon())
            return;

        if (!ZH2Game::GetEnableHudShaking())
            return;

        // Do not shake if the camera is not on the client.
        if (!_clientCameraOnBody)
            return;

        int duration = ZH2Game::GetHudShakeDuration();
        int elapsed = Decorate::GetFiringTime();
        if (elapsed >= duration)
            return;

        // Initialize shake on first tic
        if (elapsed == 1)
            _firingSeedAngle = Math::FRandom(0.0, 2.0 * BCSUtils::PI);

        fixed maxIntensity = HUDSHAKE_INTENSITYBASE * ZH2Game::GetHudShakeIntensityMultiplier();
        fixed frequency = HUDSHAKE_FREQUENCYBASE * ZH2Game::GetHudShakeFrequencyMultiplier();

        fixed progress = fixed(elapsed) / fixed(duration);
        fixed intensity = maxIntensity * (1.0 - progress);

        fixed angle = fixed(elapsed) * fixed(frequency) * 0.01;
        fixed offset = Sin(angle) * intensity;

        _xShakeOffset = Cos(_firingSeedAngle) * offset;
        _yShakeOffset = Sin(_firingSeedAngle) * offset;
    }

    internal void OpenAdminMenu(AdminMenuT menu)
    {
        _currentAdminMenu = menu;
    }

    internal void ResetHud()
    {
        OpenAdminMenu(ADMINMENU_START);
        _menuPlayerTargetId = -1;
        menuPlayerTarget = MENUTARGET_NONE;
        _filteredSpecie = Player::SPECIENONE;
    }
}

#undef LOGSOURCE