#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "utils/utils.h.acs"

strict namespace Hud
{
    #define BAR_AIRSUPPLY_NAME "AIRBAR1"
    #define BAR_AIRSUPPLY_METER_NAME "AIRBAR2"
    #define BAR_AIRSUPPLY_WIDTH 128
    #define BAR_AIRSUPPLY_HEIGHT 10

    #define BAR_SPRINT_NAME "SPRNBAR1"
    #define BAR_SPRINT_METER_NAME "SPRNBAR2"
    #define BAR_SPRINT_WIDTH 128
    #define BAR_SPRINT_HEIGHT 10

    #define BLUR_BLACK_GRAPHIC "BLURBLAC"
    #define BLUR_GREEN_GRAPHIC "BLURGREN"
    #define BLUR_RED_GRAPHIC "BLURRED"
    #define BLUR_ORANGE_GRAPHIC "BLURORAN"

    #define HUD_FIRE_GRAPHIC "HUD_FIR"
    #define HUD_INFECTFIRE_GRAPHIC "HUD_IFR"

    #define HUD_RADIOHEADER_GRAPHIC "HUD_RADH"
    #define HUD_RADIOTRACK_GRAPHIC "HUD_RADT"
    #define HUD_RADIOTRACKSELECTED_GRAPHIC "HUD_RADS"

    #define RESIST_TIME_TOKEN "%t"
    #define RESIST_PLURAL_TOKEN "%p"

    #define HUD__ZOMBIE_ABILITY_GRAPHIC "HUD_FIR"

    #define HUDSHAKE_INTENSITYBASE 50.0
    #define HUDSHAKE_FREQUENCYBASE 50.0

    // SNIPER GRAPHICS
    #define HUDID_WEAPONSNIPER_BACKGROUNDNAME "snipzm1"
    #define HUDID_WEAPONSNIPER_METERNAME "snipzm2"
    #define HUDID_WEAPONSNIPER_METERPOINTERNAME "snipzm3"

    // Radio
    #define WEAPON_RADIO_MAXDRAWNTRACKS 3

    // Obituary constants
    #define OBITUARY_FADEIN_TICS 5
    #define OBITUARY_DURATION_TICS 70
    #define OBITUARY_FADEOUT_TICS 10

    // Obituary graphics
    #define HUD_OBITUARY_HUMAN "OB_HUMAN"
    #define HUD_OBITUARY_ZOMBIE "OB_ZOMB"
    #define HUD_OBITUARY_ZOMBIE_INITIAL "OB_ZOMBI"
    #define HUD_OBITUARY_ZOMBIE_REGULAR "OB_ZOMBR"
    #define HUD_OBITUARY_ZOMBIE_OLD "OB_ZOMBO"
    #define HUD_OBITUARY_SAFE "OB_SAFE"
    #define HUD_OBITUARY_INITIAL_CHOSEN "OB_INIT"
    #define HUD_OBITUARY_SCRATCH "OB_SCRAT"
    #define HUD_OBITUARY_CURE "OB_CURE"
    #define HUD_OBITUARY_UNSAFE "OB_UNSAF"
    #define HUD_OBITUARY_FIRE "OB_FIRE"
    #define HUD_OBITUARY_ACID "OB_ACID"

    #define HUD_OBITUARY_UNKNOWN "OB_UNKN"
    #define HUD_OBITUARY_SUICIDE "OB_SUIC"
    #define HUD_OBITUARY_FALLING "OB_FALL"
    #define HUD_OBITUARY_DROWNING "OB_DROWN"
    #define HUD_OBITUARY_CRUSHING "OB_CRUSH"
    #define HUD_OBITUARY_TELEFRAG "OB_TFRAG"
    #define HUD_OBITUARY_MONSTER "OB_MONST"

    // Damage feedback graphics
    #define FEEDBACK_HIT_GRAPHIC "FB_HIT"
    #define FEEDBACK_KILL_GRAPHIC "FB_KILL"

    /* HUD IDS */

    // Base IDs
    #define HUDID_DEBUG_COORDINATES 4500
    #define HUDID_CURSOR 4501
    #define HUDID_BASE 10000

    // Special HUD parts that deviate from the normal hud flow.
    // Mainly because they should not be overwritten
    #define HUDID_PREGAMESTATUS 4510
    #define HUDID_TIMER 4520
    #define HUDID_PLAYTIMER 4530
    #define HUDID_ZTELE 4540
    #define HUDID_DEATHCAM 4545
    #define HUDID_SPRINTBAR 4550
    #define HUDID_AIRBAR 4555
    #define HUDID_IDENTITY 4560
    #define HUDID_SUMMARY_FADE 12000
    #define HUDID_PICKCHANCE HUDID_PREGAMESTATUS

    // HUD states
    #define MAX_HUD_STATES 10
    #define HUD_STATES_ANGLE 20.0
    #define HUD_STATES_RADIUS 48.0

    // Admin hud data
    // Item selector list length and
    #define ADMINHUD_ITEMSELECTORS_MAXLENGTH 35

    // Passed into the hook when parts of the HUD is drawn.
    struct HudHookDataT
    {
        HudHookTypeT Type;
    };

    // Specifies what part of the HUD got drawn.
    enum HudHookTypeT : int
    {
        HUDHOOK_PLAYERSTATUS
    };

    internal enum AdminMenuT : int
    {
        ADMINMENU_START,
        ADMINMENU_PLAYER,
        ADMINMENU_TIMER,
        ADMINMENU_ROUND,
        ADMINMENU_RESIST,
    };

    internal enum AdminMenuPlayerTargetT : int
    {
        MENUTARGET_NONE,
        MENUTARGET_PLAYERSPECIFIC,
        MENUTARGET_ALL,
    };

    internal enum HudFireTypeT : int
    {
        FIRETYPENORMAL,
        FIRETYPEINFECT,
    };

    internal struct HudContextT
    {
        // The current page that the admin item selector list is on.
        int AdminItemSelectorListPage;
    };

    extern void SetRelativePoint(fixed x = 0.0, fixed y = 0.0);
}