#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawVersion()
    {
        fixed scale = ZH2Game::GetHudVersionScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_BOTTOM);

        fixed x = BCSUtils::HudRight(),
              y = BCSUtils::HudBottom();
              
        x += _xShakeOffset;
        y += _yShakeOffset;
        
        DrawVersionString(x - 10.0, y);
    }

    internal void DrawVersionString(fixed x, fixed y)
    {
        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_RED);

        if (DevelopmentPlayerCap())
        {
            int count = PlayerCount() - BCSUtils::BotCount();

            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawText(--_drawnHudId, "player cap: " + str(count) + "/" + str(DEV_PLAYERCAP_COUNT));
            DebugDraw();

            y -= 10.0;
        }

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(--_drawnHudId, "v" + GetVersion());
        DebugDraw();

        if (IsDevelopment())
        {
            y -= 10.0;
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawText(--_drawnHudId, "devbuild");
            DebugDraw();
        }
    }
}