#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Weather
{
    void StartEmitterWeather(EmitterWeatherTypeT type)
    {
        SetEmitterWeatherEnabled(type, true);
    }

    void StopEmitterWeather(EmitterWeatherTypeT type)
    {
        SetEmitterWeatherEnabled(type, false);
    }

    internal void SetEmitterWeatherEnabled(EmitterWeatherTypeT type, bool enabled)
    {
        SetTransientEmitterWeatherEnabled(TypeToIndex((int)type), enabled);
        if (BCSUtils::IsServerOnly()) Sync::SyncWeather();
    }

    void SetEmitterWeatherSpawnCount(EmitterWeatherTypeT type, int value)
    {
        SetTransientEmitterWeatherSpawnCount(TypeToIndex((int)type), value);
        if (BCSUtils::IsServerOnly()) Sync::SyncWeather();
    }

    void SetEmitterWeatherSpawnDelay(EmitterWeatherTypeT type, int value)
    {
        SetTransientEmitterWeatherSpawnDelay(TypeToIndex((int)type), value);
        if (BCSUtils::IsServerOnly()) Sync::SyncWeather();
    }

    void StartRandomizedWeather(RandomizedWeatherTypeT type)
    {
        SetRandomizedWeatherEnabled(type, true);
    }

    void StopRandomizedWeather(RandomizedWeatherTypeT type)
    {
        SetRandomizedWeatherEnabled(type, false);
    }

    internal void SetRandomizedWeatherEnabled(RandomizedWeatherTypeT type, bool enabled)
    {
        SetTransientRandomizedWeatherEnabled(TypeToIndex((int)type), enabled);
        if (BCSUtils::IsServerOnly()) Sync::SyncWeather();
    }

    void StartAmbientWeather(AmbientWeatherTypeT type)
    {
        SetAmbientWeatherEnabled(type, true);
    }

    void StopAmbientWeather(AmbientWeatherTypeT type)
    {
        SetAmbientWeatherEnabled(type, false);
    }

    internal void SetAmbientWeatherEnabled(AmbientWeatherTypeT type, bool enabled)
    {
        SetTransientAmbientWeatherEnabled(TypeToIndex((int)type), enabled);
        if (BCSUtils::IsServerOnly()) Sync::SyncWeather();
    }
}
