#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Obituary
{
    internal void LogInitialsChosen()
    {
        int count = Event::GetReceiveData(0);
        bool multiple = count > 1;

        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            int index = 1;
            while(count--)
            {
                int id = Event::GetReceiveData(index++);

                Append(s:BCSUTILS::PlayerName(id));
                if (count == 1) Append(s:" and ");
                else if (count != 0) Append(s:", ");
            }

            Append(s:(multiple ? " have " : " has ") + "been chosen as the initial zombie" + (multiple ? "s" : "") + ".");
        }

        Logger::LogConsolePlayer(logMessage);
    }

    internal void LogPlayerSafe()
    {
        int id = Event::GetReceiveData(0);
        if (id == ConsolePlayerNumber())
            Logger::LogConsolePlayer("You have reached the safezone!");
        else
            Logger::LogConsolePlayer(BCSUtils::PlayerName(id) + " has reached the safezone!");
    }

    internal void LogPlayerScratched()
    {
        int infectedId = Event::GetReceiveData(0);
        int infectorId = Event::GetReceiveData(1);
        if (infectedId == ConsolePlayerNumber())
            Logger::LogConsolePlayer("You have been infected!");
        else
            Logger::LogConsolePlayer("\cf" + Player::GetPlayerName(infectedId) + "\cj has been infected by \cf" + Player::GetPlayerName(infectorId) + "\cj!");
    }

    internal void LogPlayerInfected()
    {
        // Todo
    }
}
