#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Obituary
{
    script "zh2_internal_obituary_initialschosen_client" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceiveInitialsChosen(packet);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries())
            QueueInitialsChosen();
        else
            LogInitialsChosen();
    }

    script "zh2_internal_obituary_playersafe_client" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerSafe(packet);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries())
            QueuePlayerSafe();
        else
            LogPlayerSafe();
    }
}
