#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Obituary
{
    script "zh2_internal_obituary_initialschosen_client" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceiveInitialsChosen(packet);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueueInitialsChosen();
        else
            LogInitialsChosen();
    }

    script "zh2_internal_obituary_playersafe_client" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerSafe(packet);

        bool safe = Event::GetReceiveData(1);
        bool firstTime = Event::GetReceiveData(2);

        // We only handle if players entered the safezone, not left.
        // We also only handle first time safety.
        if (!safe || !firstTime)
            terminate;

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerSafe();
        else
            LogPlayerSafe();
    }

    script "zh2_internal_obituary_playerscratched" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerScratched(packet);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerScratched();
        else
            LogPlayerScratched();
    }
}
