#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define PACKET_TOTAL 3 //not an actual width
#define PACKET_NATIVE_HEADER_SIZE 13

strict namespace Packet
{
    enum
    {
        PACKET_WORD,
        PACKET_SHORT,
        PACKET_BYTE
    };

    extern raw Packet_Rval;

    extern int Packet_GetMaxSize ();
    extern int Packet_GetSize (str pac);
    extern str Packet_New();
    extern str Packet_Append (str pac, raw val, int width = PACKET_WORD);
    extern str Packet_AppendStr (str pac, str val);
    extern int Packet_Send (str scrip, str pac, int client = -1);
    extern raw Packet_Read (str pac, int width = PACKET_WORD);
    extern str Packet_ReadStr (str pac);
}