#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawTimer()
    {
        int id = HUDID_TIMER;

        int index = RoundTimer::GetActiveTimerIndex();
        if (!RoundTimer::GetTimerDefined(index) || !RoundTimer::GetTimerActive(index) || !RoundTimer::GetTimerVisible(index))
            return;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetAlpha(1.0);

        // This won't show until the very last draw.
        BCSUtils::HudSetStayTime(0.5);
        BCSUtils::HudSetDisappearTime(0.5);

        // Label
        HudSetPointInternal(0.0, -10.0);
        BCSUtils::HudDrawText(--id, RoundTimer::GetTimerLabel(index));
        DebugDraw();

        // Time left.
        int ticsLeft = RoundTimer::GetTimerTicsLeft(index);
        bool drawDecimals = RoundTimer::GetTimerDrawDecimals(index);

        // Add one second to tics if decimals are disabled unless the tics equal zero.
        // This way the result will not display zero on the final second, making for a better visualization of the tics.
        if (!drawDecimals && ticsLeft != 0)
            ticsLeft += 35 * BCSUtils::Sgn(ticsLeft);

        str timerFormatted = Utils::FormatTics(ticsLeft, drawDecimals);

        HudSetPointInternal();
        BCSUtils::HudDrawText(--id, timerFormatted);
        DebugDraw();

        // If the timer has countdowns enabled, then the last 10 seconds should have a fading red label on top.
        // First 18 tics of every 35 we display this.
        if (RoundTimer::GetTimerDoCountdown(index) && ticsLeft <= 35 * 11)
        {
            int tics = ticsLeft % 35;
            fixed alpha = (tics > 18) ? (1.0 - fixed(35 - tics) / 18.0) : 0.0;

            BCSUtils::HudSetAlpha(alpha);
            BCSUtils::HudSetTextColor(CR_RED);
            BCSUtils::HudDrawText(--id, timerFormatted);
            DebugDraw();
        }
    }
}