#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "header.acs"
#include "statlist.acs"

strict namespace Hud
{
    internal void DrawEndingHud()
    {
        fixed scale = ZH2Game::GetHudEndingScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0, 480.0);
        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        fixed x = 320.0;
        fixed y = BCSUtils::HudTop() + 80.0;
        
        DrawEndingHeader(x, y);

        x = 30.0;
        y += 60.0;

        // Offset is set based on what lists are shown, meaning we might shift lists to a different position if the stat has no data.
        int listOffset = 0;

        // The vertical offset will be updated to increased values based on the longest list.
        // This value is eventually used to draw the next row.
        fixed verticalOffset = 0.0;

        // Each column 220 units wide.
        // Each row 190 units tall.
        fixed GetX(int listOffset) { return x + fixed(listOffset % 3) * 220.0; }
        fixed GetY(int listOffset) { return y + fixed(listOffset / 3) * verticalOffset; }

        void UpdateOffsets(int count)
        {
            listOffset++;

            // If we have at least one item to draw, we want to see if the vertical offset needs updating.
            // If yes, this is the longest list so far.
            if (count == 0)
                return;
            
            // Base addition of 25.0 for the header and 10.0 for a gap between lists.
            // Every name adds 15.0 to the offset.
            fixed checkVerticalOffset = 25.0 + 10.0 + fixed(count * 15);
            if (checkVerticalOffset > verticalOffset)
            {
                verticalOffset = checkVerticalOffset;
            }
        }

        /* ACTUAL DRAWING BELOW */

        // Used below to hold the final drawn item count, used for determining the y offset.
        int drawnCount;

        if (ZH2Game::GameContext.SurvivorsShuffledCount > 0)
        {
            drawnCount = DrawList(HUD_ENDINGSURVIVORS, GetX(listOffset), GetY(listOffset), "\cdSurvivors",
                ZH2Game::GameContext.SurvivorsShuffledCount, 8, ZH2Game::GameContext.SurvivorsShuffled, null);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.HordeShuffledCount > 0)
        {
            drawnCount = DrawList(HUD_ENDINGHORDE, GetX(listOffset), GetY(listOffset), "\cqThe horde",
                ZH2Game::GameContext.HordeShuffledCount, 8, ZH2Game::GameContext.HordeShuffled, null);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.DeadShuffledCount > 0)
        {
            drawnCount = DrawList(HUD_ENDINGDEAD, GetX(listOffset), GetY(listOffset), "\cjIn memory of",
                ZH2Game::GameContext.DeadShuffledCount, 8, ZH2Game::GameContext.DeadShuffled, null);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.HumanKillsOrderedCount > 0)
        {
            drawnCount = DrawList(HUD_ENDINGHUMANKILLS, GetX(listOffset), GetY(listOffset), "\cgTop human killers",
                ZH2Game::GameContext.HumanKillsOrderedCount, 4, ZH2Game::GameContext.HumanKillsOrdered, Player::GetPlayerHumanKills);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.ZombieKillsOrderedCount > 0)
        {
            drawnCount = DrawList(HUD_ENDINGZOMBIEKILLS, GetX(listOffset), GetY(listOffset), "\cfTop zombie killers",
                ZH2Game::GameContext.ZombieKillsOrderedCount, 4, ZH2Game::GameContext.ZombieKillsOrdered, Player::GetPlayerZombieKills);
            UpdateOffsets(drawnCount);
        }
            
        if (ZH2Game::GameContext.InfectsOrderedCount > 0)
        {
            drawnCount = DrawList(HUD_ENDINGINFECTS, GetX(listOffset), GetY(listOffset), "\cgTop infects",
                ZH2Game::GameContext.InfectsOrderedCount, 4, ZH2Game::GameContext.InfectsOrdered, Player::GetPlayerInfects);
            UpdateOffsets(drawnCount);
        }
    }
}