#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Full list of CVars defined in the code.
// Used by both the internal code and as externed data, as a shared file.
// This also provides an easy way to define CVar values only once instead of defining both its core function + extern function.

strict namespace CVar
{
    // Logging
    CVAR_SV_INT_CLAMPED(OverrideLogSeverity, 0, 5)
    CVAR_CL_INT_CLAMPED(OverrideLogSeverity, 0, 5)
    CVAR_SV_INT_CLAMPED(OverrideGlobalLogSeverity, 0, 5)

    // Tracers
    CVAR_SV_BOOL(EnableTracers)
    CVAR_CL_INT_CLAMPED(TracerType, 0, 2)

    // Footstep
    CVAR_CL_INT_CLAMPED(StepType, 0, 2)
    CVAR_CL_INT_CLAMPED(MaxStepDistance, 100, 8000)

    // Weather
    CVAR_SV_BOOL(EnableWeather)
    CVAR_CL_BOOL(EnableWeather)
    CVAR_CL_BOOL(EnableEmitterWeather)
    CVAR_CL_BOOL(EnableRandomizedWeather)
    CVAR_CL_BOOL(EnableAmbientWeather)

    // Chat / Zandronum
    CVAR_ENGINE_INT(GetClChatSound, "chat_sound")
    CVAR_ENGINE_BOOL(GetClShowMessages, "show_messages")
    CVAR_ENGINE_BOOL(GetSvClientsSendFullButtonInfo, "compat_clientssendfullbuttoninfo")

    // Game - Sync
    CVAR_SV_BOOL(UseSyncBuffer)
    CVAR_SV_INT_CLAMPED(SyncDelay, 0, 35)
    CVAR_SV_INT_CLAMPED(InitialSyncDelay, 0, 35)
}
