#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Sync"

#include "actor/player.acs"
#include "actor/timer.acs"
#include "actor/resist.acs"
#include "actor/round.acs"
#include "actor/power.acs"
#include "actor/admin.acs"
#include "actor/game.acs"
#include "actor/mapvoting.acs"

strict namespace Sync
{
    // Basic log formatter to include an additional sync category.
    internal str FormatLog(str category, str message)
    {
        return "[" + category + "] " + message;
    }

    /* COMBINED */

    internal void SyncAll(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        Sync::SyncPlayers(callSyncOnClients);
        Sync::SyncTimers(callSyncOnClients);
        Sync::SyncResists(callSyncOnClients);
        Sync::SyncRoundState(callSyncOnClients);
        Sync::SyncPowers(callSyncOnClients);
        Sync::SyncAdmins(callSyncOnClients);
        Sync::SyncGame(callSyncOnClients);
        Sync::SyncMapVoting(callSyncOnClients);
    }

    internal void CallClientSyncAll()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        Sync::CallSyncPlayersOnClients();
        Sync::CallSyncTimersOnClients();
        Sync::CallSyncResistsOnClients();
        Sync::CallSyncRoundStateOnClients();
        Sync::CallSyncPowersOnClients();
        Sync::CallSyncAdminsOnClients();
        Sync::CallSyncGameOnClients();
        Sync::CallSyncMapVotingOnClients();
    }

    internal void SyncAllClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        Sync::SyncPlayersClientside();
        Sync::SyncTimersClientside();
        Sync::SyncResistsClientside();
        Sync::SyncRoundStateClientside();
        Sync::SyncPowersClientside();
        Sync::SyncAdminsClientside();
        Sync::SyncGameClientside();
        Sync::SyncMapVotingClientside();
    }

    /* PLAYERS */

    internal void SyncPlayers(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizePlayersSyncedClientside();
            return;
        }

        SyncPlayersActor();

        if (callSyncOnClients)
            CallSyncPlayersOnClients();
    }

    internal void CallSyncPlayersOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_players_clientside", 0);
    }

    script "zh2_internal_sync_players_clientside" clientside
    {
        SyncPlayersActorClientside();
    }

    internal void SyncPlayersClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncPlayersActorClientSide();

        FinalizePlayersSyncedClientside();
    }

    internal void FinalizePlayersSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_PLAYERS);
    }

    /* TIMERS */

    internal void SyncTimers(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeTimersSyncedClientside();
            return;
        }

        SyncTimersActor();

        if (callSyncOnClients)
            CallSyncTimersOnClients();
    }

    internal void CallSyncTimersOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_timers_clientside", 0);
    }

    script "zh2_internal_sync_timers_clientside" clientside
    {
        SyncTimersActorClientside();
    }

    internal void SyncTimersClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncTimersActorClientside();

        FinalizeTimersSyncedClientside();
    }

    internal void FinalizeTimersSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_TIMERS);
    }

    /* RESISTS */

    internal void SyncResists(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeResistsSyncedClientside();
            return;
        }

        SyncResistsActor();

        if (callSyncOnClients)
            CallSyncResistsOnClients();
    }

    internal void CallSyncResistsOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_resists_clientside", 0);
    }

    script "zh2_internal_sync_resists_clientside" clientside
    {
        SyncResistsActorClientside();
    }

    internal void SyncResistsClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncResistsActorClientside();

        FinalizeResistsSyncedClientside();
    }

    internal void FinalizeResistsSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_RESISTS);
    }

    /* ROUND */

    internal void SyncRoundState(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeRoundStateSyncedClientside();
            return;
        }

        SyncRoundStateActor();

        if (callSyncOnClients)
            CallSyncRoundStateOnClients();
    }

    internal void CallSyncRoundStateOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_round_state_clientside", 0);
    }

    script "zh2_internal_sync_round_state_clientside" clientside
    {
        SyncRoundStateActorClientside();
    }

    internal void SyncRoundStateClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncRoundStateActorClientside();

        FinalizeRoundStateSyncedClientside();
    }

    internal void FinalizeRoundStateSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_ROUNDSTATE);
    }

    /* POWERS */

    internal void SyncPowers(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizePowersSyncedClientside();
            return;
        }

        SyncPowersActor();

        if (callSyncOnClients)
            CallSyncPowersOnClients();
    }

    internal void CallSyncPowersOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_power_clientside", 0);
    }

    script "zh2_internal_sync_power_clientside" clientside
    {
        SyncPowersActorClientside();
    }

    internal void SyncPowersClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncPowersActorClientSide();

        FinalizePowersSyncedClientside();
    }

    internal void FinalizePowersSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_POWERS);
    }

    /* ADMIN */

    internal void SyncAdmins(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeAdminsSyncedClientside();
            return;
        }

        SyncAdminsActor();

        if (callSyncOnClients)
            CallSyncAdminsOnClients();
    }

    internal void CallSyncAdminsOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_admins_clientside", 0);
    }

    script "zh2_internal_sync_admins_clientside" clientside
    {
        SyncAdminsActorClientside();
    }

    internal void SyncAdminsClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncAdminsActorClientside();

        FinalizeAdminsSyncedClientside();
    }

    internal void FinalizeAdminsSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_ADMINS);
    }

    /* GAME */

    internal void SyncGame(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeGameSyncedClientside();
            return;
        }

        SyncGameActor();

        if (callSyncOnClients)
            CallSyncGameOnClients();
    }

    internal void CallSyncGameOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_game_clientside", 0);
    }

    script "zh2_internal_sync_game_clientside" clientside
    {
        SyncGameActorClientside();
    }

    internal void SyncGameClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncGameActorClientside();

        FinalizeGameSyncedClientside();
    }

    internal void FinalizeGameSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_GAME);
    }

    /* MAP VOTING */

    internal void SyncMapVoting(bool callSyncOnClients = true)
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeMapVotingSyncedClientside();
            return;
        }

        SyncMapVotingActor();

        if (callSyncOnClients)
            CallSyncMapVotingOnClients();
    }

    internal void CallSyncMapVotingOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
            return;

        ACS_NamedExecute("zh2_internal_sync_mapvoting_clientside", 0);
    }

    script "zh2_internal_sync_mapvoting_clientside" clientside
    {
        SyncMapVotingActorClientside();
    }

    internal void SyncMapVotingClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncMapVotingActorClientside();

        FinalizeMapVotingSyncedClientside();
    }

    internal void FinalizeMapVotingSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_MAPVOTING);
    }
}

#undef LOGSOURCE