#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Sync
{
    #define ACTOR_SYNC_PLAYER_NAME_TEMPLATE "__playername%n"

    #define ACTOR_SYNC_TIMER_LABEL_TEMPLATE "__timerlabel%n"

    #define ACTOR_SYNC_RESIST_LABEL_TOP_TEMPLATE "__resistlabeltop%n"
    #define ACTOR_SYNC_RESIST_LABEL_BOTTOM_TEMPLATE "__resistlabelbottom%n"

    // Sync base is what the sync TIDs will base off.
    // Each sync category then takes a certain length which they need to sync its data.
    // The length in this case is used to debug the result and to make sure the sync stays inbounds,
    // in case we sync more TIDs and possible lose data due to overflowing.

    #define SYNC_BASE 50000

    // Start of transient TID definitions
    #define SYNC_PLAYER_PICKWEIGHT_PLAYERS_PER_PACK 4
    #define SYNC_PLAYER_PICKWEIGHT_LENGTH (BCSUtils::MAX_PLAYERS / SYNC_PLAYER_PICKWEIGHT_PLAYERS_PER_PACK)

    // Start of actual TID definitions

    // Player sync has at least four instances of 64 players needing their own sync tid.
    // We also require 32 ints from the safety slots (1 player requires 16 bits each at most)
    #define SYNC_PLAYERS_LENGTH (BCSUtils::MAX_PLAYERS * 4 + 24) + 32 + SYNC_PLAYER_PICKWEIGHT_LENGTH
    #define SYNC_PLAYERS SYNC_BASE + SYNC_PLAYERS_LENGTH

    #define SYNC_ROUNDTIMERS_LENGTH (MAX_TIMERS * 10)
    #define SYNC_ROUNDTIMERS SYNC_PLAYERS + SYNC_ROUNDTIMERS_LENGTH

    #define SYNC_RESISTS_LENGTH (MAX_RESISTS * 7 + 1)
    #define SYNC_RESISTS SYNC_ROUNDTIMERS + SYNC_RESISTS_LENGTH

    #define SYNC_ROUND_LENGTH (MAX_ROUNDSTATES * 3 + 20)
    #define SYNC_ROUND SYNC_RESISTS + SYNC_ROUND_LENGTH

    #define SYNC_POWER_LENGTH (BCSUtils::MAX_PLAYERS * MAX_POWER_TYPES)
    #define SYNC_POWER SYNC_ROUND + SYNC_POWER_LENGTH

    #define SYNC_ADMIN_LENGTH 10
    #define SYNC_ADMIN SYNC_POWER + SYNC_ADMIN_LENGTH

    #define SYNC_GAME_LENGTH 24 + BCSUtils::MAX_PLAYERS
    #define SYNC_GAME SYNC_ADMIN + SYNC_GAME_LENGTH

    #define SYNC_MAPVOTING_LENGTH (BCSUtils::MAX_PLAYERS + MAX_VOTABLEMAPS + 10)
    #define SYNC_MAPVOTING SYNC_GAME + SYNC_MAPVOTING_LENGTH

    // AFK prevention needs 64 * 2 for the last move tic and the warn tic.
    #define SYNC_AFKPREVENTION_LENGTH (BCSUtils::MAX_PLAYERS * 2)
    #define SYNC_AFKPREVENTION SYNC_MAPVOTING + SYNC_AFKPREVENTION_LENGTH

    // When adding a new sync, also increase this number.
    #define MAX_SYNC_TYPES 9

    internal enum SyncTypeT : int
    {
        // Slot 0 reserved by library sync

        SYNCTYPE_PLAYERS = 1,
        SYNCTYPE_TIMERS,
        SYNCTYPE_RESISTS,
        SYNCTYPE_ROUNDSTATE,
        SYNCTYPE_POWERS,
        SYNCTYPE_ADMINS,
        SYNCTYPE_GAME,
        SYNCTYPE_MAPVOTING,
        SYNCTYPE_AFKPREVENTION,
    };

    struct SyncContextT
    {
        int FlushTic[MAX_SYNC_TYPES];
    };
}