#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Sync"

#include "actor/player.acs"
#include "actor/timer.acs"
#include "actor/resist.acs"
#include "actor/round.acs"
#include "actor/power.acs"
#include "actor/admin.acs"
#include "actor/game.acs"
#include "actor/mapvoting.acs"
#include "actor/afkprevention.acs"
#include "actor/radio.acs"

strict namespace Sync
{
    void FlushPendingSyncs()
    {
        if (ZH2Lib::GetInitialSyncDelay() > Timer())
            return;

        int min = 0;
        int max = MAX_SYNC_TYPES - 1;
        for (int i = min; i <= max; ++i)
        {
            int tic = ZH2Game::GameContext.SyncContext.FlushTic[i];
            if (tic == 0 || tic > Timer())
                continue;

            ZH2Game::GameContext.SyncContext.FlushTic[i] = 0;

            int index = i + MAX_LIB_SYNC_TYPES;
            TriggerSyncCore(index);
        }
    }

    internal void TriggerSyncCore(int syncId)
    {
        switch(syncId)
        {
            case SYNCTYPE_PLAYERS: SyncPlayersCore(); return;
            case SYNCTYPE_TIMERS: SyncTimersCore(); return;
            case SYNCTYPE_RESISTS: SyncResistsCore(); return;
            case SYNCTYPE_ROUNDSTATE: SyncRoundStateCore(); return;
            case SYNCTYPE_POWERS: SyncPowersCore(); return;
            case SYNCTYPE_ADMINS: SyncAdminsCore(); return;
            case SYNCTYPE_GAME: SyncGameCore(); return;
            case SYNCTYPE_MAPVOTING: SyncMapVotingCore(); return;
            case SYNCTYPE_AFKPREVENTION: SyncAfkPreventionCore(); return;
            case SYNCTYPE_RADIO: SyncRadioCore(); return;

            default:
                Logger::LogError(LOGSOURCE, __FUNCTION__ + ": Failed to flush sync index " + str(syncId) + " as it's not known.");
                return;
        }
    }

    internal void DoSync(int syncId)
    {
        // Buffering not enabled.
        if (!ZH2Lib::GetUseSyncBuffer())
        {
            TriggerSyncCore(syncId);
            return;
        }

        // Remove whatever base the lib gave us so we now use zero-indexed ids.
        syncId -= MAX_LIB_SYNC_TYPES;

        int min = 0;
        int max = MAX_SYNC_TYPES - 1;
        if (syncId < min || syncId > max)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": Invalid sync id " + str(syncId) + ". Id must be between " + str(min) + " and " + str(max) + " (inclusive).");
            return;
        }

        // Already marked to sync.
        if (ZH2Game::GameContext.SyncContext.FlushTic[syncId] != 0)
            return;

        ZH2Game::GameContext.SyncContext.FlushTic[syncId] = Timer() + ZH2Lib::GetSyncDelay();
    }

    // Basic log formatter to include an additional sync category.
    internal str FormatLog(str category, str message)
    {
        return "[" + category + "] " + message;
    }

    /* COMBINED */

    internal void SyncAll()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        Sync::SyncPlayers();
        Sync::SyncTimers();
        Sync::SyncResists();
        Sync::SyncRoundState();
        Sync::SyncPowers();
        Sync::SyncAdmins();
        Sync::SyncGame();
        Sync::SyncMapVoting();
        Sync::SyncAfkPrevention();
        Sync::SyncRadio();
    }

    internal void CallClientSyncAll()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        Sync::CallSyncPlayersOnClients();
        Sync::CallSyncTimersOnClients();
        Sync::CallSyncResistsOnClients();
        Sync::CallSyncRoundStateOnClients();
        Sync::CallSyncPowersOnClients();
        Sync::CallSyncAdminsOnClients();
        Sync::CallSyncGameOnClients();
        Sync::CallSyncMapVotingOnClients();
        Sync::CallSyncAfkPreventionOnClients();
        Sync::CallSyncRadioOnClients();
    }

    internal void SyncAllClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        Sync::SyncPlayersClientside();
        Sync::SyncTimersClientside();
        Sync::SyncResistsClientside();
        Sync::SyncRoundStateClientside();
        Sync::SyncPowersClientside();
        Sync::SyncAdminsClientside();
        Sync::SyncGameClientside();
        Sync::SyncMapVotingClientside();
        Sync::SyncAfkPreventionClientside();
        Sync::SyncRadioClientside();
    }

    /* PLAYERS */

    internal void SyncPlayers()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizePlayersSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_PLAYERS);
    }

    internal void SyncPlayersCore()
    {
        SyncPlayersActor();
        CallSyncPlayersOnClients();
    }

    internal void CallSyncPlayersOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_players_clientside", 0);
    }

    script "zh2_internal_sync_players_clientside" clientside
    {
        SyncPlayersClientside();
    }

    internal void SyncPlayersClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncPlayersActorClientSide();

        FinalizePlayersSyncedClientside();
    }

    internal void FinalizePlayersSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_PLAYERS);
    }

    /* TIMERS */

    internal void SyncTimers()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeTimersSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_TIMERS);
    }

    internal void SyncTimersCore()
    {
        SyncTimersActor();
        CallSyncTimersOnClients();
    }

    internal void CallSyncTimersOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_timers_clientside", 0);
    }

    script "zh2_internal_sync_timers_clientside" clientside
    {
        SyncTimersClientside();
    }

    internal void SyncTimersClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncTimersActorClientside();

        FinalizeTimersSyncedClientside();
    }

    internal void FinalizeTimersSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_TIMERS);
    }

    /* RESISTS */

    internal void SyncResists()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeResistsSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_RESISTS);
    }

    internal void SyncResistsCore()
    {
        SyncResistsActor();
        CallSyncResistsOnClients();
    }

    internal void CallSyncResistsOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_resists_clientside", 0);
    }

    script "zh2_internal_sync_resists_clientside" clientside
    {
        SyncResistsClientside();
    }

    internal void SyncResistsClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncResistsActorClientside();

        FinalizeResistsSyncedClientside();
    }

    internal void FinalizeResistsSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_RESISTS);
    }

    /* ROUND */

    internal void SyncRoundState()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeRoundStateSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_ROUNDSTATE);
    }

    internal void SyncRoundStateCore()
    {
        SyncRoundStateActor();
        CallSyncRoundStateOnClients();
    }

    internal void CallSyncRoundStateOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_round_state_clientside", 0);
    }

    script "zh2_internal_sync_round_state_clientside" clientside
    {
        SyncRoundStateClientside();
    }

    internal void SyncRoundStateClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncRoundStateActorClientside();

        FinalizeRoundStateSyncedClientside();
    }

    internal void FinalizeRoundStateSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_ROUNDSTATE);
    }

    /* POWERS */

    internal void SyncPowers()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizePowersSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_POWERS);
    }

    internal void SyncPowersCore()
    {
        SyncPowersActor();
        CallSyncPowersOnClients();
    }

    internal void CallSyncPowersOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_power_clientside", 0);
    }

    script "zh2_internal_sync_power_clientside" clientside
    {
        SyncPowersClientside();
    }

    internal void SyncPowersClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncPowersActorClientSide();

        FinalizePowersSyncedClientside();
    }

    internal void FinalizePowersSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_POWERS);
    }

    /* ADMIN */

    internal void SyncAdmins()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeAdminsSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_ADMINS);
    }

    internal void SyncAdminsCore()
    {
        SyncAdminsActor();
        CallSyncAdminsOnClients();
    }

    internal void CallSyncAdminsOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_admins_clientside", 0);
    }

    script "zh2_internal_sync_admins_clientside" clientside
    {
        SyncAdminsClientside();
    }

    internal void SyncAdminsClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncAdminsActorClientside();

        FinalizeAdminsSyncedClientside();
    }

    internal void FinalizeAdminsSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_ADMINS);
    }

    /* GAME */

    internal void SyncGame()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeGameSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_GAME);
    }

    internal void SyncGameCore()
    {
        SyncGameActor();
        CallSyncGameOnClients();
    }

    internal void CallSyncGameOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_game_clientside", 0);
    }

    script "zh2_internal_sync_game_clientside" clientside
    {
        SyncGameClientside();
    }

    internal void SyncGameClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncGameActorClientside();

        FinalizeGameSyncedClientside();
    }

    internal void FinalizeGameSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_GAME);
    }

    /* MAP VOTING */

    internal void SyncMapVoting()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeMapVotingSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_MAPVOTING);
    }

    internal void SyncMapVotingCore()
    {
        SyncMapVotingActor();
        CallSyncMapVotingOnClients();
    }

    internal void CallSyncMapVotingOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_mapvoting_clientside", 0);
    }

    script "zh2_internal_sync_mapvoting_clientside" clientside
    {
        SyncMapVotingClientside();
    }

    internal void SyncMapVotingClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncMapVotingActorClientside();

        FinalizeMapVotingSyncedClientside();
    }

    internal void FinalizeMapVotingSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_MAPVOTING);
    }

    /* AFK Prevention */

    internal void SyncAfkPrevention()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeAfkPreventionSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_AFKPREVENTION);
    }

    internal void SyncAfkPreventionCore()
    {
        SyncAfkPreventionActor();
        CallSyncAfkPreventionOnClients();
    }

    internal void CallSyncAfkPreventionOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_afkprevention_clientside", 0);
    }

    script "zh2_internal_sync_afkprevention_clientside" clientside
    {
        SyncAfkPreventionClientside();
    }

    internal void SyncAfkPreventionClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncAfkPreventionActorClientSide();

        FinalizeAfkPreventionSyncedClientside();
    }

    internal void FinalizeAfkPreventionSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_AFKPREVENTION);
    }

    /* RADIO */

    internal void SyncRadio()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeRadioSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_RADIO);
    }

    internal void SyncRadioCore()
    {
        SyncRadioActor();
        CallSyncRadioOnClients();
    }

    internal void CallSyncRadioOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_radio_clientside", 0);
    }

    script "zh2_internal_sync_radio_clientside" clientside
    {
        SyncRadioClientside();
    }

    internal void SyncRadioClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncRadioActorClientside();

        FinalizeRadioSyncedClientside();
    }

    internal void FinalizeRadioSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_RADIO);
    }
}

#undef LOGSOURCE