#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Debug
{
    script "zh2_action_enableadmin" net
    {
        // We must either be in an offline game, the server must run in development mode, or sv_cheats must be enabled.
        if (IsNetworkGame() && !IsDevelopment() && !ZH2Game::GetSvCheats())
        {
            Logger::LogActivator("You're not allowed to be set as an admin.");
            terminate;
        }

        Admin::RconSetPlayerIsAdmin(PlayerNumber(), true);
    }

    script "zh2_action_disableadmin" net
    {
        Admin::RconSetPlayerIsAdmin(PlayerNumber(), false);
    }
}