#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    // NOTE: Setting CVars uses ConsoleCommand which might break in the future. We do notify of this on the UI.
    // https://wiki.zandronum.com/ConsoleCommand

    internal void DrawClientSettingsHud()
    {
        fixed scale = ZH2Game::GetHudClientSettingsScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0, 480.0);
        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_TOP);

        fixed x = BCSUtils::HudLeft() + 100.0,
              y = BCSUtils::HudTop() + 50.0;

        _drawnHudId = HUDID_CLIENTSETTING;
        DrawClientSettingsHeader(x, y, scale);

        y += 110.0;

        for (int i = 0; i < ZH2Game::GameContext.RequestedClientSettingCount; ++i)
            DrawInvalidSetting(x, y + fixed(30 * i), scale, i);
    }

    internal void DrawClientSettingsHeader(fixed x, fixed y, fixed scale)
    {
        // Top
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(--_drawnHudId, "Consolidate settings");
        DebugDraw();

        // Bottom
        int count = ZH2Game::GameContext.RequestedClientSettingCount;
        int persistingCount = ZH2Game::PersistingGameContext.RequestedClientSettingCount;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_YELLOW);

        BCSUtils::HudSetPoint(x, y + 15.0);
        BCSUtils::HudDrawText(--_drawnHudId, "Note: \cjUpdating CVars makes use of ConsoleCommand, which could possibly be phased out of the engine in the future.");
        DebugDraw();

        // Inform client of cl_protectcvars if set.
        if (ZH2Game::GetProtectCVars())
        {
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(CR_YELLOW);

            BCSUtils::HudSetPoint(x, y + 25.0);
            BCSUtils::HudDrawText(--_drawnHudId, "Note: \cjyou have enabled 'cl_protectcvars', which means any changes here are reverted when you disconnect. Please disable it to persist them.");
            DebugDraw();
            
            y += 10.0;
        }

        // Inform user of the issue with ConsoleCommand
        BCSUtils::HudSetPoint(x, y + 25.0);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "Total invalid settings: \cd" + str(count) + "\cj/\cd" + str(persistingCount) + "\cj.");

        // Clickable buttons
        if (DrawClickableText(--_drawnHudId, x, y + 40.0, 140.0 * scale, 10.0 * scale, "Open keybinds menu"))
            Settings::CloseMenuAndOpenCustomizeMenu();

        if (DrawClickableText(--_drawnHudId, x, y + 55.0, 140.0 * scale, 10.0 * scale, "Open zombie horde 2 menu"))
            Settings::CloseMenuAndOpenZh2Menu();

        if (DrawClickableText(--_drawnHudId, x, y + 70.0, 140.0 * scale, 10.0 * scale, "Refresh settings"))
            Settings::UpdateCurrentClientSettings();

        if (DrawClickableText(--_drawnHudId, x, y + 85.0, 140.0 * scale, 10.0 * scale, "Close settings"))
            Settings::CloseClientSettingsMenu();
    }

    internal void DrawInvalidSetting(fixed x, fixed y, fixed scale, int index)
    {
        str type = Settings::GetInvalidClientSettingType(index);
        str name = Settings::GetInvalidClientSettingName(index);
        int value = Settings::GetInvalidClientSettingValue(index);
        str label = Settings::GetInvalidClientSettingLabel(index);

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_WHITE);

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(--_drawnHudId, type == "cvar" ? "CVar" : "Keybind");

        BCSUtils::HudSetPoint(x + 90.0, y);
        BCSUtils::HudDrawText(--_drawnHudId, "\cd" + name);

        BCSUtils::HudSetPoint(x + 220.0, y);
        if (type == "cvar") BCSUtils::HudDrawText(--_drawnHudId, "\cd" + str(value));
        else BCSUtils::HudDrawText(--_drawnHudId, "\cd" + (value ? "bound" : "unbound"));

        BCSUtils::HudSetPoint(x + 290.0, y);
        if (type == "cvar") BCSUtils::HudDrawText(--_drawnHudId, "currently \cd" + str(GetCvar(name)));
        else BCSUtils::HudDrawText(--_drawnHudId, "currently \cd" + (BCSUtils::KeyBound(name) ? "bound" : "unbound"));

        // Possibly update CVar.
        // Restrictions of ConsoleCommand prevents us from binding/unbinding, so this is not supported.
        if (type == "cvar")
        {
            if (DrawClickableText(--_drawnHudId, x + 400.0, y, 100.0 * scale, 10.0 * scale, "Update CVar"))
                UpdateSettingToRequested(index);
        }
        
        BCSUtils::HudSetTextColor(CR_WHITE);

        BCSUtils::HudSetPoint(x, y + 10.0);
        BCSUtils::HudDrawText(--_drawnHudId, label);
    }

    internal void UpdateSettingToRequested(int index)
    {
        str type = Settings::GetInvalidClientSettingType(index);

        // Failsafe, should not allow when we try (un)bind a key
        if (type != "cvar")
            return;

        str name = Settings::GetInvalidClientSettingName(index);
        int value = Settings::GetInvalidClientSettingValue(index);
        
        // ConsoleCommand because SetCVar / SetGameplaySetting do not allow changing CVars we define.
        ConsoleCommand(name + " " + str(value));

        Settings::UpdateCurrentClientSettings();
    }
}