#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal bool GetIsUseKeyKeyBound() { return BCSUtils::KeyBound("+use"); }
    internal str GetUseKey() { return StrParam(k:"+use"); }

    internal void DrawDeathCamHud()
    {
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0, 480.0);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_TOP);

        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        fixed x = 320.0,
              y = BCSUtils::HudTop() + 50.0;

        _drawnHudId = HUDID_DEATHCAM;
        DrawDeathCamMessage(x, y);
    }

    internal void DrawDeathCamMessage(fixed x, fixed y)
    {
        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetDisappearTime(0.5);

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_RED);
        BCSUtils::HudDrawText(--_drawnHudId, "You are dead");
        DebugDraw();

        str message = GetIsUseKeyKeyBound()
            ? "Press " + GetUseKey() + " to spectate"
            : "Please bind a key for \"use\" in order to spectate";

        BCSUtils::HudSetPoint(x, y + 8.0);
        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, message);
        DebugDraw();
    }
}