#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    #define BAR_AIRSUPPLY_NAME "AIRBAR1"
    #define BAR_AIRSUPPLY_METER_NAME "AIRBAR2"
	#define BAR_AIRSUPPLY_WIDTH 128
	#define BAR_AIRSUPPLY_HEIGHT 10

    #define BAR_SPRINT_NAME "SPRNBAR1"
    #define BAR_SPRINT_METER_NAME "SPRNBAR2"
	#define BAR_SPRINT_WIDTH 128
	#define BAR_SPRINT_HEIGHT 10

    #define BLUR_BLACK_GRAPHIC "BLURBLAC"
    #define BLUR_GREEN_GRAPHIC "BLURGREN"
    #define BLUR_RED_GRAPHIC "BLURRED"
    #define BLUR_ORANGE_GRAPHIC "BLURORAN"

    #define HUD_FIRE_GRAPHIC "HUD_FIR"
    #define HUD_INFECTFIRE_GRAPHIC "HUD_IFR"

    #define RESIST_TIME_TOKEN "%t"
    #define RESIST_PLURAL_TOKEN "%p"

    #define HUD__ZOMBIE_ABILITY_GRAPHIC "HUD_FIR"

    #define HUDSHAKE_INTENSITYBASE 50.0
    #define HUDSHAKE_FREQUENCYBASE 50.0

    // SNIPER GRAPHICS
    #define HUD_WEAPONSNIPER_BACKGROUNDNAME "snipzm1"
    #define HUD_WEAPONSNIPER_METERNAME "snipzm2"
    #define HUD_WEAPONSNIPER_METERPOINTERNAME "snipzm3"

    // Other
    #define WEAPON_RADIO_MAXDRAWNTRACKS 3

    /* HUD IDS */

    // Base IDs
    #define HUD_DEBUG_COORDINATES 4500
    #define HUD_BASE 5000
    #define HUD_CURSOR HUD_BASE - 1

    // Individual HUD parts.
    #define HUD_FULLSERVER HUD_BASE
    #define HUD_VERSION HUD_BASE + 10
    #define HUD_ROUND HUD_BASE + 20
    #define HUD_RESISTS HUD_BASE + 500
    #define HUD_DEBUG HUD_BASE + 500
    #define HUD_ADMIN HUD_BASE + 200
    #define HUD_CLIENTSETTING HUD_BASE + 200
    #define HUD_DEATHCAM HUD_BASE + 10
    #define HUD_WEAPON HUD_BASE + 10
    #define HUD_GAME HUD_BASE + 100
    #define HUD_PLAYER HUD_BASE + 100
    #define HUD_ENDING HUD_BASE + 500
    #define HUD_SUMMARY HUD_BASE + 500
    
    internal enum AdminMenuT : int
    {
        MENU_START,
        MENU_PLAYER,
        MENU_TIMER,
        MENU_ROUND,
        MENU_RESIST,
    };

    internal enum AdminPlayerSubMenuT : int
    {
        MENU_NONE,
        MENU_PLAYERSPECIFIC,
        MENU_ALL,
    };

    internal enum HudFireTypeT : int
    {
        FIRETYPENORMAL,
		FIRETYPEINFECT,
    };
}