#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    #define BAR_AIRSUPPLY_NAME "AIRBAR1"
    #define BAR_AIRSUPPLY_METER_NAME "AIRBAR2"
	#define BAR_AIRSUPPLY_WIDTH 128
	#define BAR_AIRSUPPLY_HEIGHT 10

    #define BAR_SPRINT_NAME "SPRNBAR1"
    #define BAR_SPRINT_METER_NAME "SPRNBAR2"
	#define BAR_SPRINT_WIDTH 128
	#define BAR_SPRINT_HEIGHT 10

    #define BLUR_BLACK_GRAPHIC "BLURBLAC"
    #define BLUR_GREEN_GRAPHIC "BLURGREN"
    #define BLUR_RED_GRAPHIC "BLURRED"
    #define BLUR_ORANGE_GRAPHIC "BLURORAN"

    #define HUD_FIRE_GRAPHIC "HUD_FIR"
    #define HUD_INFECTFIRE_GRAPHIC "HUD_IFR"

    #define RESIST_TIME_TOKEN "%t"
    #define RESIST_PLURAL_TOKEN "%p"

    #define HUD__ZOMBIE_ABILITY_GRAPHIC "HUD_FIR"

    #define HUDSHAKE_INTENSITYBASE 50.0
    #define HUDSHAKE_FREQUENCYBASE 50.0

    // SNIPER GRAPHICS
    #define HUDID_WEAPONSNIPER_BACKGROUNDNAME "snipzm1"
    #define HUDID_WEAPONSNIPER_METERNAME "snipzm2"
    #define HUDID_WEAPONSNIPER_METERPOINTERNAME "snipzm3"

    // Other
    #define WEAPON_RADIO_MAXDRAWNTRACKS 3

    /* HUD IDS */

    // Base IDs
    #define HUDID_DEBUG_COORDINATES 4500
    #define HUDID_BASE 5000
    #define HUDID_CURSOR HUDID_BASE - 1

    // Individual HUD parts.
    #define HUDID_FULLSERVER HUDID_BASE
    #define HUDID_VERSION HUDID_BASE + 10
    #define HUDID_ROUND HUDID_BASE + 20
    #define HUDID_RESISTS HUDID_BASE + 500
    #define HUDID_DEBUG HUDID_BASE + 500
    #define HUDID_ADMIN HUDID_BASE + 200
    #define HUDID_CLIENTSETTING HUDID_BASE + 200
    #define HUDID_DEATHCAM HUDID_BASE + 10
    #define HUDID_WEAPON HUDID_BASE + 10
    #define HUDID_GAME HUDID_BASE + 100
    #define HUDID_PLAYER HUDID_BASE + 100
    #define HUDID_ENDING HUDID_BASE + 500
    #define HUDID_SUMMARY HUDID_BASE + 500
    
    internal enum AdminMenuT : int
    {
        ADMINMENU_START,
        ADMINMENU_PLAYER,
        ADMINMENU_TIMER,
        ADMINMENU_ROUND,
        ADMINMENU_RESIST,
    };

    internal enum AdminMenuPlayerTargetT : int
    {
        MENUTARGET_NONE,
        MENUTARGET_PLAYERSPECIFIC,
        MENUTARGET_ALL,
    };

    internal enum HudFireTypeT : int
    {
        FIRETYPENORMAL,
		FIRETYPEINFECT,
    };
}