#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    #define BAR_AIRSUPPLY_NAME "AIRBAR1"
    #define BAR_AIRSUPPLY_METER_NAME "AIRBAR2"
	#define BAR_AIRSUPPLY_WIDTH 128
	#define BAR_AIRSUPPLY_HEIGHT 10

    #define BAR_SPRINT_NAME "SPRNBAR1"
    #define BAR_SPRINT_METER_NAME "SPRNBAR2"
	#define BAR_SPRINT_WIDTH 128
	#define BAR_SPRINT_HEIGHT 10

    #define BLUR_BLACK_GRAPHIC "BLURBLAC"
    #define BLUR_GREEN_GRAPHIC "BLURGREN"
    #define BLUR_RED_GRAPHIC "BLURRED"
    #define BLUR_ORANGE_GRAPHIC "BLURORAN"

    #define HUD_FIRE_GRAPHIC "HUD_FIR"
    #define HUD_INFECTFIRE_GRAPHIC "HUD_IFR"

    #define RESIST_TIME_TOKEN "%t"
    #define RESIST_PLURAL_TOKEN "%p"

    #define HUD__ZOMBIE_ABILITY_GRAPHIC "HUD_FIR"

    #define HUDSHAKE_INTENSITYBASE 50.0
    #define HUDSHAKE_FREQUENCYBASE 50.0

    // SNIPER GRAPHICS
    #define HUD_WEAPONSNIPER_BACKGROUNDNAME "snipzm1"
    #define HUD_WEAPONSNIPER_METERNAME "snipzm2"
    #define HUD_WEAPONSNIPER_METERPOINTERNAME "snipzm3"

    // Other
    #define WEAPON_RADIO_MAXDRAWNTRACKS 3

    #define HUD_DEBUG 4500

    #define HUD_BASE 5000
    #define HUD_CURSOR HUD_BASE
    #define HUD_VERSION HUD_CURSOR + 3
    #define HUD_PLAYERSTATUS HUD_VERSION + 200
    #define HUD_PLAYERPOWERS HUD_PLAYERSTATUS + 60
    #define HUD_PLAYERBAR HUD_PLAYERPOWERS + 4
    #define HUD_PLAYERBLUR HUD_PLAYERBAR + 3 // Underwater blur, hurt blur, hurt blur (heartbeat based).
    #define HUD_PLAYERINVENTORY HUD_PLAYERBLUR + 100
    #define HUD_PREGAMESTATE HUD_PLAYERINVENTORY + 2
    #define HUD_TIMER HUD_PREGAMESTATE + 3
    #define HUD_PLAYER_STATES HUD_TIMER + 1
    #define HUD_ROUND_STATES HUD_PLAYER_STATES + 1
    #define HUD_TIMER_STATES HUD_ROUND_STATES + 1
    #define HUD_RESIST_STATES HUD_TIMER_STATES + 1
    #define HUD_GAME HUD_RESIST_STATES + 2
    #define HUD_PLAY_TIME HUD_GAME + 1
    #define HUD_FULLSERVER HUD_PLAY_TIME + 12 // Every character of "Full Server!" takes an id.

    #define HUD_RESISTS HUD_FULLSERVER + 2 * MAX_RESISTS
    #define HUD_ADMIN HUD_RESISTS + 200

    // Stat specific drawing uses a lot of IDs because it currently draws 2 things for each player.
    #define HUD_ENDINGHEADER HUD_ADMIN + 10
    #define HUD_ENDINGSURVIVORS HUD_ENDINGHEADER + 150
    #define HUD_ENDINGHORDE HUD_ENDINGSURVIVORS + 150
    #define HUD_ENDINGDEAD HUD_ENDINGHORDE + 150
    #define HUD_ENDINGHUMANKILLS HUD_ENDINGDEAD + 150
    #define HUD_ENDINGZOMBIEKILLS HUD_ENDINGHUMANKILLS + 150
    #define HUD_ENDINGINFECTS HUD_ENDINGZOMBIEKILLS + 150

    #define HUD_SUMMARYHEADER HUD_ENDINGINFECTS + 10
    #define HUD_SUMMARYTIP HUD_ENDINGINFECTS + 5
    #define HUD_SUMMARYMAPLIST HUD_SUMMARYTIP + 100
    
    #define HUD_CLIENTSETTINGSHEADER HUD_SUMMARYMAPLIST
    #define HUD_CLIENTSETTING HUD_CLIENTSETTINGSHEADER + 100

    // WEAPONS
    #define HUD_WEAPONSNIPER HUD_CLIENTSETTING + 3 // background, meter, meter pointer
    #define HUD_WEAPONRADIO HUD_WEAPONSNIPER + 100 // just lots of strings that could be drawn

    internal enum AdminMenuT : int
    {
        MENU_START,
        MENU_PLAYER,
        MENU_TIMER,
        MENU_ROUND,
        MENU_RESIST,
    };

    internal enum AdminPlayerSubMenuT : int
    {
        MENU_NONE,
        MENU_PLAYERSPECIFIC,
        MENU_ALL,
    };

    internal enum HudFireTypeT : int
    {
        FIRETYPENORMAL,
		FIRETYPEINFECT,
    };
}