#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawRoundHud()
    {
        fixed scale = ZH2Game::GetHudRoundScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_BOTTOM);

        fixed x = 0.0 + ZH2Game::GetHudRoundOffsetX(),
              y = BCSUtils::HudBottom() - ZH2Game::GetHudRoundOffsetY();
              
        x += _xShakeOffset;
        y += _yShakeOffset;

        // While we are in pregame with no countdown to start, draw the label.
        if (Round::GetActiveKnownRoundState() == Round::STATEPREGAME
            && !RoundTimer::GetAnyTimerActive())
            DrawPregameStateLabel(x + 320.0 / scale, y - 50.0);

        DrawTimer(x + 320.0 / scale, y - 20.0);

        // Bottom left
        x = BCSUtils::HudLeft(),
        y = BCSUtils::HudBottom();
              
        x += _xShakeOffset;
        y += _yShakeOffset;
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_BOTTOM);
        DrawPlayTime(x, y);
    }

    internal void DrawPregameStateLabel(fixed x, fixed y)
    {
        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_RED);
        BCSUtils::HudSetCenterText(true);

        BCSUtils::HudSetStayTime(1.5);
        BCSUtils::HudSetDisappearTime(0.5);

        // Conditionally draw based on the number of clients that are available.
        int availableClients = BCSUtils::ClientCount();
        int minimumRequiredClients = ZH2Game::GetMinimumClientCount();
        
        // The game is ready when we have the minimum number of clients.
        str topMessage = availableClients < minimumRequiredClients
            ? "This game requires atleast " + str(minimumRequiredClients) + " clients."
            : "Game is ready, " + str(availableClients) + " clients available.";
        str bottomMessage = availableClients >= minimumRequiredClients
            ? ZH2Game::GetIsRequestGameStartKeyBound()
                ? "To start, press the 'Request game start' key (" + ZH2Game::GetRequestGameStartKey() + ")"
                : "To start, bind and press the 'Request game start' key."
            : IsNetworkGame()
                ? "Please spectate."
                : "Invoke 'addbot' in the console to add bots to play with.";

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(HUD_PREGAMESTATE, topMessage);
        DebugDraw();

        BCSUtils::HudSetPoint(x, y + 8.0);
        BCSUtils::HudDrawText(HUD_PREGAMESTATE - 1, bottomMessage);
        DebugDraw();
    }

    // TODO: Handle countdown effect (game loop should do the sound)
    internal void DrawTimer(fixed x, fixed y)
    {
        int index = RoundTimer::GetActiveTimerIndex();
        if (!RoundTimer::GetTimerDefined(index) || !RoundTimer::GetTimerActive(index) || !RoundTimer::GetTimerVisible(index))
            return;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetAlpha(1.0);

        // This won't show until the very last draw.
        BCSUtils::HudSetStayTime(0.5);
        BCSUtils::HudSetDisappearTime(0.5);

        // Label
        BCSUtils::HudSetPoint(x, y - 10.0);
        BCSUtils::HudDrawText(HUD_TIMER, RoundTimer::GetTimerLabel(index));
        DebugDraw();
        
        // Time left.
        int ticsLeft = RoundTimer::GetTimerTicsLeft(index);
        str timerFormatted = Utils::FormatTics(ticsLeft, RoundTimer::GetTimerDrawDecimals(index));
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(HUD_TIMER - 1, timerFormatted);
        DebugDraw();

        // If the timer has countdowns enabled, then the last 10 seconds should have a fading red label on top.
        // First 18 tics of every 35 we display this.
        if (RoundTimer::GetTimerDoCountdown(index) && ticsLeft <= 350)
        {
            int tics = ticsLeft % 35;
            fixed alpha = (tics > 18) ? (1.0 - fixed(35 - tics) / 18.0) : 0.0;
            if (alpha == 0.0)
                return;

            BCSUtils::HudSetAlpha(alpha);
            BCSUtils::HudSetTextColor(CR_RED);
            BCSUtils::HudDrawText(HUD_TIMER - 2, timerFormatted);
            DebugDraw();
        }
    }

    internal void DrawPlayTime(fixed x, fixed y)
    {
        if (Round::GetActiveKnownRoundState() != Round::STATEPLAYING)
            return;

        int timer = Game::GetPlayTime();
        if (timer == 0) return;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetStayTime(0.5);
        BCSUtils::HudSetDisappearTime(0.5);

        // Gradual alpha increase as play time goes on.
        // 40 tics, configurable.
        int fadeInDurationTics = 40;
        fixed progress = fixed(timer) / fixed(fadeInDurationTics);
        fixed alpha = BCSUtils::Clamp(progress, 0.0, 1.0);
        BCSUtils::HudSetAlpha(alpha);

        str timerFormatted = Utils::FormatTics(timer, true);

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(HUD_PLAY_TIME, "Playing: " + timerFormatted);
        DebugDraw();
    }
}