#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    internal void SpawnBloodFromBulletPuff(int sourceId, int targetId)
    {
        // Server has disabled blood.
        if (!ZH2Game::GetServerEnabledBlood())
            return;

        // Activator should be the bulletpuff. This contains the most relevant information.
        if (!BCSUtils::StrIEquals(GetActorClass(0), HUMAN_BULLETPUFF))
            return;

        str packet = Packet::Packet_New();

        // Puff
        packet = Packet::Packet_Append(packet, GetActorX(0), Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, GetActorY(0), Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, GetActorZ(0), Packet::PACKET_WORD);

        // Source/target id
        packet = Packet::Packet_Append(packet, sourceId, Packet::PACKET_BYTE);
        packet = Packet::Packet_Append(packet, targetId, Packet::PACKET_BYTE);

        if(!NamedSendNetworkString("zh2_internal_dec_blood_spawn_client", packet))
            Logger::LogError(LogSource, "Failed to invoke zh2_internal_dec_blood_spawn_client. Message packet: '" + packet + "'.");
    }

    script "zh2_internal_dec_blood_spawn_client" (raw messagePack) clientside
    {
        if (PlayerIsBot(ConsolePlayerNumber())) terminate;
        SetActivatorToPlayer(ConsolePlayerNumber());

        // 0 - Nobody.
        // 1 - Only locally.
        // 2 - Everyone.
        int bloodType = ZH2Game::GetClientBloodType();
        if (bloodType == 0) terminate;

        // Puff
        messagePack = Packet::Packet_Read(messagePack, Packet::PACKET_WORD);
        fixed puffX = Packet::Packet_Rval;

        messagePack = Packet::Packet_Read(messagePack, Packet::PACKET_WORD);
        fixed puffY = Packet::Packet_Rval;

        messagePack = Packet::Packet_Read(messagePack, Packet::PACKET_WORD);
        fixed puffZ = Packet::Packet_Rval;

        // Source/Target
        messagePack = Packet::Packet_Read(messagePack, Packet::PACKET_BYTE);
        int sourceId = Packet::Packet_Rval;

        messagePack = Packet::Packet_Read(messagePack, Packet::PACKET_BYTE);
        int targetId = Packet::Packet_Rval;

        // Now check if we were the source.
        if (bloodType == 1 && sourceId != ConsolePlayerNumber()) terminate;

        int sourceTid = Identity::GetTid(sourceId),
            targetTid = Identity::GetTid(targetId);

        fixed sourceX = GetActorX(sourceTid),
              sourceY = GetActorY(sourceTid),
              sourceZ = GetActorZ(sourceTid),
              viewHeight = GetActorViewHeight(sourceTid) - 8.0;

        fixed targetX = GetActorX(targetTid),
              targetY = GetActorY(targetTid),
              targetZ = GetActorZ(targetTid),

              // Get the target's angle so we can offset the blood to a new relative position each tic.
              targetAngle = GetActorAngle(targetTid);

        // Normalized vector of the direction to spawn the blood at.
        fixed dirVectorX = puffX - sourceX,
              dirVectorY = puffY - sourceY,
              dirVectorZ = puffZ - (sourceZ + viewHeight);
        BCSUtils::Normalize3D(dirVectorX, dirVectorY, dirVectorZ);
        dirVectorX = -BCSUtils::r1,
        dirVectorY = -BCSUtils::r2,
        dirVectorZ = -BCSUtils::r3;

        // We undo the rotation and generated a normalized vector of the result.
        // This is the base vector of the blood direction.
        // The angle is applied each time we spawn blood.
        BCSUtils::RotateVector(dirVectorX, dirVectorY, -targetAngle);
        dirVectorX = BCSUtils::r1,
        dirVectorY = BCSUtils::r2;

        // Determine the relative offset to spawn the actual blood at.
        fixed posVectorX = puffX - targetX,
              posVectorY = puffY - targetY,
              posVectorZ = puffZ - targetZ;
        BCSUtils::RotateVector(posVectorX, posVectorY, -targetAngle);
        posVectorX = BCSUtils::r1;
        posVectorY = BCSUtils::r2;

        if (!SetActivatorToPlayer(sourceId))
            terminate;
        int weaponIndex = Item::GetItemIndexByName(GetWeapon());
        if (weaponIndex == -1)
            terminate;
        SetActivator(-1);

        Player::PlayerSpecieT specie = Player::GetPlayerSpecie(targetId);

        // This is determined when we spawn blood.
        // If the specie changed we want to adjust to the correct blood type.
        str GetBloodActor()
        {
            return specie == Player::SPECIEZOMBIE ? "ZH2ZombieBlood" : "ZH2HumanBlood"; // "DebugDrop";
        }

        for (int i = 0; i < Item::GetItemBloodSeverity(weaponIndex); ++i)
        {
            // Apply a bit of a random angle, pitch and speed increase for each instance.
            Math::RotateVector3D(dirVectorX, dirVectorY, dirVectorZ, Math::FRandom(-0.01, 0.01), Math::FRandom(-0.01, 0.01));
            fixed speed = Math::FRandom(1.2, 6.0);
            fixed finalDirX = ((fixed)BCSUtils::r1) * speed,
                  finalDirY = ((fixed)BCSUtils::r2) * speed,
                  finalDirZ = ((fixed)BCSUtils::r3) * speed;
            SpawnBloodAtVector(targetTid, GetBloodActor(), posVectorX, posVectorY, posVectorZ, finalDirX, finalDirY, finalDirZ);
        }

        // Additional blood tics.
        int bleedingTics = Item::GetItemBloodTics(weaponIndex);
        while(bleedingTics-- > 0)
        {
            // No longer alive.
            if (!BCSUtils::ActorIsAlive(targetTid))
                terminate;

            SpawnBloodAtVector(targetTid, GetBloodActor(), posVectorX, posVectorY, posVectorZ, dirVectorX, dirVectorY, dirVectorZ);
            Delay(const: 1);
        }
    }

    internal void SpawnBloodAtVector(int actorTid, str bloodActor, fixed positionVectorX, fixed positionVectorY, fixed positionVectorZ, fixed velocityX, fixed velocityY, fixed velocityZ)
    {
        // Determine where to spawn the blood, relative to the actor.
        // We do this here again to get an updated position and angle.
        fixed x = GetActorX(actorTid),
              y = GetActorY(actorTid),
              z = GetActorZ(actorTid),
              angle = GetActorAngle(actorTid);

        // Rotate back the angle.
        BCSUtils::RotateVector(positionVectorX, positionVectorY, angle);
        positionVectorX = BCSUtils::r1,
        positionVectorY = BCSUtils::r2;

        x += positionVectorX,
        y += positionVectorY,
        z += positionVectorZ;

        // Also rotate back the velocity's angle.
        BCSUtils::RotateVector(velocityX, velocityY, angle);
        velocityX = BCSUtils::r1;
        velocityY = BCSUtils::r2;

        int tid = UniqueTID();
        SpawnForced(bloodActor, x, y, z, tid);
        SetActorVelocity(tid, velocityX, velocityY, velocityZ, false, false);
    }
}
