#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    #define MAX_RADIO_TRACKS 40
    #define RADIO_COOLDOWN_SECONDS 30

    struct RadioTrackCollectionContextT
    {
        RadioTrackContextT Collection[MAX_RADIO_TRACKS];
        int Size;
    };

    struct RadioTrackContextT
    {
        str lumpName;
        str Name;
        str Author;
        str Remark;
    };
}