#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    #define MAX_RADIO_TRACKS 40
    #define RADIO_COOLDOWN_SECONDS 30

    // This constant is also defined in DECORATE and defines the TID on an actor that must always face the console player.
    #define FACEPLAYER_TID 1000000000

    struct RadioTrackCollectionContextT
    {
        RadioTrackContextT Collection[MAX_RADIO_TRACKS];
        int Size;
    };

    struct RadioTrackContextT
    {
        str lumpName;
        str Name;
        str Author;
        str Remark;
    };
}