#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    script "zh2_dec_setfire_area" (raw area, raw initialDamageTics, raw subsequentDamageTics)
    {
        AreaSetOnFireAtTid((int)area, (int)initialDamageTics, (int)subsequentDamageTics);
    }

    // Sets the area on fire at the given tid.
    internal void AreaSetOnFireAtTid(int area, int initialDamageTics, int subsequentDamageTics)
    {
        str inflictorClass = GetActorClass(0);

        // Will just be -1 if we passed nobody.
        int ownerId = Identity::GetId(GetActorProperty(0, APROP_TARGETTID));

        bool hasHit = false;
        str logMessage;
        BuildMsg(logMessage = StrParam())
        {
            Append(s:"Fire has hit ");
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                if (!PlayerIngame(i))
                    continue;

                fixed distance = BCSUtils::ActorDistance(Identity::GetTid(i), 0);
                if (distance > fixed(area))
                    continue;

                if (hasHit)
                    Append(s:", ");

                hasHit = true;
                Append(s:BCSUtils::PlayerName(i));
                SetOnFire(ownerId, i, inflictorClass, initialDamageTics, subsequentDamageTics);
            }

            if (ownerId != -1) Append(s:". Source player: " + BCSUtils::PlayerName(ownerId) + ". Inflictor: " + inflictorClass + ".");
            else Append(s:".");
        }

        if (hasHit)
            Logger::LogDebug(LOGSOURCE , logMessage);
    }

    internal void SetOnFire(int ownerId, int targetId, str inflictorClass, int initialBurningDamageTics, int subsequentBurningDamageTics)
    {
        // Zombie-only.
        if (!Player::GetPlayerIsZombie(targetId))
            return;

        // Determine tics. If the player is already burning then add the subsequent tics.
        // Other wise add the initial tics.
        int tics = Power::GetPlayerHasPower(targetId, Power::POWERFIREBURNING) ?
            subsequentBurningDamageTics :
            initialBurningDamageTics;

        // Set up the source of the fire.
        Player::SetPlayerDamageSourceActive(targetId, ownerId, inflictorClass, Player::SOURCE_FIRE);

        Power::AddPlayerPowerTics(targetId, Power::POWERFIREBURNING, tics);
    }

    internal bool IsOnFire()
    {
        return PlayerIsOnFire(PlayerNumber());
    }

    internal bool PlayerIsOnFire(int id)
    {
        return Power::GetPlayerHasPower(id, Power::POWERFIREBURNING);
    }
}
