#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    script "zh2_dec_triggerreward"(raw indexRaw)
    {
        // Do not allow items to be used if the round isn't playing.
        // However, an exception is made if the round is the pregame as the player will be reset anyway.
        Round::KnownRoundStateT state = Round::GetActiveKnownRoundState();
        if (state != Round::STATEPREGAME && state != Round::STATESTARTING && Round::GetCurrentRoundJoinable())
        {
            Logger::LogActivator("Wait for a zombie to be chosen before getting your reward.");
            terminate;
        }
        if (Round::GetCurrentRoundIsEnding())
        {
            Logger::LogActivator("The round has ended. You may not get a reward now.");
            terminate;
        }

        int index = (int)indexRaw;

        // Verify the user has the item.
        // If the user gave a bogus type or doesn't have the item, it is caught here.
        Reward::RewardItemTypeFlagsT type = Reward::GetRewardItemTypeByIndex(index);
        str itemName = Reward::ContainerTypeToItemName(type);
        if ((raw)itemName == 0 || itemName == "")
        {
            Logger::LogWarning(LOGSOURCE , "Player " + BCSUtils::PlayerName(PlayerNumber()) + " attempted to trigger reward with bad index: " + str(index) + ".");
            terminate;
        }

        if (CheckInventory(itemName) == 0)
        {
            Logger::LogWarning(LOGSOURCE , "Player " + BCSUtils::PlayerName(PlayerNumber()) + " attempted to trigger reward but doesn't have container " + itemName + " in their inventory.");
            terminate;
        }

        Reward::GiveReward(type);
    }
}
