#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Round
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LogSource, "Setting survival gamemode profile for round.");
        
        Round::DefineRoundByKnown(Round::STATEPREGAME, false, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, false, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, false, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, true, false);
        Round::DefineRoundByKnown(Round::STATEENDING, true, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, true, true);
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LogSource, "Setting escape gamemode profile for round.");

        Round::DefineRoundByKnown(Round::STATEPREGAME, false, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, false, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, false, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, true, false);
        Round::DefineRoundByKnown(Round::STATEENDING, true, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, true, true);
    }
}