#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Round
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE , "Setting survival gamemode profile for round.");
        
        Round::DefineRoundByKnown(Round::STATEPREGAME, true, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, true, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, true, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, false, false);
        Round::DefineRoundByKnown(Round::STATEENDING, false, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, false, true);
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE , "Setting escape gamemode profile for round.");

        Round::DefineRoundByKnown(Round::STATEPREGAME, true, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, true, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, true, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, false, false);
        Round::DefineRoundByKnown(Round::STATEENDING, false, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, false, true);
    }
}