#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Round
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LogSource, "Setting survival gamemode profile for round.");
        
        Round::DefineRoundByKnown(Round::STATEPREGAME, true);
        Round::DefineRoundByKnown(Round::STATESTARTING, true);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, true);
        Round::DefineRoundByKnown(Round::STATEPLAYING, false);
        Round::DefineRoundByKnown(Round::STATEENDING, false);
        Round::DefineRoundByKnown(Round::STATEVOTING, false);
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LogSource, "Setting escape gamemode profile for round.");

        Round::DefineRoundByKnown(Round::STATEPREGAME, true);
        Round::DefineRoundByKnown(Round::STATESTARTING, true);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, true);
        Round::DefineRoundByKnown(Round::STATEPLAYING, false);
        Round::DefineRoundByKnown(Round::STATEENDING, false);
        Round::DefineRoundByKnown(Round::STATEVOTING, false);
    }
}