#ifdef __IMPORTED__
    #error This file must be #included.
#endif

/* SERVERSIDE CONTEXT VALIDATION */

#define VALIDATE_IS_SERVERSIDE_FUNCTION() \
    if (BCSUtils::IsClientOnly()) \
    { \
        Logger::LogError(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s:"\cj attempted to start clientside. Call must be serverside!")); \
        return; \
    }

#define VALIDATE_IS_SERVERSIDE_FUNCTION_RETURN(returnValue) \
    if (BCSUtils::IsClientOnly()) \
    { \
        Logger::LogError(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s:"\cj attempted to start clientside. Call must be serverside!")); \
        return returnValue; \
    }

/* CLIENTSIDE CONTEXT VALIDATION */

#define VALIDATE_IS_CLIENTSIDE_FUNCTION() \
    if (BCSUtils::IsServerOnly()) \
    { \
        Logger::LogError(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s:"\cj attempted to start serverside. Call must be clientside!")); \
        return; \
    }

#define VALIDATE_IS_CLIENTSIDE_FUNCTION_RETURN(returnValue) \
    if (BCSUtils::IsServerOnly()) \
    { \
        Logger::LogError(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s: "\cj attempted to start serverside. Call must be clientside!")); \
        return returnValue; \
    }