#ifdef __IMPORTED__
    #error This file must be #included.
#endif

/* PLAYER ID VALIDATION */

#define VALIDATE_ID_VALID_SCRIPT(id) \
    if (!Identity::IsValidID(id)) \
    { \
        Logger::LogWarning(LOGSOURCE, StrParam(s:"Script \cd", s:__SCRIPT__, s:"\cj - Invalid player ID: ", d:id)); \
        terminate; \
    }

#define VALIDATE_ID_VALID_FUNCTION(id) \
    if (!Identity::IsValidID(id)) \
    { \
        Logger::LogWarning(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s:"\cj - Invalid player ID: ", d:id)); \
        return; \
    }

#define VALIDATE_ID_VALID_FUNCTION_RETURN(id, returnValue) \
    if (!Identity::IsValidID(id)) \
    { \
        Logger::LogWarning(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s:"\cj - Invalid player ID: ", d:id)); \
        return returnValue; \
    }


/* PLAYER TID VALIDATION */

#define VALIDATE_TID_VALID_SCRIPT(tid) \
    if (!Identity::IsValidTID(tid)) \
    { \
        Logger::LogWarning(LOGSOURCE, StrParam(s:"Script \cd", s:__SCRIPT__, s:"\cj - Invalid player TID: ", d:tid)); \
        terminate; \
    }

#define VALIDATE_TID_VALID_FUNCTION(tid) \
    if (!Identity::IsValidTID(tid)) \
    { \
        Logger::LogWarning(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s:"\cj - Invalid player TID: ", d:tid)); \
        return; \
    }

#define VALIDATE_TID_VALID_FUNCTION_RETURN(tid, returnValue) \
    if (!Identity::IsValidTID(tid)) \
    { \
        Logger::LogWarning(LOGSOURCE, StrParam(s:"Function \cd", s:__FUNCTION__, s:"\cj - Invalid player TID: ", d:tid)); \
        return; \
    }