#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Verify the sync id has not reached an out-of-bounds value.
// Note, to avoid issues we inline the variables, or they have a chance to not be correct.
#define VERIFY_SYNCID(syncId, high, length) \
    int highInline = high; \
    int lengthInline = length; \
    int low = highInline - lengthInline; \
    if (low > syncId) \
    { \
        Logger::LogError(LOGSOURCE, FormatLog(SYNC_CATEGORY, StrParam(s:"Sync system function '\cd", s:__FUNCTION__, s:"\cj' has an out of bounds sync value. Current sync id \cd", d:syncId, s:"\cj is below low limit of (\cd", d:highInline, s:"\cj - \cd", d:lengthInline, s:"\cj) = \cd", d:low, s:"\cj."))); \
    } \
    else \
    { \
        Logger::LogDebug(LOGSOURCE, FormatLog(SYNC_CATEGORY, StrParam(s:"Sync system function '\cd", s:__FUNCTION__, s:"\cj' id is now \cd", d:low, s:"\cj <= \cd", d:syncId, s:"\cj <= \cd", d:highInline, s:"\cj."))); \
    }