#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define MAX_TRACKEDPROPERTIES 50

strict namespace TrackedProperties
{
    enum TrackedPropertyType : int
    {
        TRACKED_TOTALLYFROZEN,
    };

    extern bool AddProperty(int index);
    extern bool AddPlayerProperty(int id, int index);
    extern bool RemoveProperty(int index);
    extern bool RemovePlayerProperty(int id, int index);
}