#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Packet"

strict namespace Packet
{
    internal raw _tmp[5];

    raw Value;

    internal int ReadUnsignedByte(str pac, int pos)
    {
        int b = GetChar(pac, pos);

        if(b < 0)
            b += 256;

        return b;
    }

    int GetMaxSize()
    {
        int maxPacketSize = GetCVar("sv_maxpacketsize");

        if(maxPacketSize > 2048)
            return 2048;

        return maxPacketSize;
    }

    int GetSize(str pac)
    {
        return StrLen(pac) + PACKET_NATIVE_HEADER_SIZE;
    }

    // Does nothing currently, but it might be needed in the future.
    str New()
    {
        return "";
    }

    str Append(str pac, raw val)
    {
        int tmp;

        for(int i = PACKET_WORD_SIZE - 1; i >= 0; i--)
        {
            tmp = val & ((1 << PACKET_BYTE_BITS) - 1);

            _tmp[i] = tmp + ' ';

            val >>= PACKET_BYTE_BITS;
        }

        return StrParam(s:pac, a:_tmp);
    }

    str AppendStr(str pac, str val)
    {
        val = StrLeft(val, 2048);
        pac = Append(pac, StrLen(val));

        return StrParam(s:pac, s:val);
    }

    bool Send(str scriptName, str pac, int client = -1)
    {
        int maxPacketSize = GetMaxSize(), packetSize = GetSize(pac);

        if(packetSize > maxPacketSize)
        {
            Log(s:"Send ERROR: Packet is too large (", i:packetSize, s:" bytes)! Current server settings allow for only ", i:maxPacketSize, s:" bytes.");
            return false;
        }

        if(packetSize == PACKET_NATIVE_HEADER_SIZE)
        {
            Log(s:"Send ERROR: Packet is empty. Not sending.");
            return false;
        }

        return (bool)NamedSendNetworkString(scriptName, pac, client);
    }

    str Read(str pac)
    {
        int shiftAmount = 4 * 8, tmp;

        Value = 0;

        for(int i = 0; i < PACKET_WORD_SIZE; i++)
        {
            Value <<= PACKET_BYTE_BITS;
            tmp = (ReadUnsignedByte(pac, i) /*& ((1 << PACKET_BYTE_BITS) - 1)*/) - ' ';

            Value |= tmp;
        }

        return StrMid(pac, PACKET_WORD_SIZE, 0x7FFFFFFF);
    }

    str ReadStr(str pac)
    {
        int len;
        pac = Read(pac);
        len = Value;

        Value = StrLeft(pac, len);

        return StrMid(pac, len, 0x7FFFFFFF);
    }

    int PackValue(int pack, int pos, int width, raw v)
    {
        if(v & PACKET_MSB_MASK)
            v |= 1 << (width - 1);

        v &= ((1 << width) - 1);
        return pack | (v << pos);
    }

    raw UnpackValue(int pack, int pos, int width, bool signed = false)
    {
        int widthm1 = width - 1;
        int v = (pack >> pos) & ((1 << width) - 1), m;

        if(signed && (v & (1 << widthm1)))
        {
            m = 1 << widthm1;
            v = (v ^ m) - m;
        }

        return v;
    }
}

#undef LOGSOURCE