#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Packet"

strict namespace Packet
{
    internal int _tmp[4];

    raw Value;

    internal int ReadUnsignedByte(str pac, int pos)
    {
        int b = GetChar(pac, pos);

        if(b < 0)
            b += 256;

        return b;
    }

    int GetMaxSize(void)
    {
        int maxPacketSize = GetCVar("sv_maxpacketsize");

        if(maxPacketSize > 2048)
            return 2048;

        return maxPacketSize;
    }

    int GetSize(str pac)
    {
        return StrLen(pac) + PACKET_NATIVE_HEADER_SIZE;
    }

    str New()
    {
        return "";
    }

    //str Append(str pac, raw val, int width = PACKET_WORD)
    str Append(str pac, raw val)
    {
        int width = PACKET_WORD;
        int zeroChar = 0x80, max, tmp;

        if( (width < PACKET_WORD) || (width >= PACKET_TOTAL) )
            width = PACKET_WORD;

        switch(width)
        {
            case PACKET_WORD: max = 4; break;
            case PACKET_SHORT: max = 2; break;
            case PACKET_BYTE: max = 1; break;
        }

        for(int i = 0; i < max; i++)
        {
            tmp = val & 0xFF;

            if(!tmp)
            {
                zeroChar |= 1 << i;
                tmp = 0xFF;
            }

            _tmp[i] = tmp;

            val >>= 8;
        }

        return StrParam(s:pac, c:zeroChar, a:(_tmp, 0, max));
    }

    str AppendStr(str pac, str val)
    {
        val = StrLeft(val, 2048);

        pac = Append(pac, StrLen(val));//, PACKET_WORD);

        return StrParam(s:pac, s:val);
    }

    bool Send(str scrip, str pac, int client = -1)
    {
        int maxPacketSize = GetMaxSize(), packetSize = GetSize(pac);

        if(packetSize > maxPacketSize)
        {
            Log(s:"Send ERROR: Packet is too large (", i:packetSize, s:" bytes)! Current server settings allow for only ", i:maxPacketSize, s:" bytes.");
            return false;
        }

        if(packetSize == PACKET_NATIVE_HEADER_SIZE)
        {
            Log(s:"Send ERROR: Packet is empty. Not sending.");
            return false;
        }

        return (bool)NamedSendNetworkString(scrip, pac, client);
    }

    //str Read(str pac, int width = PACKET_WORD)
    str Read(str pac)
    {
        int width = PACKET_WORD;
        int zeroChar = ReadUnsignedByte(pac, 0), max, shiftAmount;

        if( (width < PACKET_WORD) || (width >= PACKET_TOTAL) )
            width = PACKET_WORD;

        switch(width)
        {
            case PACKET_WORD: max = 4; break;
            case PACKET_SHORT: max = 2; break;
            case PACKET_BYTE: max = 1; break;
        }

        shiftAmount = (max - 1) * 8;

        Value = 0;

        for(int i = 0; i < max; i++)
        {
            Value >>= 8;

            if(!(zeroChar & (1 << i)))
            {
                Value &= 0x00FFFFFF;
                Value |= ReadUnsignedByte(pac, i + 1) << shiftAmount;
            }
        }

        return StrMid(pac, max + 1, 0x7FFFFFFF);
    }

    str ReadStr(str pac)
    {
        int len;
        pac = Read(pac);//, PACKET_WORD);
        len = Value;

        Value = StrLeft(pac, len);

        return StrMid(pac, len, 0x7FFFFFFF);
    }
}

#undef LOGSOURCE