#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define PACKET_TOTAL 3
#define PACKET_NATIVE_HEADER_SIZE 13

strict namespace Packet
{
    // To remove with the new packet system.
    internal enum
    {
        PACKET_WORD,
        PACKET_SHORT,
        PACKET_BYTE
    };

    extern raw Value;

    extern int GetMaxSize();
    extern int GetSize(str pac);
    extern str New(void);
    extern str Append(str pac, raw val);
    extern str AppendStr(str pac, str val);
    extern bool Send(str scriptName, str pac, int client = -1);
    extern str Read(str pac);
    extern str ReadStr(str pac);
}