#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    script "zh2_dec_setacid_area" (raw area, raw initialDamageTics, raw subsequentDamageTics)
    {
        // Will just be -1 if we passed nobody.
        int ownerId = Identity::GetId(GetActorProperty(0, APROP_TARGETTID));

        str inflictorClass = GetActorClass(0);

        // Map acid actor to known actor.
        // TODO: Make configurable
        static str itemMap[][] =
        {
            // Note this one doesn't actually have an obituary actor, just added for readability.
            // This therefore isn't used.
            { "ZH2ZombieAcidSpotBig", "ZH2ZombieAcidSpot" },
        };

        foreach(auto item; itemMap)
        {
            if (item[0] == inflictorClass)
            {
                inflictorClass = item[1];
                break;
            }
        }

        AreaSetOnAcidAtTid(ownerId, inflictorClass, (int)area, (int)initialDamageTics, (int)subsequentDamageTics);
    }

    // Sets the area as acidic at the given tid.
    internal void AreaSetOnAcidAtTid(int ownerId, str inflictorClass, int area, int initialDamageTics, int subsequentDamageTics)
    {
        bool hasHit = false;
        str logMessage;
        BuildMsg(logMessage = StrParam())
        {
            Append(s:"Acid has hit ");
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                if (!PlayerIngame(i))
                    continue;

                fixed distance = BCSUtils::ActorDistance(Identity::GetTid(i), 0);
                if (distance > fixed(area))
                    continue;

                if (hasHit)
                    Append(s:", ");

                hasHit = true;
                Append(s:BCSUtils::PlayerName(i));
                SetOnAcid(ownerId, i, inflictorClass, initialDamageTics, subsequentDamageTics);
            }

            if (ownerId != -1) Append(s:". Owner player: " + BCSUtils::PlayerName(ownerId) + ". Inflictor: " + inflictorClass + ".");
            else Append(s:".");
        }

        if (hasHit)
            Logger::LogDebug(LOGSOURCE, logMessage);
    }

    internal void SetOnAcid(int ownerId, int targetId, str inflictorClass, int initialBurningDamageTics, int subsequentBurningDamageTics)
    {
        // Human-only.
        if (!Player::GetPlayerIsHuman(targetId))
            return;

        // Determine tics. If the player is already burning then add the subsequent tics.
        // Other wise add the initial tics.
        int tics = Power::GetPlayerHasPower(targetId, Power::POWERACIDBURNING) ?
            subsequentBurningDamageTics :
            initialBurningDamageTics;

        // Set up the source of the fire.
        Player::SetPlayerDamageSourceActive(targetId, ownerId, inflictorClass, Player::SOURCE_ACID);

        Power::AddPlayerPowerTics(targetId, Power::POWERACIDBURNING, tics);
    }

    internal bool IsOnAcid()
    {
        return PlayerIsOnAcid(PlayerNumber());
    }

    internal bool PlayerIsOnAcid(int id)
    {
        return Power::GetPlayerHasPower(id, Power::POWERACIDBURNING);
    }
}
