#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Decorate"

#include "fire.acs"
#include "acid.acs"
#include "weaponfiring.acs"
#include "items.acs"
#include "blood.acs"
#include "flare.acs"
#include "reward.acs"
#include "liquid.acs"
#include "secondary.acs"
#include "radio/radio.acs"

strict namespace Decorate
{
    internal void TicServer()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (Timer() % 2 == 0)
            TakeChaingunHeat();

        TakeJacksGunSmoke();

        // The player is on fire.
        if (Player::GetOnFire())
        {
            // Player is underwater which gets rid of the power.
            if (BCSUtils::GetActorWaterlevel(0) == 3)
            {
                Power::TakePower(Power::POWERFIREBURNING);
                return;
            }

            if (!SpawnForced("ZH2PlayerOnFireEffect", GetActorX(ActivatorTid()), GetActorY(ActivatorTid()), GetActorZ(ActivatorTid())))
                Logger::LogWarning(LOGSOURCE, "Failed to spawn fire effect for player " + str(PlayerNumber()) + ".");

            if (Timer() % 10 == 0)
                Thing_Damage2(ActivatorTID(), 10, DAMAGETYPE_FIRE);
        }

        // The player is covered in acid.
        if (Player::GetOnAcid())
        {
            // Player is underwater which gets rid of the power.
            if (BCSUtils::GetActorWaterlevel(0) == 3)
            {
                Power::TakePower(Power::POWERACIDBURNING);
                return;
            }

            if (Timer() % 35 == 0)
                Thing_Damage2(ActivatorTID(), 4, DAMAGETYPE_ACID);
        }
    }

    internal void TicClient()
    {
        // Chaingun warning sound when nearly overheating.
        if (GetWeapon() == WEAPON_CHAINGUN_NAME && CheckInventory(WEAPON_CHAINGUN_HEAT_NAME) > 30 && Timer() % 8 == 0)
            AmbientSound("weapons/chaingun/WARNING", 127);

        RotateActorsToClient();
    }


    internal void TakeChaingunHeat()
    {
        if (GetWeapon() == WEAPON_CHAINGUN_NAME && IsFiringWeapon())
            return;

        TakeInventory(WEAPON_CHAINGUN_HEAT_NAME, 1);
    }


    internal void TakeJacksGunSmoke()
    {
        TakeInventory(WEAPON_JACKSGUN_SMOKE_COUNT_NAME, 1);
    }

    // This function rotates any actors with the given TID to the console player.
    internal void RotateActorsToClient()
    {
        // Determine the target tid to look at.
        int cameraTid = CheckPlayerCamera(ConsolePlayerNumber());
        if (cameraTid == -1)
            return;

        SetActorAngle(FACEPLAYER_TID, GetActorAngle(cameraTid));
    }
}

#undef LOGSOURCE
