#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    script "zh2_dec_setfire_area" (raw area, raw initialDamageTics, raw subsequentDamageTics)
    {
		AreaSetOnFireAtTid(
            -1, (int)area, (int)initialDamageTics, (int)subsequentDamageTics);
    }

    script "zh2_dec_setfire_area_targetsource" (raw area, raw initialDamageTics, raw subsequentDamageTics)
    {
		AreaSetOnFireAtTid(
            GetActorProperty(0, APROP_TARGETTID), (int)area, (int)initialDamageTics, (int)subsequentDamageTics);
    }

    // Sets the area on fire at the given tid.
    internal void AreaSetOnFireAtTid(int sourceTid, int area, int initialDamageTics, int subsequentDamageTics)
	{
        // Will just be -1 if we passed nobody.
        int sourceId = Identity::GetId(sourceTid);

        bool hasHit = false;
        str logMessage;
        BuildMsg(logMessage = StrParam())
        {
            Append(s:"Fire has hit ");
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                if (!PlayerIngame(i))
                    continue;

                fixed distance = BCSUtils::ActorDistance(Identity::GetTid(i), 0);
                if (distance > fixed(area))
                    continue;
                
                if (hasHit)
                    Append(s:", ");

                hasHit = true;
                Append(s:BCSUtils::PlayerName(i));
                SetOnFire(sourceId, i, initialDamageTics, subsequentDamageTics);
            }
			
            if (sourceId != -1) Append(s:". Source player: " + BCSUtils::PlayerName(sourceId) + ".");
            else Append(s:".");
        }

        if (hasHit)
            Logger::LogDebug(LOGSOURCE, logMessage);
	}

    internal void SetOnFire(int sourceId, int targetId, int initialBurningDamageTics, int subsequentBurningDamageTics)
	{
        // Zombie-only.
		if (!Player::GetPlayerIsZombie(targetId))
			return;
		
		// Determine tics. If the player is already burning then add the subsequent tics.
        // Other wise add the initial tics.
		int tics = Power::GetPlayerHasPower(targetId, Power::POWERFIREBURNING) ?
			subsequentBurningDamageTics :
			initialBurningDamageTics;

        // TODO: Set source as igniter. We don't have the source feature yet so this info is lost.
		
		Power::AddPlayerPowerTics(targetId, Power::POWERFIREBURNING, tics);
	}

    internal bool IsOnFire()
    {
        return PlayerIsOnFire(PlayerNumber());
    }

    internal bool PlayerIsOnFire(int id)
    {
        return Power::GetPlayerHasPower(id, Power::POWERFIREBURNING);
    }
}
