#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    script "zh2_dec_checkautousekevlar"
    {
        if (!ZH2Game::GetDisableAutoUseItems() && ZH2Game::GetAutoUseKevlars(PlayerNumber()))
            UseKevlar();
    }

    script "zh2_dec_wearkevlar"
    {
        if (!Player::GetPlayerIsHuman(PlayerNumber())) terminate;
        if (CheckInventory(KEVLAR_ITEM) == 0) terminate;
        UseKevlar();
    }

    internal void UseKevlar()
    {
        // Players may only have one point of kevlar.
        if (Player::GetKevlarPoints() != 0)
            return;

        // Note, I would set zombie protection power here, but it doesn't persist.
        TakeInventory(KEVLAR_ITEM, 1);
        Player::AddKevlarPoints(1);

        Logger::LogActivator("You are now able to withstand one more hit from zombies.");
    }

    script "zh2_dec_checkautouseenergy"
    {
        if (!ZH2Game::GetDisableAutoUseItems() && ZH2Game::GetAutoUseEnergyDrinks(PlayerNumber()))
            UseEnergy();
    }

    script "zh2_dec_useenergy"
    {
        if (!Player::GetPlayerIsHuman(PlayerNumber())) terminate;
        if (CheckInventory(ENERGY_ITEM) == 0) terminate;

        Player::PlayerPanicStateT state = Player::GetPanicState();
        if (state == Player::PANICSTATEPANICKING)
        {
            Logger::LogActivator("You can't use this whilst panicking!");
            terminate;
        }
        if (state == Player::PANICSTATECALMINGDOWN)
        {
            Logger::LogActivator("Calm down first.");
            terminate;
        }

        UseEnergy();
    }

    internal void UseEnergy()
    {
        TakeInventory(ENERGY_ITEM, 1);
        BCSUtils::SetInventory(SPRINT_ITEM, SPRINT_ITEM_MAX);
        Power::SetPowerTics(Power::POWERCAFFEINE, 35 * 30);

        LocalAmbientSound("items/ENERGY", 150);
        Logger::LogActivator("Caffeine is running through your veins...");
    }

    script "zh2_dec_checkautousemedikit"
    {
        if (!ZH2Game::GetDisableAutoUseItems() && ZH2Game::GetAutoUseMedikits(PlayerNumber()))
            UseMedikit();
    }

    script "zh2_dec_usemedikit"
    {
        if (!Player::GetPlayerIsHuman(PlayerNumber())) terminate;
        if (CheckInventory(MEDIKIT_ITEM) == 0) terminate;

        Player::PlayerPanicStateT state = Player::GetPanicState();
        if (state == Player::PANICSTATEPANICKING)
        {
            Logger::LogActivator("You can't use this whilst panicking!");
            terminate;
        }
        if (state == Player::PANICSTATECALMINGDOWN)
        {
            Logger::LogActivator("Calm down first.");
            terminate;
        }

        UseMedikit();
    }

    internal void UseMedikit()
    {
        if (BCSUtils::GetActorHealth(0) == 100)
            return;

        TakeInventory(MEDIKIT_ITEM, 1);
        HealThing(40);
    }

    script "zh2_dec_useflarebox"
    {
        if (!Player::GetPlayerIsHuman(PlayerNumber())) terminate;
        if (CheckInventory(FLARE_ITEM) == 2) terminate;
        if (CheckInventory(FLAREBOX_ITEM) != 1) terminate;

        TakeInventory(FLAREBOX_ITEM, 1);
        BCSUtils::SetInventory(FLARE_ITEM, 2);

        Logger::LogActivator("You open the box and grab what's inside.");
    }

    script "zh2_dec_usecure"
    {
        if (CheckInventory(CURE_ITEM) == 0) terminate;
        if (Player::GetInitialZombie())
        {
            Logger::LogActivator("You can't cure yourself as an initial zombie.");
            terminate;
        }

        TakeInventory(CURE_ITEM, 1);
        Game::CurePlayer(PlayerNumber(), Game::CURESOURCE_ITEM);
        Sync::SyncPlayers();

        Power::GivePower(Power::POWERHUMANIMMUNITY);
    }

    script "zh2_dec_set_fire_mine_time"
    {
        // Value is decremented every 5 tics, so 7 is a second.
        SetUserVariable(0, "user_firetotalcount", 7 * 60);
    }

    script "zh2_dec_set_circulator_time"
    {
        // The circulator fires 3 times each interval, and we allow this cycle 10 times.
        SetUserVariable(0, "user_firetotalcount", 10);
    }

    script "zh2_dec_use_suicide_bomb"
    {
        if (!Player::GetPlayerIsHuman(PlayerNumber())) terminate;
        if (CheckInventory(SUICIDE_BOMB_ITEM) == 0) terminate;

        // Check for confirmation.
        // If we want confirmation, don't use it yet.
        // Otherwise we can.
        if (CheckInventory(SUICIDE_BOMB_ITEM_CONFIRM_TIMESTAMP) < Timer())
        {
            Hud::ShowSuicideBombHud();

            GiveInventory(SUICIDE_BOMB_ITEM_CONFIRM_TIMESTAMP, Timer() + SUICIDE_BOMB_ITEM_CONFIRM_TIMESTAMP_MAX_TICS);
            SetResultValue((int)false);
            terminate;
        }

        SetResultValue((int)true);
    }
}
