#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Utils
{
    void ScaleToScreen()
    {
        fixed aspect = BCSUtils::GetAspectRatio();

        if (aspect >= 1.0)
        {
            fixed scale = 1.0 + (aspect - 1.0) / 2.0;
            BCSUtils::HudSetScaleXY(scale, 1.0);
        }
        else
        {
            aspect = 1.0 / aspect;
            fixed scale = 1.0 + (aspect - 1.0) / 2.0;
            BCSUtils::HudSetScaleXY(1.0, scale);
        }
    }
}