#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    // TODO: Make this a genuine event.
    script "zh2_internal_damage_receiveclient"(raw tid, raw damage, raw isKill) clientside
    {
        Damage::AddTotalDamage(tid, damage);
        DamageFeedback::SetTidDamaged(tid, damage, isKill);
    }

    // TODO: Make this a genuine event.
    script "zh2_internal_damagetotal_receiveclient"(raw tid, raw damage) clientside
    {
        DamageFeedback::AddTotalDamageNumberOnActor(tid, damage);
    }
}