#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Event"

#include "round.acs"
#include "timer.acs"
#include "player.acs"
#include "damage.acs"
#include "send.acs"
#include "receive.acs"

strict namespace Event
{
    internal void SetSurvivalDefaultsServer()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for events serverside.");

        EventBus::AddCallbackByScriptName(EVENTTIMERELAPSED, "zh2_internal_event_timerelapsed");
        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched");
        EventBus::AddCallbackByScriptName(EVENTPLAYERPRESCRATCHED, "zh2_internal_event_prescratched");
        EventBus::AddCallbackByScriptName(EVENTPLAYERKILLEDBYPLAYER, "zh2_internal_event_playerkilledbyplayer");
        EventBus::AddCallbackByScriptName(EVENTPLAYERLEFTROUND, "zh2_internal_event_playerleftround");
        EventBus::AddCallbackByScriptName(EVENTPLAYERSPECIECHANGED, "zh2_internal_event_specie_changed");
    }

    internal void SetSurvivalDefaultsClient()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for events clientside.");

        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched_client");
        EventBus::AddCallbackByScriptName(EVENTACTORDAMAGED, "zh2_internal_event_actordamaged");
        EventBus::AddCallbackByScriptName(EVENTACTORDAMAGEDCLIENTTOTAL, "zh2_internal_event_actordamaged_clienttotal");
    }

    internal void SetEscapeDefaultsServer()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for events serverside.");

        EventBus::AddCallbackByScriptName(EVENTTIMERELAPSED, "zh2_internal_event_timerelapsed");
        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched");
        EventBus::AddCallbackByScriptName(EVENTPLAYERPRESCRATCHED, "zh2_internal_event_prescratched");
        EventBus::AddCallbackByScriptName(EVENTPLAYERKILLEDBYPLAYER, "zh2_internal_event_playerkilledbyplayer");
        EventBus::AddCallbackByScriptName(EVENTPLAYERLEFTROUND, "zh2_internal_event_playerleftround");
        EventBus::AddCallbackByScriptName(EVENTPLAYERSPECIECHANGED, "zh2_internal_event_specie_changed");
    }

    internal void SetEscapeDefaultsClient()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for events clientside.");

        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched_client");
        EventBus::AddCallbackByScriptName(EVENTACTORDAMAGED, "zh2_internal_event_actordamaged");
        EventBus::AddCallbackByScriptName(EVENTACTORDAMAGEDCLIENTTOTAL, "zh2_internal_event_actordamaged_clienttotal");
    }
}

#undef LOGSOURCE