#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Events
{
    #define EVENT_RECEIVE_MAX_SIZE 40

    internal struct EventReceiveContextT
    {
        raw ReceiveData[EVENT_RECEIVE_MAX_SIZE];
    };

    internal enum KillTypeT : int
    {
        KILL_TYPE_NONE,
        KILL_TYPE_HUMAN_TO_HUMAN,
        KILL_TYPE_HUMAN_TO_ZOMBIE,
        KILL_TYPE_ZOMBIE_TO_ZOMBIE,
        KILL_TYPE_ZOMBIE_TO_HUMAN,
    };

    extern raw GetReceiveData(int index);

    extern void ReceivePlayerLeftRound(str packet);
    extern void ReceivePlayerDied(str packet);
    extern void ReceivePlayerScratched(str packet);
    extern void ReceivePlayerCured(str packet);
    extern void ReceivePlayerInfected(str packet);
    extern void ReceivePlayerSpecieChanged(str packet);
    extern void ReceiveResistStarted(str packet);
    extern void ReceiveResistElapsed(str packet);
    extern void ReceiveResistStopped(str packet);
    extern void ReceiveRoundSwitched(str packet);
    extern void ReceiveTimerStarted(str packet);
    extern void ReceiveTimerStopped(str packet);
    extern void ReceiveTimerPaused(str packet);
    extern void ReceiveTimerResumed(str packet);
    extern void ReceiveTimerElapsed(str packet);
    extern void ReceiveTimerSwitched(str packet);
}