#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Events"

#include "round.acs"
#include "timer.acs"
#include "player.acs"
#include "send.acs"
#include "receive.acs"

strict namespace Events
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for events.");

        EventBus::AddCallbackByScriptName(EVENTTIMERELAPSED, "zh2_internal_event_timerelapsed");
        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched");
        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched_client");
        EventBus::AddCallbackByScriptName(EVENTSCRATCHED, "zh2_internal_event_scratched");
        EventBus::AddCallbackByScriptName(EVENTPLAYERDIED, "zh2_internal_event_playerdied");
        EventBus::AddCallbackByScriptName(EVENTPLAYERLEFTROUND, "zh2_internal_event_playerleftround");
        EventBus::AddCallbackByScriptName(EVENTPLAYERSPECIECHANGED, "zh2_internal_event_specie_changed");
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for events.");

        EventBus::AddCallbackByScriptName(EVENTTIMERELAPSED, "zh2_internal_event_timerelapsed");
        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched");
        EventBus::AddCallbackByScriptName(EVENTROUNDSWITCHED, "zh2_internal_event_roundswitched_client");
        EventBus::AddCallbackByScriptName(EVENTSCRATCHED, "zh2_internal_event_scratched");
        EventBus::AddCallbackByScriptName(EVENTPLAYERDIED, "zh2_internal_event_playerdied");
        EventBus::AddCallbackByScriptName(EVENTPLAYERLEFTROUND, "zh2_internal_event_playerleftround");
        EventBus::AddCallbackByScriptName(EVENTPLAYERSPECIECHANGED, "zh2_internal_event_specie_changed");
    }

    internal void SetReceiveData(int index, raw data)
    {
        if (index >= EVENT_RECEIVE_MAX_SIZE)
        {
            Logger::LogError(LOGSOURCE, "SetReceiveData index " + str(index) + " is out of bounds (0 - " + str(EVENT_RECEIVE_MAX_SIZE - 1) + ")!");
            return;
        }

        ZH2Game::GameContext.EventReceiveContext.ReceiveData[index] = data;
    }

    internal raw GetReceiveData(int index)
    {
        if (index >= EVENT_RECEIVE_MAX_SIZE)
        {
            Logger::LogError(LOGSOURCE, "SetReceiveData index " + str(index) + " is out of bounds (0 - " + str(EVENT_RECEIVE_MAX_SIZE - 1) + ")!");
            return 0;
        }

        return ZH2Game::GameContext.EventReceiveContext.ReceiveData[index];
    }
}

#undef LOGSOURCE 