#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Events
{
    #define EVENT_RECEIVE_MAX_SIZE 40

    internal struct EventReceiveContextT
    {
        raw ReceiveData[EVENT_RECEIVE_MAX_SIZE];
    };

    internal enum KillTypeT : int
    {
        KILL_TYPE_NONE,
        KILL_TYPE_HUMAN_TO_HUMAN,
        KILL_TYPE_HUMAN_TO_ZOMBIE,
        KILL_TYPE_ZOMBIE_TO_ZOMBIE,
        KILL_TYPE_ZOMBIE_TO_HUMAN,
    };
}