#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Events
{
    internal void SendPlayerLeftRound(int id)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTPLAYERLEFTROUND, packet);
    }

    internal void SendPlayerDied(int killedId, int killerId)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, killedId, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, killerId, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTPLAYERDIED, packet);
    }

    internal void SendPlayerScratched(int attackedId, int attackerId)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, attackedId, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, attackerId, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTSCRATCHED, packet);
    }

    internal void SendPlayerCured(int id)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTCURED, packet);
    }

    internal void SendPlayerInfected(int id)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTINFECTED, packet);
    }

    internal void SendPlayerSpecieChanged(int id, Player::PlayerSpecieT specie)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, specie, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTPLAYERSPECIECHANGED, packet);
    }

    internal void SendResistStarted(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTRESISTSTARTED, packet);
    }

    internal void SendResistElapsed(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTRESISTELAPSED, packet);
    }

    internal void SendResistStopped(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTRESISTSTOPPED, packet);
    }

    internal void SendRoundSwitched(int prevIndex, int newIndex)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, prevIndex, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, newIndex, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTROUNDSWITCHED, packet);
    }

    internal void SendTimerStarted(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTTIMERSTARTED, packet);
    }

    internal void SendTimerStopped(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTTIMERSTOPPED, packet);
    }

    internal void SendTimerPaused(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTTIMERPAUSED, packet);
    }

    internal void SendTimerResumed(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTTIMERRESUMED, packet);
    }

    internal void SendTimerElapsed(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTTIMERELAPSED, packet);
    }

    internal void SendTimerSwitched(int prevIndex, int newIndex)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_Append(packet, prevIndex, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, newIndex, Packet::PACKET_WORD);
        EventBus::CallEvent(EVENTTIMERSWITCHED, packet);
    }
}