#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Events
{
    internal void SendPlayerLeftRound(int id)
    {
        EventBus::CallEvent(EVENTPLAYERLEFTROUND, id);
    }

    internal void SendPlayerDied(int killedId, int killerId)
    {
        EventBus::CallEvent(EVENTPLAYERDIED, killedId, killerId);
    }

    internal void SendPlayerScratched(int attackedId, int attackerId)
    {
        EventBus::CallEvent(EVENTSCRATCHED, attackedId, attackerId);
    }

    internal void SendPlayerCured(int id)
    {
        EventBus::CallEvent(EVENTCURED, id);
    }

    internal void SendPlayerInfected(int id)
    {
        EventBus::CallEvent(EVENTINFECTED, id);
    }

    internal void SendPlayerSpecieChanged(int id, Player::PlayerSpecieT specie)
    {
        EventBus::CallEvent(EVENTPLAYERSPECIECHANGED, id, specie);
    }

    internal void SendResistStarted(int index)
    {
        EventBus::CallEvent(EVENTRESISTSTARTED, index);
    }

    internal void SendResistElapsed(int index)
    {
        EventBus::CallEvent(EVENTRESISTELAPSED, index);
    }

    internal void SendResistStopped(int index)
    {
        EventBus::CallEvent(EVENTRESISTSTOPPED, index);
    }

    internal void SendRoundSwitched(int prevIndex, int newIndex)
    {
        EventBus::CallEvent(EVENTROUNDSWITCHED, prevIndex, newIndex);
    }

    internal void SendTimerStarted(int index)
    {
        EventBus::CallEvent(EVENTTIMERSTARTED, index);
    }

    internal void SendTimerStopped(int index)
    {
        EventBus::CallEvent(EVENTTIMERSTOPPED, index);
    }

    internal void SendTimerPaused(int index)
    {
        EventBus::CallEvent(EVENTTIMERPAUSED, index);
    }

    internal void SendTimerResumed(int index)
    {
        EventBus::CallEvent(EVENTTIMERRESUMED, index);
    }

    internal void SendTimerElapsed(int index)
    {
        EventBus::CallEvent(EVENTTIMERELAPSED, index);
    }

    internal void SendTimerSwitched(int prevIndex, int newIndex)
    {
        EventBus::CallEvent(EVENTTIMERSWITCHED, prevIndex, newIndex);
    }
}