#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Music"

strict namespace Music
{
    void SetMusic(str track, int order = 0)
    {
        // Do not change if the round ended.
        if (Round::GetCurrentRoundIsEnding())
            return;

        upmost::SetMusic(track, order);
    }

    void SetDefaultMusic(str track, int order = 0)
    {
        if (BCSUtils::IsServer())
        {
            SetCVarString(CVAR_SERVER_SYNC_DEFAULTMAPMUSIC_NAME, track);
            SetCVar(CVAR_SERVER_SYNC_DEFAULTMAPMUSIC_ORDER, order);
        }
        else
        {
            SetUserCVarString(ConsolePlayerNumber(), CVAR_CLIENT_SYNC_DEFAULTMAPMUSIC_NAME, track);
            SetUserCVar(ConsolePlayerNumber(), CVAR_CLIENT_SYNC_DEFAULTMAPMUSIC_ORDER, order);
        }
    }

    void PlayDefaultMusic()
    {
        SetMusic(GetDefaultMusicTrack(), GetDefaultMusicOrder());
    }

    internal str GetDefaultMusicTrack()
    {
        str track;
        if (BCSUtils::IsServer())
        {
            track = GetCVarString(CVAR_SERVER_SYNC_DEFAULTMAPMUSIC_NAME);
        }
        else
        {
            track = GetCVarString(CVAR_CLIENT_SYNC_DEFAULTMAPMUSIC_NAME);
        }

        if (track == "")
            return "*";

        return track;
    }

    internal int GetDefaultMusicOrder()
    {
        int order;
        if (BCSUtils::IsServer())
        {
            order = GetCvar(CVAR_SERVER_SYNC_DEFAULTMAPMUSIC_ORDER);
        }
        else
        {
            order = GetCvar(CVAR_CLIENT_SYNC_DEFAULTMAPMUSIC_ORDER);
        }

        return order;
    }
}

#undef LOGSOURCE