#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Music"

strict namespace Music
{
    void SetMusic(str track, int order = 0)
    {
        // Do not change if the round ended.
        if (Round::GetCurrentRoundIsEnding())
            return;

        upmost::SetMusic(track, order);
    }

    void SetDefaultMusic(str track, int order = 0)
    {
        SetCVarString(CVAR_SYNC_RADIO_NAME, track);
        SetCVar(CVAR_SYNC_RADIO_ORDER, order);
    }

    void PlayDefaultMusic()
    {
        SetMusic(GetDefaultMusicTrack(), GetDefaultMusicOrder());
    }

    internal str GetDefaultMusicTrack()
    {
        str track = GetCVarString(CVAR_SYNC_RADIO_NAME);
        if (track == "")
            return "*";
        
        return track;
    }

    internal int GetDefaultMusicOrder()
    {
        int order = GetCvar(CVAR_SYNC_RADIO_ORDER);
        return order;
    }
}

#undef LOGSOURCE 