#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Music
{
    #define CVAR_SERVER_SYNC_DEFAULTMAPMUSIC_NAME "__server_sync_defaultmapmusic_name"
    #define CVAR_SERVER_SYNC_DEFAULTMAPMUSIC_ORDER "__server_sync_defaultmapmusic_order"

    #define CVAR_CLIENT_SYNC_DEFAULTMAPMUSIC_NAME "__client_sync_defaultmapmusic_name"
    #define CVAR_CLIENT_SYNC_DEFAULTMAPMUSIC_ORDER "__client_sync_defaultmapmusic_order"

    extern void PlayMusic(str track, int order = 0);
    extern void SetDefaultMusic(str track, int order = 0);
    extern void PlayDefaultMusic();
}