#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Obituary"

#include "scripts.acs"

strict namespace Obituary
{
    internal void SetSurvivalDefaultsClient()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for obituaries clientside.");

        EventBus::AddCallbackByScriptName(EVENTINITIALSCHOSEN, "zh2_internal_obituary_initialschosen_client");
        EventBus::AddCallbackByScriptName(EVENTPLAYERSAFE, "zh2_internal_obituary_playersafe_client");
    }

    internal void SetEscapeDefaultsClient()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for obituaries clientside.");

        EventBus::AddCallbackByScriptName(EVENTINITIALSCHOSEN, "zh2_internal_obituary_initialschosen_client");
        EventBus::AddCallbackByScriptName(EVENTPLAYERSAFE, "zh2_internal_obituary_playersafe_client");
    }
}

#undef LOGSOURCE
