#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Obituary
{
    internal void QueueInitialsChosen()
    {
        // NOTE: We split up the initials to their own obituary.

        int count = Event::GetReceiveData(0);
        bool multiple = count != 1;
        int index = 0;

        while (count--)
        {
            int queueIndex = GetNextQueueIndex();
            SetQueueType(queueIndex, OBITUARY_INITIAL);
            SetQueueData(queueIndex, 0, index);
            SetQueueData(queueIndex, 1, Event::GetReceiveData(index + 1));

            // We also pass if this is the only zombie.
            // This way we tell clients if an index should be shown.
            SetQueueData(queueIndex, 2, multiple);
            index++;
        }
    }

    internal void QueuePlayerSafe()
    {
        int queueIndex = GetNextQueueIndex();
        SetQueueType(queueIndex, OBITUARY_SAFE);
        SetQueueData(queueIndex, 0, Event::GetReceiveData(0));
    }
}
