#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Obituary
{
    internal void QueueInitialsChosen()
    {
        // NOTE: We split up the initials to their own obituary.

        int count = Event::GetReceiveData(0);
        bool multiple = count != 1;
        int index = 0;

        while (count--)
        {
            int queueIndex = GetNextQueueIndex();
            SetQueueType(queueIndex, OBITUARY_INITIAL);
            SetQueueData(queueIndex, 0, index);
            SetQueueData(queueIndex, 1, Event::GetReceiveData(index + 1));

            // We also pass if this is the only zombie.
            // This way we tell clients if an index should be shown.
            SetQueueData(queueIndex, 2, multiple);
            index++;
        }
    }

    internal void QueuePlayerSafe()
    {
        int id = Event::GetReceiveData(0);
        int queueIndex = GetNextQueueIndex();
        SetQueueType(queueIndex, OBITUARY_SAFE);
        SetQueueData(queueIndex, 0, id);
        SetQueueData(queueIndex, 1, GetPlayerObituarySpecieType(id));
    }

    internal void QueuePlayerScratched()
    {
        // No need to get specie of the infected because they are always human.
        int infectedId = Event::GetReceiveData(0);
        int infectorId = Event::GetReceiveData(1);
        int queueIndex = GetNextQueueIndex();
        SetQueueType(queueIndex, OBITUARY_PLAYER_SCRATCHED);
        SetQueueData(queueIndex, 0, infectedId);
        SetQueueData(queueIndex, 1, infectorId);
        SetQueueData(queueIndex, 2, GetPlayerObituarySpecieType(infectorId));
    }

    internal void QueuePlayerInfected()
    {
        int id = Event::GetReceiveData(0);
        int queueIndex = GetNextQueueIndex();
        SetQueueType(queueIndex, OBITUARY_PLAYER_INFECTED);
        SetQueueData(queueIndex, 0, id);
    }

    internal void QueuePlayerDied()
    {
        int killedId = Event::GetReceiveData(0);
        int killerId = Event::GetReceiveData(1);

        // For deaths we only care if it was a suicide.
        // Player fragging is handled separately.
        if (killerId != -1 && killerId != killedId)
            return;

        bool suicide = killedId == killerId;
        int queueIndex = GetNextQueueIndex();
        SetQueueType(queueIndex, OBITUARY_PLAYER_DIED);
        SetQueueData(queueIndex, 0, killedId);
        SetQueueData(queueIndex, 1, GetPlayerObituarySpecieType(killedId));
        SetQueueData(queueIndex, 2, suicide);
    }

    internal void QueuePlayerFragged()
    {
        int killedId = Event::GetReceiveData(0);
        int killerId = Event::GetReceiveData(1);

        int queueIndex = GetNextQueueIndex();
        SetQueueType(queueIndex, OBITUARY_PLAYER_FRAGGED);
        SetQueueData(queueIndex, 0, killedId);
        SetQueueData(queueIndex, 1, killerId);
        SetQueueData(queueIndex, 2, GetPlayerObituarySpecieType(killedId));
        SetQueueData(queueIndex, 3, GetPlayerObituarySpecieType(killerId));
    }
}
