#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Obituary
{
    script "zh2_internal_obituary_initialschosen_client" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceiveInitialsChosen(packet);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueueInitialsChosen();
        else
            LogInitialsChosen();
    }

    script "zh2_internal_obituary_playersafe_client" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerSafe(packet);

        bool safe = Event::GetReceiveData(1);
        bool firstTime = Event::GetReceiveData(2);

        // We only handle if players entered the safezone, not left.
        // We also only handle first time safety.
        if (!safe || !firstTime)
            terminate;

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerSafe();
        else
            LogPlayerSafe();
    }

    script "zh2_internal_obituary_playerscratched" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerScratched(packet);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerScratched();
        else
            LogPlayerScratched();
    }

    script "zh2_internal_obituary_playerinfected" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerInfected(packet);

        int type = Event::GetReceiveData(1);
        int source = Event::GetReceiveData(2);

        // Initial infection is not handled, there is a separate event (initialschosen).
        if (type == Game::INFECT_INITIAL)
            terminate;

        // Source being another player is not handled, there is a separate event (playerscratched).
        if (source == Game::INFECTSOURCE_PLAYER)
            terminate;

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerInfected();
        else
            LogPlayerInfected();
    }

    script "zh2_internal_obituary_playercured" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerCured(packet);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerCured();
        else
            LogPlayerCured();
    }

    script "zh2_internal_obituary_playerdied" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerDied(packet);

        int killedId = Event::GetReceiveData(0);
        int killerId = Event::GetReceiveData(1);

        // For deaths we only care if it was a suicide.
        // Player fragging is handled separately.
        if (killerId != -1 && killerId != killedId)
            terminate;

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerDied();
        else
            LogPlayerDied();
    }

    script "zh2_internal_obituary_playerkilledByPlayer" (raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerKilledByPlayer(packet);

        int killedId = Event::GetReceiveData(0);
        int killerId = Event::GetReceiveData(1);

        // Attempt to receive the player's weapon.
        // If we can't determine it, or `GetWeapon()` returns "None", then default to 0.
        // After that, determine the item's definition in the custom lumps for its index.
        str weapon = (str)0;
        if (SetActivatorToPlayer(killerId))
        {
            weapon = GetWeapon();
            if (BCSUtils::StrIEquals(weapon, "none"))
                weapon = (str)0;
        }

        int weaponIndex = Item::GetItemIndexByName(weapon);

        if (ZH2Game::GetSvEnableObituaries() && ZH2Game::GetClEnableObituaries(ConsolePlayerNumber()))
            QueuePlayerKilledByPlayer(killedId, killerId, weaponIndex);
        else
            LogPlayerKilledByPlayer(killedId, killerId, weaponIndex);
    }
}
