#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "AFK prevention"

#include "player.acs"

strict namespace AfkPrevention
{
    // Manages the kick buffer which the AFK on the player side fills and formats a nice log message.
    internal void AfkPreventionRoundStartTicServer()
    {
        // To collect players we do this every 5 tics.
        if (Timer() % 5 != 0)
            return;

        int kickedCount = 0;

        for (int id = 0; id < BCSUtils::MAX_PLAYERS; id++)
        {
            if (GetPlayerWasRoundStartAfkKicked(id))
                kickedCount++;
        }

        if (kickedCount == 0)
            return;

        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            int current = 0;
            Append(s:"\cd");

            for (int id = 0; id < BCSUtils::MAX_PLAYERS; id++)
            {
                if (!GetPlayerWasRoundStartAfkKicked(id))
                    continue;

                current++;

                if (current > 1)
                {
                    if (current == kickedCount)
                        Append(s:" and ");
                    else
                        Append(s:", ");
                }

                Append(s:BCSUtils::PlayerName(id));

                SetPlayerWasRoundStartAfkKicked(id, false);
            }

            Append(s:" ");
            Append(s:(kickedCount == 1 ? "was" : "were"));
            Append(s:" moved to spectators for inactivity.");
        }

        Logger::LogBold(logMessage);
    }

    // Handles checks if the activator should be kicked for inactivity on round start.
    internal void PlayerAfkPreventionRoundStartTicServer()
    {
        if (!PlayerInGame(PlayerNumber()) || PlayerIsBot(PlayerNumber()))
            return;

        Round::KnownRoundStateT roundState = Round::GetActiveKnownRoundState();
        if (roundState != Round::STATECOUNTDOWN && roundState != Round::STATEPLAYING)
            return;

        if (!GetHasMovedThisMap())
        {
            if (Utils::GetIsMoving())
            {
                SetHasMovedThisMap(true);
                Sync::SyncAfkPrevention();
                return;
            }

            // On 0 we don't want AFK prevention at map start. Otherwise it would be instant.
            int seconds = ZH2Game::GetAfkMoveAtRoundStartBeforeSeconds();
            if (seconds == 0)
                return;

            int playTics = Player::GetPlayTics();
            if (seconds * 35 > playTics)
                return;

            // Kick and send to buffer so the Game side can log a message.
            KickFromGame(PlayerNumber(), "inactivity");
            SetWasRoundStartAfkKicked(true);
        }
    }
}

#undef LOGSOURCE