#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawClientSeparateHudAcidBlur()
    {
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(200.0, 150.0);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlpha(0.5);
        BCSUtils::HudSetStayTime(0.2);
        BCSUtils::HudSetAppearTime(0.5);
        BCSUtils::HudSetDisappearTime(0.5);

        Utils::ScaleToScreen();
        
        fixed x = 100.0,
              y = BCSUtils::HudBottom() / 2.0;

		BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawImage(0, BLUR_GREEN_GRAPHIC);
	}
}