#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace BitMath
{
    extern int GetBitPack1();
    extern int GetBitPack2();
    extern int GetBitPack3();
    extern int GetBitPack4();
    extern int SetBit(int val, int index, bool value);
    extern int GetBit64(int val1, int val2, int index);
    extern int GetBit128(int val1, int val2, int val3, int val4, int index);
    extern void SetBit64(int val1, int val2, int index, bool value);
    extern void SetBit128(int val1, int val2, int val3, int val4, int index, bool value);
}