#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "sniper.acs"
#include "radio.acs"

strict namespace Hud
{
    internal void DrawWeaponsHud()
    {
        fixed scale = ZH2Game::GetHudWeaponSniperScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(960.0, 720.0);
        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        fixed x = 480.0;
        fixed y = 360.0;
        
        DrawSniperHud(x, y, scale);

        scale = ZH2Game::GetHudWeaponRadioScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(960.0, 720.0);
        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_TOP);
        BCSUtils::HudSetCenterText(false);

        x = BCSUtils::HudLeft() + 80.0;
        y = 200.0;

        DrawRadioHud(x, y);
    }
}