#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Sync
{
    #define ACTOR_SYNC_AMBIENTWEATHER_SOUND_TEMPLATE "__syncambientweathersound%n"
    #define ACTOR_SYNC_AMBIENTWEATHER_SHELTEREDSOUND_TEMPLATE "__syncambientweathershelteredsound%n"

    #define LIB_SYNC_BASE 1600

    #define SYNC_WEATHER_LENGTH EMITTERWEATHER_COUNT * 8 + RANDOMIZEDWEATHER_COUNT * 3 + AMBIENTWEATHER_COUNT * 4
    #define SYNC_WEATHER LIB_SYNC_BASE + SYNC_WEATHER_LENGTH

    // When adding a new sync, also increase this number.
    #define MAX_LIB_SYNC_TYPES 1

    internal enum LibSyncTypeT : int
    {
        SYNCTYPE_WEATHER,
    };

    struct LibSyncContextT
    {
        int FlushTic[MAX_LIB_SYNC_TYPES];
    };

    extern void LibFlushPendingSyncs();

    extern void LibSyncAll();
    extern void CallClientLibSyncAll();
    extern void LibSyncAllClientside();

    extern void SyncWeather();
    extern void CallSyncWeatherOnClients();
    extern void SyncWeatherClientside();
}