#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Sync"

#include "actor/weather.acs"

strict namespace Sync
{
    void LibFlushPendingSyncs()
    {
        int min = 0;
        int max = MAX_LIB_SYNC_TYPES - 1;
        for (int i = min; i <= max; ++i)
        {
            int tic = ZH2Lib::LibContext.SyncContext.FlushTic[i];
            if (tic == 0 || tic > Timer())
                continue;

            ZH2Lib::LibContext.SyncContext.FlushTic[i] = 0;
            TriggerSyncCore(i);
        }
    }

    internal void TriggerSyncCore(int syncId)
    {
        switch(syncId)
        {
            case SYNCTYPE_WEATHER: SyncWeatherCore(); return;

            default:
                Logger::LogError(LOGSOURCE, __FUNCTION__ + ": Failed to flush sync index " + str(syncId) + " as it's not known.");
                return;
        }
    }

    internal void DoSync(int syncId)
    {
        // Buffering not enabled.
        if (!ZH2Lib::GetUseSyncBuffer())
        {
            TriggerSyncCore(syncId);
            return;
        }

        int min = 0;
        int max = MAX_LIB_SYNC_TYPES - 1;
        if (syncId < min || syncId > max)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": Invalid sync id " + str(syncId) + ". Id must be between " + str(min) + " and " + str(max) + " (inclusive).");
            return;
        }

        // Already marked to sync.
        if (ZH2Lib::LibContext.SyncContext.FlushTic[syncId] != 0)
            return;

        ZH2Lib::LibContext.SyncContext.FlushTic[syncId] = Timer() + 1;
    }

    // Basic log formatter to include an additional sync category.
    internal str FormatLog(str category, str message)
    {
        return "[" + category + "] " + message;
    }

    /* COMBINED */

    void LibSyncAll()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        Sync::SyncWeather();
    }

    void CallClientLibSyncAll()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        Sync::CallSyncWeatherOnClients();
    }

    void LibSyncAllClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        Sync::SyncWeatherClientside();
    }

    /* WEATHER */

    void SyncWeather()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (!IsNetworkGame())
        {
            FinalizeWeatherSyncedClientside();
            return;
        }

        DoSync(SYNCTYPE_WEATHER);
    }

    internal void SyncWeatherCore()
    {
        SyncWeatherActor();
        CallSyncWeatherOnClients();
    }

    void CallSyncWeatherOnClients()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        if (IsNetworkGame())
            ACS_NamedExecute("zh2_internal_sync_weather_clientside", 0);
    }

    script "zh2_internal_sync_weather_clientside" clientside
    {
        SyncWeatherClientside();
    }

    void SyncWeatherClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (IsNetworkGame())
            SyncWeatherActorClientSide();

        FinalizeWeatherSyncedClientside();
    }

    internal void FinalizeWeatherSyncedClientside()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();
        Event::SendDataSynced(SYNCTYPE_WEATHER);
    }
}

#undef LOGSOURCE