#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Sync
{
    #define ACTOR_SYNC_AMBIENTWEATHER_SOUND_TEMPLATE "__syncambientweathersound%n"
    #define ACTOR_SYNC_AMBIENTWEATHER_SHELTEREDSOUND_TEMPLATE "__syncambientweathershelteredsound%n"

    #define LIB_SYNC_BASE 1600

    #define SYNC_WEATHER_LENGTH EMITTERWEATHER_COUNT * 8 + RANDOMIZEDWEATHER_COUNT * 3 + AMBIENTWEATHER_COUNT * 4
    #define SYNC_WEATHER LIB_SYNC_BASE + SYNC_WEATHER_LENGTH

    extern void LibSyncAll(bool callSyncOnClients = true);
    extern void CallClientLibSyncAll();
    extern void LibSyncAllClientside();

    extern void SyncWeather(bool callSyncOnClients = true);
    extern void CallSyncWeatherOnClients();
    extern void SyncWeatherClientside();
}