#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace LibIO
{
    struct ParsedEmitterWeatherContextT
    {
        int Index;
        bool Enabled;
        Weather::EmitterWeatherSkyBehaviorT SkyBehavior;
        int SpawnCount;
        int SpawnDelay;

        int MinRadius;
        int MaxRadius;
        int MinZpos;
        int MaxZpos;
    };

    struct ParsedRandomizedWeatherContextT
    {
        int Index;
        bool Enabled;

        int MinDelay;
        int MaxDelay;
    };

    struct ParsedAmbientWeatherContextT
    {
        int Index;
        bool Enabled;

        str Sound;
        str ShelteredSound;

        int Radius;
        int ShelteredRadius;

        int Delay;
    };

    extern void ParseFootstepDefsClientside();
    extern void ParseLoggerDefClientside();
    extern void ParseLoggerDefServerside();
    extern void ParseWeatherDefClientside();
    extern void ParseWeatherDefServerside();

    extern bool ParseWeatherProfile(int handle, str identifyingSymbol, str expectedSymbol, bool setPersisting);
}