#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace LibIO
{
    struct ParsedEmitterWeatherContextT
    {
        int Index;
        bool Enabled;
        Weather::EmitterWeatherSkyBehaviorT SkyBehavior;
        int SpawnCount;
        int SpawnDelay;

        int MinRadius;
        int MaxRadius;
        int MinZpos;
        int MaxZpos;
    };

    extern ParsedEmitterWeatherContextT? ParsedEmitterWeatherContext;

    extern void ParseFootstepDefsClientside();
    extern void ParseLoggerDefClientside();
    extern void ParseLoggerDefServerside();
    extern void ParseWeatherDefClientside();
    extern void ParseWeatherDefServerside();
}