#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal SharedStateT _sharedState;

    internal void UpdateSharedState()
    {
        PlayerSkinTypeT playerSkinType = SKINTYPE_NONE;
        ZombieTeleportSkinT zombieTeleportSkin = ZTELESKIN_NONE;

        int skinIndexAcs = GetPlayerSkin(ConsolePlayerNumber(), PLAYERSKIN_VISIBLE);
        str skinName = skinIndexAcs != -1 ? (str)GetSkinProperty(skinIndexAcs, "Name") : (raw)0;

        switch (skinName)
        {
            case SKIN_HUMAN_GRENADE: playerSkinType = SKINTYPE_HUMAN_GRENADE; break;
            case SKIN_HUMAN_HANDGUN: playerSkinType = SKINTYPE_HUMAN_HANDGUN; break;
            case SKIN_HUMAN_JACKSGUN: playerSkinType = SKINTYPE_HUMAN_JACKSGUN; break;
            case SKIN_HUMAN_SHOTGUN: playerSkinType = SKINTYPE_HUMAN_SHOTGUN; break;
            case SKIN_HUMAN_DOUBLEBARRELEDSHOTGUN: playerSkinType = SKINTYPE_HUMAN_DOUBLEBARRELEDSHOTGUN; break;
            case SKIN_HUMAN_CHAINGUN: playerSkinType = SKINTYPE_HUMAN_CHAINGUN; break;
            case SKIN_HUMAN_SNIPER: playerSkinType = SKINTYPE_HUMAN_SNIPER; break;
            case SKIN_HUMAN_RIOTGUN: playerSkinType = SKINTYPE_HUMAN_RIOTGUN; break;

            case SKIN_ZOMBIEOLD:
                playerSkinType = SKINTYPE_ZOMBIEOLD;
                zombieTeleportSkin = ZTELESKIN_OLD;
                break;

            case SKIN_ZOMBIEREGULAR:
                playerSkinType = SKINTYPE_ZOMBIEREGULAR;
                zombieTeleportSkin = ZTELESKIN_REGULAR;
                break;

            case SKIN_ZOMBIEINITIAL:
                playerSkinType = SKINTYPE_ZOMBIEINITIAL;
                zombieTeleportSkin = ZTELESKIN_INITIAL;
                break;

            // No skin found, or an unrecognized one. Fallback to the default skin used for the player's specie.
            // The zombie teleport skin falls back to the modern skin.
            default:
                if (Player::GetIsHuman()) playerSkinType = SKINTYPE_HUMAN_GRENADE;
                else if (Player::GetIsZombie())
                {
                    playerSkinType = SKINTYPE_ZOMBIEOLD;
                    zombieTeleportSkin = ZTELESKIN_REGULAR;
                }
                break;
        }

        _sharedState.PlayerSkin = playerSkinType;
        _sharedState.ZombieTeleportSkin = zombieTeleportSkin;

        _sharedState.DrawKevlarArmor = Player::GetKevlarPoints() != 0;
        _sharedState.DrawCurrentOwnedItem = Item::GetClientOwnedInventorySize() != 0;
        _sharedState.DrawKeyList = Item::GetClientOwnedKeySize() != 0;

        // TODO: Should come from a lump.
        _sharedState.DrawPrimaryWeaponBackground = !CheckWeapon(WEAPON_RADIO_NAME) && !CheckWeapon(WEAPON_CLAWS_NAME);
        _sharedState.DrawSecondaryWeaponBackground = CheckWeapon(WEAPON_RIOTGUN_NAME);

        _sharedState.DrawZombieTeleportsLeft = ZH2Game::GetAllowZombieTeleporting()
            && Player::GetIsZombie()
            && Game::GetZombieTeleportingEnabled();

        _sharedState.DrawZombieAbilities = ZH2Game::GetUseZombieAbilities() && Game::GetZombieAbilityFlags() != 0;
        for (int i = 0; i < ABILITY_COUNT; ++i)
        {
            Game::ZombieAbilityTypeFlagsT flag = Game::GetZombieAbilityItemTypeByIndex(i + 1);

            // Should not happen.
            // If it does, we gracefully ignore for now and assume the ability can be used.
            _sharedState.DrawZombieAbilityByIndex[i] = flag == Game::ABILITY_NONE
                || (Game::HasZombieAbility(flag) && (ZH2Game::GetDisabledZombieAbilityFlags() & flag) == 0);
        }

        for (int i = 0; i < MAX_POWER_TYPES; ++i)
        {
            fixed factor = Power::GetPlayerCalculatedPowerFactor(ConsolePlayerNumber(), i);

            // Do not draw if 0.0
            // This will be the case for a brief moment in online games, until we synchronized.
            // Do not draw if the factor is the default.
            fixed defaultFactor = Power::GetPlayerPowerFactorDefaultValue(ConsolePlayerNumber(), i);
            _sharedState.DrawCalculatedFactorByIndex[i] = factor != 0.0 && factor != defaultFactor;
        }

        // Safety is special as it has multiple slots. If we have at least one non-hidden safety slot set to `true`, it passes.
        bool safe = false;
        for (int i = 0; i < MAX_SAFETY_SLOTS; ++i)
        {
            if (Game::GetIsSafe(i) && !Game::GetSafeHidden(i))
            {
                safe = true;
                break;
            }
        }

        _sharedState.DrawHudStateByIndex[0] = safe;
        _sharedState.DrawHudStateByIndex[1] = Power::GetHasPower(Power::POWERCAFFEINE);
        _sharedState.DrawHudStateByIndex[2] = Power::GetHasPower(Power::POWERREWARDHUMANWEAPONUPGRADE);
        _sharedState.DrawHudStateByIndex[3] = Power::GetHasPower(Power::POWERREWARDZOMBIEJUMP);
        _sharedState.DrawHudStateByIndex[4] = Power::GetHasPower(Power::POWERREWARDZOMBIESPEED);
        _sharedState.DrawHudStateByIndex[5] = Power::GetHasPower(Power::POWERPANICKING);
        _sharedState.DrawHudStateByIndex[6] = Power::GetHasPower(Power::POWERHUMANIMMUNITY);
        _sharedState.DrawHudStateByIndex[7] = Power::GetHasPower(Power::POWERZOMBIEPROTECT);
        _sharedState.DrawHudStateByIndex[8] = SpaceUtil::GetThruActorsState() != SpaceUtil::STATE_DEFAULT;
        _sharedState.DrawHudStateByIndex[9] = Power::GetHasPower(Power::POWERANTISR50);

        // Draw the sprint/air bars only for humans, and only while not at their maximum.
        _sharedState.DrawSprintBar = Player::GetIsHuman() && Player::GetSprintLeft() != SPRINT_ITEM_MAX;
        _sharedState.DrawAirSupplyBar = Player::GetIsHuman() && GetAirSupply(ConsolePlayerNumber()) != MAX_AIRSUPPLY;

        // The AFK bar requires the player to either have not moved, or have a warning he is going to get kicked.
        // Priority is on having moved at round start.
        Round::KnownRoundStateT afkRoundState = Round::GetActiveKnownRoundState();
        if (afkRoundState != Round::STATECOUNTDOWN && afkRoundState != Round::STATEPLAYING)
        {
            _sharedState.DrawAfkBar = false;
        }
        else if (!AfkPrevention::GetHasMovedThisRound())
        {
            _sharedState.AfkBarMaxTics = ZH2Game::GetAfkMoveAtRoundStartBeforeSeconds() * 35;
            _sharedState.AfkBarTicsLeft = AfkPrevention::GetTicsUntilRoundStartKick();
            _sharedState.DrawAfkBar = _sharedState.AfkBarMaxTics != 0;
        }
        else if (AfkPrevention::GetHasAfkWarn())
        {
            _sharedState.AfkBarMaxTics = ZH2Game::GetAfkZombieMoveWarnSeconds() * 35;
            _sharedState.AfkBarTicsLeft = AfkPrevention::GetZombieWarnTicsLeft();
            _sharedState.DrawAfkBar = _sharedState.AfkBarMaxTics != 0;
        }
        else
        {
            _sharedState.DrawAfkBar = false;
        }

        int timerIndex = RoundTimer::GetActiveTimerIndex();
        _sharedState.DrawTimer = RoundTimer::GetTimerDefined(timerIndex)
            && RoundTimer::GetTimerActive(timerIndex)
            && RoundTimer::GetTimerVisible(timerIndex);
    }

    internal SharedStateT module& GetSharedState()
    {
        return _sharedState;
    }
}
