#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Environment
{
    #define VersionMajor 4
    #define VersionMinor 0
    #define VersionPatch 0
    #define VersionSuffix "-beta"

    // If `DevelopmentPlayerCap()` is `true`, this cap is enforced and players joining beyond the cap are kicked out.
    #define DEV_PLAYERCAP_COUNT 8

    extern bool IsDevelopment();
    extern bool IsProduction();
}