#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Environment
{
    internal str GetVersion()
    {
        return buildmsg(StrParam())
        {
            Append(d:VERSION_MAJOR);
            Append(s:".");
            Append(d:VERSION_MINOR);
            Append(s:".");
            Append(d:VERSION_PATCH);

            if (VERSION_SUFFIX != "")
            {
                Append(s:"-");
                Append(s:VERSION_SUFFIX);
            }
        }
    }

    bool IsDevelopment()
    {
        return
    #ifdef DEV
            true
    #else
            false
    #endif
        ;
    }

    bool IsProduction()
    {
        return !IsDevelopment();
    }

    internal bool DevelopmentPlayerCap()
    {
        return
    #ifdef DEV_PLAYERCAP
            true
    #else
            false
    #endif
        ;
    }
}