#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Map
{
    // Updates the list of votable maps that a player can choose from.
    internal void UpdateVotableMaps()
    {
        Shuffle::ShuffleVotableMaps(Shuffle::FLAGIGNORECURRENTMAP | Shuffle::FLAGIGNORENEXTMAP);

        // Get how many maps to show, making sure to show less if we don't have more.
        int length = BCSUtils::Min(Shuffle::GetRelevantSize(), ZH2Game::GetMaxVotableMapsShown());
        ZH2Game::GameContext.VotableMapCount = length;

        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            Append(s:"Updated votable maps. Count: ");
            Append(d:length);
            Append(s:". Maps: ");

            for (int i = 0; i < length; ++i)
            {
                int mapIndex = Shuffle::GetIndexValue(i);
                ZH2Game::GameContext.VotableMaps[i] = mapIndex;

                Append(s:GetMapRotationInfo(mapIndex, MAPROTATION_LUMPNAME));

                if (i != length - 1)
                    Append(s:", ");
            }
        }
        Logger::LogDebug(LOGSOURCE, logMessage);
    }

    // NOTE: As per the behaviour of map rotation functions, this returns 0 when no map was found.
    internal int GetRandomMap(int flags)
    {
        Shuffle::ShuffleVotableMaps(flags);

        // No map found
        if (Shuffle::GetRelevantSize() == 0)
            return 0;

        return Shuffle::GetIndexValue(0);
    }

    internal void VotePickMapClientside(int index)
    {
        if (!NamedRequestScriptPuke("zh2_internal_voting_pick_map", index))
            Logger::LogError(LOGSOURCE, "Failed to pick map.");
    }

    script "zh2_internal_voting_pick_map" (int index) net
    {
        if (Round::GetActiveKnownRoundState() != Round::STATEVOTING) terminate;
        if (index < 0 || index >= (ZH2Game::GameContext.VotableMapCount + MAPVOTE_HARDCODED_PICKS_LENGTH)) terminate;
        if (GetPickCooldownTics() > 0) terminate;
        if (GetVotedMapIndex() == index) terminate;

        // Spectators may not vote.
        if (!ZH2Game::GetAllowSpectatorVoting() && !PlayerInGame(PlayerNumber()))
        {
            Logger::LogActivator("This server has disabled spectator voting.");
            terminate;
        }

        // A map was already picked when this timer is running.
        if (RoundTimer::GetActiveTimerKnownType() == RoundTimer::TIMERVOTED)
        {
            Logger::LogActivator("You may not pick a map anymore as the voting has ended.");
            terminate;
        }

        // Special case for "next map" where it may only be picked if we have any maps in rotation.
        if (index == MAPVOTE_NEXT && GetMapRotationSize() == 0)
        {
            Logger::LogActivator("You may not pick this option as there are no known maps to rotate to.");
            terminate;
        }

        // Special case for "random map" where it may only be picked if we had votable maps.
        // If not, then next map does the same.
        if (index == MAPVOTE_RANDOM && ZH2Game::GameContext.VotableMapCount == 0)
        {
            Logger::LogActivator("You may not pick this option as no votable maps are left.");
            terminate;
        }

        str message;
        switch(index)
        {
            case MAPVOTE_REPLAY:
            {
                message = " has chosen to \cdreplay the current map\cj.";
                break;
            }
            case MAPVOTE_NEXT:
            {
                message = " has chosen to \cdplay the next rotation map\cj.";
                break;
            }
            case MAPVOTE_RANDOM:
            {
                message = " has chosen to \cdplay a random map\cj.";
                break;
            }
            default:
            {
                int mapIndex = ZH2Game::GameContext.VotableMaps[index - 3];
                str mapName = GetMapRotationInfo(mapIndex, MAPROTATION_NAME);
                str mapLumpName = GetMapRotationInfo(mapIndex, MAPROTATION_LUMPNAME);
                int parsePosition = Map::GetParsedMapPosition(mapIndex);
                if (parsePosition != -1)
                {
                    str replacementMapName = Map::GetMapLabel(parsePosition);
                    if (replacementMapName != (raw)0)
                        mapName = replacementMapName;
                }

                message = " has picked map \cd" + str(mapLumpName) + "\cj: \cd" + mapName + "\cj.";
                break;
            }
        }

        Logger::LogBold(Player::GetPlayerName(PlayerNumber()) + message);

        // Client gets an ambient sound confirming the pick.
        LocalAmbientSound("game/MAPPICK", 127);

        SetPickCooldown();
        SetVotedMapIndex(index);
        CheckMapVoteFinished();
        Sync::SyncMapVoting();
    }

    // Çhecks if the voting should finish as everybody has voted.
    internal void CheckMapVoteFinished()
    {
        bool allowSpectatorVoting = ZH2Game::GetAllowSpectatorVoting();

        // We check if map voting finished by taking the number of voted players and comparing them to those who still have to vote.
        // Note: We also want to check spectator votes here if the cvar was enabled after a spectator already voted.
        int votedPlayers = 0;
        for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
        {
            if (!BCSUtils::PlayerIsConnected(i))
                continue;

            // We don't count spectator votes.
            if (!allowSpectatorVoting && !PlayerInGame(i))
                continue;

            if (HasPlayerVoted(i))
                votedPlayers++;
        }

        int totalVotablePlayerCount = allowSpectatorVoting ? BCSUtils::ClientCount() : PlayerCount();
        totalVotablePlayerCount -= allowSpectatorVoting ? BCSUtils::BotCount() : Utils::PlayingBotCount();

        // Avoid division by zero in case everyone left.
        int votePercentage = 0;
        if (totalVotablePlayerCount > 0)
            votePercentage = (votedPlayers * 100) / totalVotablePlayerCount;

        // Vote threshold reached.
        if (votePercentage >= ZH2Game::GetPlayerVotePercentage())
            EndVoting();
    }

    internal void EndVoting()
    {
        // Get best index to pick for the next map.
        int bestIndex = UpdateMapVoteMajority();
        Logger::LogDebug(LOGSOURCE, "Picking best map vote index: \cd" + str(bestIndex) + "\cj.");

        // If -1, nobody voted.
        // So now we want to pick a map at random.
        // To avoid issues I do not do a full random on all indexes since next/random map might be unavailable.
        // Instead we want to either:
        // - Pick a randomly chosen votable map or random.
        // - Pick the "replay map" vote option if no maps are available.
        // It's a bit more complex, but it ensures that players are able to play more smoothly depending on the situation.
        if (bestIndex == -1)
        {
            int votableMapCount = ZH2Game::GameContext.VotableMapCount;
            if (votableMapCount > 0)
            {
                // Note, we take 1 from `MAPVOTE_HARDCODED_PICKS_LENGTH` because this means "random map" can also be picked.
                bestIndex = Random(0, votableMapCount - 1) + MAPVOTE_HARDCODED_PICKS_LENGTH - 1;
                Logger::LogDebug(LOGSOURCE, "Change best pick to: \cd" + str(bestIndex) + "\cj.");
            }
            else
            {
                bestIndex = MAPVOTE_REPLAY;
                Logger::LogDebug(LOGSOURCE, "Change best pick to: \cdreplay map\cj.");
            }
        }

        // Finally, set the index.
        Map::SetFinalVotedMapIndex(bestIndex);

        // Ensure the voting timer is stopped here if it's active.
        if (RoundTimer::GetActiveTimerKnownType() == RoundTimer::TIMERVOTING)
        {
            int index = RoundTimer::GetActiveTimerIndex();
            if (RoundTimer::GetTimerActive(index))
            {
                RoundTimer::StopTimer(index);
            }
        }

        // This timer is required. If not set we log an error.
        // TODO: Ideally if we started the match we inform the map developer of this.
        int index = RoundTimer::GetIndexOfKnownType(RoundTimer::TIMERVOTED);
        if (RoundTimer::GetTimerDefined(index))
        {
            RoundTimer::SetActiveTimerByKnownType(RoundTimer::TIMERVOTED);
            RoundTimer::StartTimer(index);

            Sync::SyncTimers();
        }
        else Logger::LogError(LOGSOURCE, "Missing required voted timer.");
    }

    // Updates what map index got the majority vote.
    // We determine this by checking each index and seeing which one we have the most.
    internal int UpdateMapVoteMajority()
    {
        int bestIndex = -1;
        int bestIndexCount = 0;

        for (int i = 0; i < ZH2Game::GameContext.VotableMapCount + MAPVOTE_HARDCODED_PICKS_LENGTH; ++i)
        {
            int count = GetMapVoteCount(i);

            // New best index.
            // 50% chance we pick this when same amount of votes were given for this index as the other one.
            // However, do not try and check if the count is 0. This avoids random chance when the map was never picked in general.
            if (count != 0
                && (count > bestIndexCount
                    || (count == bestIndexCount && Random(0, 1))))
            {
                bestIndex = i;
                bestIndexCount = count;
                continue;
            }
        }

        return bestIndex;
    }
}