#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawFullServerHud()
    {
        // Do not draw unless we are having the event.
        int elapsed = Game::GetFullServerElapsedTics();
        if (elapsed == 0)
            return;

        fixed scale = ZH2Game::GetHudFullServerScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0, 480.0);
        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_TOP);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetShowOnFullAutomap(false);

        fixed x = 320.0,
              y = BCSUtils::HudTop() + 50.0;

        int id = HUD_FULLSERVER;
        id = DrawEffectText(id, x, y, "Full server!", elapsed);
    }

    internal int DrawEffectText(int id, fixed x, fixed y, str message, int elapsed)
    {
		for (int i = 0; i < strlen(message); ++i)
		{
			// Draw characters using a type on effect.
			if (elapsed < 8 * i)
				continue;
			
			// This ensures each character is displayed in order.
			fixed charX = 240.0 + (15.0 * fixed(i));
			
			// Wave effect
			fixed part = fixed(elapsed) / fixed(10 * i + (360 / 3));
			fixed charY = 60.0 + BCSUtils::Round(3.0 * Sin(part));
			
			// Goes through all the colors, changing every 10 tics.
			BCSUtils::HudSetTextColor((Timer() / 10 + i) % 20);

            BCSUtils::HudSetPoint(charX, charY);
            BCSUtils::HudDrawText(id--, StrParam(c:message[i]));
		}
        
        return id;
    }
}