//Music Player
/*#library "music_pl"
#include "zcommon.acs"
*/
#define THEME_MUSIC 0
#define RAVISHING_MUSIC 1
#define LAST_HUMAN_MUSIC 2
#define NEDM_MUSIC 3
#define SOULSPHERE_MUSIC  4
#define IMSCARED_MUSIC 5


int Local_musicstore[6]={"IBMSND3","IBMSND2","IBMSND6","NEDM","IBMSND7","SUICIDE"};
int Local_musicstoreHQ[6]={"IBMHQ017","IBMSND2","ibmhq002","ibmhq004","ibmhq003","SUICIDE"};
bool music_quality=false;
int Music_Played=0;


function void play_zm09_music(void){
    if(!music_quality){
        setmusic(Local_musicstore[Music_Played]);
    }else{
        setmusic(Local_musicstoreHQ[Music_Played]);}
}

function void Local_SetLastMusic(void){
    localsetmusic(Local_musicstore[Music_Played]);
}