
int nedm_digit1='-',nedm_digit2='-',nedm_digit3='-',nedm_digit4='-', nedm_digit5='-', nedm_digit6='-';
bool nedm_digit_lock=false;
int nedm_code=0;

int mcdonald=0;
fixed pos_z_nedm;
script 29 (int input){//Nedm Script: Switch counter to allow nedm
    bool script_lock=false;

    pos_z_nedm=getactorz(PlayerNumber()+600);
    if(input==6){
        if(pos_z_nedm<140.0){
            script_lock=true;
    }   }
    else if(input==2){
        if(pos_z_nedm<110.0){
            script_lock=true;
    }   }
    else if(input==3){
        if(pos_z_nedm<230.0){
            script_lock=true;
    }   }
    if(nedm_digit_lock==false && script_lock==false && script_lock==false){
        if(nedm_digit1=='-') {nedm_digit1=input; print(s:"NEDM SWITCH CODE\n",d:nedm_digit1,s:" - - - - -");}
        else if(nedm_digit2=='-') {nedm_digit2=input; print(s:"NEDM SWITCH CODE\n",d:nedm_digit1,s:" ",d:nedm_digit2,s:" - - - -");}
        else if(nedm_digit3=='-') {nedm_digit3=input; print(s:"NEDM SWITCH CODE\n",d:nedm_digit1,s:" ",d:nedm_digit2,s:" ",d:nedm_digit3,s:" - - -");}
        else if(nedm_digit4=='-') {nedm_digit4=input; print(s:"NEDM SWITCH CODE\n",d:nedm_digit1,s:" ",d:nedm_digit2,s:" ",d:nedm_digit3,s:" ",d:nedm_digit4,s:" - -");}
        else if(nedm_digit5=='-') {nedm_digit5=input; print(s:"NEDM SWITCH CODE\n",d:nedm_digit1,s:" ",d:nedm_digit2,s:" ",d:nedm_digit3,s:" ",d:nedm_digit4,s:" ",d:nedm_digit5,s:" -");}
        else if(nedm_digit6=='-') {nedm_digit6=input; print(s:"NEDM SWITCH CODE\n",d:nedm_digit1,s:" ",d:nedm_digit2,s:" ",d:nedm_digit3,s:" ",d:nedm_digit4,s:" ",d:nedm_digit5,s:" ",d:nedm_digit6);}
    }else if(input!=0) print(s:"locked");
    if(nedm_digit6!='-'){
        if(nedm_code==0){
            if(nedm_digit1==1 && nedm_digit2==2 && nedm_digit3==3 && nedm_digit4==4 && nedm_digit5==5 && nedm_digit6==6){
                printbold(n:0, s:" found the right code for active nedm!!!");
                ceiling_raisebyvalue(91,1,8);
                nedm_digit_lock=true;
                nedm_digit6='-';
            }
            else{
                nedm_digit1='-'; nedm_digit2='-'; nedm_digit3='-'; nedm_digit4='-'; nedm_digit5='-'; nedm_digit6='-';
                print(s:"wrong code");
            }
        }else if(nedm_code==1){
            if(nedm_digit1==6 && nedm_digit2==5 && nedm_digit3==4 && nedm_digit4==3 && nedm_digit5==2 && nedm_digit6==1){
                printbold(n:0, s:" found the right code for active nedm!!!");
                ceiling_raisebyvalue(91,1,8);
                nedm_digit_lock=true;
                nedm_digit6='-';
            }
            else{
                nedm_digit1='-'; nedm_digit2='-'; nedm_digit3='-'; nedm_digit4='-'; nedm_digit5='-'; nedm_digit6='-';
                print(s:"wrong code11");
            }
        }else if(nedm_code==2){
            if(nedm_digit1==1 && nedm_digit2==1 && nedm_digit3==1 && nedm_digit4==6 && nedm_digit5==6 && nedm_digit6==6){
                printbold(n:0, s:" found the right code for active nedm!!!");
                ceiling_raisebyvalue(91,1,8);
                nedm_digit_lock=true;
                nedm_digit6='-';
            }
            else{
                nedm_digit1='-'; nedm_digit2='-'; nedm_digit3='-'; nedm_digit4='-'; nedm_digit5='-'; nedm_digit6='-';
                print(s:"wrong code");
            }
        }else{
            if(nedm_digit1==6 && nedm_digit2==6 && nedm_digit3==6 && nedm_digit4==1 && nedm_digit5==1 && nedm_digit6==1){
                printbold(n:0, s:" found the right code for active nedm!!!");
                ceiling_raisebyvalue(91,1,8);
                nedm_digit_lock=true;
                nedm_digit6='-';
            }
            else{
                nedm_digit1='-'; nedm_digit2='-'; nedm_digit3='-'; nedm_digit4='-'; nedm_digit5='-'; nedm_digit6='-';
                print(s:"wrong code");
            }

        }
    }
    //-------------------------------------------------------------------------------------------------
    if(input==0) {mcdonald++;}
    if(mcdonald==55){
        ceiling_lowerbyvalue(91,100,8);
        ceiling_raisebyvalue(92,1,8);
    }
    else if(mcdonald==105){
        acs_execute(30,0,0,0,0);
        ceiling_lowerbyvalue(92,100,8);
        delay(353);
        floor_lowerbyvalue(89,200,200);
        floor_lowerbyvalue(90,200,200);
        tagwait(90);
        Floor_Waggle(89, 2000, 100, 0, 0);
        delay(100);
        Floor_Waggle(90, 2000, 100, 0, 0);
    }
}



bool nedm_desactive=false;

script 30 (void) clientside{//NEDM code spam
    int counter=0;
    fixed posy= -3.0;
    while(posy<=0.05){
        SetFont("NEDML");
        if(nedm_desactive==false)HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, 0.5, posy,0.1,0.0, 0.3);
        posy+=0.01;
        delay(1);
    }SetFont("NEDML");
    if(nedm_desactive==false)HudMessagebold(s:"A"; HUDMSG_PLAIN , 800, counter, 0.5, posy,1.5,0.0, 0.0);
    Music_Played=NEDM_MUSIC;
    if(nedm_desactive==false)play_zm09_music();
    delay(35);
    if(nedm_desactive==false)spawnspot("FlareDisco",87,132,0);
    ACS_Suspend(34,0);
    acs_execute(31,0);
    if(nedm_desactive==false)acs_execute(33,0);
    while(true){
        if(nedm_desactive==false){
            SetFont("NEDML");
            HudMessagebold(s:"A"; HUDMSG_PLAIN , 800, counter, 0.5 + Math::FRandom(Math::FRandom(-0.1,0.0), Math::FRandom(0.0,0.1)), posy + Math::FRandom(-0.05,0.05),0.1,0.0, 0.0);
        }delay(1);
    }
}

script 31 (void) clientside{//Nedm Code:Cat see
    fixed posx1=0.1;
    fixed posx2=0.9;
    fixed posy=0.9;
    while(true)
    {
        while(posy>=0.1)
        {
            if(nedm_desactive==false)
            {
                SetFont("NEDMCAT");
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx1+sin(posy), posy,0.1,0.0, 0.2);
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx2-sin(posy), posy,0.1,0.0, 0.2);
            }
            posy-=0.010;
            delay(3);
        }

        while(posx1<=0.9)
        {
            if(nedm_desactive==false)
            {
                SetFont("NEDMCAT");
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx1, posy+sin(posx1),0.1,0.0, 0.2);
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx2, posy-sin(posx2),0.1,0.0, 0.2);
            }
            posx2=1.0-posx1;
            posx1+=0.010;
            delay(3);
        }

        while(posy<=0.9)
        {
            if(nedm_desactive==false)
            {
                SetFont("NEDMCAT");
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx1+sin(posy), posy,0.1,0.0, 0.2);
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx2-sin(posy), posy,0.1,0.0, 0.2);
            }
            posy+=0.010;
            delay(3);
        }

        while(posx1>=0.1)
        {
            if(nedm_desactive==false)
            {
                SetFont("NEDMCAT");
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx1, posy+sin(posx1),0.1,0.0, 0.2);
                HudMessagebold(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, posx2, posy-sin(posx2),0.1,0.0, 0.2);
            }
            posx2=1.0-posx1;
            posx1-=0.010;
            delay(3);
        }
        delay(1);
    }
}

script 33 (int light, int var) clientside{//Nedm colored lights
    int arg1,arg2,arg3;
    int posy,i;
    if(light==2){
        For(i=49;i<=52;i++)    Thing_SetSpecial(i,0,var,var,var);
        Thing_SetSpecial(86,0,var,var,var);
        Thing_SetSpecial(88,0,var,var,var);
    }
    else{
        while(TRUE){
            posy=random(0,6);
            switch(posy){
            case 0:
                arg1=random(70,255);
                arg2=random(70,255);
                arg3=random(70,255);
                break;
            case 1:
                arg1=random(0,100);
                arg2=random(0,100);
                arg3=random(100,255);
                break;
            case 2:
                arg1=random(0,100);
                arg2=random(100,255);
                arg3=random(0,100);
                break;
            case 3:
                arg1=random(100,255);
                arg2=random(0,100);
                arg3=random(0,100);
                break;
            case 4:
                arg1=random(100,255);
                arg2=random(100,255);
                arg3=random(0,100);
                break;
            case 5:
                arg1=random(100,255);
                arg2=random(0,100);
                arg3=random(100,255);
                break;
            case 6:
                arg1=random(0,100);
                arg2=random(100,255);
                arg3=random(100,255);
                break;
            }
            for(i=49;i<53;i++) Thing_SetSpecial(i,0,arg1,arg2,arg3);
            Thing_SetSpecial(86,0,arg1,arg2,arg3);
            Thing_SetSpecial(88,0,arg1,arg2,arg3);
            delay(3);
        }
    }
}
