script 13 (void){//Ravishing Script: Summon ravishing and other resources
    int input=GetCvar("x_zh_zm09_ra");
    SetCvar("x_zh_zm09_ra",input+1);
    delay(random(350,700));
    SetFont("BIGFONT");
    ThingSound(77,"IBMEFF3",127);
    generator1 = false;
    acs_execute(34,0, (int)generator1 * 10 + (int)generator2,0,0);
    Thing_remove(96);
    HudMessageBold(s:"\nPRIMARY GENERATOR IS NOW DESTROYED"; HUDMSG_FADEOUT, 980, CR_RED, 0.5, 0.2, 9.8, 0.5);
    delay(50);
    ThingSound(97,"IBMEFF3",127);
    delay(50);
    ThingSound(97,"IBMEFF2",127);
    Music_Played=RAVISHING_MUSIC;
    play_zm09_music();
    SpawnSpot ("ravishingBETA",25,100,24);
    acs_execute(4,0,1,0,0);
    delay(35);

    while(Round::GetGameIsEnding() == false)
    {
        delay(10);
    }
    Thing_Deactivate(100);
}
