//#library "zm09_tnx"
//#include "zcommon.acs"




function void zm09_information(void){
    zm09_main_intro();
    printbold(s:"");
    zm09_main_credits();
    printbold(s:"");
    zm09_main_tutorial();
    zm09_main_settings();
	printbold(s:"");
}
function void zm09_main_intro(void){
    printbold(s:"============================================================\n|ZM09 - ABANDONED MINES - CREATED BY IBM5155\n============================================================\n					/!\ OpenGL required /!\ \n					\!/ Playable on soft\!/ \nZM09 V1.64");

}

function void zm09_main_credits(void){
    printbold(s:"SPECIAL THANKS TO:\n-ESTAR\n-Ijon Tichy\n-Slave2theLight\n-Torn City author\n-Ivan Zanotti\n-Dusk\n-IVAN\n-HexaDoken\n-Cruduxy\n-Popsoap\n-Mr.Fiat\n-FUSED\n-'Monolith' for the piano sound\n-'Mojang' for the rain sound\n-'Imscared - A Pixelated Nightmare' for the white face idea");

}

function void zm09_main_tutorial(void){
    printbold(s:"FAST HELP\n-The red key card spawn randomly everywhere, there'll be no specific place for spawn\n-on the computer room on the red door sector, there'll be sometimes a display with number, this number have a secret code, if you discover the secret of the code you'll know the right code to put on the switches\n-One of the third floor rooms are haunted, so look out when entering there\n-To activate NEDM you'll need to make the right code outside, and then press 2 switches inside cade X times\n-Ravishing and White-Face don't kill zombies, so have fun being a zombie\n-Soulphere is as dangerous for humans as for zombies\n-if you're laging, down the map settings writing puke 48 here");
}

function void zm09_main_settings(void){
    HudMessagebold(s:"\czmap settings can be configured writing \cjpuke 48\cf on console\n\czmap tutorial can be acessed writing \cjpuke 62\cf on console (offline only)"; HUDMSG_FADEINOUT, 544, CR_UNTRANSLATED, 0.5, 0.8,15.1,0, 0.3);
}