//ZM09 Code
int ibmnu_text[5]={"ibmnu1","ibmnu2","ibmnu3","ibmnu4","ibmnu1"};
int lava_del_tids[8]={44,49,50,51,52,53,72,86};
int tele_x,tele_y,tele_z,tele_active=0;
int secret[10];//a var to store the right code and the typed code and how right/wrong it is
//switch [ 0 - 3] store the right code
//switch [ 4 - 7] store the typed code
//switch [ 8    ] store how wrong the code is
//switch [ 9    ] store how rigt the code is

int selected;// ?
int force_whiteface=false;

#define SPAWN_LAVA_SOUND 1
#define WRONG_CNT_INDEX 8
#define RIGHT_CNT_INDEX 9
#define ALL_DIGITS_INSERTED 4

script 2 (int x){//Red door Switches
    test_secret(x);
}

script 6 (void){//Lava Script
    int time_delay=0;
    tele_active=1;
    time_delay=random(0,30);
    if(time_delay>0) delay(35*time_delay);
    Thing_ChangeTID(500, 66);
    acs_execute(15,0,SPAWN_LAVA,0,0);//text effect
    ThingSound(15,"IBMSND1",255);
    Radius_Quake(random(5,9), 12*35, 0, 16, 15);
    delay(255);
    
    Ceiling_LowerAndCrush(4,7,6553);
    Ceiling_LowerAndCrush(10,7,65536);
    Ceiling_LowerAndCrush(94,4,65536);
    Ceiling_LowerAndCrush(14,7,65536);
    Ceiling_LowerAndCrush(18,7,65536);
    Ceiling_LowerAndCrush(124,7,65536);
    delay(350);
    
    ceiling_raisebyvalue(9,10,335);
    ceiling_raisebyvalue(48,10,464);
    acs_execute(15,0,SPAWN_LAVA_SOUND,0,0);//text effect
    delay(350);
    
    door_close(4,7);    door_close(10,7);    door_close(94,4);    door_close(14,7);    door_close(18,7);    door_close(124,7);
    acs_execute(17,0,0,0,0);
    time_delay=0;while(time_delay<8){
        thing_remove(lava_del_tids[time_delay]);time_delay++;
    }generator2=0;
    acs_execute(34,0,generator1*10+generator2,0,0);
    Light_ChangeToValue(80,80);
    Light_changetovalue(81,80);
    Thing_ChangeTID(66, 500);
    Sector_SetDamage(7,MOD_LAVA,MOD_LAVA);
    delay(random(350,3500));
    
    acs_execute(13,0,0,0,0); // Invoke Ravishing.
}

script 7 (void){//50% Right code door open on cave
    floor_lowerbyvalue(29,25,320);
    floor_lowerbyvalue(26,25,256);
    floor_lowerbyvalue(24,25,192);
    floor_LOWERbyvalue(17,25,128);
    floor_lowerbyvalue(16,25,64);
}

script 15 (int action) clientside{//Lava Script: Message/sound Effect
    if(action==SPAWN_LAVA){
        int i=0;
        while(i<17){
            SetFont("BIGFONT");
            HudMessageBold(s:"                                        \c[j5]EVACUATE THE CAVE IMMEDIATELY!!! OR GET TOASTED"; HUDMSG_FADEOUT, 999, CR_RED, 0.5, 0.2, 0.5, 0.5);
            i++;
            delay(35);
        }
        delay(random(400,800));
        delay(200);
    }else{
        while(true){//Replace with ambientsound
            ThingSound(15,"ibmlava1",255);
            delay(67);
        }   
    }   
}


script 27 open { //Cursor blink logic.
    int comm=0;
    int num_pos=0;
    int s_exit=FALSE;
    while(s_exit==FALSE){
        if(comm==0 && secret[WRONG_CNT_INDEX] + secret[RIGHT_CNT_INDEX]!= ALL_DIGITS_INSERTED) { // "_"
            SetLineTexture(secret[WRONG_CNT_INDEX] + secret[RIGHT_CNT_INDEX] + 82,SIDE_FRONT,TEXTURE_MIDDLE,"ibmnu5"); 
            comm++;
        }
        else if (secret[WRONG_CNT_INDEX] + secret[RIGHT_CNT_INDEX] != ALL_DIGITS_INSERTED) {// " "
            SetLineTexture(secret[WRONG_CNT_INDEX]+secret[RIGHT_CNT_INDEX]+82,SIDE_FRONT,TEXTURE_MIDDLE,"ibmnu6"); 
            comm--;
        }
        else{
            s_exit=true;
        }
        num_pos=secret[secret[WRONG_CNT_INDEX]+secret[RIGHT_CNT_INDEX]+3];//receive the actual number;
        if(num_pos!=0){
            SetLineTexture(secret[WRONG_CNT_INDEX]+secret[RIGHT_CNT_INDEX]+81,SIDE_FRONT,TEXTURE_MIDDLE,ibmnu_text[num_pos-1]);
        }delay(10);
    }
}

script 68 (int type_human) { //only actived when 100% right code, or 0% right code
 	if (type_human == false){
        delay(random(10*35,35*35));
        ambientsound("zombie_boss",127);
        delay(35*13);
    }

    for(int j = 0; j < BCSUtils::MAX_PLAYERS; j++)
    {
        int tid = Identity::GetTid(j);
        if(PlayerInGame(j)) // There is a player
        {
            if(type_human && !Player::GetPlayerIsZombie(j)) // This player is a human and humans are rewarded
                GiveActorInventory(tid, "ZH2ItemRewardOrbMinor", 1);

            else if(!type_human && Player::GetPlayerIsZombie(j)) // This player is a zombie and zombies are rewarded
                GiveActorInventory(tid, "ZH2ItemRewardOrbMinor", 1);
                thingsound(tid,"zombie_boss_start",127);
        }
        delay(1);
    }
}

script 70 (int code) NET{
	if(code==1414325){
	force_whiteface=true;
	print(d:force_whiteface);
	print(s:"force white face spawn = true when the code is all wrong");
	}else print(s:"nop");
}

script 71 (int code, int scrpt_numb){
	if(code==1414325){
		acs_suspend(scrpt_numb,0);
	}
}

#define _100PCT_CORRECT 4
#define _75PCT_CORRECT 3
#define _50PCT_CORRECT 2
#define _25PCT_CORRECT 1
#define _0PCT_CORRECT 0

function void test_secret (int switchh){
    int i=0;
    selected++;
    secret[selected+3]=switchh;
    if(secret[selected+3]==secret[selected-1])
    {
        secret[RIGHT_CNT_INDEX]++;
    }
    else
    {
         secret[WRONG_CNT_INDEX]++;
    }

    if (selected != ALL_DIGITS_INSERTED)
    {
        return;
    }

    if(secret[RIGHT_CNT_INDEX] == _100PCT_CORRECT) {
        //print_developer(1,"100% right code",0,0,0,0,0);
        selected=GetCvar("x_zh_zm09_100");
        SetCvar("x_zh_zm09_100",selected+1);
        print_code();
        selected=random(0,100);
        if(selected<50){
            SetFont("BIGFONT");
            AmbientSound("achievement/unlocked",127);
            HudMessageBold(s:"a  wall has been opened"; HUDMSG_FADEOUT, 999, CR_GREEN, 0.5, 0.2, 5.5, 0.5);
            AmbientSound("world/reveal1",127);
            door_open(5,18);
        }else if(selected<70){
            SetFont("BIGFONT");
            AmbientSound("achievement/unlocked",127);
            AmbientSound("world/reveal1",127);
            HudMessageBold(s:"ALL HUMANS GAINED ITENS!!!!"; HUDMSG_FADEOUT, 999, CR_GREEN, 0.5, 0.2, 5.5, 0.5);
            AmbientSound("world/reveal1",127);
            Acs_execute(68,0,1,0,0);
        }else{
            SetFont("BIGFONT");
            HudMessageBold(n:0,s:" Opened all the secret passages!!!"; HUDMSG_FADEOUT, 999, CR_GREEN, 0.5, 0.2, 5.5, 0.5);
            AmbientSound("world/reveal1",127);
            AmbientSound("achievement/unlocked",127);
            door_open(11,24);
            door_open(62,24);
            door_open(5,18);
        }
    }
    else if(secret[RIGHT_CNT_INDEX] == _50PCT_CORRECT){
        selected=GetCvar("x_zh_zm09_50");
        SetCvar("x_zh_zm09_50",selected+1);
        selected=random(0,5);
        print_code();
        if(selected>3){//50% right code
            SetFont("BIGFONT");
			//print_developer(1,"50% right code",0,0,0,0,0);
            HudMessageBold(s:"a door has been unlocked"; HUDMSG_FADEOUT, 999, CR_GREEN, 0.5, 0.2, 5.5, 0.5);
            AmbientSound("world/reveal1",127);
            door_open(62,24);
        }else{//50% right code + ravishing
            SetFont("BIGFONT");
			//print_developer(1,"50% right code",0,0,0,0,0);
            HudMessageBold(s:"a door has been opened"; HUDMSG_FADEOUT, 999, CR_GREEN, 0.5, 0.2, 5.5, 0.5);
            AmbientSound("world/reveal1",127);
            door_open(11,24);
            ravishing_selector(100);
        }AmbientSound("world/reveal1",127);
    }
    else if(secret[RIGHT_CNT_INDEX]==_25PCT_CORRECT){
		//print_developer(1,"25% right code",0,0,0,0,0);
        selected=GetCvar("x_zh_zm09_25");
        SetCvar("x_zh_zm09_25",selected+1);
        print_code();
        ravishing_selector(35);
        Acs_ExecuteAlways(164, 0, PlayerNumber(), 0, 0);
    }
    else if(secret[RIGHT_CNT_INDEX] == _0PCT_CORRECT){
        selected=GetCvar("x_zh_zm09_0");
        SetCvar("x_zh_zm09_0",selected+1);
        selected=random(0,100);
        if(selected >= 90 || force_whiteface==true){//White Face script
            acs_execute(35,0,0,0,0);
            acs_execute(4,0,0,0,0);
            SpawnSpot ("IMSCARED2BETA",25,100,24);
            HudMessageBold(s:"Thanks ", n:0, s:" Now I'm free again!!!"; HUDMSG_FADEOUT, 919, CR_GREEN, 0.5, 0.6, 5.5, 0.5);
            selected=GetCvar("x_zh_zm09_wf");
            SetCvar("x_zh_zm09_wf",selected+1);
        }else if(selected>=30){
            // Give Special Items to Zombies.
            i=GetCvar("x_zh_zm09_zp");
            SetCvar("x_zh_zm09_zp",i+1);
            Acs_execute(68,0);
        }
        else 
        {
            // Spawn Lava + Ravishing.
            ACS_Execute(6,0,0,0,0);
        }
        print_code();
    }
}

function void red_keyspawn(void){
    switch(random(0,10)){
    case 0:spawn("mapspot",random(-721.0,-409.0),random(1873.0,2711.0),632.0,350,0); TeleportOther(36,350,1);break;
    case 1:spawn("mapspot",random(4528.0,5135.0),random(-1664.0,-1361.0),400.0,350,0); TeleportOther(36,350,1);break;
    case 2:spawn("mapspot",random(5623.0,5807.0),random(-783.0,-497.0),472.0,350,0); TeleportOther(36,350,1);break;
    case 3:spawn("mapspot",random(2080.0,4079.0),random(2448.0,3823.0),463.0,350,0); TeleportOther(36,350,1);break;
    case 4:spawn("mapspot",random(-3088.0,-2553.0),random(-1776.0,-1281.0),112.0,350,0); TeleportOther(36,350,1);break;
    case 5:spawn("mapspot",random(1114.0,1775.0),random(392.0,825.0),318.0,350,0); TeleportOther(36,350,1);break;
    case 6:spawn("mapspot",random(-1856.0,-1169.0),random(2125.0,2351.0),327.0,350,0); TeleportOther(36,350,1);break;
    case 7:spawn("mapspot",random(4416.0,4471.0),random(-2004.0,-1961.0),400.0,350,0); TeleportOther(36,350,1);break;
    case 8:spawn("mapspot",random(-2512.0,879.0),random(-1716.0,-449.0),362.0,350,0); TeleportOther(36,350,1);break;
    case 9:spawn("mapspot",random(4550.0,4719.0),random(-1246.0,-1169.0),465.0,350,0); TeleportOther(36,350,1);break;
    case 10:spawn("mapspot",random(-1808.0,-1585.0),random(-2320.0,-2052.0),72.0,350,0); TeleportOther(36,350,1);break;
    }
}

function void ravishing_selector(int lucky){
    int test=random(0,lucky);
    if(test<=15)  acs_execute(13,0,0,0);
}

function void print_code(void){
    HudMessageBold(n:0, s:" activated the code"; HUDMSG_FADEOUT, 997, CR_RED, 0.5, 0.5, 9.5, 0.5);
    HudMessageBold(s:"the right code is:",d:secret[0],d:secret[1],d:secret[2],d:secret[3]; HUDMSG_FADEOUT, 996, CR_RED, 0.5, 0.52, 9.5, 0.5);
    HudMessageBold(n:0, s:" code is:",d:secret[4],d:secret[5],d:secret[6],d:secret[7]; HUDMSG_FADEOUT, 995, CR_RED, 0.5, 0.54, 9.5, 0.5);
    HudMessageBold(s:"the code is ",d:100-25*secret[WRONG_CNT_INDEX],s:"% right"; HUDMSG_FADEOUT, 985, CR_RED, 0.5, 0.56, 9.5, 0.5);
}

function void secret_select(void){
    int i, j, temp;

    // Initialize ordered sequence
    secret[0] = 1;
    secret[1] = 2;
    secret[2] = 3;
    secret[3] = 4;

    // Fisher-Yates shuffle
    for(i = 3; i > 0; i--)
    {
        j = random(0, i);

        temp = secret[i];
        secret[i] = secret[j];
        secret[j] = temp;
    }
}