int ZM09VER[7]={'v','1','.','6','5'};

/* V1.65
- Minimal Changes for working with Zombie Horde 2
- Made White face slower.
- fixed CVAR definition.
- fixed death script not logging the correct actors.
- fixed map settings.
- made rainfall lighter.
- added console menu for settings.
- Fixed Soulsphere not appearing.
*/

/* V1.63
-Created ZM09VER.acs
-Adapted Soulsphere script to the new zombie horde code
*/