#pragma raw include on
#pragma raw define on

//functions that aren't related to zm09 map but yes with general things

function int GetPlayerRender(void) {return GetCVar ("vid_renderer");}




function int unusedTID(int start, int end)//THIS FUNCTION WAS CREATED BY Ijon Tichy
{
    int ret = start - 1;
    int tidNum;
    if (start > end) { start ^= end; end ^= start; start ^= end; }
    while (ret++ != end){
        if (ThingCount(0, ret) == 0)  return ret;
    }
    return -1;
}

function fixed GetHigherCeiling(int tid2) {//THIS FUNCTION WAS CREATED BY Ijon Tichy and edited  by IBM5155
    fixed posx=getactorx(tid2);
    fixed posy=getactory(tid2);
    fixed posz=GetActorCeilingZ(tid2);//504
    fixed z=posz+25.0;
    int test=0;
    int tid=unusedTID(1000, 2000);
    spawn("mapspot",posx,posy,z,tid,0);
    while(GetActorCeilingZ(tid) != 0.0)
    {
        z=z+25.0;//850.0
        thing_remove(tid);
        spawn("mapspot",posx,posy,z,tid,0);
        test++;
    }
    if(test==0)
    {
        thing_remove(tid);
        z=posz;
    }
    else
    {
        thing_remove(tid);
        spawn("mapspot",posx,posy,z-27.0,tid,0);
        z = GetActorCeilingZ(tid);
        thing_remove(tid);
    }

    return z;
}

function fixed hud_resize(void){
    int x=get_screenx();
    int y=get_screeny();
    fixed output = 0.0;
    if (x <= 320) output = 0.02;
    else if(x<=640) output = 0.01;
    else output = 0.0;
    return output;

}
function int get_screeny(void){
    return getcvar("vid_defheight");
}

function int get_screenx(void){
    return getcvar("vid_defwidth");
}


function int divide(int a, int b){
    int c=0;
    if(b!=0)
        c=a/b;
    return c;
}