//ZM09 Database

script 23 (int type, int arg1, int arg2) clientside{//Update the clientside from who called the debug command
    if(type==1){
        user_ghoulactivesound=arg1; 
        user_invisible=arg2;
    }else if(type==2){
        script_test=arg1; 
        ghoul_invtest=arg2;
    }else if(type==3){
        stuck_test=arg1;   
        script_test=arg2;
    }else if(type==4){
        ghoul_hate=arg1;   
        sound_toplay=arg2;
    }else if(type==5){
        ghoul_target=arg1; 
        monster_target_distance=arg2;
    }else if(type==6){
        soulsphere_damage=arg1;    
        generator1=arg2;
    }else if(type==7){
        generator2=arg1; 
        zm09_dev2=arg2;
    }else if(type==8){
        zm09_weather=arg1;
        debug_zm09=arg2;       
    }
}

script 26 open{//Update server side functions to clientside
    while(true){
        acs_execute(23,0,1,user_ghoulactivesound,user_invisible);
        delay(1);
        acs_execute(23,0,2,script_test,ghoul_invtest);
        delay(1);
        acs_execute(23,0,3,stuck_test,script_test);
        delay(1);
        acs_execute(23,0,4,ghoul_hate,sound_toplay);
        delay(1);
        acs_execute(23,0,5,ghoul_target,monster_target_distance);
        delay(1);
        acs_execute(23,0,6,soulsphere_damage,generator1);
        delay(1);
        acs_execute(23,0,7,generator2,zm09_dev2);
        delay(1);
        acs_execute(23,0,8,zm09_weather,ibm_distance(100,ghoul_target));
        delay(10);
    }
}

script 63 DEATH{//ZM09 STATISTICS
    int input;
    int input2;
    if(ghoul_target==playernumber()+PLAYER_TID){
        if(ThingCountName ("ravishing",0)==1){
            input=GetCvar("x_zh_zm09_rk");
            SetCvar("x_zh_zm09_rk",input+1);
        }else if(ThingCountName ("imscared2",0)==1){
            input=GetCvar("x_zh_zm09_wk");
            SetCvar("x_zh_zm09_wk",input+1);
        }else if(ThingCountName ("ghouldemon",0)>=1){//pacman
            input=GetCvar("x_zh_zm09_sk");
            SetCvar("x_zh_zm09_sk",input+1);
        }
    }
}

script 64 (int who) DISCONNECT{//REGISTER IS SOMEONE DISCONNECTED
//	print_developer(3,"Player tid",who," DISCONNECTED",0,0,0);
    int input=GetCvar("x_zh_zm09_di");
    SetCvar("x_zh_zm09_di",input+1);
}

script 65 (void) NET{//Update clientside statistics
    int a;
    int b;
    a=getcvar("x_zh_zm09_zw");
    b=getcvar("x_zh_zm09_hw");
    acs_execute(66,0,0,a,b);
    delay(10);
    a=getcvar("x_zh_zm09_to");
    b=getcvar("x_zh_zm09_cn");
    acs_execute(66,0,1,a,b);
    delay(10);
    a=getcvar("x_zh_zm09_di");
    b=getcvar("x_zh_zm09_wf");
    acs_execute(66,0,2,a,b);
    delay(10);
    a=getcvar("x_zh_zm09_ra");
    b=getcvar("x_zh_zm09_sf");
    acs_execute(66,0,3,a,b);
    delay(10);
    a=getcvar("x_zh_zm09_wk");
    b=getcvar("x_zh_zm09_rk");
    acs_execute(66,0,4,a,b);
    delay(10);
    a=getcvar("x_zh_zm09_sk");
    b=getcvar("x_zh_zm09_0");
    acs_execute(66,0,5,a,b);
    delay(10);
    a=getcvar("x_zh_zm09_25");
    b=getcvar("x_zh_zm09_50");
    acs_execute(66,0,6,a,b);
    delay(10);
    a=getcvar("x_zh_zm09_100");
    b=getcvar("x_zg_zm09_zp");
    acs_execute(66,0,7,a,b);
    delay(10);
}



script 66 (int action,int data1,int data2) CLIENTSIDE{//update clientside statistics
    switch(action){
    case 0:
        setcvar("x_zh_zm09_zw",data1);
        setcvar("x_zh_zm09_hw",data2);
    break;
    case 1:
        setcvar("x_zh_zm09_to",data1);
        setcvar("x_zh_zm09_cn",data2);
    break;
    case 2:
        setcvar("x_zh_zm09_di",data1);
        setcvar("x_zh_zm09_wf",data2);
    break;
    case 3:
        setcvar("x_zh_zm09_ra",data1);
        setcvar("x_zh_zm09_sf",data2);
    break;
    case 4:
        setcvar("x_zh_zm09_wk",data1);
        setcvar("x_zh_zm09_rk",data2);
    break;
    case 5:
        setcvar("x_zh_zm09_sk",data1);
        setcvar("x_zh_zm09_0",data2);
    break;
    case 6:
        setcvar("x_zh_zm09_25",data1);
        setcvar("x_zh_zm09_50",data2);
    break;
    case 7:
        setcvar("x_zh_zm09_100",data1);
        setcvar("x_zh_zm09_zp",data2);
    break;
    

    }
}

script 67 (void) NET clientside{//show statistics
    int x_zh_zm09_zw;// zombies wins (ok) script 1
    int x_zh_zm09_hw;// humans wins (ok) script 1
    int x_zh_zm09_to;// total of players who played zm09 (ok) script 22
    int x_zh_zm09_cn;// how many times was zm09 played (ok) script 1
    int x_zh_zm09_di;// disconnected players on zm09 (OK) script 63
    int x_zh_zm09_wf;// how many times white face apeared (ok) test_secret function
    int x_zh_zm09_ra;// how many times ravishing apeared (ok) script 13
    int x_zh_zm09_sf;// how many times soulsphere apeared (ok) script 22
    int x_zh_zm09_wk;// how many kills did white face (ok) script 63
    int x_zh_zm09_rk;// how many kills did ravishing  (ok) script 63
    int x_zh_zm09_sk;// how many kills did soulsphere (ok) script 63
    int x_zh_zm09_0;//  0% right code (ok) test_secret function
    int x_zh_zm09_25;// 25% right code (ok) test secret function
    int x_zh_zm09_50;// 50% right code (ok) test_secret function
    int x_zh_zm09_100;// 100% right code (ok) test_secret function
    int x_zh_zm09_zp;// how many times the zombies got power up when the code was 0%
    while(GetPlayerInput(-1, INPUT_BUTTONS)!=BT_USE){
        x_zh_zm09_zw=getcvar("x_zh_zm09_zw");
        x_zh_zm09_hw=getcvar("x_zh_zm09_hw");
        x_zh_zm09_to=getcvar("x_zh_zm09_to");
        x_zh_zm09_cn=getcvar("x_zh_zm09_cn");
        x_zh_zm09_di=getcvar("x_zh_zm09_di");
        x_zh_zm09_wf=getcvar("x_zh_zm09_wf");
        x_zh_zm09_ra=getcvar("x_zh_zm09_ra");
        x_zh_zm09_sf=getcvar("x_zh_zm09_sf");
        x_zh_zm09_wk=getcvar("x_zh_zm09_wk");
        x_zh_zm09_rk=getcvar("x_zh_zm09_rk");
        x_zh_zm09_sk=getcvar("x_zh_zm09_sk");
        x_zh_zm09_0=getcvar("x_zh_zm09_0");
        x_zh_zm09_25=getcvar("x_zh_zm09_25");
        x_zh_zm09_50=getcvar("x_zh_zm09_50");
        x_zh_zm09_100=getcvar("x_zh_zm09_100");
        x_zh_zm09_zp=getcvar("x_zh_zm09_zp");
        SetFont("BIGFONT");
        HudMessageBold(s:"ZM09 STATISTICS, puke 65 to update your information"; HUDMSG_FADEOUT, 500, CR_GREEN, 0, 0.18, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cdHow many times people played this map:",d:x_zh_zm09_cn; HUDMSG_FADEOUT, 501, CR_RED, 0, 0.20, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cdHow many players played this map:",d:x_zh_zm09_to, s:" (",d:divide(x_zh_zm09_to,x_zh_zm09_cn),s:" players per time)"; HUDMSG_FADEOUT, 502, CR_RED, 0, 0.22, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cdHow many players disconnected in this map:",d:x_zh_zm09_di,s:" (",d:divide(x_zh_zm09_di*100,x_zh_zm09_to),s:"% of all players, ",d:divide(x_zh_zm09_di,x_zh_zm09_cn),s:" players by map) "; HUDMSG_FADEOUT, 503, CR_RED, 0, 0.24, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cfHow many times white face appeared in this map:",d:x_zh_zm09_wf,s:" (",d:divide(x_zh_zm09_wf*100,x_zh_zm09_cn),s:"%)"; HUDMSG_FADEOUT, 504, CR_RED, 0, 0.26, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cfHow many times ravishing appeared in this map:",d:x_zh_zm09_ra,s:" (",d:divide(x_zh_zm09_ra*100,x_zh_zm09_cn),s:"%)"; HUDMSG_FADEOUT, 505, CR_RED, 0, 0.28, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cfHow many times soul sphere appeared in this map:",d:x_zh_zm09_sf,s:" (",d:divide(x_zh_zm09_sf*100,x_zh_zm09_cn),s:"%)"; HUDMSG_FADEOUT, 506, CR_RED, 0, 0.30, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cfHow many times there was no ghouls in this map:",d:x_zh_zm09_cn-x_zh_zm09_wf-x_zh_zm09_ra-x_zh_zm09_sf,s:" (",d:100-divide((x_zh_zm09_wf+x_zh_zm09_ra+x_zh_zm09_sf)*100,x_zh_zm09_cn),s:"%)"; HUDMSG_FADEOUT, 514, CR_RED, 0, 0.32, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cgHow many kills did white face in this map:",d:x_zh_zm09_wk,s:" (",d:divide(x_zh_zm09_wk*100,x_zh_zm09_wk+x_zh_zm09_rk+x_zh_zm09_sk),s:"%)"; HUDMSG_FADEOUT, 507, CR_RED, 0, 0.34, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cgHow many kills did Ravishing in this map:",d:x_zh_zm09_rk,s:" (",d:divide(x_zh_zm09_rk*100,x_zh_zm09_wk+x_zh_zm09_rk+x_zh_zm09_sk),s:"%)"; HUDMSG_FADEOUT, 508, CR_RED, 0, 0.36, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cgHow many kills did Soul Sphere in this map:",d:x_zh_zm09_sk,s:" (",d:divide(x_zh_zm09_sk*100,x_zh_zm09_wk+x_zh_zm09_rk+x_zh_zm09_sk),s:"%)"; HUDMSG_FADEOUT, 509, CR_RED, 0, 0.38, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cjHow many times the code typed was 0% correct:",d:x_zh_zm09_0,s:" (compared to other codes:",d:divide(x_zh_zm09_0*100,x_zh_zm09_0+x_zh_zm09_25+x_zh_zm09_50+x_zh_zm09_100),s:"%, ",d:divide(x_zh_zm09_0*100,x_zh_zm09_cn),s:"%of change to happen per round)"; HUDMSG_FADEOUT, 510, CR_RED, 0, 0.40, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cjHow many times the code typed was 25% correct:",d:x_zh_zm09_25,s:" (compared to other codes:",d:divide(x_zh_zm09_25*100,x_zh_zm09_0+x_zh_zm09_25+x_zh_zm09_50+x_zh_zm09_100),s:"%, ",d:divide(x_zh_zm09_25*100,x_zh_zm09_cn),s:"%of change to happen per round)"; HUDMSG_FADEOUT, 511, CR_RED, 0, 0.42, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cjHow many times the code typed was 50% correct:",d:x_zh_zm09_50,s:" (compared to other codes:",d:divide(x_zh_zm09_50*100,x_zh_zm09_0+x_zh_zm09_25+x_zh_zm09_50+x_zh_zm09_100),s:"%, ",d:divide(x_zh_zm09_50*100,x_zh_zm09_cn),s:"%of change to happen per round)"; HUDMSG_FADEOUT, 512, CR_RED, 0, 0.44, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cjHow many times the code typed was 100% correct:",d:x_zh_zm09_100,s:" (compared to other codes:",d:divide(x_zh_zm09_100*100,x_zh_zm09_0+x_zh_zm09_25+x_zh_zm09_50+x_zh_zm09_100),s:"%, ",d:divide(x_zh_zm09_100*100,x_zh_zm09_cn),s:"%of change to happen per round)"; HUDMSG_FADEOUT, 513, CR_RED, 0, 0.46, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cjHow many times the code  was used:",d:x_zh_zm09_100+x_zh_zm09_50+x_zh_zm09_25+x_zh_zm09_0,s:" (",d:divide(x_zh_zm09_100+x_zh_zm09_50+x_zh_zm09_25+x_zh_zm09_0*100,x_zh_zm09_cn),s:"%)"; HUDMSG_FADEOUT, 515, CR_RED, 0, 0.48, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:"\cj How many times the zombies got overpowered itens:",d:x_zh_zm09_zp,s:" (chance to happen on this map:",d:divide(x_zh_zm09_zp*100,x_zh_zm09_cn),s:"%)"; HUDMSG_FADEOUT, 516, CR_RED, 0, 0.5, 5.5, 0);

        delay(1);
    }
        SetFont("BIGFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 500, CR_GREEN, 0, 0.2, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 501, CR_RED, 0.3, 0.22, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 502, CR_RED, 0.3, 0.22, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 503, CR_RED, 0.3, 0.24, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 504, CR_RED, 0.3, 0.26, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 505, CR_RED, 0.3, 0.28, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 506, CR_RED, 0.3, 0.30, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 507, CR_RED, 0.3, 0.32, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 508, CR_RED, 0.3, 0.34, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 509, CR_RED, 0.3, 0.36, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 510, CR_RED, 0.3, 0.38, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 511, CR_RED, 0.3, 0.40, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 512, CR_RED, 0.3, 0.42, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 513, CR_RED, 0.3, 0.44, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 514, CR_RED, 0.3, 0.44, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 515, CR_RED, 0.3, 0.44, 5.5, 0);
        SetFont("SMALLFONT");
        HudMessageBold(s:""; HUDMSG_FADEOUT, 516, CR_RED, 0.3, 0.44, 5.5, 0);

}

script 69 (int code) NET{
	if(code==1414325){
		int back_wf_script=-1;
		int back_rav_script=-1; //there's no -1 situation
		int script_cnt=0;
		int tic_cnt=0;
		while(true){
			SETFONT("SMALLFONT");
			HudMessage(s:"TICS:",d:tic_cnt; HUDMSG_PLAIN, 544, CR_RED, 0, 0.2, 9.8, 0);
			tic_cnt+=3;
		/*
		Ravishing script:offline/online/disconnected
		Ravishing situation:visible/invisible/Stucked
		Ravishing target:!ghoul_hate
		Ravishing last script called:!ravishing_script
		*/			
		    SETFONT("SMALLFONT");
			HudMessage(s:"Ravishing script:"; HUDMSG_PLAIN, 545, CR_RED, 0, 0.22, 9.8, 0);
			if(ravishing_script==0){
				HudMessage(s:"offline"; HUDMSG_PLAIN, 546, CR_WHITE, 0.15, 0.22, 9.8, 0);
			}else if(ravishing_script==back_rav_script){
				script_cnt++;
				if(script_cnt>=50){
					HudMessage(s:"Disconnected"; HUDMSG_PLAIN, 546, CR_YELLOW, 0.2, 0.22, 9.8, 0);
				}else{
					HudMessage(s:"online"; HUDMSG_PLAIN, 546, CR_GREEN, 0.15, 0.22, 9.8, 0);
				}
			}else{
				HudMessage(s:"online"; HUDMSG_PLAIN, 546, CR_GREEN, 0.15, 0.22, 9.8, 0);
				script_cnt=0;
			}


			HudMessage(s:"Ravishing situation:"; HUDMSG_PLAIN, 547, CR_RED, 0, 0.24, 9.8, 0);
			if(user_invisible==true){
				HudMessage(s:"Invisible"; HUDMSG_PLAIN, 548, CR_WHITE, 0.15, 0.24, 9.8, 0);
			}else if(stuck_test>=20){
				HudMessage(s:"Stucked"; HUDMSG_PLAIN, 548, CR_YELLOW, 0.15, 0.24, 9.8, 0);
			}else{
				HudMessage(s:"Visible"; HUDMSG_PLAIN, 549, CR_RED, 0.15, 0.24, 9.8, 0);
			}

			HudMessage(s:"Ravishing target:"; HUDMSG_PLAIN, 550, CR_RED, 0, 0.26, 9.8, 0);
				HudMessage(n:ghoul_target-601, s:" ...number:",d:ghoul_target; HUDMSG_PLAIN, 551, CR_WHITE, 0.2, 0.26, 9.8, 0);
			HudMessage(s:"Ravishing last script:"; HUDMSG_PLAIN, 552, CR_RED, 0, 0.28, 9.8, 0);
				HudMessage(d:ravishing_script; HUDMSG_PLAIN, 553, CR_WHITE, 0.15, 0.28, 9.8, 0);
		/*
		White Face script:offline/online/disconnected/starting (debug_wf_scrpt_stck:0-2:3:4:5-else-1)
		White Face situation:visible/invisible (debug_wf_vsble)
		White Face speed:slow/fast (debug_wf_speed)
		White Face target:!ghoul_hate
		*/
		    SETFONT("SMALLFONT");
			HudMessage(s:"White Face script:"; HUDMSG_PLAIN, 554, CR_WHITE, 0, 0.3, 9.8, 0);
			if(debug_wf_scrpt_stck==0){
				HudMessage(s:"OFFLINE"; HUDMSG_PLAIN, 555, CR_WHITE, 0.15, 0.3, 9.8, 0);	
			}else if(debug_wf_scrpt_stck==1)
				HudMessage(s:"STARTING"; HUDMSG_PLAIN, 555, CR_BLUE, 0.15, 0.3, 9.8, 0);
			else if(debug_wf_scrpt_stck==back_wf_script){
				if(script_cnt>=50){
					HudMessage(s:"DISCONNECTED"; HUDMSG_PLAIN, 555, CR_YELLOW, 0.15, 0.3, 9.8, 0);	
				}else{
					script_cnt++;
					HudMessage(s:"ONLINE"; HUDMSG_PLAIN, 555, CR_GREEN, 0.15, 0.3, 9.8, 0);	
				}
			}else{
				HudMessage(s:"ONLINE"; HUDMSG_PLAIN, 555, CR_GREEN, 0.15, 0.3, 9.8, 0);
				script_cnt=0;
			}			
			
			HudMessage(s:"White Face situation:"; HUDMSG_PLAIN, 556, CR_WHITE, 0, 0.32, 9.8, 0);
			switch(debug_wf_vsble){
				case true:
				HudMessage(s:"VISIBLE"; HUDMSG_PLAIN, 557, CR_WHITE, 0.15, 0.32, 9.8, 0);	
				break;
				case false:
				HudMessage(s:"INVISIBLE"; HUDMSG_PLAIN, 557, CR_RED, 0.15, 0.32, 9.8, 0);
				break;
			}
			
			HudMessage(s:"White Face speed:"; HUDMSG_PLAIN, 558, CR_WHITE, 0, 0.34, 9.8, 0);
			if(debug_wf_speed==false){
				HudMessage(s:"SLOW"; HUDMSG_PLAIN, 559, CR_GREEN, 0.15, 0.34, 9.8, 0);
			}else{
				HudMessage(s:"FAST"; HUDMSG_PLAIN, 560, CR_RED, 0.15, 0.34, 9.8, 0);
			}
		
			HudMessage(s:"White Face target:"; HUDMSG_PLAIN, 561, CR_WHITE, 0, 0.36, 9.8, 0);
				HudMessage(n:ghoul_target-601, s:" ...number:",d:ghoul_target; HUDMSG_PLAIN, 562, CR_WHITE, 0.2, 0.36, 9.8, 0);
			delay(3);
		}
	}else{
		log(s:"\ck<white face> ", n:ActivatorTID(), s:"\cd stop cheating... thanks from ibm :) ");
	}
}

function void zm09_update_settings(void){
int i=0;
int j=0;
int input=GetCvar("x_zh_zm09");
    if(input!=0){//input=22260
        i=input/10;//2226
        i=i*10;//22260
        i=input-i;//0
        switch(i){
            case 2: nedm_desactive=false; reflection_actived=false; break;
            case 3: nedm_desactive=true;  reflection_actived=false;break;
            case 4: nedm_desactive=false; reflection_actived=true; break;
            default: nedm_desactive=true;  reflection_actived=true; break;
        }
        //22260
        i=input/100;//222
        i=i*10;//2220
        j=input/10;//2226
        i=j-i;//2226-2220=6
        if(i<1 || i>6) weather_quality=0;
        else weather_quality=i-2;
        //22260
        i=input/1000;//22
        i=i*10;//220
        j=input/100;//222
        i=j-i;//222-220=2
        if(i<2 || i>3) rain_sound=0;
        else rain_sound=i-2;
        //22260
        i=input/10000;//2
        i=i*10;//20
        j=input/1000;//22
        i=j-i;//22-20=2
        if(i<1 || i>6) rain_detail=0;
        else rain_detail=i-2;
        i=input/10000;//2
        if(i==1)music_quality=false;
        else music_quality=true;
		
		//Adapt the old menu values to the new menu
		//Funcion adapts the old save data to the new menu system
		men_selected[0]=weather_quality+1;
		if(rain_sound==1)
			men_selected[1]=false;
		else
			men_selected[1]=true;
		men_selected[2]=rain_detail+1;
		if(nedm_desactive==1)
			men_selected[3]=0;
		else
			men_selected[3]=1;
		if(reflection_actived==1)
			men_selected[4]=0;
		else
			men_selected[4]=1;
    }
    if(reflection_actived==true){
        Sector_SetPlaneReflection (153, 44, 0);
        Sector_SetPlaneReflection (149, 66, 0);
        Sector_SetPlaneReflection (3, 44, 0);
    }
	
	
    play_zm09_music();
}  