//ZM09 Tutorial
/*#library "zm09_tut"
#include "zcommon.acs"
#import "nedm.acs"
#import "rainfall.acs"
#import "distance.acs"
#import "zm09_col.acs"
#import "zm09_cod.acs"
#import "zm09_set.acs"
#import "zm09_fun.acs"
#import "FUNCTION.acs"
*/
script 55 (void){//TUTORIAL NEDM
    int i=0;
    //161 NEDM SWITCH 1
    //162 NEDM SWITCH 2
    //163 NEDM SWITCH 3
    //164 NEDM SWITCH 4
    //165 NEDM SWITCH 5
    //166 NEDM SWITCH 6
    //167 NEDM SWITCH 7
    //168 NEDM SWITCH 8
    //169 NEDM CAT SMILE
    do{
        nedm_code=0;//123456
        thing_remove(169); 
        if(nedm_digit6==6 && nedm_digit5==5 && nedm_digit4==4 && nedm_digit3==3 && nedm_digit2==2 && nedm_digit1==1) i=7;
        else if(nedm_digit6==6)i=6;
        else if(nedm_digit5==5)i=5; 
        else if(nedm_digit4==4)i=4; 
        else if(nedm_digit3==3)i=3;  
        else if(nedm_digit2==2)i=2;
        else if(nedm_digit1==1)i=1;
        else i=0;
        spawnspot("NedmMarker",161+i,169,0);
        HudMessageBold(s:"go press the nedm switch number: ",d:i+1;HUDMSG_FADEOUT,444,CR_GREEN,0,0.5,1);
        HudMessageBold(s:"your distance from the next switch is:",d:ibm_distance(600,169);HUDMSG_FADEOUT,445,CR_GREEN,0,0.48,1);
        delay(1);
    }while(!nedm_digit_lock);
    thing_remove(169);
    spawnspot("NedmMarker",167,169,0);
    do{
        HudMessageBold(s:"go press the next nedm switch by :",d:55-mcdonald,s:" times";HUDMSG_FADEOUT,444,CR_GREEN,0,0.5,1);
        HudMessageBold(s:"your distance from switch is:",d:ibm_distance(600,167);HUDMSG_FADEOUT,445,CR_GREEN,0,0.48,1);
        delay(1);
    }while(mcdonald!=55);
    thing_remove(169);
    spawnspot("NedmMarker",168,169,0);
    do{
        HudMessageBold(s:"go press the next nedm switch by :",d:105-mcdonald,s:" times";HUDMSG_FADEOUT,444,CR_GREEN,0,0.5,1);
        HudMessageBold(s:"your distance from switch is:",d:ibm_distance(600,168);HUDMSG_FADEOUT,445,CR_GREEN,0,0.48,1);
        delay(1);
    }while(mcdonald!=105);
}

script 56 (void){//TUTORIAL RED KEY CARD
    print(s:"loading spots, please wait");
    for(int i=1;i<800;i++){
        switch(random(0,10)){
            case 0:spawn("RedKeyMarker",random(-721.0,-409.0),random(1873.0,2711.0),632.0,350,0); break;
            case 1:spawn("RedKeyMarker",random(4528.0,5135.0),random(-1664.0,-1361.0),400.0,350,0);break;
            case 2:spawn("RedKeyMarker",random(5623.0,5807.0),random(-783.0,-497.0),472.0,350,0);break;
            case 3:spawn("RedKeyMarker",random(2080.0,4079.0),random(2448.0,3823.0),463.0,350,0);break;
            case 4:spawn("RedKeyMarker",random(-3088.0,-2553.0),random(-1776.0,-1281.0),112.0,350,0);break;
            case 5:spawn("RedKeyMarker",random(1114.0,1775.0),random(392.0,825.0),318.0,350,0);break;
            case 6:spawn("RedKeyMarker",random(-1856.0,-1169.0),random(2125.0,2351.0),327.0,350,0);break;
            case 7:spawn("RedKeyMarker",random(4416.0,4471.0),random(-2004.0,-1961.0),400.0,350,0);break;
            case 8:spawn("RedKeyMarker",random(-2512.0,879.0),random(-1716.0,-449.0),362.0,350,0);break;
            case 9:spawn("RedKeyMarker",random(4550.0,4719.0),random(-1246.0,-1169.0),465.0,350,0);break;
            case 10:spawn("RedKeyMarker",random(-1808.0,-1585.0),random(-2320.0,-2052.0),72.0,350,0);break;
        }            print(s:"loading spots, please wait\n ",d:(i*100)/800,s:"% loaded");

        delay(1);
    }print(s:"loaded");
    do{
        HudMessageBold(s:"check your map to find where are the red key card spots...";HUDMSG_FADEOUT,444,CR_GREEN,0,0.5,1);
        HudMessageBold(s:"your distance from redkey is:",d:ibm_distance(600,36);HUDMSG_FADEOUT,445,CR_GREEN,0,0.48,1);
        delay(1);
    }while(true);
}

script 57 (void){//TUTORIAL WINERY KEY
    print(s:"check the map to see where the winery key can be :D");
    spawnspot("WinKeyMarker",71,0,0);
     spawnspot("WinKeyMarker",72,0,0);
      spawnspot("WinKeyMarker",73,0,0);
       spawnspot("WinKeyMarker",74,0,0);
       spawnspot("WinKeyMarker",70,0,0);
}

script 58 (void){//TUTORIAL: DISABLE NEDM
    HudMessageBold(s:"                     How to disable NEDM\n\cgWARNING:\cdthis function will not disable buildings dance";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,10.0);
    delay(35*10);
    do{
        do{
            HudMessageBold(s:"INSTRUCTIONS:\n1)OPEN THE ZH2 MENU\n2)IN LEGACY MAP OPTIONS \cfOPEN THE MAIN MENU\n\cd3)PRESS ENTER\n4)SELECT NEDM ENABLED AND SET IT TO OFFn\n5)PRESS USE BUTTON TO GO OUT OF MENU AND NOW YOU WILL NEVER MORE SEE NEDM ON THIS MAP :)";HUDMSG_FADEOUT,444,CR_GREEN,0,0.8,1);
            delay(1);
       }while(GetPlayerInput(0, INPUT_BUTTONS)!=BT_USE);
       if(nedm_desactive==false){
            HudMessageBold(s:"NEDM was not disable, you may acidentaly pressed the use button before disable it, lets try again...";HUDMSG_FADEOUT,444,CR_GREEN,0,0.8,10.0);
            delay(10*35);

       }
    }while(nedm_desactive==false);    
    HudMessageBold(s:"Congratulations!!!, now you'll not see NEDM, if you missed some part of this tutorial, select again this tutorial...";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,10.0);

}



script 59 (void){//TUTORIAL HOW TO UP FRAMERATES DISABLING REFLECTION...
    HudMessageBold(s:"                     How to inscrease your frames";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,10.0);
    delay(35*10);
    do{
        do{
            HudMessageBold(s:"INSTRUCTIONS:\n1)OPEN THE ZH2 MENU\n2)IN LEGACY MAP OPTIONS \cfOPEN THE MAIN MENU\n\cd3)PRESS ENTER\n4)SELECT REFLECTION ENABLED AND SET TO OFF\n5)PRESS USE BUTTON TO GO OUT OF MENU";HUDMSG_FADEOUT,444,CR_GREEN,0,0.8,1);
            delay(1);
       }while(GetPlayerInput(0, INPUT_BUTTONS)!=BT_USE);
       if(reflection_actived==true){
            HudMessageBold(s:"Reflection was not disable, you may acidentaly pressed the use button before disable it, lets try again...";HUDMSG_FADEOUT,444,CR_GREEN,0,0.8,10.0);
            delay(10*35);

       }
    }while(nedm_desactive==false);    
    HudMessageBold(s:"Congratulations!!!, you will have your frames higher...";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,10.0);
}

script 60 (void){//TUTORIAL HOW TO UP FRAMERATES LOWERING RAIN...
    HudMessageBold(s:"                     How to increase your frames when it's raining\n\cgWARNING:\cdif this tutorial still not help to up frames, try to lower the resolution and disabling fog!!!";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,15.0);
    int i=280;
    int j=280;
    delay(35*15);
    print(s:"if you want to rain move, crouch, press open button or fire. If not wait for 7 seconds for the tutorial start...");
    delay(50);
    do{
        if(GetPlayerInput(0, INPUT_BUTTONS)!=0){
            rainfall_actived=true;
            SETFONT("SMALLFONT");
            Light_ChangeToValue(23,90);
            Sector_Setcolor(23,128,128,128);
            Light_ChangeToValue(142,90);
            Sector_Setcolor(142,128,128,128);
            Light_ChangeToValue(143,64);
            Sector_Setcolor(143,128,128,128);
            ReplaceTextures("IBMTE2","SKYFOG0",NOT_MIDDLE);
            Light_ForceLightning(0);
            acs_execute(47,0,0,0,0);
        }if(i-35<=j)j-=35;
        print(s:"if you want to rain move, crouch, press open button or fire. If not wait for ", d:j/35,s:" seconds for the tutorial start...");
        i--;
        delay(1);
        
    }while(GetPlayerInput(0, INPUT_BUTTONS)==0 && i>35);
    do{
        do{
            HudMessageBold(s:"INSTRUCTIONS:\n1)OPEN THE ZH2 MENU\n2)IN LEGACY MAP OPTIONS \cfOPEN THE MAIN MENU\n\cd3)PRESS ENTER\n4)SELECT RAIN DISTANCE AND SET TO ULTRA LOW MOVING THE PLAYER TO LEFT\n5)SELECT RAIN QUALITY AND SET IT TO LOW\n6)PRESS USE BUTTON TO GO OUT OF MENU";HUDMSG_FADEOUT,444,CR_GREEN,0,0.8,1);
            delay(1);
       }while(GetPlayerInput(0, INPUT_BUTTONS)!=BT_USE);
       if(weather_quality>=0){
            HudMessageBold(s:"Rain Distance was not set in the lowest distance or you may acidentaly pressed the use button before disable it, lets try again...";HUDMSG_FADEOUT,444,CR_GREEN,0,0.8,10.0);
            delay(6*35);
       }else if(rain_detail>0){
            HudMessageBold(s:"Rain Quality was not set in the low or you may acidentaly pressed the use button before disable it, lets try again...";HUDMSG_FADEOUT,444,CR_GREEN,0,0.8,10.0);
            delay(6*35);
       }
    }while(weather_quality>=false || rain_detail>0);    
    HudMessageBold(s:"Congratulations!!!, you will have your frames higher when raining...";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,10.0);
}

script 61 (void){//TUTORIAL HOW TO MAKE THE RIGHT CODE
    teleport(169,0,false);
    HudMessageBold(s:"                     TUTORIAL:How to make the right code";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,20.0);
    delay(120);
    HudMessageBold(s:"part 1 of 5\nThis screen sometimes show the right code, but, sometimes it'll hide the right code...\nto discover if you're seeing the right code, there must not be no repeated, and sometimes when there's no repeated number, it may not be that code too";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,20.0);
    delay(550);
    HudMessageBold(s:"part 2 of 5\nthe logic is simple, there must not have a repeated number on the screen, and here's the tutorial for when you find two numbers repeated like 1123\n if you see 1123, one of the ones are not the real one but yes four, so it could be 4123 or 1423,example 2:4122 could be 3421 or 3412";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,20.0);
    delay(600);
    HudMessageBold(s:"part 3 of 5\nwhen you have two repeated numbers it's as hard to find the code as if you didn'y have the help code on, because instead of two codes, it could be four!!! example:1133 could be:1423,1432,4123,4132";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,20.0);
    delay(550);
    HudMessageBold(s:"part 4 of 5\nfinally, when you see a code without repeated numbers, it's 50% the change to be that code, or, that all that code is wrong, ex:1234 could be 1234 or 4123";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,20.0);
    delay(550);
    HudMessageBold(s:"part 5 of 5\nsometimes the right code screen doesn't appears, this happen more time when there's more players...\nending this tutorial the code that you see on that sceen could be right or it's he-1 ex: 4 = 4 or 3, 3 = 3 or 2, 2 = 2 or 1, 1 = 1 or 4...\nEND";HUDMSG_FADEOUT,444,CR_GREEN,0.5,0.5,20.0);
}

script "internal_tutorial_menu" (void) {//TUTORIAL
    int menu=0;
    int i=0;    
    while(true){
        i=0;
        menu_zm09=menu;
        while(i<5){i++;}
            SETFONT("SMALLFONT");
            HudMessagebold(s:"ZM09 TUTORIAL"; HUDMSG_PLAIN, 544, CR_UNTRANSLATED, 0.5, 0.44,0,0, 0);
            SETFONT("SMALLFONT");
            HudMessagebold(s:"To exit the TUTORIAL press \cf-use- \n\nControlls \cfleft & right \ccto set the value of the setting\n\cfup & down \ccto select another setting\n\clWARNING\cc: you will not be able to close the menu or control the menu if you are pressing others keys (like crouch, jump,fire,...)"; HUDMSG_PLAIN, 553, CR_GRAY, 0.5, 0.60+hud_resize(),0,0, 0);
            zm09_menu_print();
            if(menu==0){
                menu_zm09=1;
                menu=1;
                zm09_menu_print();
                AmbientSound("menu/activate",127);
            }
        else if(menu==-1){//
                SETFONT("SMALLFONT");
                HudMessagebold(s:""; HUDMSG_PLAIN, 544, CR_UNTRANSLATED, 0.5, 0.5,15.1,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 545, CR_UNTRANSLATED, 0.5, 0.48,15.1,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 546, CR_UNTRANSLATED, 0.5, 0.46,15.1,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 547, CR_UNTRANSLATED, 0.44, 0.5,15.1,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 548, CR_UNTRANSLATED, 0.52, 0.44,0,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 549, CR_UNTRANSLATED, 0.52, 0.44,0,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 550, CR_UNTRANSLATED, 0.52, 0.44,0,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 551, CR_UNTRANSLATED, 0.52, 0.44,0,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 552, CR_UNTRANSLATED, 0.52, 0.44,0,0, 0);
                HudMessagebold(s:""; HUDMSG_PLAIN, 553, CR_UNTRANSLATED, 0.52, 0.44,0,0, 0);
                //activatorsound("menu/choose",127);DSSWTCHX
                AmbientSound("switches/exitbutn",127);
                menu=0;
                terminate;
        }
        if(menu==1){//TUTORIAL NEDM
            while(menu==1){
                zm09_menu_print_tutorial();
                if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_BACK){
                    menu=2;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_USE){
                    menu=-1;
                    acs_execute(55,0);
                }
                delay(1);
            }
            delay(5);
        }
        else if(menu==2){//TUTORIAL RED KEY
            while(menu==2){
                zm09_menu_print_tutorial();
                if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_BACK){
                    menu=3;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_FORWARD){
                    menu=1;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_USE){
                    menu=-1;
                    acs_execute(56,0);
                }delay(1);
            }delay(5);
        }else if(menu==3){//WINERY KEY
            while(menu==3){
                zm09_menu_print_tutorial();
                if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_FORWARD){
                    menu=2;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_BACK){
                    menu=4;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_USE){
                    menu=-1;
                    acs_execute(57,0);
                }delay(1);
            }
            delay(5);///////////////////////////////
        }else if(menu==4){//DISABLE NEDM
            while(menu==4){
                zm09_menu_print_tutorial();
                if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_FORWARD){
                    menu=3;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_USE){
                    menu=-1;
                    acs_execute(58,0);
                    delay(1);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_BACK){
                    AmbientSound("menu/cursor",127);
                    menu=5;
                }delay(1);
            }
            delay(5);
        }else if(menu==5){//UP FPS 1
            while(menu==5){
                zm09_menu_print_tutorial();
                if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_FORWARD){
                    menu=4;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_USE){
                    menu=-1;
                    acs_execute(59,0);
                    delay(1);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_BACK){
                    menu=6;
                    activatorsound("menu/cursor",127);
                }
            delay(5);
            }
        }else if(menu==6){//UP FPS 2
            while(menu==6){
                zm09_menu_print_tutorial();
                if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_FORWARD){
                    menu=5;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_USE){
                    menu=-1;
                    acs_execute(60,0);
                    delay(1);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_BACK){
                    menu=7;
                    activatorsound("menu/cursor",127);
                }
            delay(5);
            }        
        }else if(menu==7){//MAKE THE RIGHT CODE
            while(menu==7){
                zm09_menu_print_tutorial();
                if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_FORWARD){
                    menu=6;
                    AmbientSound("menu/cursor",127);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_USE){
                    menu=-1;
                    acs_execute(61,0);
                    delay(1);
                }else if(GetPlayerInput(-1, INPUT_BUTTONS)==BT_BACK){
                    menu=7;
                    //activatorsound("menu/cursor",127);
                }
            delay(5);
            }        
        }
    delay(1);
    }
}


function void zm09_menu_print_tutorial(void){
	SETFONT("SMALLFONT");
 HudMessagebold(s:zm09_menu_print_color(1),s:"TUTORIAL: HOW TO ACTIVATE NEDM:"; HUDMSG_PLAIN, 545, CR_UNTRANSLATED, 0.5, 0.46+hud_resize(),0,0, 0);
	SETFONT("SMALLFONT");
 HudMessagebold(s:zm09_menu_print_color(2),s:"TUTORIAL: HOW TO FIND THE RED KEY CARD"; HUDMSG_PLAIN, 546, CR_UNTRANSLATED, 0.5, 0.48+hud_resize()*2,0,0, 0);
	SETFONT("SMALLFONT");
 HudMessagebold(s:zm09_menu_print_color(3),s:"TUTORIAL: HOW TO FIND THE WINERY KEY"; HUDMSG_PLAIN, 547, CR_UNTRANSLATED, 0.5, 0.5+hud_resize()*3,0,0, 0);
	SETFONT("SMALLFONT");
 HudMessagebold(s:zm09_menu_print_color(4),s:"TUTORIAL: HOW TO DISABLE NEDM"; HUDMSG_PLAIN, 548, CR_UNTRANSLATED, 0.5, 0.52+hud_resize()*4,0,0, 0);
	SETFONT("SMALLFONT");
 HudMessagebold(s:zm09_menu_print_color(5),s:"TUTORIAL: HOW TO INCREASE THE FPS 1"; HUDMSG_PLAIN, 549, CR_UNTRANSLATED, 0.5, 0.54+hud_resize()*5,0,0, 0);
	SETFONT("SMALLFONT");
 HudMessagebold(s:zm09_menu_print_color(6),s:"TUTORIAL: HOW TO INCREASE THE FPS 1"; HUDMSG_PLAIN, 550, CR_UNTRANSLATED, 0.5, 0.56+hud_resize()*5,0,0, 0);
 	SETFONT("SMALLFONT");
 HudMessagebold(s:zm09_menu_print_color(7),s:"TUTORIAL: HOW TO MAKE THE RIGHT CODE"; HUDMSG_PLAIN, 551, CR_UNTRANSLATED, 0.5, 0.58+hud_resize()*5,0,0, 0);
}


function void print_secret_select_help(int secret_help1, int secret_help2,int secret_help3,int secret_help4){
    SetLineTexture(134,SIDE_FRONT,TEXTURE_MIDDLE,ibmnu_text[secret_help1-1]);
    SetLineTexture(135,SIDE_FRONT,TEXTURE_MIDDLE,ibmnu_text[secret_help2-1]);
    SetLineTexture(136,SIDE_FRONT,TEXTURE_MIDDLE,ibmnu_text[secret_help3-1]);
    SetLineTexture(137,SIDE_FRONT,TEXTURE_MIDDLE,ibmnu_text[secret_help4-1]);
}


function void secret_select_help(void)
{
    int i=random(0,100);
    int x=random(0,100);
    int secret_help1=secret[0];
    int secret_help2=secret[1];
    int secret_help3=secret[2];
    int secret_help4=secret[3];
    if(i>50) secret_help1+=1;
    i=random(0,100);
    if(i<50) secret_help2+=1;
    i=random(0,100);
    if(i>50) secret_help3+=1;
    i=random(0,100);
    if(i<50) secret_help4+=1;
    if(secret_help1==secret[0] && secret_help2==secret[1] && secret_help3==secret[2]  && secret_help3==secret[3]){
        if(random(0,100)>50){
            secret_help1+=1;
            secret_help2+=1;
            secret_help3+=1;
            secret_help4+=1;}
    }
    if(Game::ZombieCount()+Game::HumanCount()<5){
        x=random(0,100);
        if(x>10)   print_secret_select_help(secret_help1,secret_help2,secret_help3,secret_help4);
    }else if(Game::ZombieCount()+Game::HumanCount()<10){
        x=random(0,100);
        if(x>25) print_secret_select_help(secret_help1,secret_help2,secret_help3,secret_help4);
    }else if(Game::ZombieCount()+Game::HumanCount()<15){
        x=random(0,100);
        if(x>30)  print_secret_select_help(secret_help1,secret_help2,secret_help3,secret_help4);
    }else if(Game::ZombieCount()+Game::HumanCount()<20){
        x=random(0,100);
        if(x>45)  print_secret_select_help(secret_help1,secret_help2,secret_help3,secret_help4);
    }else if(Game::ZombieCount()+Game::HumanCount()<25){
        x=random(0,100);
        if(x>50) print_secret_select_help(secret_help1,secret_help2,secret_help3,secret_help4);
    }else if(Game::ZombieCount()+Game::HumanCount()<30){
        x=random(0,100);
        if(x>60)  print_secret_select_help(secret_help1,secret_help2,secret_help3,secret_help4);
    }
}