int Developer_tid = -1;

script 36 (void)  NET clientside{//Developer unlock
    print(s:" You now have unlocked the ZM09 LOG");
    delay(35);
    Developer_tid = 1;
}

script 37 open clientside{//Developer loop script
    int i=700;
    while(Developer_tid == -1) delay(70);
    //TID 700 to higher
    sethudsize(640,480,true);
    hudmessagebold(s:"ZM09 CLIENTSIDE LOG";HUDMSG_PLAIN,0,CR_WHITE,320.0,20.0,0.0);
    hudmessagebold(s:"GENERATOR STATUS\n-GENERATOR1:\n-GENERATOR2:";HUDMSG_PLAIN,0,CR_YELLOW,10.0,20.0,0.0);
    hudmessagebold(s:"     CODE STATUS\n-CODE ENTERED:\n-RIGHT CODE:";HUDMSG_PLAIN,0,CR_YELLOW,10.0,50.0,0.0);
    hudmessagebold(s:"MONSTERS:\n-Monster Spawned:\n-Tracking TID:\n-Tracking Name:\nHumans Left:\nMy Console Tid:";HUDMSG_PLAIN,0,CR_YELLOW,10.0,90.0,0.0);
    hudmessagebold(s:"Are you running software render:";HUDMSG_PLAIN,0,CR_YELLOW,60.0,120.0,0.0);
    hudmessagebold(s:"Your Aspect Ratio:";HUDMSG_PLAIN,0,CR_YELLOW,10.0,130.0,0.0);
    hudmessagebold(s:"Rainfal\n-Is raining:\n-Rain Distance:\nRain Sound:\nRain Detail";HUDMSG_PLAIN,0,CR_YELLOW,20.0,160.0,0.0);
    hudmessagebold(s:"Reflection Enabled:";HUDMSG_PLAIN,0,CR_YELLOW,10.0,190.0,0.0);
    hudmessagebold(s:"NEDM Enabled:";HUDMSG_PLAIN,0,CR_YELLOW,10.0,200.0,0.0);
    hudmessagebold(s:"HQ SND Enabled:";HUDMSG_PLAIN,0,CR_YELLOW,10.0,210.0,0.0);

    while(true){
        sethudsize(640,480,true);
        i = 700;
        switch(generator1)
        {
            case true:
                hudmessagebold(s:"ONLINE";HUDMSG_PLAIN,i,CR_GREEN,80.0,20.0,0.0);
                break;

            case false:
                hudmessagebold(s:"OFFLINE";HUDMSG_PLAIN,i,CR_RED,80.0,20.0,0.0);
                break;
        }
        i++;
        switch(generator2)
        {
            case true:
                hudmessagebold(s:"ONLINE";HUDMSG_PLAIN,i,CR_GREEN,80.0,30.0,0.0);
                break;
            case false:
                hudmessagebold(s:"OFFLINE";HUDMSG_PLAIN,i,CR_RED,80.0,30.0,0.0);
                break;
        }
        i++;
        hudmessagebold(d:secret[4],d:secret[5],d:secret[6],d:secret[7];HUDMSG_PLAIN,i,CR_RED,80.0,50.0,0.0);
        i++;
        hudmessagebold(d:secret[0],d:secret[1],d:secret[2],d:secret[3];HUDMSG_PLAIN,i,CR_RED,65.0,60.0,0.0);
        i++;
        if(thingcount(t_none,100)==0){
        hudmessagebold(s:"NONE";HUDMSG_PLAIN,i,CR_YELLOW,100.0,78.0,0.0);
        }else if(thingcountname("ravishingBETA",100)==1){
            hudmessagebold(s:"RAVISHING";HUDMSG_PLAIN,i,CR_RED,120.0,78.0,0.0);
        }else{
            hudmessagebold(s:"WHITE FACE";HUDMSG_PLAIN,i,CR_WHITE,120.0,78.0,0.0);
        }
        i++;
        hudmessagebold(d:ghoul_target;HUDMSG_PLAIN,i,CR_WHITE,60.0,86.0,0.0);
        i++;
        hudmessagebold(n:ghoul_target-599;HUDMSG_PLAIN,i,CR_WHITE,160.0,90.0,0.0);
        i++;
        hudmessagebold(d:Game::HumanCount();HUDMSG_PLAIN,i,CR_WHITE,60.0,104.0,0.0);
        i++;
        hudmessagebold(d:ConsolePlayerNumber();HUDMSG_PLAIN,i,CR_WHITE,60.0,112.0,0.0);
        i++;
        //
        i++;
        switch(rainfall_actived){
            case true:
            hudmessagebold(s:"YES";HUDMSG_PLAIN,i,CR_GREEN,55.0,152.0,0.0);
            break;
            case false:
            hudmessagebold(s:"NO";HUDMSG_PLAIN,i,CR_RED,55.0,152.0,0.0);
            break;
        }
        i++;
        hudmessagebold(d:weather_quality;HUDMSG_PLAIN,i,CR_white,75.0,160.0,0.0);
        i++;
        hudmessagebold(d:(int)rain_sound;HUDMSG_PLAIN,i,CR_white,50.0,169.0,0.0);
        i++;
        hudmessagebold(d:rain_detail;HUDMSG_PLAIN,i,CR_white,50.0,177.0,0.0);
        i++;
        hudmessagebold(d:(int)nedm_desactive;HUDMSG_PLAIN,i,CR_white,84.0,190.0,0.0);
        i++;
        hudmessagebold(d:(int)reflection_actived;HUDMSG_PLAIN,i,CR_white,68.0,200.0,0.0);
        i++;
        hudmessagebold(d:(int)music_quality;HUDMSG_PLAIN,i,CR_white,68.0,210.0,0.0);
        delay(1);
    }

}