#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    #define EVENT_RECEIVE_MAX_SIZE 40

    struct EventReceiveContextT
    {
        raw ReceiveData[EVENT_RECEIVE_MAX_SIZE];
    };

    extern void SendDataSynced(int type);
    extern void ReceiveDataSynced(str packet);

    extern void SetReceiveData(int index, raw data);
    extern raw GetReceiveData(int index);
}