#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    void SendDataSynced(int type)
    {
        str packet = Packet::New();
        packet = Packet::AppendStr(packet, EVENTDATASYNCED);
        packet = Packet::Append(packet, type);
        EventBus::CallEvent(packet);
    }

    internal void SendRandomizedWeatherTrigger(int index)
    {
        str packet = Packet::New();
        packet = Packet::AppendStr(packet, EVENTRANDOMIZEDWEATHERTRIGGERED);
        packet = Packet::Append(packet, index);
        EventBus::CallEvent(packet);
    }
}