#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#nocompact
#pragma raw include on
#pragma raw define on

#linklibrary "zh2game"

#define VersionMajor 3
#define VersionMinor 0
#define VersionPatch 0
#define VersionSuffix "-beta"

// If `DevelopmentPlayerCap()` is `true`, this cap is enforced and players joining beyond the cap are kicked out.
#define DEV_PLAYERCAP_COUNT 8

#include "zh2game/main.h.acs"