#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace IO
{
    internal bool ParseSafety(int handle, str mapLump, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "safety")) return false;

        Logger::LogDebug(LOGSOURCE, "Start parse map safety blocks for \cd" + mapLump + ".");

        int braceLevel = Tokenizer::GetBraceLevel(handle);

        if (!Tokenizer::ExpectNextChar(handle, '['))
            return false;

        Tokenizer::Next(handle);

        // While the bracket level does not match the end level, we keep parsing.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) != braceLevel)
        {
            str symbol = Tokenizer::GetSymbol(handle);

            if (!ParseSafetySlotBlock(handle, mapLump, symbol))
                return false;

            // Optional comma.
            Tokenizer::Next(handle, false);
            if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
                Tokenizer::Next(handle, false);
        }

        Logger::LogDebug(LOGSOURCE, "Parsed map safety blocks \cd" + mapLump + ".");
        return true;
    }

    internal bool ParseSafetySlotBlock(int handle, str mapLump, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "slot"))
        {
            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing safety slot for " + mapLump + ": '" + identifyingSymbol + "'. Expected Slot.");
            return false;
        }

        Tokenizer::Next(handle);

        if (!Tokenizer::TryParseIntValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for the safety slot is not a correct value. Expected a valid numeric value within bounds.");
            return false;
        }

        int slot = (int)Tokenizer::GetParsedValue();

        if (slot < 0 || slot >= MAX_SAFETY_SLOTS)
        {
            Tokenizer::SetErrored(handle, "The given safety slot " + str(slot) + " is not valid.");
            return false;
        }

        Logger::LogDebug(LOGSOURCE, "Start parse safety slot \cd" + str(slot) + "\cj block for \cd" + mapLump + ".");

        int braceLevel = Tokenizer::GetBraceLevel(handle);

        if (!Tokenizer::ExpectNextChar(handle, '{'))
            return false;

        Tokenizer::Next(handle);

        // While the bracket level does not match the end level, we keep parsing.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) != braceLevel)
        {
            str symbol = Tokenizer::GetSymbol(handle);

            if (ParseSafetySlotHidden(handle, slot, symbol))
            {
                // Optional comma.
                Tokenizer::Next(handle, false);
                if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
                    Tokenizer::Next(handle, false);
                continue;
            }

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing safety slot " + str(slot) + " block for " + mapLump + ": '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        Logger::LogDebug(LOGSOURCE, "Parsed safety slot \cd" + str(slot) + "\cj block for \cd" + mapLump + ".");
        return true;
    }

    internal bool ParseSafetySlotHidden(int handle, int slot, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "hidden"))
            return false;

        Tokenizer::Next(handle);

        if (Tokenizer::GetToken(handle) == Tokenizer::TEQ)
            Tokenizer::Next(handle);

        if (!Tokenizer::TryParseBooleanOrNumbericValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for safety slot Hidden is not a correct value. Expected boolean or numeric value within bounds.");
            return false;
        }

        int parsedValue = (int)Tokenizer::GetParsedValue();
        bool hidden = parsedValue != 0;

        Game::SetSafeHidden(hidden, slot, false);

        Logger::LogDebug(LOGSOURCE, "Parsed safety slot \cd" + str(slot) + "\cj hidden: \cd" + str(hidden) + "\cj.");
        return true;
    }
}