#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace IO
{
    internal bool ParseWeatherProfiles(int handle, str mapLump, str identifyingSymbol)
    {
        return LibIO::ParseWeatherProfile(handle, identifyingSymbol, "weatherprofiles", true, HandleParsedProfile);
    }

    // Sets the retrieved profile.
    internal void HandleParsedProfile(LibIO::ParsedEmitterWeatherContextT global:0& data)
    {
        // I can't use a ref here because the data is missing. Compiler bug.
        //Weather::EmitterWeatherContextT module& context = ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[data.Index];

        Weather::SetEmitterWeatherEnabled(data.Index, data.Enabled);
        Weather::SetEmitterWeatherSkyBehavior(data.Index, data.SkyBehavior);
        Weather::SetEmitterWeatherSpawnCount(data.Index, data.SpawnCount);
        Weather::SetEmitterWeatherSpawnDelay(data.Index, data.SpawnDelay);
        Weather::SetEmitterWeatherMinRadius(data.Index, data.MinRadius);
        Weather::SetEmitterWeatherMaxRadius(data.Index, data.MaxRadius);
        Weather::SetEmitterWeatherMinZpos(data.Index, data.MinZpos);
        Weather::SetEmitterWeatherMaxZpos(data.Index, data.MaxZpos);
    }
}