#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "IO"

#include "client/footstep/footstep.acs"
#include "shared/logger/logger.acs"
#include "weather/weather.acs"

strict namespace IO
{
    void ParseWeatherDefServerside()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();
        ACS_NamedExecuteWithResult("zh2_internal_parse_weather_defs_server");
    }
}

#undef LOGSOURCE