#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace bcs
{
    extern void[]* malloc (int size);
    extern void free (void[]* ptr);
    extern void memmove (void[]* dstIn, void[]* srcIn, int size);
    extern int memcmp (void[]* ptr1in, void[]* ptr2in, int size);
    extern void[]* realloc (void[]* oldPtr, int size);
    extern void[]* alloca (int size);

    extern void allocDump ();
    extern void exit ();
}