#ifdef __INCLUDED__
    #error This file must be #imported.
#endif

#nocompact
#pragma raw include on
#pragma raw define on

// Libbcs
#pragma pointer_space global 0

#library "zh2lib"

#include "libbcs.bcs"

#include "cvars.acs"

#import "zcommon.bcs"
#import "bcsutils.acs"

#include "zh2lib.h.acs"

#include "utils/utils.acs"
#include "tokenizer/tokenize.acs"
#include "weather/weather.acs"
#include "logger/logger.acs"
#include "hook/hook.acs"
#include "eventbus/eventbus.acs"
#include "bitmath/bitmath.acs"
#include "packet/packet.acs"
#include "weight/weight.acs"
#include "chat/chat.acs"
#include "libevent/event.acs"
#include "libsync/libsync.acs"
#include "identity/identity.acs"
#include "footstep/footstep.acs"
#include "spaceutil/spaceutil.acs"
#include "teleportutil/teleportutil.acs"
#include "trackedproperties/trackedproperties.acs"
#include "libdecorate/libdecorate.acs"
#include "libio/libio.acs"
#include "math/math.acs"

#define LOGSOURCE "ZH2Lib"

strict namespace ZH2Lib
{
    void ResetPlayerLibContext(int id)
    {
        Logger::LogDebug(LOGSOURCE, "Resetting player lib context for player " + str(id) + ".");

        static LibPlayerT emptyPlayerDef;
        if (!Memcpy(LibContext.Players[id], emptyPlayerDef))
            Logger::LogError(LOGSOURCE, "Failed to empty player lib context for player " + str(id) + ".");
    }
}

#undef LOGSOURCE
