#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#linklibrary "ZH2Lib"

#include "libbcs.h.acs"

#include "zh2lib/libpreprocessor/event.h.acs"
#include "zh2lib/libpreprocessor/context.h.acs"
#include "zh2lib/libpreprocessor/identity.h.acs"
#include "zh2lib/libpreprocessor/sync.h.acs"

#include "zh2lib/utils/utils.h.acs"
#include "zh2lib/tokenizer/tokenize.h.acs"
#include "zh2lib/weather/weather.h.acs"
#include "zh2lib/logger/logger.h.acs"
#include "zh2lib/hook/hook.h.acs"
#include "zh2lib/eventbus/eventbus.h.acs"
#include "zh2lib/bitMath/bitmath.h.acs"
#include "zh2lib/packet/packet.h.acs"
#include "zh2lib/weight/weight.h.acs"
#include "zh2lib/chat/chat.h.acs"
#include "zh2lib/libevent/event.h.acs"
#include "zh2lib/libsync/libsync.h.acs"
#include "zh2lib/identity/identity.h.acs"
#include "zh2lib/footstep/footstep.h.acs"
#include "zh2lib/spaceutil/spaceutil.h.acs"
#include "zh2lib/teleportutil/teleportutil.h.acs"
#include "zh2lib/trackedproperties/trackedproperties.h.acs"
#include "zh2lib/libdecorate/libdecorate.h.acs"
#include "zh2lib/libio/libio.h.acs"
#include "zh2lib/math/math.h.acs"

strict namespace ZH2Lib
{
    #define PERSISTINGLIBCONTEXTINDEX 2

    LibContextT LibContext;
    global PersistingLibContextT PERSISTINGLIBCONTEXTINDEX: PersistingLibContext;

    struct LibContextT
    {
        LibPlayerT Players[BCSUtils::MAX_PLAYERS];

        Weight::WeightContextT WeightContext;

        // Clientside and serverside handled. Not synched.
        // Stores the eventbus keys and their callbacks.
        EventBus::EventBusCollectionT EventBusCollection;

        // Clientside and serverside handled. Not synched.
        // Stores received data from events, which has been unpacked.
        Event::EventReceiveContextT EventReceiveContext;

        // Clientside
        // When should the given client id next play a footstep sound?
        int StepTimestamps[BCSUtils::MAX_PLAYERS];

        Weather::WeatherContextT WeatherContext;
    };

    struct LibPlayerT
    {
        // Not synced, tracks properties on a player, allowing subsequent setting and unsetting of the property.
        int TrackedPropertyCounters[MAX_TRACKEDPROPERTIES];

        // Serverside. Indicates if the player is explicitly allowed to walk through other actors.
        // A tertiary state exists for returning to default.
        SpaceUtil::PlayerThruActorsStateT ThruActorsState;
    };

    struct PersistingLibContextT
    {
        Logger::LogContextT LogContext;
        Footstep::StepCollectionContextT StepContext;
        Weather::PersistingWeatherContextT WeatherContext;
    };

    extern void ResetPlayerLibContext(int id);
}