#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#linklibrary "ZH2Lib"

#include "libbcs.h.acs"

#include "libpreprocessor/event.h.acs"
#include "libpreprocessor/context.h.acs"
#include "libpreprocessor/identity.h.acs"
#include "libpreprocessor/sync.h.acs"

#include "utils/utils.h.acs"
#include "tokenizer/tokenize.h.acs"
#include "weather/weather.h.acs"
#include "logger/logger.h.acs"
#include "hook/hook.h.acs"
#include "eventbus/eventbus.h.acs"
#include "bitMath/bitmath.h.acs"
#include "packet/packet.h.acs"
#include "weight/weight.h.acs"
#include "chat/chat.h.acs"
#include "libevent/event.h.acs"
#include "libsync/libsync.h.acs"
#include "identity/identity.h.acs"
#include "footstep/footstep.h.acs"
#include "spaceutil/spaceutil.h.acs"
#include "trackedproperties/trackedproperties.h.acs"
#include "libdecorate/libdecorate.h.acs"
#include "libio/libio.h.acs"
#include "math/math.h.acs"

strict namespace ZH2Lib
{
    #define PERSISTINGLIBCONTEXTINDEX 2

    LibContextT LibContext;
    global PersistingLibContextT PERSISTINGLIBCONTEXTINDEX: PersistingLibContext;

    struct LibContextT
    {
        LibPlayerT Players[BCSUtils::MAX_PLAYERS];

        Weight::WeightContextT WeightContext;

        // Clientside and serverside handled. Not synched.
        // Stores the eventbus keys and their callbacks.
        EventBus::EventBusCollectionT EventBusCollection;

        // Clientside and serverside handled. Not synched.
        // Stores received data from events, which has been unpacked.
        Event::EventReceiveContextT EventReceiveContext;

        // Clientside
        // When should the given client id next play a footstep sound?
        int StepTimestamps[BCSUtils::MAX_PLAYERS];

        Weather::WeatherContextT WeatherContext;
    };

    struct LibPlayerT
    {
        // Not synced, tracks properties on a player, allowing subsequent setting and unsetting of the property.
        int TrackedPropertyCounters[MAX_TRACKEDPROPERTIES];

        // Serverside. Indicates if the player is explicitly allowed to walk through other actors.
        // A tertiary state exists for returning to default.
        SpaceUtil::PlayerThruActorsStateT ThruActorsState;
    };

    struct PersistingLibContextT
    {
        Logger::LogContextT LogContext;
        Footstep::StepCollectionContextT StepContext;
        Weather::PersistingWeatherContextT WeatherContext;
    };

    extern void ResetPlayerLibContext(int id);
}