#ifdef __INCLUDED__
    #error This file must be #imported.
#endif

#nocompact
#pragma raw include on
#pragma raw define on

// Libbcs
#pragma pointer_space global 0

#library "zh2lib"

#include "libbcs.bcs"

#include "zh2lib/cvars.acs"

#import "zcommon.bcs"
#import "bcsutils.acs"

#include "zh2lib.h.acs"

#include "zh2lib/utils/utils.acs"
#include "zh2lib/tokenizer/tokenize.acs"
#include "zh2lib/weather/weather.acs"
#include "zh2lib/logger/logger.acs"
#include "zh2lib/hook/hook.acs"
#include "zh2lib/eventbus/eventbus.acs"
#include "zh2lib/bitmath/bitmath.acs"
#include "zh2lib/packet/packet.acs"
#include "zh2lib/weight/weight.acs"
#include "zh2lib/chat/chat.acs"
#include "zh2lib/libevent/event.acs"
#include "zh2lib/libsync/libsync.acs"
#include "zh2lib/identity/identity.acs"
#include "zh2lib/footstep/footstep.acs"
#include "zh2lib/spaceutil/spaceutil.acs"
#include "zh2lib/teleportutil/teleportutil.acs"
#include "zh2lib/trackedproperties/trackedproperties.acs"
#include "zh2lib/libdecorate/libdecorate.acs"
#include "zh2lib/libio/libio.acs"
#include "zh2lib/math/math.acs"

#define LOGSOURCE "ZH2Lib"

strict namespace ZH2Lib
{
    void ResetPlayerLibContext(int id)
    {
        Logger::LogDebug(LOGSOURCE, "Resetting player lib context for player " + str(id) + ".");

        static LibPlayerT emptyPlayerDef;
        if (!Memcpy(LibContext.Players[id], emptyPlayerDef))
            Logger::LogError(LOGSOURCE, "Failed to empty player lib context for player " + str(id) + ".");
    }
}

#undef LOGSOURCE
