#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// General logic for setting somebody as an admin and persisting their state.

#define LOGSOURCE  "Admin"

#include "rcon.acs"
#include "hudactions.acs"

strict namespace Admin
{
    internal bool GetIsAdmin() { return GetPlayerIsAdmin(PlayerNumber()); }
    internal bool GetPlayerIsAdmin(int id)
    {
        VALIDATE_ID_VALID_FUNCTION_RETURN(id, false);
        return ZH2Game::PersistingGameContext.Players[id].IsAdmin;
    }

    internal void SetIsAdmin(bool set) { SetPlayerIsAdmin(PlayerNumber(), set); }
    internal void SetPlayerIsAdmin(int id, bool set)
    {
        VALIDATE_ID_VALID_FUNCTION(id);

        if (!BCSUTILS::PlayerIsConnected(id))
        {
            Logger::LogError(LOGSOURCE , "Failed to set admin on player. Player id " + str(id) + " is not connected.");
            return;
        }

        ZH2Game::PersistingGameContext.Players[id].IsAdmin = set;
        Logger::LogDebug(LOGSOURCE , "Player (\cd" + str(id) + "\cj) " + BCSUTILS::PlayerName(id) + " has been \cd" + (set ? "added" : "removed") + "\cj as an admin.");
    }

    internal void BroadcastAdmin(bool set)
    {
        BroadcastPlayerAdmin(PlayerNumber(), set);
    }

    // General broadcast function to inform everybody somebody was set/unset as an admin.
    internal void BroadcastPlayerAdmin(int id, bool set)
    {
        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            Append(s:"Player (\cd" + str(id) + "\cj) has been \cd" + (set ? "added" : "removed") + "\cj as an admin");
            if (PlayerNumber() == -1) Append(s:".");
            else Append(s:" by (\cd" + str(id) + "\cj) " + BCSUTILS::PlayerName(id) + ".");
        }

        Logger::LogTo(id, "\cfYou have been " + (set ? "added" : "removed") + " as an admin player!");
        Logger::LogExcept(id, logMessage);
    }

    internal void ToggleAdminHud()
    {
        if (ZH2Game::GameContext.HasAdminHudOpen)
            DisableAdminHud();
        else
            EnableAdminHud();
    }


    internal void EnableAdminHud()
    {
        // Ignore if the game ended.
        // The ending has a lot of HUD elements and clickable buttons which would interfere.
        if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
            return;

        if (!Admin::GetIsAdmin())
        {
            Logger::LogActivator("You must be an admin for this operation.");
            return;
        }

        // If we enable the admin menu, make sure the settings hud is disabled.
        ZH2Game::GameContext.HasClientSettingsHudOpen = false;

        SetIsAdminHudEnabledInternal(true);
    }

    internal void DisableAdminHud()
    {
        // If we disable the admin menu, we want to make sure to go back to the start menu.
        // Also reset the target player id if we had somebody.
        Hud::ResetHud();

        SetIsAdminHudEnabledInternal(false);
    }

    internal void SetIsAdminHudEnabledInternal(bool set)
    {
        ZH2Game::GameContext.HasAdminHudOpen = set;
        Hud::SetCursorEnabled(set);
        Player::LockMovement(set);
    }
}

#undef LOGSOURCE 