#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// General logic for setting somebody as an admin and persisting their state.

#define LogSource "Admin"

#include "rcon.acs"
#include "hudactions.acs"

strict namespace Admin
{
    internal bool GetAdmin() { return GetPlayerAdmin(PlayerNumber()); }
    internal bool GetPlayerAdmin(int id)
    {
        VALIDATE_ID_VALID_FUNCTION_RETURN(id, false);
        return ZH2Game::PersistingGameContext.Players[id].IsAdmin;
    }

    internal void SetAdmin(bool set) { SetPlayerAdmin(PlayerNumber(), set); }
    internal void SetPlayerAdmin(int id, bool set)
    {
        VALIDATE_ID_VALID_FUNCTION(id);

        if (!BCSUTILS::PlayerIsConnected(id))
        {
            Logger::LogError(LogSource, "Failed to set admin on player. Player id " + str(id) + " is not connected.");
            return;
        }

        ZH2Game::PersistingGameContext.Players[id].IsAdmin = set;
        Logger::LogDebug(LogSource, "Player (\cd" + str(id) + "\cj) " + BCSUTILS::PlayerName(id) + " has been \cd" + (set ? "added" : "removed") + "\cj as an admin.");
    }

    // General broadcast function to inform everybody somebody was set/unset as an admin.
    internal void BroadcastAdmin(int id, bool set)
    {
        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            Append(s:"Player (\cd" + str(id) + "\cj) has been \cd" + (set ? "added" : "removed") + "\cj as an admin");
            if (PlayerNumber() == -1) Append(s:".");
            else Append(s:" by (\cd" + str(id) + "\cj) " + BCSUTILS::PlayerName(id) + ".");
        }

        Logger::LogTo("\cfYou have been " + (set ? "added" : "removed") + " as an admin player!", id);
        Logger::LogExcept(logMessage, id);
    }

    internal void ToggleAdminHud()
    {
        if (ZH2Game::GameContext.HasAdminHudOpen)
            DisableAdminHud();
        else
            EnableAdminHud();
    }


    internal void EnableAdminHud()
    {
        // Ignore if the game ended.
        // The ending has a lot of HUD elements and clickable buttons which would interfere.
        if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
            return;

        if (!Admin::GetAdmin())
        {
            Logger::LogActivator("You must be an admin for this operation.");
            return;
        }

        // If we enable the admin menu, make sure the settings hud is disabled.
        ZH2Game::GameContext.HasClientSettingsHudOpen = false;

        SetAdminHudEnabledInternal(true);
    }

    internal void DisableAdminHud()
    {
        // If we disable the admin menu, we want to make sure to go back to the start menu.
        // Also reset the target player id if we had somebody.
        Hud::ResetHud();

        SetAdminHudEnabledInternal(false);
    }

    internal void SetAdminHudEnabledInternal(bool set)
    {
        ZH2Game::GameContext.HasAdminHudOpen = set;
        Hud::SetCursorEnabled(set);

        if (!NamedRequestScriptPuke("zh2_internal_menu_admin_request_set_frozen", int(set)))
            Logger::LogError(LogSource, "Failed to set frozen state on player for admin hud.");
    }
}

#undef LogSource