#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Pukable scripts.

strict namespace Admin
{
    // Callable from the rcon.

    script "zh2_enableadminplayer" (int id)
    {
        RconSetPlayerAdmin(id, true);
    }

    script "zh2_disableadminplayer" (int id)
    {
        RconSetPlayerAdmin(id, false);
    }

    internal void RconSetPlayerAdmin(int id, bool set)
    {
        if (!Identity::IsValidID(id))
            return;

        if (!BCSUTILS::PlayerIsConnected(id))
            return;

        // Just ignore if we try to enable/disable on somebody that already has admin set to the same state.
        if (GetPlayerAdmin(id) == set) return;

        SetPlayerAdmin(id, set);
        BroadcastAdmin(id, set);

        Sync::SyncAdmins();
    }
}