#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Pukable scripts.

strict namespace Admin
{
    // Callable from the rcon.

    script "zh2_admin_playerenable" (int id)
    {
        RconSetPlayerIsAdmin(id, true);
    }

    script "zh2_admin_playerdisable" (int id)
    {
        RconSetPlayerIsAdmin(id, false);
    }

    internal void RconSetPlayerIsAdmin(int id, bool set)
    {
        if (!Identity::IsValidID(id))
            return;

        if (!BCSUTILS::PlayerIsConnected(id))
            return;

        // Just ignore if we try to enable/disable on somebody that already has admin set to the same state.
        if (GetPlayerIsAdmin(id) == set) return;

        SetPlayerIsAdmin(id, set);
        BroadcastPlayerAdmin(id, set);

        Sync::SyncAdmins();
    }
}