#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    internal void LogBoldToHumans(str message) { LogBoldToSpecies(SPECIEHUMAN, message); }
    internal void LogBoldToZombies(str message) { LogBoldToSpecies(SPECIEZOMBIE, message); }

    internal void LogBoldToSpecies(SpecieTypeT specie, str message)
    {
        for (int i = 0; i < BCSUTILS::MAX_PLAYERS; ++i)
        {
            if (GetPlayerSpecie(i) != specie)
                continue;

            int tid = Identity::GetTID(i);
            if (!BCSUTILS::ActorIsAlive(tid))
                continue;

            Logger::LogTo(i, message);
        }
    }
}
