#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    internal void NameTic()
    {
        // Check if the player's name changed.
        // Update and inform other players if it's the case.

        str oldName = Player::GetName();
        str currentName = BCSUtils::PlayerName(PlayerNumber());
        if (oldName != currentName)
        {
            Player::SetName(currentName);
            Sync::SyncPlayers();

            Logger::LogDebug(LogSource, "Player \cd" + str(PlayerNumber()) + "\cj changed their name from " + oldName + " to " + currentName + ".");
        }
    }

    internal void SetName(str name)
    {
        SetPlayerName(PlayerNumber(), name);
    }

    internal void SetPlayerName(int id, str name)
    {
        ZH2Game::GameContext.Players[id].Name = name;
        ZH2Game::GameContext.Players[id].StrippedName = BCSUtils::StripColorCodes(name);
    }

    internal str GetName()
    {
        return GetPlayerName(PlayerNumber());
    }

    internal str GetPlayerName(int id)
    {
        raw name = ZH2Game::GameContext.Players[id].Name;
        return name != 0 && (str)name != "" ? (str)name : "Unknown player (" + str(id) + ")";
    }

    internal str GetStrippedName()
    {
        return GetStrippedPlayerName(PlayerNumber());
    }

    internal str GetStrippedPlayerName(int id)
    {
        raw name = ZH2Game::GameContext.Players[id].StrippedName;
        return name != 0 && (str)name != "" ? (str)name : "Unknown player (" + str(id) + ")";
    }
}
