#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LogSource "Player"

#include "specie.acs"
#include "morph.acs"
#include "log.acs"
#include "team.acs"
#include "skin.acs"
#include "inventory.acs"
#include "lock.acs"
#include "name.acs"
#include "state.acs"
#include "stats.acs"
#include "kevlar.acs"
#include "sprint.acs"
#include "panic.acs"
#include "taunt.acs"
#include "translucentallies.acs"
#include "initialzombie.acs"
#include "heartbeat.acs"

strict namespace Player
{
    void SetSurvivalDefaults()
    {
        Logger::LogDebug(LogSource, "Setting survival gamemode profile for player.");
        SetPlayFinalHeartbeat(true);
    }

    void SetEscapeDefaults()
    {
        Logger::LogDebug(LogSource, "Setting escape gamemode profile for player.");
        SetPlayFinalHeartbeat(false);
    }
}

#undef LogSource