#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    enum SpecieTypeT : int
    {
        SPECIENONE,
        SPECIEHUMAN,
        SPECIEZOMBIE
    };

    internal enum PlayerTeamT : int
    {
        TEAM_HUMAN,
        TEAM_ZOMBIE,
    };

    internal enum PlayerStateT : int
    {
        STATENONE,
        STATEGONE,
        STATEPLAYING,
        STATEDEAD,
    };

    internal enum PanicStateT : int
    {
        PANICSTATENONE,
        PANICSTATEPANICKING,
        PANICSTATECALMINGDOWN,
    };

    extern bool GetIsZombie();
    extern bool GetPlayerIsZombie(int id);
    extern bool GetIsHuman();
    extern bool GetPlayerIsHuman(int id);
}