#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    enum PlayerSpecieT : int
    {
        SPECIENONE,
        SPECIEHUMAN,
        SPECIEZOMBIE
    };

    internal enum PlayerTeamT : int
    {
        TEAM_HUMAN,
        TEAM_ZOMBIE,
    };

    internal enum PlayerStateT : int
    {
        STATENONE,
        STATEGONE,
        STATEPLAYING,
        STATEDEAD,
    };

    internal enum PlayerPanicStateT : int
    {
        PANICSTATENONE,
        PANICSTATEPANICKING,
        PANICSTATECALMINGDOWN,
    };

    internal enum ZombieSkinTypeT : int
    {
        ZOMBIESKIN_OLD,
        ZOMBIESKIN_REGULAR,
        ZOMBIESKIN_INITIAL,
    };

    extern bool GetIsZombie();
    extern bool GetPlayerIsZombie(int id);
    extern bool GetIsHuman();
    extern bool GetPlayerIsHuman(int id);
}