#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Player
{
    internal PlayerSpecieT GetSpecie()
    {
        return GetPlayerSpecie(PlayerNumber());
    }
    internal PlayerSpecieT GetPlayerSpecie(int id)
    {
        if (!Identity::IsValidID(id)) return SPECIENONE;
        return ZH2Game::GameContext.Players[id].SpecieType;
    }

    internal bool SetSpecie(PlayerSpecieT specie)
    {
        return SetPlayerSpecie(PlayerNumber(), specie);
    }
    internal bool SetPlayerSpecie(int id, PlayerSpecieT specie)
    {
        if (!Identity::IsValidID(id)) return false;
        ZH2Game::GameContext.Players[id].SpecieType = specie;
        Logger::LogDebug(LOGSOURCE , "Setting specie of \cd" + str(id) + " \cjto " + GetSpecieIndexAsString(specie) + ".");
        return true;
    }

    bool GetIsZombie() { return GetPlayerIsZombie(PlayerNumber()); }
    bool GetPlayerIsZombie(int id) { return GetPlayerSpecie(id) == SPECIEZOMBIE; }
    internal bool SetZombie() { return SetPlayerZombie(PlayerNumber()); }
    internal bool SetPlayerZombie(int id) { return SetPlayerSpecie(id, SPECIEZOMBIE); }
    script "zh2_dec_getiszombie" { SetResultValue(int(GetIsZombie())); }
    script "zh2_dec_gettargetiszombie"
    {
        if (!SetActivatorToTarget(0))
        {
            SetResultValue(0);
            terminate;
        }
        SetResultValue(int(GetIsZombie()));
    }

    bool GetIsHuman() { return GetPlayerIsHuman(PlayerNumber()); }
    bool GetPlayerIsHuman(int id) { return GetPlayerSpecie(id) == SPECIEHUMAN; }
    internal bool SetHuman() { return SetPlayerHuman(PlayerNumber()); }
    internal bool SetPlayerHuman(int id) { return SetPlayerSpecie(id, SPECIEHUMAN); }
    script "zh2_dec_getishuman" { SetResultValue(int(GetIsHuman())); }
    script "zh2_dec_gettargetishuman"
    {
        if (!SetActivatorToTarget(0))
        {
            SetResultValue(0);
            terminate;
        }
        SetResultValue(int(GetIsHuman()));
    }

    internal PlayerSpecieT GetSpecieTypeByIndex(int index)
    {
        if (index <= SPECIENONE || index > SPECIEZOMBIE)
            return SPECIENONE;

        static PlayerSpecieT collection[] = { SPECIEHUMAN, SPECIEZOMBIE };
        return collection[index - 1];
    }

    internal str GetSpecieIndexAsString(int index)
    {
        if (index <= SPECIENONE || index > SPECIEZOMBIE)
            return "none";

        static str collection[] = { "human", "zombie", };
        return collection[index - 1];
    }
}