#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawDebugHud()
    {
        fixed scale = ZH2Game::GetHudDebugScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_TOP);

        PrepareHud(
            BCSUtils::HudLeft() + ZH2Game::GetHudDebugOffsetX() + 50.0,
            BCSUtils::HudTop() - ZH2Game::GetHudDebugOffsetY() + 50.0,
            false);

        DrawPlayerStates();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_TOP);

        // All three drawn parts use the base x and y offset.
        fixed baseX = BCSUtils::HudRight() - ZH2Game::GetHudDebugOffsetX() - 250.0,
              baseY = BCSUtils::HudTop() - ZH2Game::GetHudDebugOffsetY() + 50.0;

        int rows;

        PrepareHud(baseX, baseY, false);
        rows = DrawRoundStates();

        PrepareHud(baseX, baseY + (30.0 + fixed(5 * rows)), false);
        rows = DrawTimerStates();

        PrepareHud(baseX, baseY + (110.0 + fixed(5 * rows + 20)), false);
        rows = DrawResistStates();
    }

    internal void DrawPlayerStates()
    {
        BCSUtils::HudSetFont("SmallFont");

        str message;
        buildmsg(message = StrParam())
        {
            Append(s:"\n\cgPlayers");
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                // If the player is STATENONE, we never had their state or they left before the game started.
                // Otherwise we DO show the data.
                Player::PlayerStateT state = Player::GetPlayerState(i);
                if (state == Player::STATENONE) continue;

                int tid = Identity::GetTid(i);

                Append(s:"\n\cj" + Player::GetPlayerName(i));

                int playTics = Player::GetPlayerPlayTics(i);
                if (playTics != 0)
                    Append(s:"\cd (" + str(playTics / 35) + "s)");

                // Only draw state if not playing for the sake of relevancy.
                if (state != Player::STATEPLAYING) Append(s:"\cg (" + Player::GetPlayerStateAsString(state) + ")");

                Append(s:"\ck (" + Player::GetSpecieIndexAsString(Player::GetPlayerSpecie(i)) + ")");

                if (Player::GetPlayerInitialZombiePreviously(i)) Append(s:"\cn (Initial Previously)");
                if (Player::GetPlayerInitialZombieLastMap(i)) Append(s:"\ck (Initial Last map)");
                if (Player::GetPlayerInitialZombie(i)) Append(s:"\ci (Initial)");

                // Damage is not synchronized.
                int damage = Player::GetDamageToPlayer(i);
                if (damage != 0)
                    Append(s:"\cg (" + str(damage) + " dmg)");

                // Health is not synchronized.
                if (!IsNetworkGame() && state == Player::STATEPLAYING)
                    Append(s:"\cd (" + str(Player::GetPlayerHealth(i)) + ")");
            }
        }

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, message);
        DebugDraw();
    }


    internal int DrawRoundStates()
    {
        BCSUtils::HudSetFont("SmallFont");

        int rows;
        str message;
        buildmsg(message = StrParam())
        {
            Append(s:"\cgRounds (yellow means active)");

            Round::RoundStateContextT[] module& rounds = ZH2Game::GameContext.MapDetails.Rounds;
            for (int index = 0; index < lengthof(rounds); ++index)
            {
                if (!Round::GetRoundDefined(index)) continue;

                str roundName = Round::GetRoundStateIndexAsString(index);

                // TODO: Get active index from function instead of from a variable like this.
                str lineColor = ZH2Game::GameContext.MapDetails.ActiveRoundStateIndex == index
                    ? "\cf" : "\cj";
                str line = "\n" + lineColor + roundName;
                Append(s:line);

                rows++;
            }
        }

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, message);
        DebugDraw();

        return rows;
    }

    internal int DrawTimerStates()
    {
        BCSUtils::HudSetFont("SmallFont");

        int rows;
        str message;
        buildmsg(message = StrParam())
        {
            Append(s:"\cgInternal timers");
            Append(s:"\n\cjTimer: " + str(Timer()));
            Append(s:"\n\cjSynchronized timer: " + str(Utils::GetSynchronizedTimer()));
            Append(s:"\n\cjOffset: " + str(Utils::GetSynchronizedTimer() - Timer()));
            Append(s:"\n\n");

            Append(s:"\cgTimers (yellow means active)");

            RoundTimer::RoundTimerContextT[] module& timers = ZH2Game::GameContext.MapDetails.Timers;
            for (int index = 0; index < lengthof(timers); ++index)
            {
                if (!RoundTimer::GetTimerDefined(index)) continue;

                str timerName = RoundTimer::GetTimerIndexAsString(index);
                int tics = RoundTimer::GetTimerTicsLeft(index);

                str lineColor = RoundTimer::GetActiveTimerIndex() == index
                    ? "\cf" : "\cj";
                str line = "\n" + lineColor + timerName + " " + str(tics) + "/" + str(RoundTimer::GetTimerMaximumTics(index));
                Append(s:line);

                rows++;
            }
        }

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, message);
        DebugDraw();

        return rows;
    }

    internal int DrawResistStates()
    {
        BCSUtils::HudSetFont("SmallFont");

        int rows;
        str message;
        buildmsg(message = StrParam())
        {
            Append(s:"\cgResists (yellow means active)");

            Resist::ResistT[] module& timers = ZH2Game::GameContext.MapDetails.Resists;
            for (int index = 0; index < lengthof(timers); ++index)
            {
                if (!Resist::IsDefined(index)) continue;

                int timeLeft = Resist::GetTicsLeft(index);
                str lineColor = Resist::IsActive(index)
                    ? "\cf" : "\cj";

                Resist::ResistLifecycleStateT lifecycleState = Resist::GetLifecycleState(index);
                str lifecycleStateString = Resist::GetLifecycleStateStringByIndex(lifecycleState);
                str line = "\n" + lineColor + "Resist #" + str(index + 1) + " " + str(timeLeft) + " (" + lifecycleStateString + ")";
                Append(s:line);

                rows++;
            }
        }

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, message);
        DebugDraw();

        return rows;
    }
}