#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "sync.acs"
#include "pregame.acs"
#include "playtime.acs"
#include "pickchance.acs"

strict namespace Hud
{
    internal void DrawRoundHud()
    {
        fixed scale = CVar::GetClHudRoundScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_BOTTOM);

        // While we are in pregame with no countdown to start, draw the label.
        if (Round::GetActiveKnownRoundState() == Round::STATEPREGAME
            && !RoundTimer::GetAnyTimerActive())
        {
            PrepareHud(
                CVar::GetClHudRoundOffsetX() + 320.0,
                BCSUtils::HudBottom() - CVar::GetClHudRoundOffsetY() - 50.0,
                false);

            DrawPregameStateLabel();
        }

        if (BCSUtils::ActorIsAlive(ActivatorTid()) && Round::GetActiveKnownRoundState() == Round::STATECOUNTDOWN)
        {
            PrepareHud(
                CVar::GetClHudRoundOffsetX() + 320.0,
                BCSUtils::HudBottom() - CVar::GetClHudRoundOffsetY() - 40.0,
                false);

            DrawPickChance();
        }

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_BOTTOM);

        PrepareHud(
            BCSUtils::HudLeft(),
            BCSUtils::HudBottom(),
            false);

        DrawPlayTime();
    }
}