#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace AfkPrevention
{
    internal struct AfkPreventionContextT
    {
        // A buffer to hold who got kicked since the last flush.
        bool AfkKickedPlayers[BCSUtils::MAX_PLAYERS];
    };

    internal struct PlayerAfkPreventionContextT
    {
        int LastMoveTic;
        int WarnTic;
        ZombieAfkTypeT ZombieAfkType;
    };

    // Handles the state of the zombie to keep track what state is known.
    internal enum ZombieAfkTypeT : int
    {
        TYPE_NONE,
        TYPE_CHECKING,
        TYPE_WARNED,
    };
}