#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace AfkPrevention
{
    // General boolean that acts as a buffer for broadcasting inactivity.
    internal bool GetWasRoundStartAfkKicked()
    {
        return GetPlayerWasRoundStartAfkKicked(PlayerNumber());
    }

    internal bool GetPlayerWasRoundStartAfkKicked(int id)
    {
        return ZH2Game::GameContext.AfkPreventionContext.AfkKickedPlayers[id];
    }

    internal void SetAfkKicked(bool set)
    {
        SetPlayerAfkKicked(PlayerNumber(), set);
    }

    internal void SetPlayerAfkKicked(int id, bool set)
    {
        ZH2Game::GameContext.AfkPreventionContext.AfkKickedPlayers[id] = set;
    }

    // The last tic the player has moved
    internal int GetLastMoveTic()
    {
        return GetPlayerLastMoveTic(PlayerNumber());
    }

    internal int GetPlayerLastMoveTic(int id)
    {
        return ZH2Game::GameContext.Players[id].AfkPreventionContext.LastMoveTic;
    }

    internal void SetLastMoveTic(int tic)
    {
        SetPlayerLastMoveTic(PlayerNumber(), tic);
    }

    internal void SetPlayerLastMoveTic(int id, int tic)
    {
        ZH2Game::GameContext.Players[id].AfkPreventionContext.LastMoveTic = tic;
    }

    // The tic when we start warning the player of possibly getting kicked.
    internal int GetWarnTic()
    {
        return GetPlayerWarnTic(PlayerNumber());
    }

    internal int GetPlayerWarnTic(int id)
    {
        return ZH2Game::GameContext.Players[id].AfkPreventionContext.WarnTic;
    }

    internal void SetWarnTic(int tic)
    {
        SetPlayerWarnTic(PlayerNumber(), tic);
    }

    internal void SetPlayerWarnTic(int id, int tic)
    {
        ZH2Game::GameContext.Players[id].AfkPreventionContext.WarnTic = tic;
    }

    // The last tic the player has moved
    internal ZombieAfkTypeT GetZombieAfkType()
    {
        return GetPlayerZombieAfkType(PlayerNumber());
    }

    internal ZombieAfkTypeT GetPlayerZombieAfkType(int id)
    {
        return ZH2Game::GameContext.Players[id].AfkPreventionContext.ZombieAfkType;
    }

    internal void SetZombieAfkType(ZombieAfkTypeT type)
    {
        SetPlayerZombieAfkType(PlayerNumber(), type);
    }

    internal void SetPlayerZombieAfkType(int id, ZombieAfkTypeT type)
    {
        ZH2Game::GameContext.Players[id].AfkPreventionContext.ZombieAfkType = type;
    }

    // Helper booleans to check if the player has moved at all in the round.
    internal bool GetHasMovedThisRound()
    {
        return GetPlayerHasMovedThisRound(PlayerNumber());
    }

    internal bool GetPlayerHasMovedThisRound(int id)
    {
        return GetPlayerLastMoveTic(id) != 0;
    }

    // Helper booleans to check if the player has moved at all in the round.
    internal bool GetHasAfkWarn()
    {
        return GetPlayerHasAfkWarn(PlayerNumber());
    }

    internal bool GetPlayerHasAfkWarn(int id)
    {
        return GetPlayerWarnTic(id) != 0;
    }

    // The tics until the player would be kicked for being inactive at round start.
    // NOTE: This does not check if you did move, it merely returns when you would get kicked.
    internal int GetTicsUntilRoundStartKick()
    {
        return GetPlayerTicsUntilRoundStartKick(PlayerNumber());
    }

    internal int GetPlayerTicsUntilRoundStartKick(int id)
    {
        int seconds = ZH2Game::GetAfkMoveAtRoundStartBeforeSeconds();
        if (seconds == 0)
            return 0;

        int playTics = Player::GetPlayerPlayTics(id);
        return BCSUtils::Max(0, (seconds * 35) - playTics);
    }

    // The tics until the grace tics end for the zombie.
    internal int GetZombieGraceTicsLeft()
    {
        return GetPlayerZombieGraceTicsLeft(PlayerNumber());
    }

    internal int GetPlayerZombieGraceTicsLeft(int id)
    {
        int graceTics = ZH2Game::GetAfkZombieMoveGraceTics();
        if (graceTics == 0)
            return 0;

        int lastMoveTic = GetPlayerLastMoveTic(id);
        return BCSUtils::Max(0, graceTics - (Utils::GetSynchronizedTimer() - lastMoveTic));
    }

    // The tics until the check tics end for the zombie.
    internal int GetZombieCheckTicsLeft()
    {
        return GetPlayerZombieCheckTicsLeft(PlayerNumber());
    }

    internal int GetPlayerZombieCheckTicsLeft(int id)
    {
        int graceTics = ZH2Game::GetAfkZombieMoveGraceTics();
        int checkTics = ZH2Game::GetAfkZombieMoveCheckTics();
        if (checkTics == 0)
            return 0;

        int lastMoveTic = GetPlayerLastMoveTic(id);
        return BCSUtils::Max(0, (checkTics + graceTics) - (Utils::GetSynchronizedTimer() - lastMoveTic));
    }

    // The tics until the player would be kicked for being inactive as a zombie.
    // NOTE: This does not check if you did move, it merely returns when you would get kicked.
    internal int GetZombieWarnTicsLeft()
    {
        return GetPlayerZombieWarnTicsLeft(PlayerNumber());
    }

    internal int GetPlayerZombieWarnTicsLeft(int id)
    {
        int seconds = ZH2Game::GetAfkZombieMoveWarnSeconds();
        if (seconds == 0)
            return 0;

        int warnTic = GetPlayerWarnTic(id);
        return BCSUtils::Max(0, seconds * 35 - (Utils::GetSynchronizedTimer() - warnTic));
    }
}
