#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawResistMenuHud(fixed x, fixed y, fixed scale)
    {
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfResist");

        y += 10.0 * scale;
        if (DrawClickableText(--_drawnHudId, x, y, 100.0 * scale, 10.0 * scale, "Back to start"))
            OpenAdminMenu(MENU_START);
        
        y += 20.0 * scale;

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfManage resists");

        y += 10.0 * scale;
        int rows = 0;
        Resist::ResistT[]& resists = ZH2Game::GameContext.MapDetails.Resists;
        for (int index = 0; index < lengthof(resists); ++index)
        {
            if (!Resist::IsDefined(index)) continue;

            BCSUtils::HudSetPoint(x, y + fixed(10 * rows) * scale);
            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudDrawText(--_drawnHudId, "Resist #" + str(index));

            BCSUtils::HudSetPoint(x + 80.0 * scale, y + fixed(10 * rows) * scale);
            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudDrawText(--_drawnHudId, str(Resist::GetTicsLeft(index)) + "/" + str(Resist::GetMaximumTics(index)));

            if (DrawClickableTextConditional(
                !Resist::IsActive(index), --_drawnHudId, x + 140.0, y + fixed(10 * rows) * scale, 40.0 * scale, 10.0 * scale, "start"))
            {
                Admin::AdminSetStartResistClientside(index);
            }

            if (DrawClickableTextConditional(
                Resist::IsActive(index), --_drawnHudId, x + 190.0, y + fixed(10 * rows) * scale, 40.0 * scale, 10.0 * scale, "stop"))
            {
                Admin::AdminSetStopResistClientside(index);
            }

            rows++;
        }
    }
}