#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawResistMenuHud()
    {
        BCSUtils::HudSetTextColor(CR_WHITE);

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, "\cfResist");

        if (DrawClickableText(--_drawnHudId, 0.0, 10.0, 100.0, 10.0, "Back to start"))
            OpenAdminMenu(ADMINMENU_START);

        BCSUtils::HudSetTextColor(CR_WHITE);

        HudSetPointInternal(0.0, 30.0);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfManage resists");

        int rows = 0;
        Resist::ResistT[] module& resists = ZH2Game::GameContext.MapDetails.Resists;
        for (int index = 0; index < lengthof(resists); ++index)
        {
            if (!Resist::IsDefined(index)) continue;

            fixed addY = 40.0 + fixed(10 * rows);

            BCSUtils::HudSetTextColor(CR_WHITE);

            HudSetPointInternal(0.0, addY);
            BCSUtils::HudDrawText(--_drawnHudId, "Resist #" + str(index));

            BCSUtils::HudSetTextColor(CR_WHITE);

            HudSetPointInternal(80.0, addY);
            BCSUtils::HudDrawText(--_drawnHudId, str(Resist::GetTicsLeft(index)) + "/" + str(Resist::GetMaximumTics(index)));

            Resist::ResistRunStateT state = Resist::GetRunState(index);

            if (DrawClickableTextConditional(
                state == Resist::STATENONE, --_drawnHudId, 140.0, addY, 40.0, 10.0, "start"))
            {
                Admin::AdminSetStartResistClientside(index);
            }

            if (DrawClickableTextConditional(
                state == Resist::STATERUNNING || state == Resist::STATEPAUSED, --_drawnHudId, 190.0, addY, 40.0, 10.0, "elapse"))
            {
                Admin::AdminSetElapseResistClientside(index);
            }

            if (DrawClickableTextConditional(
                state == Resist::STATERUNNING || state == Resist::STATEPAUSED, --_drawnHudId, 250.0, addY, 40.0, 10.0, "stop"))
            {
                Admin::AdminSetStopResistClientside(index);
            }

            if (DrawClickableTextConditional(
                state == Resist::STATERUNNING, --_drawnHudId, 300.0, addY, 40.0, 10.0, "pause"))
            {
                Admin::AdminSetPauseResistClientside(index);
            }

            if (DrawClickableTextConditional(
                state == Resist::STATEPAUSED, --_drawnHudId, 350.0, addY, 40.0, 10.0, "resume"))
            {
                Admin::AdminSetResumeResistClientside(index);
            }

            rows++;
        }
    }
}