#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawRoundMenuHud(int id, fixed x, fixed y, fixed scale)
    {
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(id--, "\cfRound");

        y += 10.0 * scale;
        if (DrawClickableText(id--, x, y, 100.0 * scale, 10.0 * scale, "Back to start"))
            OpenAdminMenu(MENU_START);
        
        y += 20.0 * scale;

        BCSUtils::HudSetPoint(x, y);
        if (DrawClickableTextConditional(
            Round::GetActiveKnownRoundState() == Round::STATEPLAYING, id--, x, y, 60.0 * scale, 10.0 * scale, "End game"))
        {
            Admin::AdminEndGameClientside();
        }

        y += 10.0 * scale;

        // Kill unsafe players
        if (DrawClickableTextConditional(
            Round::GetActiveKnownRoundState() == Round::STATEPLAYING, id--, x, y, 80.0 * scale, 10.0 * scale, "Kill unsafe players"))
        {
            Admin::AdminKillUnsafePlayersClientSide();
        }

        y += 20.0 * scale;
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(id--, "\cfSet round state");

        y += 10.0 * scale;

        // Explicit button for disabling the current round state.
        BCSUtils::HudSetPoint(x, y);
        if (DrawClickableTextConditional(
            Round::GetActiveRoundStateIndex() != 0, id--, x, y, 80.0 * scale, 10.0 * scale, "Disable round state"))
        {
            Admin::AdminSetRoundStateClientside(0);
        }

        y += 10.0 * scale;
        int rows = 0;
        Round::RoundStateContextT[]& rounds = ZH2Game::GameContext.MapDetails.Rounds;
        for (int index = 0; index < lengthof(rounds); ++index)
        {
            if (!Round::GetRoundDefined(index)) continue;

            if (DrawClickableTextConditional(
                Round::GetActiveRoundStateIndex() != index, id--, x, (y + fixed(10 * rows) * scale), 80.0 * scale, 10.0 * scale, Round::GetRoundStateIndexAsString(index)))
            {
                Admin::AdminSetRoundStateClientside(index);
            }

            rows++;
        }

        y += (20.0 + fixed(10 * rows)) * scale;
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(id--, "\cfSet round timer");

        y += 10.0 * scale;

        // Explicit button for disabling the current timer.
        BCSUtils::HudSetPoint(x, y);
        if (DrawClickableTextConditional(
            RoundTimer::GetActiveTimerIndex() != 0, id--, x, y, 80.0 * scale, 10.0 * scale, "Disable timer"))
        {
            Admin::AdminSetRoundTimerClientside(0);
        }

        y += 10.0 * scale;

        rows = 0;
        RoundTimer::RoundTimerContextT[]& roundTimers = ZH2Game::GameContext.MapDetails.Timers;
        for (int index = 0; index < lengthof(roundTimers); ++index)
        {
            if (!RoundTimer::GetTimerDefined(index)) continue;

            if (DrawClickableTextConditional(
                RoundTimer::GetActiveTimerIndex() != index, id--, x, (y + fixed(10 * rows)), 80.0 * scale, 10.0 * scale, RoundTimer::GetTimerIndexAsString(index)))
            {
                Admin::AdminSetRoundTimerClientside(index);
            }

            rows++;
        }
    }
}