#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawStartMenuHud(int id, fixed x, fixed y, fixed scale)
    {
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(id--, "\cfAdmin menu");

        y += 10.0 * scale;
        if (DrawClickableText(id--, x, y, 100.0 * scale, 10.0 * scale, "Players"))
            OpenAdminMenu(MENU_PLAYER);

        y += 10.0 * scale;
        if (DrawClickableText(id--, x, y, 100.0 * scale, 10.0 * scale, "Timers"))
            OpenAdminMenu(MENU_TIMER);

        y += 10.0 * scale;
        if (DrawClickableText(id--, x, y, 100.0 * scale, 10.0 * scale, "Round"))
            OpenAdminMenu(MENU_ROUND);

        y += 10.0 * scale;
        if (DrawClickableText(id--, x, y, 100.0 * scale, 10.0 * scale, "Resists"))
            OpenAdminMenu(MENU_RESIST);
    }
}