#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawPlayerCounters(Player::ZombieSkinTypeT skinType)
    {
        int humanCount = Game::HumanCount();
        int zombieCount = Game::ZombieCount();

        fixed x = 0.0;

        if (humanCount > 0)
        {

            HudSetPointInternal(-15.0, 0.0);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDHBACK");
            DebugDraw();

            HudSetPointInternal(-10.0, 2.0);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDCHUMN");
            DebugDraw();

            HudSetPointInternal(8.0, 2.0);
            BCSUtils::HudDrawText(--_drawnHudId, str(humanCount));
            DebugDraw();

            x += 50.0;
        }

        if (zombieCount > 0)
        {
            // NOTE: Initial not currently working because we don't check initial zombies by design.
            str zombieGraphic;
            switch(skinType)
            {
                case Player::ZOMBIESKIN_INITIAL:
                    zombieGraphic = "HUDCZOMI";
                    break;
                case Player::ZOMBIESKIN_REGULAR:
                    zombieGraphic = "HUDCZOMR";
                    break;
                case Player::ZOMBIESKIN_OLD:
                    zombieGraphic = "HUDCZOMO";
                    break;
            }

            HudSetPointInternal(x - 15.0, 0.0);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDZBACK");
            DebugDraw();

            HudSetPointInternal(x - 10.0, 2.0);
            BCSUtils::HudDrawImage(--_drawnHudId, zombieGraphic);
            DebugDraw();

            HudSetPointInternal(x + 8.0, 2.0);
            BCSUtils::HudDrawText(--_drawnHudId, str(zombieCount));
            DebugDraw();
        }
    }

    internal void DrawStatCounters(Player::ZombieSkinTypeT skinType)
    {
        int kills = Player::GetZombieKills();
        int infects = Player::GetInfects();

        if (kills > 0 || infects > 0)
        {
            HudSetPointInternal(-18.0, -2.0);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDTBACK");
            DebugDraw();
        }

        fixed x = 0.0;

        if (kills > 0)
        {
            // NOTE: Initial not currently working because we don't check initial zombies by design.
            str zombieGraphic;
            switch(skinType)
            {
                case Player::ZOMBIESKIN_INITIAL:
                    zombieGraphic = "HUDKCZMI";
                    break;
                case Player::ZOMBIESKIN_REGULAR:
                    zombieGraphic = "HUDKCZMR";
                    break;
                case Player::ZOMBIESKIN_OLD:
                    zombieGraphic = "HUDKCZMO";
                    break;
            }

            HudSetPointInternal(-10.0, 0.0);
            BCSUtils::HudDrawImage(--_drawnHudId, zombieGraphic);
            DebugDraw();

            HudSetPointInternal(8.0, 0.0);
            BCSUtils::HudDrawText(--_drawnHudId, str(kills));
            DebugDraw();

            x += 30.0;
        }

        if (infects > 0)
        {
            HudSetPointInternal(x - 10.0, 0.0);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDCINFC");
            DebugDraw();

            HudSetPointInternal(x + 8.0, 0.0);
            BCSUtils::HudDrawText(--_drawnHudId, str(infects));
            DebugDraw();
        }
    }
}