#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "ztele.acs"
#include "counter.acs"

// TODO: has its own flow, should probably be combined to avoid confusion.
#include "fullserver.acs"
#include "resist.acs"

strict namespace Hud
{
    internal void DrawGameHud()
    {
        fixed scale = ZH2Game::GetHudGameScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        PrepareHud(
            320.0,
            BCSUtils::HudBottom() - 100.0,
            true);

        DrawZombieTeleportTime();

        // Do not draw the counters unless there are more than two players playing.
        if (PlayerCount() >= 2)
        {
            // Get general skin type to show for zombies.
            Player::ZombieSkinTypeT skinType = Player::GetZombieSkinType(false);

            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_CENTER);
            BCSUtils::HudSetFont("cybfont");

            PrepareHud(
                BCSUtils::HudLeft() - ZH2Game::GetHudPlayerStatusOffsetX() + 60.0,
                BCSUtils::HudBottom() - ZH2Game::GetHudPlayerStatusOffsetY() - 10.0,
                true);

            DrawPlayerCounters(skinType);

            PrepareHud(
                BCSUtils::HudRight() + ZH2Game::GetHudPlayerStatusOffsetX() - 190.0,
                BCSUtils::HudBottom() - ZH2Game::GetHudPlayerStatusOffsetY() - 120.0,
                true);

            DrawStatCounters(skinType);

            BCSUtils::HudSetFont("smallfont");
        }
    }
}