#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    Resist::ResistHookDataT? _resistHookData;

    internal void DrawResistsHud()
    {
        // Client is a zombie, and the cvar to not show resists is enabled.
        if (Player::GetIsZombie() && !ZH2Game::GetShowZombiesResists())
            return;

        fixed scale = ZH2Game::GetHudResistsScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_TOP);

        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        // TODO: We should be able to define for each resist what it should do (not fade out for example)
        BCSUtils::HudSetAlpha(GetFadeOutAlpha());

        // On a full server event, offset the resists downwards as to avoid overlapping with the wobbling text.
        fixed addY = Game::GetFullServerElapsedTics() > 0 ? 50.0 : 0.0;
        PrepareHud(
            320.0,
            BCSUtils::HudTop() + 50.0 + addY,
            true);

        DrawResists();
    }

    internal void DrawResists()
    {
        // Ensure we have the hook data allocated.
        if (_resistHookData == null)
            _resistHookData = BCS::Malloc(lengthof(_resistHookData));

        int offset = 0;
        for (int index = 0; index < MAX_RESISTS; ++index)
        {
            if (!Resist::IsDefined(index))
                continue;

            if (Resist::GetRunState(index) != Resist::STATERUNNING)
                continue;

            _resistHookData.Index = index;
            _resistHookData.Offset = offset;
            Hook::Call(Hook::HOOK_CLIENTDRAWRESIST, _resistHookData);

            DrawResist(index, offset++);
        }
    }

    internal void DrawResist(int index, int offset)
    {
        Resist::ResistT module& resist = Resist::GetRefByindex(index);
        int ticsLeft = Resist::GetTicsLeft(index);

        // Failsafe, as online the client might not be informed in time of the resist ending.
        if (ticsLeft <= 0)
            return;

        str FormatLabel(int colorAtIndex, str label)
        {
            // We add 35 tics or we might display "0 seconds" which is weird.
            int ticsLeftPlusOne = ticsLeft + 35;

            // Check for possible time to add.
            if (BCSUtils::StrContains(label, RESIST_TIME_TOKEN))
            {
                // Color the time token that the label has.
                // TODO: We want to somehow incorporate colored text here.
                if (colorAtIndex != -1) label = BCSUTILS::StrReplace(label, RESIST_TIME_TOKEN, "\cj" + str(ticsLeftPlusOne / 35) + "\c-");
                else label = BCSUTILS::StrReplace(label, RESIST_TIME_TOKEN, str(ticsLeftPlusOne / 35));
            }

            // If the label contains the plural token in the string, then format it depending on the time left.
            // This is a very basic check which adds "s" and the point is that "second" and "seconds" get supported.
            if (BCSUtils::StrContains(label, RESIST_PLURAL_TOKEN))
            {
                if (ticsLeftPlusOne > 35 && ticsLeftPlusOne <= 70)
                    label = BCSUtils::StrReplace(label, RESIST_PLURAL_TOKEN, "");
                else
                    label = BCSUtils::StrReplace(label, RESIST_PLURAL_TOKEN, "s");
            }

            return label;
        }

        bool hideTopReason = Resist::GetHideTopReason(index);
        bool hideTimeReason = Resist::GetHideTimeReason(index);

        if (!hideTopReason && resist.InitialState.TopReasonLabel != (raw)0 && resist.InitialState.TopReasonLabel != "")
        {
            int colorAtIndex = !resist.InitialState.TopReasonHasColoredTimeToken
                ? resist.InitialState.TopReasonTimeTokenIndex : -1;
            str topReasonLabel = FormatLabel(colorAtIndex, resist.InitialState.TopReasonLabel);

            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudSetFont("SmallFont");

            HudSetPointInternal(0.0, fixed(30 * offset));
            BCSUtils::HudDrawText(--_drawnHudId, topReasonLabel);
            DebugDraw();
        }

        if (!hideTimeReason && resist.InitialState.TimeReasonLabel != (raw)0 && resist.InitialState.TimeReasonLabel != "")
        {
            int colorAtIndex = !resist.InitialState.TimeReasonHasColoredTimeToken
                ? resist.InitialState.TimeReasonTimeTokenIndex : -1;
            str timeReasonLabel = FormatLabel(colorAtIndex, resist.InitialState.TimeReasonLabel);

            BCSUtils::HudSetTextColor(CR_RED);
            BCSUtils::HudSetFont("BigFont");

            HudSetPointInternal(0.0, fixed(30 * offset) + 12.0);
            BCSUtils::HudDrawText(--_drawnHudId, timeReasonLabel);
            DebugDraw();
        }
    }

    internal fixed GetFadeOutAlpha()
    {
        // We decrement a single tic because the HUD otherwise shows the previous second for a single tic as soon as it faded in.
        int phase = (Utils::GetSynchronizedTimer() - 1) % 35;
        if (phase < 18)
            return 1.0;

        // Fade over 18 tics.
        int fadeStep = phase - 18;
        return 1.0 - fixed(fadeStep) / 18.0;
    }
}