#ifdef __IMPORTED__
	#error This file must be #included.
#endif

#define TICTOSECOND 2.85714285714

strict namespace Utils
{
	extern str WrapString(str input, int maxLength);
    extern str TruncateString(str input, int limit, str suffix = "...");
	extern str FormatTics(int tics, bool includeDecimals = false);

	extern int GetSynchronizedTimer(void);
	extern void InitializeSynchronizedTimerForPlayer(int playerId);
    extern void ScaleToScreen();
}