#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawGameHud()
    {
        fixed scale = ZH2Game::GetHudGameScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_BOTTOM);

        fixed x = 320.0,
              y = BCSUtils::HudBottom() - 100.0;
              
        x += _xShakeOffset;
        y += _yShakeOffset;

        _drawnHudId = HUDID_GAME;
        DrawZombieTeleportTime(x, y);
    }
}