name: "Bug Report"
description: Report a problem with Zombie Horde 2.
title: "[Bug] "
labels: ["type-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve **Zombie Horde 2**!
        **Please do not report exploits or vulnerabilities here.** Contact us directly.
        
        **Please note** this project is not affiliated with Zandronum and its development.
        If the issue is caused by the engine itself, report it to the Zandronum team instead.

  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      description: "Please confirm before submitting:"
      options:
        - label: "I have searched existing issues to avoid duplicates."
          required: true
        - label: "I am using Zandronum **3.2.1 or newer**."
          required: true
        - label: "The bug is not an engine bug."
          required: true
        - label: "The bug is not an exploit or vulnerability which should be reported directly."
          required: true

  - type: input
    id: version
    attributes:
      label: "Game version"
      description: "Which version of Zombie Horde 2 are you running? You are able to find the version of the mod by looking at the bottom right of your game window when playing the mod."
      placeholder: "e.g. v2.0.0-beta"

  - type: textarea
    id: description
    attributes:
      label: "Bug description"
      description: "Please provide a clear explanation of the bug."
      placeholder: "Describe the problem here..."
    validations:
      required: true
      
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "Please provide a severity to this issue to mark its importance."
      options:
        - "Minor issue"
        - "Major issue"
        - "Crashes game"
        - "Exploit"
        - "Other"

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "If possible, please provide steps to reproduce the bug to make confirming easier."
      placeholder: |
        1. Start the game
        2. Go to map 'ZM01'
        3. ...

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What is supposed to happen in this situation?"
      placeholder: |
        Write behaviour...

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots / Logs"
      description: "Screenshots help visualize the bug. The mod has build-in warning/error logging that can also help greatly if you are able to share these."
      placeholder: |
        Screenshot links / logs...
