name: "Feature Request"
description: Suggest an idea or improvement for Zombie Horde 2.
title: "[Feature] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea for **Zombie Horde 2**!  
        **Please note** we cannot add engine-level features. Suggest these to the Zandronum team instead.

  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      description: "Please confirm before submitting:"
      options:
        - label: "I have searched existing issues to avoid duplicates."
          required: true
        - label: "The feature is fit as a mod feature and not an engine feature."
          required: true

  - type: input
    id: summary
    attributes:
      label: "Feature summary"
      description: "Briefly describe the feature you wish to see."
      placeholder: "e.g. new CVar, new game mode, change of a feature..."
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Feature details"
      description: "Explain your idea in detail."
      placeholder: "Explain what the feature should do, why it would help gameplay, etc."
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why would this feature improve the experience?"
      placeholder: "Explain how this benefits players or gameplay..."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "Alternatives of a feature might fit implementation better or fit as an initial change to later implement as a whole."
      placeholder: |
        Write alternatives...
