name: "Question / Discussion"
description: Ask a question about Zombie Horde 2 (not for bug reports or feature requests).
title: "[Question] "
labels: ["type-question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out!  
        **Please note** this form is **not** for bug reports or feature requests.  
        - Use **Bug Report** if you found an actual issue.  
        - Use **Feature Request** if you want a new idea added.  
        - Only use this for gameplay questions, clarifications, or general discussion.
        Questions and discussions are better suited in the Discord server if you wish to receive more answers.

  - type: checkboxes
    id: checks
    attributes:
      label: "Before posting..."
      description: "Please confirm you are using the correct template:"
      options:
        - label: "This is not a bug report."
          required: true
        - label: "This is not a feature request."
          required: true
          
  - type: dropdown
    id: category
    attributes:
      label: "Category"
      description: "Please provide a category to this issue."
      options:
        - "Gameplay / mechanics"
        - "Mapping / modding"
        - "Compatibility"
        - "Other"

  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Ask your question or start your discussion here."
      placeholder: "Write your question or discussion topic..."
    validations:
      required: true
