blank_issues_enabled: false

contact_links:
  - name: Contact (opens a Discord server invite link)
    url: https://discord.roydefined.com/
    about: Please join the Discord for suggestions or to report bugs. Always privately report exploits or vulnerabilities instead of sharing these publicly.