#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// !!DEPRECATED!!
// The parsing of radio blocks has been moved into a separate lump.
// Users should use that block instead. This path will keep working.

strict namespace IO
{
    internal bool ParseRadio(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "radio"))
            return false;

        Logger::LogWarning(LOGSOURCE, "Parsing radio tracks through a " + MODDEFLUMPNAME + " lump has been deprecated! Use the new " + RADIODEFLUMPNAME + " lump instead.");
        return ParseRadioBlock(handle);
    }
}