#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Hard limit on the number of maps we can define.
// The base bata does hold all the base properties of a map so we should not make this a huge number.
#define MAXMAPCOUNT 500

#define MAPVOTE_HARDCODED_PICKS_LENGTH 3

strict namespace Map
{
    internal enum MapVoteHardcodedPick : int
    {
        MAPVOTE_REPLAY,
        MAPVOTE_NEXT,
        MAPVOTE_RANDOM,
    };

    struct MapPropertiesT
    {
        str GameMode;
        str Label;
        str Graphic;
        bool IsNew;
        bool IsLegacyMap;
    };
}