#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "PlayerSpace"

strict namespace PlayerSpace
{
    // TODO: This return a boolean because we must know if we should resync players. Can this be changed? It's kind of ugly.
    internal bool ThruActorTic()
    {
        // Is the player in a state where they want to turn off ThruActors?
        if (GetThruActorsState() != STATE_GOBACKDEFAULT)
            return false;

        // Is there space to turn off ThruActors?
        if (!GetHasSpace())
            return false;

        BCSUtils::ChangeFlag("THRUACTORS", false);
        SetThruActorsState(STATE_DEFAULT);

        return true;
    }

    void SetThruActors(bool enable)
    {
        SetPlayerThruActors(PlayerNumber(), enable);
    }

    void SetPlayerThruActors(int id, bool enable)
    {
        int tid = Identity::GetTid(id);
        PlayerThruActorsStateT currentState = GetPlayerThruActorsState(id);

        // Ensure we're not already in the correct state.
        bool doContinue = enable
            ? currentState != STATE_THRUACTORS
            : currentState != STATE_DEFAULT;

        if (!doContinue)
            return;

        // We only enable the flag. We never disable it.
        // The tic function will take care of that as it needs to ensure there is space.
        // Also, if we're on STATE_GOBACKDEFAULT we still have the flag.
        if (enable && currentState == STATE_DEFAULT)
            BCSUtils::ChangeActorFlag(tid, "THRUACTORS", true);

        // If we unset the state, we want to request the state to turn back.
        PlayerThruActorsStateT nextState = enable ? STATE_THRUACTORS : STATE_GOBACKDEFAULT;
        SetPlayerThruActorsState(id, nextState);
    }

    PlayerThruActorsStateT GetThruActorsState()
    {
        return GetPlayerThruActorsState(PlayerNumber());
    }

    PlayerThruActorsStateT GetPlayerThruActorsState(int id)
    {
        return ZH2Lib::LibContext.Players[id].ThruActorsState;
    }

    void SetThruActorsState(PlayerThruActorsStateT state)
    {
        SetPlayerThruActorsState(PlayerNumber(), state);
    }

    void SetPlayerThruActorsState(int id, PlayerThruActorsStateT state)
    {
        ZH2Lib::LibContext.Players[id].ThruActorsState = state;
    }

    PlayerThruActorsStateT GetThruActorsStateByIndex(int index)
    {
        if (index <= STATE_DEFAULT || index > STATE_GOBACKDEFAULT)
            return STATE_DEFAULT;

        static PlayerThruActorsStateT collection[] = { STATE_DEFAULT, STATE_THRUACTORS, STATE_GOBACKDEFAULT };
        return collection[index];
    }
}

#undef LOGSOURCE
