#ifdef __IMPORTED__
	#error This file must be #included.
#endif

#define LOGSOURCE  "TrackedProperties"

// Small little util to track certain properties in the case they can trigger multiple times subsequently.

strict namespace TrackedProperties
{
	bool AddProperty(int index)
	{
		return AddPlayerProperty(PlayerNumber(), index);
	}

	bool AddPlayerProperty(int id, int index)
	{
		return ++ZH2Lib::LibContext.Players[id].TrackedPropertyCounters[index] == 1;
	}

	bool RemoveProperty(int index)
	{
		return RemovePlayerProperty(PlayerNumber(), index);
	}

	bool RemovePlayerProperty(int id, int index)
	{
		return --ZH2Lib::LibContext.Players[id].TrackedPropertyCounters[index] == 0;
	}
}

#undef LOGSOURCE 
