#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    // This indicates the sub menu that we are on when in the `ADMINMENU_PLAYER` menu.
    internal AdminMenuPlayerTargetT menuPlayerTarget;

    // This indicates what player we should target when we are in the `ADMINMENU_PLAYER` screen and targeting a specific player.
    // If -1 we don't target anybody and we render the initial window instead.
    internal int _menuPlayerTargetId = -1;

    // Used to pass along species when pressing buttons for specie specific players.
    // Can be set using the buttons.
    internal Player::SpecieTypeT _filteredSpecie;

    internal void DrawPlayerMenuHud(fixed x, fixed y, fixed scale)
    {
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfPlayers");

        y += 10.0 * scale;
        if (DrawClickableText(--_drawnHudId, x, y, 100.0 * scale, 10.0 * scale, "Back to start"))
            OpenAdminMenu(ADMINMENU_START);

        y += 10.0 * scale;

        if (menuPlayerTarget != MENUTARGET_NONE)
        {
            if (DrawClickableText(--_drawnHudId, x, y, 100.0 * scale, 10.0 * scale, "Back to players"))
            {
                _menuPlayerTargetId = -1;
                menuPlayerTarget = MENUTARGET_NONE;
            }
        }
        else
        {
            if (DrawClickableText(--_drawnHudId, x, y, 100.0 * scale, 10.0 * scale, "For all players"))
                menuPlayerTarget = MENUTARGET_ALL;
        }
        
        y += 20.0 * scale;

        // Draw player specific commands when we select a player, otherwise draw the player list.
        switch(menuPlayerTarget)
        {
            case MENUTARGET_NONE:
                DrawPlayerList(x, y, scale);
                break;
            
            case MENUTARGET_ALL:
                DrawGiveAll(x, y, scale);
                break;
            
            case MENUTARGET_PLAYERSPECIFIC:
                DrawPlayerDetails(x, y, scale, _menuPlayerTargetId);
                break;
        }
    }

    internal void DrawPlayerList(fixed x, fixed y, fixed scale)
    {
        // Add bots as human/zombie. Doesn't work if we reached max players.
        
        if (DrawClickableTextConditional(
            BCSUtils::ClientCount() != BCSUtils::MAX_PLAYERS, --_drawnHudId, x * scale, y, 100.0 * scale, 10.0 * scale, "add bot (human)"))
        {
            Admin::AdminAddHumanBotClientside();
        }

        if (DrawClickableTextConditional(
            BCSUtils::ClientCount() != BCSUtils::MAX_PLAYERS, --_drawnHudId, x + 150.0 * scale, y, 100.0 * scale, 10.0 * scale, "add bot (zombie)"))
        {
            Admin::AdminAddZombieBotClientside();
        }

        if (DrawClickableTextConditional(
            BCSUtils::BotCount() != 0, --_drawnHudId, x + 300.0 * scale, y, 100.0 * scale, 10.0 * scale, "remove bot"))
        {
            Admin::AdminRemoveBotClientside();
        }
        
        y += 10.0 * scale;

        int offset = 0;
        for (int i = 0; i < BCSUTILS::MAX_PLAYERS; ++i)
        {
            if (!BCSUTILS::ActorIsAlive(Identity::GetTID(i)))
                continue;
            
            BCSUtils::HudSetPoint(x, y + fixed(10 * offset) * scale);
            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudDrawText(--_drawnHudId, str(i));

            if (DrawClickableText(--_drawnHudId, x + 20.0, y + fixed(10 * offset) * scale, 60.0 * scale, 10.0 * scale, BCSUTILS::PlayerName(i)))
            {
                _menuPlayerTargetId = i;
                menuPlayerTarget = MENUTARGET_PLAYERSPECIFIC;
            }

            offset++;
        }
    }

    
    internal void DrawGiveAll(fixed x, fixed y, fixed scale)
    {
        // In some cases we loop over all species.
        // Note specie "none" means we give the reward to everybody in this instance.
        // (No point making a whole separate set of code when we can just reuse it).

        fixed rowY = y;

        /* LIST OF POWERS */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudDrawText(--_drawnHudId, "\cfFilter specie");
            
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetFont("SmallFont");

        y += 20.0 * scale;
    
        for (int i = Player::SPECIENONE; i <= Player::SPECIEZOMBIE; ++i)
        {
            Player::SpecieTypeT specie = Player::GetSpecieTypeByIndex(i);
            str label = specie == Player::SPECIENONE
                ? "all"
                : Player::GetSpecieIndexAsString(specie);

            if (DrawClickableTextConditional(
                _filteredSpecie != specie, --_drawnHudId, (x + fixed(50 * i)) * scale, y, 50.0 * scale, 10.0 * scale, label))
            {
                _filteredSpecie = specie;
            }
        }
        
        y += 20.0 * scale;

        /* ALLOW JOIN */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAllow join");
            
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetFont("SmallFont");

        y += 20.0 * scale;
        
        if (DrawClickableText(--_drawnHudId, x, y, 30.0 * scale, 10.0 * scale, "enable"))
            Admin::AdminSetAllowJoinClientSide(true);
        
        if (DrawClickableText(--_drawnHudId, (x + 60.0), y, 40.0 * scale, 10.0 * scale, "disable"))
            Admin::AdminSetAllowJoinClientSide(false);

        y += 20.0 * scale;

        /* LIST OF POWERS */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudDrawText(--_drawnHudId, "\cfPowers");

        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawPowerSelectors(x, y, scale, InvokeIncrementPowerOnAll);

        // Note, hardcoded 2 for the current two available items you can increase.
        y += 10.0 * 2.0 * scale;
        
        y += 20.0 * scale;

        /* ARMOR */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAdd armor");

        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawArmorIncrementSelectors(x, y, scale, InvokeArmorIncrementOnAll);
        
        y += 20.0 * scale;

        /* REWARD CONTAINERS */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive containers");
        
        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardContainerSelectors(x, y, scale, InvokeContainerOnAll);

        // Resets y and moves x
        y = rowY - 100.0;
        x += 200.0 * scale;

        /* ITEMS */
        
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive items");
        
        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawItemSelectors(x, y, scale, InvokeIncrementItemOnAll);

        // Resets y and moves x
        y = rowY - 100.0;
        x += 300.0 * scale;

        /* REWARDS */
        
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive rewards");
        
        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardSelectors(x, y, scale, InvokeGiveRewardOnAll);
    }

    internal void InvokeIncrementItemOnAll(int index, int amount)
    {
        Admin::AdminIncrementSpecieItemClientside(_filteredSpecie, index, amount);
    }

    internal void InvokeGiveRewardOnAll(int index)
    {
        Admin::AdminGiveSpecieRewardClientside(_filteredSpecie, index);
    }

    internal void InvokeIncrementPowerOnAll(int index, int amount)
    {
        Admin::AdminIncrementSpeciePowerClientside(_filteredSpecie, index, amount);
    }

    internal void InvokeArmorIncrementOnAll(int amount)
    {
        Admin::AdminIncrementSpecieArmorClientSide(_filteredSpecie, amount);
    }

    internal void InvokeContainerOnAll(Reward::RewardItemTypeFlagsT type)
    {
        Admin::AdminGiveRewardContainerSpecieClientSide(_filteredSpecie, type);
    }

    internal void DrawPlayerDetails(fixed x, fixed y, fixed scale, int playerId)
    {
        fixed rowY = y;
        
        if (playerId == -1)
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudSetTextColor(CR_RED);
            BCSUtils::HudDrawText(--_drawnHudId, "Error: failed to determine player id.");
            return;
        }
        
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, Player::GetPlayerName(playerId));

        y += 10.0 * scale;

        // Failsafe, player left or died. Should return back to the initial list.
        if (!BCSUTILS::ActorIsAlive(Identity::GetTID(playerId)))
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudSetTextColor(CR_RED);
            BCSUtils::HudDrawText(--_drawnHudId, "Player is dead or left.");
            return;
        }

        if (DrawClickableTextConditional(
            !Player::GetPlayerIsZombie(playerId), --_drawnHudId, x, y, 50.0 * scale, 10.0 * scale, "infect"))
        {
            Admin::AdminInfectPlayerClientside(playerId);
        }

        if (DrawClickableTextConditional(
            !Player::GetPlayerIsHuman(playerId), --_drawnHudId, x + 50.0 * scale, y, 50.0 * scale, 10.0 * scale, "cure"))
        {
            Admin::AdminCurePlayerClientside(playerId);
        }

        if (DrawClickableText(--_drawnHudId, x + 90.0 * scale, y, 50.0 * scale, 10.0 * scale, "kill"))
            Admin::AdminKillPlayerClientside(playerId);

        y += 20.0 * scale;

        /* ALLOW JOIN */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAllow join");
            
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetFont("SmallFont");

        y += 20.0 * scale;
        
        if (DrawClickableText(--_drawnHudId, x, y, 30.0 * scale, 10.0 * scale, "enable"))
            Admin::AdminSetPlayerAllowJoinClientSide(playerId, true);
        
        if (DrawClickableText(--_drawnHudId, (x + 60.0), y, 40.0 * scale, 10.0 * scale, "disable"))
            Admin::AdminSetPlayerAllowJoinClientSide(playerId, false);

        y += 20.0 * scale;
            
        /* LIST OF POWERS */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudDrawText(--_drawnHudId, "\cfPowers");

        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawPowerSelectors(x, y, scale, InvokeIncrementPowerOnSelectedPlayer);
        
        y += 20.0 * scale;

        /* ARMOR */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAdd armor");

        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawArmorIncrementSelectors(x, y, scale, InvokeArmorIncrementOnSelectedPlayer);

        y += 20.0 * scale;

        /* REWARD CONTAINERS */

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive containers");
        
        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardContainerSelectors(x, y, scale, InvokeContainerOnSelectedPlayer);
        
        // Resets y and moves x
        y = rowY - 100.0;
        x += 200.0 * scale;

        /* ITEMS */
        
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive items");
        
        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawItemSelectors(x, y, scale, InvokeIncrementItemOnSelectedPlayer);
        
        // Resets y and moves x
        y = rowY - 100.0;
        x += 300.0 * scale;

        /* REWARDS */
        
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive rewards");
        
        y += 20.0 * scale;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardSelectors(x, y, scale, InvokeGiveRewardOnSelectedPlayer);
        
        y += 20.0 * scale;
    }

    internal void InvokeIncrementItemOnSelectedPlayer(int index, int amount)
    {
        Admin::AdminIncrementPlayerItemClientside(_menuPlayerTargetId, index, amount);
    }

    internal void InvokeGiveRewardOnSelectedPlayer(int index)
    {
        Admin::AdminGivePlayerRewardClientside(_menuPlayerTargetId, index);
    }

    internal void InvokeIncrementPowerOnSelectedPlayer(int index, int amount)
    {
        Admin::AdminIncrementPlayerPowerClientside(_menuPlayerTargetId, index, amount);
    }

    internal void InvokeArmorIncrementOnSelectedPlayer(int amount)
    {
        Admin::AdminIncrementPlayerArmorClientSide(_menuPlayerTargetId, amount);
    }

    internal void InvokeContainerOnSelectedPlayer(Reward::RewardItemTypeFlagsT type)
    {
        Admin::AdminGiveRewardContainerPlayerClientSide(_menuPlayerTargetId, type);
    }

    // TODO: Should split this by category maybe.
    internal void DrawItemSelectors(fixed x, fixed y, fixed scale, void function(int, int)& invoker)
    {
        for (int i = 0; i < Item::GetItemCollectionSize(); ++i)
        {
            // This will always exist as it is required.
            str label = Item::GetItemLabel(i);
            if (label == (raw)0 || label == "")
                label = Item::GetItemName(i);

            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudSetPoint(x, y + fixed(10 * i) * scale);
            BCSUtils::HudDrawText(--_drawnHudId, label);

            if (DrawClickableText(--_drawnHudId, x + 200.0, y + fixed(10 * i) * scale, 40.0 * scale, 10.0 * scale, "give"))
                invoker(i, 1);

            if (DrawClickableText(--_drawnHudId, x + 240.0, y + fixed(10 * i) * scale, 40.0 * scale, 10.0 * scale, "take"))
                invoker(i, -1);
        }
    }

    internal void DrawRewardSelectors(fixed x, fixed y, fixed scale, void function(int)& invoker)
    {
        for (int i = 0; i < Reward::GetRewardCollectionSize(); ++i)
        {
            // This will always exist as it is required.
            str name = Reward::GetRewardName(i);

            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudSetPoint(x, y + fixed(10 * i) * scale);
            BCSUtils::HudDrawText(--_drawnHudId, name);

            if (DrawClickableText(--_drawnHudId, x, y + fixed(10 * i) * scale, 140.0 * scale, 10.0 * scale, name))
                invoker(i);
        }
    }

    internal void DrawPowerSelectors(fixed x, fixed y, fixed scale, void function(int, int)& invoker)
    {
        int offset = 0;
        for (int i = 0; i < Power::GetPowerSize(); ++i)
        {
            Power::PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[i];

            // For now we are skipping powers with no max length since they are usually something special.
            // They make no sense to provide.
            if (context.MaxTics == BCSUtils::INT_MAX)
                continue;
            
            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudSetPoint(x, y + fixed(10 * offset) * scale);
            BCSUtils::HudDrawText(--_drawnHudId, Power::GetPowerIndexAsString(i));

            // TODO: Support more increments, possibly even the ability to decrement.
            if (DrawClickableText(--_drawnHudId, x + 100.0, y + fixed(10 * offset) * scale, 20.0 * scale, 10.0 * scale, "+5s"))
                invoker(i, 35 * 5);

            offset++;
        }
    }

    internal void DrawArmorIncrementSelectors(fixed x, fixed y, fixed scale, void function(int)& invoker)
    {
        // Increment / decrement
        if (DrawClickableText(--_drawnHudId, x, y * scale, 30.0 * scale, 10.0 * scale, "-50"))
            invoker(-50);

        if (DrawClickableText(--_drawnHudId, x + 30.0 * scale, y * scale, 30.0 * scale, 10.0 * scale, "-10"))
            invoker(-10);

        if (DrawClickableText(--_drawnHudId, x + 60.0 * scale, y * scale, 30.0 * scale, 10.0 * scale, "-1"))
            invoker(-1);

        if (DrawClickableText(--_drawnHudId, x + 90.0 * scale, y * scale, 30.0 * scale, 10.0 * scale, "+1"))
            invoker(1);

        if (DrawClickableText(--_drawnHudId, x + 120.0 * scale, y * scale, 30.0 * scale, 10.0 * scale, "+10"))
            invoker(10);

        if (DrawClickableText(--_drawnHudId, x + 150.0 * scale, y * scale, 30.0 * scale, 10.0 * scale, "+50"))
            invoker(50);
    }

    internal void DrawRewardContainerSelectors(fixed x, fixed y, fixed scale, void function(Reward::RewardItemTypeFlagsT)& invoker)
    {
        for (int j = 0; j < REWARD_CONTAINER_COUNT; ++j)
        {
            fixed buttonX = x + fixed(100 * (j % 2)) * scale;
            fixed buttonY = y + fixed(10 * (j / 2)) * scale;

            Reward::RewardItemTypeFlagsT type = Reward::GetRewardItemTypeByIndex(j + 1);
            str buttonName = Reward::ContainerTypeToShortReadableString(type);
            if (DrawClickableText(--_drawnHudId, buttonX, buttonY, 100.0 * scale, 10.0 * scale, buttonName))
                invoker(type);
        }
    }
}