#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace RoundTimer
{
    // No support for pregame or other states yet.

    /*int GetPregameTicsElapsed()
    {
        // We don't have anything for this yet. Technically this is also Timer().
    }

    int GetPregameTicsLeft()
    {
        return GetTimerTicsLeft(GetIndexOfKnownType(TIMERCOUNTDOWN));
    }*/

    int GetPlayingTicsElapsed()
    {
        return Timer() - ZH2Game::GameContext.MatchStartTic;
    }

    int GetPlayingTicsLeft()
    {
        return GetTimerTicsLeft(GetIndexOfKnownType(TIMERPLAYING));
    }

    int GetEndingTicsElapsed()
    {
        return Timer() - ZH2Game::GameContext.MatchEndingTic;
    }

    int GetEndingTicsLeft()
    {
        return GetTimerTicsLeft(GetIndexOfKnownType(TIMERENDING));
    }
}