#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "RoundTimer"

#include "extern.acs"
#include "state.acs"

strict namespace RoundTimer
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for round timers.");

        // TODO: play timer should be scalable.
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERPREGAMECOUNTDOWN, 10, 30, RoundTimer::TIMERDRAWDECIMALS, "Game is starting in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERCOUNTDOWN, 30, 30, RoundTimer::TIMERDRAWDECIMALS, "Picking a zombie in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERPLAYING, 60, 180, RoundTimer::TIMERDOCOUNTDOWN, "Time left");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERENDING, 10, 10, RoundTimer::TIMERDRAWDECIMALS);
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERENDINGWITHRESTART, 5, 5, RoundTimer::TIMERDRAWDECIMALS, "Restarting...");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTING, 20, 20, RoundTimer::TIMERDRAWDECIMALS); // TODO: RoundTimer::TIMERHIDDEN
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTED, 5, 5, RoundTimer::TIMERDRAWDECIMALS, "Moving to next map...");
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for round timers.");

        RoundTimer::DefineKnownTimer(RoundTimer::TIMERPREGAMECOUNTDOWN, 10, 30, RoundTimer::TIMERDRAWDECIMALS, "Game is starting in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERCOUNTDOWN, 10, 30, RoundTimer::TIMERDRAWDECIMALS, "Picking a zombie in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERENDING, 10, 10, RoundTimer::TIMERDRAWDECIMALS);
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERENDINGWITHRESTART, 5, 5, RoundTimer::TIMERDRAWDECIMALS, "Restarting...");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTING, 20, 20, RoundTimer::TIMERDRAWDECIMALS); // TODO: RoundTimer::TIMERHIDDEN
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTED, 5, 5, RoundTimer::TIMERDRAWDECIMALS, "Moving to next map...");
    }

    // NOTE: Commented and unused until we get to allocating these again.
    // internal void Initialize()
    // {
    //     static RoundTimer::RoundTimerContextT lengthdef;
    //     ZH2Game::GameContext.Timers = BCS::ArrNew(5, lengthof(lengthdef));
    // }

    internal void TicServer()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        int index = GetActiveTimerIndex();
        int timeLeft = GetTimerTicsLeft(index);
        if (GetTimerDefined(index) && GetTimerActive(index) && timeLeft == 0)
        {
            StopTimer(index);
            Event::SendTimerElapsed(index);
        }
    }

    internal void TicClient()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        // Countdown timer.
        // The actual end sound is not tied to the timer, but rather plays when the play round ends from the server.
        int index = GetActiveTimerIndex();
        if (GetTimerDefined(index) && GetTimerActive(index) && GetTimerDoCountdown(index))
        {
            int timeLeft = GetTimerTicsLeft(index);
            if (timeLeft <= 350 && timeLeft > 0 && timeLeft % 35 == 0)
                AmbientSound("world/TIMERONE", 100);
        }
    }

    // Called from the server to indicate the round ended.
    // Note: This is mainly separated because online the timer might switch before reaching zero on the client. This works around the sound not calling.
    internal void CallEndSound()
    {
        AmbientSound("world/TIMEREND", 100);
    }
}

#undef LOGSOURCE
