#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawSprintBar()
    {
        // Draw the sprint bar if human, and if we are not at the maximum.
        if (!Player::GetIsHuman())
            return;

        int left = Player::GetSprintLeft();
        if (left == SPRINT_ITEM_MAX)
            return;

        int id = HUDID_SPRINTBAR;

        HudSetPointInternal();
        BCSUtils::HudDrawImage(--id, BAR_SPRINT_NAME);

        fixed percentage = fixed(left) / fixed(SPRINT_ITEM_MAX);
        fixed clipX = BCSUtils::Round(fixed(BAR_SPRINT_WIDTH) * percentage);

        //BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
        BCSUtils::HudSetClipRect(fixed(-BAR_SPRINT_WIDTH / 2), fixed(-BAR_SPRINT_HEIGHT), clipX, fixed(BAR_SPRINT_HEIGHT));
        BCSUtils::HudDrawImage(--id, BAR_SPRINT_METER_NAME);
        BCSUtils::HudRemoveClipRect();
        BCSUtils::HudSetAlpha(1.0);

        DebugDraw();
    }

    internal void DrawAirSupplyBar()
    {
        // Note also that because zombies have no air supply, the bar will show empty even though they will never drown.
        if (!Player::GetIsHuman())
            return;

        int airSupply = GetAirSupply(ConsolePlayerNumber());
        if (airSupply == MAX_AIRSUPPLY)
            return;

        int id = HUDID_AIRBAR;

        HudSetPointInternal();
        BCSUtils::HudDrawImage(--id, BAR_AIRSUPPLY_NAME);

        fixed percentage = fixed(airSupply) / fixed(MAX_AIRSUPPLY);
        fixed clipX = BCSUtils::Round(fixed(BAR_AIRSUPPLY_WIDTH) * percentage);

        //BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
        BCSUtils::HudSetClipRect(fixed(-BAR_AIRSUPPLY_WIDTH / 2), fixed(-BAR_AIRSUPPLY_HEIGHT), clipX, fixed(BAR_AIRSUPPLY_HEIGHT));
        BCSUtils::HudDrawImage(--id, BAR_AIRSUPPLY_METER_NAME);
        BCSUtils::HudRemoveClipRect();
        BCSUtils::HudSetAlpha(1.0);

        DebugDraw();
    }

    internal void DrawAfkBar()
    {
        Round::KnownRoundStateT roundState = Round::GetActiveKnownRoundState();
        if (roundState != Round::STATECOUNTDOWN && roundState != Round::STATEPLAYING)
            return;

        // The bar requires the player to either have no moved, or have a warning he is going to get kicked.
        // Priority is on having moved at round start.
        int max, tics;
        if (!AfkPrevention::GetHasMovedThisRound())
        {
            max = ZH2Game::GetAfkMoveAtRoundStartBeforeSeconds() * 35;
            tics = AfkPrevention::GetTicsUntilRoundStartKick();
        }
        else if (AfkPrevention::GetHasAfkWarn())
        {
            max = ZH2Game::GetAfkZombieMoveWarnSeconds() * 35;
            tics = AfkPrevention::GetZombieWarnTicsLeft();
        }
        else
            return;

        if (max == 0)
            return;

        int id = HUDID_AFKBAR;

        HudSetPointInternal();
        BCSUtils::HudDrawImage(--id, BAR_AFKPREVENTION_NAME);

        fixed percentage = fixed(tics) / fixed(max);
        fixed clipX = BCSUtils::Round(fixed(BAR_AFKPREVENTION_WIDTH) * percentage);

        //BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
        BCSUtils::HudSetClipRect(fixed(-BAR_AFKPREVENTION_WIDTH / 2), fixed(-BAR_AFKPREVENTION_HEIGHT), clipX, fixed(BAR_AFKPREVENTION_HEIGHT));
        BCSUtils::HudDrawImage(--id, BAR_AFKPREVENTION_METER_NAME);
        BCSUtils::HudRemoveClipRect();
        DebugDraw();

        BCSUtils::HudSetAlpha(1.0);

        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetStayTime(0.0);
        BCSUtils::HudSetDisappearTime(1.0);

        HudSetPointInternal(0.0, 10.0);
        BCSUtils::HudDrawText(--id, "Move to avoid getting kicked for inactivity");

        DebugDraw();
    }
}