#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "game.acs"
#include "player.acs"
#include "timer.acs"

strict namespace Hud
{
    internal void DrawHudDefault()
    {
        // Alongside checking individual categories, this boolean indicates if we draw the hud as a whole.
        bool drawHud = ZH2Game::GetDrawHud();

        if (drawHud && ZH2Game::GetDrawRoundHud())
            DrawTimerDefault();

        // All of this is strictly during the playing game.
        if (Round::GetActiveKnownRoundState() < Round::STATEENDING)
        {
            if (_clientCameraOnBody && drawHud)
                DrawPlayerHud();

            if (drawHud && ZH2Game::GetDrawGameHud())
                DrawGameHud();
        }
    }
}
