#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "status.acs"
#include "bar.acs"

strict namespace Hud
{
    internal void DrawPlayerHud()
    {
        if (!BCSUtils::ActorIsAlive(ActivatorTid()))
            return;

        if (ZH2Game::GetDrawPlayerBarsHud())
            DrawBarHud();

        if (ZH2Game::GetDrawPlayerStatusHud())
            DrawPlayerStatusHud();
    }
}