#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    #define PLAYERID_KEYROWCOUNT 5

    internal void DrawPlayerBackground()
    {
        HudSetPointInternal();
        BCSUtils::HudDrawImage(--_drawnHudId, "HUDBACK");
        DebugDraw();

        HudSetPointInternal(90.0, -40.0);
        BCSUtils::HudDrawImage(--_drawnHudId, "HUDIBACK");
        DebugDraw();
    }

    // TODO: Should come from a parsed lump.
    internal void DrawPlayerSkin()
    {
        str skinIcon = (raw)0;
        switch (GetSharedState().PlayerSkin)
        {
            case SKINTYPE_HUMAN_GRENADE: skinIcon = PLAYER_HUD_SKIN_FIREGRENADE; break;
            case SKINTYPE_HUMAN_HANDGUN: skinIcon = PLAYER_HUD_SKIN_HANDGUN; break;
            case SKINTYPE_HUMAN_JACKSGUN: skinIcon = PLAYER_HUD_SKIN_JACKSGUN; break;
            case SKINTYPE_HUMAN_SHOTGUN: skinIcon = PLAYER_HUD_SKIN_SHOTGUN; break;
            case SKINTYPE_HUMAN_DOUBLEBARRELEDSHOTGUN: skinIcon = PLAYER_HUD_SKIN_DOUBLESHOTGUN; break;
            case SKINTYPE_HUMAN_CHAINGUN: skinIcon = PLAYER_HUD_SKIN_CHAINGUN; break;
            case SKINTYPE_HUMAN_SNIPER: skinIcon = PLAYER_HUD_SKIN_SNIPER; break;
            case SKINTYPE_HUMAN_RIOTGUN: skinIcon = PLAYER_HUD_SKIN_RIOTGUN; break;
            case SKINTYPE_ZOMBIEOLD: skinIcon = PLAYER_HUD_SKIN_OLDZOMBIE; break;
            case SKINTYPE_ZOMBIEREGULAR: skinIcon = PLAYER_HUD_SKIN_REGULARZOMBIE; break;
            case SKINTYPE_ZOMBIEINITIAL: skinIcon = PLAYER_HUD_SKIN_INITIALZOMBIE; break;
        }

        if (skinIcon == (raw)0)
            return;

        HudSetPointInternal();
        BCSUtils::HudDrawImage(--_drawnHudId, skinIcon);
    }

    internal void DrawKevlarArmor()
    {
        if (!GetSharedState().DrawKevlarArmor)
            return;

        int armount = Player::GetKevlarPoints();

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_BLUE);
        BCSUtils::HudSetCenterText(true);

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, str(armount));
        DebugDraw();
    }

    internal int DrawHealth()
    {
        // Also flicker health based on current health.
        int health = BCSUtils::Max(0, PlayerHealth());
        bool flicker = health <= (Player::GetIsZombie() ? HEALTH_ZOMBIECRITICAL : HEALTH_HUMANCRITICAL);
        if (!flicker || (flicker && Timer() % 50 < 25))
        {
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(flicker ? CR_RED : CR_WHITE);


            HudSetPointInternal();
            BCSUtils::HudDrawText(--_drawnHudId, str(health));
            DebugDraw();
        }

        return _drawnHudId;
    }

    internal void DrawCurrentOwnedItem()
    {
        if (!GetSharedState().DrawCurrentOwnedItem)
            return;

        int index = Item::GetInventoryIndex(Item::GetClientOwnedInventoryIndex(Item::_currentInventoryIndex));
        str graphic = Item::GetItemGraphic(index);
        str name = Item::GetItemName(index);
        int inventoryCount = CheckInventory(name);


        HudSetPointInternal();
        BCSUtils::HudDrawImage(--_drawnHudId, graphic);
        DebugDraw();

        // Draw the current count of the item if we have more than one.
        if (inventoryCount > 1)
        {
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(CR_YELLOW);

            HudSetPointInternal(20.0, -10.0);
            BCSUtils::HudDrawText(--_drawnHudId, str(inventoryCount));
            DebugDraw();
        }
    }

    internal void DrawCalculatedFactors()
    {
        // TODO: Make configurable from lumps
        static str factorGraphics[] = { "FSPEED", "FJUMP", "FDAMFACT", "FDAMMULT", "FKNOCKBK" };
        static int factorColors[] = { CR_WHITE, CR_WHITE, CR_RED, CR_WHITE, CR_WHITE };

        fixed offsetY = 0.0;
        for (int i = 0; i < MAX_POWER_TYPES; ++i)
        {
            if (!GetSharedState().DrawCalculatedFactorByIndex[i])
                continue;

            fixed factor = Power::GetPlayerCalculatedPowerFactor(ConsolePlayerNumber(), i);
            fixed defaultFactor = Power::GetPlayerPowerFactorDefaultValue(ConsolePlayerNumber(), i);

            BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

            HudSetPointInternal(0.0, offsetY);
            BCSUtils::HudDrawImage(--_drawnHudId, factorGraphics[i]);
            DebugDraw();

            // Prefixed "x" symbol.
            // TODO: Can this turn smaller?
            BCSUtils::HudSetTextColor(factorColors[i]);
            HudSetPointInternal(12.0, offsetY);
            BCSUtils::HudDrawText(--_drawnHudId, "x");
            DebugDraw();

            // Calculate the actual difference.
            // This improves how factors like jump (default 8.0) are drawn, should they be doubled (show 2.0 instead of 16.0)
            fixed adjustedFactor = factor / defaultFactor;

            // Only a single decimal is shown.
            str formattedFactor = Utils::FormatDecimals(adjustedFactor, 1);

            // Factor (also using the color as above).
            BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_CENTER);
            HudSetPointInternal(17.0, offsetY);
            BCSUtils::HudDrawText(--_drawnHudId, formattedFactor);
            DebugDraw();

            offsetY -= 15.0;
        }

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_BOTTOM);
    }

    internal void DrawZombieTeleportsLeft()
    {
        if (!GetSharedState().DrawZombieTeleportsLeft)
            return;

        str graphic = (raw)0;
        switch (GetSharedState().ZombieTeleportSkin)
        {
            case ZTELESKIN_OLD: graphic = HUD_ZTELE_ZOMBIEOLD; break;
            case ZTELESKIN_REGULAR: graphic = HUD_ZTELE_ZOMBIEREGULAR; break;
            case ZTELESKIN_INITIAL: graphic = HUD_ZTELE_ZOMBIEINITIAL; break;
        }

        int left = Game::GetZombieTeleportsLeft();

        HudSetPointInternal();
        BCSUtils::HudDrawImage(--_drawnHudId, graphic);
        DebugDraw();

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetAlpha(0.8);

        HudSetPointInternal(5.0, -3.0);
        BCSUtils::HudDrawText(--_drawnHudId, str(left));
        DebugDraw();

        BCSUtils::HudSetAlpha(1.0);
    }

    internal void DrawHudStates()
    {
        static str graphics[MAX_HUD_STATES] = { "ST_SAFE", "ST_CAFF", "ST_DAMFC", "ST_JUMP", "ST_SPEED", "ST_PANIC", "ST_CURE", "ST_HINV", "ST_UNSOL", "ST_SR50" };

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        int offset = 0;
        for (int i = 0; i < MAX_HUD_STATES; ++i)
        {
            if (!GetSharedState().DrawHudStateByIndex[i])
                continue;

            fixed angleDeg = 180.0 + fixed(offset) * HUD_STATES_ANGLE;
            fixed angle    = angleDeg / 360.0;

            fixed x = Cos(angle) * HUD_STATES_RADIUS;
            fixed y = Sin(angle) * HUD_STATES_RADIUS;

            HudSetPointInternal(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, graphics[i]);
            DebugDraw();

            offset++;
        }

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_BOTTOM);
    }

    internal void DrawKeyList()
    {
        if (!GetSharedState().DrawKeyList)
            return;

        int keyCount = Item::GetClientOwnedKeySize();

        // Start more left as we have more keys
        fixed adjustX = 10.0 * fixed(keyCount / (PLAYERID_KEYROWCOUNT + 1));

        for (int i = 0; i < keyCount; ++i)
        {
            fixed addX = 15.0 * fixed(i / PLAYERID_KEYROWCOUNT) - adjustX;
            fixed addY = 10.0 * fixed(i % PLAYERID_KEYROWCOUNT);
            int itemIndex = Item::GetKeyIndex(Item::GetClientOwnedKeyIndex(i));

            HudSetPointInternal(addX, addY);
            BCSUtils::HudDrawImage(--_drawnHudId, Item::GetItemGraphic(itemIndex));
        }
    }

    internal void DrawWeaponBackground()
    {
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_CENTER);

        if (GetSharedState().DrawSecondaryWeaponBackground)
        {
            HudSetPointInternal(20.0, 8.0);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDSBACK");
            DebugDraw();
        }

        if (GetSharedState().DrawPrimaryWeaponBackground)
        {
            HudSetPointInternal();
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDPBACK");
            DebugDraw();
        }
    }

    internal void DrawWeaponIcon()
    {
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_CENTER);

        str weaponIcon = "";
        if      (CheckWeapon(WEAPON_SHOTGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_SHOTGUN + str(CheckInventory(WEAPON_AMMO_SHOTGUN_NAME));
        else if (CheckWeapon(WEAPON_DOUBLESHOTGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_SUPERSHOTGUN  + str(CheckInventory(WEAPON_AMMO_DOUBLESHOTGUN_NAME));
        else if (CheckWeapon(WEAPON_SNIPER_NAME)) weaponIcon = WEAPON_HUD_SKIN_SNIPER + str(1 - CheckInventory(WEAPON_SNIPER_SHOULDEJECTCASE_NAME));
        else if (CheckWeapon(WEAPON_JACKSGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_JACKS + str(CheckInventory(WEAPON_AMMO_JACKSGUN_NAME));
        else if (CheckWeapon(WEAPON_HANDGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_PISTOL;
        else if (CheckWeapon(WEAPON_RIOTGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_RIOTGUN + str(CheckInventory(WEAPON_AMMO_RIOTGUN_CURRENT_NAME));

        if (weaponIcon != "")
        {
            HudSetPointInternal();
            BCSUtils::HudDrawImage(--_drawnHudId, weaponIcon);
            DebugDraw();
        }

        // Special logic for the chaingun and fire grenade, which have two graphics and some clipping.
        if (CheckWeapon(WEAPON_CHAINGUN_NAME))
        {
            HudSetPointInternal();
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_CHAINGUN);

            fixed percentage = fixed(CheckInventory(WEAPON_CHAINGUN_HEAT_NAME)) / fixed(WEAPON_CHAINGUN_MAX_HEAT);
            fixed clipX = BCSUtils::Round(fixed(WEAPON_CHAINGUN_METER_WIDTH) * percentage);


            BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
            BCSUtils::HudSetClipRect(fixed(-WEAPON_CHAINGUN_METER_WIDTH), fixed(-WEAPON_CHAINGUN_METER_HEIGHT) / 2.0, clipX, fixed(WEAPON_CHAINGUN_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_CHAINGUN_METER);
            BCSUtils::HudRemoveClipRect();
            BCSUtils::HudSetAlpha(1.0);

            DebugDraw();
        }
        else if (CheckWeapon(WEAPON_FIREGRENADE_NAME))
        {
            HudSetPointInternal();
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_FIREGRENADE);

            fixed percentage = fixed(CheckInventory(WEAPON_FIREGRENADE_THROWPOWER_NAME)) / fixed(WEAPON_FIREGRENADE_MAX_THROWPOWER);
            fixed clipX = BCSUtils::Round(fixed(WEAPON_FIREGRENADE_METER_WIDTH) * percentage);

            BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
            BCSUtils::HudSetClipRect(fixed(-WEAPON_FIREGRENADE_METER_WIDTH), fixed(-WEAPON_FIREGRENADE_METER_HEIGHT) / 2.0, clipX, fixed(WEAPON_FIREGRENADE_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_FIREGRENADE_METER);
            BCSUtils::HudRemoveClipRect();
            BCSUtils::HudSetAlpha(1.0);

            DebugDraw();
        }

        // The riotgun draws an extra indicator for how many canisters it has left.
        // This is a division of the total based on what fits in the gun.
        else if (CheckWeapon(WEAPON_RIOTGUN_NAME))
        {
            HudSetPointInternal(50.0, 8.0);
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_RIOTGUN_CLIP);
            DebugDraw();

            HudSetPointInternal(44.0, 8.0);
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudDrawText(--_drawnHudId, str(CheckInventory(WEAPON_AMMO_RIOTGUN_TOTAL_NAME)));
        }
    }

    internal void DrawZombieAbilities()
    {
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_BOTTOM);

        if (!GetSharedState().DrawZombieAbilities)
            return;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetCenterText(true);

        // The vertical offset goes down with each ability.
        fixed y = 0.0;

        for (int i = ABILITY_COUNT - 1; i >= 0; --i)
        {
            if (!GetSharedState().DrawZombieAbilityByIndex[i])
                continue;

            bool selected = Game::GetSelectedAbilityIndex() == i;

            int maxTics = Game::GetZombieAbilityCooldownMaxTicsByIndex(i);
            int tics = Game::GetZombieAbilityCooldownTicsLeftByIndex(i);

            // Visual indication of the ability not being ready.
            BCSUtils::HudSetAlpha(!selected && tics > 0 ? 0.4 : 1.0);

            HudSetPointInternal(0.0, y);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUD_ZA" + str(i) + str(1));

            // Visualize the time left before this ability can be used.
            int graphicIndex = selected ? 3 : 2;
            fixed percentage = BCSUtils::Clamp(fixed(tics) / fixed(maxTics), 0.0, 1.0);
            fixed clipY = fixed(HUD_ZOMBIEABILITY_METER_HEIGHT) - BCSUtils::Round(fixed(HUD_ZOMBIEABILITY_METER_HEIGHT) * percentage);

            BCSUtils::HudSetClipRect(fixed(-HUD_ZOMBIEABILITY_METER_WIDTH), -clipY, fixed(HUD_ZOMBIEABILITY_METER_WIDTH), fixed(HUD_ZOMBIEABILITY_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, "HUD_ZA" + str(i) + str(graphicIndex));
            BCSUtils::HudRemoveClipRect();

            DebugDraw();

            // Show possible cooldown if selected
            if (selected && tics > 0)
            {
                BCSUtils::HudSetAlpha(1.0);
                str label = Utils::FormatTics(tics, true);

                HudSetPointInternal(-20.0, y - 10.0);
                BCSUtils::HudDrawText(--_drawnHudId, str(label));
            }

            y -= 60.0;
        }
    }
}