#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawWeaponBackground(fixed x, fixed y)
    {
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_CENTER);

        if (GetSharedState().DrawSecondaryWeaponBackground)
        {
            BCSUtils::HudSetPoint(x + 20.0, y + 8.0);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDSBACK");
            DebugDraw();
        }

        if (GetSharedState().DrawPrimaryWeaponBackground)
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUDPBACK");
            DebugDraw();
        }
    }

    internal void DrawWeaponIcon(fixed x, fixed y)
    {
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_CENTER);

        str weaponIcon = "";
        if      (Weapon::CheckWieldedShotgun()) weaponIcon = DEFAULT_WEAPON_HUD_SKIN_SHOTGUN + str(CheckInventory(WEAPON_AMMO_SHOTGUN_NAME));
        else if (Weapon::CheckWieldedDoubleShotgun()) weaponIcon = DEFAULT_WEAPON_HUD_SKIN_SUPERSHOTGUN  + str(CheckInventory(WEAPON_AMMO_DOUBLESHOTGUN_NAME));
        else if (Weapon::CheckWieldedSniper()) weaponIcon = DEFAULT_WEAPON_HUD_SKIN_SNIPER + str(1 - CheckInventory(WEAPON_SNIPER_SHOULDEJECTCASE_NAME));
        else if (Weapon::CheckWieldedJacksGun()) weaponIcon = DEFAULT_WEAPON_HUD_SKIN_JACKS + str(CheckInventory(WEAPON_AMMO_JACKSGUN_NAME));
        else if (Weapon::CheckWieldedHandgun()) weaponIcon = DEFAULT_WEAPON_HUD_SKIN_PISTOL;
        else if (Weapon::CheckWieldedRiotGun()) weaponIcon = DEFAULT_WEAPON_HUD_SKIN_RIOTGUN + str(CheckInventory(WEAPON_AMMO_RIOTGUN_CURRENT_NAME));

        if (weaponIcon != "")
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, weaponIcon);
            DebugDraw();
        }

        // Special logic for the chaingun and fire grenade, which have two graphics and some clipping.
        if (Weapon::CheckWieldedChaingun())
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, DEFAULT_WEAPON_HUD_SKIN_CHAINGUN);

            fixed percentage = fixed(CheckInventory(WEAPON_CHAINGUN_HEAT_NAME)) / fixed(WEAPON_CHAINGUN_MAX_HEAT);
            fixed clipX = BCSUtils::Round(fixed(DEFAULT_WEAPON_CHAINGUN_METER_WIDTH) * percentage);

            BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
            BCSUtils::HudSetClipRect(fixed(-DEFAULT_WEAPON_CHAINGUN_METER_WIDTH), fixed(-DEFAULT_WEAPON_CHAINGUN_METER_HEIGHT) / 2.0, clipX, fixed(DEFAULT_WEAPON_CHAINGUN_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, DEFAULT_WEAPON_HUD_SKIN_CHAINGUN_METER);
            BCSUtils::HudRemoveClipRect();
            BCSUtils::HudSetAlpha(1.0);

            DebugDraw();
        }
        else if (Weapon::CheckWieldedFireGrenade())
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, DEFAULT_WEAPON_HUD_SKIN_FIREGRENADE);

            fixed percentage = fixed(CheckInventory(WEAPON_FIREGRENADE_THROWPOWER_NAME)) / fixed(WEAPON_FIREGRENADE_MAX_THROWPOWER);
            fixed clipX = BCSUtils::Round(fixed(DEFAULT_WEAPON_FIREGRENADE_METER_WIDTH) * percentage);

            BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
            BCSUtils::HudSetClipRect(fixed(-DEFAULT_WEAPON_FIREGRENADE_METER_WIDTH), fixed(-DEFAULT_WEAPON_FIREGRENADE_METER_HEIGHT) / 2.0, clipX, fixed(DEFAULT_WEAPON_FIREGRENADE_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, DEFAULT_WEAPON_HUD_SKIN_FIREGRENADE_METER);
            BCSUtils::HudRemoveClipRect();
            BCSUtils::HudSetAlpha(1.0);

            DebugDraw();
        }

        // The riotgun draws an extra indicator for how many canisters it has left.
        // This is a division of the total based on what fits in the gun.
        else if (Weapon::CheckWieldedRiotGun())
        {
            BCSUtils::HudSetPoint(x + 50.0, y + 8.0);
            BCSUtils::HudDrawImage(--_drawnHudId, DEFAULT_WEAPON_HUD_SKIN_RIOTGUN_CLIP);
            DebugDraw();

            BCSUtils::HudSetPoint(x + 44.0, y + 8.0);
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(CR_WHITE);
            BCSUtils::HudDrawText(--_drawnHudId, str(CheckInventory(WEAPON_AMMO_RIOTGUN_TOTAL_NAME)));
        }
    }
}
