#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace DamageFeedback
{
    // Constant defines the spacing of numbers between eachother.
    #define DAMAGE_NUMBER_DIGIT_SPACING_BASE 10.0

    // Constants define the general values to determine how gravity, velocity and scale is handled.
    // The cap is the highest number we assume before the value is using the max value of the constants below.
    #define DAMAGE_NUMBER_DAMAGE_CAP 300
    #define DAMAGE_NUMBER_VELOCITY_Z_MIN 0.3
    #define DAMAGE_NUMBER_VELOCITY_Z_MAX 2.0

    #define DAMAGE_NUMBER_GRAVITY_MIN 0.02
    #define DAMAGE_NUMBER_GRAVITY_MAX 0.08

    #define DAMAGE_NUMBER_SCALE_MIN 0.30
    #define DAMAGE_NUMBER_SCALE_MAX 0.60

    internal void UpdateDamageNumbers()
    {
        for (int i = 0; i < MAX_DAMAGE_NUMBERS; ++i)
        {
            DamageFeedbackNumberInfoT& numberInfo = GetDamageNumberInfo(i);
            if (!numberInfo.Set)
                continue;

            // Read the scale of the first digit and determine the spacing.
            fixed scale = GetActorProperty(numberInfo.Tid + 1, APROP_SCALEX);
            fixed spacing = DAMAGE_NUMBER_DIGIT_SPACING_BASE * scale;

            // Position the numbers in a way so they will always be centered relative to the master actor.
            fixed baseY = (fixed(numberInfo.NumberCount - 1) * spacing) / 2.0;

            for (int j = 0; j < numberInfo.NumberCount; ++j)
            {
                int digitTid = numberInfo.Tid + 1 + j;

                fixed offsetY = baseY - (fixed(j) * spacing);

                SetActivator(digitTid);
                Warp(numberInfo.Tid, 0.0, offsetY, 0.0, 0.0, WARPF_NOCHECKPOSITION | WARPF_STOP);
            }
        }

        SetActivatorToPlayer(ConsolePlayerNumber());
    }

    internal void AddDamageNumberOnActor(int tid, int damage)
    {
        int numberCount = 1;
        int tmp = damage;

        // Let's assume we can't hit over 10 digits worth of damage for now.
        while (tmp >= 10 && numberCount < 10)
        {
            tmp /= 10;
            ++numberCount;
        }

        fixed x = GetActorX(tid) + Math::FRandom(-10.0, 10.0),
              y = GetActorY(tid) + Math::FRandom(-10.0, 10.0),
              z = GetActorZ(tid) + Math::FRandom( 56.0, 64.0);

        int masterTid = UniqueTid();
        SpawnForced("ZH2DamageNumberMaster", x, y, z, masterTid, 0);

        for (int i = 0; i < numberCount; ++i)
        {
            int digitTid = masterTid + 1 + i;

            SpawnForced("ZH2DamageNumber", x, y, z, digitTid, 0);

            int div = 1;
            int power = (numberCount - 1) - i;
            while (power-- > 0)
                div *= 10;

            int digitNumber = (damage / div) % 10;
            SetThingSpecial(digitTid, 0, digitNumber);
        }

        int cappedDamage = damage;
        if (cappedDamage > DAMAGE_NUMBER_DAMAGE_CAP)
            cappedDamage = DAMAGE_NUMBER_DAMAGE_CAP;

        fixed ratio = fixed(cappedDamage) / fixed(DAMAGE_NUMBER_DAMAGE_CAP);

        fixed velZ = DAMAGE_NUMBER_VELOCITY_Z_MAX - (ratio * (DAMAGE_NUMBER_VELOCITY_Z_MAX - DAMAGE_NUMBER_VELOCITY_Z_MIN));
        fixed grav = DAMAGE_NUMBER_GRAVITY_MAX - (ratio * (DAMAGE_NUMBER_GRAVITY_MAX - DAMAGE_NUMBER_GRAVITY_MIN));
        fixed scale = DAMAGE_NUMBER_SCALE_MIN + (ratio * (DAMAGE_NUMBER_SCALE_MAX - DAMAGE_NUMBER_SCALE_MIN));

        SetActorVelocity(masterTid, 0.0, 0.0, velZ, false, false);
        SetActorProperty(masterTid, APROP_GRAVITY, grav);

        // Apply scale to all digit actors
        for (int i = 0; i < numberCount; ++i)
        {
            int digitTid = masterTid + 1 + i;

            SetActorProperty(digitTid, APROP_SCALEX, scale);
            SetActorProperty(digitTid, APROP_SCALEY, scale);
        }

        SetNextDamageNumberInfo(masterTid, numberCount);
    }

    internal void SetNextDamageNumberInfo(int tid, int numberCount)
    {
        int index = GetDamageNumberIndex() + 1;
        index %= MAX_DAMAGE_NUMBERS;
        SetDamageNumberIndex(index);

        DamageFeedbackNumberInfoT& numberInfo = GetDamageNumberInfo(index);
        numberInfo.Set = true;
        numberInfo.SpawnTic = Timer();
        numberInfo.Tid = tid;
        numberInfo.NumberCount = numberCount;
    }

    internal void SetDamageNumberIndex(int index)
    {
        ZH2Game::GameContext.DamageFeedbackInfo.DamageNumberIndex = index;
    }

    internal int GetDamageNumberIndex()
    {
        return ZH2Game::GameContext.DamageFeedbackInfo.DamageNumberIndex;
    }

    internal DamageFeedbackNumberInfoT& GetDamageNumberInfo(int index)
    {
        return ZH2Game::GameContext.DamageFeedbackInfo.DamageNumbers[index];
    }
}
