#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// The absolute maximum number of damage numbers to show.
#define MAX_DAMAGE_NUMBERS 200

strict namespace DamageFeedback
{
    struct DamageFeedbackInfoT
    {
        // Indicates the tics when the last hit/kill happened.
        int HitFeedbackTic;
        int KillFeedbackTic;

        // Accumulating counter for damage and kills that get reset after enough time passes without an update.
        int DamageCount;
        int KillCount;

        DamageFeedbackNumberInfoT DamageNumbers[MAX_DAMAGE_NUMBERS];
        int DamageNumberIndex;
    };

    struct DamageFeedbackNumberInfoT
    {
        bool Set;
        int SpawnTic;
        int Tid;
        int NumberCount;
    };
}