#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace DamageFeedback
{
    struct DamageFeedbackInfoT
    {
        // Indicates the tics when the last hit/kill happened.
        int HitFeedbackTic;
        int KillFeedbackTic;

        // Accumulating counter for damage and kills that get reset after enough time passes without an update.
        int DamageCount;
        int KillCount;
    };
}