#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace IO
{

    // RELEVANT SCRIPT NAMES
    // These are called by the awaiter too, so we defined them here.
    #define SCRIPT_PARSE_PERSISTING_MAP_POSITION_DEFS "zh2_internal_parse_map_position_defs"
    #define SCRIPT_PARSE_CURRENT_MAP_DEFS "zh2_internal_parse_current_map_defs"
    #define SCRIPT_PARSE_PERSISTING_MOD_DEFS_SERVERSIDE "zh2_internal_parse_mod_defs_serverside"
    #define SCRIPT_PARSE_PERSISTING_MOD_DEFS_CLIENTSIDE "zh2_internal_parse_mod_defs_clientside"
    #define SCRIPT_PARSE_RADIO_DEF_LUMPS_CLIENTSIDE "zh2_internal_parse_radio_def_lumps_clientside"

    #define MOD_DEF_LUMP_NAME "zhmoddef"
    #define MAP_DEF_LUMP_NAME "zhmapdef"
    #define RADIO_DEF_LUMP_NAME "radiodef"

    #define HUMAN_START_ITEMS_KEY "humanstartitems"
    #define ZOMBIE_START_ITEMS_KEY "zombiestartitems"

    #define RESIST_PREFIX_KEY "resist"
    #define RESIST_DEFINITIONS_KEY "definitions"
    #define RESISTS_PREFIX_KEY "resists"
    #define RESIST_LENGTH_KEY "length"
    #define RESIST_TOP_REASON_LABEL_KEY "topreasonlabel"
    #define RESIST_TIME_REASON_LABEL_KEY "timereasonlabel"
    #define RESIST_PRE_RESIST_SCRIPT_KEY  "PreResistScript"
    #define RESIST_POST_RESIST_SCRIPT_KEY "PostResistScript"
    #define RESIST_GLOBAL_PRE_RESIST_SCRIPT_KEY  "GlobalPreResistScript"
    #define RESIST_GLOBAL_POST_RESIST_SCRIPT_KEY "GlobalPostResistScript"

    #define RESIST_FLAGS_KEY "Flags"
    #define RESIST_FLAG_HIDE_TOP_REASON_KEY "HideTopReason"
    #define RESIST_FLAG_HIDE_TIME_REASON_KEY "HideTimeReason"
    #define RESIST_FLAG_NO_FADE_KEY "NoFade"
    #define RESIST_FLAG_SHOW_WHEN_PAUSED_KEY "ShowWhenPaused"
    #define RESIST_FLAG_DONT_AWAIT_PRE_SCRIPT_KEY "DontAwaitPreScript"
    #define RESIST_FLAG_DONT_AWAIT_POST_SCRIPT_KEY "DontAwaitPostScript"

    #define EVENTS_PREFIX_KEY "events"
    #define RADIO_DEF_LUMP_RADIO_LIST_BLOCK_KEYWORD "radiolist"
    #define RADIO_DEF_LUMP_RADIO_LIST_TRACK_KEYWORD "track"

    /* MAP BASE DEFINITIONS */

    struct MapBaseCollectionT
    {
        // Indicates if the lumps have been parsed already.
        bool Initialized;

        IO::MapBaseDefT Collection[MAX_MAP_COUNT];
        int Count;
    };

    struct MapBaseDefT
    {
        str MapLump;
        int LumpIndex;
        int LumpStartOffset;
        int LumpEndOffset;

        Map::MapPropertiesT Properties;
    };

    /* MAP DETAILED DEFINITION */

    internal struct MapDetailedT
    {
        RoundTimer::RoundTimerContextT Timers[MAX_TIMERS];
        int ActiveRoundTimerIndex;

        Round::RoundStateContextT Rounds[MAX_ROUNDSTATES];
        int ActiveRoundStateIndex;

        Resist::ResistT Resists[MAX_RESISTS];

        // An offset applied to the general cycle resists use to determine the interval to show.
        // The interval ensures all fades match, but this offset is set by the first resist.
        // The first resist can then show instantly instead of waiting for the general cycle.
        int ResistFadeCycleOffsetTic;

        // Serverside map scripts invoked for every resist.
        str GlobalPreResistScript;
        str GlobalPostResistScript;

        // This is purely clientside so we know if the sync was for new resists, or if we edit them.
        bool ResistsInitialized;

        // If `true`, the map is configured to play a heartbeat ambient on the final human.
        // TODO: This could turn into an integer indicating the final n humans play a heartbeat.
        bool PlayFinalHumanHeartbeat;
    };
}