#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace IO
{

    // RELEVANT SCRIPT NAMES
    // These are called by the awaiter too, so we defined them here.
    #define SCRIPT_PARSE_PERSISTING_MAP_POSITION_DEFS "zh2_internal_parse_map_position_defs"
    #define SCRIPT_PARSE_CURRENT_MAP_DEFS "zh2_internal_parse_current_map_defs"
    #define SCRIPT_PARSE_PERSISTING_MOD_DEFS_SERVERSIDE "zh2_internal_parse_mod_defs_serverside"
    #define SCRIPT_PARSE_PERSISTING_MOD_DEFS_CLIENTSIDE "zh2_internal_parse_mod_defs_clientside"
    #define SCRIPT_PARSE_RADIO_DEF_LUMPS_CLIENTSIDE "zh2_internal_parse_radio_def_lumps_clientside"

    #define MODDEFLUMPNAME "zhmoddef"
    #define MAPDEFLUMPNAME "zhmapdef"
    #define RADIODEFLUMPNAME "radiodef"

    #define HUMANSTARTITEMSKEY "humanstartitems"
    #define ZOMBIESTARTITEMSKEY "zombiestartitems"

    #define RESISTSPREFIXKEY "resists"
    #define RESISTLENGTHKEY "length"
    #define RESISTTOPREASONLABELKEY "topreasonlabel"
    #define RESISTTIMEREASONLABELKEY "timereasonlabel"
    #define RESISTPRERESISTSCRIPTKEY  "PreResistScript"
    #define RESISTPOSTRESISTSCRIPTKEY "PostResistScript"

    #define RESISTFLAGSKEY "Flags"
    #define RESISTFLAGHIDETOPREASONKEY "HideTopReason"
    #define RESISTFLAGHIDETIMEREASONKEY "HideTimeReason"
    #define RESISTFLAGNOFADEKEY "NoFade"

    #define EVENTSPREFIXKEY "events"
    #define RADIODEFLUMP_RADIOLIST_BLOCKKEYWORD "radiolist"
    #define RADIODEFLUMP_RADIOLIST_TRACKKEYWORD "track"

    /* MAP BASE DEFINITIONS */

    struct MapBaseCollectionT
    {
        // Indicates if the lumps have been parsed already.
        bool Initialized;

        IO::MapBaseDefT Collection[MAXMAPCOUNT];
        int Count;
    };

    struct MapBaseDefT
    {
        str MapLump;
        int LumpIndex;
        int LumpStartOffset;
        int LumpEndOffset;

        Map::MapPropertiesT Properties;
    };

    /* MAP DETAILED DEFINITION */

    internal struct MapDetailedT
    {
        RoundTimer::RoundTimerContextT Timers[MAX_TIMERS];
        int ActiveRoundTimerIndex;

        Round::RoundStateContextT Rounds[MAX_ROUNDSTATES];
        int ActiveRoundStateIndex;

        Resist::ResistT Resists[MAX_RESISTS];

        // Serverside map scripts invoked for every resist.
        str GlobalPreResistScript;
        str GlobalPostResistScript;

        // This is purely clientside so we know if the sync was for new resists, or if we edit them.
        bool ResistsInitialized;

        // If `true`, the map is configured to play a heartbeat ambient on the final human.
        // TODO: This could turn into an integer indicating the final n humans play a heartbeat.
        bool PlayFinalHumanHeartbeat;
    };
}