#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Logger
{
    void LogDebug(str source, str message)
    {
        LogMessageLevel(source, Logger::LEVELDEBUG, message);
    }

    void LogInformation(str source, str message)
    {
        LogMessageLevel(source, Logger::LEVELINFO, message);
    }

    void LogWarning(str source, str message)
    {
        LogMessageLevel(source, Logger::LEVELWARN, message);
    }

    void LogError(str source, str message)
    {
        LogMessageLevel(source, Logger::LEVELERROR, message);
    }

    void LogFatal(str source, str message)
    {
        LogMessageLevel(source, Logger::LEVELFATAL, message);
    }

    void LogMessageLevel(str source, LogLevelT logLevel, str message)
    {
        // Check if global override has disabled this log message.
        if (!IsEnabledGlobally(source, logLevel))
            return;

        LogOwnerT owner = BCSUtils::ISClientOnly() ? OWNERCLIENT
                        : BCSUtils::IsServerOnly() ? OWNERSERVER
                        : OWNERNONE;

        str messagePacket = Packet::New();
        messagePacket = Packet::AppendStr(messagePacket, source);
        messagePacket = Packet::Append(messagePacket, (int)logLevel);
        messagePacket = Packet::Append(messagePacket, (int)owner);
        messagePacket = Packet::AppendStr(messagePacket, message);

        // When logged serverside, we also want to perform buffering and logging through rcon.
        if (BCSUtils::IsServerOnly())
            AddPacketLogToBuffer(messagePacket);

        // Now send the log to clients.
        // Already clientside, so we do not need to do networking.
        if (BCSUtils::IsClient())
        {
            if (!ACS_NamedExecuteAlways("LoggerLib_LogPacketOnClientString", 0, messagePacket))
                PrintError("Failed to invoke LoggerLib_LogPacketOnClientString. Message packet: '" + messagePacket + "'.");
            return;
        }

        if(!NamedSendNetworkString("LoggerLib_LogPacketOnClientInt", messagePacket))
            PrintError("Failed to invoke LoggerLib_LogPacketOnClientInt. Message packet: '" + messagePacket + "'.");
    }

    // Returns `true` if the given source-level combination is configured to be logged.
    // This is determined based on the override cvar of the client/server.
    internal bool IsEnabled(str source, LogLevelT level)
    {
        // Switch between server/client and check their override. If set, always check that first.
        int severity;
        if (BCSUtils::IsServerOnly())
            severity = GetLogLevelByIndex(ZH2Lib::GetServerOverwriteLogSeverity());
        else
            severity = GetLogLevelByIndex(ZH2Lib::GetClientOverwriteLogSeverity());

        if (severity != LEVELNONE)
            return severity <= level;

        // Check overrides for the given source and prioritize that override over the global default.
        for (int i = 0; i < ZH2Lib::PersistingLibContext.LogContext.OverrideCount; ++i)
        {
            LogOverrideT global:PERSISTINGLIBCONTEXTINDEX& override = ZH2Lib::PersistingLibContext.LogContext.Overrides[i];
            if (!BCSUtils::StrIEquals(override.Source, source))
                continue;

            return override.Level <= level;
        }

        return ZH2Lib::PersistingLibContext.LogContext.DefaultLevel <= level;
    }

    // Returns `true` if the given source-level combination is configured to be logged.
    // This is determined based on the global override cvar.
    internal bool IsEnabledGlobally(str source, LogLevelT level)
    {
        int severity = GetLogLevelByIndex(ZH2Lib::GetGlobalOverwriteLogSeverity());
        return severity == LEVELNONE || severity <= level;
    }

    internal LogOwnerT GetLogOwnerByIndex(int index)
    {
        if (index <= OWNERNONE || index > OWNERSERVER)
            return OWNERNONE;

        static LogOwnerT collection[] = { OWNERNONE, OWNERCLIENT, OWNERSERVER };
        return collection[index];
    }

    internal str GetLogOwnerAsString(LogOwnerT owner)
    {
        return owner == OWNERCLIENT ? "client" :
            owner == OWNERSERVER ? "server" :
            owner == OWNERNONE ? "neither" :
            "???";
    }

    internal LogLevelT GetLogLevelByIndex(int index)
    {
        if (index <= LEVELNONE || index > LEVELFATAL)
            return LEVELNONE;

        static LogLevelT collection[] = { LEVELDEBUG, LEVELINFO, LEVELWARN, LEVELERROR, LEVELFATAL };
        return collection[index - 1];
    }

    internal LogLevelT GetLogLevelByString(str string)
    {
        string = BCSUtils::StrToLower(string);
        switch(string)
        {
            case "dbg":
            case "debug":
                return LEVELDEBUG;

            case "inf":
            case "info":
            case "information":
                return LEVELINFO;

            case "wrn":
            case "warn":
            case "warning":
                return LEVELWARN;

            case "err":
            case "error":
                return LEVELERROR;

            case "ftl":
            case "fatal":
                return LEVELFATAL;

            default:
                return LEVELNONE;
        }
    }

    internal str GetLogLevelAsString(LogLevelT logLevel)
    {
        return logLevel == LEVELDEBUG ? "debug" :
            logLevel == LEVELINFO ? "information" :
            logLevel == LEVELWARN ? "warning" :
            logLevel == LEVELERROR ? "error" :
            logLevel == LEVELFATAL ? "fatal" :
            "???";
    }

    internal str GetLogLevelShortenedAsString(LogLevelT logLevel)
    {
        return logLevel == LEVELDEBUG ? "dbg" :
            logLevel == LEVELINFO ? "inf" :
            logLevel == LEVELWARN ? "wrn" :
            logLevel == LEVELERROR ? "err" :
            logLevel == LEVELFATAL ? "ftl" :
            "???";
    }

    internal str GetLogLevelColorAsString(LogLevelT logLevel)
    {
        return logLevel == LEVELDEBUG ? "j" :
            logLevel == LEVELINFO ? "n" :
            logLevel == LEVELWARN ? "k" :
            logLevel == LEVELERROR ? "g" :
            logLevel == LEVELFATAL ? "g" :
            "j";
    }
}