#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace LibIO
{
    script "zh2_internal_parse_weather_defs_server" busy
    {
        if (ZH2Lib::PersistingLibContext.WeatherContext.DefaultProfilesParsed)
            terminate;

        ParseWeatherLumps();
        ZH2Lib::PersistingLibContext.WeatherContext.DefaultProfilesParsed = true;
    }

    // Parses all the weathdef lumps.
    internal void ParseWeatherLumps()
    {
        int startIndex = -1;
        while(true)
        {
            startIndex = LumpOpen("weathdef", startIndex);

            if (startIndex == -1)
                break;

            if (LumpGetInfo(startIndex, LUMP_INFO_SIZE) == 0)
                continue;

            ParseSingleWeatherLump(LumpReadString(startIndex, 0));
            LumpClose(startIndex);
        }
    }

    internal void ParseSingleWeatherLump(str buffer)
    {
        int handle = Tokenizer::RentTokenizer(buffer);
        if (handle == -1)
            return;

        Tokenizer::Next(handle, false);

        while(Tokenizer::CanRead(handle))
        {
            str symbol = Tokenizer::GetSymbol(handle);
            if (ParseWeatherProfile(handle, symbol, "defaultweatherprofiles", false, HandleParsedProfile))
                continue;

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing weather lump: '" + symbol + "'.");
            Tokenizer::ReturnTokenizer(handle);
            return;
        }

        Tokenizer::ReturnTokenizer(handle);
    }

    // Externed for override behavior to be possible.
    bool ParseWeatherProfile(int handle, str identifyingSymbol, str expectedSymbol, bool useDefaultBase, void function(ParsedEmitterWeatherContextT global:0&)& parseCallback)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, expectedSymbol)) return false;

        int braceLevel = Tokenizer::GetBraceLevel(handle);
        if (!Tokenizer::ExpectNextChar(handle, '{'))
            return false;

        Tokenizer::Next(handle);

        // While the brace level does not match the end level, we keep parsing.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) != braceLevel)
        {
            str symbol = Tokenizer::GetSymbol(handle);
            if (ParseEmitterWeatherBlock(handle, symbol, useDefaultBase))
            {
                parseCallback(ParsedEmitterWeatherContext!!);
                continue;
            }

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing " + expectedSymbol + ": '" + symbol + "'.");
            return false;
        }

        // Optional comma.
        Tokenizer::Next(handle, false);
        if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
            Tokenizer::Next(handle, false);
        return true;
    }

    // Sets the default profile.
    internal void HandleParsedProfile(ParsedEmitterWeatherContextT global:0& data)
    {
        // I can't use a ref here because the data is missing. Compiler bug.
        //Weather::EmitterWeatherContextT module& context = ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[data.Index];

        Weather::SetPersistingEmitterWeatherEnabled(data.Index, data.Enabled);
        Weather::SetPersistingEmitterWeatherSkyBehavior(data.Index, data.SkyBehavior);
        Weather::SetPersistingEmitterWeatherSpawnCount(data.Index, data.SpawnCount);
        Weather::SetPersistingEmitterWeatherSpawnDelay(data.Index, data.SpawnDelay);
        Weather::SetPersistingEmitterWeatherMinRadius(data.Index, data.MinRadius);
        Weather::SetPersistingEmitterWeatherMaxRadius(data.Index, data.MaxRadius);
        Weather::SetPersistingEmitterWeatherMinZpos(data.Index, data.MinZpos);
        Weather::SetPersistingEmitterWeatherMaxZpos(data.Index, data.MaxZpos);
    }
}