#ifdef __IMPORTED__
	#error This file must be #included.
#endif

strict namespace ZH2Lib
{
    // Logging
    internal int GetClientOverwriteLogSeverity() { return BCSUTILS::Clamp(GetCvar("cl_zh2_overridelogseverity"), 0, 5); }
    internal int GetServerOverwriteLogSeverity() { return BCSUTILS::Clamp(GetCvar("sv_zh2_overridelogseverity"), 0, 5); }

    // Tracers
    internal bool GetServerEnabledTracers() { return (bool)GetCvar("sv_zh2_enabletracers"); }
    internal int GetClientTracerType() { return BCSUTILS::Clamp(GetCvar("cl_zh2_tracertype"), 0, 2); }

    // Footstep
    internal int GetClientStepType() { return BCSUTILS::Clamp(GetCvar("cl_zh2_steptype"), 0, 2); }
    internal int GetClientMaxStepDistance() { return BCSUTILS::Clamp(GetCvar("cl_zh2_maxstepdistance"), 100, 8000); }

    // Weather
    internal bool GetEnableWeather() { return (bool)GetCvar("cl_zh2_enableweather"); }
}