#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Event"

#include "send.acs"
#include "receive.acs"

strict namespace Event
{
    void SetReceiveData(int index, raw data)
    {
        if (index >= EVENT_RECEIVE_MAX_SIZE)
        {
            Logger::LogError(LOGSOURCE, "SetReceiveData index " + str(index) + " is out of bounds (0 - " + str(EVENT_RECEIVE_MAX_SIZE - 1) + ")!");
            return;
        }

        ZH2Lib::LibContext.EventReceiveContext.ReceiveData[index] = data;
    }

    raw GetReceiveData(int index)
    {
        if (index >= EVENT_RECEIVE_MAX_SIZE)
        {
            Logger::LogError(LOGSOURCE, "SetReceiveData index " + str(index) + " is out of bounds (0 - " + str(EVENT_RECEIVE_MAX_SIZE - 1) + ")!");
            return 0;
        }

        return ZH2Lib::LibContext.EventReceiveContext.ReceiveData[index];
    }
}

#undef LOGSOURCE