#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    void ReceiveRandomizedWeatherTrigger(str packet)
    {
        packet = Packet::Read(packet);
        int killedId = Packet::Value;

        packet = Packet::Read(packet);
        int killerId = Packet::Value;

        packet = Packet::Read(packet);
        int itemIndex = Packet::Value;

        packet = Packet::Read(packet);
        int addFireEffect = Packet::Value;

        packet = Packet::Read(packet);
        int addAcidEffect = Packet::Value;

        SetReceiveData(0, killedId);
        SetReceiveData(1, killerId);
        SetReceiveData(2, itemIndex);
        SetReceiveData(3, addFireEffect);
        SetReceiveData(4, addAcidEffect);
    }
}