#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Weather
{
    internal void TicEmitterWeather(int sourceTid)
    {
        for (int i = 0; i < EMITTER_WEATHER_COUNT; ++i)
        {
            // I can't use a ref here because the data is missing. Compiler bug.
            //EmitterWeatherContextT module& context = ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[i];

            if (!GetEmitterWeatherEnabled(i))
                continue;

            // Don't spawn this tic.
            if (GetEmitterWeatherNextSpawnTic(i) > Timer())
                continue;

            str class = GetEmitterWeatherActorByIndex(i);

            for (int j = 0; j < GetEmitterWeatherSpawnCount(i); ++j)
                SpawnParticle(sourceTid, class, i);

            SetEmitterWeatherNextSpawnTic(i, Timer() + GetEmitterWeatherSpawnDelay(i));
        }
    }

    internal void SpawnParticle(int sourceTid, str class, int index)
    {
        fixed angle = fixed(random(0, 1000)) / 1000.0,
              radius = fixed(random(GetEmitterWeatherMinRadius(index), GetEmitterWeatherMaxRadius(index)));

        fixed sourceZ = GetActorZ(sourceTid) + GetActorViewHeight(sourceTid);

        // Determine the position to spawn the weather particle at
        fixed spotX = GetActorX(sourceTid) + cos(angle) * radius,
              spotY = GetActorY(sourceTid) + sin(angle) * radius,
              spotZ = sourceZ + fixed(random(GetEmitterWeatherMinZpos(index), GetEmitterWeatherMaxZpos(index)));

        // Determine the z-height of the ceiling.
        fixed ceilingZ = GetSectorCeilingZ(0, int(spotX), int(spotY)) - 2.0;

        // If the ceiling is closer use the ceiling's z positioning instead to prevent it from not spawning.
        if (spotZ > ceilingZ)
            spotZ = ceilingZ;

        int spotId = UniqueTID();

        EmitterWeatherSkyBehaviorT skyBehavior = GetEmitterWeatherSkyBehavior(index);

        // The weather has specific behavior when it comes to spawning with a ceiling.
        if (skyBehavior != Weather::EMITTERWEATHER_SKYBEHAVIOUR_NONE)
        {
            if (!Spawn("MapSpot", spotX, spotY, sourceZ, spotId, 0))
                return;

            bool hasSkyCeiling = CheckActorCeilingTexture(spotId, "F_SKY1");
            Thing_Remove(spotId);

            // Further depending on the enum, check if we need a sky ceiling or not.
            if (skyBehavior == Weather::EMITTERWEATHER_SKYBEHAVIOUR_REQUIRESKY && !hasSkyCeiling
                || skyBehavior == Weather::EMITTERWEATHER_SKYBEHAVIOUR_REQUIRENOSKY && hasSkyCeiling)
                return;
        }

        SpawnForced(class, spotX, spotY, spotZ, 0, 0);
    }

    // Map-specific context
    bool GetEmitterWeatherEnabled(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].Enabled; }
    void SetEmitterWeatherEnabled(int index, bool value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].Enabled = value; }
    EmitterWeatherSkyBehaviorT GetEmitterWeatherSkyBehavior(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].SkyBehavior; }
    void SetEmitterWeatherSkyBehavior(int index, EmitterWeatherSkyBehaviorT value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].SkyBehavior = value; }
    int GetEmitterWeatherSpawnCount(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].SpawnCount; }
    void SetEmitterWeatherSpawnCount(int index, int value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].SpawnCount = value; }
    int GetEmitterWeatherSpawnDelay(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].SpawnDelay; }
    void SetEmitterWeatherSpawnDelay(int index, int value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].SpawnDelay = value; }
    int GetEmitterWeatherMinRadius(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MinRadius; }
    void SetEmitterWeatherMinRadius(int index, int value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MinRadius = value; }
    int GetEmitterWeatherMaxRadius(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MaxRadius; }
    void SetEmitterWeatherMaxRadius(int index, int value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MaxRadius = value; }
    int GetEmitterWeatherMinZpos(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MinZpos; }
    void SetEmitterWeatherMinZpos(int index, int value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MinZpos = value; }
    int GetEmitterWeatherMaxZpos(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MaxZpos; }
    void SetEmitterWeatherMaxZpos(int index, int value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].MaxZpos = value; }
    int GetEmitterWeatherNextSpawnTic(int index) { return ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].NextSpawnTic; }
    void SetEmitterWeatherNextSpawnTic(int index, int value) { ZH2Lib::LibContext.WeatherContext.EmitterWeatherCollection[index].NextSpawnTic = value; }

    // Persisting context
    internal bool GetPersistingEmitterWeatherEnabled(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].Enabled; }
    internal void SetPersistingEmitterWeatherEnabled(int index, bool value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].Enabled = value; }
    internal EmitterWeatherSkyBehaviorT GetPersistingEmitterWeatherSkyBehavior(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].SkyBehavior; }
    internal void SetPersistingEmitterWeatherSkyBehavior(int index, EmitterWeatherSkyBehaviorT value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].SkyBehavior = value; }
    internal int GetPersistingEmitterWeatherSpawnCount(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].SpawnCount; }
    internal void SetPersistingEmitterWeatherSpawnCount(int index, int value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].SpawnCount = value; }
    internal int GetPersistingEmitterWeatherSpawnDelay(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].SpawnDelay; }
    internal void SetPersistingEmitterWeatherSpawnDelay(int index, int value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].SpawnDelay = value; }
    internal int GetPersistingEmitterWeatherMinRadius(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MinRadius; }
    internal void SetPersistingEmitterWeatherMinRadius(int index, int value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MinRadius = value; }
    internal int GetPersistingEmitterWeatherMaxRadius(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MaxRadius; }
    internal void SetPersistingEmitterWeatherMaxRadius(int index, int value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MaxRadius = value; }
    internal int GetPersistingEmitterWeatherMinZpos(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MinZpos; }
    internal void SetPersistingEmitterWeatherMinZpos(int index, int value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MinZpos = value; }
    internal int GetPersistingEmitterWeatherMaxZpos(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MaxZpos; }
    internal void SetPersistingEmitterWeatherMaxZpos(int index, int value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].MaxZpos = value; }
    internal int GetPersistingEmitterWeatherNextSpawnTic(int index) { return ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].NextSpawnTic; }
    internal void SetPersistingEmitterWeatherNextSpawnTic(int index, int value) { ZH2Lib::PersistingLibContext.WeatherContext.EmitterWeatherCollection[index].NextSpawnTic = value; }

    internal str GetEmitterWeatherActorByIndex(int index)
    {
        if (index < 0 || index > 4)
            return (raw)0;

        static str actors[] = { "DebugDrop", "DebugDropSky", "DebugDropNoSky", "ZH2WeatherRainDrop", "ZH2WeatherSnowDrop" };
        return actors[index];
    }

    internal EmitterWeatherSkyBehaviorT GetEmitterWeatherSkyBehaviorByIndex(int index)
    {
        if (index < 0 || index > 2)
            return EMITTERWEATHER_SKYBEHAVIOUR_UNKNOWN;

        static EmitterWeatherSkyBehaviorT actors[] = { EMITTERWEATHER_SKYBEHAVIOUR_NONE, EMITTERWEATHER_SKYBEHAVIOUR_REQUIRESKY, EMITTERWEATHER_SKYBEHAVIOUR_REQUIRENOSKY, };
        return actors[index];
    }
}
