#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Weather"

#include "emitter.acs"

strict namespace Weather
{
    void InitializeServer()
    {
        for (int i = 0; i < EMITTER_WEATHER_COUNT; ++i)
        {
            SetEmitterWeatherEnabled(i, GetPersistingEmitterWeatherEnabled(i));
            SetEmitterWeatherSkyBehavior(i, GetPersistingEmitterWeatherSkyBehavior(i));
            SetEmitterWeatherSpawnCount(i, GetPersistingEmitterWeatherSpawnCount(i));
            SetEmitterWeatherSpawnDelay(i, GetPersistingEmitterWeatherSpawnDelay(i));
            SetEmitterWeatherMinRadius(i, GetPersistingEmitterWeatherMinRadius(i));
            SetEmitterWeatherMaxRadius(i, GetPersistingEmitterWeatherMaxRadius(i));
            SetEmitterWeatherMinZpos(i, GetPersistingEmitterWeatherMinZpos(i));
            SetEmitterWeatherMaxZpos(i, GetPersistingEmitterWeatherMaxZpos(i));
            SetEmitterWeatherNextSpawnTic(i, GetPersistingEmitterWeatherNextSpawnTic(i));
        }
    }

    void TicClient()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (!ZH2Lib::GetEnableWeather())
            return;

        // Determine the client's current camera position to determine where the tic handles weather.
        int cameraTid = CheckPlayerCamera(PlayerNumber());
        if (cameraTid == -1)
            return;

        TicEmitterWeather(cameraTid);
    }
}

#undef LOGSOURCE
