#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Weather
{
    #define EMITTER_WEATHER_COUNT 5

    enum EmitterWeatherCeilingBehaviorT : int
    {
        EMITTERWEATHER_CEILINGBEHAVIOUR_NONE,
        EMITTERWEATHER_CEILINGBEHAVIOUR_REQUIRESKY,
        EMITTERWEATHER_CEILINGBEHAVIOUR_REQUIRENOSKY,
    };

    // NOTE, also the index of the weather.
    enum EmitterWeatherTypeT : int
    {
        EMITTERWEATHER_DEBUG,
        EMITTERWEATHER_DEBUGSKY,
        EMITTERWEATHER_DEBUGNOSKY,
        EMITTERWEATHER_RAIN,
        EMITTERWEATHER_SNOW,
    };

    struct WeatherContextT
    {
        EmitterWeatherContextT EmitterWeatherCollection[EMITTER_WEATHER_COUNT];
    };

    struct EmitterWeatherContextT
    {
        bool Enabled;
        EmitterWeatherCeilingBehaviorT CeilingBehavior;
        int SpawnCount;
        int SpawnDelay;

        int MinRadius;
        int MaxRadius;
        int MinZpos;
        int MaxZpos;

        // Clientside, tracks when to spawn the weather next.
        int NextSpawnTic;
    };

    extern void TicClient();
}