#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Weather"

#include "emitter.acs"

strict namespace Weather
{
    void InitializeServer()
    {
        for (int i = 0; i < EMITTER_WEATHER_COUNT; ++i)
        {
            SetTransientEmitterWeatherEnabled(i, GetPersistingEmitterWeatherEnabled(i));
            SetTransientEmitterWeatherSkyBehavior(i, GetPersistingEmitterWeatherSkyBehavior(i));
            SetTransientEmitterWeatherSpawnCount(i, GetPersistingEmitterWeatherSpawnCount(i));
            SetTransientEmitterWeatherSpawnDelay(i, GetPersistingEmitterWeatherSpawnDelay(i));
            SetTransientEmitterWeatherMinRadius(i, GetPersistingEmitterWeatherMinRadius(i));
            SetTransientEmitterWeatherMaxRadius(i, GetPersistingEmitterWeatherMaxRadius(i));
            SetTransientEmitterWeatherMinZpos(i, GetPersistingEmitterWeatherMinZpos(i));
            SetTransientEmitterWeatherMaxZpos(i, GetPersistingEmitterWeatherMaxZpos(i));
            SetTransientEmitterWeatherNextSpawnTic(i, GetPersistingEmitterWeatherNextSpawnTic(i));
        }
    }

    void TicClient()
    {
        VALIDATE_IS_CLIENTSIDE_FUNCTION();

        if (!ZH2Lib::GetEnableWeather())
            return;

        // Determine the client's current camera position to determine where the tic handles weather.
        int cameraTid = CheckPlayerCamera(PlayerNumber());
        if (cameraTid == -1)
            return;

        TicEmitterWeather(cameraTid);
    }
}

#undef LOGSOURCE
