#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Weather
{
    #define EMITTER_WEATHER_COUNT 5

    enum EmitterWeatherSkyBehaviorT : int
    {
        EMITTERWEATHER_SKYBEHAVIOUR_UNKNOWN,
        EMITTERWEATHER_SKYBEHAVIOUR_NONE,
        EMITTERWEATHER_SKYBEHAVIOUR_REQUIRESKY,
        EMITTERWEATHER_SKYBEHAVIOUR_REQUIRENOSKY,
    };

    enum EmitterWeatherTypeT : int
    {
        EMITTERWEATHER_UNKNOWN,
        EMITTERWEATHER_DEBUG,
        EMITTERWEATHER_DEBUGSKY,
        EMITTERWEATHER_DEBUGNOSKY,
        EMITTERWEATHER_RAIN,
        EMITTERWEATHER_SNOW,
    };

    struct WeatherContextT
    {
        // Map-specific overrides.
        EmitterWeatherContextT EmitterWeatherCollection[EMITTER_WEATHER_COUNT];
    };

    struct PersistingWeatherContextT
    {
        // Global defaults.
        EmitterWeatherContextT EmitterWeatherCollection[EMITTER_WEATHER_COUNT];

        // IO
        bool DefaultProfilesParsed;
    };

    struct EmitterWeatherContextT
    {
        bool Enabled;
        EmitterWeatherSkyBehaviorT SkyBehavior;
        int SpawnCount;
        int SpawnDelay;

        int MinRadius;
        int MaxRadius;
        int MinZpos;
        int MaxZpos;

        // Clientside, tracks when to spawn the weather next.
        int NextSpawnTic;
    };

    extern void InitializeServer();
    extern void TicClient();

    extern bool GetEmitterWeatherEnabled(int index);
    extern void SetEmitterWeatherEnabled(int index, bool value);
    extern EmitterWeatherSkyBehaviorT GetEmitterWeatherSkyBehavior(int index);
    extern void SetEmitterWeatherSkyBehavior(int index, EmitterWeatherSkyBehaviorT value);
    extern int GetEmitterWeatherSpawnCount(int index);
    extern void SetEmitterWeatherSpawnCount(int index, int value);
    extern int GetEmitterWeatherSpawnDelay(int index);
    extern void SetEmitterWeatherSpawnDelay(int index, int value);
    extern int GetEmitterWeatherMinRadius(int index) ;
    extern void SetEmitterWeatherMinRadius(int index, int value);
    extern int GetEmitterWeatherMaxRadius(int index);
    extern void SetEmitterWeatherMaxRadius(int index, int value);
    extern int GetEmitterWeatherMinZpos(int index);
    extern void SetEmitterWeatherMinZpos(int index, int value);
    extern int GetEmitterWeatherMaxZpos(int index);
    extern void SetEmitterWeatherMaxZpos(int index, int value);
    extern int GetEmitterWeatherNextSpawnTic(int index);
    extern void SetEmitterWeatherNextSpawnTic(int index, int value);
}