#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "status.acs"
#include "power.acs"
#include "bar.acs"
#include "blur.acs"
#include "inventory.acs"
#include "identity.acs"

// TODO: has its own flow, should probably be combined to avoid confusion.
#include "clientsettings.acs"
#include "deathcam.acs"

strict namespace Hud
{
    internal void DrawPlayerHud()
    {
        if (!BCSUtils::ActorIsAlive(ActivatorTid()))
            return;

        if (ZH2Game::GetDrawPlayerBarsHud())
            DrawBarHud();

        if (ZH2Game::GetDrawPlayerStatusHud())
            DrawPlayerStatusHud();
            
        if (ZH2Game::GetDrawPlayerPowersHud())
            DrawPlayerPowersHud();
        
        DrawIdentity();
        
        DrawInventory();

        DrawBlurHud();
    }
}