#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Monster
{
    script "zh2_dec_angel_checksee"
    {
        static int nextSeeTrigger;
        if (nextSeeTrigger < Timer())
        {
            nextSeeTrigger = Timer() + ANGEL_NEXT_SEE_SCREAM;
            SetResultValue((int)true);
        }
        else
        {
            SetResultValue((int)false);
        }
    }
}
