#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal int _startDrawIndex = 0;

    internal void DrawRadioHud()
    {
        // No tracks to display.
        if (Decorate::GetRadioCollectionSize() == 0)
            return;

        // Adjust the start index to stay within bounds.
        int currentIndex = Decorate::GetClientRadioCurrentlySelectedIndex();
        int endDrawIndex = GetEndDrawIndex(_startDrawIndex);
        
        if (_startDrawIndex > currentIndex)
        {
            _startDrawIndex = currentIndex;
            endDrawIndex = GetEndDrawIndex(_startDrawIndex);
        }
            
        if (endDrawIndex <= currentIndex)
        {
            _startDrawIndex = BCSUtils::Max(0, currentIndex - WEAPON_RADIO_MAXDRAWNTRACKS + 1);
            endDrawIndex = GetEndDrawIndex(_startDrawIndex);
        }

        if (!CheckWeapon(WEAPON_RADIO_NAME))
            return;

        // The vertical offset will move down with each track.
        fixed addY = 0.0;

        for (int i = _startDrawIndex; i < endDrawIndex; ++i)
        {
            BCSUtils::HudSetTextColor(i == currentIndex ? CR_GREEN : CR_WHITE);
            BCSUtils::HudSetFont("BigFont");
            
            HudSetPointInternal(0.0, addY);
            BCSUtils::HudDrawText(--_drawnHudId, str(i + 1) + ". " + Decorate::GetRadioTrackName(i));
            DebugDraw();

            str author = Decorate::GetRadioTrackAuthor(i);
            if ((raw)author != 0 && author != "")
            {
                addY += 15.0;
                
                BCSUtils::HudSetTextColor(CR_GRAY);
                BCSUtils::HudSetFont("SmallFont");

                HudSetPointInternal(0.0, addY);
                BCSUtils::HudDrawText(--_drawnHudId, "By " + author);
            }

            str remark = Decorate::GetRadioTrackRemark(i);
            if ((raw)remark != 0 && remark != "")
            {
                addY += 10.0;

                BCSUtils::HudSetTextColor(CR_GRAY);
                BCSUtils::HudSetFont("SmallFont");
                
                HudSetPointInternal(0.0, addY);
                BCSUtils::HudDrawText(--_drawnHudId, remark);
            }

            addY += 20.0;
        }
    }

    internal int GetEndDrawIndex(int startDrawIndex)
    {
        return BCSUtils::Min(startDrawIndex + WEAPON_RADIO_MAXDRAWNTRACKS, Decorate::GetRadioCollectionSize());
    }
}