#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE  "Shuffle"

#include "clientsettings.acs"
#include "player.acs"
#include "ending.acs"
#include "round.acs"
#include "map.acs"

strict namespace Shuffle
{
    internal BufferContextT _context;

    // Optional argument to provide for sort functions that depend on extra data to sort.
    internal raw _sortArg;

    internal int GetIndexValue(int index)
    {
        return _context.Buffer[index];
    }

    internal int GetRelevantSize()
    {
        return _context.BufferRelevantSize;
    }

    script "zh2_internal_shuffle_swapbufferitems" (int left, int right)
    {
        BCSUtils::Swap(_context.Buffer[left], _context.Buffer[right]);
        _context.Buffer[left] = BCSUtils::r1;
        _context.Buffer[right] = BCSUtils::r2;
    }

    // Helper method that calculates the relevant size of the buffer after preparing it.
    // The comparer is used to determine when to break out. Return `true` if the item is still relevant
    internal void UpdateRelevantBufferSize(bool function(int)& comparer)
    {
        _context.BufferRelevantSize = 0;
        while (_context.BufferRelevantSize < _context.BufferIteratorSize)
        {
            if(!comparer(_context.Buffer[_context.BufferRelevantSize]))
                break;

            _context.BufferRelevantSize++;
        }
    }
}

#undef LOGSOURCE 