#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE  "Shuffle"

#include "clientsettings.acs"
#include "player.acs"
#include "ending.acs"
#include "round.acs"
#include "map.acs"

strict namespace Shuffle
{
    internal BufferContextT _context;

    internal int GetIndexValue(int index)
    {
        return _context.Buffer[index];
    }

    internal int GetRelevantSize()
    {
        return _context.BufferRelevantSize;
    }

    script "zh2_internal_shuffle_swapbufferitems" (int left, int right)
    {
        BCSUtils::Swap(_context.Buffer[left], _context.Buffer[right]);
        _context.Buffer[left] = BCSUtils::r1;
        _context.Buffer[right] = BCSUtils::r2;
    }
}

#undef LOGSOURCE 