#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Shuffle
{
    script "zh2_internal_shuffle_comparehumankills" (int left, int right)
    {
        SetResultValue(int(
            Player::GetPlayerHumanKills(_context.Buffer[left]) >
            Player::GetPlayerHumanKills(_context.Buffer[right])
        ));
    }

    script "zh2_internal_shuffle_comparezombiekills" (int left, int right)
    {
        SetResultValue(int(
            Player::GetPlayerZombieKills(_context.Buffer[left]) >
            Player::GetPlayerZombieKills(_context.Buffer[right])
        ));
    }

    script "zh2_internal_shuffle_compareinfects" (int left, int right)
    {
        SetResultValue(int(
            Player::GetPlayerInfects(_context.Buffer[left]) >
            Player::GetPlayerInfects(_context.Buffer[right])
        ));
    }

    internal void SortByHumanKills(ShufflePrepareTypeT shuffleType = SHUFFLEASSIGNED)
    {
        PrepareBufferPlayers(shuffleType);
        BCSUtils::SortArray(0, _context.BufferIteratorSize, "zh2_internal_shuffle_comparehumankills", "zh2_internal_shuffle_swapbufferitems");

        _context.BufferRelevantSize = 0;
        while (_context.BufferRelevantSize < _context.BufferIteratorSize)
        {
            int id = _context.Buffer[_context.BufferRelevantSize];
            if(Player::GetPlayerHumanKills(id) == 0)
                break;
                
            _context.BufferRelevantSize++;
        }
    }

    internal void SortByZombieKills(ShufflePrepareTypeT shuffleType = SHUFFLEASSIGNED)
    {
        PrepareBufferPlayers(shuffleType);
        BCSUtils::SortArray(0, _context.BufferIteratorSize, "zh2_internal_shuffle_comparezombiekills", "zh2_internal_shuffle_swapbufferitems");

        _context.BufferRelevantSize = 0;
        while (_context.BufferRelevantSize < _context.BufferIteratorSize)
        {
            int id = _context.Buffer[_context.BufferRelevantSize];
            if(Player::GetPlayerZombieKills(id) == 0)
                break;
                
            _context.BufferRelevantSize++;
        }
    }

    internal void SortByInfects(ShufflePrepareTypeT shuffleType = SHUFFLEASSIGNED)
    {
        PrepareBufferPlayers(shuffleType);
        BCSUtils::SortArray(0, _context.BufferIteratorSize, "zh2_internal_shuffle_compareinfects", "zh2_internal_shuffle_swapbufferitems");

        _context.BufferRelevantSize = 0;
        while (_context.BufferRelevantSize < _context.BufferIteratorSize)
        {
            int id = _context.Buffer[_context.BufferRelevantSize];
            if(Player::GetPlayerInfects(id) == 0)
                break;
                
            _context.BufferRelevantSize++;
        }
    }
}