#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    // This indicates the sub menu that we are on when in the `ADMINMENU_PLAYER` menu.
    internal AdminMenuPlayerTargetT menuPlayerTarget;

    // This indicates what player we should target when we are in the `ADMINMENU_PLAYER` screen and targeting a specific player.
    // If -1 we don't target anybody and we render the initial window instead.
    internal int _menuPlayerTargetId = -1;

    // Used to pass along species when pressing buttons for specie specific players.
    // Can be set using the buttons.
    internal Player::SpecieTypeT _filteredSpecie;

    internal void DrawPlayerMenuHud()
    {
        fixed x = GetHudX(),
              y = GetHudY() + 10.0;

        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, "\cfPlayers");

        if (DrawClickableText(--_drawnHudId, x, y, 100.0, 10.0, "Back to start"))
            OpenAdminMenu(ADMINMENU_START);

        if (menuPlayerTarget != MENUTARGET_NONE)
        {
            if (DrawClickableText(--_drawnHudId, x, y + 10.0, 100.0, 10.0, "Back to players"))
            {
                _menuPlayerTargetId = -1;
                menuPlayerTarget = MENUTARGET_NONE;
            }
        }
        else
        {
            if (DrawClickableText(--_drawnHudId, x, y + 10.0, 100.0, 10.0, "For all players"))
                menuPlayerTarget = MENUTARGET_ALL;
        }

        // Draw player specific commands when we select a player, otherwise draw the player list.
        switch(menuPlayerTarget)
        {
            case MENUTARGET_NONE:
                DrawPlayerList();
                break;
            
            case MENUTARGET_ALL:
                DrawGiveAll();
                break;
            
            case MENUTARGET_PLAYERSPECIFIC:
                DrawPlayerDetails(_menuPlayerTargetId);
                break;
        }
    }

    internal void DrawPlayerList()
    {
        fixed x = GetHudX(),
              y = GetHudY() + 20.0;

        // Add bots as human/zombie. Doesn't work if we reached max players.
        
        if (DrawClickableTextConditional(
            BCSUtils::ClientCount() != BCSUtils::MAX_PLAYERS, --_drawnHudId, x, y, 100.0, 10.0, "add bot (human)"))
        {
            Admin::AdminAddHumanBotClientside();
        }

        if (DrawClickableTextConditional(
            BCSUtils::ClientCount() != BCSUtils::MAX_PLAYERS, --_drawnHudId, x + 150.0, y, 100.0, 10.0, "add bot (zombie)"))
        {
            Admin::AdminAddZombieBotClientside();
        }

        if (DrawClickableTextConditional(
            BCSUtils::BotCount() != 0, --_drawnHudId, x + 300.0, y, 100.0, 10.0, "remove bot"))
        {
            Admin::AdminRemoveBotClientside();
        }

        int offset = 0;
        for (int i = 0; i < BCSUTILS::MAX_PLAYERS; ++i)
        {
            if (!BCSUTILS::ActorIsAlive(Identity::GetTID(i)))
                continue;
            
            BCSUtils::HudSetTextColor(CR_WHITE);
            
            HudSetPointInternal(0.0, 10.0 + fixed(10 * offset));
            BCSUtils::HudDrawText(--_drawnHudId, str(i));

            if (DrawClickableText(--_drawnHudId, x + 20.0, y + 10.0 + fixed(10 * offset), 60.0, 10.0, BCSUTILS::PlayerName(i)))
            {
                _menuPlayerTargetId = i;
                menuPlayerTarget = MENUTARGET_PLAYERSPECIFIC;
            }

            offset++;
        }
    }

    
    internal void DrawGiveAll()
    {
        // In some cases we loop over all species.
        // Note specie "none" means we give the reward to everybody in this instance.
        // (No point making a whole separate set of code when we can just reuse it).

        fixed x = GetHudX(),
              y = GetHudY();
            
        fixed addX = 0.0,
              addY = 0.0;

        /* LIST OF POWERS */

        BCSUtils::HudSetFont("BigFont");
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfFilter specie");
            
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetFont("SmallFont");

        addY += 20.0;
    
        for (int i = Player::SPECIENONE; i <= Player::SPECIEZOMBIE; ++i)
        {
            Player::SpecieTypeT specie = Player::GetSpecieTypeByIndex(i);
            str label = specie == Player::SPECIENONE
                ? "all"
                : Player::GetSpecieIndexAsString(specie);

            if (DrawClickableTextConditional(
                _filteredSpecie != specie, --_drawnHudId, x + addX + fixed(50 * i), y + addY, 50.0, 10.0, label))
            {
                _filteredSpecie = specie;
            }
        }
        
        y += 20.0;

        /* ALLOW JOIN */

        BCSUtils::HudSetFont("BigFont");
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAllow join");
            
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetFont("SmallFont");

        addY += 20.0;
        
        if (DrawClickableText(--_drawnHudId, x + addX, y + addY, 30.0, 10.0, "enable"))
            Admin::AdminSetAllowJoinClientSide(true);
        
        if (DrawClickableText(--_drawnHudId, x + 60.0 + addX, y + addY, 40.0, 10.0, "disable"))
            Admin::AdminSetAllowJoinClientSide(false);

        addY += 20.0;

        /* LIST OF POWERS */

        BCSUtils::HudSetFont("BigFont");
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfPowers");

        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawPowerSelectors(addX, addY, InvokeIncrementPowerOnAll);

        // Note, hardcoded 2 for the current two available items you can increase.
        addY += 10.0 * 2.0;
        
        addY += 20.0;

        /* KEVLAR ARMOR */

        BCSUtils::HudSetFont("BigFont");
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAdd kevlar armor");

        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawArmorIncrementSelectors(addX, addY, InvokeArmorIncrementOnAll);
        
        addY += 20.0;

        /* REWARD CONTAINERS */

        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive containers");
        
        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardContainerSelectors(addX, addY, InvokeContainerOnAll);

        // Resets y and moves x
        addY = -100.0;
        addX += 200.0;

        /* ITEMS */
        
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive items");
        
        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawItemSelectors(addX, addY, InvokeIncrementItemOnAll);

        // Resets y and moves x
        addY = -100.0;
        addX += 300.0;

        /* REWARDS */
        
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive rewards");
        
        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardSelectors(addX, addY, InvokeGiveRewardOnAll);
    }

    internal void InvokeIncrementItemOnAll(int index, int amount)
    {
        Admin::AdminIncrementSpecieItemClientside(_filteredSpecie, index, amount);
    }

    internal void InvokeGiveRewardOnAll(int index)
    {
        Admin::AdminGiveSpecieRewardClientside(_filteredSpecie, index);
    }

    internal void InvokeIncrementPowerOnAll(int index, int amount)
    {
        Admin::AdminIncrementSpeciePowerClientside(_filteredSpecie, index, amount);
    }

    internal void InvokeArmorIncrementOnAll(int amount)
    {
        Admin::AdminIncrementSpecieArmorClientSide(_filteredSpecie, amount);
    }

    internal void InvokeContainerOnAll(Reward::RewardItemTypeFlagsT type)
    {
        Admin::AdminGiveRewardContainerSpecieClientSide(_filteredSpecie, type);
    }

    internal void DrawPlayerDetails(int playerId)
    {
        fixed x = GetHudX(),
              y = GetHudY();
            
        fixed addX = 0.0,
              addY = 0.0;
        
        if (playerId == -1)
        {
            BCSUtils::HudSetTextColor(CR_RED);
            
            HudSetPointInternal(addX, addY);
            BCSUtils::HudDrawText(--_drawnHudId, "Error: failed to determine player id.");

            return;
        }
        
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, Player::GetPlayerName(playerId));

        addY += 10.0;

        // Failsafe, player left or died. Should return back to the initial list.
        if (!BCSUTILS::ActorIsAlive(Identity::GetTID(playerId)))
        {
            BCSUtils::HudSetTextColor(CR_RED);
        
            HudSetPointInternal(addX, addY);
            BCSUtils::HudDrawText(--_drawnHudId, "Player is dead or left.");
            return;
        }

        if (DrawClickableTextConditional(
            !Player::GetPlayerIsZombie(playerId), --_drawnHudId, x, y, 50.0, 10.0, "infect"))
        {
            Admin::AdminInfectPlayerClientside(playerId);
        }

        if (DrawClickableTextConditional(
            !Player::GetPlayerIsHuman(playerId), --_drawnHudId, x + 50.0, y, 50.0, 10.0, "cure"))
        {
            Admin::AdminCurePlayerClientside(playerId);
        }

        if (DrawClickableText(--_drawnHudId, x + 90.0, y, 50.0, 10.0, "kill"))
            Admin::AdminKillPlayerClientside(playerId);

        addY += 20.0;

        /* ALLOW JOIN */

        BCSUtils::HudSetFont("BigFont");
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAllow join");
            
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetFont("SmallFont");

        addY += 20.0;
        
        if (DrawClickableText(--_drawnHudId, x, y, 30.0, 10.0, "enable"))
            Admin::AdminSetPlayerAllowJoinClientSide(playerId, true);
        
        if (DrawClickableText(--_drawnHudId, (x + 60.0), y, 40.0, 10.0, "disable"))
            Admin::AdminSetPlayerAllowJoinClientSide(playerId, false);

        addY += 20.0;
            
        /* LIST OF POWERS */

        BCSUtils::HudSetFont("BigFont");
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfPowers");

        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawPowerSelectors(addX, addY, InvokeIncrementPowerOnSelectedPlayer);
        
        addY += 20.0;

        /* KEVLAR ARMOR */

        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAdd kevlar armor");

        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawArmorIncrementSelectors(addX, addY, InvokeArmorIncrementOnSelectedPlayer);

        addY += 20.0;

        /* REWARD CONTAINERS */

        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive containers");
        
        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardContainerSelectors(addX, addY, InvokeContainerOnSelectedPlayer);
        
        // Resets y and moves x
        addY = -100.0;
        addX += 200.0;

        /* ITEMS */
        
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive items");
        
        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawItemSelectors(addX, addY, InvokeIncrementItemOnSelectedPlayer);
        
        // Resets y and moves x
        addY = -100.0;
        addX += 300.0;

        /* REWARDS */
        
        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal(addX, addY);
        BCSUtils::HudDrawText(--_drawnHudId, "\cfGive rewards");
        
        addY += 20.0;

        BCSUtils::HudSetFont("SmallFont");
        DrawRewardSelectors(addX, addY, InvokeGiveRewardOnSelectedPlayer);
    }

    internal void InvokeIncrementItemOnSelectedPlayer(int index, int amount)
    {
        Admin::AdminIncrementPlayerItemClientside(_menuPlayerTargetId, index, amount);
    }

    internal void InvokeGiveRewardOnSelectedPlayer(int index)
    {
        Admin::AdminGivePlayerRewardClientside(_menuPlayerTargetId, index);
    }

    internal void InvokeIncrementPowerOnSelectedPlayer(int index, int amount)
    {
        Admin::AdminIncrementPlayerPowerClientside(_menuPlayerTargetId, index, amount);
    }

    internal void InvokeArmorIncrementOnSelectedPlayer(int amount)
    {
        Admin::AdminIncrementPlayerArmorClientSide(_menuPlayerTargetId, amount);
    }

    internal void InvokeContainerOnSelectedPlayer(Reward::RewardItemTypeFlagsT type)
    {
        Admin::AdminGiveRewardContainerPlayerClientSide(_menuPlayerTargetId, type);
    }

    // TODO: Should split this by category maybe.
    internal void DrawItemSelectors(fixed addX, fixed addY, void function(int, int)& invoker)
    {
        fixed x = GetHudX() + addX,
              y = GetHudY() + addY;

        for (int i = 0; i < Item::GetItemCollectionSize(); ++i)
        {
            // This will always exist as it is required.
            str label = Item::GetItemLabel(i);
            if (label == (raw)0 || label == "")
                label = Item::GetItemName(i);

            BCSUtils::HudSetTextColor(CR_WHITE);
            
            HudSetPointInternal(addX, addY + fixed(10 * i));
            BCSUtils::HudDrawText(--_drawnHudId, label);

            if (DrawClickableText(--_drawnHudId, x + 200.0, y + fixed(10 * i), 40.0, 10.0, "give"))
                invoker(i, 1);

            if (DrawClickableText(--_drawnHudId, x + 240.0, y + fixed(10 * i), 40.0, 10.0, "take"))
                invoker(i, -1);
        }
    }

    internal void DrawRewardSelectors(fixed addX, fixed addY, void function(int)& invoker)
    {
        fixed x = GetHudX() + addX,
              y = GetHudY() + addY;

        for (int i = 0; i < Reward::GetRewardCollectionSize(); ++i)
        {
            // This will always exist as it is required.
            str name = Reward::GetRewardName(i);

            BCSUtils::HudSetTextColor(CR_WHITE);
            
            HudSetPointInternal(addX, addY + fixed(10 * i));
            BCSUtils::HudDrawText(--_drawnHudId, name);

            if (DrawClickableText(--_drawnHudId, x, y + fixed(10 * i), 140.0, 10.0, name))
                invoker(i);
        }
    }

    internal void DrawPowerSelectors(fixed addX, fixed addY, void function(int, int)& invoker)
    {
        fixed x = GetHudX() + addX,
              y = GetHudY() + addY;

        int offset = 0;
        for (int i = 0; i < Power::GetPowerSize(); ++i)
        {
            Power::PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[i];

            // For now we are skipping powers with no max length since they are usually something special.
            // They make no sense to provide.
            if (context.MaxTics == BCSUtils::INT_MAX)
                continue;
            
            BCSUtils::HudSetTextColor(CR_WHITE);
            
            HudSetPointInternal(addX, addY + fixed(10 * i));
            BCSUtils::HudDrawText(--_drawnHudId, Power::GetPowerIndexAsString(i));

            // TODO: Support more increments, possibly even the ability to decrement.
            if (DrawClickableText(--_drawnHudId, x + 100.0, y + fixed(10 * offset), 20.0, 10.0, "+5s"))
                invoker(i, 35 * 5);

            offset++;
        }
    }

    internal void DrawArmorIncrementSelectors(fixed addX, fixed addY, void function(int)& invoker)
    {
        fixed x = GetHudX() + addX,
              y = GetHudY() + addY;

        // Increment / decrement
        if (DrawClickableText(--_drawnHudId, x, y, 30.0, 10.0, "-50"))
            invoker(-50);

        if (DrawClickableText(--_drawnHudId, x + 30.0, y, 30.0, 10.0, "-10"))
            invoker(-10);

        if (DrawClickableText(--_drawnHudId, x + 60.0, y, 30.0, 10.0, "-1"))
            invoker(-1);

        if (DrawClickableText(--_drawnHudId, x + 90.0, y, 30.0, 10.0, "+1"))
            invoker(1);

        if (DrawClickableText(--_drawnHudId, x + 120.0, y, 30.0, 10.0, "+10"))
            invoker(10);

        if (DrawClickableText(--_drawnHudId, x + 150.0, y, 30.0, 10.0, "+50"))
            invoker(50);
    }

    internal void DrawRewardContainerSelectors(fixed addX, fixed addY, void function(Reward::RewardItemTypeFlagsT)& invoker)
    {
        fixed x = GetHudX() + addX,
              y = GetHudY() + addY;
              
        for (int j = 0; j < REWARD_CONTAINER_COUNT; ++j)
        {
            fixed buttonX = x + fixed(100 * (j % 2));
            fixed buttonY = y + fixed(10 * (j / 2));

            Reward::RewardItemTypeFlagsT type = Reward::GetRewardItemTypeByIndex(j + 1);
            str buttonName = Reward::ContainerTypeToShortReadableString(type);
            if (DrawClickableText(--_drawnHudId, buttonX, buttonY, 100.0, 10.0, buttonName))
                invoker(type);
        }
    }
}