#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawStartMenuHud()
    {
        BCSUtils::HudSetTextColor(CR_WHITE);
        
        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, "\cfAdmin menu");

        if (DrawClickableText(--_drawnHudId, 0.0, 10.0, 100.0, 10.0, "Players"))
            OpenAdminMenu(ADMINMENU_PLAYER);

        if (DrawClickableText(--_drawnHudId, 0.0, 20.0, 100.0, 10.0, "Timers"))
            OpenAdminMenu(ADMINMENU_TIMER);

        if (DrawClickableText(--_drawnHudId, 0.0, 30.0, 100.0, 10.0, "Round"))
            OpenAdminMenu(ADMINMENU_ROUND);

        if (DrawClickableText(--_drawnHudId, 0.0, 40.0, 100.0, 10.0, "Resists"))
            OpenAdminMenu(ADMINMENU_RESIST);
    }
}