#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "header.acs"
#include "statlist.acs"

strict namespace Hud
{
    internal void DrawEndingHud()
    {
        fixed scale = ZH2Game::GetHudEndingScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0, 480.0);
        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        PrepareHud(
            320.0,
            BCSUtils::HudTop() + 80.0,
            false);

        Game::EndActionT action = Game::GetEndAction();
        DrawEndingHeader(action);

        // If the action isn't default then the normal flow doesn't run.
        // So we don't draw the stats either.
        if (action != Game::ACTION_DEFAULT)
            return;

        // Offset is set based on what lists are shown, meaning we might shift lists to a different position if the stat has no data.
        int listOffset = 0;

        // The vertical offset will be updated to increased values based on the longest list.
        // This value is eventually used to draw the next row.
        fixed verticalOffset = 0.0;

        // Each column 220 units wide.
        // Each row 190 units tall.
        fixed GetAddX(int listOffset) { return fixed(listOffset % 3) * 220.0; }
        fixed GetAddY(int listOffset) { return fixed(listOffset / 3) * verticalOffset; }

        void UpdateOffsets(int count)
        {
            listOffset++;

            // If we have at least one item to draw, we want to see if the vertical offset needs updating.
            // If yes, this is the longest list so far.
            if (count == 0)
                return;

            // Base addition of 25.0 for the header and 10.0 for a gap between lists.
            // Every name adds 15.0 to the offset.
            fixed checkVerticalOffset = 25.0 + 10.0 + fixed(count * 15);
            if (checkVerticalOffset > verticalOffset)
            {
                verticalOffset = checkVerticalOffset;
            }
        }

        // Used below to hold the final drawn item count, used for determining the y offset.
        int drawnCount;

        PrepareHud(
            30.0,
            BCSUtils::HudTop() + 140.0,
            false);

        /* ACTUAL DRAWING */

        if (ZH2Game::GameContext.SurvivorsShuffledCount > 0)
        {
            drawnCount = DrawList(GetAddX(listOffset), GetAddY(listOffset), "\cdSurvivors",
                ZH2Game::GameContext.SurvivorsShuffledCount, 8, ZH2Game::GameContext.SurvivorsShuffled, null);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.HordeShuffledCount > 0)
        {
            drawnCount = DrawList(GetAddX(listOffset), GetAddY(listOffset), "\cqThe horde",
                ZH2Game::GameContext.HordeShuffledCount, 8, ZH2Game::GameContext.HordeShuffled, null);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.DeadShuffledCount > 0)
        {
            drawnCount = DrawList(GetAddX(listOffset), GetAddY(listOffset), "\cjIn memory of",
                ZH2Game::GameContext.DeadShuffledCount, 8, ZH2Game::GameContext.DeadShuffled, null);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.HumanKillsOrderedCount > 0)
        {
            drawnCount = DrawList(GetAddX(listOffset), GetAddY(listOffset), "\cgTop human killers",
                ZH2Game::GameContext.HumanKillsOrderedCount, 4, ZH2Game::GameContext.HumanKillsOrdered, Player::GetPlayerHumanKills);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.ZombieKillsOrderedCount > 0)
        {
            drawnCount = DrawList(GetAddX(listOffset), GetAddY(listOffset), "\cfTop zombie killers",
                ZH2Game::GameContext.ZombieKillsOrderedCount, 4, ZH2Game::GameContext.ZombieKillsOrdered, Player::GetPlayerZombieKills);
            UpdateOffsets(drawnCount);
        }

        if (ZH2Game::GameContext.InfectsOrderedCount > 0)
        {
            drawnCount = DrawList(GetAddX(listOffset), GetAddY(listOffset), "\cgTop infects",
                ZH2Game::GameContext.InfectsOrderedCount, 4, ZH2Game::GameContext.InfectsOrdered, Player::GetPlayerInfects);
            UpdateOffsets(drawnCount);
        }
    }
}