#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE  "EventBus"

strict namespace EventBus
{
    internal EventBusEventContextT _eventBusEvents[10];

    // Tracks the number of events registered so we can determine if more can be added.
    internal int _eventCount = 0;

    void AddEventBusCallbackByScriptName(str eventKey, str scriptName)
    {
        int index = EnsureEventExists(eventKey);
        if (index == -1)
        {
            Logger::LogError(LOGSOURCE , "Failed to add event " + eventKey + " with script name callback " + scriptName +". Maximum event bus capacity reached of " + str(lengthof(_eventBusEvents)) + ".");
            return;
        }

        // Add callback if there is space.
        if (lengthof(_eventBusEvents[index].ScriptNameCallbacks) == _eventBusEvents[index].ScriptNameCallbackCount)
        {
            Logger::LogError(LOGSOURCE , "Failed to add event " + eventKey + " with script name callback " + scriptName +". Maximum event callback capacity reached of " + str(_eventBusEvents[index].ScriptNameCallbackCount) + ".");
            return;
        }

        Logger::LogDebug(LOGSOURCE , "Added new event event callback for \cd" + eventKey + "\cj: \cd" + scriptName + "\cj.");
        _eventBusEvents[index].ScriptNameCallbacks[_eventBusEvents[index].ScriptNameCallbackCount] = scriptName;
        _eventBusEvents[index].ScriptNameCallbackCount++;
    }

    void AddEventBusCallbackByScriptNumber(str eventKey, int scriptNumber)
    {
        int index = EnsureEventExists(eventKey);
        if (index == -1)
        {
            Logger::LogError(LOGSOURCE , "Failed to add event " + eventKey + " with script number callback " + str(scriptNumber) +". Maximum event bus capacity reached of " + str(lengthof(_eventBusEvents)) + ".");
            return;
        }

        // Add callback if there is space.
        if (lengthof(_eventBusEvents[index].ScriptNumberCallbacks) == _eventBusEvents[index].ScriptNumberCallbackCount)
        {
            Logger::LogError(LOGSOURCE , "Failed to add event " + eventKey + " with script number callback " + str(scriptNumber) +". Maximum event callback capacity reached of " + str(_eventBusEvents[index].ScriptNumberCallbackCount) + ".");
            return;
        }

        Logger::LogDebug(LOGSOURCE , "Added new event event callback for \cd" + eventKey + "\cj: \cd" + str(scriptNumber) + "\cj.");
        _eventBusEvents[index].ScriptNumberCallbacks[_eventBusEvents[index].ScriptNumberCallbackCount] = scriptNumber;
        _eventBusEvents[index].ScriptNumberCallbackCount++;
    }

    void CallEvent(str eventKey, raw arg1 = 0, raw arg2 = 0, raw arg3 = 0)
    {
        Logger::LogDebug(LOGSOURCE , "Calling event " + eventKey + ".");
        int index = GetEventIndexByKey(eventKey);
        if (index == -1)
        {
            Logger::LogDebug(LOGSOURCE , "Event " + eventKey + " was not found.");
            return;
        }

        int scriptNameCallbackCount = _eventBusEvents[index].scriptNameCallbackCount;
        for (int i = 0; i < scriptNameCallbackCount; ++i)
        {
            str scriptName = _eventBusEvents[index].scriptNameCallbacks[i];
            if (!ACS_NamedExecuteAlways(scriptName, 0, arg1, arg2, arg3))
            {
                Logger::LogError(LOGSOURCE , "Failed to call script " + scriptName + " callback under event with key " + eventKey + ".");
                continue;
            }
        }

        int scriptNumberCallbackCount = _eventBusEvents[index].scriptNumberCallbackCount;
        for (int i = 0; i < scriptNumberCallbackCount; ++i)
        {
            int scriptNumber = _eventBusEvents[index].scriptNumberCallbacks[i];
            if (!ACS_ExecuteAlways(scriptNumber, 0, arg1, arg2, arg3))
            {
                Logger::LogError(LOGSOURCE , "Failed to call script " + str(scriptNumber) + " callback under event with key " + eventKey + ".");
                continue;
            }
        }
    }

    internal int EnsureEventExists(str eventKey)
    {
        int index = GetEventIndexByKey(eventKey);
        if (index != -1) return index;

        // Ensure we have space
        if (lengthof(_eventBusEvents) == _eventCount) return -1;

        Logger::LogDebug(LOGSOURCE , "Added new event bus event \cd" + eventKey + "\cj on index \cd" + str(_eventCount) + "\cj.");
        _eventBusEvents[_eventCount++].eventKey = eventKey;
        return _eventCount - 1;
    }

    internal int GetEventIndexByKey(str eventKey)
    {
        for (int i = 0; i < _eventCount; ++i)
        {
            if (BCSUtils::StrIEquals(eventKey, _eventBusEvents[i].eventKey)) return i;
        }

        return -1;
    }
}

#undef LOGSOURCE 
