#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    // This handles setting the graphic used for the z-tele counter for zombies.
    internal str ConsolePlayerSkinToZombieTeleportGraphic()
    {
        int indexAcs = GetPlayerSkin(ConsolePlayerNumber(), PLAYERSKIN_VISIBLE);
        if (indexAcs == -1)
            return (raw)0;

        switch ((str)GetSkinProperty(indexAcs, "Name"))
        {
            case SKIN_ZOMBIEOLD: return HUD_ZTELE_ZOMBIEOLD;
            case SKIN_ZOMBIEINITIAL: return HUD_ZTELE_ZOMBIEINITIAL;
            case SKIN_ZOMBIEREGULAR: return HUD_ZTELE_ZOMBIEREGULAR;

            default:
                return (raw)0;
        }
    }
}