#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Weapon
{
    bool CheckOwned(int weaponType, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        return ((raw)className) != 0 && CheckInventory(className) > 0;
    }

    void Give(int weaponType, int amount, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        if (((raw)className) != 0)
            GiveInventory(className, amount);
    }

    internal bool CheckActorOwned(int tid, int weaponType, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        return ((raw)className) != 0 && CheckActorInventory(tid, className) > 0;
    }

    internal void GiveActor(int tid, int weaponType, int amount, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        if (((raw)className) != 0)
            GiveActorInventory(tid, className, amount);
    }
}
