#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Weapon
{
    bool CheckOwned(int weaponType, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        return ((raw)className) != 0 && CheckInventory(className) > 0;
    }

    void Give(int weaponType, int amount, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        if (((raw)className) != 0)
            GiveInventory(className, amount);
    }

    internal bool CheckActorOwned(int tid, int weaponType, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        return ((raw)className) != 0 && CheckActorInventory(tid, className) > 0;
    }

    internal void GiveActor(int tid, int weaponType, int amount, int skin = WEAPONSKIN_BESTFIT)
    {
        str className = GetWeaponClassName(weaponType, skin);
        if (((raw)className) != 0)
            GiveActorInventory(tid, className, amount);
    }

    // A 50% chance to get a fire grenade one second into playing.
    // TODO: Replace with better distribution.
    // NOTE: Logic was moved away from the ENTER script due to desync issues.
    // Zandronum doesn't like it when I give weapons to the player, whilst also setting the wielded weapon.
    internal void FireGrenadeBonusTic()
    {
        if (!Player::GetIsHuman() || Player::GetPlayerState(PlayerNumber()) != Player::STATEPLAYING)
            return;

        if (Player::GetPlayTics() != 35)
            return;

        if (!BCSUtils::RandBool())
            return;

        Give(WEAPONTYPE_FIREGRENADE, 1);
        GiveInventory(WEAPON_AMMO_FIREGRENADE_NAME, 1);

        Logger::LogActivator("You have received a fire grenade!");
    }
}
