#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Weapon spawn spots could be unlimited but we need some limit here.
#define MAX_WEAPONSPAWNSPOTS 200

strict namespace Weapon
{
    internal enum WeaponTypeT : int
    {
        WEAPONTYPE_CHAINGUN,
        WEAPONTYPE_CLAWS,
        WEAPONTYPE_DOUBLESHOTGUN,
        WEAPONTYPE_FIREGRENADE,
        WEAPONTYPE_HANDGUN,
        WEAPONTYPE_JACKSGUN,
        WEAPONTYPE_RADIO,
        WEAPONTYPE_RIOTGUN,
        WEAPONTYPE_SHOTGUN,
        WEAPONTYPE_SNIPER,
    };

    // A tracked fake weapon spawn spot. `WeaponType` indicates what should be spawned in its place.
    internal struct WeaponSpawnSpotT
    {
        int Tid;
        WeaponTypeT WeaponType;
    };

    internal struct WeaponSpawnContextT
    {
        WeaponSpawnSpotT Spots[MAX_WEAPONSPAWNSPOTS];
        int SpotCount;
    };
}
