#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Weapon
{
    internal bool CheckWieldedChaingun() { return CheckWeapon(WEAPON_CHAINGUN_DEFAULT_NAME) || CheckWeapon(WEAPON_CHAINGUN_LEGACY_NAME); }
    internal bool CheckWieldedClaws() { return CheckWeapon(WEAPON_CLAWS_DEFAULT_NAME) || CheckWeapon(WEAPON_CLAWS_LEGACY_NAME); }
    internal bool CheckWieldedDoubleShotgun() { return CheckWeapon(WEAPON_DOUBLESHOTGUN_DEFAULT_NAME) || CheckWeapon(WEAPON_DOUBLESHOTGUN_LEGACY_NAME); }
    internal bool CheckWieldedFireGrenade() { return CheckWeapon(WEAPON_FIREGRENADE_DEFAULT_NAME) || CheckWeapon(WEAPON_FIREGRENADE_LEGACY_NAME); }
    internal bool CheckWieldedHandgun() { return CheckWeapon(WEAPON_HANDGUN_DEFAULT_NAME) || CheckWeapon(WEAPON_HANDGUN_LEGACY_NAME); }
    internal bool CheckWieldedJacksGun() { return CheckWeapon(WEAPON_JACKSGUN_DEFAULT_NAME) || CheckWeapon(WEAPON_JACKSGUN_LEGACY_NAME); }
    internal bool CheckWieldedRadio() { return CheckWeapon(WEAPON_RADIO_DEFAULT_NAME) || CheckWeapon(WEAPON_RADIO_LEGACY_NAME); }
    internal bool CheckWieldedRiotGun() { return CheckWeapon(WEAPON_RIOTGUN_DEFAULT_NAME) || CheckWeapon(WEAPON_RIOTGUN_LEGACY_NAME); }
    internal bool CheckWieldedShotgun() { return CheckWeapon(WEAPON_SHOTGUN_DEFAULT_NAME) || CheckWeapon(WEAPON_SHOTGUN_LEGACY_NAME); }
    internal bool CheckWieldedSniper() { return CheckWeapon(WEAPON_SNIPER_DEFAULT_NAME) || CheckWeapon(WEAPON_SNIPER_LEGACY_NAME); }
}
