#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LogSource "IO"

// There are three different stages of parsing supported:
// - Mod parses the zhmoddef in full for its data and stores this in a persisting struct. This contains a lot of metadata like starting weapons.
// - MapBase parses the base map data that is defined in zhmapdef lumps.
//   This is the base parse and not a detailed parse. We don't parse things like resists, for example. It would be way too much with many map.
//   Specifically this is creating persisting data of what maps are defined and where we can find this data.
// - MapDetailed extends on the MapBase and parses the remaining data that the map has defined.
//   This is NOT persisting, and we only parse the map currently being played.
// TODO: Should split the base into two more. We only need certain properties when the map ended?

#include "mod/mod.acs"
#include "mapbase/mapbase.acs"
#include "mapdetailed/mapdetailed.acs"

strict namespace IO
{
}

#undef LogSource