#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace IO
{
    internal bool ParseItems(int handle, str identifyingSymbol)
    {
        // Also supporting plurals
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "items"))
            return false;

        Logger::LogDebug(LOGSOURCE, "Start parsing items.");

        int braceLevel = Tokenizer::GetBraceLevel(handle);
        if (!Tokenizer::ExpectNextChar(handle, '{'))
            return false;

        Tokenizer::Next(handle);

        // While the brace level does not match the end level, we keep parsing.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) != braceLevel)
        {
            if (ParseItem(handle))
                continue;

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing items: '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        // Peek next character, see if we have a comma.
        // These are optional and if so, make sure to skip it.
        Tokenizer::Next(handle, false);
        if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
            Tokenizer::Next(handle, false);

        Logger::LogDebug(LOGSOURCE, "Finished parsing items of this lump.");
        return true;
    }

    internal bool ParseItem(int handle)
    {
        if (!BCSUTILS::StrIEquals(Tokenizer::GetSymbol(handle), "item"))
            return false;

        Logger::LogDebug(LOGSOURCE, "Start parsing single item.");
        Tokenizer::Next(handle);

        // Expecting a string-like type for the name
        Tokenizer::TokenTypeT token = Tokenizer::GetToken(handle);
        if (token != Tokenizer::TSYMBOL && token != Tokenizer::TSTRING)
        {
            Tokenizer::SetErrored(handle, "Expected symbol or string for item, received '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        str name = Tokenizer::GetSymbol(handle);

        if (!Tokenizer::ExpectNextToken(handle, Tokenizer::TLBRACE)) return false;
        int braceLevel = Tokenizer::GetBraceLevel(handle);

        Tokenizer::Next(handle);

        // No more room for more items. Log a warning and skip the remaining body.
        int count = ZH2Game::PersistingGameContext.ItemCollection.Size;
        if (count >= MAX_ITEMS)
        {
            Logger::LogWarning(LOGSOURCE, "The maximum number of configurable items was reached (" + str(count) + ").");
            Tokenizer::ParseRemainingBodyAsEmpty(handle);
            return true;
        }

        // As long as we are inside this body, parse properties and insert them into the new item.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) == braceLevel)
        {
            str symbol = Tokenizer::GetSymbol(handle);
            if (ParseItemSpecieOwned(handle, symbol)
                || ParseItemGiveOnSpawn(handle, symbol)
                || ParseItemGiveOnSpecie(handle, symbol)
                || ParseItemType(handle, symbol)
                || ParseItemGraphic(handle, symbol)
                || ParseItemLabel(handle, symbol)
                || ParseItemDescription(handle, symbol)
                || ParseItemBloodSeverity(handle, symbol)
                || ParseItemBloodTics(handle, symbol)
                || ParseItemKickback(handle, symbol)
                || ParseItemTakeOnPanic(handle, symbol)
                || ParseItemObituaryGraphic(handle, symbol)
                || ParseItemObituaryGraphicWidth(handle, symbol)
                || ParseItemWeaponType(handle, symbol)
                || ParseItemSkin(handle, symbol)
                || ParseItemSpawnClassName(handle, symbol))
            {
                // Optional comma.
                Tokenizer::Next(handle, false);
                if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
                    Tokenizer::Next(handle, false);

                continue;
            }

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing an item: '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.Name = name;

        // Optional comma.
        Tokenizer::Next(handle, false);
        if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
            Tokenizer::Next(handle, false);

        // TODO: Log data
        Logger::LogDebug(LOGSOURCE, "Finished parsing item: \cd" + context.Name + "\cj.");
        ZH2Game::PersistingGameContext.ItemCollection.Size++;
        return true;
    }

    internal bool ParseItemSpecieOwned(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "humanowned")
            && !BCSUTILS::StrIEquals(identifyingSymbol, "zombieowned")) return false;

        str specie = Tokenizer::GetSymbol(handle);
        Tokenizer::Next(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        if (BCSUTILS::StrIEquals(specie, "humanowned")) context.HumanOwned = true;
        else context.ZombieOwned = true;

        Logger::LogDebug(LOGSOURCE, "Parsed item specie owned. Specie symbol: \cd" + specie + "\cj.");
        return true;
    }

    internal bool ParseItemGiveOnSpawn(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "giveonspawn")) return false;

        str specie = Tokenizer::GetSymbol(handle);
        Tokenizer::Next(handle);

        if (!Tokenizer::TryParseIntValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for GiveOnSpawn is not a correct value. Expected a valid numeric value within bounds.");
            return false;
        }

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];

        int parsedValue = (int)Tokenizer::GetParsedValue();
        context.GiveOnSpawnCount = parsedValue;

        Logger::LogDebug(LOGSOURCE, "Parsed item give on spawn. Amount: \cd" + str(parsedValue) + "\cj.");
        return true;
    }

    internal bool ParseItemGiveOnSpecie(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "giveonhuman")
            && !BCSUTILS::StrIEquals(identifyingSymbol, "giveonzombie")) return false;

        str specie = Tokenizer::GetSymbol(handle);
        Tokenizer::Next(handle);

        if (!Tokenizer::TryParseIntValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for GiveOnHuman/GiveOnZombie is not a correct value. Expected a valid numeric value within bounds.");
            return false;
        }

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];

        int parsedValue = (int)Tokenizer::GetParsedValue();
        if (BCSUTILS::StrIEquals(specie, "giveonhuman")) context.GiveOnHumanCount = parsedValue;
        else context.GiveOnZombieCount = parsedValue;

        Logger::LogDebug(LOGSOURCE, "Parsed item give on specie. Specie symbol: \cd" + specie + "\cj. Amount: \cd" + str(parsedValue) + "\cj.");
        return true;
    }

    internal bool ParseItemType(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "isweaponitem")
            && !BCSUTILS::StrIEquals(identifyingSymbol, "isinventoryitem")
            && !BCSUTILS::StrIEquals(identifyingSymbol, "iskeyitem")) return false;

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.Type = BCSUTILS::StrIEquals(identifyingSymbol, "isweaponitem") ? Item::TYPE_WEAPON
                     : BCSUTILS::StrIEquals(identifyingSymbol, "isinventoryitem") ? Item::TYPE_INVENTORY
                     : BCSUTILS::StrIEquals(identifyingSymbol, "iskeyitem") ? Item::TYPE_KEY
                     : Item::TYPE_NONE;

        Logger::LogDebug(LOGSOURCE, "Parsed item type: " + str(context.Type) + ".");
        return true;
    }

    internal bool ParseItemGraphic(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "graphic")) return false;
        Tokenizer::Next(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.Graphic = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed item graphic: \cd" + context.Graphic + "\cj.");
        return true;
    }

    internal bool ParseItemLabel(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "label")) return false;
        Tokenizer::Next(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.Label = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed item label: \cd" + context.Label + "\cj.");
        return true;
    }

    internal bool ParseItemDescription(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "description")) return false;
        Tokenizer::Next(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.Description = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed item description: \cd" + context.Description + "\cj.");
        return true;
    }

    internal bool ParseItemBloodSeverity(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "bloodseverity")) return false;
        Tokenizer::Next(handle);

        if (!Tokenizer::TryParseIntValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for blood severity is not a correct value. Expected a valid numeric value within bounds.");
            return false;
        }

        int parsedValue = (int)Tokenizer::GetParsedValue();
        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.BloodSeverity = parsedValue;

        Logger::LogDebug(LOGSOURCE, "Parsed blood severity: \cd" + str(context.BloodSeverity) + "\cj.");
        return true;
    }

    internal bool ParseItemBloodTics(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "bloodtics")) return false;
        Tokenizer::Next(handle);

        if (!Tokenizer::TryParseIntValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for blood tics is not a correct value. Expected a valid numeric value within bounds.");
            return false;
        }

        int parsedValue = (int)Tokenizer::GetParsedValue();
        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.BloodTics = parsedValue;

        Logger::LogDebug(LOGSOURCE, "Parsed blood tics: \cd" + str(context.BloodTics) + "\cj.");
        return true;
    }

    internal bool ParseItemKickback(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "kickback")) return false;
        Tokenizer::Next(handle);

        if (!Tokenizer::TryParseIntValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for kickback is not a correct value. Expected a valid numeric value within bounds.");
            return false;
        }

        int parsedValue = (int)Tokenizer::GetParsedValue();
        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.Kickback = parsedValue;

        Logger::LogDebug(LOGSOURCE, "Parsed kickback: \cd" + str(context.Kickback) + "\cj.");
        return true;
    }

    internal bool ParseItemTakeOnPanic(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "takeonpanic")) return false;

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.TakeOnPanic = true;

        Logger::LogDebug(LOGSOURCE, "Parsed item take on panic.");
        return true;
    }

    internal bool ParseItemObituaryGraphic(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "obituarygraphic")) return false;
        Tokenizer::Next(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.ObituaryGraphic = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed item obituary graphic: \cd" + context.ObituaryGraphic + "\cj.");
        return true;
    }

    internal bool ParseItemObituaryGraphicWidth(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "obituarygraphicwidth")) return false;
        Tokenizer::Next(handle);

        if (!Tokenizer::TryParseIntValue(handle))
        {
            Tokenizer::SetErrored(handle, "The given value for obituary graphic width is not a correct value. Expected a valid numeric value within bounds.");
            return false;
        }

        int parsedValue = (int)Tokenizer::GetParsedValue();
        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.ObituaryGraphicWidth = parsedValue;

        Logger::LogDebug(LOGSOURCE, "Parsed item obituary graphic width: \cd" + str(context.ObituaryGraphicWidth) + "\cj.");
        return true;
    }

    internal bool ParseItemWeaponType(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "weapontype")) return false;
        Tokenizer::Next(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.WeaponType = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed item weapon type: \cd" + context.WeaponType + "\cj.");
        return true;
    }

    internal bool ParseItemSkin(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "skin")) return false;
        Tokenizer::Next(handle);

        str skin = Tokenizer::GetSymbol(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        if (BCSUTILS::StrIEquals(skin, "default")) context.Skin = Item::ITEMSKIN_DEFAULT;
        else if (BCSUTILS::StrIEquals(skin, "legacy")) context.Skin = Item::ITEMSKIN_LEGACY;
        else
        {
            Tokenizer::SetErrored(handle, "The given value for skin is not a correct value. Expected 'Default' or 'Legacy', received '" + skin + "'.");
            return false;
        }

        Logger::LogDebug(LOGSOURCE, "Parsed item skin: \cd" + str(context.Skin) + "\cj.");
        return true;
    }

    internal bool ParseItemSpawnClassName(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "spawnclassname")) return false;
        Tokenizer::Next(handle);

        Item::ItemContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.ItemCollection.Collection[ZH2Game::PersistingGameContext.ItemCollection.Size];
        context.SpawnClassName = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed item spawn class name: \cd" + context.SpawnClassName + "\cj.");
        return true;
    }
}