#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace IO
{
    internal bool ParsePowers(int handle, str identifyingSymbol)
    {
        // Also supporting plurals
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "powers"))
            return false;

        Logger::LogDebug(LOGSOURCE, "Start parsing powers.");

        int braceLevel = Tokenizer::GetBraceLevel(handle);
        if (!Tokenizer::ExpectNextChar(handle, '{'))
            return false;

        Tokenizer::Next(handle);

        // While the brace level does not match the end level, we keep parsing.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) != braceLevel)
        {
            if (ParsePower(handle))
                continue;

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing powers: '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        // Peek next character, see if we have a comma.
        // These are optional and if so, make sure to skip it.
        Tokenizer::Next(handle, false);
        if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
            Tokenizer::Next(handle, false);

        Logger::LogDebug(LOGSOURCE, "Finished parsing powers.");
        return true;
    }

    internal bool ParsePower(int handle)
    {
        if (!BCSUTILS::StrIEquals(Tokenizer::GetSymbol(handle), "power"))
            return false;

        Logger::LogDebug(LOGSOURCE, "Start parsing single power.");
        Tokenizer::Next(handle);

        // Expecting a string-like type for the name
        Tokenizer::TokenTypeT token = Tokenizer::GetToken(handle);
        if (token != Tokenizer::TSYMBOL && token != Tokenizer::TSTRING)
        {
            Tokenizer::SetErrored(handle, "Expected symbol or string for power name, received '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        str name = Tokenizer::GetSymbol(handle);
        int braceLevel = Tokenizer::GetBraceLevel(handle);

        if (!Tokenizer::ExpectNextToken(handle, Tokenizer::TLBRACE)) return false;
        Tokenizer::Next(handle);

        // No more room for more powers. Log a warning and skip the remaining body.
        int index = ZH2Game::PersistingGameContext.PowerCollection.Size;
        if (index >= MAX_POWERS)
        {
            Logger::LogWarning(LOGSOURCE, "The maximum number of configurable powers was reached (" + str(index) + ").");
            Tokenizer::ParseRemainingBodyAsEmpty(handle);
            return true;
        }

        // As long as we are inside this body, parse properties and insert them into the new power.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) != braceLevel)
        {
            str symbol = Tokenizer::GetSymbol(handle);
            if (ParsePowerHudGraphicAttribute(handle, symbol)
                || ParsePowerMaxTicsAttribute(handle, symbol)
                || ParsePowerDefaultFactor(handle, symbol))
            {
                // Optional comma.
                Tokenizer::Next(handle, false);
                if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
                    Tokenizer::Next(handle, false);

                continue;
            }

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing a power: '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        Power::PowerContextT global:PERSISTING_GAME_CONTEXT_INDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[index];

        context.Name = name;

        // We don't verify the power. The index has now been used and code could merely check for the index to exist.

        // Optional comma.
        Tokenizer::Next(handle, false);
        if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
            Tokenizer::Next(handle, false);

        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            Append(s:"Parsed power \cd" + context.Name + "\cj.");

            if ((raw)context.HudGraphic != 0)
                Append(s:" Hud graphic: \cd" + context.HudGraphic + "\cj.");

            // TODO: Reference properly instead of inline. It didn't work properly otherwise.
            int maxTics = Power::GetPowerMaxTics(index);
            if (maxTics != 0)
                Append(s:" Max tics: \cd" + str(maxTics) + "\cj.");

            for(int i = 0; i < MAX_POWER_TYPES; ++i)
            {
                // TODO: Reference properly instead of inline. It didn't work properly otherwise.
                if (!Power::GetPowerDefaultFactorDefined(index, i))
                    continue;

                str name = Power::GetPowerFactorName(i);

                // TODO: Reference properly instead of inline. It didn't work properly otherwise.
                fixed factor = Power::GetPowerDefaultFactorValue(index, i);
                Append(s:" Factor \cd" + name + "\cj: \cd" + str(factor) + "\cj.");
            }
        }

        Logger::LogDebug(LOGSOURCE, logMessage);

        ZH2Game::PersistingGameContext.PowerCollection.Size++;
        return true;
    }

    internal bool ParsePowerHudGraphicAttribute(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "hudgraphic")) return false;
        Tokenizer::Next(handle);

        Power::PowerContextT global:PERSISTING_GAME_CONTEXT_INDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[ZH2Game::PersistingGameContext.PowerCollection.Size];

        // Already parsed
        if (context.HudGraphic != (str)0)
        {
            Tokenizer::SetErrored(handle, "Failed to parse power attribute: The power's hud graphic was previously defined. You can only define the hud graphic once, or make a new power.");
            return false;
        }

        str graphic = Tokenizer::GetSymbol(handle);
        context.HudGraphic = graphic;

        Logger::LogDebug(LOGSOURCE, "Parsed power graphic: \cd" + graphic + "\cj.");
        return true;
    }

    internal bool ParsePowerMaxTicsAttribute(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "maxtics")) return false;
        Tokenizer::Next(handle);

        Power::PowerContextT global:PERSISTING_GAME_CONTEXT_INDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[ZH2Game::PersistingGameContext.PowerCollection.Size];

        // Already parsed
        if (context.MaxTics != 0)
        {
            Tokenizer::SetErrored(handle, "Failed to parse power attribute: The power's maximum tics was previously defined. You can only define the maximum tics once, or make a new power.");
            return false;
        }

        if (!Tokenizer::TryParseBooleanOrNumbericValue(handle))
        {
            Tokenizer::SetErrored(handle, "Failed to parse power attribute: the given value for MaxTics is not a correct value. Expected numeric value within bounds.");
            return false;
        }

        int value = (int)Tokenizer::GetParsedValue();
        context.MaxTics = value;

        Logger::LogDebug(LOGSOURCE, "Parsed power maxtics: \cd" + str(value) + "\cj.");
        return true;
    }

    internal bool ParsePowerDefaultFactor(int handle, str identifyingSymbol)
    {
        // Determine the type.
        Power::PowerFactorTypeT factorType;
        switch(BCSUTILS::StrToLower(identifyingSymbol))
        {
            case "speedmodifier": factorType = Power::POWERTYPE_SPEED; break;
            case "jumpmodifier": factorType = Power::POWERTYPE_JUMP; break;
            case "damagefactor": factorType = Power::POWERTYPE_DAMAGEFACTOR; break;
            case "damagemultiplier": factorType = Power::POWERTYPE_DAMAGEMULTIPLIER; break;
            case "knockbackmodifier": factorType = Power::POWERTYPE_KNOCKBACK; break;

            // Not a factor.
            default: return false;
        }

        str name = Power::GetPowerFactorName(factorType);
        Tokenizer::Next(handle);

        int index = ZH2Game::PersistingGameContext.PowerCollection.Size;

        // Already parsed
        if (Power::GetPowerDefaultFactorDefined(index, factorType))
        {
            Tokenizer::SetErrored(handle, "Failed to parse power factor " + name + ": The factor was previously defined. You can only define each factor once, or make a new power.");
            return false;
        }

        if (!Tokenizer::TryParseFixedValue(handle))
        {
            Tokenizer::SetErrored(handle, "Failed to parse power factor " + name + ": the given value for the factor is not a correct value. Expected a valid fixed value within bounds.");
            return false;
        }

        fixed value = (fixed)Tokenizer::GetParsedValue();
        Power::SetPowerDefaultFactorValue(index, factorType, value);
        Power::SetPowerDefaultFactorDefined(index, factorType, true);

        Logger::LogDebug(LOGSOURCE, "Parsed power factor \cd" + name + "\cj: \cd" + str(value) + "\cj.");
        return true;
    }
}