#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace IO
{
    internal bool ParseWeaponSpawners(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "weaponspawners"))
            return false;

        Logger::LogDebug(LOGSOURCE, "Start parsing weapon spawners.");

        int braceLevel = Tokenizer::GetBraceLevel(handle);
        if (!Tokenizer::ExpectNextChar(handle, '{'))
            return false;

        Tokenizer::Next(handle);

        // While the brace level does not match the end level, we keep parsing.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) != braceLevel)
        {
            if (ParseWeaponSpawner(handle))
                continue;

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing weapon spawners: '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        // Peek next character, see if we have a comma.
        // These are optional and if so, make sure to skip it.
        Tokenizer::Next(handle, false);
        if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
            Tokenizer::Next(handle, false);

        Logger::LogDebug(LOGSOURCE, "Finished parsing weapon spawners of this lump.");
        return true;
    }

    internal bool ParseWeaponSpawner(int handle)
    {
        if (!BCSUTILS::StrIEquals(Tokenizer::GetSymbol(handle), "weaponspawner"))
            return false;

        Logger::LogDebug(LOGSOURCE, "Start parsing single weapon spawner.");
        Tokenizer::Next(handle);

        // Expecting a string-like type for the name
        Tokenizer::TokenTypeT token = Tokenizer::GetToken(handle);
        if (token != Tokenizer::TSYMBOL && token != Tokenizer::TSTRING)
        {
            Tokenizer::SetErrored(handle, "Expected symbol or string for weapon spawner, received '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        str name = Tokenizer::GetSymbol(handle);

        if (!Tokenizer::ExpectNextToken(handle, Tokenizer::TLBRACE)) return false;
        int braceLevel = Tokenizer::GetBraceLevel(handle);

        Tokenizer::Next(handle);

        // No more room for more weapon spawners. Log a warning and skip the remaining body.
        int count = ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Size;
        if (count >= MAX_WEAPONSPAWNERS)
        {
            Logger::LogWarning(LOGSOURCE, "The maximum number of configurable weapon spawners was reached (" + str(count) + ").");
            Tokenizer::ParseRemainingBodyAsEmpty(handle);
            return true;
        }

        // As long as we are inside this body, parse properties and insert them into the new weapon spawner.
        while (Tokenizer::CanRead(handle) && Tokenizer::GetBraceLevel(handle) == braceLevel)
        {
            str symbol = Tokenizer::GetSymbol(handle);
            if (ParseWeaponSpawnerSpawnSpotClassName(handle, symbol)
                || ParseWeaponSpawnerResolverClassName(handle, symbol)
                || ParseWeaponSpawnerAmmoClassName(handle, symbol))
            {
                // Optional comma.
                Tokenizer::Next(handle, false);
                if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
                    Tokenizer::Next(handle, false);

                continue;
            }

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing weapon spawner: '" + Tokenizer::GetSymbol(handle) + "'.");
            return false;
        }

        Weapon::WeaponSpawnerConfigT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Collection[ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Size];
        context.Name = name;

        // Optional comma.
        Tokenizer::Next(handle, false);
        if (Tokenizer::GetToken(handle) == Tokenizer::TCOMMA)
            Tokenizer::Next(handle, false);

        Logger::LogDebug(LOGSOURCE, "Finished parsing weapon spawner: \cd" + context.Name + "\cj.");
        ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Size++;
        return true;
    }

    internal bool ParseWeaponSpawnerSpawnSpotClassName(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "spawnspotclassname")) return false;
        Tokenizer::Next(handle);

        Weapon::WeaponSpawnerConfigT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Collection[ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Size];
        context.SpawnSpotClassName = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed weapon spawner spawn spot class name: \cd" + context.SpawnSpotClassName + "\cj.");
        return true;
    }

    internal bool ParseWeaponSpawnerResolverClassName(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "resolverclassname")) return false;
        Tokenizer::Next(handle);

        Weapon::WeaponSpawnerConfigT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Collection[ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Size];
        context.ResolverClassName = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed weapon spawner resolver class name: \cd" + context.ResolverClassName + "\cj.");
        return true;
    }

    internal bool ParseWeaponSpawnerAmmoClassName(int handle, str identifyingSymbol)
    {
        if (!BCSUTILS::StrIEquals(identifyingSymbol, "ammoclassname")) return false;
        Tokenizer::Next(handle);

        Weapon::WeaponSpawnerConfigT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Collection[ZH2Game::PersistingGameContext.WeaponSpawnerCollection.Size];
        context.AmmoClassName = Tokenizer::GetSymbol(handle);

        Logger::LogDebug(LOGSOURCE, "Parsed weapon spawner ammo class name: \cd" + context.AmmoClassName + "\cj.");
        return true;
    }
}
