#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define TICTOSECOND 2.85714285714

strict namespace Utils
{
    extern int PlayingBotCount();
    extern str WrapString(str input, int maxLength);
    extern str TruncateString(str input, int limit, str suffix = "...");
    extern str FormatTics(int tics, bool includeDecimals = false);
    extern str FormatDecimals(fixed value, int decimalCount);

    extern int GetSynchronizedTimer(void);
    extern void InitializeSynchronizedTimerForPlayer(int playerId);
    extern void ScaleToScreen();

    extern bool GetIsMoving();
    extern bool GetPlayerIsMoving (int id);
}