#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawDamageCount()
    {
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(1280.0, 960.0);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        PrepareHud(640.0, 480.0, false);

        // Booleans are used to determine if we did hit once.
        // This ensures we can use tic 0 for displaying feedback.
        bool hasHitOnce = Player::GetHitFeedbackTics() > 0;
        bool hasKillOnce = Player::GetKillFeedbackTics() > 0;

        // Booleans indicate if the user configured the counters to show.
        ZH2Game::DamageFeedbackCounterShowTypeT counterShowType = ZH2Game::GetDamageFeedbackCounterShowType();
        bool showDamageCounters = counterShowType == ZH2Game::DAMAGEFEEDBACK_COUNTER_SHOW_DAMAGE || counterShowType == ZH2Game::DAMAGEFEEDBACK_COUNTER_SHOW_BOTH;
        bool showKillCounters = counterShowType == ZH2Game::DAMAGEFEEDBACK_COUNTER_SHOW_KILLS || counterShowType == ZH2Game::DAMAGEFEEDBACK_COUNTER_SHOW_BOTH;

        int elapsedHit = Player::GetElapsedHitFeedbackTics();
        int elapsedKill = Player::GetElapsedKillFeedbackTics();

        // These values indicate the max amount of tics the counters are shown for.
        int shownDamageTics = ZH2Game::GetDamageFeedbackDamageCounterShownTics();
        int shownKillTics = ZH2Game::GetDamageFeedbackKillCounterShownTics();

        fixed y = 20.0;

        int damageTicsLeft = BCSUtils::Max(0, shownDamageTics - elapsedHit);
        if (showDamageCounters && hasHitOnce && damageTicsLeft > 0)
        {
            fixed alpha = CalculateFeedbackAlpha(damageTicsLeft);
            fixed scale = CalculateFeedbackPulseScale(elapsedHit);
            int damageCount = Player::GetDamageCount();

            BCSUtils::HudSetAlpha(alpha);
            BCSUtils::HudSetScale(scale);

            HudSetPointInternal(0.0, y);
            BCSUtils::HudDrawText(--_drawnHudId, str(damageCount));

            y += 10.0;
        }

        int killTicsLeft = BCSUtils::Max(0, shownKillTics - elapsedKill);
        if (showKillCounters && hasKillOnce && killTicsLeft > 0)
        {
            fixed alpha = CalculateFeedbackAlpha(killTicsLeft);
            fixed scale = CalculateFeedbackPulseScale(elapsedKill);
            int killCount = Player::GetKillCount();

            BCSUtils::HudSetAlpha(alpha);
            BCSUtils::HudSetScale(scale);
            BCSUtils::HudSetTextColor(CR_RED);

            HudSetPointInternal(0.0, y);
            BCSUtils::HudDrawText(--_drawnHudId, str(killCount) + " kill" + (killCount != 1 ? "s" : ""));
        }
    }
}