#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawMarker()
    {
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(1280.0, 960.0);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);

        PrepareHud(640.0, 480.0, false);

        // Booleans are used to determine if we did hit once.
        // This ensures we can use tic 0 for displaying feedback.
        bool hasHitOnce = Player::GetHitFeedbackTics() > 0;
        bool hasKillOnce = Player::GetKillFeedbackTics() > 0;

        // First draw hit, then kill.
        // Kill will be drawn over any hit graphics.
        int elapsedHit = Player::GetElapsedHitFeedbackTics();
        int elapsedKill = Player::GetElapsedKillFeedbackTics();

        // TODO: replace with configurable length.
        int shownHitTics = 10;
        int shownKillTics = 35;

        int ticsLeft = BCSUtils::Max(0, shownHitTics - elapsedHit);
        if (hasHitOnce && ticsLeft > 0)
        {
            HudSetPointInternal();
            BCSUtils::HudSetAlpha(CalculateFeedbackAlpha(ticsLeft));
            BCSUtils::HudDrawImage(--_drawnHudId, FEEDBACK_HIT_GRAPHIC);
        }

        ticsLeft = BCSUtils::Max(0, shownKillTics - elapsedKill);
        if (hasKillOnce && ticsLeft > 0)
        {
            HudSetPointInternal();
            BCSUtils::HudSetAlpha(CalculateFeedbackAlpha(ticsLeft));
            BCSUtils::HudDrawImage(--_drawnHudId, FEEDBACK_KILL_GRAPHIC);
        }
    }
}