#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Packet
{
    #define PACKET_MSB_MASK 0x80000000

    #define PACKET_BYTE_BITS 7
    #define PACKET_WORD_SIZE 5

    #define PACKET_NATIVE_HEADER_SIZE 13

    extern raw Value;

    extern int GetMaxSize();
    extern int GetSize(str pac);
    extern str New();
    extern str Append(str pac, raw val);
    extern str AppendStr(str pac, str val);
    extern bool Send(str scriptName, str pac, int client = -1);
    extern str Read(str pac);
    extern str ReadStr(str pac);
    extern int PackValue(int pack, int pos, int width, raw v);
    extern raw UnpackValue(int pack, int pos, int width, bool signed = false);
}