#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace ZH2Game
{
    bool GetIsRequestGameStartKeyBound() { return BCSUtils::KeyBound("RequestGameStart"); }
    str GetRequestGameStartKey() { return StrParam(k:"RequestGameStart"); }

    script "zh2_action_requestgamestart" net
    {
        // Set the timer to be 1 second left if a timer is active and we either play offline, or the user is an admin.
        // Do not check for development, for now.
        if (/*Environment::IsDevelopment() &&*/ RoundTimer::GetAnyTimerActive() && (!IsNetworkGame() || Admin::GetIsAdmin()))
        {
            int index = RoundTimer::GetActiveTimerIndex();

            if (!RoundTimer::GetTimerDefined(index)) terminate;
            if (RoundTimer::GetTimerTicsLeft(index) < 1 * 35) terminate;

            // Removing 1 tic prevents the countdown ambient from playing every tic if it's the play timer.
            RoundTimer::SetTimerTicsLeft(index, 1 * 35 - 1);
            Logger::LogBold(BCSUTILS::PlayerName(PlayerNumber()) + " has sped up the timer.");

            Sync::SyncTimers();
            terminate;
        }

        // Otherwise check for pregame and start the countdown to start the map.
        // For this we should not already have the timer active.
        if (Round::GetActiveKnownRoundState() == Round::STATEPREGAME
            && RoundTimer::GetActiveTimerKnownType() != RoundTimer::TIMERPREGAMECOUNTDOWN)
        {
            int availableClients = BCSUtils::ClientCount();
            int minimumRequiredClients = ZH2Game::GetMinimumClientCount();
            if (availableClients < minimumRequiredClients)
            {
                Logger::LogActivator("The game requires atleast " + str(minimumRequiredClients) + " clients before starting.");
                terminate;
            }

            // Create the timer if it is not defined.
            int index = RoundTimer::GetIndexOfKnownType(RoundTimer::TIMERPREGAMECOUNTDOWN);
            if (!RoundTimer::GetTimerDefined(index))
            {
                if (RoundTimer::GetTimerSkin() == RoundTimer::TIMERSKIN_LEGACY)
                    RoundTimer::DefineKnownTimer(RoundTimer::TIMERPREGAMECOUNTDOWN, 10, 30, TIMER_DEFAULT_TOP_TEMPLATE, "Game is starting in %d s");
                else
                    RoundTimer::DefineKnownTimer(RoundTimer::TIMERPREGAMECOUNTDOWN, 10, 30, "Game is starting in");

                Logger::LogDebug(LOGSOURCE, "Created a pregame countdown as the timer was not defined.");
            }

            RoundTimer::SetActiveTimerByKnownType(RoundTimer::TIMERPREGAMECOUNTDOWN);
            RoundTimer::StartTimer(index);
            Logger::LogBold(BCSUtils::PlayerName(PlayerNumber()) + " has requested to start the game.");

            Sync::SyncTimers();
            terminate;
        }

        // Nothing triggered, so log a message instead.
        Logger::LogActivator("The game is already starting or has already started.");
    }

    script "zh2_action_sprint" (raw doSprint) net
    {
        Player::SetSprinting((bool)doSprint);
    }

    script "zh2_action_panic" net
    {
        Player::StartPanic();
    }

    script "zh2_action_zombieteleport" net
    {
        Game::CallZombieTeleport();
    }

    // Note: Can be called whilst dead. This works fine.
    script "zh2_action_toggleadminhud" net clientside
    {
        Admin::ToggleAdminHud();
    }

    script "zh2_action_consolidateclientsettings" net clientside
    {
        Settings::UpdateCurrentClientSettings();
        Settings::BroadcastClientConsolidateSettings(true);
    }

    script "zh2_action_enableclientsettingshud" net clientside
    {
        Settings::OpenClientSettingsMenu();
    }

    script "zh2_action_iteratezombieability" (raw directionRaw) net clientside
    {
        if (!BCSUtils::IsAlive())
            terminate;

        if (!Player::GetIsZombie())
            terminate;

        int direction = (int)directionRaw;
        int current = Game::GetSelectedAbilityIndex();
        int last = current;

        // Recursively iterate the ability.
        // We skip over abilities we don't own or are disabled.
        // This continues until we encountered the initial index which means we have no eligible index.
        do
        {
            current += direction;
            if (current < 0) current = ABILITY_COUNT - 1;
            else if (current >= ABILITY_COUNT) current = 0;

            Game::ZombieAbilityTypeFlagsT flag = Game::GetZombieAbilityItemTypeByIndex(current + 1);
            if (!Game::HasZombieAbility(flag)
                || (ZH2Game::GetDisabledZombieAbilityFlags() & flag) != 0)
            {
                continue;
            }

            Game::SetSelectedAbilityIndex(current);
            break;
        } while (current != last);
    }

    /* MUSIC */

    script "zh2_action_music_playdefault" net clientside
    {
        Music::PlayDefaultMusic();
    }

    /* INVENTORY */

    script "zh2_action_nextinventory" (raw direction) net clientside
    {
        Item::CycleNextInventory((int)direction);
    }

    script "zh2_action_invokeinventory" net clientside
    {
        Item::InvokeCurrentInventoryItem();
    }
}