#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Now handled through mapinfo.
//#define REQUIREDGAMEMODE "cooperative"

/* EVENTS */

#define EVENTINITIALSCHOSEN "initialschosen"
#define EVENTROUNDSWITCHED "roundswitched"

#define EVENTTIMERSWITCHED "timerswitched"
#define EVENTTIMERSTARTED "timerstarted"
#define EVENTTIMERPAUSED "timerresumed"
#define EVENTTIMERRESUMED "timerpaused"
#define EVENTTIMERSTOPPED "timerstopped"
#define EVENTTIMERELAPSED "timerelapsed"

#define EVENTRESISTSTARTED "resiststarted"
#define EVENTRESISTSTOPPED "resiststopped"
#define EVENTRESISTELAPSED "resistelapsed"

#define EVENTPLAYERDIED "playerdied"
#define EVENTPLAYERKILLEDBYPLAYER "playerkilledbyplayer"
#define EVENTPLAYERKILLEDBYMONSTER "playerkilledbymonster"

// Note, not for general leaving. Specific to when a player leaves a playing round.
#define EVENTPLAYERLEFTROUND "playerleftround"

#define EVENTPLAYERCURED "playercured"
#define EVENTPLAYERINFECTED "playerinfected"
#define EVENTPLAYERPRESCRATCHED "playerprescratched"
#define EVENTPLAYERSCRATCHED "playerscratched"
#define EVENTPLAYERSPECIECHANGED "playerspeciechanged"
#define EVENTPLAYERSAFE "playersafe"

#define EVENTPOWEREXPIRED "powerexpired"

#define EVENTACTORDAMAGED "actordamaged"
#define EVENTACTORDAMAGEDCLIENTTOTAL "actordamagedclienttotal"

// Build in tracks
#define TRACK_FULLSERVER "D_FULLSR"

/* GAME */
#define ACTOR_INITIALSPAWNSPOT_NAME "InitialSpawnSpot"
#define ACTOR_ZOMBIETELEPORTSPOT_NAME "ZombieTeleportSpot"


/* CLASSES */
#define CLASS_INVISIBLE "InvisiblePlayer"
#define CLASS_HUMAN "HumanPlayer"
#define CLASS_ZOMBIE "ZombiePlayer"

/* PLAYER SKINS */
#define SKIN_HUMAN "Default"
#define SKIN_HUMAN_GRENADE "FireGrenade"
#define SKIN_HUMAN_HANDGUN "Handgun"
#define SKIN_HUMAN_JACKSGUN "Jacksgun"
#define SKIN_HUMAN_SHOTGUN "Shotgun"
#define SKIN_HUMAN_DOUBLEBARRELEDSHOTGUN "Doubleshotgun"
#define SKIN_HUMAN_CHAINGUN "Chaingun"
#define SKIN_HUMAN_SNIPER "Sniperrifle"
#define SKIN_HUMAN_RIOTGUN "Riotgun"
#define SKIN_HUMAN_RADIO "Radio"
#define SKIN_ZOMBIEOLD "ZombieOld"
#define SKIN_ZOMBIEREGULAR "ZombieRegular"
#define SKIN_ZOMBIEINITIAL "ZombieInitial"

/* ITEMS */
#define KEVLAR_ITEM "ZH2ItemKevlar"
#define LEAPSTONE_ITEM "ZH2ItemLeapstone"
#define CURE_ITEM "ZH2ItemCure"
#define CRYSTAL_ITEM "ZH2ItemFireCrystal"
#define HOLYCROSS_ITEM "ZH2ItemHolyCross"
#define SYRINGE_ITEM "ZH2ItemSyringe"
#define ENERGY_ITEM "ZH2ItemEnergy"
#define FLARE_ITEM "ZH2ItemFlare"
#define FLAREBOX_ITEM "ZH2ItemFlareBox"
#define MEDIKIT_ITEM "ZH2ItemMedikit"
#define SUICIDE_BOMB_ITEM "ZH2ItemSuicideBomb"
#define CIRCULATOR_ITEM "ZH2ItemCirculator"
#define FIREMINE_ITEM "ZH2ItemFireMine"

#define MEDIKITHEALTH_ITEM "ZH2MedikitHealth"

#define SUICIDE_BOMB_ITEM_CONFIRM_TIMESTAMP "ZH2ItemSuicideBombConfirmTimestamp"

/* KEYS */
#define KEY_BLOODRUBY_NAME "ZH2LegacyBloodruby"
#define KEY_NIGHTSAPPHIRE_NAME "ZH2LegacyNightSapphire"
#define KEY_BLUE_KEYCARD "ZH2BlueKeycard"
#define KEY_RED_KEYCARD "ZH2RedKeycard"
#define KEY_YELLOW_KEYCARD "ZH2YellowKeycard"
#define KEY_BLUE_SKULL "ZH2BlueSkullKey"
#define KEY_RED_SKULL "ZH2RedSkullKey"
#define KEY_YELLOW_SKULL "ZH2YellowSkullKey"
#define KEY_BATTERY "ZH2LegacyZe19Battery"
#define KEY_CROWBAR "ZH2LegacyZe27Crowbar"
#define KEY_CAVEKEY "ZH2LegacyCaveKey"

/* CURRENCIES */
#define CURRENCY_CASH_NAME "ZH2EgyptCash"

/* MECHANICS */
#define SPRINT_ITEM "ZH2SprintEnergy"
#define KEVLAR_ARMOR_POINTS_ITEM "ZH2KevlarArmorPoints"
#define ZOMBIE_TELEPORT_TIMESTAMP_ITEM "ZH2ZombieTeleportTimestamp"
#define ZOMBIEABILITY_DO_ABILITY_ITEM "ZH2DoZombieAbilityIndex"
#define ZOMBIEABILITY_TIMESTAMP_BASE "ZH2ZombieAbility{0}Timestamp"
#define POWER_ACTOR_BASE "ZH2Power{0}TimeStamp"

#define SPRINT_ITEM_MAX 1000

/* EFFECTS */
#define HUMAN_BULLETPUFF "ZH2WeaponBulletPuff"

/* DAMAGE TYPES */
#define DAMAGETYPE_ZOMBIESCRATCH_NAME "ZH2ZombieScratch"
#define DAMAGETYPE_ZOMBIEPUSH_NAME "ZH2ZombiePush"
#define DAMAGETYPE_HUMANDEFAULT_NAME "ZH2HumanDefault"
#define DAMAGETYPE_SETONFIRE_NAME "ZH2SetOnFire" // Similar to Zombie Horde 1's FireG damagetype.

#define DAMAGETYPE_FIRE "ZH2Fire"
#define DAMAGETYPE_ACID "ZH2Acid"

/* OTHER STATS */
#define HEALTH_HUMANDANGEROUS 20
#define HEALTH_HUMANCRITICAL 10

#define HEALTH_ZOMBIEDANGEROUS 800
#define HEALTH_ZOMBIECRITICAL 300

#define MAX_AIRSUPPLY 35 * 20