#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace ZH2Game
{
    // Admin
    internal bool GetClAdminSpawnBotInFront(int playerId) { return (bool)GetUserCvar(playerId, "cl_zh2_adminspawnbotinfront"); }

    // Game
    internal int GetMinimumClientCount() { return BCSUTILS::Clamp(GetCvar("sv_zh2_minimumclientcount"), 0, BCSUTILS::MAX_PLAYERS); }
    internal bool GetInfectTimeIncrease() { return (bool)GetCvar("sv_zh2_infecttimeincrease"); }
    internal int GetPlayersPerInitial() { return BCSUTILS::Clamp(GetCvar("sv_zh2_playersperinitial"), 6, BCSUTILS::MAX_PLAYERS); }
    internal bool GetShowZombiesResists() { return (bool)GetCvar("sv_zh2_showzombiesresists"); }
    internal bool GetEnableFullServer() { return (bool)GetCvar("sv_zh2_enablefullserver"); }
    internal int GetFullServerRoundInterval() { return BCSUTILS::Clamp(GetCvar("sv_zh2_fullserverroundinterval"), 1, 100); }
    internal ZombieSkinBehaviourT GetZombieSkinBehaviour()
    {
        switch(BCSUTILS::Clamp(GetCvar("sv_zh2_zombieskinbehaviour"), 0, 2))
        {
            case 1:
                return BEHAVIOUR_FORCEOLDSKIN;
            case 2:
                return BEHAVIOUR_FORCENEWSKIN;
            default:
                return BEHAVIOUR_DEFAULT;
        }
    }

    internal int GetEndOfRoundRewardCount() { return BCSUTILS::Clamp(GetCvar("sv_zh2_endofroundrewardcount"), 0, 64); }
    internal bool GetEndOfRoundRewardSafePlayers() { return (bool)GetCvar("sv_zh2_endofroundrewardsafeplayers"); }

    // Game - Round
    internal InitialZombiePickMethodT GetInitialZombiePickMethod()
    {
        switch(BCSUTILS::Clamp(GetCVar("sv_zh2_initialpickmethod"), 0, 2))
        {
            case 1:
                return INITIALZOMBIEPICKMETHOD_LEGACY;
            case 2:
                return INITIALZOMBIEPICKMETHOD_WEIGHT;
            default:
                return INITIALZOMBIEPICKMETHOD_RANDOM;
        }
    }
    internal bool GetInitialPickRememberLastMap() { return (bool)GetCvar("sv_zh2_initialpickrememberlastmap"); }

    // Game - Compensation
    internal int GetCompensateMaxSecondsReturned() { return BCSUTILS::Clamp(GetCvar("sv_zh2_compensatemaxsecondsreturned"), 0, 100); }
    internal int GetCompensateHealthFactorReturned() { return BCSUTILS::Clamp(GetCvar("sv_zh2_compensatemaxhealthfactorreturned"), 0, 200); }
    internal int GetCompensateRestartIfSpecBeforeSeconds() { return BCSUTILS::Clamp(GetCvar("sv_zh2_compensaterestartifspecbeforeseconds"), 0, 300); }
    internal int GetCompensateAwardKillDamagePercentage() { return BCSUTILS::Clamp(GetCvar("sv_zh2_compensateawardkilldamagepercentage"), 0, 100); }

    // Game - AFK prevention
    internal bool GetAfkMoveAtRoundStart() { return (bool)GetCvar("sv_zh2_afkmoveatroundstart"); }
    internal int GetAfkMoveAtRoundStartBeforeSeconds() { return BCSUTILS::Clamp(GetCvar("sv_zh2_afkmoveatroundstartbeforeseconds"), 0, 60); }
    internal bool GetAfkMoveAsZombie() { return (bool)GetCvar("sv_zh2_afkmoveaszombie"); }
    internal int GetAfkZombieMoveGraceTics() { return BCSUTILS::Clamp(GetCvar("sv_zh2_afkzombiemovegracetics"), 0, 700); }
    internal int GetAfkZombieMoveCheckTics() { return BCSUTILS::Clamp(GetCvar("sv_zh2_afkzombiemovechecktics"), 0, 700); }
    internal int GetAfkZombieMoveWarnSeconds() { return BCSUTILS::Clamp(GetCvar("sv_zh2_afkzombiemovewarnseconds"), 0, 20); }

    // Game - Obituary
    internal bool GetSvEnableObituaries() { return (bool)GetCvar("sv_zh2_enableobituaries"); }
    internal bool GetClEnableObituaries(int playerId) { return (bool)GetUserCvar(playerId, "cl_zh2_enableobituaries"); }
    internal int GetShownObituaries(int playerId) { return BCSUTILS::Clamp(GetUserCvar(playerId, "cl_zh2_shownobituaries"), 1, OBITUARY_COLLECTION_MAX_SIZE); }

    // Game - Settings
    internal bool GetInformClientOfCVars() { return (bool)GetCvar("cl_zh2_informclientofcvars"); }

    internal bool GetEnableAntiTelefragSystem() { return (bool)GetCvar("sv_zh2_enableantitelefragsystem"); }

    // Game - Modifiers
    internal bool GetUseCustomKnockbackModifier() { return (bool)GetCvar("sv_zh2_usecustomknockbackmodifier"); }
    internal fixed GetCustomKnockbackModifierMultiplier() { return BCSUTILS::Clamp((fixed)GetCvar("sv_zh2_customknockbackmodifiermultiplier"), 0.1, 10.0); }
    internal bool GetUseCustomDamageFactorModifier() { return (bool)GetCvar("sv_zh2_usecustomdamagefactormodifier"); }
    internal fixed GetCustomDamageFactorModifierMultiplier() { return BCSUTILS::Clamp((fixed)GetCvar("sv_zh2_customdamagefactormodifiermultiplier"), 0.1, 10.0); }

    // Game - Voting
    internal bool GetAllowMapVoting() { return (bool)GetCvar("sv_zh2_AllowMapVoting"); }
    internal bool GetVoteIncludePlayedMaps() { return (bool)GetCvar("sv_zh2_voteincludeplayedmaps"); }
    internal bool GetAllowSpectatorVoting() { return (bool)GetCvar("sv_zh2_allowspectatorvoting"); }
    internal int GetMaxVotableMapsShown() { return BCSUTILS::Clamp(GetCvar("sv_zh2_MaxVotableMapsShown"), 1, MAX_VOTABLEMAPS); }
    internal int GetPlayerVotePercentage() { return BCSUTILS::Clamp(GetCvar("sv_zh2_PlayerVotePercentage"), 1, 100); }
    internal int GetPlayerCooldownTics() { return BCSUTILS::Clamp(GetCvar("sv_zh2_PlayerPickCooldownTics"), 0, 350); }

    // Game - Features
    internal bool GetUseMapResetsFeature() { return (bool)GetCvar("sv_zh2_usemapresetsfeature"); }
    internal bool GetUseDeadSpectatorsFeature() { return (bool)GetCvar("sv_zh2_usedeadspectatorsfeature"); }
    internal bool GetUseCustomKnockbackFeature() { return (bool)GetCvar("sv_zh2_usecustomknockbackfeature"); }
    internal bool GetUseAntiSR50() { return (bool)GetCvar("sv_zh2_useantisr50"); }

    // Player
    internal int GetShownInventoryItems() { return BCSUTILS::Clamp(GetCvar("cl_zh2_showninventoryitems"), 1, 11); }
    internal bool GetWrapInventoryItems() { return (bool)GetCvar("cl_zh2_wrapinventoryitems"); }

    internal bool GetSvIdentifyPlayers() { return (bool)GetCvar("sv_zh2_identifyplayers"); }
    internal IdentifyPlayerSpecieTypeT GetClIdentifyPlayers()
    {
        switch (BCSUTILS::Clamp(GetCVar("cl_zh2_identifyplayers"), 0, 3))
        {
            case 1:
                return IDENTIFY_PLAYER_ALL;
            case 2:
                return IDENTIFY_PLAYER_ONLY_SAME;
            case 3:
                return IDENTIFY_PLAYER_ONLY_OTHER;
            default:
                return IDENTIFY_PLAYER_OFF;
        }
    }
    internal IdentifyPlayerTypeT GetClIdentifyPlayerType()
    {
        switch (BCSUTILS::Clamp(GetCVar("cl_zh2_identifyplayertype"), 0, 2))
        {
            case 1:
                return IDENTIFY_PLAYER_NAME;
            case 2:
                return IDENTIFY_PLAYER_SPECIE;
            default:
                return IDENTIFY_PLAYER_BOTH;
        }
    }

    internal bool GetAutoUseMedikits(int playerId) { return (bool)GetUserCvar(playerId, "cl_zh2_autousemedikits"); }
    internal bool GetAutoUseKevlars(int playerId) { return (bool)GetUserCvar(playerId, "cl_zh2_autousekevlars"); }
    internal bool GetAutoUseEnergyDrinks(int playerId) { return (bool)GetUserCvar(playerId, "cl_zh2_autouseenergydrinks"); }

    internal bool GetSvTranslucentAllies() { return (bool)GetCvar("sv_zh2_translucentallies"); }
    internal int GetTranslucentAlliesDistance() { return BCSUTILS::Clamp(GetCvar("cl_zh2_translucentalliesdistance"), 100, 1000); }
    internal TranslucentAlliesT GetClTranslucentAllies()
    {
        // Note: defaults to "on with required cvars" when the value is out of bounds.
        switch(BCSUTILS::Clamp(GetCvar("cl_zh2_translucentallies"), 0, 2))
        {
            case 0:
                return TRANSLUCENT_ALLIES_OFF;
            case 2:
                return TRANSLUCENT_ALLIES_ON;
            default:
                return TRANSLUCENT_ALLIES_ON_WITH_REQUIRED_CVARS;
        }
    }
    internal int GetBaseAllyTranslucency() { return BCSUTILS::Clamp(GetCvar("cl_zh2_baseallytranslucency"), 30, 100); }

    internal bool GetSvTeamIndicators() { return (bool)GetCvar("sv_zh2_teamindicators"); }
    internal bool GetClTeamIndicators() { return (bool)GetCvar("cl_zh2_teamindicators"); }
    internal int GetTeamIndicatorDistance() { return BCSUTILS::Clamp(GetCvar("cl_zh2_teamindicatordistance"), 128, 1000); }
    internal bool GetShowTargetTeamIndicator() { return (bool)GetCvar("cl_zh2_showtargetteamindicator"); }

    internal bool GetSvEnableDamageFeedback() { return (bool)GetCvar("sv_zh2_enabledamagefeedback"); }
    internal bool GetClEnableDamageFeedback() { return (bool)GetCvar("cl_zh2_enabledamagefeedback"); }
    internal bool GetClEnableDamageFeedbackSounds() { return (bool)GetCvar("cl_zh2_enabledamagefeedbacksounds"); }

    internal DamageFeedbackMarkerShowTypeT GetDamageFeedbackMarkerShowType()
    {
        switch(BCSUTILS::Clamp(GetCvar("cl_zh2_enabledamagefeedbackmarkers"), 0, 3))
        {
            case 1:
                return DAMAGEFEEDBACK_MARKER_SHOW_HITS;
            case 2:
                return DAMAGEFEEDBACK_MARKER_SHOW_KILLS;
            case 3:
                return DAMAGEFEEDBACK_MARKER_SHOW_BOTH;
            default:
                return DAMAGEFEEDBACK_MARKER_SHOW_NONE;
        }
    }

    internal int GetDamageFeedbackHitMarkerShownTics() { return BCSUTILS::Clamp(GetCvar("cl_zh2_damagefeedbackhitmarkershowntics"), 10, 120); }
    internal int GetDamageFeedbackKillMarkerShownTics() { return BCSUTILS::Clamp(GetCvar("cl_zh2_damagefeedbackkillmarkershowntics"), 10, 120); }

    internal DamageFeedbackCounterShowTypeT GetDamageFeedbackCounterShowType()
    {
        switch(BCSUTILS::Clamp(GetCvar("cl_zh2_enabledamagefeedbackcounters"), 0, 3))
        {
            case 1:
                return DAMAGEFEEDBACK_COUNTER_SHOW_DAMAGE;
            case 2:
                return DAMAGEFEEDBACK_COUNTER_SHOW_KILLS;
            case 3:
                return DAMAGEFEEDBACK_COUNTER_SHOW_BOTH;
            default:
                return DAMAGEFEEDBACK_COUNTER_SHOW_NONE;
        }
    }

    internal int GetDamageFeedbackDamageCounterShownTics() { return BCSUTILS::Clamp(GetCvar("cl_zh2_damagefeedbackdamagecountershowntics"), 10, 120); }
    internal int GetDamageFeedbackKillCounterShownTics() { return BCSUTILS::Clamp(GetCvar("cl_zh2_damagefeedbackkillcountershowntics"), 10, 120); }

    internal DamageFeedbackNumberShowTypeT GetClDamageFeedbackNumberShowType()
    {
        switch(BCSUTILS::Clamp(GetCvar("cl_zh2_enabledamagefeedbacknumbers"), 0, 2))
        {
            case 1:
                return DAMAGEFEEDBACK_NUMBER_SHOW_TOTAL;
            case 2:
                return DAMAGEFEEDBACK_NUMBER_SHOW_INDIVIDUAL;
            default:
                return DAMAGEFEEDBACK_NUMBER_SHOW_NONE;
        }
    }

    internal int GetDamageFeedbackRatioDamageCap() { return BCSUTILS::Clamp(GetCvar("cl_zh2_damagefeedbackratiodamagecap"), 1, 2000); }
    internal int GetDamageFeedbackYellowDamageNumberThreshold() { return BCSUTILS::Clamp(GetCvar("cl_zh2_damagefeedbackyellowdamagenumberthreshold"), 0, 1990); }
    internal int GetDamageFeedbackRedDamageNumberThreshold() { return BCSUTILS::Clamp(GetCvar("cl_zh2_damagefeedbackreddamagenumberthreshold"), 0, 2000); }

    // Player - Music
    internal bool GetIgnoreRadioMusic() { return (bool)GetCvar("cl_zh2_ignoreradiomusic"); }
    internal bool GetInvertRadioNavigation() { return (bool)GetCvar("cl_zh2_invertradionavigation"); }
    internal bool GetTrackNotFoundPlayRandom() { return (bool)GetCvar("cl_zh2_tracknotfoundplayrandom"); }
    internal bool GetRadioProximityEnabled() { return (bool)GetCvar("cl_zh2_radioproximity"); }
    internal bool GetRadioFadeMapMusicEnabled() { return (bool)GetCvar("cl_zh2_radiofademapmusic"); }
    internal bool GetIgnoreFullServerMusic() { return (bool)GetCvar("cl_zh2_ignorefullservermusic"); }

    // Player - Zombie
    internal bool GetAllowZombieTeleporting() { return (bool)GetCvar("sv_zh2_allowzombieteleporting"); }
    internal int GetMaxZombieTeleports() { return BCSUTILS::Clamp(GetCvar("sv_zh2_maxzombieteleports"), 1, 10); }
    internal int GetZombieTeleportSeconds() { return BCSUTILS::Clamp(GetCvar("sv_zh2_zombieteleportseconds"), 1, 20); }
    internal bool GetAllowRandomZombieTaunts() { return (bool)GetCvar("sv_zh2_allowrandomzombietaunts"); }
    internal bool GetAllowMovingWhenZombieTeleporting() { return (bool)GetCvar("sv_zh2_allowmovingwhenzombieteleporting"); }
    internal bool GetUseZombieAbilities() { return (bool)GetCvar("sv_zh2_usezombieabilities"); }
    internal bool GetUseZombieAbilityCooldowns() { return (bool)GetCvar("sv_zh2_usezombieabilitycooldowns"); }
    internal int GetDisabledZombieAbilityFlags() { return BCSUTILS::Clamp(GetCvar("sv_zh2_disabledzombieabilityflags"), 0, 3); }

    internal DropGrenadeOnInfectT GetDropGrenadeOnInfect()
    {
        switch(BCSUTILS::Clamp(GetCvar("sv_zh2_dropgrenadeoninfect"), 0, 2))
        {
            case 0:
                return DROPBEHAVIOUR_ALWAYS;
            case 1:
                return DROPBEHAVIOUR_ONLY_REGULAR_ZOMBIES;
            default:
                return DROPBEHAVIOUR_NEVER;
        }
    }

    // Player - Human
    internal int GetFlareType(int playerId) { return BCSUTILS::Clamp(GetUserCvar(playerId, "cl_zh2_flaretype"), 0, 8); }
    internal bool GetEnableFinalHeartbeat() { return (bool)GetCvar("cl_zh2_enablefinalheartbeat"); }
    internal bool GetEnableHurtHeartbeat() { return (bool)GetCvar("cl_zh2_enablehurtheartbeat"); }
    internal bool GetServerEnabledBlood() { return (bool)GetCvar("sv_zh2_enableblood"); }
    internal int GetClientBloodType() { return BCSUTILS::Clamp(GetCvar("cl_zh2_bloodtype"), 0, 2); }
    internal bool GetAllowSprinting() { return (bool)GetCvar("sv_zh2_allowsprinting"); }
    internal int GetMinimumSprintAmount() { return BCSUTILS::Clamp(GetCvar("sv_zh2_minimumsprintamount"), 1, 1000); }
    internal bool GetAllowPanicking() { return (bool)GetCvar("sv_zh2_allowpanicking"); }
    internal int GetMaxPanicCount() { return BCSUTILS::Clamp(GetCvar("sv_zh2_maxpaniccount"), 1, 10); }

    // Player - Features
    internal bool GetRemoveSoftwareTextures() { return (bool)GetCvar("cl_zh2_removesoftwaretextures"); }

    // Hud
    internal bool GetDrawHud() { return (bool)GetCvar("cl_zh2_drawhud"); }

    internal bool GetDrawDebugCoordinatesHud() { return (bool)GetCvar("cl_zh2_DrawDebugCoordinatesHud"); }

    internal bool GetEnableHudShaking() { return (bool)GetCvar("cl_zh2_ShakeHud"); }
    internal fixed GetHudShakeIntensityMultiplier() { return 1.1/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudShakeIntensityMultiplier"), 0.1, 5.0)*/; }
    internal fixed GetHudShakeFrequencyMultiplier() { return 1.1/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudShakeFrequencyMultiplier"), 0.1, 5.0)*/; }
    internal int GetHudShakeDuration() { return 4/*BCSUTILS::Clamp(GetCvar("cl_zh2_HudShakeDurationTics"), 1, 20)*/; }

    internal fixed GetCursorScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_CursorScale"), 0.05, 2.0)*/; }

    internal bool GetDrawVersionHud() { return (bool)GetCvar("cl_zh2_DrawVersionHud"); }
    internal fixed GetHudVersionScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudVersionScale"), 0.05, 2.0)*/; }

    internal bool GetDrawPlayerStatusHud() { return (bool)GetCvar("cl_zh2_DrawPlayerStatusHud"); }
    internal fixed GetHudPlayerStatusOffsetX() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerStatusOffsetX"), 0.0, 200.0); }
    internal fixed GetHudPlayerStatusOffsetY() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerStatusOffsetY"), 0.0, 40.0); }
    internal fixed GetHudPlayerStatusScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerStatusScale"), 0.05, 2.0)*/; }

    internal bool GetDrawPlayerPowersHud() { return (bool)GetCvar("cl_zh2_DrawPlayerPowersHud"); }
    internal fixed GetHudPlayerPowersOffsetX() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerPowersOffsetX"), -200.0, 200.0); }
    internal fixed GetHudPlayerPowersOffsetY() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerPowersOffsetY"), -40.0, 40.0); }
    internal fixed GetHudPlayerPowersScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerPowersScale"), 0.05, 2.0)*/; }

    internal bool GetDrawPlayerBarsHud() { return (bool)GetCvar("cl_zh2_DrawPlayerBarsHud"); }
    internal fixed GetHudPlayerBarsOffsetX() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerBarsOffsetX"), -200.0, 200.0); }
    internal fixed GetHudPlayerBarsOffsetY() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerBarsOffsetY"), -40.0, 40.0); }
    internal fixed GetHudPlayerBarsScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudPlayerBarsScale"), 0.05, 2.0)*/; }

    internal bool GetDrawRoundHud() { return (bool)GetCvar("cl_zh2_DrawRoundHud"); }
    internal fixed GetHudRoundOffsetX() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudRoundOffsetX"), -200.0, 200.0); }
    internal fixed GetHudRoundOffsetY() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudRoundOffsetY"), 0.0, 40.0); }
    internal fixed GetHudRoundScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudRoundScale"), 0.05, 2.0)*/; }

    internal bool GetDrawGameHud() { return (bool)GetCvar("cl_zh2_DrawGameHud"); }
    internal fixed GetHudGameScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudGameScale"), 0.05, 2.0)*/; }

    internal fixed GetHudObituaryOffsetX() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_hudobituaryoffsetx"), -200.0, 200.0); }
    internal fixed GetHudObituaryOffsetY() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_hudobituaryoffsety"), 0.0, 40.0); }

    internal bool GetDrawDebugHud() { return (bool)GetCvar("cl_zh2_DrawDebugHud"); }
    internal fixed GetHudDebugOffsetX() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudDebugOffsetX"), 0.0, 200.0); }
    internal fixed GetHudDebugOffsetY() { return BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudDebugOffsetY"), 0.0, 40.0); }
    internal fixed GetHudDebugScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudDebugScale"), 0.05, 2.0)*/; }

    internal bool GetDrawResistsHud() { return (bool)GetCvar("cl_zh2_DrawResistsHud"); }
    internal fixed GetHudResistsScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudResistsScale"), 0.05, 2.0)*/; }

    internal fixed GetHudAdminScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudAdminScale"), 0.05, 2.0)*/; }
    internal fixed GetHudEndingScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudEndingScale"), 0.05, 2.0)*/; }
    internal fixed GetHudSummaryScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudSummaryScale"), 0.05, 2.0)*/; }
    internal fixed GetHudClientSettingsScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudClientSettingsScale"), 0.05, 2.0)*/; }
    internal fixed GetHudWeaponSniperScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudWeaponSniperScale"), 0.05, 2.0)*/; }
    internal fixed GetHudWeaponRadioScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudWeaponRadioScale"), 0.05, 2.0)*/; }
    internal fixed GetHudFullServerScale() { return 1.0/*BCSUTILS::Clamp((fixed)GetCvar("cl_zh2_HudFullServerScale"), 0.05, 2.0)*/; }

    // Zandronum specific
    internal bool GetNoRespawnInvul() { return (bool)GetCvar("sv_norespawninvul"); }
    internal bool GetSvCheats() { return (bool)GetCvar("sv_cheats"); }
    internal bool GetShootThroughAllies() { return (bool)GetCvar("sv_shootthroughallies"); }
    internal bool GetUnblockAllies() { return (bool)GetCvar("sv_unblockallies"); }
    internal bool GetProtectCVars() { return (bool)GetCvar("cl_protectcvars"); }
    internal int GetMaxPlayers() { return BCSUTILS::Clamp(GetCvar("sv_maxplayers"), 1, 64); }
    internal bool GetCompatNoObituaries() { return (bool)GetCvar("compat_noobituaries"); }
    internal int GetMaxBanDuration() { return BCSUTILS::Clamp(GetCvar("sv_maxacsbanduration"), 0, BCSUtils::INT_MAX); }

    internal fixed GetSndMusicVolume() { return BCSUtils::a_GetCVarFixed("snd_musicvolume"); }

    // NOTE: this uses ConsoleCommand, it should get a better alternative sometime.
    internal void SetSndMusicVolume(fixed volume) { ConsoleCommand("snd_musicvolume " + str(volume)); }
}