#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "debug/debug.acs"
#include "game/game.acs"
#include "sync/sync.acs"
#include "map/map.acs"
#include "events/events.acs"
#include "round/round.acs"
#include "roundtimer/roundtimer.acs"
#include "player/player.acs"
#include "feature/feature.acs"
#include "gameloop/gameloop.acs"
#include "settings/settings.acs"
#include "shuffle/shuffle.acs"
#include "music/music.acs"
#include "reward/reward.acs"
#include "weight/weight.acs"
#include "damage/damage.acs"
#include "damagefeedback/damagefeedback.acs"
#include "obituary/obituary.acs"
#include "decorate/decorate.acs"
#include "resist/resist.acs"
#include "power/power.acs"
#include "item/item.acs"
#include "admin/admin.acs"
#include "hud/hud.acs"
#include "io/io.acs"

#define LOGSOURCE "Main"

#include "scriptevents.acs"
#include "cvars.acs"
#include "binds.acs"

#define SCRIPT_ENTER_RESPAWN_NAME "zh2_internal_enter_respawn"
#define SCRIPT_ENTER_RESPAWN_CLIENTSIDE_NAME "zh2_internal_enter_respawn_clientside"

strict namespace ZH2Game
{
    internal GameContextT GameContext;
    global PersistingGameContextT PERSISTINGGAMECONTEXTINDEX: PersistingGameContext;

    // This is used for joining players/bots to force them to a specific specie.
    // This is specifically used for the admin to add bots of specific species.
    // If not set, we default to humans.
    internal Player::PlayerSpecieT _forceSpecie;

    script "zh2_internal_open" open
    {
        Logger::LogDebug(LOGSOURCE, "Call script \"zh2_internal_open\"");

        // Offline only as the connect event is only ran online.
        if (!IsNetworkGame())
        {
            GameLoop::StartServerPlayerLoopById(ConsolePlayerNumber());
            Utils::InitializeSynchronizedTimerForPlayer(ConsolePlayerNumber());
        }

        // Online we want to now start the player loop for all available players as those already in the server won't actually trigger the event.
        else
        {
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                if (!BCSUtils::PlayerIsConnected(i))
                    continue;

                GameLoop::StartServerPlayerLoopById(i);
                Utils::InitializeSynchronizedTimerForPlayer(i);
            }
        }

        // Verify gamemode.
        // The single tic delay is for the logger to pass to clients.
        // No longer required in Zandronum 3.3 as it is now possible to lock the gamemode through mapinfo.
        /*if (BCSUtils::StrToLower(GetCurrentGameMode()) != REQUIREDGAMEMODE)
        {
            Logger::LogWarning(LOGSOURCE, "Zombie Horde was build for the " + REQUIREDGAMEMODE + " gamemode. Updating game type...");
            Delay(const: 1);
            if (!SetCurrentGameMode(REQUIREDGAMEMODE)) Logger::LogError(LOGSOURCE, "Failed to set the current gamemode to " + REQUIREDGAMEMODE + ".");
            terminate;
        }*/

        // Note, these two parses should work concurrently and both rent a tokenizer for this.
        // Parse persisting data here.
        Logger::LogDebug(LOGSOURCE, "Start parsing persisting data (server).");
        LibIO::ParseWeatherDefServerside();
        LibIO::ParseLoggerDefServerside();
        IO::ParseModDefLumpsServerside();
        IO::ParseMapDefLumps();

        // Initialize library
        // Weather must initialize before we parse the map.
        Weather::InitializeServer();

        // Parse non-persisting data now.
        Logger::LogDebug(LOGSOURCE, "Start parsing non-persisting data (server).");
        IO::ParseCurrentMapLump();

        // Now the loop starts because we have loaded everything.
        GameLoop::StartServerLoop();

        // Set the current game mode if we have it set.
        str gameMode = Map::GetCurrentMapGameMode();
        if (((raw)gameMode) != 0 && gameMode != "")
        {
            Logger::LogDebug(LOGSOURCE, "Setting up serverside game mode: \cd" + gameMode + "\cj.");

            switch (BCSUtils::StrToLower(gameMode))
            {
                case "survival":
                    Event::SetSurvivalDefaultsServer();
                    Player::SetSurvivalDefaults();
                    Game::SetSurvivalDefaults();
                    Round::SetSurvivalDefaults();
                    RoundTimer::SetSurvivalDefaults();
                    break;

                case "escape":
                    Event::SetEscapeDefaultsServer();
                    Player::SetEscapeDefaults();
                    Game::SetEscapeDefaults();
                    Round::SetEscapeDefaults();
                    RoundTimer::SetEscapeDefaults();
                    break;

                default:
                    Logger::LogWarning(LOGSOURCE, "The given game mode profile does not exist: " + gamemode + ".");
                    break;
            }
        }
        else
        {
            Logger::LogDebug(LOGSOURCE, "Map has no game mode defined.");
        }

        // Set up the initial game state depending on if we have enough players or not.
        int availableClients = BCSUtils::ClientCount();
        int minimumRequiredClients = ZH2Game::GetMinimumClientCount();
        if (availableClients < minimumRequiredClients)
        {
            Round::SetKnownRoundState(Round::STATEPREGAME);
        }
        else
        {
            // Start the timer if defined.
            int index = RoundTimer::GetIndexOfKnownType(RoundTimer::TIMERCOUNTDOWN);
            if (RoundTimer::GetTimerDefined(index))
            {
                Round::SetKnownRoundState(Round::STATECOUNTDOWN);
                RoundTimer::SetActiveTimerByKnownType(RoundTimer::TIMERCOUNTDOWN);
                RoundTimer::StartTimer(index);
            }

            // Is not, we go to the state before the countdown and the map will have to start manually.
            else
            {
                Round::SetKnownRoundState(Round::STATESTARTING);
                Logger::LogDebug(LOGSOURCE, "Waiting for the map to start the game.");
            }
        }

        Sync::SyncRoundState();
        Sync::SyncTimers();
        Sync::SyncResists();

        // Required for the zombie abilities to be synched.
        Sync::SyncGame();

        // Resync admin list
        Sync::SyncAdmins();

        LibSync::SyncWeather();

        // After a moment, sync all players and allow them to sync themselves on enter.
        Delay(const: 5);

        ZH2Game::GameContext.DoSyncOnEnter = true;
        Sync::SyncPlayers();

        // Send the default values to the client.
        Sync::SyncPowers();
    }

    script "zh2_internal_open_client" open clientside
    {
        Logger::LogDebug(LOGSOURCE, "Call script \"zh2_internal_open_client\"");

        Logger::LogDebug(LOGSOURCE, "Start parsing persisting data (client).");

        // Parse other persisting data here.
        LibIO::ParseFootstepDefsClientside();
        IO::ParseModDefLumpsClientside();
        if (IsNetworkGame())
        {
            LibIO::ParseLoggerDefClientside();
            IO::ParseMapDefLumps();
        }

        // Wait for the persisting data to be parsed.
        Logger::LogDebug(LOGSOURCE, "Start parsing non-persisting data (client).");

        // Parse non-persisting data now.
        if (IsNetworkGame())
            IO::ParseCurrentMapLump();

        // We now iterate the resulting list of items, splitting them into three separate collections which makes iterating them much easier.
        // TODO: This should be exported to its own function. Or perhaps be removed altogether.
        Item::ItemCollectionContextT global:PERSISTINGGAMECONTEXTINDEX& collection = ZH2Game::PersistingGameContext.ItemCollection;
        if (!collection.HasSplitItems)
        {
            for (int i = 0; i < collection.Size; ++i)
            {
                Item::ItemTypeT type = collection.Collection[i].Type;
                if      (type == Item::TYPE_WEAPON)    collection.WeaponCollection[collection.WeaponCollectionSize++] = i;
                else if (type == Item::TYPE_INVENTORY) collection.InventoryCollection[collection.InventoryCollectionSize++] = i;
                else if (type == Item::TYPE_KEY)       collection.KeyCollection[collection.KeyCollectionSize++] = i;
            }

            collection.HasSplitItems = true;
        }

        // Set the current game mode if we have it set.
        str gameMode = Map::GetCurrentMapGameMode();
        if (((raw)gameMode) != 0 && gameMode != "")
        {
            Logger::LogDebug(LOGSOURCE, "Setting up clientside game mode: \cd" + gameMode + "\cj.");

            switch (BCSUtils::StrToLower(gameMode))
            {
                case "survival":
                    Event::SetSurvivalDefaultsClient();
                    Obituary::SetSurvivalDefaultsClient();
                    break;

                case "escape":
                    Event::SetEscapeDefaultsClient();
                    Obituary::SetEscapeDefaultsClient();
                    break;

                default:
                    Logger::LogWarning(LOGSOURCE, "The given game mode profile does not exist: " + gamemode + ".");
                    break;
            }
        }
        else
        {
            Logger::LogDebug(LOGSOURCE, "Map has no game mode defined.");
        }

        // Now the loop starts because we have loaded everything.
        GameLoop::StartClientPlayerLoopActivator();

        // Fully sync up the client.
        Sync::SynAllClientside();
        LibSync::SyncAllClientside();

        Settings::UpdateCurrentClientSettings();
        Weather::InitializeClient();

        // Voting is active, so the client needs a mouse.
        // TODO: Move this when adding the sync callback system.
        if (Round::GetActiveKnownRoundState() == Round::STATEVOTING)
        {
            Hud::SetCursorEnabled(true);
            Player::LockMovement(true);
        }

        // Initialize team indicators for all existing players.
        // This does not have to run offline as the enter script works fine.
        if (IsNetworkGame())
        {
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                // Ignore self.
                if (ConsolePlayerNumber() == i)
                    continue;

                if (!PlayerInGame(i))
                    continue;

                int tid = Identity::GetTID(i);
                if (!BCSUTILS::ActorIsAlive(tid))
                    continue;

                Game::SpawnPlayerTeamIndicator(i);
            }
        }

        // Inform the client to play the current default music.
        Music::PlayDefaultMusic();

        // Damage feedback
        DamageFeedback::InitializeDamageFeedbackClient();

        // Everything below requires the client to be the activator.
        // TODO: Improve so this is not required.
        if (!SetActivatorToPlayer(ConsolePlayerNumber()))
            terminate;

        Settings::BroadcastClientConsolidateSettings(false);
    }

    script "zh2_internal_enter" enter
    {
        // Exclusive to bots who spawn from `addbot` and skip any sort of connect/open call.
        if (PlayerIsBot(PlayerNumber()))
            GameLoop::StartServerPlayerLoopById(PlayerNumber());

        ACS_NamedExecuteWithResult(SCRIPT_ENTER_RESPAWN_NAME, 0);
    }

    script "zh2_internal_enter_client" enter clientside
    {
        ACS_NamedExecuteWithResult(SCRIPT_ENTER_RESPAWN_CLIENTSIDE_NAME, 0);
    }

    script "zh2_internal_respawn" respawn
    {
        ACS_NamedExecuteWithResult(SCRIPT_ENTER_RESPAWN_NAME, 0);
    }

    script "zh2_internal_respawn_client" respawn clientside
    {
        ACS_NamedExecuteWithResult(SCRIPT_ENTER_RESPAWN_CLIENTSIDE_NAME, 0);
    }

    script "zh2_internal_unloading" unloading
    {
        Logger::LogDebug(LOGSOURCE, "Call script \"zh2_internal_unloading\"");

        Power::Unload();

        // Reset the default music, or the music will move to the next map.
        Music::SetDefaultMusic("");
    }

    script "zh2_internal_disconnect" (int id) disconnect
    {
        Logger::LogDebug(LOGSOURCE, "Call script \"zh2_internal_disconnect\"");

        VALIDATE_ID_VALID_SCRIPT(id);
        int tid = Identity::GetTID(id);
        Identity::DisposeTID(tid);

        // If the player did not spectate then they left.
        // In that case we do not handle the logic.
        // Rather the `GAMEEVENT_PLAYERLEAVESSERVER` event will do this in the event handler script.
        if (!PlayerIsSpectator(id))
            terminate;

        // Player always plays the game, so no explicit check for a playing player exists here.

        // Only run if player was playing in the round.
        if (Player::GetPlayerState(id) == Player::STATEPLAYING)
        {
            int activeRoundIndex = Round::GetActiveRoundStateIndex();

            // The player left a playing round.
            if (Round::GetActiveKnownRoundState() == Round::STATEPLAYING)
            {
                Logger::LogDebug(LOGSOURCE, "Playing player has spectated: (\cd" + str(id) + "\cj)" + BCSUTILS::PlayerName(id) + ".");
                Player::SetPlayerState(id, Player::STATEGONE);
                Event::SendPlayerLeftRound(id);
            }

            // Check if the round was still joinable.
            // We must reset the player context then as somebody else can take it.
            else if (Round::GetRoundJoinable(activeRoundIndex))
            {
                Logger::LogDebug(LOGSOURCE, "Playing player has spectated (not a playing round): (\cd" + str(id) + "\cj)" + BCSUTILS::PlayerName(id) + ".");
                ResetPlayerContext(id);
            }

            Sync::SyncPlayers();
        }

        // Always reset the lib context of the player.
        ZH2Lib::ResetPlayerLibContext(id);
    }

    script "zh2_internal_disconnect_client" (int id) disconnect clientside
    {
        // Dispose team indicator unless we're the one that disconnected.
        if (id != ConsolePlayerNumber())
            Game::DisposePlayerTeamIndicator(id);
    }

    script "zh2_internal_death" death
    {
        int killedId = PlayerNumber();
        VALIDATE_ID_VALID_SCRIPT(killedId);

        // Skip this script if the player is not playing (state is likely dead already).
        // This will always happen when setting a player as a dead spectator.
        // TODO: No longer required with `GAMEEVENT_PLAYERJOINS`
        if (Player::GetPlayerState(killedId) != Player::STATEPLAYING)
            terminate;

        // Get the killer.
        // The killer might not exist for deaths, which means that the id remains -1.
        int killerId = -1;
        if (SetActivatorToTarget(0))
            killerId = PlayerNumber();

        // The round is not joinable, so the player has to be removed from their body.
        if (!Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()))
        {
            // Build message, but don't mention they can join next map if they are allowed to always join.
            str message = "You are dead.";
            if (!AllowPlayerJoin(PlayerNumber()))
                message += " You will be able to play again next map.";

            RemovePlayer(killedId, message);
        }

        Logger::LogDebug(LOGSOURCE, "Call script \"zh2_internal_death\" for player " + str(killedId) + " killed by player " + str(killerId) + ".");

        // Reset transient context if still in a joinable state.
        // Otherwise set as dead.
        if (Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()))
            ResetPlayerContext(killedId);
        else
            Player::SetPlayerState(killedId, Player::STATEDEAD);

        Identity::DisposeTID(Identity::GetTid(killedId));
        Sync::SyncPlayers();
    }

    script "zh2_internal_death_client" death clientside
    {
        Logger::LogDebug(LOGSOURCE, "Call script \"zh2_internal_death_client\" for player " + str(PlayerNumber()) + ".");

        // Dispose team indicator unless we're the one that died.
        if (PlayerNumber() != ConsolePlayerNumber())
            Game::DisposeTeamIndicator();

        // Only run the rest on the dying client.
        if (ConsolePlayerNumber() != PlayerNumber())
            terminate;

        Settings::CloseClientSettingsMenu();
        Admin::DisableAdminHud();

        // Trigger a death cam when the round has started and the player dies.
        if (!Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()) && Player::GetPlayerState(PlayerNumber()) == Player::STATEPLAYING)
        {
            Game::InitializeClientDeathCamera();

            // Death cam needs a tic to initialize online, or it won't work.
            delay(const: 1);
            Game::StartClientDeathCamera();
        }
    }

    script SCRIPT_ENTER_RESPAWN_NAME
    {
        Logger::LogDebug(LOGSOURCE, "Call script \"" + SCRIPT_ENTER_RESPAWN_NAME + "\"");

        Identity::InitializeActivator();

        // Set specie, possibly forced to a specific specie.
        // SPECIENONE defaults to SPECIEHUMAN.
        if (_forceSpecie == Player::SPECIENONE)
            _forceSpecie = Player::SPECIEHUMAN;

        // TODO: Abstract into a repurposable functions
        if (_forceSpecie == Player::SPECIEHUMAN)
        {
            // Ensure all zombie weapons are taken.
            // This ensures that all weapons are correctly taken on this initial morph when the map changed.
            Player::TakeZombieWeapons();

            // TODO: Abstract into a repurposable function
            Player::MorphToHuman();
            Player::SetHumanTeam();
            Player::SetHumanSkin();
            Player::SetHuman();
            Player::GiveHumanInventory(true);
            Power::RecalculatePowers();

            // A 50% chance to get a fire grenade.
            // TODO: Replace with better distribution.
            if (BCSUtils::RandBool())
            {
                GiveInventory(WEAPON_FIREGRENADE_NAME, 1);
                GiveInventory(WEAPON_AMMO_FIREGRENADE_NAME, 1);
            }

            // Ensure we always start with the shotgun to avoid weird behaviour.
            SetWeapon(WEAPON_SHOTGUN_NAME);
        }
        else if (_forceSpecie == Player::SPECIEZOMBIE)
        {
            // Ensure all human weapons are taken.
            // This ensures that all weapons are correctly taken on this initial morph when the map changed.
            Player::TakeHumanWeapons();

            Player::MorphToZombie();
            Player::SetZombieTeam();
            Player::SetZombieSkin(SKIN_ZOMBIEOLD);
            Player::SetZombie();
            Player::GiveZombieInventory();
            Power::RecalculatePowers();
        }

        _forceSpecie = Player::SPECIENONE;

        Player::SetState(Player::STATEPLAYING);

        // Set initial name. The player's loop will then track possible changes.
        Player::SetName(BCSUtils::PlayerName(PlayerNumber()));

        Game::InitializePlayerModifiers(PlayerNumber());
        Feature::InitializePlayerFeatures(PlayerNumber());

        // Possible extra syncs depending on time.
        // We only do these if the map has been playing for a bit to avoid 64 players calling it.
        if (ZH2Game::GameContext.DoSyncOnEnter)
        {
            Sync::SyncPlayers();

            // Note we want to sync on enter as powers are inventory items and we also initialize stuff like modifiers above.
            Sync::SyncPowers();
        }

        // Set the player as an admin.
        // This is now removed and you can turn it on through the menu/rcon. Always works offline.
        // if (!Admin::GetIsAdmin())
        // {
        //     Admin::SetIsAdmin(true);
        //     Sync::SyncAdmins();
        // }
    }

    internal void RemovePlayer(int id, str message)
    {
        // Player is already a sort of spectator, so this function should not be called.
        if (PlayerIsSpectator(id) != 0)
        {
            Logger::LogWarning(LOGSOURCE, "Attempted to set " + str(id) + " as a spectator, but this player is already spectating.");
            return;
        }

        Logger::LogTo(id, message);

        if (GetUseDeadSpectatorsFeature())
        {
            if (SetDeadSpectator(id, true))
                return;

            Logger::LogWarning(LOGSOURCE, "Failed to set " + str(id) + " as dead spectator. Falling back to KickFromGame.");
        }

        if (KickFromGame(id, message))
            return;

        Logger::LogError(LOGSOURCE, "Failed to set " + str(id) + " as spectator. KickFromGame failed.");
    }

    script SCRIPT_ENTER_RESPAWN_CLIENTSIDE_NAME clientside
    {
        Logger::LogDebug(LOGSOURCE, "Call script \"" + SCRIPT_ENTER_RESPAWN_CLIENTSIDE_NAME + "\"");

        // Same as on the serverside, check if we can join the game at all or if we are capped/restricted.
        // TODO: No longer required with `GAMEEVENT_PLAYERJOINS`
        if (!GetPlayerIsWithinPlayerCap(PlayerNumber()) || !GetPlayerCanJoin(PlayerNumber()))
            terminate;

        // Spawn a team indicator unless we're the one entering/respawning
        if (PlayerNumber() != ConsolePlayerNumber())
            Game::SpawnTeamIndicator();
    }

    // Returns `true` if the given player can join.
    // Checks for global, and player specific joining.
    internal bool AllowPlayerJoin(int id)
    {
        return GameContext.AlwaysAllowJoin || GameContext.Players[id].AlwaysAllowJoin;
    }

    // Returns `true` if the player is within the player cap, assuming it's enabled.
    internal bool GetPlayerIsWithinPlayerCap(int id)
    {
        return !DevelopmentPlayerCap() || PlayerIsBot(id) || PlayerCount() - Utils::PlayingBotCount() <= DEV_PLAYERCAP_COUNT;
    }

    // Returns `true` if the player canJoin.
    internal bool GetPlayerCanJoin(int id)
    {
        return AllowPlayerJoin(id) || Round::GetRoundJoinable(Round::GetActiveRoundStateIndex());
    }

    // Note this is not always emptied in the game.
    // If the game is playing (and not in a joinable state), it will remain available until the map changes.
    internal void ResetPlayerContext(int id)
    {
        Logger::LogDebug(LOGSOURCE, "Resetting player context for player " + str(id) + ".");

        static PlayerT emptyPlayerDef;
        if (!Memcpy(GameContext.Players[id], emptyPlayerDef))
            Logger::LogError(LOGSOURCE, "Failed to empty player context for player " + str(id) + ".");
    }

    internal void ResetPlayerPersistingContext(int id)
    {
        Logger::LogDebug(LOGSOURCE, "Resetting persisting player context for player " + str(id) + ".");

        static PersistingPlayerT emptyPlayerDef;
        if (!Memcpy(PersistingGameContext.Players[id], emptyPlayerDef))
            Logger::LogError(LOGSOURCE, "Failed to empty persisting player context for player " + str(id) + ".");
    }
}

#undef LOGSOURCE