#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Note, matches the max size of rewards that has been set.
// This must match the size, or exceed it if something else grows bigger.
#define MAX_WEIGHT_SIZE 100

strict namespace Weight
{
    struct WeightContextT
    {
        WeightT Weights[MAX_WEIGHT_SIZE];
        int Count;
    };

    struct WeightT
    {
        int Index;
        int Weight;
    };

    extern void PrepareWeights();
    extern bool HasWeights();
    extern void AddWeight(int index, int weight);
    extern void FinalizeWeights();
    extern int Next(int i = -1);
}