#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    script "zh2_internal_event_actordamaged"(raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceiveActorDamaged(packet);

        int id = Event::GetReceiveData(0);

        // Only handle damage from ourselves.
        if (id != ConsolePlayerNumber())
            terminate;

        int tid = Event::GetReceiveData(1);
        int damage = Event::GetReceiveData(2);
        bool targetDied = Event::GetReceiveData(3);

        // Don't count damage if we damaged ourselves.
        if (Identity::GetTid(ConsolePlayerNumber()) == tid)
            terminate;

        Damage::AddTotalDamage(tid, damage, targetDied);
        DamageFeedback::SetTidDamaged(tid, damage, targetDied);
    }

    script "zh2_internal_event_actordamaged_clienttotal"(raw packetStr) clientside
    {
        str packet = (str)packetStr;
        Event::ReceiveActorDamagedClientTotal(packet);

        int tid = Event::GetReceiveData(0);
        int damage = Event::GetReceiveData(1);
        bool targetDied = Event::GetReceiveData(2);

        // Play a sound if enabled.
        if (ZH2Game::GetClEnableDamageFeedbackSounds())
        {
            str sound = targetDied ? "world/damagekill" : "world/damagehit";
            AmbientSound(sound, 127);
        }

        DamageFeedback::AddTotalDamageNumberOnActor(tid, damage);
    }
}