#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Event"

#include "round.acs"
#include "timer.acs"
#include "player.acs"
#include "damage.acs"
#include "send.acs"
#include "receive.acs"

strict namespace Event
{
    internal void SetSurvivalDefaultsServer()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for events serverside.");

        EventBus::AddCallbackByScriptName(EVENT_TIMER_ELAPSED, "zh2_internal_event_timerelapsed");
        EventBus::AddCallbackByScriptName(EVENT_ROUND_SWITCHED, "zh2_internal_event_roundswitched");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_PRE_SCRATCHED, "zh2_internal_event_prescratched");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_KILLED_BY_PLAYER, "zh2_internal_event_playerkilledbyplayer");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_LEFT_ROUND, "zh2_internal_event_playerleftround");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_SPECIE_CHANGED, "zh2_internal_event_specie_changed");
    }

    internal void SetSurvivalDefaultsClient()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for events clientside.");

        EventBus::AddCallbackByScriptName(EVENT_ROUND_SWITCHED, "zh2_internal_event_roundswitched_client");
        EventBus::AddCallbackByScriptName(EVENT_ACTOR_DAMAGED, "zh2_internal_event_actordamaged");
        EventBus::AddCallbackByScriptName(EVENT_ACTOR_DAMAGED_CLIENT_TOTAL, "zh2_internal_event_actordamaged_clienttotal");
    }

    internal void SetEscapeDefaultsServer()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for events serverside.");

        EventBus::AddCallbackByScriptName(EVENT_TIMER_ELAPSED, "zh2_internal_event_timerelapsed");
        EventBus::AddCallbackByScriptName(EVENT_ROUND_SWITCHED, "zh2_internal_event_roundswitched");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_PRE_SCRATCHED, "zh2_internal_event_prescratched");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_KILLED_BY_PLAYER, "zh2_internal_event_playerkilledbyplayer");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_LEFT_ROUND, "zh2_internal_event_playerleftround");
        EventBus::AddCallbackByScriptName(EVENT_PLAYER_SPECIE_CHANGED, "zh2_internal_event_specie_changed");
    }

    internal void SetEscapeDefaultsClient()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for events clientside.");

        EventBus::AddCallbackByScriptName(EVENT_ROUND_SWITCHED, "zh2_internal_event_roundswitched_client");
        EventBus::AddCallbackByScriptName(EVENT_ACTOR_DAMAGED, "zh2_internal_event_actordamaged");
        EventBus::AddCallbackByScriptName(EVENT_ACTOR_DAMAGED_CLIENT_TOTAL, "zh2_internal_event_actordamaged_clienttotal");
    }
}

#undef LOGSOURCE