#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    script "zh2_internal_event_prescratched" (raw packetStr)
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerScratched(packet);
        int infectedId = GetReceiveData(0);
        int infectorId = GetReceiveData(1);

        // Double check a zombie infects a human.
        // If two players infect on the same tic, this can not be the case.
        if (!Player::GetPlayerIsHuman(infectedId) || !Player::GetPlayerIsZombie(infectorId))
            terminate;

        Logger::LogDebug(LOGSOURCE, "Scratching (\cd" + str(infectedId) + "\cj) " + BCSUtils::PlayerName(infectedId) + " by (\cd" + str(infectorId) + "\cj) " + BCSUtils::PlayerName(infectorId) + ".");

        // Check for protection.
        if (Power::GetPlayerHasPower(infectedId, Power::POWERZOMBIEPROTECT))
            terminate;

        // Always visualize a scratch at this point.
        if (!PlayerIsBot(infectedId))
            Hud::ShowPlayerHudScratch(infectedId);

        // Check infected if they wear kevlar.
        // If so, they are protected for this hit.
        int infectedTid = Identity::GetTid(infectedId);
        VALIDATE_TID_VALID_SCRIPT(infectedTid);

        if (Player::GetPlayerKevlarPoints(infectedId) > 0)
        {
            // Take a point.
            Player::AddPlayerKevlarPoints(infectedId, -1);

            PlaySound(infectedTid, "items/ARMORHIT", CHAN_AUTO);
            Power::SetPlayerPowerTics(infectedId, Power::POWERZOMBIEPROTECT, 18);
            terminate;
        }

        // Check if they are protected against infection.
        // If so, we damage for 32 (ZH1's claws hit 4 and this protection used to multiply this by 8).
        // Also make immune for 18 tics since the claw can hit multiple times and it kills very quickly.
        if (Power::GetPlayerHasPower(infectedId, Power::POWERHUMANIMMUNITY))
        {
            Power::SetPlayerPowerTics(infectedId, Power::POWERZOMBIEPROTECT, 18);
            SetActivatorToPlayer(infectorId);
            Thing_Damage(infectedTid, 32, MOD_UNKNOWN);
            terminate;
        }

        Game::InfectPlayer(infectedId, Game::INFECT_REGULAR, Game::INFECTSOURCE_PLAYER);
        Event::SendPlayerScratched(infectedId, infectorId);

        // Update score and state.
        Player::IncrementPlayerInfects(infectorId);
        Game::UpdateScoreBoard(infectorId);
        Game::IncreaseTimerOnInfect();

        // Reward the infector.
        // Every 5 infects, give an item.
        if (Player::GetPlayerInfects(infectorId) % 5 == 0)
            Reward::GivePlayerContainer(infectorId, Reward::REWARDORBMINOR);

        Sync::SyncPlayers();
    }

    script "zh2_internal_event_playerkilledbyplayer" (raw packetStr)
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerKilledByPlayer(packet);
        int killedId = GetReceiveData(0);
        int killerId = GetReceiveData(1);

        // Ignore suicide. This should never be possible.
        if (killedId == killerId)
            terminate;

        Logger::LogDebug(LOGSOURCE,
            "\cd" + Player::GetSpecieIndexAsString(Player::GetPlayerSpecie(killerId)) + "\cj " + Player::GetPlayerName(killerId)
            + " has killed \cd"
            + Player::GetSpecieIndexAsString(Player::GetPlayerSpecie(killedId)) + "\cj " + Player::GetPlayerName(killedId) + ".");

        // Determine kill type. Makes the stuff below simpler.
        Player::PlayerSpecieT killerSpecie = Player::GetPlayerSpecie(killerId);
        Player::PlayerSpecieT killedSpecie = Player::GetPlayerSpecie(killedId);
        KillTypeT killType =
            killerSpecie == Player::SPECIEHUMAN && killedSpecie == Player::SPECIEHUMAN ? KILL_TYPE_HUMAN_TO_HUMAN :
            killerSpecie == Player::SPECIEHUMAN && killedSpecie == Player::SPECIEZOMBIE ? KILL_TYPE_HUMAN_TO_ZOMBIE :
            killerSpecie == Player::SPECIEZOMBIE && killedSpecie == Player::SPECIEZOMBIE ? KILL_TYPE_ZOMBIE_TO_ZOMBIE :
            killerSpecie == Player::SPECIEZOMBIE && killedSpecie == Player::SPECIEHUMAN ? KILL_TYPE_ZOMBIE_TO_HUMAN :
            KILL_TYPE_NONE;

        // A kill is accidental if the species match.
        bool accidental = killerSpecie == killedSpecie;

        // Update score and state.
        // For kills to count, the player must either kill a zombie as a human, or kill a human as a zombie.
        if (killType == KILL_TYPE_HUMAN_TO_ZOMBIE)      Player::IncrementPlayerZombieKills(killerId);
        else if (killType == KILL_TYPE_ZOMBIE_TO_HUMAN) Player::IncrementPlayerHumanKills(killerId);

        Game::UpdateScoreBoard(killerId);

        // Reward the killer if the kill is not accidental.
        // Then determine if we killed 2 of the given specie and reward them.
        if (!accidental)
        {
            int count = killType == KILL_TYPE_HUMAN_TO_ZOMBIE
                ? Player::GetPlayerZombieKills(killerId)
                : Player::GetPlayerHumanKills(killerId);

            if (count % 2 == 0)
                Reward::GivePlayerContainer(killerId, Reward::REWARDORBMAJOR);
        }
    }

    script "zh2_internal_event_playerleftround" (raw packetStr)
    {
        // Ignore if the game ended.
        if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
            terminate;

        // Do not overwrite existing end reasons.
        if (Game::GetEndReason() != Game::REASONNONE)
            terminate;

        str packet = (str)packetStr;
        Event::ReceivePlayerLeftRound(packet);
        int id = GetReceiveData(0);
        int reason = GetReceiveData(1);

        int health = Player::GetPlayerHealth(id);
        int maxHealth = GetZombieMaxHealth(id);

        if (Player::GetPlayerIsZombie(id))
        {
            AwardZombieKillByDamage(id, maxHealth);

            // An intentional leave is one which is triggered on:
            // - LEAVEREASON_LEFT
            // - LEAVEREASON_TIMEOUT
            //
            // This means it's unintentional when the following reasons are given:
            // - LEAVEREASON_ERROR
            // - LEAVEREASON_RECONNECT
            // - LEAVEREASON_KICKED
            bool intentional = reason == LEAVEREASON_LEFT || reason == LEAVEREASON_TIMEOUT;

            // Ban a player when playing online.
            // We ignore this when the player is no longer connected, because you can't ban somebody that left.
            if (IsNetworkGame() && intentional && BCSUtils::PlayerIsConnected(id))
            {
                // Effective duration is always the lowest of the two, so either being 0 disables the ban.
                int duration = BCSUtils::Min(ZH2Game::GetMaxBanDuration(), ZH2Game::GetMaxZombieBanDuration());
                if (duration != 0)
                {
                    Logger::LogDebug(LOGSOURCE, "Attempting to ban player (\cd" + str(id) + "\cj) " + BCSUtils::PlayerName(id) + " for \cd" + str(duration) + "\cj minute(s).");

                    if (!BanFromGame(id, duration, ZOMBIELEAVEBANREASON))
                        Logger::LogWarning(LOGSOURCE, "Failed to ban player (\cd" + str(id) + "\cj) " + BCSUtils::PlayerName(id) + " for \cd" + str(duration) + "\cj minute(s).");
                }
                else
                    Logger::LogDebug(LOGSOURCE, "Ignoring ban for player (\cd" + str(id) + "\cj) " + BCSUtils::PlayerName(id) + " for \cd" + str(duration) + "\cj. No duration.");
            }

            if (Game::ZombieCount() == 0)
            {
                AmbientSound("world/RAGEQUIT", 127);
                Game::SetEndReason(Game::REASONZOMBIELEFT);

                // Check if the last leave was within a configured time.
                // If so, we do not want to end the round and continue. Instead we must reset.
                if (CompensateCheckIfRestartNeeded())
                    Game::SetEndAction(Game::ACTION_RESTART);
            }

            // Game is still playing, we should add time to the active timer based on health.
            else
            {
                CompensateHealthForLeavingZombie(id, health);

                if(RoundTimer::GetAnyTimerActive())
                {
                    // If we have max seconds to compensate enabled, add some time based on a factor of it.
                    int maxSeconds = ZH2Game::GetCompensateMaxSecondsReturned();
                    if (maxSeconds != 0)
                    {
                        // Add time to the timer to account for a ragequitting zombie, based on zombie health.
                        // Maximum time is configurable, and gradually less based on hp difference.
                        int tid = Identity::GetTID(id);

                        fixed ratio = fixed(health) / fixed(maxHealth);
                        fixed ratioInverse = 1.0 - ratio;

                        int timerIndex = RoundTimer::GetActiveTimerIndex();
                        int tics = int(ratioInverse * fixed(maxSeconds * 35));
                        int ticDiff = RoundTimer::IncrementTimer(timerIndex, tics);
                        if (ticDiff > 0)
                        {
                            Sync::SyncTimers();

                            // Only show a visual increase if the timer is not hidden.
                            if (RoundTimer::GetTimerVisible(timerIndex))
                                Game::CallVisualAddTime(ticDiff);

                            int displayedSeconds = BCSUtils::Abs(ticDiff / 35);
                            Logger::LogBold("\cjThe timer has been \cdincremented \cjby \cd" + str(displayedSeconds) + "s" + "\cj to adjust for the leaving zombie.");
                        }
                    }
                }
            }
        }
        else if (Player::GetPlayerIsHuman(id))
        {
            if (Game::HumanCount() == 0)
                Game::SetEndReason(Game::REASONHUMANLEFT);
        }

        // If the round ends here, the game ending syncs everything already.
        // Otherwise, the timer compensation above syncs itself as needed.
    }

    internal bool CompensateCheckIfRestartNeeded()
    {
        int seconds = ZH2Game::GetCompensateRestartIfSpecBeforeSeconds();
        return Game::GetPlayTime() < (seconds * 35);
    }

    internal void AwardZombieKillByDamage(int zombieId, int maxHealth)
    {
        int requiredPercentage = ZH2Game::GetCompensateAwardKillDamagePercentage();
        if (requiredPercentage == 0)
        {
            Logger::LogDebug(LOGSOURCE, "Ignoring zombie kill damage award. Required percentage is 0.");
            return;
        }

        int requiredDamage = (maxHealth * requiredPercentage) / 100;
        if (requiredDamage <= 0)
        {
            Logger::LogDebug(LOGSOURCE, "Ignoring zombie kill damage award. Required damage is \cd" + str(requiredDamage) + "\cj.");
            return;
        }

        Logger::LogDebug(LOGSOURCE,
            "Evaluating zombie kill damage award for player (\cd" + str(zombieId) + "\cj) "
            + Player::GetPlayerName(zombieId)
            + ". Zombie start health: \cd" + str(maxHealth)
            + "\cj. Required percentage: \cd" + str(requiredPercentage)
            + "%\cj. Required damage: \cd" + str(requiredDamage) + "\cj.");

        int awardedId = -1;
        int awardedDamage = 0;

        for (int i = 0; i < BCSUtils::MAX_PLAYERS; i++)
        {
            if (!Player::GetPlayerIsHuman(i))
                continue;

            int damage = Player::GetPlayerDamageToPlayer(i, zombieId);
            if (damage == 0)
                continue;

            if (damage < requiredDamage)
            {
                Logger::LogDebug(LOGSOURCE, "Rejected candidate (\cd" + str(i) + "\cj) " + Player::GetPlayerName(i) + "dealt \cd" + str(damage) + "\cj damage. Damage is below required damage.");
                continue;
            }

            if (damage <= awardedDamage)
            {
                Logger::LogDebug(LOGSOURCE, "Rejected candidate (\cd" + str(i) + "\cj) " + Player::GetPlayerName(i) + "dealt \cd" + str(damage) + "\cj damage. Current best candidate has equal or higher damage.");
                continue;
            }

            awardedId = i;
            awardedDamage = damage;

            Logger::LogDebug(LOGSOURCE, "Current best zombie kill award candidate is (\cd" + str(i) + "\cj) " + Player::GetPlayerName(i) + " with \cd" + str(damage) + "\cj damage.");
        }

        // Sort of failsafe, it's possible the zombie only got damaged by the environment or monsters.
        if (awardedId == -1)
        {
            Logger::LogDebug(LOGSOURCE, "No player qualified for the zombie kill damage award.");
            return;
        }

        // TODO: Merge this with the other kill code.
        Player::IncrementPlayerZombieKills(awardedId);
        Game::UpdateScoreBoard(awardedId);

        if (Player::GetPlayerZombieKills(awardedId) % 2 == 0)
            Reward::GivePlayerContainer(awardedId, Reward::REWARDORBMAJOR);

        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            Append(s:"Player ");
            Append(s:BCSUtils::PlayerName(awardedId));
            Append(s:" has been awarded the zombie kill for dealing \cd");
            Append(d:awardedDamage);
            Append(s:"\cj/\cd");
            Append(d:maxHealth);
            Append(s:"\cj damage.");
        }

        Logger::LogBold(logMessage);
    }

    internal int GetZombieMaxHealth(int zombieId)
    {
        bool isInitialZombie = Player::GetPlayerInitialZombie(zombieId);
        return isInitialZombie
            ? Game::GetInitialZombieMaxHealth()
            : Game::GetRegularZombieMaxHealth();
    }

    internal void CompensateHealthForLeavingZombie(int id, int health)
    {
        int factor = ZH2Game::GetCompensateHealthFactorReturned();
        if (factor == 0)
            return;

        int zombieCount = 0;

        for (int i = 0; i < BCSUtils::MAX_PLAYERS; i++)
        {
            if (i != id && Player::GetPlayerIsZombie(i))
                zombieCount++;
        }

        if (zombieCount == 0)
            return;

        int compensatedHealth = (health * factor) / 100;
        int healthPerZombie = compensatedHealth / zombieCount;

        if (healthPerZombie <= 0)
            return;

        for (int i = 0; i < BCSUtils::MAX_PLAYERS; i++)
        {
            // Failsafe
            if (i == id)
                continue;

            int tid = Identity::GetTID(i);
            if (!Player::GetPlayerIsZombie(i) || !BCSUtils::ActorIsAlive(tid))
                continue;

            SetActorProperty(tid, APROP_HEALTH, GetActorProperty(tid, APROP_HEALTH) + healthPerZombie);
        }

        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            Append(s:"The zombie's \cd");
            Append(d:compensatedHealth);
            Append(s:" health \cjhas ");

            if (zombieCount == 1)
            {
                Append(s:"been transferred to the remaining zombie.");
            }
            else
            {
                Append(s:"been divided over the remaining zombies, granting \cd");
                Append(d:healthPerZombie);
                Append(s:" health \cjto each.");
            }
        }

        Logger::LogBold(logMessage);
    }

    script "zh2_internal_event_specie_changed" (raw packetStr)
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerSpecieChanged(packet);
        int id = GetReceiveData(0);
        int specieIndex = GetReceiveData(1);

        Player::PlayerSpecieT specie = Player::GetSpecieTypeByIndex(specieIndex);

        // Full reset of powers on specie change.
        // It might be possible the speed is not reset, so we force it.
        Power::ResetPlayerPowers(id, true);
        Sync::SyncPowers();
    }
}