#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    script "zh2_internal_event_prescratched" (raw packetStr)
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerScratched(packet);
        int infectedId = GetReceiveData(0);
        int infectorId = GetReceiveData(1);

        // Double check a zombie infects a human.
        // If two players infect on the same tic, this can not be the case.
        if (!Player::GetPlayerIsHuman(infectedId) || !Player::GetPlayerIsZombie(infectorId))
            terminate;

        Logger::LogDebug(LOGSOURCE, "Scratching (\cd" + str(infectedId) + "\cj) " + BCSUtils::PlayerName(infectedId) + " by (\cd" + str(infectorId) + "\cj) " + BCSUtils::PlayerName(infectorId) + ".");

        // Check for protection.
        if (Power::GetPlayerHasPower(infectedId, Power::POWERZOMBIEPROTECT))
            terminate;

        // Always visualize a scratch at this point.
        if (!PlayerIsBot(infectedId))
            Hud::ShowPlayerHudScratch(infectedId);

        // Check infected if they wear kevlar.
        // If so, they are protected for this hit.
        int infectedTid = Identity::GetTid(infectedId);
        VALIDATE_TID_VALID_SCRIPT(infectedTid);

        if (Player::GetPlayerKevlarPoints(infectedId) > 0)
        {
            // Take a point.
            Player::AddPlayerKevlarPoints(infectedId, -1);

            PlaySound(infectedTid, "items/ARMORHIT", CHAN_AUTO);
            Power::SetPlayerPowerTics(infectedId, Power::POWERZOMBIEPROTECT, 18);
            terminate;
        }

        // Check if they are protected against infection.
        // If so, we damage for 32 (ZH1's claws hit 4 and this protection used to multiply this by 8).
        // Also make immune for 18 tics since the claw can hit multiple times and it kills very quickly.
        if (Power::GetPlayerHasPower(infectedId, Power::POWERHUMANIMMUNITY))
        {
            Power::SetPlayerPowerTics(infectedId, Power::POWERZOMBIEPROTECT, 18);
            SetActivatorToPlayer(infectorId);
            Thing_Damage(infectedTid, 32, MOD_UNKNOWN);
            terminate;
        }

        Game::InfectPlayer(infectedId, Game::INFECT_REGULAR, Game::INFECTSOURCE_PLAYER);
        Event::SendPlayerScratched(infectedId, infectorId);

        // Update score and state.
        Player::IncrementPlayerInfects(infectorId);
        Game::UpdateScoreBoard(infectorId);
        Game::IncreaseTimerOnInfect();

        // Reward the infector.
        // Every 5 infects, give an item.
        if (Player::GetPlayerInfects(infectorId) % 5 == 0)
            Reward::GivePlayerContainer(infectorId, Reward::REWARDORBMINOR);

        Sync::SyncPlayers();
    }

    script "zh2_internal_event_playerkilledbyplayer" (raw packetStr)
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerKilledByPlayer(packet);
        int killedId = GetReceiveData(0);
        int killerId = GetReceiveData(1);

        // Ignore suicide. This should never be possible.
        if (killedId == killerId)
            terminate;

        Logger::LogDebug(LOGSOURCE,
            "\cd" + Player::GetSpecieIndexAsString(Player::GetPlayerSpecie(killerId)) + "\cj " + Player::GetPlayerName(killerId)
            + " has killed \cd"
            + Player::GetSpecieIndexAsString(Player::GetPlayerSpecie(killedId)) + "\cj " + Player::GetPlayerName(killedId) + ".");

        // Determine kill type. Makes the stuff below simpler.
        Player::PlayerSpecieT killerSpecie = Player::GetPlayerSpecie(killerId);
        Player::PlayerSpecieT killedSpecie = Player::GetPlayerSpecie(killedId);
        KillTypeT killType =
            killerSpecie == Player::SPECIEHUMAN && killedSpecie == Player::SPECIEHUMAN ? KILL_TYPE_HUMAN_TO_HUMAN :
            killerSpecie == Player::SPECIEHUMAN && killedSpecie == Player::SPECIEZOMBIE ? KILL_TYPE_HUMAN_TO_ZOMBIE :
            killerSpecie == Player::SPECIEZOMBIE && killedSpecie == Player::SPECIEZOMBIE ? KILL_TYPE_ZOMBIE_TO_ZOMBIE :
            killerSpecie == Player::SPECIEZOMBIE && killedSpecie == Player::SPECIEHUMAN ? KILL_TYPE_ZOMBIE_TO_HUMAN :
            KILL_TYPE_NONE;

        // A kill is accidental if the species match.
        bool accidental = killerSpecie == killedSpecie;

        // Update score and state.
        // For kills to count, the player must either kill a zombie as a human, or kill a human as a zombie.
        if (killType == KILL_TYPE_HUMAN_TO_ZOMBIE)      Player::IncrementPlayerZombieKills(killerId);
        else if (killType == KILL_TYPE_ZOMBIE_TO_HUMAN) Player::IncrementPlayerHumanKills(killerId);

        Game::UpdateScoreBoard(killerId);

        // Reward the killer if the kill is not accidental.
        // Then determine if we killed 2 of the given specie and reward them.
        if (!accidental)
        {
            int count = killType == KILL_TYPE_HUMAN_TO_ZOMBIE
                ? Player::GetPlayerZombieKills(killerId)
                : Player::GetPlayerHumanKills(killerId);

            if (count % 2 == 0)
                Reward::GivePlayerContainer(killerId, Reward::REWARDORBMAJOR);
        }
    }

    script "zh2_internal_event_playerleftround" (raw packetStr)
    {
        // Ignore if the game ended.
        if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
            terminate;

        // Do not overwrite existing end reasons.
        if (Game::GetEndReason() != Game::REASONNONE)
            terminate;

        str packet = (str)packetStr;
        Event::ReceivePlayerLeftRound(packet);
        int id = GetReceiveData(0);
        int reason = GetReceiveData(1);

        if (Player::GetPlayerIsZombie(id))
        {
            // An intentional leave is one which is triggered on:
            // - LEAVEREASON_LEFT
            // - LEAVEREASON_TIMEOUT
            //
            // This means it's unintentional when the following reasons are given:
            // - LEAVEREASON_ERROR
            // - LEAVEREASON_RECONNECT
            // - LEAVEREASON_KICKED
            bool intentional = reason == LEAVEREASON_LEFT || reason == LEAVEREASON_TIMEOUT;

            // Ban a player when playing online.
            // We ignore this when the player is no longer connected, because you can't ban somebody that left.
            if (IsNetworkGame() && intentional && BCSUtils::PlayerIsConnected(id))
            {
                int duration = ZH2Game::GetMaxBanDuration();
                if (duration != 0)
                {
                    Logger::LogDebug(LOGSOURCE, "Attempting to ban player (\cd" + str(id) + "\cj) " + BCSUtils::PlayerName(id) + " for \cd" + str(duration) + "\cj minute(s).");

                    if (!BanFromGame(id, duration, ZOMBIELEAVEBANREASON))
                        Logger::LogWarning(LOGSOURCE, "Failed to ban player (\cd" + str(id) + "\cj) " + BCSUtils::PlayerName(id) + " for \cd" + str(duration) + "\cj minute(s).");
                }
                else
                    Logger::LogDebug(LOGSOURCE, "Ignoring ban for player (\cd" + str(id) + "\cj) " + BCSUtils::PlayerName(id) + " for \cd" + str(duration) + "\cj. No duration.");
            }

            if (Game::ZombieCount() == 0)
            {
                Game::SetEndReason(Game::REASONZOMBIELEFT);
                AmbientSound("world/RAGEQUIT", 127);
            }

            // Game is still playing, we should add time to the active timer.
            else if(RoundTimer::GetAnyTimerActive())
            {
                // If we have max seconds to compensate enabled, add some time based on a factor of it.
                int maxSeconds = ZH2Game::GetCompensateMaxSecondsReturned();
                if (maxSeconds != 0)
                {
                    // Add time to the timer to account for a ragequitting zombie, based on zombie health.
                    // Maximum is 30 seconds, gradually less based on hp difference.
                    int tid = Identity::GetTID(id);
                    VALIDATE_TID_VALID_SCRIPT(tid);

                    int health = GetActorProperty(tid, APROP_SPAWNHEALTH);
                    int healthMax = GetActorProperty(tid, APROP_HEALTH);

                    fixed ratio = fixed(health) / fixed(healthMax);
                    fixed ratioInverse = 1.0 - ratio;

                    int tics = int(ratioInverse * fixed(maxSeconds * 35));
                    int ticDiff = RoundTimer::IncrementTimer(RoundTimer::GetActiveTimerIndex(), tics);
                    if (ticDiff > 0)
                    {
                        Game::CallVisualAddTime(ticDiff);
                        int displayedSeconds = BCSUtils::Abs(ticDiff / 35);
                        Logger::LogBold("\cjThe timer has been \cdincremented \cjby \cd" + str(displayedSeconds) + "s" + "\cj to adjust for the leaving zombie.");
                    }
                }
            }
        }
        else if (Player::GetPlayerIsHuman(id))
        {
            if (Game::HumanCount() == 0)
                Game::SetEndReason(Game::REASONHUMANLEFT);
        }

        // No sync, the game ending does it already.
    }

    script "zh2_internal_event_specie_changed" (raw packetStr)
    {
        str packet = (str)packetStr;
        Event::ReceivePlayerSpecieChanged(packet);
        int id = GetReceiveData(0);
        int specieIndex = GetReceiveData(1);

        Player::PlayerSpecieT specie = Player::GetSpecieTypeByIndex(specieIndex);

        // Full reset of powers on specie change.
        // It might be possible the speed is not reset, so we force it.
        Power::ResetPlayerPowers(id, true);
        Sync::SyncPowers();
    }
}