#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    void ReceiveInitialsChosen(str packet)
    {
        packet = Packet::Read(packet);
        int count = Packet::Value;
        SetReceiveData(0, count);

        int index = 1;
        while (count--)
        {
            packet = Packet::Read(packet);
            SetReceiveData(index++, Packet::Value);
        }
    }

    void ReceivePlayerLeftRound(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        SetReceiveData(0, id);
    }

    void ReceivePlayerDied(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        packet = Packet::Read(packet);
        int type = Packet::Value;

        SetReceiveData(0, id);
        SetReceiveData(1, type);
    }

    void ReceivePlayerKilledByPlayer(str packet)
    {
        packet = Packet::Read(packet);
        int killedId = Packet::Value;

        packet = Packet::Read(packet);
        int killerId = Packet::Value;

        packet = Packet::Read(packet);
        int itemIndex = Packet::Value;

        packet = Packet::Read(packet);
        int addFireEffect = Packet::Value;

        packet = Packet::Read(packet);
        int addAcidEffect = Packet::Value;

        SetReceiveData(0, killedId);
        SetReceiveData(1, killerId);
        SetReceiveData(2, itemIndex);
        SetReceiveData(3, addFireEffect);
        SetReceiveData(4, addAcidEffect);
    }

    void ReceivePlayerKilledByMonster(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        packet = Packet::ReadStr(packet);
        str monsterName = Packet::Value;

        SetReceiveData(0, id);
        SetReceiveData(1, monsterName);
    }

    void ReceivePlayerScratched(str packet)
    {
        packet = Packet::Read(packet);
        int attackedId = Packet::Value;

        packet = Packet::Read(packet);
        int attackerId = Packet::Value;

        SetReceiveData(0, attackedId);
        SetReceiveData(1, attackerId);
    }

    void ReceivePlayerCured(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        packet = Packet::Read(packet);
        int transformed = Packet::Value;

        packet = Packet::Read(packet);
        int sourceInt = Packet::Value;

        SetReceiveData(0, id);
        SetReceiveData(1, transformed);
        SetReceiveData(2, sourceInt);
    }

    void ReceivePlayerInfected(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        packet = Packet::Read(packet);
        int typeInt = Packet::Value;

        packet = Packet::Read(packet);
        int sourceInt = Packet::Value;

        SetReceiveData(0, id);
        SetReceiveData(1, typeInt);
        SetReceiveData(2, sourceInt);
    }

    void ReceivePlayerSpecieChanged(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        packet = Packet::Read(packet);
        int specieInt = Packet::Value;

        SetReceiveData(0, id);
        SetReceiveData(1, specieInt);
    }

    void ReceivePlayerSafe(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        packet = Packet::Read(packet);
        int safe = Packet::Value;

        packet = Packet::Read(packet);
        int firstTime = Packet::Value;

        SetReceiveData(0, id);
        SetReceiveData(1, safe);
        SetReceiveData(2, firstTime);
    }

    void ReceiveResistStarted(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveResistElapsed(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveResistStopped(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveRoundSwitched(str packet)
    {
        packet = Packet::Read(packet);
        int prevIndex = Packet::Value;

        packet = Packet::Read(packet);
        int newIndex = Packet::Value;

        SetReceiveData(0, prevIndex);
        SetReceiveData(1, newIndex);
    }

    void ReceiveTimerStarted(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveTimerStopped(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveTimerPaused(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveTimerResumed(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveTimerElapsed(str packet)
    {
        packet = Packet::Read(packet);
        int index = Packet::Value;

        SetReceiveData(0, index);
    }

    void ReceiveTimerSwitched(str packet)
    {
        packet = Packet::Read(packet);
        int prevIndex = Packet::Value;

        packet = Packet::Read(packet);
        int newIndex = Packet::Value;

        SetReceiveData(0, prevIndex);
        SetReceiveData(1, newIndex);
    }

    void ReceivePowerExpired(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        SetReceiveData(0, id);
    }

    void ReceiveActorDamaged(str packet)
    {
        packet = Packet::Read(packet);
        int id = Packet::Value;

        packet = Packet::Read(packet);
        int tid = Packet::Value;

        packet = Packet::Read(packet);
        int damage = Packet::Value;

        packet = Packet::Read(packet);
        int targetDied = Packet::Value;

        SetReceiveData(0, id);
        SetReceiveData(1, tid);
        SetReceiveData(2, damage);
        SetReceiveData(3, targetDied);
    }

    void ReceiveActorDamagedClientTotal(str packet)
    {
        packet = Packet::Read(packet);
        int tid = Packet::Value;

        packet = Packet::Read(packet);
        int damage = Packet::Value;

        packet = Packet::Read(packet);
        int targetDied = Packet::Value;

        SetReceiveData(0, tid);
        SetReceiveData(1, damage);
        SetReceiveData(2, targetDied);
    }
}