#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawSummaryHeader()
    {
        // Different header if the timer is TIMERVOTED
        if (RoundTimer::GetActiveTimerKnownType() == RoundTimer::TIMERVOTED)
        {
            // Top
            BCSUtils::HudSetFont("BigFont");

            HudSetPointInternal();
            BCSUtils::HudDrawText(--_drawnHudId, "The map has been picked");
            DebugDraw();

            return;
        }

        // Top
        BCSUtils::HudSetFont("BigFont");

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, "Pick the next map");
        DebugDraw();

        // Bottom
        BCSUtils::HudSetFont("SmallFont");

        HudSetPointInternal(0.0, 15.0);
        BCSUtils::HudDrawText(--_drawnHudId, "or have the game decide");
        DebugDraw();
    }
}