#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "header.acs"
#include "tip.acs"
#include "maplist.acs"

strict namespace Hud
{
    // TODO: The fade offsetting is not fully correct here. Should somebody ever encoutner issues it should be revisited.
    internal void DrawSummaryHud()
    {
        // Draw a fade to black out the window.
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(32.0, 32.0);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        Utils::ScaleToScreen();

        PrepareHud(
            64.0,
            64.0,
            false);

        SetFade();

        // Draw other parts.
        fixed scale = ZH2Game::GetHudSummaryScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_TOP);
        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudSetVirtualSize(640.0, 480.0);
        BCSUtils::HudSetScale(scale);

        PrepareHud(
            320.0,
            BCSUtils::HudTop() + 60.0,
            false);

        DrawSummaryHeader();

        PrepareHud(
            320.0,
            BCSUtils::HudTop() + 120.0,
            false);

        DrawTip();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_BOTTOM);

        PrepareHud(
            100.0,
            BCSUtils::HudBottom() - 80.0,
            false);

        DrawMapList();
    }

    internal void SetFade()
    {
        int voteTic = Game::GetGameVotingTic();
        int diff = Utils::GetSynchronizedTimer() - voteTic;

        if (voteTic == 0 || diff <= 0)
            return;

        // 1 second of fadeout.
        fixed fadeAmount = BCSUtils::Min(1.0, fixed(diff) / 35.0);
        BCSUtils::HudSetAlpha(fadeAmount);

        HudSetPointInternal();
        BCSUtils::HudDrawImage(HUDID_SUMMARY_FADE, "BLACK");
    }
}