#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace EventBus
{
    // Defines an event for the event bus to use.
    internal struct EventBusEventContextT
    {
        str EventKey;
        str ScriptNameCallbacks[20];
        int ScriptNumberCallbacks[20];

        // Tracks the number of callbacks registered so we can determine if more can be added.
        int ScriptNameCallbackCount,
            ScriptNumberCallbackCount;
    };

    extern void AddCallbackByScriptName(str eventKey, str scriptName);
    extern void AddCallbackByScriptNumber(str eventKey, int scriptNumber);
    extern void CallEvent(str eventKey, raw arg1 = 0, raw arg2 = 0, raw arg3 = 0);
}