#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "EventBus"

// TODO: Use a reference type, but for some reason it would not mutate values.

strict namespace EventBus
{
    void AddCallbackByScriptName(str eventKey, str scriptName)
    {
        int index = EnsureEventExists(eventKey);
        if (index == -1)
        {
            Logger::LogError(LOGSOURCE, "Failed to add event " + eventKey + " with script name callback " + scriptName +". Maximum event bus capacity reached of " + str(lengthof(ZH2Lib::LibContext.EventBusCollection)) + ".");
            return;
        }

        // Add callback if there is space.
        if (lengthof(ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNameCallbacks) == ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNameCallbackCount)
        {
            Logger::LogError(LOGSOURCE, "Failed to add event " + eventKey + " with script name callback " + scriptName +". Maximum event callback capacity reached of " + str(ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNameCallbackCount) + ".");
            return;
        }

        Logger::LogDebug(LOGSOURCE, "Added new event event callback for \cd" + eventKey + "\cj: \cd" + scriptName + "\cj.");
        ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNameCallbacks[ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNameCallbackCount++] = scriptName;
    }

    void AddCallbackByScriptNumber(str eventKey, int scriptNumber)
    {
        int index = EnsureEventExists(eventKey);
        if (index == -1)
        {
            Logger::LogError(LOGSOURCE, "Failed to add event " + eventKey + " with script number callback " + str(scriptNumber) +". Maximum event bus capacity reached of " + str(lengthof(ZH2Lib::LibContext.EventBusCollection)) + ".");
            return;
        }

        // Add callback if there is space.
        if (lengthof(ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNumberCallbacks) == ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNumberCallbackCount)
        {
            Logger::LogError(LOGSOURCE, "Failed to add event " + eventKey + " with script number callback " + str(scriptNumber) +". Maximum event callback capacity reached of " + str(ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNumberCallbackCount) + ".");
            return;
        }

        Logger::LogDebug(LOGSOURCE, "Added new event event callback for \cd" + eventKey + "\cj: \cd" + str(scriptNumber) + "\cj.");
        ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNumberCallbacks[ZH2Lib::LibContext.EventBusCollection.Collection[index].ScriptNumberCallbackCount++] = scriptNumber;
    }

    void CallEvent(str eventKey, raw arg1 = 0, raw arg2 = 0, raw arg3 = 0)
    {
        Logger::LogDebug(LOGSOURCE, "Calling event " + eventKey + ".");
        int index = GetEventIndexByKey(eventKey);
        if (index == -1)
        {
            Logger::LogDebug(LOGSOURCE, "Event " + eventKey + " was not found.");
            return;
        }

        // Note, we use `ACS_(Named)ExecuteWithResult` here to ensure the event is passed without a tic delay.

        int scriptNameCallbackCount = ZH2Lib::LibContext.EventBusCollection.Collection[index].scriptNameCallbackCount;
        for (int i = 0; i < scriptNameCallbackCount; ++i)
        {
            str scriptName = ZH2Lib::LibContext.EventBusCollection.Collection[index].scriptNameCallbacks[i];
            ACS_NamedExecuteWithResult(scriptName, arg1, arg2, arg3);
        }

        int scriptNumberCallbackCount = ZH2Lib::LibContext.EventBusCollection.Collection[index].scriptNumberCallbackCount;
        for (int i = 0; i < scriptNumberCallbackCount; ++i)
        {
            int scriptNumber = ZH2Lib::LibContext.EventBusCollection.Collection[index].scriptNumberCallbacks[i];
            ACS_ExecuteWithResult(scriptNumber, arg1, arg2, arg3);
        }
    }

    internal int EnsureEventExists(str eventKey)
    {
        int index = GetEventIndexByKey(eventKey);

        if (index != -1)
            return index;

        // Ensure we have space
        if (lengthof(ZH2Lib::LibContext.EventBusCollection.Collection) == ZH2Lib::LibContext.EventBusCollection.Count)
            return -1;

        Logger::LogDebug(LOGSOURCE, "Added new event bus event \cd" + eventKey + "\cj on index \cd" + str(ZH2Lib::LibContext.EventBusCollection.Count) + "\cj.");
        ZH2Lib::LibContext.EventBusCollection.Collection[ZH2Lib::LibContext.EventBusCollection.Count++].eventKey = eventKey;

        return ZH2Lib::LibContext.EventBusCollection.Count - 1;
    }

    internal int GetEventIndexByKey(str eventKey)
    {
        for (int i = 0; i < ZH2Lib::LibContext.EventBusCollection.Count; ++i)
        {
            if (BCSUtils::StrIEquals(eventKey, ZH2Lib::LibContext.EventBusCollection.Collection[i].eventKey))
                return i;
        }

        return -1;
    }
}

#undef LOGSOURCE 
