// Preprocessor definitions used in the sync namespace.

// Verify the sync id has not reached an out-of-bounds value.
#define VERIFY_SYNCID(syncId, base, length) \
    if (base - length > syncId) \
    { \
        Logger::LogError(LogSource, FormatLog(SYNC_CATEGORY, "Sync system function '\cd" + __FUNCTION__ + "\cj' has an out of bounds sync value. Current sync id \cd" + str(syncId) + "\cj is below base id \cd" + str(base) + "\cj - \cd" + str(length) + "\cj = \cd" + str(base - length) + "\cj.")); \
    } \
    Logger::LogDebug(LogSource, FormatLog(SYNC_CATEGORY, "Sync system function '\cd" + __FUNCTION__ + "\cj' id is now \cd" + str(base) + "\cj < \cd" + str(syncId) + "\cj."));