#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// TODO: Reorganize this mess.
strict namespace Sync
{
    #define ACTOR_SYNC_PLAYER_NAME_TEMPLATE "__playername%n"

    #define ACTOR_SYNC_TIMER_LABEL_TEMPLATE "__timerlabel%n"

    #define ACTOR_SYNC_RESIST_LABEL_TOP_TEMPLATE "__resistlabeltop%n"
    #define ACTOR_SYNC_RESIST_LABEL_BOTTOM_TEMPLATE "__resistlabelbottom%n"

    #define SYNC_BASE 900
    
    #define SYNC_PLAYERS SYNC_BASE + 300
    #define SYNC_ROUNDTIMERS SYNC_PLAYERS + MAX_TIMERS * 10
    #define SYNC_RESISTS SYNC_ROUNDTIMERS + MAX_RESISTS * 10
    #define SYNC_ROUND SYNC_RESISTS + 200
    #define SYNC_ADMIN SYNC_ROUND + 50
    #define SYNC_GAME SYNC_ADMIN + 1000
    #define SYNC_MAPVOTING SYNC_GAME + 50
}