#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Full list of CVars defined in the code.
// Used by both the internal code and as externed data, as a shared file.
// This also provides an easy way to define CVar values only once instead of defining both its core function + extern function.

strict namespace CVar
{
    // ZE11
    CVAR_SV_BOOL(Ze11EnableFrozenTeleporting)

    // ZE14
    CVAR_CL_BOOL(Ze14EnableDynamicLights)

    // ZE26
    CVAR_SV_INT_CLAMPED(Ze26Flow, 0, 2)

    // ZM06
    CVAR_SV_INT_CLAMPED(Zm06Event, 0, 3)

    // ZM14
    CVAR_CL_BOOL(Zm14EnableDynamicLights)
}
