#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#linklibrary "ZH2Lib"

#include "libbcs.h.acs"

#include "zh2lib/common.h.acs"

#include "zh2lib/preprocessor/event.h.acs"
#include "zh2lib/preprocessor/context.h.acs"
#include "zh2lib/preprocessor/identity.h.acs"
#include "zh2lib/preprocessor/sync.h.acs"

#include "zh2lib/utils/utils.h.acs"
#include "zh2lib/tokenizer/tokenize.h.acs"
#include "zh2lib/weather/weather.h.acs"
#include "zh2lib/logger/logger.h.acs"
#include "zh2lib/hook/hook.h.acs"
#include "zh2lib/eventbus/eventbus.h.acs"
#include "zh2lib/bitMath/bitmath.h.acs"
#include "zh2lib/packet/packet.h.acs"
#include "zh2lib/weight/weight.h.acs"
#include "zh2lib/chat/chat.h.acs"
#include "zh2lib/event/event.h.acs"
#include "zh2lib/sync/sync.h.acs"
#include "zh2lib/identity/identity.h.acs"
#include "zh2lib/footstep/footstep.h.acs"
#include "zh2lib/spaceutil/spaceutil.h.acs"
#include "zh2lib/teleportutil/teleportutil.h.acs"
#include "zh2lib/trackedproperties/trackedproperties.h.acs"
#include "zh2lib/decorate/decorate.h.acs"
#include "zh2lib/io/io.h.acs"
#include "zh2lib/math/math.h.acs"

strict namespace ZH2Lib
{
    #define PERSISTINGLIBCONTEXTINDEX 2

    LibContextT LibContext;
    global PersistingLibContextT PERSISTINGLIBCONTEXTINDEX: PersistingLibContext;

    struct LibContextT
    {
        LibPlayerT Players[BCSUtils::MAX_PLAYERS];

        Weight::WeightContextT WeightContext;

        // Clientside and serverside handled. Not synched.
        // Stores the eventbus keys and their callbacks.
        EventBus::EventBusCollectionT EventBusCollection;

        // Clientside and serverside handled. Not synched.
        // Stores received data from events, which has been unpacked.
        Event::EventReceiveContextT EventReceiveContext;

        Weather::WeatherContextT WeatherContext;

        Sync::LibSyncContextT SyncContext;
    };

    struct LibPlayerT
    {
        // Not synced, tracks properties on a player, allowing subsequent setting and unsetting of the property.
        int TrackedPropertyCounters[MAX_TRACKEDPROPERTIES];

        // Serverside. Indicates if the player is explicitly allowed to walk through other actors.
        // A tertiary state exists for returning to default.
        SpaceUtil::PlayerThruActorsStateT ThruActorsState;

        // Clientside
        Footstep::PlayerFootstepStateT FootstepState;
    };

    struct PersistingLibContextT
    {
        Logger::LogContextT LogContext;
        Footstep::StepCollectionContextT StepContext;
        Weather::PersistingWeatherContextT WeatherContext;
    };

    extern void ResetPlayerLibContext(int id);
    extern bool GetUseSyncBuffer();
}