#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Monster
{
    script "zh2_dec_zm09_soulsphere_getdamage" (void)
    {
        if (CheckScript("zm09_soulsphere_getdamage_impl", true))
            setresultvalue(ACS_NamedExecuteWithResult("zm09_soulsphere_getdamage_impl"));

        // Determined default outside of ZM09
        else
            setresultvalue(2);
    }
}
