#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Monster
{
    script "zh2_dec_zm09_imscared_onattack" (void)
    {
        SetHudSize(640, 480, true);
        SetFont("ISCAR");
        ActivatorSound("SOULFUCK", 255);
        HudMessage(s:"A"; HUDMSG_FADEINOUT, 0, CR_UNTRANSLATED, 0.5, 0.5, 5.0, 0.0, 0.2);

        if (CheckScript("zm09_imscared_onattack_impl", true))
        {
            ACS_NamedExecute("zm09_imscared_onattack_impl", 0);
            NamedScriptWait("zm09_imscared_onattack_impl");
        }

        SetFont("SMALLFONT");
    }
}
