#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace LibSync
{
    #define LIB_SYNC_BASE 1600

    #define SYNC_WEATHER_LENGTH (EMITTER_WEATHER_COUNT * 8)
    #define SYNC_WEATHER LIB_SYNC_BASE + SYNC_WEATHER_LENGTH

    extern void SyncAll(bool callSyncOnClients = true);
    extern void CallClientSyncAll();
    extern void SyncAllClientside();

    extern void SyncWeather(bool callSyncOnClients = true);
    extern void CallSyncWeatherOnClients();
    extern void SyncWeatherClientside();
}