#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal int _startDrawIndex = 0;

    internal void DrawRadioHud()
    {
        int size = Decorate::GetRadioCollectionSize();

        int currentIndex = Decorate::GetClientRadioCurrentlySelectedIndex();
        int endDrawIndex = GetEndDrawIndex(_startDrawIndex);

        // Adjust the start index to stay within bounds.
        // Best to always make sure these are in bounds in case the user manually pukes a script.
        if (size != 0)
        {
            if (_startDrawIndex > currentIndex)
            {
                _startDrawIndex = currentIndex;
                endDrawIndex = GetEndDrawIndex(_startDrawIndex);
            }

            if (endDrawIndex <= currentIndex)
            {
                _startDrawIndex = BCSUtils::Max(0, currentIndex - WEAPON_RADIO_MAX_DRAWN_TRACKS + 1);
                endDrawIndex = GetEndDrawIndex(_startDrawIndex);
            }
        }

        if (!Weapon::CheckWielded(Weapon::WEAPONTYPE_RADIO))
            return;

        BCSUtils::HudSetFont("BigFont");
        BCSUtils::HudSetTextColor(CR_WHITE);

        HudSetPointInternal(6.0, 0.0);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_RADIOHEADER_GRAPHIC);

        HudSetPointInternal(20.0, 0.0);
        BCSUtils::HudDrawText(--_drawnHudId, "Track list");
        DebugDraw();

        BCSUtils::HudSetFont("SmallFont");

        // The vertical offset will move down with each track.
        fixed addY = 28.0;

        // No tracks to display.
        if (size == 0)
        {
            BCSUtils::HudSetTextColor(CR_YELLOW);

            HudSetPointInternal(20.0, addY);
            BCSUtils::HudDrawText(--_drawnHudId, "No tracks to display. Add some!");
            DebugDraw();
            return;
        }

        addY += 4.0;

        for (int i = _startDrawIndex; i < endDrawIndex; ++i)
        {
            HudSetPointInternal(-5.0, addY);
            BCSUtils::HudDrawImage(--_drawnHudId, i == currentIndex ? HUD_RADIO_TRACK_SELECTED_GRAPHIC : HUD_RADIOTRACK_GRAPHIC);

            HudSetPointInternal(20.0, addY + 2.0);
            BCSUtils::HudDrawText(--_drawnHudId, Decorate::GetRadioTrackName(i));
            DebugDraw();

            addY += 30.0;
        }

        addY -= 4.0;

        str author = Decorate::GetRadioTrackAuthor(currentIndex);
        if ((raw)author != 0 && author != "")
        {
            BCSUtils::HudSetTextColor(CR_GRAY);
            BCSUtils::HudSetFont("SmallFont");

            HudSetPointInternal(20.0, addY);
            BCSUtils::HudDrawText(--_drawnHudId, "By " + author);

            addY += 10.0;
        }

        str remark = Decorate::GetRadioTrackRemark(currentIndex);
        if ((raw)remark != 0 && remark != "")
        {
            BCSUtils::HudSetTextColor(CR_GRAY);
            BCSUtils::HudSetFont("SmallFont");

            HudSetPointInternal(20.0, addY);
            BCSUtils::HudDrawText(--_drawnHudId, remark);
        }
    }

    internal int GetEndDrawIndex(int startDrawIndex)
    {
        return BCSUtils::Min(startDrawIndex + WEAPON_RADIO_MAX_DRAWN_TRACKS, Decorate::GetRadioCollectionSize());
    }
}