#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Power
{
    internal void Tic()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        // Check if the activator's powers have expired.
        bool hasExpired = false;

        str logMessage;
        BuildMsg(logMessage = StrParam())
        {
            int id = PlayerNumber();
            Append(s:"Power(s) expired of " + BCSUtils::PlayerName(id) + ": ");

            for (int i = 0; i < ZH2Game::PersistingGameContext.PowerCollection.Size; ++i)
            {
                if (!GetPlayerHasPower(id, i))
                    continue;

                // If the player has the power but no tics, we need to take away the power.
                if (GetPlayerPowerTicsLeft(id, i) > 0)
                    continue;

                BCSUtils::SetActorInventory(Identity::GetTid(id), GetItemName(i), 0);

                if (hasExpired)
                    Append(s:", ");
                
                hasExpired = true;
                Append(s:"\cd" + GetPowerIndexAsString(i) + "\cj");
            }
			
            Append(s:".");
        }

        // Something expired
        if (hasExpired)
        {
            Logger::LogDebug(LOGSOURCE, logMessage);
            RecalculatePowers();
        }
    }

    internal void RecalculatePowers() { RecalculatePlayerPowers(PlayerNumber()); }
    internal void RecalculatePlayerPowers(int id)
    {
        // Zombies have a forced default speed of 1.2
        fixed speed = Player::GetPlayerIsZombie(id) ? 1.2 : 1.0;
        fixed jumpZ = 8.0;
        fixed damageFactor = 1.0;
        fixed damageMultiplier = 1.0;
		
        str speedLogMessage = "Setting speed of player " + BCSUtils::PlayerName(id) + ": \cj" + str(speed);
        str jumpLogMessage = "Setting jump of player " + BCSUtils::PlayerName(id) + ": \cj" + str(jumpZ);
        str damageFactorLogMessage = "Setting damage factor of player " + BCSUtils::PlayerName(id) + ": \cj" + str(damageFactor);
        str damageMultiplierLogMessage = "Setting damage multiplier of player " + BCSUtils::PlayerName(id) + ": \cj" + str(damageMultiplier);
        
        bool speedChanged = false,
             jumpZChanged = false,
             damageFactorChanged = false,
             damageMultiplierChanged = false;

        for (int i = 0; i < ZH2Game::PersistingGameContext.PowerCollection.Size; ++i)
        {
            if (!GetPlayerHasPower(id, i))
                continue;
            
            PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[i];
            
            if (context.SpeedModifier != 1.0)
            {
                speedLogMessage += " * " + str(context.SpeedModifier); 
                speed *= context.SpeedModifier;
                speedChanged = true;
            }

            if (context.JumpModifier != 1.0)
            {
                jumpLogMessage += " * " + str(context.JumpModifier); 
                jumpZ *= context.JumpModifier;
                jumpZChanged = true;
            }

            if (context.DamageFactor != 1.0)
            {
                damageFactorLogMessage += " * " + str(context.DamageFactor); 
                damageFactor *= context.DamageFactor;
                damageFactorChanged = true;
            }


            if (context.DamageMultiplier != 1.0)
            {
                damageMultiplierLogMessage += " * " + str(context.DamageMultiplier); 
                damageMultiplier *= context.DamageMultiplier;
                damageMultiplierChanged = true;
            }
        }
		
        if (speedChanged)
        {
            speedLogMessage += ". Total: \cd" + str(speed) + "\cj.";
            Logger::LogDebug(LOGSOURCE, speedLogMessage);
        }

        if (jumpZChanged)
        {
            jumpLogMessage += ". Total: \cd" + str(jumpZ) + "\cj.";
            Logger::LogDebug(LOGSOURCE, jumpLogMessage);
        }

        if (damageFactorChanged)
        {
            damageFactorLogMessage += ". Total: \cd" + str(damageFactor) + "\cj.";
            Logger::LogDebug(LOGSOURCE, damageFactorLogMessage);
        }

        if (damageMultiplierChanged)
        {
            damageMultiplierLogMessage += ". Total: \cd" + str(damageMultiplier) + "\cj.";
            Logger::LogDebug(LOGSOURCE, damageMultiplierLogMessage);
        }

        // Note the values must still be set in case we go back to default values after having it set.
        int tid = Identity::GetTid(id);
		SetActorProperty(tid, APROP_SPEED, speed);
		SetActorProperty(tid, APROP_JUMPZ, jumpZ);
		SetActorProperty(tid, APROP_DAMAGEFACTOR, damageFactor);
		SetActorProperty(tid, APROP_DAMAGEMULTIPLIER, damageFactor);
    }

    internal void ResetPowers()
    {
        ResetPlayerPowers(PlayerNumber());
    }

    internal void ResetPlayerPowers(int id)
    {
        for (int i = 0; i < GetPowerSize(); ++i)
            TakePlayerPower(id, i);
    }
}
