#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Power"

#include "events.acs"

strict namespace Power
{
    internal void Unload()
    {
        // We must unset the overridden powers or they persist to the next map (because it's part of the persisting data).
        // We could check if everything exists, but by default these values should always be 0.0 anyway.
        for (int i = 0; i < GetPowerSize(); ++i)
        {
            for (int j = 0; j < MAX_POWER_TYPES; ++j)
                SetPowerOverrideFactorValue(i, j, 0.0);
        }
    }

    internal int GetPowerSize() { return ZH2Game::PersistingGameContext.PowerCollection.Size; }

    internal void GivePower(int powerIndex) { GivePlayerPower(PlayerNumber(), powerIndex); }
    internal void GivePlayerPower(int id, int powerIndex) { SetPlayerPowerTics(id, powerIndex, BCSUtils::INT_MAX); }

    internal void TakePower(int powerIndex) { TakePlayerPower(PlayerNumber(), powerIndex); }
    internal void TakePlayerPower(int id, int powerIndex, bool recalculatePowers = true)
    {
        BCSUtils::SetActorInventory(Identity::GetTid(id), GetItemName(powerIndex), 0);

        if (recalculatePowers)
            RecalculatePlayerPowers(id);
    }

    internal void AddPowerTics(int powerIndex, int tics) { AddPlayerPowerTics(PlayerNumber(), powerIndex, tics); }
    internal void AddPlayerPowerTics(int id, int powerIndex, int tics, bool recalculatePowers = true)
    {
        int ticsLeft = GetPlayerPowerTicsLeft(id, powerIndex);

        if (recalculatePowers)
            SetPlayerPowerTics(id, powerIndex, ticsLeft + tics);
    }

    internal void SetPowerTics(int powerIndex, int tics) { SetPlayerPowerTics(PlayerNumber(), powerIndex, tics); }
    internal void SetPlayerPowerTics(int id, int powerIndex, int tics)
    {
        // Never set powers when the round ended.
        if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
        {
            Logger::LogDebug(LOGSOURCE, "Ignore power \cd" + GetPowerName(powerIndex) + "\cj change for " + BCSUtils::PlayerName(id) + ". Round is over.");
            return;
        }

        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];

        // Min / Max tics
        // Max tics default to being infinite if not set.
        int maxTics = context.MaxTics == 0 ? BCSUtils::INT_MAX : context.MaxTics;
        tics = BCSUtils::Clamp(tics, 0, context.MaxTics);

        // Ensure we don't underflow or overflow the timestamp in the clamp.
        int timer = Utils::GetSynchronizedTimer();
        tics = BCSUtils::Min(tics, BCSUtils::INT_MAX - timer);

        int timeStamp = timer + tics;
        BCSUtils::SetActorInventory(Identity::GetTid(id), GetItemName(powerIndex), timeStamp);
        RecalculatePlayerPowers(id);

        Logger::LogDebug(LOGSOURCE, "Power updated for player " + BCSUtils::PlayerName(id) + ". Power \cd" + GetPowerName(powerIndex) + "\cj now has \cd" + str(tics) + " \cjtics left.");
    }

    internal int GetPowerTicsLeft(int powerIndex) { return GetPlayerPowerTicsLeft(PlayerNumber(), powerIndex); }
    internal int GetPlayerPowerTicsLeft(int id, int powerIndex)
    {
        int timeStamp = CheckActorInventory(Identity::GetTid(id), GetItemName(powerIndex));
        int tics = BCSUtils::Max(timeStamp - Utils::GetSynchronizedTimer(), 0);
        return tics;
    }

    internal bool GetHasPower(int powerIndex) { return GetPowerTicsLeft(powerIndex) > 0; }
    internal bool GetPlayerHasPower(int id, int powerIndex)
    {
        // Note we don't use `GetPlayerPowerTicsLeft` here as this truly indicates if we have the power set
        // (and also makes it useful for checking for expired powers).
        return CheckActorInventory(Identity::GetTid(id), GetItemName(powerIndex)) > 0;
    }

    internal str GetPowerHudGraphic(int powerIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        return context.HudGraphic;
    }

    internal str GetPowerName(int powerIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        return context.Name;
    }

    internal int GetPowerMaxTics(int powerIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        return context.MaxTics;
    }

    internal fixed GetPowerDefaultFactorValue(int powerIndex, int factorIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return 0.0;

        return context.DefaultFactors[factorIndex].Factor;
    }

    internal void SetPowerDefaultFactorValue(int powerIndex, int factorIndex, fixed factor)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return;

        context.DefaultFactors[factorIndex].Factor = factor;
    }

    internal bool GetPowerDefaultFactorDefined(int powerIndex, int factorIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return false;

        return context.DefaultFactors[factorIndex].Defined;
    }

    internal void SetPowerDefaultFactorDefined(int powerIndex, int factorIndex, bool defined)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return;

        context.DefaultFactors[factorIndex].Defined = defined;
    }

    internal fixed GetPowerOverrideFactorValue(int powerIndex, int factorIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return 0.0;

        return context.OverrideFactors[factorIndex].Factor;
    }

    internal void SetPowerOverrideFactorValue(int powerIndex, int factorIndex, fixed factor)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return;

        context.OverrideFactors[factorIndex].Factor = factor;
    }

    internal bool GetPowerOverrideFactorDefined(int powerIndex, int factorIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return false;

        return context.OverrideFactors[factorIndex].Defined;
    }

    internal void SetPowerOverrideFactorDefined(int powerIndex, int factorIndex, bool defined)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return;

        context.OverrideFactors[factorIndex].Defined = defined;
    }

    // No setter for this one. Use the override one instead.
    internal fixed GetPowerFactorValue(int powerIndex, int factorIndex)
    {
        PowerContextT global:PERSISTINGGAMECONTEXTINDEX& context = ZH2Game::PersistingGameContext.PowerCollection.Collection[powerIndex];
        if (factorIndex < 0 || factorIndex >= MAX_POWER_TYPES)
            return 0.0;

        // If we have overridden the factor, return that one instead.
        return context.OverrideFactors[factorIndex].Defined
            ? context.OverrideFactors[factorIndex].Factor
            : context.DefaultFactors[factorIndex].Factor;
    }

    internal str GetItemName(int index)
    {
        return BCSUtils::StrReplace(POWER_ACTOR_BASE, "{0}", str(index));
    }

    internal str GetPowerFactorName(int index)
    {
        static str collection[] = {
            "Speed", "Jump", "Damage Factor", "Damage Multiplier"
        };

        // Should not happen. The index should always point to a known type.
        if (index < 0 || index >= lengthof(collection))
            return "Unknown (" + str(index) + ")";

        return collection[index];
    }

    internal int PowerFactorToProperty(int index)
    {
        static int collection[] = {
            APROP_SPEED, APROP_JUMPZ, APROP_DAMAGEFACTOR, APROP_DAMAGEMULTIPLIER
        };

        // Should not happen. The index should always point to a known type.
        if (index < 0 || index >= lengthof(collection))
            return 0;

        return collection[index];
    }
}

#undef LOGSOURCE
