#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Power
{
    #define MAX_POWERS 20
    #define MAX_POWER_TYPES 4

    struct PowerCollectionContextT
    {
        // Set to `true` if we defined the collection.
        bool Defined;

        PowerContextT Collection[MAX_POWERS];
        int Size;
    };

    struct PowerContextT
    {
        str Name;
        str HudGraphic;
        int MaxTics;

        // Note: The power type is implicitly defined using the index.
        PowerFactorContextT DefaultFactors[MAX_POWER_TYPES];
        PowerFactorContextT OverrideFactors[MAX_POWER_TYPES];
    };

    struct PowerFactorContextT
    {
        bool Defined;
        fixed Factor;
    };

    internal enum PowerFactorTypeT : int
    {
        POWERTYPE_SPEED,
        POWERTYPE_JUMP,
        POWERTYPE_DAMAGEFACTOR,
        POWERTYPE_DAMAGEMULTIPLIER,
    };

    enum KnownPowerTypeT : int
    {
        POWERFIREBURNING,
        POWERACIDBURNING,
        POWERSPRINTING,
        POWERPANICKING,
        POWERCAFFEINE,

        POWERZOMBIEPROTECT,
        POWERHUMANIMMUNITY,

        POWERREWARDHUMANSPEED,
        POWERREWARDHUMANWEAPONUPGRADE,
        POWERREWARDZOMBIESPEED,
        POWERREWARDZOMBIEJUMP,
        POWERREWARDZOMBIEVULNERABILITY,
    };
}