#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace RoundTimer
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE , "Setting survival gamemode profile for round timers.");

        // TODO: play timer should be scalable.
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERPREGAMECOUNTDOWN, 10, 30, RoundTimer::TIMERDRAWDECIMALS, "Game is starting in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERCOUNTDOWN, 30, 30, RoundTimer::TIMERDRAWDECIMALS, "Picking a zombie in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERPLAYING, 60, 180, RoundTimer::TIMERDOCOUNTDOWN, "Time left");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERENDING, 10, 10, RoundTimer::TIMERDRAWDECIMALS);
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTING, 20, 20, RoundTimer::TIMERDRAWDECIMALS); // TODO: RoundTimer::TIMERHIDDEN
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTED, 5, 5, RoundTimer::TIMERDRAWDECIMALS, "Moving to next map...");
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE , "Setting escape gamemode profile for round timers.");

        RoundTimer::DefineKnownTimer(RoundTimer::TIMERPREGAMECOUNTDOWN, 10, 30, RoundTimer::TIMERDRAWDECIMALS, "Game is starting in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERCOUNTDOWN, 10, 30, RoundTimer::TIMERDRAWDECIMALS, "Picking a zombie in");
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERENDING, 10, 10, RoundTimer::TIMERDRAWDECIMALS);
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTING, 20, 20, RoundTimer::TIMERDRAWDECIMALS); // TODO: RoundTimer::TIMERHIDDEN
        RoundTimer::DefineKnownTimer(RoundTimer::TIMERVOTED, 5, 5, RoundTimer::TIMERDRAWDECIMALS, "Moving to next map...");
    }
}