#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawClientSeparateHudFire(HudFireTypeT type = FIRETYPENORMAL)
    {
        if (!ACS_NamedExecuteAlways("zh2_internal_hud_drawfire", 0, type)) 
			Logger::LogError(LogSource, "Failed to invoke zh2_internal_hud_drawfire.");
    }

    script "zh2_internal_hud_drawfire" (raw type) clientside
	{
		str sprite = type == FIRETYPENORMAL ? HUD_FIRE_GRAPHIC : HUD_INFECTFIRE_GRAPHIC;
		int x = Random(0, 160);
		int y = 80 - Random(15, 30);

		fixed alpha = 0.1;
        for (int i = 0; i < 18; ++i)
        {
            BCSUtils::HudResetState();
            BCSUtils::HudSetVirtualSize(80.0, 60.0);
            BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
            BCSUtils::HudSetShowOnFullAutomap(false);

            BCSUtils::HudSetAlpha(alpha);
            BCSUtils::HudSetPoint(fixed(x), fixed(y));
            BCSUtils::HudDrawImage(0, sprite + str(i / 2));

            y -= 1;
			alpha += 0.04;
            
            Delay(const: 1);
        }
	}

    internal void DrawClientSeparateHudFireBlur()
    {
        if (Timer() % 10 != 0)
            return;

        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(200.0, 150.0);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlpha(0.5);
        BCSUtils::HudSetStayTime(0.2);
        BCSUtils::HudSetAppearTime(0.5);
        BCSUtils::HudSetDisappearTime(0.5);
        Utils::ScaleToScreen();
        
        fixed x = 100.0,
              y = BCSUtils::HudBottom() / 2.0;
              
		BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawImage(0, BLUR_ORANGE_GRAPHIC);
	}
}