#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Events
{
    internal void ReceivePlayerLeftRound(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        SetReceiveData(0, id);
    }

    internal void ReceivePlayerDied(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int killedId = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int killerId = Packet::Packet_Rval;

        SetReceiveData(0, killedId);
        SetReceiveData(0, killerId);
    }

    internal void ReceivePlayerScratched(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int attackedId = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int attackerId = Packet::Packet_Rval;

        SetReceiveData(0, attackedId);
        SetReceiveData(0, attackerId);
    }

    internal void ReceivePlayerCured(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        SetReceiveData(0, id);
    }

    internal void ReceivePlayerInfected(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        SetReceiveData(0, id);
    }

    internal void ReceivePlayerSpecieChanged(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int specieInt = Packet::Packet_Rval;

        SetReceiveData(0, id);
        SetReceiveData(1, specieInt);
    }

    internal void ReceiveResistStarted(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveResistElapsed(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveResistStopped(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveRoundSwitched(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int prevIndex = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int newIndex = Packet::Packet_Rval;

        SetReceiveData(0, prevIndex);
        SetReceiveData(0, newIndex);
    }

    internal void ReceiveTimerStarted(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveTimerStopped(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveTimerPaused(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveTimerResumed(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveTimerElapsed(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    internal void ReceiveTimerSwitched(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int prevIndex = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int newIndex = Packet::Packet_Rval;

        SetReceiveData(0, prevIndex);
        SetReceiveData(0, newIndex);
    }
}