#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    void ReceiveInitialsChosen(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int count = Packet::Packet_Rval;
        SetReceiveData(0, count);

        int index = 1;
        while (count--)
        {
            packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
            SetReceiveData(index++, Packet::Packet_Rval);
        }
    }

    void ReceivePlayerLeftRound(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        SetReceiveData(0, id);
    }

    void ReceivePlayerDied(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int killedId = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int killerId = Packet::Packet_Rval;

        SetReceiveData(0, killedId);
        SetReceiveData(1, killerId);
    }

    void ReceivePlayerScratched(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int attackedId = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int attackerId = Packet::Packet_Rval;

        SetReceiveData(0, attackedId);
        SetReceiveData(1, attackerId);
    }

    void ReceivePlayerCured(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        SetReceiveData(0, id);
    }

    void ReceivePlayerInfected(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        SetReceiveData(0, id);
    }

    void ReceivePlayerSpecieChanged(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int specieInt = Packet::Packet_Rval;

        SetReceiveData(0, id);
        SetReceiveData(1, specieInt);
    }

    void ReceivePlayerSafe(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int id = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int safe = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int firstTime = Packet::Packet_Rval;

        SetReceiveData(0, id);
        SetReceiveData(1, safe);
        SetReceiveData(2, firstTime);
    }

    void ReceiveResistStarted(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveResistElapsed(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveResistStopped(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveRoundSwitched(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int prevIndex = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int newIndex = Packet::Packet_Rval;

        SetReceiveData(0, prevIndex);
        SetReceiveData(1, newIndex);
    }

    void ReceiveTimerStarted(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveTimerStopped(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveTimerPaused(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveTimerResumed(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveTimerElapsed(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int index = Packet::Packet_Rval;

        SetReceiveData(0, index);
    }

    void ReceiveTimerSwitched(str packet)
    {
        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int prevIndex = Packet::Packet_Rval;

        packet = Packet::Packet_Read(packet, Packet::PACKET_WORD);
        int newIndex = Packet::Packet_Rval;

        SetReceiveData(0, prevIndex);
        SetReceiveData(1, newIndex);
    }
}