#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Events
{
    internal void ReceivePlayerLeftRound(str packet)
    {
    }

    internal void ReceivePlayerDied(str packet)
    {
    }

    internal void ReceivePlayerScratched(str packet)
    {
    }

    internal void ReceivePlayerCured(str packet)
    {
    }

    internal void ReceivePlayerInfected(str packet)
    {
    }

    internal void ReceivePlayerSpecieChanged(str packet)
    {
    }

    internal void ReceiveResistStarted(str packet)
    {
    }

    internal void ReceiveResistElapsed(str packet)
    {
    }

    internal void ReceiveResistStopped(str packet)
    {
    }

    internal void ReceiveRoundSwitched(str packet)
    {
    }

    internal void ReceiveTimerStarted(str packet)
    {
    }

    internal void ReceiveTimerStopped(str packet)
    {
    }

    internal void ReceiveTimerPaused(str packet)
    {
    }

    internal void ReceiveTimerResumed(str packet)
    {
    }

    internal void ReceiveTimerElapsed(str packet)
    {
    }

    internal void ReceiveTimerSwitched(str packet)
    {
    }
}