#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Event
{
    internal void SendInitialsChosen(int chosenCount)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTINITIALSCHOSEN);
        packet = Packet::Packet_Append(packet, chosenCount, Packet::PACKET_WORD);

        for(int i = 0; i < BCSUTILS::MAX_PLAYERS; ++i)
        {
            if (Player::GetPlayerInitialZombie(i))
                packet = Packet::Packet_Append(packet, i, Packet::PACKET_WORD);
        }

        EventBus::CallEvent(packet);
    }

    internal void SendPlayerLeftRound(int id)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERLEFTROUND);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerDied(int id, ZH2Game::PlayerDeathTypeT type)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERDIED);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, type, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerKilledByPlayer(int killedId, int killerId, int itemIndex, bool addFireEffect, bool addAcidEffect)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERKILLEDBYPLAYER);
        packet = Packet::Packet_Append(packet, killedId, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, killerId, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, itemIndex, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, addFireEffect, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, addAcidEffect, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerKilledByMonster(int id, str monsterName)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERKILLEDBYMONSTER);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        packet = Packet::Packet_AppendStr(packet, monsterName);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerPreScratched(int attackedId, int attackerId)
    {
        str packet = Packet::Packet_New();

        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERPRESCRATCHED);
        packet = Packet::Packet_Append(packet, attackedId, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, attackerId, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerScratched(int attackedId, int attackerId)
    {
        str packet = Packet::Packet_New();

        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERSCRATCHED);
        packet = Packet::Packet_Append(packet, attackedId, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, attackerId, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerCured(int id, bool transformed, Game::CureSourceT source)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERCURED);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, (int)transformed, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, source, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerInfected(int id, Game::InfectTypeT type, Game::InfectSourceT source)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERINFECTED);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, type, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, source, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerSpecieChanged(int id, Player::PlayerSpecieT specie)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERSPECIECHANGED);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, specie, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPlayerSafe(int id, bool safe, bool firstTime)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPLAYERSAFE);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, (int)safe, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, (int)firstTime, Packet::PACKET_WORD);

        EventBus::CallEvent(packet);
    }

    internal void SendResistStarted(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTRESISTSTARTED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendResistElapsed(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTRESISTELAPSED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendResistStopped(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTRESISTSTOPPED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendRoundSwitched(int prevIndex, int newIndex)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTROUNDSWITCHED);
        packet = Packet::Packet_Append(packet, prevIndex, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, newIndex, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendTimerStarted(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTTIMERSTARTED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendTimerStopped(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTTIMERSTOPPED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendTimerPaused(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTTIMERPAUSED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendTimerResumed(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTTIMERRESUMED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendTimerElapsed(int index)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTTIMERELAPSED);
        packet = Packet::Packet_Append(packet, index, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendTimerSwitched(int prevIndex, int newIndex)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTTIMERSWITCHED);
        packet = Packet::Packet_Append(packet, prevIndex, Packet::PACKET_WORD);
        packet = Packet::Packet_Append(packet, newIndex, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }

    internal void SendPowerExpired(int id)
    {
        str packet = Packet::Packet_New();
        packet = Packet::Packet_AppendStr(packet, EVENTPOWEREXPIRED);
        packet = Packet::Packet_Append(packet, id, Packet::PACKET_WORD);
        EventBus::CallEvent(packet);
    }
}