#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace TeleportUtil
{
    // This defines how many tries we do on a spot before we instead make the actor unsolid.
    #define TELEPORT_TRYCOUNT 10

    #define TELEPORT_TEMPSPOTTID 1800

    enum TeleportFlagsT : int
	{
        // Spawn teleport for on the source, target or both.
		TELEPORT_FOGSOURCE = 1 << 0,
		TELEPORT_FOGTARGET = 1 << 1,
		TELEPORT_FOGBOTH = TELEPORT_FOGSOURCE | TELEPORT_FOGTARGET,

        // Keep the velocity that existed on the player before teleporting.
		TELEPORT_KEEPVELOCITY = 1 << 2,

        // Use the angle used by the target spot.
		TELEPORT_USETARGETANGLE = 1 << 3,

        // Keep the height relative to the floor.
		TELEPORT_KEEPHEIGHT = 1 << 4,
	};

    extern void TeleportAreaBetween(int targetTidMin, int targetTidMax, int area = 90, int flags = 0);
    extern void PlayerTeleportAreaBetween(int sourceId, int targetTidMin, int targetTidMax, int area = 90, int flags = 0);

    extern void TeleportArea(int targetTid, int area = 90, int flags = 0);
    extern void PlayerTeleportArea(int sourceId, int targetTid, int area = 90, int flags = 0);
}