#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "TeleportUtil"

strict namespace TeleportUtil
{
    void TeleportAreaBetween(int targetTidMin, int targetTidMax, int area = 90, int flags = 0)
    {
        // Since thruactors requires a valid player we only support players for now.
        // This is because of the tic system that runs only on players.
        int sourceId = PlayerNumber();
        if (sourceId == -1)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + " only supports players for now.");
            return;
        }

        PlayerTeleportAreaBetween(sourceId, targetTidMin, targetTidMax, area, flags);
    }

    // Note: uses PlayerTeleportArea with a set of tids.
    void PlayerTeleportAreaBetween(int sourceId, int targetTidMin, int targetTidMax, int area = 90, int flags = 0)
    {
        VALIDATE_ID_VALID_FUNCTION(sourceId);

        if (targetTidMin >= targetTidMax)
        {
            targetTidMin = targetTidMax;
            Logger::LogWarning(LOGSOURCE, __FUNCTION__ + ": targetTidMin should be lower than targetTidMax");
        }

        int targetTid = targetTidMin;
        while(targetTidMin <= targetTidMax)
        {
            if (!TryTeleportPlayerArea(sourceId, targetTidMin, area, flags))
            {
                targetTidMin++;
                continue;
            }

            return;
        }

        TeleportUnsolidActor(sourceId, targetTidMin, flags);
    }

    void TeleportArea(int targetTid, int area = 90, int flags = 0)
    {
        // Since thruactors requires a valid player we only support players for now.
        // This is because of the tic system that runs only on players.
        int sourceId = PlayerNumber();
        if (sourceId == -1)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + " only supports players for now.");
            return;
        }

        PlayerTeleportArea(sourceId, targetTid, area, flags);
    }

    void PlayerTeleportArea(int sourceId, int targetTid, int area = 90, int flags = 0)
    {
        VALIDATE_ID_VALID_FUNCTION(sourceId);

        // If false, we failed to get a position without telefragging. So instead make the player unsolid.
        if (!TryTeleportPlayerArea(sourceId, targetTid, area, flags))
            TeleportUnsolidActor(sourceId, targetTid, flags);
    }

    internal bool TryTeleportPlayerArea(int sourceId, int targetTid, int area, int flags)
    {
        int sourceTid = Identity::GetTid(sourceId);

		fixed baseX = GetActorX(targetTID),
			  baseY = GetActorY(targetTID),
			  baseZ = GetActorZ(targetTID);

		fixed x = baseX,
			  y = baseY,
			  z = baseZ;

        fixed height = GetActorProperty(sourceTid, APROP_HEIGHT),
              radius = GetActorProperty(sourceTid, APROP_RADIUS),
              angle = GetActorAngle(targetTid);

        int tries = TELEPORT_TRYCOUNT;
        while (tries--)
        {
            // No space, pick a new position within the given area and try again.
            if (!SpaceUtil::GetXYZHasSpace(x, y, z, height, radius))
            {
				x = baseX + fixed(Random(-area, area));
				y = baseY + fixed(Random(-area, area));
				z = baseZ + fixed(Random(0, area));
                continue;
            }

            // Found space!
            TeleportActorToXYZ(sourceTid, x, y, z, angle, flags);
            return true;
        }

        return false;
    }

    internal void TeleportUnsolidActor(int sourceId, int targetTid, int flags)
    {
        int sourceTid = Identity::GetTid(sourceId);
        fixed x = GetActorX(targetTID),
			  y = GetActorY(targetTID),
			  z = GetActorZ(targetTID);

        fixed angle = GetActorAngle(targetTid);

        SpaceUtil::SetPlayerThruActors(sourceId, true);
        TeleportActorToXYZ(sourceTid, x, y, z, angle, flags);
        SpaceUtil::SetPlayerThruActors(sourceId, false);
    }

    internal void TeleportActorToXYZ(int sourceTid, fixed x, fixed y, fixed z, fixed angle, int flags)
    {
        str packet = Packet::New();
        packet = Packet::Append(packet, sourceTid);
        packet = Packet::Append(packet, x);
        packet = Packet::Append(packet, y);
        packet = Packet::Append(packet, z);
        packet = Packet::Append(packet, angle);
        packet = Packet::Append(packet, flags);

        ACS_NamedExecuteWithResult("zh2_internal_teleportxyz", packet);
    }

    // Note we don't use SetActorPosition here since it doesn't guarantee a teleport.
    // Generally this will never fail to pick a safe position. Should it do so anyway then at least it still teleports.
    script "zh2_internal_teleportxyz"(raw packet)
    {
        packet = Packet::Read(packet);
        int sourceTid = Packet::Value;

        packet = Packet::Read(packet);
        fixed x = Packet::Value;

        packet = Packet::Read(packet);
        fixed y = Packet::Value;

        packet = Packet::Read(packet);
        fixed z = Packet::Value;

        packet = Packet::Read(packet);
        fixed angle = Packet::Value;

        packet = Packet::Read(packet);
        int flags = Packet::Value;

        fixed sourceX = GetActorX(sourceTid),
              sourceY = GetActorY(sourceTid),
              sourceZ = GetActorZ(sourceTid);

        if (!SetActivator(sourceTid))
        {
            Logger::LogError(LOGSOURCE, "Failed to set source tid " + str(sourceTid) + " as activator.");
            terminate;
        }

        bool fogSource = (flags & TELEPORT_FOGSOURCE) == TELEPORT_FOGSOURCE,
             fogTarget = (flags & TELEPORT_FOGTARGET) == TELEPORT_FOGTARGET,
             keepVelocity = (flags & TELEPORT_KEEPVELOCITY) == TELEPORT_KEEPVELOCITY,
             useTargetAngle = (flags & TELEPORT_USETARGETANGLE) == TELEPORT_USETARGETANGLE,
             keepHeight = (flags & TELEPORT_KEEPHEIGHT) == TELEPORT_KEEPHEIGHT;

        if (fogSource)
            SpawnForced("TeleportFog", sourceX, sourceY, sourceZ, 0, 0);

        SpawnForced("MapSpot", x, y, z, TELEPORT_TEMPSPOTTID, 0);
        Teleport_NoFog(TELEPORT_TEMPSPOTTID, 0, 0, (int)keepHeight);
        Thing_Remove(TELEPORT_TEMPSPOTTID);

        if (fogTarget)
            SpawnForced("TeleportFog", x, y, z, 0, 0);

        if (!keepVelocity)
            SetActorVelocity(sourceTid, 0.0, 0.0, 0.0, false, false);

        if (useTargetAngle)
            SetActorAngle(sourceTid, angle);
    }
}

#undef LOGSOURCE
