#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Resist"

#include "scripthandler.acs"
#include "extern.acs"
#include "sync.acs"

// Note:
// - Resist ending tic will be -1 for inactive resists. If not, the resist is active.

strict namespace Resist
{
    internal void InitializeClient()
    {
        Logger::LogDebug(LOGSOURCE, "Initializing clientside.");

        EventBus::AddCallbackByScriptName(EVENTDATASYNCED, "zh2_internal_event_resistdatasynced");
    }

    // Tic checks for any expired resists and stops them.
    // Additionally, an event will be called.
    internal void TicServer()
    {
        VALIDATE_IS_SERVERSIDE_FUNCTION();

        ResistT[] module& resists = ZH2Game::GameContext.MapDetails.Resists;
        for (int index = 0; index < lengthof(resists); ++index)
        {
            if (!IsDefined(index))
                continue;

            ResistT module& resist = resists[index];

            ResistRunStateT state = GetRunState(index);
            if (state == STATEREADYTORUN)
            {
                SetRunState(index, STATERUNNING);
                Event::SendResistStarted(index);
                Sync::SyncResists();

                Logger::LogDebug(LOGSOURCE, "Resist " + str(index) + " has started.");
            }

            else if (state == STATEREADYTOELAPSE)
            {
                SetRunState(index, STATEENDED);
                Event::SendResistElapsed(index);
                Sync::SyncResists();

                Logger::LogDebug(LOGSOURCE, "Resist " + str(index) + " has elapsed.");
            }

            else if (state == STATEREADYTOSTOP)
            {
                SetRunState(index, STATEENDED);
                Event::SendResistStopped(index);
                Sync::SyncResists();

                Logger::LogDebug(LOGSOURCE, "Resist " + str(index) + " has stopped.");
            }

            else if (state == STATERUNNING && GetTicsDifference(index) <= 0)
            {
                if (resist.InitialState.PostResistScript != (raw)0)
                {
                    StartPostResistScript(index);
                    return;
                }

                SetResistReadyToElapse(index);
            }
        }
    }

    internal void DefineNewByIndex(
        int index,
        int length,
        str topReasonLabel = (raw)0,
        str timeReasonLabel = (raw)0,
        str preResistScript = (raw)0,
        str postResistScript = (raw)0,
        int flags = FLAG_NONE)
    {
        if (index < 0 || index >= MAX_RESISTS)
        {
            Logger::LogError(LOGSOURCE, "Resist index " + str(index) + " is invalid. Index must be between 0-" + str(MAX_RESISTS - 1) + ".");
            return;
        }

        ResistT module& resist = GetRefByindex(index);
        resist.InitialState.Length = length;
        resist.InitialState.TopReasonLabel = topReasonLabel;
        resist.InitialState.TimeReasonLabel = timeReasonLabel;
        resist.InitialState.PreResistScript = preResistScript;
        resist.InitialState.PostResistScript = postResistScript;
        resist.InitialState.Flags = flags;
        resist.EndingTic = -1;
        resist.Defined = true;

        Logger::LogDebug(LOGSOURCE, "Created new resist at index \cd" + str(index) + "\cj. Length: \cd" + str(length) + "\cj. Top reason: \cd" + topReasonLabel + "\cj. Time reason: \cd" + timeReasonLabel + ".");
    }

    internal ResistT module& GetRefByindex(int index) { return ZH2Game::GameContext.MapDetails.Resists[index]; }

    // Called by the client, which is used to determine some things about the resist that do not change after it was made.
    internal void InitializeResistClientside(int index)
    {
        ResistT module& resist = GetRefByindex(index);

        // Explicit check for `(raw)0` as timereason meaning nothing was set at all.
        // Default to "resist for %t seconds" then.
        if (resist.InitialState.TimeReasonLabel == (raw)0)
            resist.InitialState.TimeReasonLabel = "Resist for " + RESIST_TIME_TOKEN + " second" + RESIST_PLURAL_TOKEN;

        // Determine if the top reason / time reason has a time token.
        // If yes, also check if it's colored (if not, then the hud will add it).
        str topReason = resist.InitialState.TopReasonLabel;
        if (topReason != (raw)0 && topReason != "")
        {
            resist.InitialState.TopReasonTimeTokenIndex = BCSUtils::StrFind(topReason, RESIST_TIME_TOKEN);
            if (resist.InitialState.TopReasonTimeTokenIndex > 3)
            {
                str before = StrMid(topReason, resist.InitialState.TopReasonTimeTokenIndex - 2, 2);
                if (before == "\c" && BCSUtils::IsAlpha(topReason[resist.InitialState.TopReasonTimeTokenIndex - 1]))
                    resist.InitialState.TopReasonHasColoredTimeToken = true;
            }
        }

        str timeReason = resist.InitialState.TimeReasonLabel;
        if (timeReason != (raw)0 && timeReason != "")
        {
            resist.InitialState.TimeReasonTimeTokenIndex = BCSUtils::StrFind(timeReason, RESIST_TIME_TOKEN);
            if (resist.InitialState.TimeReasonTimeTokenIndex > 3)
            {
                str before = StrMid(timeReason, resist.InitialState.TimeReasonTimeTokenIndex - 2, 2);
                if (before == "\c" && BCSUtils::IsAlpha(timeReason[resist.InitialState.TimeReasonTimeTokenIndex - 1]))
                    resist.InitialState.TimeReasonHasColoredTimeToken = true;
            }
        }

        str topReasonLog = topReason != (raw)0 && topReason != "" ? topReason : "N/A";
        str timeReasonLog = timeReason != (raw)0 && timeReason != "" ? timeReason : "N/A";
        Logger::LogDebug(LOGSOURCE, "Initialized new resist clientside at index \cd" + str(index) + "\cj. Time reason: " + timeReasonLog + ". Top reason: " + topReasonLog + ". Top reason has time token: \cd" + (resist.InitialState.TopReasonTimeTokenIndex != -1 ? "yes" : "no") + "\cj. Top reason time token has color: \cd" + (resist.InitialState.TopReasonHasColoredTimeToken ? "yes" : "no") + "\cj. Time reason has time token: \cd" + (resist.InitialState.TimeReasonTimeTokenIndex != -1 ? "yes" : "no") + "\cj. Time reason time token has color: \cd" + (resist.InitialState.TimeReasonHasColoredTimeToken ? "yes" : "no") + "\cj.");
    }

    internal int GetMaximumTics(int index)
    {
        return GetRefByindex(index).InitialState.Length * 35;
    }

    internal bool IsDefined(int index)
    {
        return GetRefByindex(index).Defined;
    }

    internal bool IsActive(int index)
    {
        ResistRunStateT state = GetRunState(index);
        return state != STATENONE && state != STATEENDED;
    }

    internal int GetTicsLeft(int index)
    {
        int timeLeft = BCSUtils::Max(GetTicsDifference(index), 0);
        return timeLeft;
    }

    internal int GetTicsDifference(int index)
    {
        return GetRefByindex(index).EndingTic - Utils::GetSynchronizedTimer();
    }

    internal void StartResist(int index)
    {
        ResistRunStateT state = GetRunState(index);
        if (state != STATENONE)
            return;

        ResistT module& resist = GetRefByindex(index);
        if (resist.InitialState.PreResistScript != (raw)0)
        {
            StartPreResistScript(index);
            return;
        }

        SetResistReadyToRun(index);
    }

    internal void SetResistReadyToRun(int index)
    {
        ResistT module& resist = GetRefByindex(index);

        // The ending tic of a resist is set to an interval of 35 to keep in sync with other resists.
        // This is mostly so the visualization of them remains equal between other resists.
        int endingTic = Utils::GetSynchronizedTimer() + resist.InitialState.Length * 35;
        resist.EndingTic = endingTic + (35 - (endingTic % 35));

        Logger::LogDebug(LOGSOURCE, "Resist is ready to run. True length: \cd" + str(resist.EndingTic - Utils::GetSynchronizedTimer()) + "\cj tics.");
        SetRunState(index, STATEREADYTORUN);
    }

    internal void SetResistReadyToElapse(int index)
    {
        ResistT module& resist = GetRefByindex(index);

        Logger::LogDebug(LOGSOURCE, "Resist is ready to elapse.");
        SetRunState(index, STATEREADYTOELAPSE);
    }

    internal void SetResistReadyToStop(int index)
    {
        GetRefByindex(index).EndingTic = -1;

        Logger::LogDebug(LOGSOURCE, "Resist is ready to stop.");
        SetRunState(index, STATEREADYTOSTOP);
    }

    internal void ElapseAllResists()
    {
        ResistT[] module& resists = ZH2Game::GameContext.MapDetails.Resists;
        for (int index = 0; index < lengthof(resists); ++index)
        {
            if (!IsDefined(index))
                continue;

            if (!IsActive(index))
                continue;

            SetRunState(index, STATEREADYTOELAPSE);
        }
    }

    internal void StopAllResists()
    {
        ResistT[] module& resists = ZH2Game::GameContext.MapDetails.Resists;
        for (int index = 0; index < lengthof(resists); ++index)
        {
            if (!IsDefined(index))
                continue;

            if (!IsActive(index))
                continue;

            SetRunState(index, STATEREADYTOSTOP);
        }
    }

    internal void SetRunState(int index, ResistRunStateT state)
    {
        GetRefByindex(index).RunState = state;
    }

    internal ResistRunStateT GetRunState(int index)
    {
        return GetRefByindex(index).RunState;
    }

    internal void StartPreResistScript(int index)
    {
        ResistT module& resist = GetRefByindex(index);

        SetRunState(index, STATEPRESCRIPT);
        ACS_NamedExecuteWithResult(RESIST_SCRIPT_HANDLER_NAME, index, true, resist.InitialState.PreResistScript);
    }

    internal void StartPostResistScript(int index)
    {
        ResistT module& resist = GetRefByindex(index);

        SetRunState(index, STATEPOSTSCRIPT);
        ACS_NamedExecuteWithResult(RESIST_SCRIPT_HANDLER_NAME, index, false, resist.InitialState.PostResistScript);
    }

    internal void SetFlags(int index, int flags)
    {
        GetRefByindex(index).InitialState.Flags = flags;
    }

    internal int GetFlags(int index)
    {
        return GetRefByindex(index).InitialState.Flags;
    }

    internal bool HasFlag(int index, ResistFlagT flag)
    {
        return (GetFlags(index) & flag) != 0;
    }

    internal bool GetHideTopReason(int index)
    {
        return HasFlag(index, FLAG_HIDE_TOP_REASON);
    }

    internal bool GetHideTimeReason(int index)
    {
        return HasFlag(index, FLAG_HIDE_TIME_REASON);
    }

    internal bool GetNoFade(int index)
    {
        return HasFlag(index, FLAG_NO_FADE);
    }

    internal ResistRunStateT GetRunStateTypeByIndex(int stateIndex)
    {
        static ResistRunStateT collection[] = { STATENONE, STATEPRESCRIPT, STATEREADYTORUN, STATERUNNING, STATEPOSTSCRIPT, STATEREADYTOELAPSE, STATEENDED };

        // No known round state.
        if (stateIndex < STATENONE && stateIndex > STATEENDED)
            return STATENONE;

        return collection[stateIndex];
    }
}

#undef LOGSOURCE