#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Resist
{
    // Hardcoded limit on resists to avoid too many of them.
    // Also, the actor based sync approach requires preset cvars which must be extended to match this count.
    // In the future I will support the ability to allocate these to allow for more, but this requires an extra library.
    #define MAX_RESISTS 20

    #define RESIST_SCRIPT_HANDLER_NAME "zh2_internal_resist_script_handler"
    #define RESIST_SCRIPT_HANDLER_AWAITER_NAME "zh2_internal_resist_script_handler_awaiter"

    internal struct ResistInitialStateT
    {
        str TopReasonLabel, TimeReasonLabel;
        int Length;

        // Serverside, exclusive scripts for the resist which will be invoked before and after the script runs.
        str PreResistScript, PostResistScript;

        // Everything below is intialized clientside and helps with setting up the resist logic.
        bool TopReasonHasColoredTimeToken;
        bool TimeReasonHasColoredTimeToken;
        int TopReasonTimeTokenIndex;
        int TimeReasonTimeTokenIndex;
    };

    internal struct ResistT
    {
        ResistInitialStateT InitialState;
        int EndingTic;
        ResistRunStateT RunState;

        // Set to `true` if we defined the resist index.
        // Clientside this is also checked to ensure we have a valid resist.
        bool Defined;
    };

    enum ResistRunStateT : int
    {
        STATENONE,
        STATEPRESCRIPT,
        STATEREADYTORUN,
        STATERUNNING,
        STATEPOSTSCRIPT,
        STATEREADYTOEND,
        STATEENDED,
    };

    extern int CreateResist(
        int length,
        str topReasonLabel = (raw)0,
        str timeReasonLabel = (raw)0,
        str preResistScript = (raw)0,
        str postResistScript = (raw)0);

    extern void CreateResistByIndex(
        int index,
        int length,
        str topReasonLabel = (raw)0,
        str timeReasonLabel = (raw)0,
        str preResistScript = (raw)0,
        str postResistScript = (raw)0);

    extern int StartResistByIndex(int index);
}