#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// The script below is used to handle the pre and post scripts that must invoke before and after a resist.

strict namespace Resist
{
    script RESIST_SCRIPT_HANDLER_NAME (raw index, raw isPreScript, raw scriptName)
    {
        if (!CheckScript(scriptName, true))
        {
            Logger::LogError(LOGSOURCE, RESIST_SCRIPT_HANDLER_NAME + " failed to call " + (isPreScript ? "pre" : "post") + "-script " + (str)scriptName + " of resist " + str((int)index) + ". Script not found.");
            return;
        }

        ACS_NamedExecute(scriptName, 0);
        NamedScriptWait(scriptName);

        if (isPreScript)
            SetResistReadyToRun(index);
        else
            SetResistReadyToEnd(index);
    }
}