#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// The scripts below is used to handle the pre and post scripts that must invoke before and after a resist.

strict namespace Resist
{
    script RESIST_SCRIPT_HANDLER_NAME (raw index, raw isPreScript, raw scriptName)
    {
        ACS_NamedExecute(scriptName, 0);
        NamedScriptWait(scriptName);

        if (isPreScript)
            SetScriptReadyToRun(index);
        else
            SetScriptReadyToEnd(index);
    }
}