#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawZombieTeleportTime(fixed x, fixed y)
    {
        if (!Game::GetIsZombieTeleporting())
            return;
        
        int id = HUDID_ZTELE;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetCenterText(true);

        BCSUtils::HudSetDisappearTime(0.5);

        int tics = Game::GetZombieTeleportTics();
        str formattedTics = Utils::FormatTics(tics, true);

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawText(--id, "Teleporting in " + formattedTics);
        DebugDraw();

        BCSUtils::HudSetPoint(x, y + 8.0);
        BCSUtils::HudDrawText(--id, "Do not move");
        DebugDraw();
    }
}