#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Shuffle
{
    script "zh2_internal_shuffle_compareinitials" (int left, int _)
    {
        int id = _context.Buffer[left];
        bool previously = Player::GetPlayerInitialZombiePreviously(id);
        bool lastMap = Player::GetPlayerInitialZombieLastMap(id);

        SetResultValue(
            int(!previously && !lastMap));
    }

    internal bool ShuffleByNotPreviouslyInitialZombieComparer(int id)
    {
        return !Player::GetPlayerInitialZombiePreviously(id)
            && !Player::GetPlayerInitialZombieLastMap(id);
    }

    internal void ShuffleByNotPreviouslyInitialZombie()
    {
        // This function is explicitly used for playing players.
        PrepareBufferPlayers(SHUFFLEPLAYING);

        BCSUtils::SortArray(0, _context.BufferIteratorSize, "zh2_internal_shuffle_compareinitials", "zh2_internal_shuffle_swapbufferitems");
        UpdateRelevantBufferSize(ShuffleByNotPreviouslyInitialZombieComparer);
        BCSUtils::ShuffleArray(0, _context.BufferRelevantSize, "zh2_internal_shuffle_swapbufferitems");
    }
}