#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Decorate
{
    script "zh2_dec_radio_cyclemusic" (raw direction) net clientside
    {
        if (GetRadioCollectionSize() == 0)
            terminate;

        if (ZH2Game::GetInvertRadioNavigation())
            direction = -direction;

        ZH2Game::GameContext.RadioCurrentlySelectedIndex += (int)direction;
        if (ZH2Game::GameContext.RadioCurrentlySelectedIndex < 0) ZH2Game::GameContext.RadioCurrentlySelectedIndex = BCSUtils::Max(GetRadioCollectionSize() - 1, 0);
        if (ZH2Game::GameContext.RadioCurrentlySelectedIndex >= GetRadioCollectionSize()) ZH2Game::GameContext.RadioCurrentlySelectedIndex = 0;
    }

    script "zh2_dec_radio_stopmusic" net clientside
    {
        SetMusic("");
    }

    script "zh2_dec_radio_setcurrentmusic" net clientside
    {
        // We have no tracks, no point in changing.
        if (Decorate::GetRadioCollectionSize() == 0)
        {
            Logger::LogActivator("You don't have any music tracks.");
            terminate;
        }

        int trackIndex = GetClientRadioCurrentlySelectedIndex();
        SetClientCurrentRadioTrackIndex(trackIndex);

        str lump = GetRadioTrackLumpName(trackIndex);
        str name = GetRadioTrackName(trackIndex);
        str author = GetRadioTrackAuthor(trackIndex);
        SetMusic(lump);

        str packet = Packet::New();
        packet = Packet::AppendStr(packet, lump);
        packet = Packet::AppendStr(packet, name);
        packet = Packet::AppendStr(packet, author);

        if(!Packet::Send("zh2_internal_radio_settrack", packet))
            Logger::LogError(LOGSOURCE, "Failed to call internal set radio track.");
    }

    script "zh2_internal_radio_settrack" (raw packet) net
    {
        if (!CheckWeapon(WEAPON_RADIO_NAME))
            terminate;

        // Avoid spamming radio music changes.
        int ticsLeft = GetRadioTrackCooldownTicsLeft();
        if (ticsLeft > 0)
        {
            int secondsLeft = int(BCSUtils::Ceil(fixed(ticsLeft) / 35.0));
            str secondsPlural = secondsLeft == 1 ? "" : "s";
            Logger::LogActivator("The music recently changed, so the track change won't be shared. Try again in " + str(secondsLeft) + " second" + secondsPlural + ".");
            terminate;
        }

        UpdateRadioTrackCooldown();

        if (!Packet::Send("zh2_internal_radio_settracktoclient", packet))
            Logger::LogError(LOGSOURCE, "Failed to call zh2_internal_radio_settracktoclient");
    }

    script "zh2_internal_radio_settracktoclient" (raw packet) clientside
    {
        int sourceId = PlayerNumber();
        BCSUtils::SetActivatorToConsolePlayer();

        packet = Packet::ReadStr(packet);
        str lump = Packet::Value;

        packet = Packet::ReadStr(packet);
        str name = Packet::Value;

        packet = Packet::ReadStr(packet);
        str author = Packet::Value;

        str trackMessage;
        buildmsg(trackMessage = StrParam())
        {
            Append(s:"\cd");
            Append(s:name);
            if ((raw)author != 0 && author != "")
            {
                Append(s:"\cj by \cd");
                Append(s:author);
            }
        }

        // We're the source. Log a message and leave because we already changed tracks.
        if (sourceId == ConsolePlayerNumber())
        {
            Logger::LogActivator("Now playing " + trackMessage + "\cj.");
            terminate;
        }

        int trackIndex = GetRadioTrackIndexByLumpName(lump);

        // Do we have this track?
        if (trackIndex == -1)
        {
            Logger::LogActivator(BCSUtils::PlayerName(sourceId) + " is playing " + trackMessage + "\cj, but you don't have this track. You can add it under the lump \cd" + lump + " \cjto play it.");
            terminate;
        }

        Logger::LogActivator(BCSUtils::PlayerName(sourceId) + " is now playing " + trackMessage + "\cj.");

        // If not the source, possible ignore this change.
        if (ZH2Game::GetIgnoreRadioMusic())
        {
            Logger::LogActivator("You've chosen to ignore this track.");
            terminate;
        }

        SetClientCurrentRadioTrackIndex(trackIndex);
        SetMusic(lump);
    }
}
