#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawInitialChosen(int queueIndex, fixed yOffset)
    {
        int index = Obituary::GetQueueData(queueIndex, 0);
        int id = Obituary::GetQueueData(queueIndex, 1);
        int multiple = Obituary::GetQueueData(queueIndex, 2);

        HudSetPointInternal(-26.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(id));
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        HudSetPointInternal(-18.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_HUMAN);
        DebugDraw();

        HudSetPointInternal(0.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_INITIAL_CHOSEN);
        DebugDraw();

        // With multiple zombies we want to show the index of this zombie.
        if (multiple)
        {
            BCSUtils::HudSetFont("SMALLFONT");
            BCSUtils::HudSetTextColor(CR_RED);

            HudSetPointInternal(-6.0, yOffset - 3.0);
            BCSUtils::HudDrawText(--_drawnHudId, str(index + 1));
            DebugDraw();
        }
    }

    internal void DrawPlayerSafe(int queueIndex, fixed yOffset)
    {
        int id = Obituary::GetQueueData(queueIndex, 0);
        int type = Obituary::GetQueueData(queueIndex, 1);
        str graphic = TranslateSpecieGraphic(type);

        HudSetPointInternal(-26.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(id));
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        if (graphic != (str)0)
        {
            HudSetPointInternal(-18.0, yOffset);
            BCSUtils::HudDrawImage(--_drawnHudId, graphic);
            DebugDraw();
        }

        HudSetPointInternal(0.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_SAFE);
        DebugDraw();
    }

    internal void DrawPlayerScratched(int queueIndex, fixed yOffset, fixed alpha)
    {
        int infected = Obituary::GetQueueData(queueIndex, 0);
        int infector = Obituary::GetQueueData(queueIndex, 1);
        int infectorType = Obituary::GetQueueData(queueIndex, 2);
        str infectorGraphic = TranslateSpecieGraphic(infectorType);

        HudSetPointInternal(-18.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(infector));
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        if (infectorGraphic != (str)0)
        {
            HudSetPointInternal(-9.0, yOffset);
            BCSUtils::HudDrawImage(--_drawnHudId, infectorGraphic);
            DebugDraw();
        }

        HudSetPointInternal(9.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_HUMAN);
        DebugDraw();

        fixed effectAlpha = BCSUtils::Max(0, alpha - 0.4);
        BCSUtils::HudSetAlpha(effectAlpha);

        HudSetPointInternal(9.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_SCRATCH);
        DebugDraw();

        BCSUtils::HudSetAlpha(alpha);

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_CENTER);

        HudSetPointInternal(18.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(infected));
        DebugDraw();
    }

    internal void DrawPlayerInfected(int queueIndex, fixed yOffset, fixed alpha)
    {
        int id = Obituary::GetQueueData(queueIndex, 0);

        HudSetPointInternal(-8.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(id));
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        HudSetPointInternal(0.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_HUMAN);
        DebugDraw();

        fixed effectAlpha = BCSUtils::Max(0, alpha - 0.4);
        BCSUtils::HudSetAlpha(effectAlpha);

        HudSetPointInternal(0.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_SCRATCH);
        DebugDraw();

        BCSUtils::HudSetAlpha(alpha);
    }

    internal void DrawPlayerCured(int queueIndex, fixed yOffset)
    {
        int id = Obituary::GetQueueData(queueIndex, 0);

        HudSetPointInternal(-26.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(id));
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        HudSetPointInternal(-18.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_ZOMBIE);
        DebugDraw();

        HudSetPointInternal(0.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_CURE);
        DebugDraw();
    }

    internal void DrawPlayerDied(int queueIndex, fixed yOffset)
    {
        int id = Obituary::GetQueueData(queueIndex, 0);
        int type = Obituary::GetQueueData(queueIndex, 1);
        int deathType = Obituary::GetQueueData(queueIndex, 2);
        str specieGraphic = TranslateSpecieGraphic(type);

        // Determine the graphic to draw based on the type.
        str deathGraphic;
        switch(deathType)
        {
            case ZH2Game::DEATHTYPE_SUICIDE: { deathGraphic = HUD_OBITUARY_SUICIDE; break; }
            case ZH2Game::DEATHTYPE_FALLING: { deathGraphic = HUD_OBITUARY_FALLING; break; }
            case ZH2Game::DEATHTYPE_DROWNING: { deathGraphic = HUD_OBITUARY_DROWNING; break; }
            case ZH2Game::DEATHTYPE_CRUSHING: { deathGraphic = HUD_OBITUARY_CRUSHING; break; }
            case ZH2Game::DEATHTYPE_TELEFRAG: { deathGraphic = HUD_OBITUARY_TELEFRAG; break; }
            case ZH2Game::DEATHTYPE_UNSAFE: { deathGraphic = HUD_OBITUARY_UNSAFE; break; }
            default: deathGraphic = HUD_OBITUARY_UNKNOWN; break;
        }

        HudSetPointInternal(-26.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(id));
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        if (specieGraphic != (str)0)
        {
            HudSetPointInternal(-18.0, yOffset);
            BCSUtils::HudDrawImage(--_drawnHudId, specieGraphic);
            DebugDraw();
        }

        HudSetPointInternal(0.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, deathGraphic);
        DebugDraw();
    }

    internal void DrawPlayerKilledByPlayer(int queueIndex, fixed yOffset, fixed alpha)
    {
        int killedId = Obituary::GetQueueData(queueIndex, 0);
        int killerId = Obituary::GetQueueData(queueIndex, 1);
        int killedType = Obituary::GetQueueData(queueIndex, 2);
        int killerType = Obituary::GetQueueData(queueIndex, 3);
        int itemIndex = Obituary::GetQueueData(queueIndex, 4);
        bool addFireEffect = Obituary::GetQueueData(queueIndex, 5);
        bool addAcidEffect = Obituary::GetQueueData(queueIndex, 6);
        str killedGraphic = TranslateSpecieGraphic(killedType);
        str killerGraphic = TranslateSpecieGraphic(killerType);
        str itemGraphic = Item::GetItemObituaryGraphic(itemIndex);
        int itemGraphicWidth = Item::GetItemObituaryGraphicWidth(itemIndex);

        // No graphic, default to a generic icon and its width.
        if (itemGraphic == (str)0 || itemGraphic == "")
        {
            itemGraphic = HUD_OBITUARY_UNKNOWN;
            itemGraphicWidth = 36;
        }

        HudSetPointInternal(fixed(-itemGraphicWidth / 2) - 8.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(killerId));
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        if (killedGraphic != (str)0)
        {
            HudSetPointInternal(fixed(-itemGraphicWidth / 2), yOffset);
            BCSUtils::HudDrawImage(--_drawnHudId, killerGraphic);
            DebugDraw();
        }

        HudSetPointInternal(0.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, itemGraphic);
        DebugDraw();

        // Extra effect to draw.
        if (addFireEffect || addAcidEffect)
        {
            str graphic = addFireEffect ? HUD_OBITUARY_FIRE : HUD_OBITUARY_ACID;
            fixed alphaReduction = addFireEffect ? 0.2 : 0.5;

            fixed effectAlpha = BCSUtils::Max(0, alpha - alphaReduction);
            BCSUtils::HudSetAlpha(effectAlpha);

            HudSetPointInternal(fixed(itemGraphicWidth / 2) - 18.0, yOffset);
            BCSUtils::HudDrawImage(--_drawnHudId, graphic);
            DebugDraw();

            BCSUtils::HudSetAlpha(alpha);
        }

        if (killedGraphic != (str)0)
        {
            HudSetPointInternal(fixed(itemGraphicWidth / 2), yOffset);
            BCSUtils::HudDrawImage(--_drawnHudId, killedGraphic);
            DebugDraw();
        }

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_CENTER);

        HudSetPointInternal(fixed(itemGraphicWidth / 2) + 8.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(killedId));
        DebugDraw();
    }

    internal void DrawPlayerKilledByMonster(int queueIndex, fixed yOffset)
    {
        int id = Obituary::GetQueueData(queueIndex, 0);
        int type = Obituary::GetQueueData(queueIndex, 1);
        str monsterName = Obituary::GetQueueData(queueIndex, 2);
        str specieGraphic = TranslateSpecieGraphic(type);

        HudSetPointInternal(-18.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, monsterName);
        DebugDraw();

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_CENTER);

        HudSetPointInternal(-10.0, yOffset);
        BCSUtils::HudDrawImage(--_drawnHudId, HUD_OBITUARY_MONSTER);
        DebugDraw();

        if (specieGraphic != (str)0)
        {
            HudSetPointInternal(10.0, yOffset);
            BCSUtils::HudDrawImage(--_drawnHudId, specieGraphic);
            DebugDraw();
        }

        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_CENTER);

        HudSetPointInternal(18.0, yOffset);
        BCSUtils::HudDrawText(--_drawnHudId, BCSUtils::PlayerName(id));
        DebugDraw();
    }
}