#ifdef __IMPORTED__
	#error This file must be #included.
#endif

strict namespace Reward
{
    // Extension that gives a number of random players the given reward container.
    internal void GiveRandomPlayerRewardContainers(RewardItemTypeFlagsT type)
    {
        // No players to reward.
        if (PlayerCount() == 0)
            return;

        // Check how many players to give an item.
        int givePlayerCount = ZH2Game::GetEndOfRoundRewardCount();
        if (givePlayerCount == 0)
            return;

        str itemName = Reward::ContainerTypeToItemName(type);
        Shuffle::ShuffleByNotOwningItem(itemName);

        // Ensure there are players that we can give an item.
        int relevantSize = Shuffle::GetRelevantSize();
        if (relevantSize == 0)
            return;

        // Now loop until we either exhaust the buffer or gave everybody an item.
        int index = 0;
        while (givePlayerCount-- && relevantSize--)
        {
            int id = Shuffle::GetIndexValue(index);
            int tid = Identity::GetTid(id);
            index++;
            
            // Should also not happen, we just checked if the player has the item already.
            if (CheckActorInventory(tid, itemName))
            {
                Logger::LogWarning(LogSource, "Returned player to reward already has the container.");
                return;
            }

            GiveActorInventory(tid, itemName, 1);
            InformPlayerContainerReceived(id, type);
        }
    }
}
