#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Reward
{
    internal void GiveReward(RewardItemTypeFlagsT type)
    {
        GivePlayerReward(PlayerNumber(), type);
    }

    internal void GivePlayerReward(int id, RewardItemTypeFlagsT type)
    {
        VALIDATE_ID_VALID_FUNCTION(id);
        int tid = Identity::GetTid(id);

        Weight::PrepareWeightsByReward(id, type);

        // No weights means the player has all rewards already.
        if (!Weight::HasWeights())
        {
            Logger::LogTo(id, "You have all the rewards! Use some before receiving new ones.");
            return;
        }

        int index = -1;
        while(true)
        {
            index = Weight::Next(index);

            // This should not happen.
            // We have weights, and we already filtered non-applicable items.
            // We should ALWAYS get a valid weight.
            if (index == -1)
            {
                Logger::LogWarning(LOGSOURCE , "No more weights exist when attempting to give an item to player " + str(id) + ".");
                continue;
            }

            // We already checked this when preparing the weights, it should not happen.
            if (!GetCanGivePlayerReward(id, index))
            {
                Logger::LogWarning(LOGSOURCE , "Unexpected item index " + str(index) + " can't be given when attempting to give an item to player " + str(id) + ".");
                continue;
            }

            break;
        }

        // Determine and take the user's item.
        // This is done loosely in case this function is called internally and the player won't have the item.
        str itemName = ContainerTypeToItemName(type);
        if ((raw)itemName != 0 && itemName != "" && CheckActorInventory(tid, itemName) > 0)
            TakeActorInventory(tid, itemName, 1);

        GivePlayerRewardByIndex(id, index);
        BroadcastGiveItem(id, index);
    }

    internal bool GetCanGiveReward(int index)
    {
        return GetCanGivePlayerReward(PlayerNumber(), index);
    }

    internal bool GetCanGivePlayerReward(int id, int index)
    {
        Player::SpecieTypeT specie = Player::GetPlayerSpecie(id);

        // Conditionally check for specie.
        // Both instances must be specie specific.
        // If one doesn't provide it we assume the reward can be for any specie.
        if (specie != Player::SPECIENONE)
        {
            Player::SpecieTypeT rewardSpecie = Reward::GetRewardSpecieSpecific(index);
            if (rewardSpecie != Player::SPECIENONE && specie != rewardSpecie)
                return false;
        }

        // Check for restriction.
        // Restriction means there's some reason the item can't be given (restricted/duplicate/disabled/etc).
        str callRestrict = GetRewardCallRestrict(index);
        if (callRestrict != (raw)0 && callRestrict != ""
            && ACS_NamedExecuteWithResult(callRestrict, id))
        {
            Logger::LogDebug(LOGSOURCE , "Can't give reward, restrict script \cd\"" + callRestrict + "\"\cj returned 'true'.");
            return false;
        }

        // Check for duplicates, skip if the user already has the item.
        str give = GetRewardGive(index);
        if ((raw)give != 0 && give != ""
            && CheckActorInventory(Identity::GetTid(id), give) > 0)
        {
            Logger::LogDebug(LOGSOURCE , "Can't give reward, the user already has item \cd\"" + give + "\"\cj.");
            return false;
        }

        return true;
    }

    internal void GiveRewardByIndex(int index)
    {
        GivePlayerRewardByIndex(PlayerNumber(), index);
    }

    internal void GivePlayerRewardByIndex(int id, int index)
    {
        VALIDATE_ID_VALID_FUNCTION(id);
        int tid = Identity::GetTid(id);

        str name = GetRewardName(index),
            callGive = GetRewardCallGive(index),
            give = GetRewardGive(index),
            sound = GetRewardSound(index);

        if ((raw)callGive != 0 && callGive != "")
        {
            if (!ACS_NamedExecuteAlways(callGive, 0, id))
                Logger::logError(LOGSOURCE , "Failed to call script \"" + callGive + "\" for reward index " + str(index) + ".");
        }

        if ((raw)give != 0 && give != "")
            GiveActorInventory(tid, give, 1);

        if ((raw)sound != 0 && sound != "")
            PlaySound(tid, sound, CHAN_ITEM, 1.0);
    }

    internal void BroadcastGiveItem(int id, int index)
    {
        str localMessage = GetRewardLocalMessage(index),
            message = GetRewardMessage(index);

        if ((raw)localMessage != 0 && localMessage != "")
            Logger::LogTo(id, localMessage);

        if ((raw)message != 0 && message != "")
        {
            if (BCSUtils::StrContains(message, REWARD_PLAYER_TOKEN))
                message = BCSUtils::StrReplace(message, REWARD_PLAYER_TOKEN, BCSUtils::PlayerName(id));

            Logger::LogExcept(id, message);
        }
    }
}
