#ifdef __IMPORTED__
	#error This file must be #included.
#endif

strict namespace Reward
{
    script "zh2_internal_reward_givefatigue" (raw idRaw)
    {
        int id = (int)idRaw;
        Power::SetPlayerPowerTics(id, Power::POWERREWARDHUMANSPEED, 60 * 35);
    }

    script "zh2_internal_reward_givevulnerability" (raw idRaw)
    {
        int id = (int)idRaw;
        Power::GivePlayerPower(id, Power::POWERREWARDZOMBIEVULNERABILITY);
    }

    script "zh2_internal_reward_giveweaponsupgrade" (raw idRaw)
    {
        int id = (int)idRaw;
        Power::GivePlayerPower(id, Power::POWERREWARDHUMANWEAPONUPGRADE);
    }

    script "zh2_internal_reward_givezombiesecondary" (raw idRaw)
    {
        int id = (int)idRaw;
        Game::SetPlayerZombieAbilityFlags(id, Game::GetDefaultZombieAbilityFlags());
        Sync::SyncGame();
    }

    script "zh2_internal_reward_givespeedincrease" (raw idRaw)
    {
        int id = (int)idRaw;
        Power::GivePlayerPower(id, Power::POWERREWARDZOMBIESPEED);
    }

    script "zh2_internal_reward_givehighjump" (raw idRaw)
    {
        int id = (int)idRaw;
        Power::SetPlayerPowerTics(id, Power::POWERREWARDZOMBIEJUMP, 90 * 35);
    }
}
