#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define MAX_REWARD_DEFINITIONS 100
#define REWARD_PLAYER_TOKEN "%p"

#define REWARD_CONTAINER_COUNT 2

strict namespace Reward
{
    struct RewardCollectionContextT
    {
        RewardContextT Collection[MAX_REWARD_DEFINITIONS];
        int Count;
    };

    struct RewardContextT
    {
        int ContainerFlags;
        str Name;
        int Weight;
        Player::PlayerSpecieT SpecieSpecific;
        str CallRestrict;
        str CallGive;
        str Give;
        str Sound;
        str LocalMessage;
        str Message;
    };

    enum RewardItemTypeFlagsT : int
    {
        REWARDNONE,
        REWARDORBMINOR = 1 << 0,
        REWARDORBMAJOR = 1 << 1,
    };
}