#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace CVar
{
    internal enum TranslucentAlliesT : int
    {
        TRANSLUCENT_ALLIES_OFF,
        TRANSLUCENT_ALLIES_ON_WITH_REQUIRED_CVARS,
        TRANSLUCENT_ALLIES_ON,
    };

    internal enum ZombieSkinBehaviourT : int
    {
        BEHAVIOUR_DEFAULT,
        BEHAVIOUR_FORCEOLDSKIN,
        BEHAVIOUR_FORCENEWSKIN,
    };

    internal enum ObituaryDisplayModeT : int
    {
        OBITUARYDISPLAY_GRAPHICAL,
        OBITUARYDISPLAY_TEXT,
        OBITUARYDISPLAY_LEGACYTEXT,
    };

    internal enum ObituaryDisplayModeOverrideT : int
    {
        OBITUARYDISPLAYOVERRIDE_NONE,
        OBITUARYDISPLAYOVERRIDE_GRAPHICAL,
        OBITUARYDISPLAYOVERRIDE_TEXT,
        OBITUARYDISPLAYOVERRIDE_LEGACYTEXT,
    };

    internal enum DropGrenadeOnInfectT : int
    {
        DROPBEHAVIOUR_ALWAYS,
        DROPBEHAVIOUR_ONLY_REGULAR_ZOMBIES,
        DROPBEHAVIOUR_NEVER,
    };

    internal enum DamageFeedbackMarkerShowTypeT : int
    {
        DAMAGEFEEDBACK_MARKER_SHOW_NONE,
        DAMAGEFEEDBACK_MARKER_SHOW_HITS,
        DAMAGEFEEDBACK_MARKER_SHOW_KILLS,
        DAMAGEFEEDBACK_MARKER_SHOW_BOTH,
    };

    internal enum DamageFeedbackCounterShowTypeT : int
    {
        DAMAGEFEEDBACK_COUNTER_SHOW_NONE,
        DAMAGEFEEDBACK_COUNTER_SHOW_DAMAGE,
        DAMAGEFEEDBACK_COUNTER_SHOW_KILLS,
        DAMAGEFEEDBACK_COUNTER_SHOW_BOTH,
    };

    internal enum DamageFeedbackNumberShowTypeT : int
    {
        DAMAGEFEEDBACK_NUMBER_SHOW_NONE,
        DAMAGEFEEDBACK_NUMBER_SHOW_TOTAL,
        DAMAGEFEEDBACK_NUMBER_SHOW_INDIVIDUAL,
    };

    internal enum IdentifyPlayerSpecieTypeT : int
    {
        IDENTIFY_PLAYER_OFF,
        IDENTIFY_PLAYER_ALL,
        IDENTIFY_PLAYER_ONLY_SAME,
        IDENTIFY_PLAYER_ONLY_OTHER,
    };

    internal enum IdentifyPlayerTypeT : int
    {
        IDENTIFY_PLAYER_BOTH,
        IDENTIFY_PLAYER_NAME,
        IDENTIFY_PLAYER_SPECIE,
    };

    internal enum InitialZombiePickMethodT : int
    {
        INITIALZOMBIEPICKMETHOD_RANDOM,
        INITIALZOMBIEPICKMETHOD_LEGACY,
        INITIALZOMBIEPICKMETHOD_WEIGHT
    };

    internal enum HudSkinBehaviourT : int
    {
        HUDSKINBEHAVIOUR_DEFAULT,
        HUDSKINBEHAVIOUR_FORCEDEFAULTSKIN,
        HUDSKINBEHAVIOUR_FORCELEGACYSKIN,
    };

    internal enum HudSkinPreferenceT : int
    {
        HUDSKINPREFERENCE_AUTO,
        HUDSKINPREFERENCE_DEFAULT,
        HUDSKINPREFERENCE_LEGACY,
    };
}
