#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    internal void DrawBarHud()
    {
        fixed scale = ZH2Game::GetHudPlayerBarsScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetDisappearTime(1.0);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_CENTER, BCSUtils::HUD_ALIGN_BOTTOM);

        int id = HUD_PLAYERBAR;
        
        // Left side
        fixed x = 320.0 + ZH2Game::GetHudPlayerBarsOffsetX(),
              y = BCSUtils::HudBottom() - 100.0 - ZH2Game::GetHudPlayerBarsOffsetY();

        x += _xShakeOffset;
        y += _yShakeOffset;

        id = DrawSprintBar(id, x, y);
        y += 15.0;
        id = DrawAirSupplyBar(id, x, y);
    }

    internal int DrawSprintBar(int id, fixed x, fixed y)
    {
        // Draw the sprint bar if human, and if we are not at the maximum.
        if (!Player::GetIsHuman())
            return id;
        
        int left = Player::GetSprintLeft();
        if (left == SPRINT_ITEM_MAX)
            return id;
        
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawImage(id--, BAR_SPRINT_NAME);

        fixed percentage = fixed(left) / fixed(SPRINT_ITEM_MAX);
        fixed clipX = BCSUtils::Round(fixed(BAR_SPRINT_WIDTH) * percentage);

        //BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
        BCSUtils::HudSetClipRect(fixed(-BAR_SPRINT_WIDTH / 2), fixed(-BAR_SPRINT_HEIGHT), clipX, fixed(BAR_SPRINT_HEIGHT));
        BCSUtils::HudDrawImage(id--, BAR_SPRINT_METER_NAME);
        BCSUtils::HudRemoveClipRect();
        BCSUtils::HudSetAlpha(1.0);

        DebugDraw();
        
        return id;
    }

    internal int DrawAirSupplyBar(int id, fixed x, fixed y)
    {
        // Note also that because zombies have no air supply, the bar will show empty even though they will never drown.
        if (!Player::GetIsHuman())
            return id;

		int airSupply = GetAirSupply(ConsolePlayerNumber());
		if (airSupply == MAX_AIRSUPPLY)
			return id;

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawImage(id--, BAR_AIRSUPPLY_NAME);

        fixed percentage = fixed(airSupply) / fixed(MAX_AIRSUPPLY);
        fixed clipX = BCSUtils::Round(fixed(BAR_AIRSUPPLY_WIDTH) * percentage);

        //BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
        BCSUtils::HudSetClipRect(fixed(-BAR_AIRSUPPLY_WIDTH / 2), fixed(-BAR_AIRSUPPLY_HEIGHT), clipX, fixed(BAR_AIRSUPPLY_HEIGHT));
        BCSUtils::HudDrawImage(id--, BAR_AIRSUPPLY_METER_NAME);
        BCSUtils::HudRemoveClipRect();
        BCSUtils::HudSetAlpha(1.0);

        DebugDraw();

        return id;
    }
}