#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    // NOTE: Setting CVars uses ConsoleCommand which might break in the future. We do notify of this on the UI.
    // https://wiki.zandronum.com/ConsoleCommand

    internal void DrawClientSettingsHud()
    {
        fixed scale = ZH2Game::GetHudClientSettingsScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0, 480.0);
        BCSUtils::HudSetScale(scale);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_TOP);

        fixed y = BCSUtils::HudTop() + 50.0;

        PrepareHud(
            BCSUtils::HudLeft() + 100.0,
            y,
            false);

        DrawClientSettingsHeader();

        BCSUtils::HudSetFont("BigFont");
        HudSetPointInternal(0.0, 60.0 + y);

        if (ZH2Game::GameContext.RequestedClientSettingCount > 0)
        {
            BCSUtils::HudDrawText(--_drawnHudId, "Settings");

            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(CR_YELLOW);

            HudSetPointInternal(0.0, 80.0 + y);
            BCSUtils::HudDrawText(--_drawnHudId, "Type");

            HudSetPointInternal(90.0, 80.0 + y);
            BCSUtils::HudDrawText(--_drawnHudId, "Name");

            HudSetPointInternal(250.0, 80.0 + y);
            BCSUtils::HudDrawText(--_drawnHudId, "Current");

            HudSetPointInternal(320.0, 80.0 + y);
            BCSUtils::HudDrawText(--_drawnHudId, "Required");

            HudSetPointInternal(400.0, 80.0 + y);
            BCSUtils::HudDrawText(--_drawnHudId, "Action");

            for (int i = 0; i < ZH2Game::GameContext.RequestedClientSettingCount; ++i)
            {
                PrepareHud(
                    BCSUtils::HudLeft() + 100.0,
                    y + 150.0 + fixed(30 * i),
                    false);

                DrawInvalidSetting(i);
            }
        }
        else
        {
            BCSUtils::HudSetTextColor(CR_GREEN);
            BCSUtils::HudDrawText(--_drawnHudId, "No settings to consolidate.");
        }
    }

    internal void DrawClientSettingsHeader()
    {
        // Top
        BCSUtils::HudSetFont("BigFont");

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, "Consolidate settings");
        DebugDraw();

        // Bottom
        int count = ZH2Game::GameContext.RequestedClientSettingCount;
        int persistingCount = ZH2Game::PersistingGameContext.RequestedClientSettingCount;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_YELLOW);

        HudSetPointInternal(0.0, 15.0);
        BCSUtils::HudDrawText(--_drawnHudId, "Note: \cjUpdating CVars makes use of ConsoleCommand, which could possibly be phased out of the engine in the future.");
        DebugDraw();

        // Vertical offset changes if protect cvars is enabled.
        fixed addY = 0.0;

        // Inform client of cl_protectcvars if set.
        if (ZH2Game::GetProtectCVars())
        {
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(CR_YELLOW);

            HudSetPointInternal(0.0, 25.0);
            BCSUtils::HudDrawText(--_drawnHudId, "Note: \cjyou have enabled 'cl_protectcvars', which means any changes here are reverted when you disconnect. Please disable it to persist them.");
            DebugDraw();

            addY += 10.0;
        }

        // Inform user of the issue with ConsoleCommand
        BCSUtils::HudSetTextColor(CR_WHITE);

        HudSetPointInternal(0.0, 25.0 + addY);
        BCSUtils::HudDrawText(--_drawnHudId, "Total invalid settings: \cd" + str(count) + "\cj/\cd" + str(persistingCount) + "\cj.");

        BCSUtils::HudSetFont("BigFont");

        HudSetPointInternal(0.0, 50.0 + addY);
        BCSUtils::HudDrawText(--_drawnHudId, "Actions");

        BCSUtils::HudSetFont("SmallFont");

        // Clickable buttons
        if (DrawClickableText(--_drawnHudId, 0.0, 65.0 + addY, 140.0, 10.0, "Refresh settings"))
            Settings::UpdateCurrentClientSettings();

        if (DrawClickableText(--_drawnHudId, 0.0, 80.0 + addY, 140.0, 10.0, "Close settings"))
            Settings::CloseClientSettingsMenu();

        if (DrawClickableText(--_drawnHudId, 160.0, 65.0 + addY, 140.0, 10.0, "Open keybinds menu"))
            Settings::CloseMenuAndOpenCustomizeMenu();

        if (DrawClickableText(--_drawnHudId, 160.0, 80.0 + addY, 140.0, 10.0, "Open zombie horde 2 menu"))
            Settings::CloseMenuAndOpenZh2Menu();
    }

    internal void DrawInvalidSetting(int index)
    {
        str type = Settings::GetInvalidClientSettingType(index);
        str name = Settings::GetInvalidClientSettingName(index);
        int value = Settings::GetInvalidClientSettingValue(index);
        str label = Settings::GetInvalidClientSettingLabel(index);

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_WHITE);

        HudSetPointInternal();
        BCSUtils::HudDrawText(--_drawnHudId, type == "cvar" ? "CVar" : "Keybind");

        HudSetPointInternal(90.0, 0.0);
        BCSUtils::HudDrawText(--_drawnHudId, "\cd" + name);

        HudSetPointInternal(250.0, 0.0);
        if (type == "cvar") BCSUtils::HudDrawText(--_drawnHudId, "\cd" + str(GetCvar(name)));
        else BCSUtils::HudDrawText(--_drawnHudId, "\cd" + (BCSUtils::KeyBound(name) ? "bound" : "unbound"));

        HudSetPointInternal(320.0, 0.0);
        if (type == "cvar") BCSUtils::HudDrawText(--_drawnHudId, "\cd" + str(value));
        else BCSUtils::HudDrawText(--_drawnHudId, "\cd" + (value ? "bound" : "unbound"));

        // Possibly update CVar.
        // Restrictions of ConsoleCommand prevents us from binding/unbinding, so this is not supported.
        if (type == "cvar")
        {
            if (DrawClickableText(--_drawnHudId, 400.0, 0.0, 100.0, 10.0, "Update CVar"))
                UpdateSettingToRequested(index);
        }

        BCSUtils::HudSetTextColor(CR_WHITE);

        HudSetPointInternal(0.0, 10.0);
        BCSUtils::HudDrawText(--_drawnHudId, label);
    }

    internal void UpdateSettingToRequested(int index)
    {
        str type = Settings::GetInvalidClientSettingType(index);

        // Failsafe, should not allow when we try (un)bind a key
        if (type != "cvar")
            return;

        str name = Settings::GetInvalidClientSettingName(index);
        int value = Settings::GetInvalidClientSettingValue(index);

        // ConsoleCommand because SetCVar / SetGameplaySetting do not allow changing CVars we define.
        ConsoleCommand(name + " " + str(value));

        Settings::UpdateCurrentClientSettings();
    }
}