#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "status.acs"
#include "power.acs"
#include "bar.acs"
#include "blur.acs"
#include "inventory.acs"

strict namespace Hud
{
    internal void DrawPlayerHud()
    {
        if (!BCSUtils::ActorIsAlive(ActivatorTid()))
            return;

        _drawnHudId = HUDID_PLAYER;

        if (ZH2Game::GetDrawPlayerBarsHud())
            DrawBarHud();

        if (ZH2Game::GetDrawPlayerStatusHud())
            DrawPlayerStatusHud();
            
        if (ZH2Game::GetDrawPlayerPowersHud())
            DrawPlayerPowersHud();
        
        DrawInventory();

        DrawBlurHud();
    }
}