#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hud
{
    #define PLAYERID_KEYROWCOUNT 5

    internal void DrawPlayerStatusHud()
    {
        // Hud scaling is done through `HudSetVirtualSize` as `HudSetScale` only applies scaling to the final sprite
        // The issue here is that positioning will be wrong.

        fixed scale = ZH2Game::GetHudPlayerStatusScale();
        BCSUtils::HudResetState();
        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_LEFT, BCSUtils::HUD_ALIGN_BOTTOM);
        BCSUtils::HudSetStayTime(BCSUtils::HUDTIC);
        
        // Left side
        fixed x = BCSUtils::HudLeft() + ZH2Game::GetHudPlayerStatusOffsetX(),
              y = BCSUtils::HudBottom() - ZH2Game::GetHudPlayerStatusOffsetY();

        x += _xShakeOffset;
        y += _yShakeOffset;

        DrawPlayerIdentification(x + 30.0, y - 20.0, scale);

        // Right side
        x = BCSUtils::HudRight() + ZH2Game::GetHudPlayerStatusOffsetX(),
        y = BCSUtils::HudBottom() - ZH2Game::GetHudPlayerStatusOffsetY();

        x += _xShakeOffset;
        y += _yShakeOffset;

        DrawWeaponIcon(x - 80.0, y - 40.0);
        
        if (Player::GetIsZombie())
            DrawZombieAbilities(x - 80.0, y - 220.0);
    }

    internal void DrawPlayerIdentification(fixed x, fixed y, fixed scale)
    {
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawImage(--_drawnHudId, "HUDBACK");
        DebugDraw();

        BCSUtils::HudSetPoint(x + 90.0, y - 40.0);
        BCSUtils::HudDrawImage(--_drawnHudId, "HUDIBACK");
        DebugDraw();

        DrawPlayerSkin(x + 25.0, y - 18.0);
        DrawArmor(x + 50.0, y - 30.0);
        DrawHealth(x + 50.0, y - 20.0);
        DrawCurrentOwnedItem(x + 100.0, y - 125.0);
        DrawKeyList(x + 118.0, y - 70.0, scale);
    }

    // TODO: Should come from a parsed lump.
    internal void DrawPlayerSkin(fixed x, fixed y)
    {
        str skinIcon = (raw)0;
        int indexAcs = GetPlayerSkin(ConsolePlayerNumber(), PLAYERSKIN_VISIBLE);
        if (indexAcs == -1)
            return;

        switch ((str)GetSkinProperty(indexAcs, "Name"))
        {
            case SKIN_HUMAN_GRENADE: skinIcon = PLAYER_HUD_SKIN_FIREGRENADE; break;
            case SKIN_HUMAN_HANDGUN: skinIcon = PLAYER_HUD_SKIN_HANDGUN; break;
            case SKIN_HUMAN_JACKSGUN: skinIcon = PLAYER_HUD_SKIN_JACKSGUN; break;
            case SKIN_HUMAN_SHOTGUN: skinIcon = PLAYER_HUD_SKIN_SHOTGUN; break;
            case SKIN_HUMAN_DOUBLEBARRELEDSHOTGUN: skinIcon = PLAYER_HUD_SKIN_DOUBLESHOTGUN; break;
            case SKIN_HUMAN_CHAINGUN: skinIcon = PLAYER_HUD_SKIN_CHAINGUN; break;
            case SKIN_HUMAN_SNIPER: skinIcon = PLAYER_HUD_SKIN_SNIPER; break;
            case SKIN_HUMAN_RADIO: skinIcon = PLAYER_HUD_SKIN_RADIO; break;
            case SKIN_ZOMBIEOLD: skinIcon = PLAYER_HUD_SKIN_OLDZOMBIE; break;
            case SKIN_ZOMBIEREGULAR: skinIcon = PLAYER_HUD_SKIN_REGULARZOMBIE; break;
            case SKIN_ZOMBIEINITIAL: skinIcon = PLAYER_HUD_SKIN_INITIALZOMBIE; break;

            // No skin found, Fallback to default skin used for specie.
            default:
                if (Player::GetIsHuman()) skinIcon = PLAYER_HUD_SKIN_HUMAN;
                else if (Player::GetIsZombie()) skinIcon = PLAYER_HUD_SKIN_ZOMBIE;
                else return;
        }

		if (skinIcon == (raw)0)
            return;
        
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawImage(--_drawnHudId, skinIcon);
    }

    internal void DrawArmor(fixed x, fixed y)
    {
        int armount = CheckInventory("Armor");
        if (armount == 0) return;

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_BLUE);
        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudSetCenterText(true);
        BCSUtils::HudDrawText(--_drawnHudId, str(armount));
        DebugDraw();
    }

    internal int DrawHealth(fixed x, fixed y)
    {
        // Also flicker health based on current health.
        int health = BCSUtils::Max(0, PlayerHealth());
        bool flicker = health <= (Player::GetIsZombie() ? HEALTH_ZOMBIECRITICAL : HEALTH_HUMANCRITICAL);
        if (!flicker || (flicker && Timer() % 50 < 25))
        {
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(flicker ? CR_RED : CR_WHITE);
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawText(--_drawnHudId, str(health));
            DebugDraw();
        }

        return _drawnHudId;
    }

    internal void DrawCurrentOwnedItem(fixed x, fixed y)
    {
        if (Item::GetClientOwnedInventorySize() == 0)
            return;
        
        int index = Item::GetInventoryIndex(Item::GetClientOwnedInventoryIndex(Item::_currentInventoryIndex));
        str graphic = Item::GetItemGraphic(index);
        str name = Item::GetItemName(index);
        int inventoryCount = CheckInventory(name);

        BCSUtils::HudSetPoint(x, y);
        BCSUtils::HudDrawImage(--_drawnHudId, graphic);
        DebugDraw();

        // Draw the current count of the item if we have more than one.
        if (inventoryCount > 1)
        {
            BCSUtils::HudSetPoint(x + 20.0, y - 10.0);
            BCSUtils::HudSetFont("SmallFont");
            BCSUtils::HudSetTextColor(CR_YELLOW);
            BCSUtils::HudDrawText(--_drawnHudId, str(inventoryCount));
            DebugDraw();
        }
    }

    internal void DrawKeyList(fixed x, fixed y, fixed scale)
    {
        // No keys to draw.
        int keyCount = Item::GetClientOwnedKeySize();
        if (keyCount == 0)
            return;
        
        // Start more left as we have more keys
        x -= 10.0 * fixed(keyCount / (PLAYERID_KEYROWCOUNT + 1));

        x *= 1.5;
        y *= 1.5;

        BCSUtils::HudSetVirtualSize(960.0 / scale, 720.0 / scale);

        for (int i = 0; i < keyCount; ++i)
        {
            fixed itemX = x + 15.0 * fixed(i / PLAYERID_KEYROWCOUNT);
            fixed itemY = y + 10.0 * fixed(i % PLAYERID_KEYROWCOUNT);
            int itemIndex = Item::GetKeyIndex(Item::GetClientOwnedKeyIndex(i));
            
            BCSUtils::HudSetPoint(itemX, itemY);
            BCSUtils::HudDrawImage(--_drawnHudId, Item::GetItemGraphic(itemIndex));
        }

        BCSUtils::HudSetVirtualSize(640.0 / scale, 480.0 / scale);
    }

    internal void DrawWeaponIcon(fixed x, fixed y)
    {
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_BOTTOM);
        
        str weaponIcon = "";
		if		(CheckWeapon(WEAPON_SHOTGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_SHOTGUN + str(CheckInventory(WEAPON_AMMO_SHOTGUN_NAME));
		else if (CheckWeapon(WEAPON_DOUBLESHOTGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_SUPERSHOTGUN  + str(CheckInventory(WEAPON_AMMO_DOUBLESHOTGUN_NAME));
		else if (CheckWeapon(WEAPON_SNIPER_NAME)) weaponIcon = WEAPON_HUD_SKIN_SNIPER + str(1 - CheckInventory(WEAPON_SNIPER_SHOULDEJECTCASE_NAME));
		else if (CheckWeapon(WEAPON_JACKSGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_JACKS + str(CheckInventory(WEAPON_AMMO_JACKSGUN_NAME));
		else if (CheckWeapon(WEAPON_HANDGUN_NAME)) weaponIcon = WEAPON_HUD_SKIN_PISTOL;
		
		if (weaponIcon != "")
		{
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, weaponIcon);
            DebugDraw();
            return;
		}

        // Special logic for the chaingun and fire grenade, which have two graphics and some clipping.
        if (CheckWeapon(WEAPON_CHAINGUN_NAME))
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_CHAINGUN);

            fixed percentage = fixed(CheckInventory(WEAPON_CHAINGUN_HEAT_NAME)) / fixed(WEAPON_CHAINGUN_MAX_HEAT);
			fixed clipX = BCSUtils::Round(fixed(WEAPON_CHAINGUN_METER_WIDTH) * percentage);


            BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
            BCSUtils::HudSetClipRect(fixed(-WEAPON_CHAINGUN_METER_WIDTH), fixed(-WEAPON_CHAINGUN_METER_HEIGHT), clipX, fixed(WEAPON_CHAINGUN_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_CHAINGUN_METER);
            BCSUtils::HudRemoveClipRect();
            BCSUtils::HudSetAlpha(1.0);

            DebugDraw();
        }
        else if (CheckWeapon(WEAPON_FIREGRENADE_NAME))
        {
            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_FIREGRENADE);

			fixed percentage = fixed(CheckInventory(WEAPON_FIREGRENADE_THROWPOWER_NAME)) / fixed(WEAPON_FIREGRENADE_MAX_THROWPOWER);
			fixed clipX = BCSUtils::Round(fixed(WEAPON_FIREGRENADE_METER_WIDTH) * percentage);

            BCSUtils::HudSetAlpha(BCSUtils::Min(1.0, percentage * 1.5));
            BCSUtils::HudSetClipRect(fixed(-WEAPON_FIREGRENADE_METER_WIDTH), fixed(-WEAPON_FIREGRENADE_METER_HEIGHT), clipX, fixed(WEAPON_FIREGRENADE_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, WEAPON_HUD_SKIN_FIREGRENADE_METER);
            BCSUtils::HudRemoveClipRect();
            BCSUtils::HudSetAlpha(1.0);

            DebugDraw();
        }
    }

    internal void DrawZombieAbilities(fixed x, fixed y)
    {
        BCSUtils::HudSetAlignment(BCSUtils::HUD_ALIGN_RIGHT, BCSUtils::HUD_ALIGN_BOTTOM);

        // Server disabled abilities or we have none, skip drawing.
        if (!ZH2Game::GetUseZombieAbilities()
            || Game::GetZombieAbilityFlags() == 0)
        {
			return;
		}

        BCSUtils::HudSetFont("SmallFont");
        BCSUtils::HudSetTextColor(CR_WHITE);
        BCSUtils::HudSetCenterText(true);
        
        for (int i = ABILITY_COUNT - 1; i >= 0; --i)
        {
            Game::ZombieAbilityTypeFlagsT flag = Game::GetZombieAbilityItemTypeByIndex(i + 1);

            // Should not happen.
            // If it does, we gracefully ignore for now and assume the ability can be used.
            if (flag != Game::ABILITY_NONE)
            {
                // Server disabled this ability or we don't have it.
                if (!Game::HasZombieAbility(flag)
                    || (ZH2Game::GetDisabledZombieAbilityFlags() & flag) != 0)
                {
                    continue;
                }
            }

            bool selected = Game::GetSelectedAbilityIndex() == i;

            int maxTics = Game::GetZombieAbilityCooldownMaxTicsByIndex(i);
            int tics = Game::GetZombieAbilityCooldownTicsLeftByIndex(i);

            // Visual indication of the ability not being ready.
            BCSUtils::HudSetAlpha(!selected && tics > 0 ? 0.4 : 1.0);

            BCSUtils::HudSetPoint(x, y);
            BCSUtils::HudDrawImage(--_drawnHudId, "HUD_ZA" + str(i) + str(1));

            // Visualize the time left before this ability can be used.
            int graphicIndex = selected ? 3 : 2;
            fixed percentage = BCSUtils::Clamp(fixed(tics) / fixed(maxTics), 0.0, 1.0);
            fixed clipY = fixed(HUD_ZOMBIEABILITY_METER_HEIGHT) - BCSUtils::Round(fixed(HUD_ZOMBIEABILITY_METER_HEIGHT) * percentage);

            BCSUtils::HudSetClipRect(fixed(-HUD_ZOMBIEABILITY_METER_WIDTH), -clipY, fixed(HUD_ZOMBIEABILITY_METER_WIDTH), fixed(HUD_ZOMBIEABILITY_METER_HEIGHT));
            BCSUtils::HudDrawImage(--_drawnHudId, "HUD_ZA" + str(i) + str(graphicIndex));
            BCSUtils::HudRemoveClipRect();

            DebugDraw();

            // Show possible cooldown if selected
            if (selected && tics > 0)
            {
                BCSUtils::HudSetAlpha(1.0);
                BCSUtils::HudSetPoint(x - 20.0, y - 10.0);
                str label = Utils::FormatTics(tics, true);
                BCSUtils::HudDrawText(--_drawnHudId, str(label));
            }

            y -= 60.0;
        }
    }
}