#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace ZH2Lib
{
    // Logging
    internal int GetClientOverwriteLogSeverity() { return BCSUTILS::Clamp(GetCvar("cl_zh2_overridelogseverity"), 0, 5); }
    internal int GetServerOverwriteLogSeverity() { return BCSUTILS::Clamp(GetCvar("sv_zh2_overridelogseverity"), 0, 5); }
    internal int GetGlobalOverwriteLogSeverity() { return BCSUTILS::Clamp(GetCvar("sv_zh2_overridegloballogseverity"), 0, 5); }

    // Tracers
    internal bool GetServerEnabledTracers() { return (bool)GetCvar("sv_zh2_enabletracers"); }
    internal int GetClientTracerType() { return BCSUTILS::Clamp(GetCvar("cl_zh2_tracertype"), 0, 2); }

    // Footstep
    internal int GetClientStepType() { return BCSUTILS::Clamp(GetCvar("cl_zh2_steptype"), 0, 2); }
    internal int GetClientMaxStepDistance() { return BCSUTILS::Clamp(GetCvar("cl_zh2_maxstepdistance"), 100, 8000); }

    // Weather
    internal bool GetSvEnableWeather() { return (bool)GetCvar("sv_zh2_enableweather"); }
    internal bool GetClEnableWeather() { return (bool)GetCvar("cl_zh2_enableweather"); }
    internal bool GetClEnableEmitterWeather() { return (bool)GetCvar("cl_zh2_enableemitterweather"); }
    internal bool GetClEnableRandomizedWeather() { return (bool)GetCvar("cl_zh2_enablerandomizedweather"); }
    internal bool GetClEnableAmbientWeather() { return (bool)GetCvar("cl_zh2_enableambientweather"); }

    // Chat / Zandronum
    internal int GetChatSound() { return GetCvar("chat_sound"); }
    internal bool GetShowMessages() { return (bool)GetCvar("show_messages"); }
    internal bool GetClientSendFullButtonInfo() { return (bool)GetCvar("compat_clientssendfullbuttoninfo"); }

    // Game - Sync
    bool GetUseSyncBuffer() { return (bool)GetCvar("sv_zh2_usesyncbuffer"); }
    int GetSyncDelay() { return BCSUTILS::Clamp(GetCvar("sv_zh2_syncdelay"), 0, 35); }
}