#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    // Manages the kick buffer which the AFK on the player side fills and formats a nice log message.
    internal void AfkPreventionRoundStartTicServer()
    {
        // To collect players we do this every 5 tics.
        if (Timer() % 5 != 0)
            return;

        int kickedCount = 0;

        for (int id = 0; id < BCSUtils::MAX_PLAYERS; id++)
        {
            if (GetPlayerWasRoundStartAfkKicked(id))
                kickedCount++;
        }

        if (kickedCount == 0)
            return;

        str logMessage;
        buildmsg(logMessage = StrParam())
        {
            int current = 0;
            Append(s:"\cd");

            for (int id = 0; id < BCSUtils::MAX_PLAYERS; id++)
            {
                if (!GetPlayerWasRoundStartAfkKicked(id))
                    continue;

                current++;

                if (current > 1)
                {
                    if (current == kickedCount)
                        Append(s:" and ");
                    else
                        Append(s:", ");
                }

                Append(s:BCSUtils::PlayerName(id));

                SetPlayerWasRoundStartAfkKicked(id, false);
            }

            Append(s:" ");
            Append(s:(kickedCount == 1 ? "was" : "were"));
            Append(s:" moved to spectators for inactivity.");
        }

        Logger::LogBold(logMessage);
    }

    internal bool GetWasRoundStartAfkKicked()
    {
        return GetPlayerWasRoundStartAfkKicked(PlayerNumber());
    }

    internal bool GetPlayerWasRoundStartAfkKicked(int id)
    {
        return ZH2Game::GameContext.AfkPreventionRoundStartContext.AfkKickedPlayers[id];
    }

    internal void SetWasRoundStartAfkKicked(bool set)
    {
        SetPlayerWasRoundStartAfkKicked(PlayerNumber(), set);
    }

    internal void SetPlayerWasRoundStartAfkKicked(int id, bool set)
    {
        ZH2Game::GameContext.AfkPreventionRoundStartContext.AfkKickedPlayers[id] = set;
    }
}
