#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    internal bool HandlePlayerChatMessage(int id, str message)
    {
        // The function prevents bots from sending a message when they are a zombie.
        // They are also not allowed to chat when the round has ended.
        return !PlayerIsBot(id) || Player::GetPlayerIsHuman(id) || Round::GetActiveKnownRoundState() < Round::STATEENDING;
    }
}
