#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    // This is the main method that is called from a few places to initiate the end state.
    internal void EndGame()
    {
        // Ensure the play timer is stopped here if it's active.
        if (RoundTimer::GetActiveTimerKnownType() == RoundTimer::TIMERPLAYING)
        {
            int index = RoundTimer::GetActiveTimerIndex();
            if (RoundTimer::GetTimerActive(index))
            {
                RoundTimer::StopTimer(index);
            }
        }

        // Set end reason if not already set (which it would if a player left, for example).
        if (Game::GetEndReason() == Game::REASONNONE)
            Game::SetEndReason(Game::REASONSPECIEWON);

        // Ensure the round state is defined.
        if (!Round::GetRoundDefined(Round::GetIndexOfKnownRoundStateType(Round::STATEENDING)))
        {
            Logger::LogError(LOGSOURCE, "Failed to start ending round state. Round not defined, use defaults or define the round.");
            return;
        }

        Round::SetKnownRoundState(Round::StateEnding);
        Sync::SyncRoundState();

        // We gotta sync both of these so the final stats are build properly.
        // (although to my knowledge we always sync players properly, but it doesn't hurt)
        Sync::SyncPlayers();
        Sync::SyncGame();

        // Turn off the radio, the proximity feature interferes with the end music and also is just generally annoying.
        if (Decorate::GetRadioBroadcastActive())
        {
            Decorate::ClearRadioBroadcast();
            Sync::SyncRadio();
        }
    }

    /* DIFFERENT KILL METHODS TO KILL ONE OR MORE SPECIES. */

    internal void KillHumans() { KillSpecies(Player::SPECIEHUMAN); }
    internal void KillZombies() { KillSpecies(Player::SPECIEZOMBIE); }
    internal void KillUnsafeHumans(int slot = -1) { KillUnsafeSpecies(Player::SPECIEHUMAN, slot); }
    internal void KillUnsafeZombies(int slot = -1) { KillUnsafeSpecies(Player::SPECIEZOMBIE, slot); }

    void KillUnsafePlayers(int slot = -1)
    {
        KillUnsafeHumans(slot);
        KillUnsafeZombies(slot);
    }

    internal void KillSpecies(Player::PlayerSpecieT specie)
    {
        for (int i = 0; i < BCSUTILS::MAX_PLAYERS; i++)
        {
            if (!PlayerInGame(i) || Player::GetPlayerSpecie(i) != specie)
                continue;

            KillPlayer(i);
        }
    }

    internal void KillUnsafeSpecies(Player::PlayerSpecieT specie, int slot = -1)
    {
        if (slot < -1 || slot >= MAX_SAFETY_SLOTS)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": slot " + str(slot) + " is not valid.");
            return;
        }

        for (int i = 0; i < BCSUTILS::MAX_PLAYERS; i++)
        {
            if (!PlayerInGame(i) || Player::GetPlayerSpecie(i) != specie)
                continue;

            KillUnsafePlayer(i, slot);
        }
    }

    void Kill(int modifier = MOD_UNKNOWN)
    {
        KillPlayer(PlayerNumber(), modifier);
    }

    void KillPlayer(int id, int modifier = MOD_UNKNOWN)
    {
        int tid = Identity::GetTID(id);
        if (!PlayerInGame(id) || !BCSUtils::ActorIsAlive(tid)) return;

        Thing_Damage(tid, /* BCSUtils::INT_MAX */ 999999, modifier);
    }

    internal void KillUnsafePlayer(int id, int slot = -1)
    {
        int tid = Identity::GetTID(id);
        if (!PlayerInGame(id) || !BCSUtils::ActorIsAlive(tid)) return;

        if (slot < -1 || slot >= MAX_SAFETY_SLOTS)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": slot " + str(slot) + " is not valid.");
            return;
        }

        if (slot == -1 && GetPlayerIsSafeAny(id))
        {
            Logger::LogDebug(LOGSOURCE, "Player not killed. Player id " + str(id) + " is safe.");
            return;
        }
        else if (slot != -1 && GetPlayerIsSafe(id, slot))
        {
            Logger::LogDebug(LOGSOURCE, "Player not killed. Player id " + str(id) + " is safe in slot " + str(slot) + ".");
            return;
        }

        KillPlayer(id, MOD_EXIT);
    }
}