#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Game"

#include "ending.acs"
#include "endgame.acs"
#include "tip.acs"
#include "safe.acs"
#include "team.acs"
#include "chat.acs"
#include "spawn.acs"
#include "health.acs"
#include "specie.acs"
#include "playtime.acs"
#include "knockback.acs"
#include "modifiers.acs"
#include "roundtime.acs"
#include "secondary.acs"
#include "infectcure.acs"
#include "scoreboard.acs"
#include "fullserver.acs"
#include "deathcam.acs"
#include "winningspecie.acs"
#include "initialspawnspot.acs"
#include "zombieteleportspot.acs"

strict namespace Game
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for game.");

        EventBus::AddCallbackByScriptName(EVENTPLAYERSPECIECHANGED, "zh2_internal_modifier_specie_changed");

        SetZombieHealthValues(true, 4000, 3000);
        SetZombieHealthValues(false, 2000, 1000);

        Game::SetDefaultZombieAbilityFlags(ABILITY_PUSH | ABILITY_SPIT);
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for game.");

        EventBus::AddCallbackByScriptName(EVENTPLAYERSPECIECHANGED, "zh2_internal_modifier_specie_changed");

        SetZombieHealthValues(true, 5000, 4000);
        SetZombieHealthValues(false, 1500, 750);

        Game::SetDefaultZombieAbilityFlags(ABILITY_PUSH);
    }
}

#undef LOGSOURCE