#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define CUSTOMDATA_ZOMBIEKILLS "ZombieKills"
#define CUSTOMDATA_HUMANKILLS "HumanKills"
#define CUSTOMDATA_INFECTS "Infects"

// Note, if we were to increase this value past 3 we do need to support the extra bit in the sync.
// Currently just 2 bits fit this data, so if we extend to up to 7 we need 3 bits.
#define MAX_VOTABLEMAPS 3

// The zombie teleports could be unlimited but we need some limit here.
// By default the initial spawn spots should really only be 5 since 5 initials can be chosen.
// However, we have a cvar to change this limit, and we can have like 32 initials now.
// Better to adjust code to support this than force people to add 32 spawns.
#define MAX_INITIALSPAWNSPOTS 50
#define MAX_ZOMBIETELEPORTSPOTS 100

// Tips, maximum count and how long we want to show tips for.
#define MAX_TIPS 100
#define TIP_LENGTH 35 * 10

#define ABILITY_COUNT 2

#define MAX_END_TRACKS 6

#define MAX_SAFETY_SLOTS 16

// Team indicators
#define TEAM_INDICATOR_NAME "ZH2TeamIndicator"
#define TEAM_INDICATOR_UNKNOWN_STATE "spawn.unknown"
#define TEAM_INDICATOR_ALLY_STATE "spawn.ally"
#define TEAM_INDICATOR_ENEMY_STATE "spawn.enemy"
#define TEAM_INDICATOR_TID_BASE 5000

// Modifiers
#define MAX_SERVER_MODIFIERS 2

strict namespace Game
{
    internal enum WinningSpecieT : int
    {
        SPECIENONE,
        SPECIETIE,
        SPECIEHUMAN,
        SPECIEZOMBIE
    };

    internal enum EndReasonT : int
    {
        REASONNONE,
        REASONSPECIEWON,
        REASONHUMANLEFT,
        REASONZOMBIELEFT,
        REASONADMINENDED,
    };

    // Represents the way an infection was triggered, which changes the behaviour.
    internal enum InfectTypeT : int
    {
        INFECT_INITIAL,
        INFECT_REGULAR,
    };

    internal enum InfectSourceT : int
    {
        INFECTSOURCE_ADMIN,
        INFECTSOURCE_PLAYER,
        INFECTSOURCE_ROUND,
    };

    internal enum CureSourceT : int
    {
        CURESOURCE_ADMIN,
        CURESOURCE_ITEM,
    };

    enum ZombieAbilityTypeFlagsT : int
    {
        ABILITY_NONE,
        ABILITY_PUSH = 1 << 0,
        ABILITY_SPIT = 1 << 1,
    };

    // The available serverside modifiers the server can configure on players.
    // Note, this indirectly also specifies the index of the modifier when used in functions.
    internal enum ModifierTypeT : int
    {
        MODIFIERTYPE_KNOCKBACK,
        MODIFIERTYPE_DAMAGEFACTOR,
    };

    internal struct EndingTypeT
    {
        str WinMessagesTop[2],
            WinMessagesBottom[2],
            WinGraphics[2];

        int TrackCount;
        str Tracks[MAX_END_TRACKS];
    };

    struct TipCollectionContextT
    {
        str Collection[MAX_TIPS];
        int Count;
    };

    internal struct ServerModifierT
    {
        bool Enabled;
        fixed Factor;
    };

    internal struct ZombieTeleportContextT
    {
        // Initial zombie teleport spots have tid 0, but we need these to get an actual tid to work properly.
        // This variable tracks that tid.
        int InitialZombieTeleportSpawnSpotTid;

        int ZombieTeleportSpots[MAX_ZOMBIETELEPORTSPOTS];
        int ZombieTeleportSpotCount;

        // The current tid of the zombie teleport spot(s) to use.
        int CurrentZombieTeleportSpotTid;

        // Indicates if zombie teleporting is enabled.
        bool ZombieTeleportingEnabled;

        // Indicated from lump reading if we manually enabled/disabled zombie teleports rather than having it work automatically.
        bool LumpReadSetZombieTeleportingEnabledSet;
        bool LumpReadSetZombieTeleportingEnabled;

        // Sets the overridden value specifying the maximum number of allowed zombie teleports.
        // If unset, `sv_zh2_maxzombieteleports` is used instead.
        bool OverrideMaxZombieTeleportsSet;
        int OverrideMaxZombieTeleportsCount;
    };

    internal struct PlayerZombieTeleportContextT
    {
        int ZombieTeleportsUsed;
    };

    internal struct SafeContextT
    {
        SafeSlotContextT Slots[MAX_SAFETY_SLOTS];
    };

    internal struct SafeSlotContextT
    {
        // Synched.
        // If a slot is hidden, it won't visually broadcast through the obituary system, or the HUD.
        bool Hidden;
    };

    internal struct PlayerSafeContextT
    {
        PlayerSafeSlotContextT Slots[MAX_SAFETY_SLOTS];
    };

    internal struct PlayerSafeSlotContextT
    {
        // Safe is synched. Indicates if a player reached the safezone.
        // FirstTimeSafe is serverside and indicates if the player has reached safety before.
        bool Safe;
        bool FirstTimeSafe;
    };

    extern void KillUnsafePlayers(int slot = 0);

    extern void SetIsSafe(bool safe, int slot = 0);
    extern void SetPlayerIsSafe(int id, bool safe, int slot = 0, bool broadcast = true);
    extern bool GetIsSafe(int slot = 0);
    extern bool GetPlayerIsSafe(int id, int slot = 0);

    extern void SetAllPlayersSafe(bool safe, int slot = 0, bool broadcast = true);
    extern void SetAllHumansSafe(bool safe, int slot = 0, bool broadcast = true);
    extern void SetAllZombiesSafe(bool safe, int slot = 0, bool broadcast = true);

    extern int HumanCount(bool includeDead = false);
    extern int ZombieCount(bool includeDead = false);

    extern void SetCurrentZombieTeleportSpotTid(int tid);
    extern int GetCurrentZombieTeleportSpotTid();
    extern void SetZombieTeleportingEnabled(bool enabled);
    extern bool GetZombieTeleportingEnabled();
    extern int GetInitialZombieTeleportSpotTid();
    extern void SetOverrideMaxZombieTeleports(int value);
    extern void UnsetOverrideMaxZombieTeleports();
    extern int GetMaxZombieTeleports();
}