#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    // Note these hardcode to always return 200 in case the value is unset.
    // Should never happen, but at least it prevents questionable deaths on infect which makes it clear it's unconfigured.
    internal int GetInitialZombieMaxHealth() { return GetZombieHealthOrDefault(ZH2Game::GameContext.InitialZombieMaxHealth); }
    internal int GetInitialZombieMinHealth() { return GetZombieHealthOrDefault(ZH2Game::GameContext.InitialZombieMinHealth); }
    internal int GetRegularZombieMaxHealth() { return GetZombieHealthOrDefault(ZH2Game::GameContext.RegularZombieMaxHealth); }
    internal int GetRegularZombieMinHealth() { return GetZombieHealthOrDefault(ZH2Game::GameContext.RegularZombieMinHealth); }
    internal int GetZombieHealthOrDefault(int health)
    {
        return health != 0 ? health : 200;
    }

    internal void SetZombieHealthValues(bool initial, int max, int min)
    {
        if (initial)
        {
            ZH2Game::GameContext.InitialZombieMaxHealth = max;
            ZH2Game::GameContext.InitialZombieMinHealth = min;
        }
        else
        {
            ZH2Game::GameContext.RegularZombieMaxHealth = max;
            ZH2Game::GameContext.RegularZombieMinHealth = min;
        }
    }

    // Determines what health to provide to the given player if they were to become a initial zombie.
    internal int DetermineHealthToGivePlayerInitialZombie(int id)
    {
        int max = GetInitialZombieMaxHealth();
        int min = GetInitialZombieMinHealth();
        return DetermineHealthCore(id, min, max);
    }

    // Determines what health to provide to the given player if they were to become a regular zombie.
    internal int DetermineHealthToGivePlayerRegularZombie(int id)
    {
        int max = GetRegularZombieMaxHealth();
        int min = GetRegularZombieMinHealth();
        return DetermineHealthCore(id, min, max);
    }

    internal int DetermineHealthCore(int id, int min, int max)
    {
        fixed ratio = GetPlayerHPFactor(id);
        printbold(f:ratio);
        return min + int(ratio * fixed(max - min));
    }

    internal fixed GetPlayerHPFactor(int id)
    {
        int tid = Identity::GetTid(id);
        printbold(d:BCSUtils::GetActorHealth(tid), s:", ", d:BCSUtils::GetActorSpawnHealth(tid));
        return BCSUtils::Clamp(
            fixed(BCSUtils::GetActorHealth(tid)) / fixed(BCSUtils::GetActorSpawnHealth(tid)), 0.0, 1.0);
    }
}
