#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    internal int GetGameStartTic()
    {
        return ZH2Game::GameContext.MatchStartTic;
    }

    internal void SetGameStartTicNow()
    {
        SetGameStartTic(Utils::GetSynchronizedTimer());
    }

    internal void SetGameStartTic(int tic)
    {
        ZH2Game::GameContext.MatchStartTic = tic;
    }

    internal int GetGameEndingTic()
    {
        return ZH2Game::GameContext.MatchEndingTic;
    }

    internal void SetGameEndingTicNow()
    {
        SetGameEndingTic(Utils::GetSynchronizedTimer());
    }

    internal void SetGameEndingTic(int tic)
    {
        ZH2Game::GameContext.MatchEndingTic = tic;
    }

    internal int GetGameVotingTic()
    {
        return ZH2Game::GameContext.MatchVotingTic;
    }

    internal void SetGameVotingTicNow()
    {
        SetGameVotingTic(Utils::GetSynchronizedTimer());
    }

    internal void SetGameVotingTic(int tic)
    {
        ZH2Game::GameContext.MatchVotingTic = tic;
    }

    internal int GetPlayTime()
    {
        int start = GetGameStartTic();
        int end = GetGameEndingTic();

        // Tic was not set.
        if (start == 0)
            return 0;

        // If the ending tic is set, we must return the diff between that and the start tic.
        // Otherwise the match is ongoing and we diff the current timer tic.
        if (end != 0)
            return end - start;

        return Utils::GetSynchronizedTimer() - start;
    }
}
