#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    void SetIsSafe(bool safe, int slot = 0) { SetPlayerIsSafe(PlayerNumber(), safe, slot); }
    script "zh2_script_setissafe" (raw slot) { SetPlayerIsSafe(PlayerNumber(), LineSide() == LINE_FRONT, slot); }

    void SetPlayerIsSafe(int id, bool safe, int slot = 0, bool broadcast = true)
    {
        if (!Identity::IsValidID(id))
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": player id " + str(id) + " is not valid.");
            return;
        }

        if (slot < 0 || slot >= MAX_SAFETY_SLOTS)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": slot " + str(slot) + " is not valid.");
            return;
        }

        ZH2Game::GameContext.Players[id].SafeContext.Slots[slot].Safe = safe;
        Logger::LogDebug(LOGSOURCE, BCSUTILS::PlayerName(id) + " (\cd" + str(id) + "\cj) \cd" + (safe ? "entered" : "left") + "\cj safe zone with slot \cd" + str(slot) + "\cj.");

        bool firstTime = safe && !ZH2Game::GameContext.Players[id].SafeContext.Slots[slot].FirstTimeSafe;
        if (safe)
            ZH2Game::GameContext.Players[id].SafeContext.Slots[slot].FirstTimeSafe = true;

        Event::SendPlayerSafe(id, safe, slot, firstTime);

        if (broadcast)
            Sync::SyncPlayers();
    }

    void SetAllPlayersSafe(bool safe, int slot = 0, bool broadcast = true)
    {
        SetAllHumansSafe(safe, slot, false);
        SetAllZombiesSafe(safe, slot, false);

        if (broadcast)
            Sync::SyncPlayers();
    }

    void SetAllHumansSafe(bool safe, int slot = 0, bool broadcast = true) { SetAllSpeciesSafe(Player::SPECIEHUMAN, safe, slot, broadcast); }
    void SetAllZombiesSafe(bool safe, int slot = 0, bool broadcast = true) { SetAllSpeciesSafe(Player::SPECIEZOMBIE, safe, slot, broadcast); }

    internal void SetAllSpeciesSafe(Player::PlayerSpecieT specie, bool safe, int slot = 0, bool broadcast = true)
    {
        for (int i = 0; i < BCSUTILS::MAX_PLAYERS; i++)
        {
            if (!PlayerInGame(i))
                continue;

            int tid = Identity::GetTID(i);
            if (!BCSUTILS::ActorIsAlive(tid))
                continue;

            if (Player::GetPlayerSpecie(i) != specie)
                continue;

            SetPlayerIsSafe(i, safe, slot, false);
        }

        if (broadcast)
            Sync::SyncPlayers();
    }

    bool GetIsSafe(int slot = 0) { return GetPlayerIsSafe(PlayerNumber(), slot); }
    bool GetPlayerIsSafe(int id, int slot = 0)
    {
        if (!Identity::IsValidID(id))
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": player id " + str(id) + " is not valid.");
            return false;
        }

        if (slot < 0 || slot >= MAX_SAFETY_SLOTS)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": slot " + str(slot) + " is not valid.");
            return false;
        }

        return ZH2Game::GameContext.Players[id].SafeContext.Slots[slot].Safe;
    }

    internal void SetSafeHidden(bool hidden, int slot = 0, bool broadcast = true)
    {
        if (slot < 0 || slot >= MAX_SAFETY_SLOTS)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": slot " + str(slot) + " is not valid.");
            return;
        }

        ZH2Game::GameContext.SafeContext.Slots[slot].Hidden = hidden;
        Logger::LogDebug(LOGSOURCE, "Safe slot \cd" + str(slot) + "\cj is now \cd" + (hidden ? "hidden" : "visible") + "\cj.");

        if (broadcast)
            Sync::SyncPlayers();
    }

    internal bool GetSafeHidden(int slot = 0)
    {
        if (slot < 0 || slot >= MAX_SAFETY_SLOTS)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": slot " + str(slot) + " is not valid.");
            return false;
        }

        return ZH2Game::GameContext.SafeContext.Slots[slot].Hidden;
    }
}