#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define REQUIREDGAMEMODE "cooperative"

/* EVENTS */

#define EVENTROUNDSWITCHED "roundswitched"

#define EVENTTIMERSWITCHED "timerswitched"
#define EVENTTIMERSTARTED "timerstarted"
#define EVENTTIMERPAUSED "timerresumed"
#define EVENTTIMERRESUMED "timerpaused"
#define EVENTTIMERSTOPPED "timerstopped"
#define EVENTTIMERELAPSED "timerelapsed"

#define EVENTRESISTSTARTED "resiststarted"
#define EVENTRESISTSTOPPED "resiststopped"
#define EVENTRESISTELAPSED "resistelapsed"

#define EVENTPLAYERDIED "playerdied"

// Note, not for general leaving. Specific to when a player leaves a playing round.
#define EVENTPLAYERLEFTROUND "playerleftround"

#define EVENTCURED "playercured"
#define EVENTINFECTED "playerinfected"
#define EVENTSCRATCHED "playerscratched"

// Build in tracks
#define TRACK_FULLSERVER "D_FULLSR"

/* GAME */
#define ACTOR_INITIALSPAWNSPOT_NAME "InitialSpawnSpot"
#define ACTOR_ZOMBIETELEPORTSPOT_NAME "ZombieTeleportSpot"

/* WEAPONS */
#define WEAPON_NOTHINGWEAPON_NAME "ZH2NothingWeapon"
#define WEAPON_CHAINGUN_NAME "ZH2WeaponChaingun"
#define WEAPON_CLAWS_NAME "ZH2WeaponClaws"
#define WEAPON_DOUBLESHOTGUN_NAME "ZH2WeaponDoubleShotgun"
#define WEAPON_FIREGRENADE_NAME "ZH2WeaponFireGrenade"
#define WEAPON_HANDGUN_NAME "ZH2WeaponHandgun"
#define WEAPON_JACKSGUN_NAME "ZH2WeaponJacksGun"
#define WEAPON_SHOTGUN_NAME "ZH2WeaponShotgun"
#define WEAPON_SNIPER_NAME "ZH2WeaponSniper"
#define WEAPON_RADIO_NAME "ZH2WeaponRadio"

#define WEAPON_FIREGRENADE_SPAWN_NAME "ZH2WeaponFireGrenadeSpawn"
#define WEAPON_JACKSGUN_SPAWN_NAME "ZH2WeaponJacksGunSpawn"

#define WEAPON_AMMO_DOUBLESHOTGUN_NAME "ZH2WeaponDoubleShotgunShell"
#define WEAPON_AMMO_FIREGRENADE_NAME "ZH2WeaponFireGrenadeAmmo"
#define WEAPON_AMMO_JACKSGUN_NAME "ZH2WeaponJacksGunAmmo"
#define WEAPON_AMMO_SHOTGUN_NAME "ZH2WeaponShotgunAmmo"

#define WEAPON_CHAINGUN_HEAT_NAME "ZH2Chaingunheat"
#define WEAPON_FIREGRENADE_THROWPOWER_NAME "ZH2WeaponFireGrenadeThrowPower"
#define WEAPON_JACKSGUN_SMOKE_COUNT_NAME "ZH2WeaponJacksGunSmokeCount"
#define WEAPON_SNIPER_SHOULDEJECTCASE_NAME "ZH2WeaponSniperShouldEjectCase"
#define WEAPON_SNIPER_ZOOM_LEVEL_NAME "ZH2WeaponSniperZoomlevel"
#define WEAPON_SNIPER_IS_ZOOMED_NAME "ZH2WeaponSniperIsZoomed"

/* LIMITS */
#define WEAPON_CHAINGUN_MAX_HEAT 50
#define WEAPON_FIREGRENADE_MAX_THROWPOWER 100
#define WEAPON_BLOCK_FIRING_ITEM "ZH2BlockWeaponFiring"

/* HUD SIZINGS */
#define WEAPON_CHAINGUN_METER_WIDTH 70
#define WEAPON_CHAINGUN_METER_HEIGHT 29

#define WEAPON_FIREGRENADE_METER_WIDTH 50
#define WEAPON_FIREGRENADE_METER_HEIGHT 39

// Note the zombie graphics vary in size so this is not exact
#define HUD_ZOMBIEABILITY_METER_WIDTH 91
#define HUD_ZOMBIEABILITY_METER_HEIGHT 50

/* CLASSES */
#define CLASS_INVISIBLE "InvisiblePlayer"
#define CLASS_HUMAN "HumanPlayer"
#define CLASS_ZOMBIE "ZombiePlayer"

/* PLAYER SKINS */
#define SKIN_HUMAN "Default"
#define SKIN_HUMAN_GRENADE "Grenade"
#define SKIN_HUMAN_HANDGUN "Handgun"
#define SKIN_HUMAN_JACKSGUN "Jacksgun"
#define SKIN_HUMAN_SHOTGUN "Shotgun"
#define SKIN_HUMAN_DOUBLEBARRELEDSHOTGUN "Doubleshotgun"
#define SKIN_HUMAN_CHAINGUN "Chaingun"
#define SKIN_HUMAN_SNIPER "Sniperrifle"
#define SKIN_HUMAN_RADIO "Radio"
#define SKIN_ZOMBIEOLD "ZombieOld"
#define SKIN_ZOMBIEREGULAR "ZombieRegular"
#define SKIN_ZOMBIEINITIAL "ZombieInitial"

/* WEAPON HUD SKINS */
#define WEAPON_HUD_SKIN_SHOTGUN "HUDSHOT"
#define WEAPON_HUD_SKIN_SUPERSHOTGUN "HUDSSG"
#define WEAPON_HUD_SKIN_SNIPER "HUDSNIP"
#define WEAPON_HUD_SKIN_JACKS "HUDJACK"
#define WEAPON_HUD_SKIN_PISTOL "HUDPIST"

#define WEAPON_HUD_SKIN_FIREGRENADE "HUDGREN1"
#define WEAPON_HUD_SKIN_FIREGRENADE_METER "HUDGREN2"

#define WEAPON_HUD_SKIN_CHAINGUN "HUDCHAN1"
#define WEAPON_HUD_SKIN_CHAINGUN_METER "HUDCHAN2"

/* PLAYER HUD SKINS */
#define PLAYER_HUD_SKIN_CHAINGUN "HUD_SCHA"
#define PLAYER_HUD_SKIN_DOUBLESHOTGUN "HUD_SDBS"
#define PLAYER_HUD_SKIN_FIREGRENADE "HUD_SGRN"
#define PLAYER_HUD_SKIN_JACKSGUN "HUD_SJCK"
#define PLAYER_HUD_SKIN_HANDGUN "HUD_SPIS"
#define PLAYER_HUD_SKIN_SHOTGUN "HUD_SSHT"
#define PLAYER_HUD_SKIN_SNIPER "HUD_SSNP"
#define PLAYER_HUD_SKIN_OLDZOMBIE "HUD_SZMO"
#define PLAYER_HUD_SKIN_INITIALZOMBIE "HUD_SZMI"
#define PLAYER_HUD_SKIN_REGULARZOMBIE "HUD_SZMR"
#define PLAYER_HUD_SKIN_RADIO PLAYER_HUD_SKIN_HUMAN
#define PLAYER_HUD_SKIN_HUMAN "HUD_HUMN"
#define PLAYER_HUD_SKIN_ZOMBIE PLAYER_HUD_SKIN_OLDZOMBIE

/* ITEMS */
#define KEVLAR_ITEM "ZH2ItemKevlar"
#define LEAPSTONE_ITEM "ZH2ItemLeapstone"
#define CURE_ITEM "ZH2ItemCure"
#define CRYSTAL_ITEM "ZH2ItemFireCrystal"
#define HOLYCROSS_ITEM "ZH2ItemHolyCross"
#define SYRINGE_ITEM "ZH2ItemSyringe"
#define KEVLAR_ARMOR_ITEM "ZH2KevlarArmor"
#define ENERGY_ITEM "ZH2ItemEnergy"
#define FLARE_ITEM "ZH2ItemFlare"
#define FLAREBOX_ITEM "ZH2ItemFlareBox"
#define MEDIKIT_ITEM "ZH2ItemMedikit"

#define MEDIKITHEALTH_ITEM "ZH2MedikitHealth"

/* KEYS */
#define KEY_BLOODRUBY_NAME "ZH2LegacyBloodruby"
#define KEY_NIGHTSAPPHIRE_NAME "ZH2LegacyNightSapphire"
#define KEY_BLUE_KEYCARD "ZH2BlueKeycard"
#define KEY_RED_KEYCARD "ZH2RedKeycard"
#define KEY_YELLOW_KEYCARD "ZH2YellowKeycard"
#define KEY_BLUE_SKULL "ZH2BlueSkullKey"
#define KEY_RED_SKULL "ZH2RedSkullKey"
#define KEY_YELLOW_SKULL "ZH2YellowSkullKey"
#define KEY_BATTERY "ZH2LegacyZe19Battery"
#define KEY_CROWBAR "ZH2LegacyZe27Crowbar"

/* CURRENCIES */
#define CURRENCY_CASH_NAME "ZH2LegacyCash"

/* MECHANICS */
#define SPRINT_ITEM "ZH2SprintEnergy"
#define ZOMBIE_TELEPORT_TIMESTAMP_ITEM "ZH2ZombieTeleportTimestamp"
#define ITEM_PLAYERPICKTIMESTAMP "ZH2PlayerPickTimestamp"
#define ZOMBIEABILITY_DO_ABILITY_ITEM "ZH2DoZombieAbilityIndex"
#define ZOMBIEABILITY_TIMESTAMP_BASE "ZH2ZombieAbility{0}Timestamp"
#define POWER_ACTOR_BASE "ZH2Power{0}TimeStamp"

#define SPRINT_ITEM_MAX 1000

/* EFFECTS */
#define HUMAN_BULLETPUFF "ZH2WeaponBulletPuff"

/* DAMAGE TYPES */
#define DAMAGETYPE_ZOMBIESCRATCH_NAME "ZH2ZombieScratch"
#define DAMAGETYPE_ZOMBIEPUSH_NAME "ZH2ZombiePush"
#define DAMAGETYPE_HUMANDEFAULT_NAME "ZH2HumanDefault"
#define DAMAGETYPE_SETONFIRE_NAME "ZH2SetOnFire" // Similar to Zombie Horde 1's FireG damagetype.

/* OTHER STATS */
#define HEALTH_HUMANDANGEROUS 20
#define HEALTH_HUMANCRITICAL 10

#define HEALTH_ZOMBIEDANGEROUS 800
#define HEALTH_ZOMBIECRITICAL 300

#define MAX_AIRSUPPLY 35 * 20

/* DEATH CAM */
#define DEATH_CAM_TID 45000
#define DEATH_CAM_DISTANCE 128.0