#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Note, included from zh2lib.
#include "validation.acs"

#include "game/game.acs"
#include "sync/sync.acs"
#include "map/map.acs"
#include "events/events.acs"
#include "round/round.acs"
#include "roundtimer/roundtimer.acs"
#include "player/player.acs"
#include "gameloop/gameloop.acs"
#include "settings/settings.acs"
#include "shuffle/shuffle.acs"
#include "music/music.acs"
#include "reward/reward.acs"
#include "weight/weight.acs"
#include "obituary/obituary.acs"
#include "decorate/decorate.acs"
#include "resist/resist.acs"
#include "power/power.acs"
#include "item/item.acs"
#include "admin/admin.acs"
#include "hud/hud.acs"
#include "io/io.acs"

#define LOGSOURCE  "Main"

#include "cvars.acs"
#include "binds.acs"
#include "wait.acs"

strict namespace ZH2Game
{
    internal GameContextT GameContext;
    global PersistingGameContextT PERSISTINGGAMECONTEXTINDEX: PersistingGameContext;

    // This is used for joining players/bots to force them to a specific specie.
    // This is specifically used for the admin to add bots of specific species.
    // If not set, we default to humans.
    internal Player::PlayerSpecieT _forceSpecie;

    script "zh2_internal_open" open
    {
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_open\"");

        // Offline only as the connect event is only ran online.
        if (!IsNetworkGame())
        {
            GameLoop::StartServerPlayerLoopById(ConsolePlayerNumber());
            Utils::InitializeSynchronizedTimerForPlayer(ConsolePlayerNumber());
        }

        // Online we want to now start the player loop for all available players as those already in the server won't actually trigger the event.
        else
        {
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                if (!BCSUtils::PlayerIsConnected(i))
                    continue;

                GameLoop::StartServerPlayerLoopById(i);
                Utils::InitializeSynchronizedTimerForPlayer(i);
            }
        }

        // Verify gamemode.
        // The single tic delay is for the logger to pass to clients.
        if (BCSUtils::StrToLower(GetCurrentGameMode()) != REQUIREDGAMEMODE)
        {
            Logger::LogWarning(LOGSOURCE , "Zombie Horde was build for the " + REQUIREDGAMEMODE + " gamemode. Updating game type...");
            Delay(const: 1);
            if (!SetCurrentGameMode(REQUIREDGAMEMODE)) Logger::LogError(LOGSOURCE , "Failed to set the current gamemode to " + REQUIREDGAMEMODE + ".");
            terminate;
        }

        str awaiter = GetServersideAwaiter();
        Logger::LogDebug(LOGSOURCE , "Start awaiter \"" + awaiter + "\".");

        if (!ACS_NamedExecute(awaiter, 0))
        {
            Logger::LogError(LOGSOURCE , "Awaiter " + awaiter + " could not be started. Script failed to execute.");
            terminate;
        }

        // Note, these two parses should work concurrently and both rent a tokenizer for this.
        // Parse persisting data here.
        Logger::LogDebug(LOGSOURCE , "Start parsing persisting data (server).");
        LibIO::ParseLoggerDefServerside();
        IO::ParseModDefLumpsServerside();
        IO::ParseMapDefLumps();

        // Wait for the persisting data to be parsed.
        WAIT_FOR_SCRIPT_PARSE_PERSISTING_LOGGER_DEFS_SERVERSIDE();
        WAIT_FOR_SCRIPT_PARSE_PERSISTING_MOD_DEFS_SERVERSIDE();
        WAIT_FOR_SCRIPT_PARSE_PERSISTING_MAP_POSITION_DEFS();

        // Parse non-persisting data now.
        Logger::LogDebug(LOGSOURCE , "Start parsing non-persisting data (server).");
        IO::ParseCurrentMapLump();

        // Wait for the non-persisting data to be parsed.
        WAIT_FOR_SCRIPT_PARSE_CURRENT_MAP_DEFS();

        // Now the loop starts because we have loaded everything.
        GameLoop::StartServerLoop();

        // Set the current game mode if we have it set.
        str gameMode = Map::GetCurrentMapGameMode();
        if (((raw)gameMode) != 0 && gameMode != "")
        {
            Logger::LogDebug(LOGSOURCE , "Setting up serverside game mode: \cd" + gameMode + "\cj.");

            switch (BCSUtils::StrToLower(gameMode))
            {
                case "survival":
                    Event::SetSurvivalDefaultsServer();
                    Player::SetSurvivalDefaults();
                    Game::SetSurvivalDefaults();
                    Round::SetSurvivalDefaults();
                    RoundTimer::SetSurvivalDefaults();
                    break;

                case "escape":
                    Event::SetEscapeDefaultsServer();
                    Player::SetEscapeDefaults();
                    Game::SetEscapeDefaults();
                    Round::SetEscapeDefaults();
                    RoundTimer::SetEscapeDefaults();
                    break;

                default:
                    Logger::LogWarning(LOGSOURCE , "The given game mode profile does not exist: " + gamemode + ".");
                    break;
            }
        }
        else
        {
            Logger::LogDebug(LOGSOURCE , "Map has no game mode defined.");
        }

        // Set up the initial game state depending on if we have enough players or not.
        int availableClients = BCSUtils::ClientCount();
        int minimumRequiredClients = ZH2Game::GetMinimumClientCount();
        if (availableClients < minimumRequiredClients)
        {
            Round::SetKnownRoundState(Round::STATEPREGAME);
        }
        else
        {
            // Start the timer if defined.
            int index = RoundTimer::GetIndexOfKnownType(RoundTimer::TIMERCOUNTDOWN);
            if (RoundTimer::GetTimerDefined(index))
            {
                Round::SetKnownRoundState(Round::STATECOUNTDOWN);
                RoundTimer::SetActiveTimerByKnownType(RoundTimer::TIMERCOUNTDOWN);
                RoundTimer::StartTimer(index);
            }

            // Is not, we go to the state before the countdown and the map will have to start manually.
            else
            {
                Round::SetKnownRoundState(Round::STATESTARTING);
                Logger::LogDebug(LOGSOURCE , "Waiting for the map to start the game.");
            }
        }

        Sync::SyncRoundState();
        Sync::SyncTimers();
        Sync::SyncResists();

        // Required for the zombie abilities to be synched.
        Sync::SyncGame();

        // Resync admin list
        Sync::SyncAdmins();

        // After a moment, sync all players and allow them to sync themselves on enter.
        Delay(const: 5);

        ZH2Game::GameContext.SyncPlayerOnEnter = true;
        Sync::SyncPlayers();
    }

    script "zh2_internal_open_client" open clientside
    {
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_open_client\"");

        str awaiter = GetClientsideAwaiter();
        if (!ACS_NamedExecute(awaiter, 0))
        {
            Logger::LogError(LOGSOURCE , "Awaiter " + awaiter + " could not be started. Script failed to execute.");
            terminate;
        }

        Logger::LogDebug(LOGSOURCE , "Start parsing persisting data (client).");

        // Parse other persisting data here.
        LibIO::ParseFootstepDefsClientside();
        IO::ParseModDefLumpsClientside();
        if (IsNetworkGame())
        {
            LibIO::ParseLoggerDefClientside();
            IO::ParseMapDefLumps();
        }

        // Wait for the persisting data to be parsed.
        Logger::LogDebug(LOGSOURCE , "Start parsing non-persisting data (client).");
        WAIT_FOR_SCRIPT_PARSE_PERSISTING_FOOTSTEP_DEFS();
        WAIT_FOR_SCRIPT_PARSE_PERSISTING_MOD_DEFS_CLIENTSIDE();
        if (IsNetworkGame())
        {
            WAIT_FOR_SCRIPT_PARSE_PERSISTING_LOGGER_DEFS_CLIENTSIDE();
            WAIT_FOR_SCRIPT_PARSE_PERSISTING_MAP_POSITION_DEFS();
        }

        // Parse non-persisting data now.
        if (IsNetworkGame())
            IO::ParseCurrentMapLump();

        // Wait for the non-persisting data to be parsed.
        if (IsNetworkGame())
            WAIT_FOR_SCRIPT_PARSE_CURRENT_MAP_DEFS();

        // We now iterate the resulting list of items, splitting them into three separate collections which makes iterating them much easier.
        Item::ItemCollectionContextT global:PERSISTINGGAMECONTEXTINDEX& collection = ZH2Game::PersistingGameContext.ItemCollection;
        for (int i = 0; i < collection.Size; ++i)
        {
            Item::ItemTypeT type = collection.Collection[i].Type;
            if      (type == Item::TYPE_WEAPON)    collection.WeaponCollection[collection.WeaponCollectionSize++] = i;
            else if (type == Item::TYPE_INVENTORY) collection.InventoryCollection[collection.InventoryCollectionSize++] = i;
            else if (type == Item::TYPE_KEY)       collection.KeyCollection[collection.KeyCollectionSize++] = i;
        }

        // Set the current game mode if we have it set.
        str gameMode = Map::GetCurrentMapGameMode();
        if (((raw)gameMode) != 0 && gameMode != "")
        {
            Logger::LogDebug(LOGSOURCE , "Setting up clientside game mode: \cd" + gameMode + "\cj.");

            switch (BCSUtils::StrToLower(gameMode))
            {
                case "survival":
                    Event::SetSurvivalDefaultsClient();
                    Obituary::SetSurvivalDefaultsClient();
                    break;

                case "escape":
                    Event::SetEscapeDefaultsClient();
                    Obituary::SetEscapeDefaultsClient();
                    break;

                default:
                    Logger::LogWarning(LOGSOURCE , "The given game mode profile does not exist: " + gamemode + ".");
                    break;
            }
        }
        else
        {
            Logger::LogDebug(LOGSOURCE , "Map has no game mode defined.");
        }

        // Now the loop starts because we have loaded everything.
        GameLoop::StartClientPlayerLoopActivator();

        // Fully sync up the client.
        Sync::SynAllClientside();

        Settings::UpdateCurrentClientSettings();

        // Voting is active, so the client needs a mouse.
        // TODO: Move this when adding the sync callback system.
        if (Round::GetActiveKnownRoundState() == Round::STATEVOTING)
        {
            Hud::SetCursorEnabled(true);
            Player::LockMovement(true);
        }

        // Initialize team indicators for all existing players.
        // This does not have to run offline as the enter script works fine.
        if (IsNetworkGame())
        {
            for (int i = 0; i < BCSUtils::MAX_PLAYERS; ++i)
            {
                // Ignore self.
                if (ConsolePlayerNumber() == i)
                    continue;

                if (!PlayerInGame(i))
                    continue;

                int tid = Identity::GetTID(i);
                if (!BCSUTILS::ActorIsAlive(tid))
                    continue;

                Game::SpawnPlayerTeamIndicator(i);
            }
        }

        // Inform the client to play the current default music.
        Music::PlayDefaultMusic();

        // Everything below requires the client to be the activator.
        // TODO: Improve so this is not required.
        if (!SetActivatorToPlayer(ConsolePlayerNumber()))
            terminate;

        Settings::BroadcastClientConsolidateSettings(false);
    }

    script "zh2_internal_enter" enter
    {
        // Exclusive to bots who spawn from `addbot` and skip any sort of connect/open call.
        if (PlayerIsBot(PlayerNumber()))
            GameLoop::StartServerPlayerLoopById(PlayerNumber());

        if (!ACS_NamedExecuteAlways("zh2_internal_enter_respawn", 0))
            Logger::LogError(LOGSOURCE , "Failed to call general enter/respawn script for client serverside.");
    }

    script "zh2_internal_enter_client" enter clientside
    {
        if (!ACS_NamedExecuteAlways("zh2_internal_enter_respawn_clientside", 0))
            Logger::LogError(LOGSOURCE , "Failed to call general enter/respawn script for client clientside.");
    }

    script "zh2_internal_respawn" respawn
    {
        if (!ACS_NamedExecuteAlways("zh2_internal_enter_respawn", 0))
            Logger::LogError(LOGSOURCE , "Failed to call general enter/respawn script for client serverside.");
    }

    script "zh2_internal_respawn_client" respawn clientside
    {
        if (!ACS_NamedExecuteAlways("zh2_internal_enter_respawn_clientside", 0))
            Logger::LogError(LOGSOURCE , "Failed to call general enter/respawn script for client clientside.");
    }

    script "zh2_internal_unloading" unloading
    {
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_unloading\"");

        // Reset the default music, or the music will move to the next map.
        Music::SetDefaultMusic("");
    }

    script "zh2_internal_disconnect" (int id) disconnect
    {
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_disconnect\"");

        VALIDATE_ID_VALID_SCRIPT(id);
        int tid = Identity::GetTID(id);
        Identity::DisposeTID(tid);

        // If the player did not spectate then they left.
        // In that case we do not handle the logic.
        // Rather the `GAMEEVENT_PLAYERLEAVESSERVER` event will do this in the event handler script.
        if (!PlayerIsSpectator(id))
            terminate;

        // Player always plays the game, so no explicit check for a playing player exists here.

        // Only run if player was playing in the round.
        if (Player::GetPlayerState(id) == Player::STATEPLAYING)
        {
            int activeRoundIndex = Round::GetActiveRoundStateIndex();

            // The player left a playing round.
            if (Round::GetActiveKnownRoundState() == Round::STATEPLAYING)
            {
                Logger::LogDebug(LOGSOURCE , "Playing player has spectated: (\cd" + str(id) + "\cj)" + BCSUTILS::PlayerName(id) + ".");
                Player::SetPlayerState(id, Player::STATEGONE);
                Event::SendPlayerLeftRound(id);
            }

            // Check if the round was still joinable.
            // We must reset the player context then as somebody else can take it.
            else if (Round::GetRoundJoinable(activeRoundIndex))
            {
                Logger::LogDebug(LOGSOURCE , "Playing player has spectated (not a playing round): (\cd" + str(id) + "\cj)" + BCSUTILS::PlayerName(id) + ".");
                ResetPlayerContext(id);
            }

            Sync::SyncPlayers();
        }

        // Always reset the lib context of the player.
        ZH2Lib::ResetPlayerLibContext(id);
    }

    script "zh2_internal_disconnect_client" (int id) disconnect clientside
    {
        // Dispose team indicator unless we're the one that disconnected.
        if (id != ConsolePlayerNumber())
            Game::DisposePlayerTeamIndicator(id);
    }

    script "zh2_internal_death" death
    {
        int killedId = PlayerNumber();
        VALIDATE_ID_VALID_SCRIPT(killedId);

        // Skip this script if the player is not playing (state is likely dead already).
        // This will always happen when setting a player as a dead spectator.
        if (Player::GetPlayerState(killedId) != Player::STATEPLAYING)
            terminate;

        // Get the killer.
        int killerId = -1;
        if (SetActivatorToTarget(0))
            killerId = PlayerNumber();

        // The round is not joinable, so the player has to be removed from their body.
        if (!Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()))
        {
            // Build message, but don't mention they can join next map if they are allowed to always join.
            str message = "You are dead.";
            if (!AllowPlayerJoin(PlayerNumber()))
                message += " You will be able to play again next map.";

            RemovePlayer(killedId, message);
        }

        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_death\" for player " + str(killedId) + " killed by player " + str(killerId) + ".");

        Event::SendPlayerDied(killedId, killerId);

        // Reset transient context if still in a joinable state.
        // Otherwise set as dead.
        if (Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()))
            ResetPlayerContext(killedId);
        else
            Player::SetPlayerState(killedId, Player::STATEDEAD);

        Sync::SyncPlayers();
    }

    script "zh2_internal_death_client" death clientside
    {
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_death_client\" for player " + str(PlayerNumber()) + ".");

        // Dispose team indicator unless we're the one that died.
        if (PlayerNumber() != ConsolePlayerNumber())
            Game::DisposeTeamIndicator();

        // Only run the rest on the dying client.
        if (ConsolePlayerNumber() != PlayerNumber())
            terminate;

        Settings::CloseClientSettingsMenu();
        Admin::DisableAdminHud();

        // Trigger a death cam when the round has started and the player dies.
        if (!Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()) && Player::GetPlayerState(PlayerNumber()) == Player::STATEPLAYING)
        {
            Game::InitializeClientDeathCamera();

            // Death cam needs a tic to initialize online, or it won't work.
            delay(const: 1);
            Game::StartClientDeathCamera();
        }
    }

    script "zh2_internal_event" (raw type, raw arg1, raw arg2) event
    {
        // This does not trigger offline so the OPEN script is used for that instead.
        // IsNetworkGame is therefore not needed, but added in case the behaviour does end up changing somehow.
        if (IsNetworkGame() && type == GAMEEVENT_PLAYERCONNECT)
        {
            Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_PLAYERCONNECT\cj.");

            VALIDATE_ID_VALID_SCRIPT((int)arg1);

            /*ZH2Lib::ResetPlayerLibContext(arg1);
            ResetPlayerPersistingContext(arg1);
            ResetPlayerContext(arg1);*/

            GameLoop::StartServerPlayerLoopById(arg1);
            Utils::InitializeSynchronizedTimerForPlayer(arg1);
            terminate;
        }

        // Damage to player without any armor affecting it.
        if (type == GAMEEVENT_ACTOR_DAMAGED_PREMOD)
        {
            // Disable damaging entirely if the round ended.
            if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
            {
                SetResultValue(0);
                terminate;
            }

            Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_ACTOR_DAMAGED_PREMOD\cj.");

            // Check for infect.
            int attackedId = PlayerNumber();
            VALIDATE_ID_VALID_SCRIPT(attackedId);

            // The attacked player is to be set on fire with this damagetype.
            if ((str)arg2 == DAMAGETYPE_SETONFIRE_NAME)
                Decorate::SetOnFire(-1, attackedId, 350, 200);

            // Everything below is for player on player contact.
            if (!SetActivator(0, AAPTR_DAMAGE_SOURCE)) terminate;

            // If -1, not a player.
            int attackerId = PlayerNumber();
            if (attackerId == -1)
                terminate;

            // Zombie attacked a human.
            if (Player::GetPlayerIsHuman(attackedId) && Player::GetPlayerIsZombie(attackerId))
            {
                // The damage type must be the type given by claws here, or it wasn't a scratch.
                // This fixes damage in general, and also prevents infinite loops (which happends when the human is immune).
                if ((str)arg2 == DAMAGETYPE_ZOMBIESCRATCH_NAME)
                {
                    Event::SendPlayerPreScratched(attackedId, attackerId);

                    // We always set the damage to 0.
                    SetResultValue(0);
                }

                // Alternatively, the zombie pushed the human with the barrel push ability.
                // To avoid complete annihilation of the human we want to set the damage to 0
                else if ((str)arg2 == DAMAGETYPE_ZOMBIEPUSH_NAME)
                    SetResultValue(0);
            }

            // Human attacked human
            if (Player::GetPlayerIsHuman(attackedId) && Player::GetPlayerIsHuman(attackerId))
            {
                // If we shot somebody, nullify the damage (telefragging is still possible).
                if ((str)arg2 == DAMAGETYPE_HUMANDEFAULT_NAME)
                    SetResultValue(0);
            }

            // Spawn blood on the attacked from the bulletpuff.
            if (!SetActivator(0, AAPTR_DAMAGE_INFLICTOR)) terminate;
            Decorate::SpawnBloodFromBulletPuff(attackerId, attackedId);
            terminate;
        }

        // Player fully left server.
        if (type == GAMEEVENT_PLAYERLEAVESSERVER)
        {
            Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_PLAYERLEAVESSERVER\cj.");

            VALIDATE_ID_VALID_SCRIPT((int)arg1);

            int activeRoundIndex = Round::GetActiveRoundStateIndex();

            // Only run if player was playing in the round.
            if (Player::GetPlayerState(arg1) == Player::STATEPLAYING)
            {
                // The round was being played. We must not reset the player context.
                // Otherwise another player can take the spot, so we clean up the context.
                if (!Round::GetRoundJoinable(activeRoundIndex))
                {
                    Logger::LogDebug(LOGSOURCE , "Playing player has disconnected: (\cd" + str((int)arg1) + "\cj)" + BCSUTILS::PlayerName((int)arg1) + ". Reason: \cd" + str((int)arg2) + "\cj.");
                    Player::SetPlayerState(arg1, Player::STATEGONE);

                    // Finally, if the round was the playing round, call the event.
                    if (Round::GetActiveKnownRoundState() == Round::STATEPLAYING)
                        Event::SendPlayerLeftRound(arg1);
                }
                else
                {
                    Logger::LogDebug(LOGSOURCE , "Playing player has disconnected (not a playing round): (\cd" + str((int)arg1) + "\cj)" + BCSUTILS::PlayerName((int)arg1) + ".");
                    ResetPlayerContext(arg1);
                }

                Sync::SyncPlayers();
            }

            // If we are currently voting, then we want to make sure this player no longer contributes to voting.
            if (Round::GetActiveKnownRoundState() == Round::STATEVOTING)
            {
                Map::SetPlayerVotedMapIndex(arg1, -1);
                Map::CheckMapVoteFinished();
                Sync::SyncMapVoting();
            }

            // The persisting context is always reset. This might still have data for the spectating player.
            // NOTE: This does not contain data required for anything specific. This should be revisited if it does.
            // We'd have to do this in unloading or something.
            ResetPlayerPersistingContext(arg1);

            // Always reset the lib context of the player.
            ZH2Lib::ResetPlayerLibContext(arg1);
            terminate;
        }

        // Track initial spawn spots and zombie teleport spots.
        // The arg must be 1 here, or we do something weird with random spawners which I won't support.
        if (type == GAMEEVENT_ACTOR_SPAWNED && arg1 == 1)
        {
            Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_ACTOR_SPAWNED\cj.");

            str class = GetActorClass(0);
            if (class == ACTOR_INITIALSPAWNSPOT_NAME) Game::TrackInitialSpawnSpot();
            else if (class == ACTOR_ZOMBIETELEPORTSPOT_NAME) Game::TrackZombieTeleportSpot();
        }

        if (type == GAMEEVENT_CHAT && arg1 != -1)
            SetResultValue((int)Game::HandlePlayerChatMessage(arg1, GetChatMessage(arg1, 0)));
    }

    script "zh2_internal_enter_respawn"
    {
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_enter_respawn\"");
        WAIT_FOR_SCRIPT_OPEN_SERVER();
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_enter_respawn\" after awaiter");

        // Forced player cap is enabled so the player will be kicked if we reached the limit.
        if (DevelopmentPlayerCap() && !PlayerIsBot(PlayerNumber()) && PlayerCount() - Utils::PlayingBotCount() > DEV_PLAYERCAP_COUNT)
        {
            RemovePlayer(PlayerNumber(), "This development build enforces a maximum player cap of " + str(DEV_PLAYERCAP_COUNT) + ". Please use a compatible, non-development version of Zombie Horde 2 to lift this limit.");
            terminate;
        }

        Identity::InitializeActivator();

        // The game is not in a state where players can join.
        // Depending on configuration we set the player as a dead spectator or kick them to spectate.
        // Should setting dead spectator fail then we fall back to using KickFromGame.
        if (!AllowPlayerJoin(PlayerNumber()) && !Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()))
        {
            RemovePlayer(PlayerNumber(), "You will join the next map.");
            terminate;
        }

        // Set specie, possibly forced to a specific specie.
        // SPECIENONE defaults to SPECIEHUMAN.
        if (_forceSpecie == Player::SPECIENONE)
            _forceSpecie = Player::SPECIEHUMAN;

        // TODO: Abstract into a repurposable functions
        if (_forceSpecie == Player::SPECIEHUMAN)
        {
            // Ensure all zombie weapons are taken.
            // This ensures that all weapons are correctly taken on this initial morph when the map changed.
            Player::TakeZombieWeapons();

            // TODO: Abstract into a repurposable function
            Player::MorphToHuman();
            Player::SetHumanTeam();
            Player::SetHumanSkin();
            Player::SetHuman();
            Player::GiveHumanInventory(true);
            Power::RecalculatePowers();

            // A 50% chance to get a fire grenade.
            // TODO: Replace with better distribution.
            if (BCSUtils::RandBool())
            {
                GiveInventory(WEAPON_FIREGRENADE_NAME, 1);
                GiveInventory(WEAPON_AMMO_FIREGRENADE_NAME, 1);
            }

            // Ensure we always start with the shotgun to avoid weird behaviour.
            SetWeapon(WEAPON_SHOTGUN_NAME);
        }
        else if (_forceSpecie == Player::SPECIEZOMBIE)
        {
            // Ensure all human weapons are taken.
            // This ensures that all weapons are correctly taken on this initial morph when the map changed.
            Player::TakeHumanWeapons();

            Player::MorphToZombie();
            Player::SetZombieTeam();
            Player::SetZombieSkin(SKIN_ZOMBIEOLD);
            Player::SetZombie();
            Player::GiveZombieInventory();
            Power::RecalculatePowers();
        }

        _forceSpecie = Player::SPECIENONE;

        Player::SetState(Player::STATEPLAYING);

        // Set initial name. The player's loop will then track possible changes.
        Player::SetName(BCSUtils::PlayerName(PlayerNumber()));

        // Should we sync this player?
        if (ZH2Game::GameContext.SyncPlayerOnEnter)
            Sync::SyncPlayers();

        // Set the player as an admin.
        // This is now removed and you can turn it on through the menu/rcon. Always works offline.
        // if (!Admin::GetIsAdmin())
        // {
        //     Admin::SetIsAdmin(true);
        //     Sync::SyncAdmins();
        // }
    }

    internal void RemovePlayer(int id, str message)
    {
        // Player is already a sort of spectator, so this function should not be called.
        if (PlayerIsSpectator(id) != 0)
        {
            Logger::LogWarning(LOGSOURCE , "Attempted to set " + str(id) + " as a spectator, but this player is already spectating.");
            return;
        }

        Logger::LogTo(id, message);

        if (GetUseDeadSpectators())
        {
            if (SetDeadSpectator(id, true))
                return;

            Logger::LogWarning(LOGSOURCE , "Failed to set " + str(id) + " as dead spectator. Falling back to KickFromGame.");
        }

        if (KickFromGame(id, message))
            return;

        Logger::LogError(LOGSOURCE , "Failed to set " + str(id) + " as spectator. KickFromGame failed.");
    }

    script "zh2_internal_enter_respawn_clientside" clientside
    {
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_enter_respawn_clientside\"");
        WAIT_FOR_SCRIPT_OPEN_CLIENT();
        Logger::LogDebug(LOGSOURCE , "Call script \"zh2_internal_enter_respawn_clientside\" after awaiter");

        // The game is not in a state where players can join.
        if (!Round::GetRoundJoinable(Round::GetActiveRoundStateIndex()))
            terminate;

        // Spawn a team indicator unless we're the one entering/respawning
        if (PlayerNumber() != ConsolePlayerNumber())
            Game::SpawnTeamIndicator();
    }

    // Returns `true` if the given player can join.
    // Checks for global, and player specific joining.
    internal bool AllowPlayerJoin(int id)
    {
        return GameContext.AlwaysAllowJoin || GameContext.Players[id].AlwaysAllowJoin;
    }

    // Note this is not always emptied in the game.
    // If the game is playing (and not in a joinable state), it will remain available until the map changes.
    internal void ResetPlayerContext(int id)
    {
        Logger::LogDebug(LOGSOURCE , "Resetting player context for player " + str(id) + ".");

        static PlayerT emptyPlayerDef;
        if (!Memcpy(GameContext.Players[id], emptyPlayerDef))
            Logger::LogError(LOGSOURCE , "Failed to empty player context for player " + str(id) + ".");
    }

    internal void ResetPlayerPersistingContext(int id)
    {
        Logger::LogDebug(LOGSOURCE , "Resetting persisting player context for player " + str(id) + ".");

        static PersistingPlayerT emptyPlayerDef;
        if (!Memcpy(PersistingGameContext.Players[id], emptyPlayerDef))
            Logger::LogError(LOGSOURCE , "Failed to empty persisting player context for player " + str(id) + ".");
    }
}

#undef LOGSOURCE