// A bunch of preprocessor definitions, used in the mod.

#define ITERATESPECIES(specieType, body) \
    for (int id = 0; id < BCSUtils::MAX_PLAYERS; ++id) \
    { \
        int tid = Identity::GetTid(id); \
        if (!PlayerInGame(id) || !BCSUtils::ActorIsAlive(tid)) continue; \
        if (specieType != Player::SPECIENONE && Player::GetPlayerSpecie(id) != specieType) continue; \
        body; \
    }