#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace ZH2Game
{
    script "zh2_internal_event" (raw type, raw arg1, raw arg2) event
    {
        switch(type)
        {
            case GAMEEVENT_PLAYERCONNECT: OnPlayerConnect(arg1); terminate;
            case GAMEEVENT_ACTOR_DAMAGED_PREMOD: SetResultValue(OnActorPreModifiedDamage(arg1, arg2)); terminate;
            case GAMEEVENT_PLAYERFRAGS: OnPlayerFragged(arg1, PlayerNumber()); terminate;
            case GAMEEVENT_PLAYERLEAVESSERVER: OnPlayerLeavesServer(arg1, arg2); terminate;
            case GAMEEVENT_ACTOR_SPAWNED: OnActorSpawned(arg1); terminate;
            case GAMEEVENT_CHAT: SetResultValue((int)OnChat(arg1)); terminate;
        }
    }

    internal void OnPlayerConnect(int id)
    {
        // This does not trigger offline so the OPEN script is used for that instead.
        // IsNetworkGame is therefore not needed, but added in case the behaviour does end up changing somehow.
        if (!IsNetworkGame())
            return;

        Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_PLAYERCONNECT\cj.");

        VALIDATE_ID_VALID_FUNCTION(id);

        /*ZH2Lib::ResetPlayerLibContext(id);
        ResetPlayerPersistingContext(id);
        ResetPlayerContext(id);*/

        GameLoop::StartServerPlayerLoopById(id);
        Utils::InitializeSynchronizedTimerForPlayer(id);
    }

    // Damage to player without any armor affecting it.
    internal int OnActorPreModifiedDamage(int damage, str damageType)
    {
        // Disable damaging entirely if the round ended.
        if (Round::GetActiveKnownRoundState() >= Round::STATEENDING)
            return 0;

        Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_ACTOR_DAMAGED_PREMOD\cj.");

        // Check for infect.
        int attackedId = PlayerNumber();
        VALIDATE_ID_VALID_FUNCTION_RETURN(attackedId, damage);

        // The attacked player is to be set on fire with this damagetype.
        if (damageType == DAMAGETYPE_SETONFIRE_NAME)
            Decorate::SetOnFire(-1, attackedId, 350, 200);

        // Everything below is for player on player contact.
        if (!SetActivator(0, AAPTR_DAMAGE_SOURCE))
            return damage;

        // If -1, not a player.
        int attackerId = PlayerNumber();
        if (attackerId == -1)
            return damage;

        // Zombie attacked a human.
        if (Player::GetPlayerIsHuman(attackedId) && Player::GetPlayerIsZombie(attackerId))
        {
            // The damage type must be the type given by claws here, or it wasn't a scratch.
            // This fixes damage in general, and also prevents infinite loops (which happends when the human is immune).
            if (damageType == DAMAGETYPE_ZOMBIESCRATCH_NAME)
            {
                Event::SendPlayerPreScratched(attackedId, attackerId);

                // We always set the damage to 0.
                return 0;
            }

            // Alternatively, the zombie pushed the human with the barrel push ability.
            // To avoid complete annihilation of the human we want to set the damage to 0
            else if (damageType == DAMAGETYPE_ZOMBIEPUSH_NAME)
            {
                return 0;
            }
        }

        // Human attacked human
        if (Player::GetPlayerIsHuman(attackedId) && Player::GetPlayerIsHuman(attackerId))
        {
            // If we shot somebody, nullify the damage (telefragging is still possible).
            if (damageType == DAMAGETYPE_HUMANDEFAULT_NAME)
                return 0;
        }

        // Spawn blood on the attacked from the bulletpuff.
        if (!SetActivator(0, AAPTR_DAMAGE_INFLICTOR))
            return damage;

        Decorate::SpawnBloodFromBulletPuff(attackerId, attackedId);
        return damage;
    }

    // Player frags another player.
    // This code does not have any extra checks unlike `death` as fragging should always be between two living players.
    internal void OnPlayerFragged(int killedId, int killerId)
    {
        Event::SendPlayerKilledByPlayer(killedId, killerId);
    }

    // Player fully left server.
    internal void OnPlayerLeavesServer(int id, int reason)
    {
        Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_PLAYERLEAVESSERVER\cj.");

        VALIDATE_ID_VALID_FUNCTION(id);

        int activeRoundIndex = Round::GetActiveRoundStateIndex();

        // Only run if player was playing in the round.
        if (Player::GetPlayerState(id) == Player::STATEPLAYING)
        {
            // The round was being played. We must not reset the player context.
            // Otherwise another player can take the spot, so we clean up the context.
            if (!Round::GetRoundJoinable(activeRoundIndex))
            {
                Logger::LogDebug(LOGSOURCE , "Playing player has disconnected: (\cd" + str(id) + "\cj)" + BCSUTILS::PlayerName(id) + ". Reason: \cd" + str(reason) + "\cj.");
                Player::SetPlayerState(id, Player::STATEGONE);

                // Finally, if the round was the playing round, call the event.
                if (Round::GetActiveKnownRoundState() == Round::STATEPLAYING)
                    Event::SendPlayerLeftRound(id);
            }
            else
            {
                Logger::LogDebug(LOGSOURCE , "Playing player has disconnected (not a playing round): (\cd" + str(id) + "\cj)" + BCSUTILS::PlayerName(id) + ".");
                ResetPlayerContext(id);
            }

            Sync::SyncPlayers();
        }

        // If we are currently voting, then we want to make sure this player no longer contributes to voting.
        if (Round::GetActiveKnownRoundState() == Round::STATEVOTING)
        {
            Map::SetPlayerVotedMapIndex(id, -1);
            Map::CheckMapVoteFinished();
            Sync::SyncMapVoting();
        }

        // The persisting context is always reset. This might still have data for the spectating player.
        // NOTE: This does not contain data required for anything specific. This should be revisited if it does.
        // We'd have to do this in unloading or something.
        ResetPlayerPersistingContext(id);

        // Always reset the lib context of the player.
        ZH2Lib::ResetPlayerLibContext(id);
    }

    // Track initial spawn spots and zombie teleport spots.
    internal void OnActorSpawned(int spawnBits)
    {
        // The spawnBits must be 1 here, or we do something weird with random spawners which I won't support.
        if (spawnBits != GAMEEVENT_SPAWN_LEVELSPAWNED)
            return;

        Logger::LogDebug(LOGSOURCE , "Call event \cdGAMEEVENT_ACTOR_SPAWNED\cj.");

        str class = GetActorClass(0);
        if (class == ACTOR_INITIALSPAWNSPOT_NAME) Game::TrackInitialSpawnSpot();
        else if (class == ACTOR_ZOMBIETELEPORTSPOT_NAME) Game::TrackZombieTeleportSpot();
    }

    internal bool OnChat(int id)
    {
        // Ignore if the server send the message.
        if (id == -1)
            return true;

        return Game::HandlePlayerChatMessage(id, GetChatMessage(id, 0));
    }
}