#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    #define DEATH_CAM_ACTOR "ZH2DeathCam"
    #define DEATH_CAM_TID 45000
    #define DEATH_CAM_DISTANCE 128.0
    #define DEATH_CAM_ZVEL 0.3
    #define DEATH_CAM_HOLD_TICS 105

    #define DEATH_CAM_MAX_HORIZONTAL_DISTANCE 250.0
    #define DEATH_CAM_MAX_VERTICAL_DISTANCE 50.0

    // Holds the player's death location.
    fixed playerDeathPosX = 0.0,
          playerDeathPosY = 0.0,
          playerDeathPosZ = 0.0;

    internal void ClientDeathCamTic()
    {
        if (!ClientDeathCameraEnabled())
            return;

        // Allow death cam cancellation by pressing `USE`.
        if (BCSUtils::KeyPressed(BT_USE))
        {
            DisposeClientDeathCamera();
            return;
        }
        
        // Automatically dispose of the death cam when too far away.
        fixed diffX = GetActorX(DEATH_CAM_TID) - playerDeathPosX,
              diffY = GetActorY(DEATH_CAM_TID) - playerDeathPosY,
              diffZ = GetActorZ(DEATH_CAM_TID) - playerDeathPosZ;

        fixed horizontalDistance = VectorLength(diffX, diffY);
        fixed verticalDistance = BCSUtils::Abs(diffZ);
        
        if (horizontalDistance > DEATH_CAM_MAX_HORIZONTAL_DISTANCE || verticalDistance > DEATH_CAM_MAX_VERTICAL_DISTANCE)
            DisposeClientDeathCamera();
    }

    internal void InitializeClientDeathCamera()
    {
        int tid = Identity::GetTid(ConsolePlayerNumber());
        playerDeathPosX = GetActorX(tid);
        playerDeathPosY = GetActorY(tid);
        playerDeathPosZ = GetActorZ(tid) + (fixed)GetActorProperty(tid, APROP_VIEWHEIGHT);

        fixed angle = GetActorAngle(tid);

        // Backwards offset based on angle
        fixed offsetX = cos(angle) * DEATH_CAM_DISTANCE,
              offsetY = sin(angle) * DEATH_CAM_DISTANCE;

        // Now get a spot that is moved backwards for the camera.
        fixed x = playerDeathPosX - offsetX;
        fixed y = playerDeathPosY - offsetY;

        SpawnForced(DEATH_CAM_ACTOR, x, y, playerDeathPosZ, DEATH_CAM_TID, (raw)(angle) >> 8);

        fixed forwardX = cos(angle),
              forwardY = sin(angle),
              rightX   = cos(angle + 0.25),
              rightY   = sin(angle + 0.25);

        // Final speed. Always backwards and left/right.
        fixed forwardSpeed = -Math::FRandom(0.4, 0.8),
              strafeSpeed  =  Math::FRandom(-0.3, 0.3);

        fixed velX = forwardX * forwardSpeed + rightX * strafeSpeed,
              velY = forwardY * forwardSpeed + rightY * strafeSpeed;

        SetActorVelocity(DEATH_CAM_TID, velX, velY, DEATH_CAM_ZVEL, false, false);
    }

    internal void StartClientDeathCamera()
    {
        ChangeCamera(DEATH_CAM_TID, (int)false, (int)false);
    }

    internal void DisposeClientDeathCamera()
    {
        ChangeCamera(0, (int)false, (int)false);
        Thing_Remove(DEATH_CAM_TID);

        playerDeathPosX = 0.0;
        playerDeathPosY = 0.0;
        playerDeathPosZ = 0.0;
    }

    // Can just check if the camera is spawned.
    internal bool ClientDeathCameraEnabled()
    {
        return ThingCountName(DEATH_CAM_ACTOR, DEATH_CAM_TID) > 0;
    }
}
