#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// The EndReason is the reason why a round would have ended.
// It hints to clients what would have happened for a round to end. For example, an admin could have ended it.

strict namespace Game
{
    // Preset data for the three endings.
    // TODO: Receive from lump so it can be edited.
    internal EndingTypeT _endingTypes[] =
    {
        {
            { "\ciMission failed!", "\ciFission mailed!" },
            { "\ckHow did you manage to do this?", "\ckWhat the...?!" },
            { "NWIN" },
            
            1,
            { "D_WINN" }
        },
        {
            { "\chHumans \cjwin!", "\chHumans \cjVictory!" },
            { "\cjHumanity is safe... for now!", "\cjDon't mess with humans, bro!" },
            { "HWIN_OLD", "HWIN_NEW" },
            
            4,
            { "D_WINH1", "D_WINH2", "D_WINH3", "D_WINH4" },
        },
        {
            { "\cgZombies \cjwin!", "\cgZombies \cjVictory!" },
            { "\cgBring bigger guns next time!", "\cgEarth is their new home now!" },
            { "ZWIN_OLD", "ZWIN_NEW" },

            6,
            { "D_WINZ1", "D_WINZ2", "D_WINZ3", "D_WINZ4", "D_WINZ5", "D_WINZ6" },
        },
    };

    // Called clientside to build up the ending screen.
    internal void ClientBuildEnding()
    {
        // Set a random top and bottom message.
        WinningSpecieT winningSpecie = Game::GetWinningSpecie();
        int index = (int)winningSpecie - 1;
        EndingTypeT& ending = _endingTypes[index];

        // The graphic needs a separate check for zombies as this one has two graphics.
        // TODO: This does not account for when the skin is overridden
        ZH2Game::GameContext.WinGraphic = winningSpecie == Game::SPECIETIE
            ? ending.WinGraphics[0]
            : ending.WinGraphics[(int)!Map::GetCurrentMapIsLegacyMap()];
        
        // Messages
        ZH2Game::GameContext.WinMessageTop = ending.WinMessagesTop[Random(0, lengthof(ending.WinMessagesTop) - 1)];
        ZH2Game::GameContext.WinMessageBottom = ending.WinMessagesBottom[Random(0, lengthof(ending.WinMessagesBottom) - 1)];

        // Play a track for the winning type.
        if (ending.TrackCount != 0)
        {
            int index = Random(0, ending.TrackCount - 1);
            str track = ending.Tracks[index];
            if (track != (raw)0 && track != "")
                Music::SetMusic(track);
        }

        // Set the ordered lists indicating the final stats.
        
        Shuffle::SortByHumanKills();
        ZH2Game::GameContext.HumanKillsOrderedCount = Shuffle::GetRelevantSize();
        for (int i = 0; i < ZH2Game::GameContext.HumanKillsOrderedCount; ++i)
            ZH2Game::GameContext.HumanKillsOrdered[i] = Shuffle::GetIndexValue(i);

        Shuffle::SortByZombieKills();
        ZH2Game::GameContext.ZombieKillsOrderedCount = Shuffle::GetRelevantSize();
        for (int i = 0; i < ZH2Game::GameContext.ZombieKillsOrderedCount; ++i)
            ZH2Game::GameContext.ZombieKillsOrdered[i] = Shuffle::GetIndexValue(i);

        Shuffle::SortByInfects();
        ZH2Game::GameContext.InfectsOrderedCount = Shuffle::GetRelevantSize();
        for (int i = 0; i < ZH2Game::GameContext.InfectsOrderedCount; ++i)
            ZH2Game::GameContext.InfectsOrdered[i] = Shuffle::GetIndexValue(i);

        Shuffle::ShuffleBySurvived();
        ZH2Game::GameContext.SurvivorsShuffledCount = Shuffle::GetRelevantSize();
        for (int i = 0; i < ZH2Game::GameContext.SurvivorsShuffledCount; ++i)
            ZH2Game::GameContext.SurvivorsShuffled[i] = Shuffle::GetIndexValue(i);

        Shuffle::ShuffleByHorde();
        ZH2Game::GameContext.HordeShuffledCount = Shuffle::GetRelevantSize();
        for (int i = 0; i < ZH2Game::GameContext.HordeShuffledCount; ++i)
            ZH2Game::GameContext.HordeShuffled[i] = Shuffle::GetIndexValue(i);

        Shuffle::ShuffleByDead();
        ZH2Game::GameContext.DeadShuffledCount = Shuffle::GetRelevantSize();
        for (int i = 0; i < ZH2Game::GameContext.DeadShuffledCount; ++i)
            ZH2Game::GameContext.DeadShuffled[i] = Shuffle::GetIndexValue(i);
    }

    internal void SetEndReason(EndReasonT reason)
    {
        ZH2Game::GameContext.EndReason = reason;
    }
    
    internal EndReasonT GetEndReason()
    {
        return ZH2Game::GameContext.EndReason;
    }

    internal EndReasonT GetEndReasonTypeByIndex(int index)
    {
        static EndReasonT collection[] = { REASONNONE, REASONSPECIEWON, REASONHUMANLEFT, REASONZOMBIELEFT, REASONADMINENDED, };
        return collection[index];
    }
}
