#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    // All of these items will be taken on infect.
    internal str _takeOnInfectItems[] = {
        WEAPON_CHAINGUN_HEAT_NAME, WEAPON_FIREGRENADE_THROWPOWER_NAME, WEAPON_JACKSGUN_SMOKE_COUNT_NAME,
        WEAPON_SNIPER_SHOULDEJECTCASE_NAME, WEAPON_SNIPER_ZOOM_LEVEL_NAME, WEAPON_SNIPER_IS_ZOOMED_NAME,
        WEAPON_SNIPER_BOLTING_NAME, WEAPON_SHOTGUN_MUST_PUMP_NAME, WEAPON_DOUBLESHOTGUN_EJECT_SHELLS_NAME,
    };

    internal void Infect(InfectTypeT type)
    {
        InfectPlayer(PlayerNumber(), type);
    }

    internal void Cure()
    {
        CurePlayer(PlayerNumber());
    }

    internal void CurePlayer(int id)
    {
        // Ensure all zombie weapons are taken.
        Player::TakePlayerZombieWeapons(id);

        Player::SetPlayerHuman(id);
        Player::MorphPlayerToHuman(id);
        Player::SetPlayerHumanTeam(id);
        Player::SetPlayerHumanSkin(id);
        Player::GivePlayerHumanInventory(id, false);

        // This not really needed if we take powers, because the recalculate is automatically called.
        //Power::RecalculatePlayerPowers(id);

        int tid = Identity::GetTID(id);
        if (!SpawnForced("CureEffect", GetActorX(tid), GetActorY(tid), GetActorZ(tid)))
            Logger::LogWarning(LOGSOURCE , "Failed to spawn cure effect for player " + str(id) + ".");

        Event::SendPlayerCured(id);
        Event::SendPlayerSpecieChanged(id, Player::SPECIEHUMAN);
    }

    internal void InfectPlayer(int infectedId, InfectTypeT type)
    {
        int tid = Identity::GetTID(infectedId);

        DropFireGrenade(tid, type);

        // Ensure all human weapons are taken.
        Player::TakePlayerHumanWeapons(infectedId);

        // Determine skin.
        // When playing a legacy map or getting infected by an admin, always use old zombies.
        // Otherwise pick initial/subsequent based on the passed type.
        str skin = SKIN_ZOMBIEOLD;
        if (!Map::GetCurrentMapIsLegacyMap())
        {
            switch(type)
            {
                case INFECT_REGULAR:
                    skin = SKIN_ZOMBIEREGULAR;
                    break;
                case INFECT_INITIAL:
                    skin = SKIN_ZOMBIEINITIAL;
                    break;
            }
        }

        // Override skin behaviour
        switch (ZH2Game::GetZombieSkinBehaviour())
        {
            case ZH2Game::BEHAVIOUR_FORCEOLDSKIN:
                skin = SKIN_ZOMBIEOLD;
                break;
            case ZH2Game::BEHAVIOUR_FORCENEWSKIN:
                switch(type)
                {
                    case INFECT_REGULAR:
                        skin = SKIN_ZOMBIEREGULAR;
                        break;
                    case INFECT_INITIAL:
                        skin = SKIN_ZOMBIEINITIAL;
                        break;
                }
                break;
        }

        // Determine health to give based on current player health.
        // Zombie health is based on the player's health.
        int spawnHealth;
        int health;
        switch(type)
        {
            case INFECT_REGULAR:
                spawnHealth = Game::GetRegularZombieMaxHealth();
                health = Game::DetermineHealthToGivePlayerRegularZombie(infectedId);
                break;
            case INFECT_INITIAL:
                spawnHealth = Game::GetInitialZombieMaxHealth();
                health = Game::DetermineHealthToGivePlayerInitialZombie(infectedId);
                break;
            case INFECT_ADMIN:
                spawnHealth = 2000;
                health = 2000;
                break;
        }

        // Set up to be a zombie.
        Player::SetPlayerZombie(infectedId);
        Player::MorphPlayerToZombie(infectedId);
        Player::SetPlayerZombieTeam(infectedId);
        Player::SetPlayerZombieSkin(infectedId, skin);
        Player::GivePlayerZombieInventory(infectedId);
        Player::SetPlayerNextZombieTauntTic(infectedId);

        // Now also set health.
        BCSUtils::SetActorSpawnHealth(tid, spawnHealth);
        BCSUtils::SetActorHealth(tid, health);

        // Initials get abilities
        if (type == INFECT_INITIAL)
        {
            // Set the abilities to their defaults.
            SetPlayerZombieAbilityFlags(infectedId, GetDefaultZombieAbilityFlags());

            // Set a cooldown on all of the abilities
            if (ZH2Game::GetUseZombieAbilityCooldowns())
            {
                for (int i = 0; i < ABILITY_COUNT; ++i)
                    Game::GivePlayerZombieAbilityCooldownByIndex(infectedId, i);
            }
        }

        // Additional hardcoded items that must be taken, related to weaponry that otherwise causes weird behavior.
        foreach(str item; _takeOnInfectItems)
            BCSUtils::TakeMaxActorInventory(tid, item);

        if (!SpawnForced("ZH2InfectionFireEffect", GetActorX(tid), GetActorY(tid), GetActorZ(tid)))
            Logger::LogWarning(LOGSOURCE , "Failed to spawn infection effect for player " + str(infectedId) + ".");

        if (!PlayerIsBot(infectedId))
        {
            if (!NamedExecuteClientScript("zh2_internal_player_infected_client", infectedId))
                Logger::LogWarning(LOGSOURCE , "Clientside infect script failed for player " + str(infectedId) + ".");
        }

        PlaySound(tid, "zombie/WAKE", CHAN_AUTO);

        // Remove panic state
        Player::SetPlayerPanicState(infectedId, Player::PANICSTATENONE);

        Event::SendPlayerInfected(infectedId);
        Event::SendPlayerSpecieChanged(infectedId, Player::SPECIEZOMBIE);
    }

    // Drop fire grenade if the player owns one and is eligible to drop one depending on specie and configuration.
    internal void DropFireGrenade(int tid, InfectTypeT type)
    {
        if (CheckActorInventory(tid, WEAPON_AMMO_FIREGRENADE_NAME) == 0)
            return;

        // Never drop when infected by an admin.
        if (type == INFECT_ADMIN)
            return;

        ZH2Game::DropGrenadeOnInfectT dropBehaviour = ZH2Game::GetDropGrenadeOnInfect();

        if (dropBehaviour == ZH2Game::DROPBEHAVIOUR_NEVER)
            return;

        // Only regular zombies should drop a grenade.
        if (dropBehaviour == ZH2Game::DROPBEHAVIOUR_ONLY_REGULAR_ZOMBIES && type != INFECT_REGULAR)
            return;

        Spawn(WEAPON_FIREGRENADE_SPAWN_NAME, GetActorX(tid), GetActorY(tid), GetActorFloorZ(tid) + 8.0);
    }

    script "zh2_internal_player_infected_client" clientside
    {
        SetActivatorToPlayer(ConsolePlayerNumber());
        for(int i = 0; i < 10; ++i)
        {
            for (int j = 0; j < 6; ++j)
                Hud::DrawClientSeparateHudFire(Hud::FIRETYPEINFECT);

            Delay(const: 1);
        }
    }
}