#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    // Note, the activator of this function must be an initial zombie spawn spot.
    // It is assumed that this is the case when entering this function since it's checked beforehand.
    internal void TrackInitialSpawnSpot()
    {
        if (GetInitialSpawnSpotCount() == MAX_INITIALSPAWNSPOTS)
        {
            Logger::LogWarning(LOGSOURCE , "Unable to track initial zombie spawn spot: maximum number of trackable spots reached (" + str(MAX_INITIALSPAWNSPOTS) + ").");
            return;
        }

        int tid = UniqueTID();
        Thing_ChangeTID(0, tid);
        ZH2Game::GameContext.InitialSpawnSpots[ZH2Game::GameContext.InitialSpawnSpotCount++] = tid;
        Logger::LogDebug(LOGSOURCE , "Start tracking initial zombie spawn spot \cd" + str(tid) + "\cj, index \cd" + str(ZH2Game::GameContext.InitialSpawnSpotCount - 1) + "\cj.");
    }

    internal int GetInitialSpawnSpotCount()
    {
        return ZH2Game::GameContext.InitialSpawnSpotCount;
    }

    internal int GetInitialSpawnSpot(int index)
    {
        if (index < 0 || index > GetInitialSpawnSpotCount())
            return -1;

        return ZH2Game::GameContext.InitialSpawnSpots[index];
    }
}
