#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    internal void SetGameStartTicNow()
    {
        ZH2Game::GameContext.MatchStartTic = Utils::GetSynchronizedTimer();
    }

    internal void SetGameEndingTicNow()
    {
        ZH2Game::GameContext.MatchEndingTic = Utils::GetSynchronizedTimer();
    }

    internal int GetPlayTime()
    {
        // Tic was not set.
        if (ZH2Game::GameContext.MatchStartTic == 0)
            return 0;

        // If the ending tic is set, we must return the diff between that and the start tic.
        // Otherwise the match is ongoing and we diff the current timer tic.
        if (ZH2Game::GameContext.MatchEndingTic != 0)
            return ZH2Game::GameContext.MatchEndingTic - ZH2Game::GameContext.MatchStartTic;

        return Utils::GetSynchronizedTimer() - ZH2Game::GameContext.MatchStartTic;
    }
}
