#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    internal void UpdateScoreBoard(int id)
    {
        SetCustomPlayerValue(
            CUSTOMDATA_HUMANKILLS, id,
            Player::GetPlayerHumanKills(id));

        SetCustomPlayerValue(
            CUSTOMDATA_ZOMBIEKILLS, id,
            Player::GetPlayerZombieKills(id));

        SetCustomPlayerValue(
            CUSTOMDATA_INFECTS, id,
            Player::GetPlayerInfects(id));
    }
}
