#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Game
{
    internal void ChangeSpecieInventory(Player::PlayerSpecieT type, str item, int amount)
    {
        ITERATESPECIES(type, {
            if (amount > 0) GiveActorInventory(tid, item, amount);
            else            TakeActorInventory(tid, item, BCSUtils::Abs(amount));
        });
    }

    internal void GiveSpecieInventory(Player::PlayerSpecieT type, str item, int amount) { ChangeSpecieInventory(type, item, amount); }
    internal void GiveHumanInventory(str item, int amount)  { ChangeSpecieInventory(Player::SPECIEHUMAN, item, amount); }
    internal void GiveZombieInventory(str item, int amount) { ChangeSpecieInventory(Player::SPECIEZOMBIE, item, amount); }

    internal void TakeSpecieInventory(Player::PlayerSpecieT type, str item, int amount) { ChangeSpecieInventory(type, item, -amount); }
    internal void TakeHumanInventory(str item, int amount)  { ChangeSpecieInventory(Player::SPECIEHUMAN, item, -amount); }
    internal void TakeZombieInventory(str item, int amount) { ChangeSpecieInventory(Player::SPECIEZOMBIE, item, -amount); }
}