#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Identity"

strict namespace Identity
{
    void InitializeActivator()
    {
        int tid = PLAYER_TID_BASE + PlayerNumber();
        Logger::LogDebug(LOGSOURCE, "Assigning TID \cd" + str(tid) + "\cj to \cd" + BCSUtils::PlayerName(PlayerNumber()) + "\cj (id \cd" + str(PlayerNumber()) + "\cj).");
        Thing_ChangeTID(0, tid);
    }

    void DisposeTID(int tid)
    {
        Thing_ChangeTID(tid, 0);
    }

    bool IsValidTID(int tid)
    {
        int id = tid - PLAYER_TID_BASE;
        return id >= 0 && id < BCSUtils::MAX_PLAYERS;
    }

    bool IsValidID(int id)
    {
        return id >= 0 && id < BCSUtils::MAX_PLAYERS;
    }

    // Note, validation before and after this function is required. The mod contains various validation functions.
    int GetTID(int id)
    {
        return id + PLAYER_TID_BASE;
    }

    // Note, validation before and after this function is required. The mod contains various validation functions.
    int GetID(int tid)
    {
        return tid - PLAYER_TID_BASE;
    }
}

#undef LOGSOURCE 