#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Item
{
    #define MAX_ITEMS 80

    struct ItemCollectionContextT
    {
        ItemContextT Collection[MAX_ITEMS];
        int Size;
        
        // This is a predetermined collection of the different item types.
        // This is used for iteration so we don't need to hassle with if the current item fits the required type.
        // Each entry is the index of the relevant item.
        int WeaponCollection[MAX_ITEMS];
        int InventoryCollection[MAX_ITEMS];
        int KeyCollection[MAX_ITEMS];
        int WeaponCollectionSize;
        int InventoryCollectionSize;
        int KeyCollectionSize;
    };

    struct ItemContextT
    {
        str Name;
        ItemTypeT Type;
        bool HumanOwned;
        bool ZombieOwned;
        int GiveOnSpawnCount;
        int GiveOnHumanCount;
        int GiveOnZombieCount;
        bool TakeOnPanic;

        // Item specific (inventory/key)
        str Graphic;
        str Label;
        str Description;

        // Weapon specific
        int BloodSeverity;
		int BloodTics;
    };

    enum ItemTypeT : int
    {
        TYPE_NONE,
        TYPE_WEAPON,
        TYPE_INVENTORY,
        TYPE_KEY,
    };
}