#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Monster
{
    script "zh2_dec_zm18_kameleon_switchcolordelay" (void)
    {
        ACS_NamedExecute("zh2_dec_zm18_kameleon_switchcolor", 0, 0, 0, 0);
        delay(1);
        ACS_NamedExecute("zh2_dec_zm18_kameleon_switchcolor", 0, random(1, 8), 0, 0);
        delay(35*random(10, 20));
        ACS_NamedExecute("zh2_dec_zm18_kameleon_switchcolor", 0, 0, 0, 0);
        delay(1);
        ACS_NamedExecute("zh2_dec_zm18_kameleon_switchcolor", 0, random(1, 8), 0, 0);
        delay(35*random(20, 40));
        restart;
    }

    script "zh2_dec_zm18_kameleon_switchcolor" (int Typ)
    {
        if (Typ == 0) // White
        {
            CreateTranslation (10, 0:247=2:247);
            Thing_SetTranslation (0, 10);
        }
        if (Typ == 1) // White
        {
            CreateTranslation (1, 112:127=80:95);
            Thing_SetTranslation (0, 1);
        }
        if (Typ == 2) // Grey
        {
            CreateTranslation (2, 112:127=96:111);
            Thing_SetTranslation (0, 2);
        }
        if (Typ == 3) // Orange
        {
            CreateTranslation (3, 112:127=208:223);
            Thing_SetTranslation (0, 3);
        }
        if (Typ == 4) // Yellow
        {
            CreateTranslation (4, 112:124=160:166, 125:127=167:167);
            Thing_SetTranslation (0, 4);
        }
        if (Typ == 5) // Red
        {
            CreateTranslation (5, 112:127=176:191);
            Thing_SetTranslation (0, 5);
        }
        if (Typ == 6) // Indigo
        {
            CreateTranslation (6, 112:114=240:240, 115:124=241:246, 125:127=0:0);
            Thing_SetTranslation (0, 6);
        }
        if (Typ == 7) // Brown
        {
            CreateTranslation (7, 112:127=64:79);
            Thing_SetTranslation (0, 7);
        }
        if (Typ == 8) // Blue
        {
            CreateTranslation (8, 112:127=192:207);
            Thing_SetTranslation (0, 8);
        }
    }

    script "zh2_dec_zm18_kameleon_switchform" (void)
    {
        TakeInventory("ZH2LegacyZM18LabYouCanSeeMe", 1);
        delay(35*random(20, 40));
        GiveInventory("ZH2LegacyZM18LabYouCanSeeMe", 1);
        delay(35*random(20, 40));
        restart;
    }

    script "zh2_dec_zm18_kameleon_maybeteleport" (void)
    {
        switch (random(1, 20))
        {
            case 1:
                Thing_Move(0, random(90, 94), 0);
                break;
        }
    }

    script "zh2_dec_zm18_kameleon_teleport" (void)
    {
        Thing_Move(0, random(90, 94), 0);
    }
}
