#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Round
{
    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for round.");
        
        Round::DefineRoundByKnown(Round::STATEPREGAME, false, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, false, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, false, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, true, false);
        Round::DefineRoundByKnown(Round::STATEENDING, true, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, true, true);
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for round.");

        Round::DefineRoundByKnown(Round::STATEPREGAME, false, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, false, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, false, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, true, false);
        Round::DefineRoundByKnown(Round::STATEENDING, true, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, true, true);
    }

    internal bool GetCurrentRoundJoinable()
    {
        return GetRoundJoinable(GetActiveRoundStateIndex());
    }

    internal bool GetCurrentRoundIsEnding()
    {
        return GetRoundIsEnding(GetActiveRoundStateIndex());
    }

    bool GetGameIsPlaying()
    {
        return !GetCurrentRoundJoinable() && !GetCurrentRoundIsEnding();
    }

    bool GetGameIsPregameOrPlaying()
    {
        return !GetCurrentRoundIsEnding();
    }
}