#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Round
{
    // Used below
    internal bool GetCurrentRoundJoinable()
    {
        return GetRoundJoinable(GetActiveRoundStateIndex());
    }

    // Used below
    internal bool GetCurrentRoundIsEnding()
    {
        return GetRoundIsEnding(GetActiveRoundStateIndex());
    }

    /* Helper functions to check the state of the game */

    bool GetGameIsPregameOrPlaying()
    {
        return !GetCurrentRoundIsEnding();
    }

    bool GetGameIsPlaying()
    {
        return !GetCurrentRoundJoinable() && !GetCurrentRoundIsEnding();
    }

    bool GetGameIsEnding()
    {
        return GetCurrentRoundIsEnding();
    }
}