#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Round
{
    bool GetGameIsPregame()
    {
        return GetCurrentRoundJoinable();
    }

    bool GetGameIsPlaying()
    {
        return !GetCurrentRoundJoinable() && !GetCurrentRoundIsEnding();
    }

    bool GetGameIsEnding()
    {
        return GetCurrentRoundIsEnding();
    }

    internal bool GetCurrentRoundJoinable()
    {
        return GetRoundJoinable(GetActiveRoundStateIndex());
    }

    internal bool GetCurrentRoundIsEnding()
    {
        return GetRoundIsEnding(GetActiveRoundStateIndex());
    }
}