#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Round
{
    // Hardcoded limit on round states to avoid too many of them.
    // In the future I will support the ability to allocate these to allow for more, but this requires an extra library.
    #define MAX_ROUNDSTATES 20

    internal struct RoundStateContextT
    {
        // Set to `true` if we defined the round state index.
        bool defined;

        bool DenyJoin;
        bool IsEnding;
    };

    // A known round state is a round state that the mod has build in, which is different from a custom round state which does not.
    // The support is all the same, but this is easier for the mod because we can use this enum for clarity.
    enum KnownRoundStateT : int
    {
        STATENONE = 0,
        STATEPREGAME = 1,
        STATESTARTING = 2,
        STATECOUNTDOWN = 3,
        STATEPLAYING = 4,

        /* Room for custom round states */

        STATEENDING = 18,
        STATEVOTING = 19,
    };

    extern bool GetGameIsPlaying();
    extern bool GetMapIsActive();
}