#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#define LOGSOURCE "Round"

#include "extern.acs"
#include "state.acs"
#include "initialzombie.acs"

strict namespace Round
{
    internal void InitializeClient()
    {
        Logger::LogDebug(LOGSOURCE, "Initializing clientside.");

        EventBus::AddCallbackByScriptName(EVENT_DATA_SYNCED, "zh2_internal_event_rounddatasynced");
    }

    internal void SetSurvivalDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting survival gamemode profile for round.");

        Round::DefineRoundByKnown(Round::STATEPREGAME, false, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, false, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, false, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, true, false);
        Round::DefineRoundByKnown(Round::STATEENDING, true, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, true, true);
    }

    internal void SetEscapeDefaults()
    {
        Logger::LogDebug(LOGSOURCE, "Setting escape gamemode profile for round.");

        Round::DefineRoundByKnown(Round::STATEPREGAME, false, false);
        Round::DefineRoundByKnown(Round::STATESTARTING, false, false);
        Round::DefineRoundByKnown(Round::STATECOUNTDOWN, false, false);
        Round::DefineRoundByKnown(Round::STATEPLAYING, true, false);
        Round::DefineRoundByKnown(Round::STATEENDING, true, true);
        Round::DefineRoundByKnown(Round::STATEVOTING, true, true);
    }
}

#undef LOGSOURCE