#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hook
{
    #define HOOK_MAX 1

    // TODO: This should go into the core once the hook array doesn't rely on it for its size.
    enum HookTypeT
    {
        HOOK_DRAWHUD,
    };

    extern bool Register(HookTypeT type, int function(void[]*)& fn);
    extern void Unregister(HookTypeT type);
    extern void Call(HookTypeT type, void[]* data);
}