#ifdef __IMPORTED__
    #error This file must be #included.
#endif

strict namespace Hook
{
    #define HOOK_MAX 4

    // TODO: This should go into the core once the hook array doesn't rely on it for its size.
    enum HookTypeT
    {
        HOOK_CLIENTDRAWHUD,
        HOOK_CLIENTTIC,
        HOOK_SERVERTIC,
        HOOK_SERVERPLAYERTIC,
    };

    extern bool Register(HookTypeT type, raw function(void[]*)& fn);
    extern void Unregister(HookTypeT type);
    extern raw Call(HookTypeT type, void[]* data = null);
}