#ifdef __IMPORTED__
    #error This file must be #included.
#endif

/* PLAYER ID VALIDATION */

#define VALIDATE_ID_VALID_SCRIPT(id) \
    if (!Identity::IsValidID(id)) \
    { \
        Logger::LogWarning(LOGSOURCE, "Script \cd" + __SCRIPT__ + "\cj - Invalid player ID: " + str(id)); \
        terminate; \
    }

#define VALIDATE_ID_VALID_FUNCTION(id) \
    if (!Identity::IsValidID(id)) \
    { \
        Logger::LogWarning(LOGSOURCE, "Function \cd" + __FUNCTION__ + "\cj - Invalid player ID: " + str(id)); \
        return; \
    }

#define VALIDATE_ID_VALID_FUNCTION_RETURN(id, returnValue) \
    if (!Identity::IsValidID(id)) \
    { \
        Logger::LogWarning(LOGSOURCE, "Function \cd" + __FUNCTION__ + "\cj - Invalid player ID: " + str(id)); \
        return returnValue; \
    }


/* PLAYER TID VALIDATION */

#define VALIDATE_TID_VALID_SCRIPT(tid) \
    if (!Identity::IsValidTID(tid)) \
    { \
        Logger::LogWarning(LOGSOURCE, "Script \cd" + __SCRIPT__ + "\cj - Invalid player TID: " + str(tid)); \
        terminate; \
    }

#define VALIDATE_TID_VALID_FUNCTION(id) \
    if (!Identity::IsValidTID(tid)) \
    { \
        Logger::LogWarning(LOGSOURCE, "Function \cd" + __FUNCTION__ + "\cj - Invalid player TID: " + str(tid)); \
        return; \
    }

#define VALIDATE_TID_VALID_FUNCTION_RETURN(id, returnValue) \
    if (!Identity::IsValidTID(tid)) \
    { \
        Logger::LogWarning(LOGSOURCE, "Function \cd" + __FUNCTION__ + "\cj - Invalid player TID: " + str(tid)); \
        return; \
    }