#ifdef __IMPORTED__
    #error This file must be #included.
#endif

// Verify the sync id has not reached an out-of-bounds value.
// Note, to avoid issues we inline the variables, or they have a chance to not be correct.
#define VERIFY_SYNCID(syncId, high, length) \
    int highInline = high; \
    int lengthInline = length; \
    int low = highInline - lengthInline; \
    if (low > syncId) \
    { \
        Logger::LogError(LOGSOURCE, FormatLog(SYNC_CATEGORY, "Sync system function '\cd" + __FUNCTION__ + "\cj' has an out of bounds sync value. Current sync id \cd" + str(syncId) + "\cj is below low limit of (\cd" + str(highInline) + "\cj - \cd" + str(lengthInline) + "\cj) = \cd" + str(low) + "\cj.")); \
    } \
    else \
    { \
        Logger::LogDebug(LOGSOURCE, FormatLog(SYNC_CATEGORY, "Sync system function '\cd" + __FUNCTION__ + "\cj' id is now \cd" + str(low) + "\cj <= \cd" + str(syncId) + "\cj <= \cd" + str(highInline) + "\cj.")); \
    }