#ifdef __IMPORTED__
    #error This file must be #included.
#endif

#include "clientside/clientsettings.acs"
#include "clientside/radio.acs"
#include "clientside/tip.acs"
#include "shared/reward.acs"
#include "shared/powers.acs"
#include "shared/items.acs"
#include "shared/weaponspawners.acs"

strict namespace IO
{
    internal void ParseModDefLumpsServerside()
    {
        ACS_NamedExecuteWithResult(SCRIPT_PARSE_PERSISTING_MOD_DEFS_SERVERSIDE, 0);
    }

    internal void ParseModDefLumpsClientside()
    {
        ACS_NamedExecuteWithResult(SCRIPT_PARSE_PERSISTING_MOD_DEFS_CLIENTSIDE);
    }

    // NOTE: This script is `BUSY` and will not trigger a runaway error.
    script SCRIPT_PARSE_PERSISTING_MOD_DEFS_SERVERSIDE BUSY
    {
        if (ZH2Game::PersistingGameContext.ParsedModDefServerside)
            terminate;

        Logger::LogDebug(LOGSOURCE, "Begin parsing mod def lumps serverside.");

        int startIndex = 0;
        while(startIndex != -1)
            startIndex = DoParseModDefLumps(startIndex, true);

        Logger::LogDebug(LOGSOURCE, "Finished parsing mod def lumps serverside.");

        ZH2Game::PersistingGameContext.ParsedModDefServerside = true;
    }

    // NOTE: This script is `BUSY` and will not trigger a runaway error.
    script SCRIPT_PARSE_PERSISTING_MOD_DEFS_CLIENTSIDE BUSY
    {
        if (ZH2Game::PersistingGameContext.ParsedModDefclientside)
            terminate;

        Logger::LogDebug(LOGSOURCE, "Begin parsing mod def lumps clientside.");

        int startIndex = 0;
        while(startIndex != -1)
            startIndex = DoParseModDefLumps(startIndex, false);

        Logger::LogDebug(LOGSOURCE, "Finished parsing mod def lumps clientside.");
        ZH2Game::PersistingGameContext.ParsedModDefclientside = true;
    }

    internal int DoParseModDefLumps(int startIndex, bool isServerside)
    {
        startIndex = LumpOpen(MOD_DEF_LUMP_NAME, startIndex);
        if (startIndex == -1)
        {
            Logger::LogDebug(LOGSOURCE, "No more mod def lumps found.");
            return startIndex;
        }

        Logger::LogDebug(LOGSOURCE, "Found mod def lump: \cd" + (str)LumpGetInfo(startIndex, LUMP_INFO_NAME) + "\cj.");
        if (LumpGetInfo(startIndex, LUMP_INFO_SIZE) == 0)
        {
            Logger::LogDebug(LOGSOURCE, "Mod def file is empty.");
            return startIndex;
        }

        ParseModDefLump(LumpReadString(startIndex, 0), isServerSide);
        LumpClose(startIndex);
        return startIndex;
    }

    internal void ParseModDefLump(str buffer, bool isServerside)
    {
        int handle = Tokenizer::RentTokenizer(buffer);
        if (handle == -1)
        {
            Logger::LogError(LOGSOURCE, __FUNCTION__ + ": failed to rent a tokenizer.");
            return;
        };

        Tokenizer::Next(handle, false);

        while(Tokenizer::CanRead(handle))
        {
            str symbol = Tokenizer::GetSymbol(handle);

            //Logger::LogDebug(LOGSOURCE, "\cd" + MOD_DEF_LUMP_NAME + "\cj symbol: \cd" + symbol + "\cj.");

            if (isServerside)
            {
                if (Tokenizer::ParseBodyAsEmpty(handle, symbol, "requestedclientsettings")
                    || Tokenizer::ParseBodyAsEmpty(handle, symbol, "radio")
                    || Tokenizer::ParseBodyAsEmpty(handle, symbol, "tips"))
                    continue;

                // Note, blood severity is a serverside thing on weapons, so items must be parsed here.
                if (ParsePowers(handle, symbol)
                    || ParseItems(handle, symbol)
                    || ParseRewards(handle, symbol)
                    || ParseWeaponSpawners(handle, symbol))
                    continue;
            }
            else
            {
                if (ParseRequestedClientSettings(handle, symbol)
                    || ParseRadio(handle, symbol)
                    || ParseTips(handle, symbol))
                    continue;

                if (Tokenizer::ParseBodyAsEmpty(handle, symbol, "weaponspawners"))
                    continue;

                // As powers consists of shared data, parsing them in an offline game only has to be done serverside.
                // The items are also parsed clientside online since the whole system for the inventory and such rely on it.
                if (IsNetworkGame()
                    && (ParsePowers(handle, symbol)
                    || ParseItems(handle, symbol)
                    || ParseRewards(handle, symbol)))
                    continue;

                if (!IsNetworkGame()
                    && (Tokenizer::ParseBodyAsEmpty(handle, symbol, "powers")
                    || Tokenizer::ParseBodyAsEmpty(handle, symbol, "items")
                    || Tokenizer::ParseBodyAsEmpty(handle, symbol, "rewards")))
                    continue;
            }

            Tokenizer::SetErrored(handle, "Unknown symbol whilst parsing " + MOD_DEF_LUMP_NAME + " (serverside: " + (isServerside ? "true" : "false") + "): '" + symbol + "'.");
            break;
        }

        Tokenizer::ReturnTokenizer(handle);
    }
}